### ISSUE TITLE
Update Open Liberty's MP metrics docs to include new Simple Timer metric and REST stat metrics as part of metrics-2.3

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/docs#1109]
This is for the **20.0.0.4 release**!
Includes a quick fix for the `mpMetrics-2.2` release

Update **File 1**:
https://openliberty.io/docs/ref/general/#metrics-catalog.html
- Include the new type of runtime provided REST stat metrics
- See https://github.com/eclipse/microprofile-metrics/issues/293

| MPMETRICS-2.X NAME | MPMETRICS-2.X PROMETHEUS NAME(S) | TYPE| DESCRIPTION | FEATURE(S) REQUIRED |
| ------------- | ------------- | ------------- | ------------- | ------------- |
| REST.request |  base_REST_request_total{class="<fully_qualified_class_name>",method="<method_signature>"}  base_REST_request_elapsedTime_seconds{class="<fully_qualified_class_name>",method="<method_signature>" | SimpleTimer | The number of invocations and total response time of this RESTful resource method since the start of the server. | [mpMetrics-2.3](https://openliberty.io/docs/ref/feature/#mpMetrics-2.3.html) | 
| cpu.processCpuTime / (nanoseconds)|  base_cpu_processCpuTime_seconds| Gauge| Displays the CPU time used by the process on which the Java virtual machine is running. | [mpMetrics-2.2](https://openliberty.io/docs/ref/feature/#mpMetrics-2.2.html) and [monitor-1.0](https://openliberty.io/docs/ref/feature/#monitor-1.0.html) | 

**ALSO with existing metrics, need to add in addition the mpMetrics-2.3 feature availability. OR if we're directly replacing the `mpMetrics-2.2` with `mpMetrics-2.3` then we need to remove mentions of `monitor-1.0`. In `mpMetrics-2.3` the feature will also directly/explicitly start `monitor-1.0` now.

**Note: cpu.processCpuTime was missed from the 2.2 release.

Update **File 2**:
https://openliberty.io/docs/ref/general/#microservice_observability_metrics.html
- Introduce the new type of Simple Timer metric
- See https://github.com/eclipse/microprofile-metrics/issues/496

```
Simple Timers (New in 2.3)
Simple Timer metrics tracks the elapsed timing duration and invocation counts. This is a light-weight alternative to the peformance heavy Timer metric.

@SimplyTimed
This annotation is used for marking a method, constructor, or type as a SimplyTimed.  The simple timer tracks how frequently the annotated object is invoked and tracks how long the invocations take to complete:

@GET
@Path("/weather");
@SimplyTimed(name = "weatherSimplyTimed", displayName="Weather data", description="Provides weather data in JSON")
public JSON getWeatherData() {
    retrieveWeatherData();
}
```

**Comment by Channyboy** [comment]
related open-liberty tracking issue: https://github.com/OpenLiberty/open-liberty/issues/10947

**Comment by Charlotte-Holt** [comment]
@Channyboy Updates for this at 
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microservice-observability-metrics.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics-catalog.html

Please review and let me know if additional updates are necessary. Thanks!

**Comment by Channyboy** [comment]
Looks good!

```
base_REST_request_total{class="<fully_qualified_class_name>",method="<method_signature>"} base_REST_request_elapsedTime_seconds{class="<fully_qualified_class_name>",method="<method_signature>"}
```

I caught a mistake I made, i forgot to add the metric unit to the second metric for `REST.request`

```
base_REST_request_total{class="<fully_qualified_class_name>",method="<method_signature>"} 

base_REST_request_elapsedTime_seconds{class="<fully_qualified_class_name>",method="<method_signature>"} / (seconds)
```

Is it possible to add a space inbetween the two metrics like the updated sample i provided above? Not sure if it also translates properly on the page.

One small concern is that is there a way to indicate at which version a metric was introduced? I'm not sure if there's a a good way to do that?

**Comment by Charlotte-Holt** [comment]
@Channyboy Made those additional updates you suggested in https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics-catalog.html. 

We're currently working on moving the docs into the Antora framework, and with this move, we'll be able to do versioning with a version selector in each topic, so I think this would be a case where the `REST.request` metric is available in the 20.0.0.4 and later doc, and the 20.0.0.3 and earlier doc doesn't have this row in the table. (Same thing for the Simple Timer section of https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microservice-observability-metrics.html.)

**Comment by Channyboy** [comment]
Looks good!

**Comment by Charlotte-Holt** [comment]
These updates are live at 
- https://openliberty.io/docs/ref/general/#microservice-observability-metrics.html
- https://openliberty.io/docs/ref/general/#metrics-catalog.html
