### ISSUE TITLE
Examples for OpenShift service account authentication via Social Login 1.0

### ISSUE THREAD

**Issue by ayoho** [OpenLiberty/docs#1118]
https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html

Add the following examples to the bottom of the existing set of examples.

The `socialLogin-1.0` feature can be configured to use OpenShift service accounts to authenticate and authorize protected resource requests. This allows server administrators to secure, for example, monitoring and metrics endpoints that might produce sensitive information but require repeated access by an automated process or non-human entity. This allows service accounts to authenticate themselves by providing in the request a service account token that was created within the OpenShift cluster.

The minimum configuration requires only that an `<okdServiceLogin>` element be specified:

  ```XML
  <server>

  <!-- Enable features -->
  <featureManager>
    <feature>socialLogin-1.0</feature>
  </featureManager>

  <okdServiceLogin />

  </server>
  ```
  
The minimum configuration assumes that the Liberty server is packaged and deployed within an OpenShift cluster. By default, the `<okdServiceLogin>` element will be used to authenticate all protected resource requests that the Liberty server receives.

Incoming requests to protected resources must include a service account token. The token must be specified as a bearer token in the `Authorization` header of the request. The Liberty server will use the service account token to query information about the associated service account from the OpenShift cluster. The OpenShift project that the service account is in will be used as the group for the service account when making authorization decisions. Similarly, the name of the service account will be used as the user name.

If the Liberty server is not deployed within an OpenShift cluster, the `userValidationApi` attribute should be configured and set to the value for the appropriate User API endpoint in the OpenShift cluster:

  ```XML
  <okdServiceLogin userValidationApi="https://cluster.domain.example.com/apis/user.openshift.io/v1/users/~" />
  ```

  Multiple `<okdServiceLogin>` elements can be configured as long as each element has a unique `id` attribute specified. In those cases, authentication filters should also be configured to ensure the appropriate endpoints are protected by a unique `<okdServiceLogin>` instance.

**Comment by ayoho** [comment]
- Start the first sentence of the article with "The" to make it "The Social Media Login feature provides a form of single sign-on..."
- The first sentence under the "Request log in with a social media ID" section says
    > A customizable selection form is presented so the user can choose which provider they prefer to sign in with.

    The customizable selection form doesn't come into play if there's just one social media provider configured, as is the case in this section. I'd suggest removing this sentence.

    I'd change the first sentence to be something like
    > The Social Media Login feature provides a set of built-in configuration elements for popular social media providers in addition to generic configuration elements to support arbitrary social media providers.

- I think the "Provide a choice of social media providers to the user" section should say:
    > You can configure multiple social media providers to allow users to choose the provider they want to sign in with. A customizable selection form that shows all of the available providers to sign with is presented to the user before authentication. The following example presents the user with the choice of Google, GitHub, Facebook, LinkedIn, and Twitter with which to log in:

- The "Request log in with a social media ID only if the users is also in another registry" section is misleading. I'd suggest renaming this section to something like "Require authenticated users to also be present in the configured registry"
    > You can restrict the presentation of a social media provider to only users who are also in another configured registry.

    The `mapToUserRegistry` attribute doesn't "restrict presentation of a social media provider to only users who are also in another configured registry." That attribute will allow access to a protected resource only if the user information returned from the social media provider can be mapped to an existing user in the configured user registry.

    I'd suggest changing this section to say:
    > Require authenticated users to also be present in the configured registry
    > 
    > You can further restrict access to your protected resource by requiring the user returned from the social media provider to also exist in the configured user registry. For example, use the `mapToUserRegistry` attribute to configure your app so that users must authenticate through Google and also be verified as an existing user in the company LDAP registry:

**Comment by ayoho** [comment]
Doc looks fine to me.

**Comment by lauracowen** [comment]
@ManasiGandhi Can you provide a link to where this is? I don't see it in the [Social Media Login gendoc topic](https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#socialLogin-1.0.html) so I'm not sure what's been reviewed already.

**Comment by ManasiGandhi** [comment]
@lauracowen here is the link to the draft https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#socialLogin-1.0.html

**Comment by Charlotte-Holt** [comment]
@lauracowen Manasi mentioned to me that she added the last two examples, so I think those are the two that need review. 

@ManasiGandhi Peer review feedback:

- You could link, "...use an authentication filter." to this topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authentication-filters-specifying-mechanism.html. 
- In, "...MicroProfile JWT (mp-jwt) feature.", I don't think you need "(mp-jwt)". Instead, I'd make "MicroProfile JWT feature" the link text. 
- I'd update, "For more information, see `authFilter`." to say something like, "For more information, see the `authFilter` configuration element." Just to give it a little more context. 
- I'd suggest updating a few things in the last example to read something like:
"To authenticate with a social media provider that isn't configured out-of-the-box with Open Liberty, use the `oauth2Login` element (for OAuth providers) or the `oidcLogin` element (for OpenID Connect providers). These elements supply the configuration details that are needed to work with the provider. These details can usually be obtained from the social media provider’s developer instructions. The following example configures Instagram as the social media provider:"

**Comment by lauracowen** [comment]
- I just read through @ayoho 's [feedback](https://app.zenhub.com/workspaces/open-liberty-docs-backlog-5c7031f61d4580192beb4070/issues/openliberty/docs/1118#issuecomment-637095899) - can you implement his suggestions throughout this topic, pls? I know that's not related to what you were doing but he makes some useful points about wording that is maybe not quite accurate as it currently stands.
- @ManasiGandhi The two last examples shown on the draft site were already in the published topic. I think something hasn't built correctly because I'm not seeing any examples about okd configuration (as described at the top of this issue). Can you take a look and make sure the files have merged into `draft` branch and are building correctly?

**Comment by ManasiGandhi** [comment]
@lauracowen I worked on your suggestions. There was a problem building some things. I made those additions again. I worked on @ayoho 's recommendations [here](https://github.com/OpenLiberty/docs/issues/1118#issuecomment-637095899)  previously and he signed them off [ here](https://github.com/OpenLiberty/docs/issues/1118#issuecomment-641481974). Can you review the draft https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#socialLogin-1.0.html?

**Comment by lauracowen** [comment]
@ManasiGandhi Thanks. I see your new section now.

- However, Adam's changes aren't shown in this built file so I think they must also have been lost at the same time. Unless you have a copy of your old file locally, I think you'll need to make them again.
- BTW, Adam's comments about the first sentence in the topic, you can't make those changes in the file you're working in (you'll have noticed that that's generated as part of the original file that you're only augmenting). So please can you create a separate issue on the OL docs backlog (and paste the number in a comment in here) with those comments in them and state that they need to be made in the feature metatype file? We can address that separately then (the changes have to be made in a properties file in a different Github repo).

New section
- Needs a descriptive heading like the other sections.
- Follow the style/approach of the other sections. This section should not be instructional. It should be providing a minimal (as possible) example config snippet and explanation of what it shows.
  - eg It shouldn't include the `<server>...` tags, or the `<featureManager>...` lines. The example for how to enable the feature is shown at the top of the file (part of the generated file).
- The text and examples at the top of this issue are not provided to paste in as-is. You need to extract the relevant information from it. Then, based on the approach you can see in this and other similar topics, and on the [guidance](https://ibm.ent.box.com/notes/608240270119), construct a section to do the same for when you're configuring the social media login feature on openshift.

**Comment by lauracowen** [comment]
I don't see the changes requested above in the built file: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/socialLogin-1.0.html

Also can you list the changes made in a comment when you've done them so it's easy to see what's been changed and whether/how you addressed each comment (eg if you disagree or have a better suggestions, mention it in the comment so it doesn't look like you just accidentally missed it)?

**Comment by ManasiGandhi** [comment]
@lauracowen Here are the updates (Draft link https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/socialLogin-1.0.html),

@ayoho suggestions 

- [X] Start the first sentence of the article with "The" to make it "The Social Media Login feature provides a form of single sign-on..." ( Created a separate issue on the OL docs backlog- #1979 )

- [X] The first sentence under the "Request log in with a social media ID" section says

   ` A customizable selection form is presented so the user can choose which provider they prefer to sign in with.
`
The customizable selection form doesn't come into play if there's just one social media provider configured, as is the case in this section. I'd suggest removing this sentence.

I'd change the first sentence to be something like

    `The Social Media Login feature provides a set of built-in configuration elements for popular social media providers in addition to generic configuration elements to support arbitrary social media providers.` 

- [x] I think the "Provide a choice of social media providers to the user" section should say:

   `You can configure multiple social media providers to allow users to choose the provider they want to sign in with. A customizable selection form that shows all of the available providers to sign with is presented to the user before authentication. The following example presents the user with the choice of Google, GitHub, Facebook, LinkedIn, and Twitter with which to log in:` 

- [x] The "Request log in with a social media ID only if the users is also in another registry" section is misleading. I'd suggest renaming this section to something like "Require authenticated users to also be present in the configured registry"

    You can restrict the presentation of a social media provider to only users who are also in another configured registry.

`The mapToUserRegistry attribute doesn't "restrict presentation of a social media provider to only users who are also in another configured registry." That attribute will allow access to a protected resource only if the user information returned from the social media provider can be mapped to an existing user in the configured user registry.
`
I'd suggest changing this section to say:

    Require authenticated users to also be present in the configured registry

    `You can further restrict access to your protected resource by requiring the user returned from the social media provider to also exist in the configured user registry. For example, use the mapToUserRegistry attribute to configure your app so that users must authenticate through Google and also be verified as an existing user in the company LDAP registry:

Changes requested by you 

- [x] Needs a descriptive heading like the other sections. 

- [x] Follow the style/approach of the other sections. This section should not be instructional. It should be providing a minimal (as possible) example config snippet and explanation of what it shows.

    eg It shouldn't include the <server>... tags, or the <featureManager>... lines. The example for how to enable the feature is shown at the top of the file (part of the generated file). 

- [x] The text and examples at the top of this issue are not provided to paste in as-is. You need to extract the relevant information from it. Then, based on the approach you can see in this and other similar topics, and on the guidance, construct a section to do the same for when you're configuring the social media login feature on openshift.



`

**Comment by lauracowen** [comment]
Thank you for rescuing/re-creating all the missing updates to this! They look good, thanks for applying all the updates to the rest of the topic as well as this OpenShift bit - it looks better now.

Nice intro to the OpenShift section.

Some comments:
- Can you remove "To configure the socialLogin-1.0 feature, specify the okdServiceLogin element." - that goes without saying. Just say "The following example shows how to configure the Social Media Login feature to use OpenShift service accounts as a single sign-on provider:" (if that's technically accurate way to say it)
- "The OpenShift project is used as the group " - I'm not sure what this means - what is "the OpenShift project"?
- In general, can you avoid using "thus" as it's a bit archaic. I can't remember what the IBM style guidance is around that but I think it generally advises against using archaic terms.

**Comment by ManasiGandhi** [comment]
@lauracowen Thanks for your review. I worked on your suggestions:

- [x] Can you remove "To configure the socialLogin-1.0 feature, specify the okdServiceLogin element." - that goes without saying. Just say "The following example shows how to configure the Social Media Login feature to use OpenShift service accounts as a single sign-on provider:" (if that's technically accurate way to say it)- I checked with Adam Yoho and he said it's technically accurate.

- [x] "The OpenShift project is used as the group " - I'm not sure what this means - what is "the OpenShift project"?

- [x] In general, can you avoid using "thus" as it's a bit archaic. I can't remember what the IBM style guidance is around that but I think it generally advises against using archaic terms

**Comment by lauracowen** [comment]
Ah I understand now. Thanks for the updates. Signing off now.

**Comment by ManasiGandhi** [comment]
New link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/feature/socialLogin-1.0.html

**Comment by ManasiGandhi** [comment]
@chirp1 Updated link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/socialLogin-1.0.html.

**Comment by ManasiGandhi** [comment]
@chirp1 20.12 updated  link https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/socialLogin-1.0.html.

**Comment by dmuelle** [comment]
Hi Manasi- I came across this while reviewing [Richard's Active Directory example](https://github.com/OpenLiberty/docs/issues/2075) on the same page. I think it needs a few edits:

- per lauras comment above, remove reference to "The socialLogin-1.0 feature.." as it is inferred. You can start the example by telling the user they can configure OpenShift service accounts as an authentication provider.
- to make the example title more concise and parallel with Richards example, you could simplify it to be: "Use an OpenShift service account as an authentication provider"
- the subject and verb are split in this sentence, making it hard to read:
"With this configuration, server administrators can secure endpoints, for example, monitoring and metrics endpoints, that might produce sensitive information."
you could make it more clear by joining subject and verb (and removing might...)
"With this configuration, server administrators can secure endpoints that produce sensitive information, such as monitoring and metrics endpoints."
-  I found this sentence confusing:
"The service accounts can authenticate themselves by providing a service account token that was created within the OpenShift cluster in the request."
 I think because of the placement of "...in the request" makes it difficult to tell what the clause modifies (the cluster or the token) . Maybe:
 ""The service accounts can authenticate requests to an endpoint by including  a service account token that was created within the OpenShift cluster."
 - I think the sentence that introduces the example should provide a little more info, especially since the config is so minimal. Something like:
 "You can configure the Social Media Login feature to use OpenShift service accounts as a single sign-on provider by specifying the `okdServiceLogin` element, as shown in the following example:"

 - I also think you should include more of the info Adam initially provided, particularly this:

>  The minimum configuration assumes that the Liberty server is packaged and deployed within an OpenShift cluster. By default, the <okdServiceLogin> element will be used to authenticate all protected resource requests that the Liberty server receives.

> Incoming requests to protected resources must include a service account token. The token must be specified as a bearer token in the Authorization header of the request. The Liberty server will use the service account token to query information about the associated service account from the OpenShift cluster. The OpenShift project that the service account is in will be used as the group for the service account when making authorization decisions. Similarly, the name of the service account will be used as the user name.

you already have some of this info, but including a little more might help the user troubleshoot. 

- it might be helpful to include a link to the OCP doc, like Richard has for the Active Directory example. I think the following link would work for info on service accounts: https://docs.openshift.com/container-platform/latest/authentication/understanding-and-creating-service-accounts.html
