### ISSUE TITLE
Add new rule to JAX-RS 2.0 behavior changes

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/docs#1156]
Add a new bullet to this page:  https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_jaxrs_behavior.html

- In JAX-RS 1.1 multiple url-patterns could be specified for each JAXRS servlet.   For example:
[web-xml-snippet1.txt](https://github.com/OpenLiberty/docs/files/4263618/web-xml-snippet1.txt)

In JAX-RS 2.0 each servlet definition can have just a single url-pattern defined.  Multiple url-pattern definitions will now require multiple servlet definitions.  For example:

[web-xml-snippet2.txt](https://github.com/OpenLiberty/docs/files/4263638/web-xml-snippet2.txt)

**Comment by Charlotte-Holt** [comment]
https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_jaxrs_behavior.html isn't relevant to OL, as 1.1 isn't in OL.

**Comment by Charlotte-Holt** [comment]
Created this in the liberty repo: https://github.ibm.com/was-liberty/liberty-docs/issues/2125.
