### ISSUE TITLE
Add links from the MP intro topic to the relevant concept topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1162]
We've now got several intro/conceptual topics about the main capabilities that are represented in MicroProfile (eg observability and metrics, resiliency, rest clients). Can we provide links embedded in the relevant sections of the [MicroProfile intro topic](https://openliberty.io/docs/ref/general/#microprofile.html) to each of the concept topics that exists so far (not all will have one yet). This intro topic gives a taster but doesn't really explain the concepts in much detail, so links to more detail would be useful. And would also help guide visitors into the docs.

**Comment by Charlotte-Holt** [comment]
Add "Guide:" prefix to the guide links, too

**Comment by dmuelle** [comment]
Added links to each section- I did not add the "Guides:" prefix as the intro text for each link already identifies that the destination is a guide

**Comment by dmuelle** [comment]
changes on vnext with #4175
