### ISSUE TITLE
Doc Weld diagnostic tool

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1182]
As mentioned in https://developer.ibm.com/wasdev/blog/2016/06/30/beta-websphere-liberty-and-tools-july-2016/
It's a really helpful tool.

SME: Andy Guibert

**Comment by Charlotte-Holt** [comment]
https://github.ibm.com/was-WASdev/WASdevnet-website/tree/master/developer.ibm.com/wasdev/blog/2016/06/30/beta-websphere-liberty-and-tools-july-2016
