### ISSUE TITLE
Example config for MP OpenAPI feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1196]
For this issue, we need to determine if a config snippet is needed for the MP OpenAPI feature (it may not be). If it is, we need to find the most useful example(s) to include in the feature doc.

**Comment by dmuelle** [comment]
Checked with @arthurdm to see if config examples were needed

**Comment by dmuelle** [comment]
After talking w/ Laura and Karen about Arthur's feedback, closing this issue
