### ISSUE TITLE
Configuring a JAAS custom login module for Liberty document issue

### ISSUE THREAD

**Issue by liusophie** [OpenLiberty/docs#1240]
In this document:
Configuring a JAAS custom login module for Liberty
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_jaas.html

Step #1: Enable the **appSecurity-3.0** Liberty feature in the server.xml file.
<featureManager>
    <feature>**appSecurity-2.0**</feature>
</featureManager>

Please clarify if appSecurity-3.0 or appSecurity-2.0 should be enabled, and correct the documents. 
Thanks.

**Comment by una-tapa** [comment]
**Sophie**
Thanks for opening the issue.  Please work with doc team to verify the change. 

**Doc team**
Please refer to Slack discussion confirmed by dev here. 
https://ibm-cloud.slack.com/archives/C324NP6H5/p1584546698169400 

Both appSecurity-3.0 and appSecurity-2.0 supports JAAS module.  It would be great fi we can  keep 2.0 in the server.xml example and mention in the sentence that both 2.0 and 3.0 works.  

Majority of users can do with 2.0.  If we only mention 3.0, it will give them unnecessary concerns. 

Thanks!

**Comment by dmuelle** [comment]
@una-tapa would this update be acceptable?

`Enable the Liberty Application Security feature, version 2.0 or later, in the server.xml file.` 

That way the doc won't need to be updated if another version of appSec is released in the future.

If not, I can change it to

`Enable the appSecurity-2.0  or appSecurity-3.0 Liberty feature in the server.xml file.`

Let me know which is preferred, thanks

**Comment by dmuelle** [comment]
@una-tapa @liusophie please review the draft update on our preprod site:

https://www-03preprod.ibm.com/support/knowledgecenter/en/SSAW57_liberty_temp/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_jaas.html

Let me know if it looks ok or needs further edits. These changes will go public w/ Liberty 20.0.0.4

Thanks!

**Comment by una-tapa** [comment]
Looks great thanks!

**Comment by dmuelle** [comment]
You're welcome! Closing this issue
