### ISSUE TITLE
MP Config 1.4 blog post content

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/docs#1268]
This should be included in the 20.0.0.4 blog post...

Content will be here: https://github.com/OpenLiberty/open-liberty/issues/10794

**Comment by chirp1** [comment]
See the blog post to see what information to document for MP config 1.4. This MP config 1.4 information is in addition to the MP config information in this WebSphere Liberty topic: https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_microprofile_overview.html This topic includes information for mpConfig-1.1, 1.2 and 1.3.

**Comment by Charlotte-Holt** [comment]
Link to blog post: https://openliberty.io/blog/2020/04/09/microprofile-3-3-open-liberty-20004.html#conf

**Comment by Charlotte-Holt** [comment]
Related to #1495. Need to work out what's important from the KC topics. Contact Scott Kurz.
