### ISSUE TITLE
Example config for JCache Session Persistence feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1290]
Example config for the `sessionCache-1.0` feature: https://openliberty.io/docs/ref/feature/#sessionCache-1.0.html

**Resources**:
- https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_session_persistence_jcache.html

It might be worth searching the KC for other examples that you can dig up before reaching out to an SME.

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi Looking good. Review comments: 

- Maybe change the heading "Configuring Liberty servers to persist session data with JCache" to "Configuring Open Liberty to persist session data with JCache"?
- I don't think JCache needs to be monospaced. Most of what I'm finding online is just "JCache"
- "After enabling" to "After you enable"
- Add a colon at the end of the sentence to lead to your example
- I'm a little confused by this sentence: "You can specify JCache vendor configuration by specifying a provider-specific URI, provider-specific properties, or Specify provider-specific system properties." Should it be "You can specify JCache vendor configuration by specifying a provider-specific URI, provider-specific properties, or provider-specific system properties."? Is there a difference between provider-specific properties and provider-specific system properties? There may be, but just checking! 
- Maybe update "Following is an example to configure session persistence by using Hazelcast as the JCache provider:" to "The following example configures session persistence with Hazelcast as the JCache provider:"
- I'd try to tie the info about the clone ID into the other example, because right now it feels a little disjointed when I read it. I think first highlight why someone would want to do that and when it's useful, and then explain how with the additional information. 
- "option" after `--clean` doesn't need to be monospaced
- ${wlp.user.dir}/servers/s1/bootstrap.properties and ${wlp.user.dir}/servers/s2/bootstrap.properties do need to be monospaced
- I'd add a colon after "Specify unique variables in the bootstrap.properties file of each server"
- Do we need this here at all: "Synchronize the system clocks of all computers that host Liberty servers. If the system clocks are not synchronized, session invalidation can occur prematurely."? It seems just kind of tacked onto the end. If it's important info, can we try to contextualize it a little bit? Maybe work in into the details above, or add another sentence about how it ties into the examples?

**Comment by aguibert** [comment]
Review comments:
- In the code examples I would suggest using `${server.config.dir}` instead of `${shared.resource.dir}`. This is because usually there is only 1 server per wlp install in modern (containerized) environments and the shared resource dir really only makes sense if you have >2 servers per wlp install.
- For the 3rd (largest) code example, I would suggest only showing the minimum configuration that the accompanying text is talking about, which would look like this:
```xml
  <httpSessionCache libraryRef="jCacheVendorLib"
                    uri="file:${shared.resource.dir}/hazelcast/hazelcast.xml"/>

  <httpSession cloneId="${cloneId}"/>
```
Alternatively, you could reword the text to frame the code example as an "all together" view of the config (which is useful to readers too).
- The text `If you configure multiple servers to persist session data to the same database` is incorrect, with JCache there is no database involved, it's all just in-memory replication.
- The text `The clone ID is specified in step 2.` doesn't make sense because I don't see any numbered steps on this page

**Comment by aguibert** [comment]
looks good now, thanks!

**Comment by ManasiGandhi** [comment]
@lauracowen can you review https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#sessionCache-1.0.html?

**Comment by lauracowen** [comment]
The format of this needs to be modified to follow the same approach as other config example topics. The aim is to show one or more alternative examples of server config; it's not to try to provide instructional/task information about how to do a full configuration. If there's a need for a full task topic on configuring JCache, raise a separate issue to be prioiritised on the backlog.

From the text shown in this topic, and from what (I think) @aguibert says above, I don't think these are two separate config examples. They don't look like alternatives; they look like two parts of the same config? If they are two parts of the same config, they should be a single code example. Then the text should describe what the examples provide, not step-by-step instructions.

- Collapse the two code examples into one (starting from `<library id=...` and ending with the `<httpSession cloneID=...` line).
- Within the code example, don't use variables. These are examples by definition so it's fine (and in fact clearer) to use hardcoded values, as long as you explain what those values represent in the description that follows the code example. So...
  - Find out a typical installation location of Hazelcast (eg `/usr/hazelcast`???) and use that in both places.
  - for the value of `cloneId`, make it `server1` unless there's a better value.
  - Remove the whole last part from "Specify unique variables..." (including the two bootstrap.properties examples) because we're not explaining how to do that here; that's something you can do with any server config in Open Liberty and it's explained elsewhere.

This example shows how to configure JCache to use Hazelcast as the JCache provider. We don't need to offer alternatives because this is just an example.

So format the topic something like:

>== Persisting session data with JCache and Hazelcast
>The following example shows how to persist session data with Hazelcast as the JCache provider:
>`config example here`
>The `library` element defines a library that points to the location of your JCache provider. The JCache provider in this example is Hazelcast, which is located in a JAR file called `hazelcast.jar` in the Hazelcast installation directory(??). A clone ID is xxxxx (what is it? or would that be obvious to someone configuring session caching?) and is unique for each server. In the example, the clone ID is `server1`, which matches the clone ID shown in (where?). Additional Hazelcast configuration is provided in the `hazelcast.xml` file.

I think that's all we need here. I don't understand from the text what happens in production if the server is started with the `--clean` option if you've already assigned it manually. I think we can just describe the production scenario here. Or, if it's important to provide the developer experience as well, we can flag that up in an additional sentence.

We will have a separate concept/intro topic to session caching, which can explain more about clone IDs and any other concepts. And, if necessary, we can also have a separate task/procedural topic on how to configure session caching if there's more to it than just the server config.

**Comment by ManasiGandhi** [comment]
@rw2513 Can you peer review this draft https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#sessionCache-1.0.html?

**Comment by lauracowen** [comment]
Thanks. Just some formatting to clean up now:

- Can you change the heading to the heading I suggested (all these topics are about configuring Liberty services so it's redundant to say so, and the important bit here is that you're configuring session persistence with Hazelcast as the JCache provider so Hazelcast should be mentioned).
- Can you clean up the XML to get rid of the spaces on the left of each tag but make sure the `fileset` element is still indented to show it's nested; get rid of the unnecessary blank link between the first and second lines of XML.
- Something's gone wrong with the syntax in the last sentence (some dodgy backticks, I think). Can you make sure to check for this sort of thing in the draft site when it's built.
- `hazelcast.jar` isn't the directory name - that's the library for the provider, which is in the `hazelcast` directory.

**Comment by Rwalls1** [comment]
## Peer review
- Make sure to run Acrolinx again, I noticed a few things were flagged.
- I think you should change "Following is an example to configure session persistence by using Hazelcast as the JCache provider:” to “The following example shows the configuration of session persistence by using Hazelcast as the JCache provider” to maintain consistency of example description syntax across topics.

**Comment by ManasiGandhi** [comment]
@lauracowen I made the updates per your review


 

- [x]  hazelcast.jar isn't the directory name - that's the library for the provider, which is in the hazelcast directory.

    

- [x] Can you change the heading to the heading I suggested (all these topics are about configuring Liberty services so it's redundant to say so, and the important bit here is that you're configuring session persistence with Hazelcast as the JCache provider so Hazelcast should be mentioned).

    

- [x] Can you clean up the XML to get rid of the spaces on the left of each tag but make sure the fileset element is still indented to show it's nested; get rid of the unnecessary blank link between the first and second lines of XML.

    

- [x] Something's gone wrong with the syntax in the last sentence (some dodgy backticks, I think). Can you make sure to check for this sort of thing in the draft site when it's built.

**Comment by ManasiGandhi** [comment]
@Rwalls1 I made the edits per your peer review


    

- [x] Make sure to run Acrolinx again, I noticed a few things were flagged.

    

- [x] I think you should change "Following is an example to configure session persistence by using Hazelcast as the JCache provider:” to “The following example shows the configuration of session persistence by using Hazelcast as the JCache provider” to maintain consistency of example description syntax across topics.

**Comment by lauracowen** [comment]
Looks good, thanks. Two last things then I can sign it off:

- The wrong language is specified for the XML source code example (in the asciidoc source it says "java"). Can you fix that so that the syntax highlighting displays correctly in the example?
- I think the wording of "by using" in the first sentence is a bit odd because it's not configured by using Hazelcast as the provider. It's actually showing what the configuration is like _when_ using Hazelcast as the provider. Is "by using" a recommended style (I keep seeing it when reviewing some of these topics)? I think "when using" is more appropriate here - but maybe see what @chirp1 says.

**Comment by ManasiGandhi** [comment]
@chirp1 updated draft link https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/sessionCache-1.0.html

**Comment by dmuelle** [comment]
need to replace `${server.config.dir}` variable with an example (use `server1` for consistency ) per #1877. Once the file is updated, please mark it off from the checklist in that issue- thanks!

**Comment by ManasiGandhi** [comment]
@dmuelle I replaced ${server.config.dir} variable with server1.

**Comment by ManasiGandhi** [comment]
@lauracowen I worked on your suggestions


    

- [x] The wrong language is specified for the XML source code example (in the asciidoc source it says "java"). Can you fix that so that the syntax highlighting displays correctly in the example?

    

- [x] I think the wording of "by using" in the first sentence is a bit odd because it's not configured by using Hazelcast as the provider. It's actually showing what the configuration is like when using Hazelcast as the provider. Is "by using" a recommended style (I keep seeing it when reviewing some of these topics)? I think "when using" is more appropriate here - but maybe see what @chirp1 says.

**Comment by lauracowen** [comment]
Okay, one last change (sorry, I should've caught this before):

"The library element defines a library that points to the location of your JCache provider. The JCache provider in this example is Hazelcast, which is located in the hazelcast.jar library. " -> "The `library` element specifies that the JCache provider to use is Hazelcast, which is located in the `hazelcast.jar` library. "
(Avoid making generic/abstract statements in these topics - just talk directly about what the example shows.)

**Comment by ManasiGandhi** [comment]
@lauracowen I worked on your edit suggestion:

- [x] "The library element defines a library that points to the location of your JCache provider. The JCache provider in this example is Hazelcast, which is located in the hazelcast.jar library. " -> "The library element specifies that the JCache provider to use is Hazelcast, which is located in the hazelcast.jar library. "

(Avoid making generic/abstract statements in these topics - just talk directly about what the example shows.)

**Comment by lauracowen** [comment]
Great, thanks. Signing off.

**Comment by ManasiGandhi** [comment]
New link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/feature/sessionCache-1.0.html

**Comment by ManasiGandhi** [comment]
@chirp1 20.12 updated link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/sessionCache-1.0.html.

**Comment by Rwalls1** [comment]
@ManasiGandhi 
SME: Nathan Mittlestat
Proposed updates from issue #2843:

# Content proposal for config example updates
The following suggested updates are drawn from the "Configuring Infinispan in client/server mode" and "Configuring Infinispan in embedded mode" sections from the planned [Configuring Infinispan as a JCache provider](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.4/configuring-infinispan-support.html) topic.

## Configuring Infinispan in client/server mode with OpenShift
You can configure Infinispan in client/server mode with OpenShift to connect to a remote Infinispan server with Open Liberty to access cached HTTP session data from applications. To configure Infinispan in client/server mode, you can configure the `httpSessionCache` element, as shown in the following example:
```xml
  <httpSessionCache libraryRef="InfinispanLib">
    <properties infinispan.client.hotrod.server_list="infinispan-server:11222"/>
    <properties infinispan.client.hotrod.auth_username="sampleUser"/>
    <properties infinispan.client.hotrod.auth_password="samplePassword"/>
    <properties infinispan.client.hotrod.auth_realm="default"/>
    <properties infinispan.client.hotrod.sasl_mechanism="PLAIN"/>
    <properties infinispan.client.hotrod.java_serial_whitelist=".*"/>
    <properties infinispan.client.hotrod.marshaller="org.infinispan.commons.marshall.JavaSerializationMarshaller"/>
  </httpSessionCache>
    <library id="InfinispanLib">
        <fileset dir="${shared.resource.dir}/infinispan" includes="*.jar"/>
    </library>
```
The `libraryRef` attribute in the `httpSessionCache` element specifies the `“InfinispanLib”` value to reference a shared library to load the Infinispan JAR files.  The `properties` elements that are embedded in the `httpSessionCache` element set the minimum configuration [properties](https://docs.jboss.org/infinispan/11.0/apidocs/org/infinispan/client/hotrod/configuration/package-summary.html) that are needed for the Infinispan Hot Rod client. This configuration uses [PLAIN authentication](https://infinispan.org/docs/dev/titles/hotrod_java/hotrod_java.html#authentication). After you configure Infinispan in client/server mode, you need to start an Infinispan in the OpenShift environment. For more information, see [Configuring Infinispan as a JCache provider](https://draft-openlibertyio.mybluemix.net/docs/latest/configuring-infinispan-support.html).
## Configuring Infinispan in embedded mode with OpenShift
You can configure Infinispan in embedded mode with OpenShift to enable multiple embedded servers to form a cluster that provides high availability of user HTTP session data. Before you configure Infinispan in embedded mode, you need to enable the MicroProfile Reactive Streams and MicroProfile Metrics features in addition to the JCache session persistence feature. To configure Infinispan in embedded mode, you can configure the `httpSessionCache` element, as shown in the following example:
```xml
    <httpSessionCache libraryRef="InfinispanLib" uri="file:${shared.resource.dir}/infinispan/infinispan.xml"/>
    <library id="InfinispanLib">
        <fileset dir="${shared.resource.dir}/infinispan" includes="*.jar"/>
    </library>
</server> 	
```
The `libraryRef` attribute in the `httpSessionCache` element specifies the `“InfinispanLib”` value to reference a shared library to load the Infinispan JAR files. The `uri` attribute specifies the `"file:${shared.resource.dir}/infinispan/infinispan.xml”`value to reference the `Infinispan.xml` file. You must also configure the `infinispan` element to enable clustering, as shown in the following example:
```xml
<infinispan>
  <jgroups>
     <stack-file name="jgroups-kubernetes" path="/default-configs/default-jgroups-kubernetes.xml"/>
  </jgroups>
  <cache-container>
    <transport stack="jgroups-kubernetes" />
  </cache-container>
</infinispan>
```
The `path` attribute in the `stack-file` element specifies the "/default-configs/default-jgroups-kubernetes.xml” value that references the default Kubernetes service that enables clustering in OpenShift. You also have to configure a `service.yaml` file and a `jvm.options` file to configure Infinispan in embedded mode with OpenShift. For more information, see [Configuring Infinispan as a JCache provider](https://draft-openlibertyio.mybluemix.net/docs/latest/configuring-infinispan-support.html).
## Configure Infinispan in embedded mode without OpenShift
You configure Infinispan in embedded mode without OpenShift. You have to enable the MicroProfile Reactive Streams and MicroProfile Metrics features in addition to the JCache session persistence feature. You also must have a shared library for Infinispan. In the following example, the `libraryRef` attribute in the `httpSessionCache` element references a shared library to load Infinispan JAR files from with the `InfinispanLib`:
```xml
<httpSessionCache libraryRef="InfinispanLib”/>
```

**Comment by nmittles** [comment]
Reviewed https://draft-openlibertyio.mybluemix.net/docs/21.0.0.5/reference/feature/sessionCache-1.0.html:
Comments are in the same order as they appear in the doc.


CURRENT: Configuring Infinispan in client/server mode with OpenShift
PROPOSED: Configuring Infinispan in client/server mode on OpenShift

CURRENT: You can configure Infinispan in client/server mode with OpenShift to connect to a remote Infinispan server with Open Liberty to access cached HTTP session data from applications. 
PROPOSED: You can configure Infinispan in client/server mode on OpenShift to connect to a remote Infinispan server with Open Liberty to access cached HTTP session data. 

CURRENT: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library to load the Infinispan JAR files. 
PROPOSED: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library which loads the Infinispan JAR files. 

CURRENT: After you configure Infinispan in client/server mode, you need to start an Infinispan in the OpenShift environment.
PROPOSED: After you configure Infinispan in client/server mode, you need to start an Infinispan server in the OpenShift environment.

CURRENT: Configuring Infinispan in embedded mode with OpenShift
PROPOSED: Configuring Infinispan in embedded mode on OpenShift

CURRENT: You can configure Infinispan in embedded mode with OpenShift to enable multiple embedded servers to form a cluster that provides high availability of user HTTP session data. 
PROPOSED: You can configure Infinispan in embedded mode on OpenShift to enable multiple embedded servers to form a cluster that provides high availability of user HTTP session data.

Suggestion: Make 'MicroProfile Reactive Streams' and 'MicroProfile Metrics' into links for the actual Liberty features?

CURRENT: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library to load the Infinispan JAR files. 
PROPOSED: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library which loads the Infinispan JAR files. 

CURRENT:The uri attribute specifies the file:${shared.resource.dir}/infinispan/infinispan.xml value to reference the Infinispan.xml file.
PROPOSED: The uri attribute specifies the file:${shared.resource.dir}/infinispan/infinispan.xml value to reference the Infinispan configuration file <provide link to Infinispan Declarative Configuration here, https://infinispan.org/docs/11.0.x/titles/configuring/configuring.html#declarative-configuring >.

CURRENT: You must also configure the infinispan element to enable clustering, as shown in the following example:
PROPOSED: In the Infinispan configuration file you must configure the infinispan element to enable clustering, as shown in the following example:

CURRENT: You configure Infinispan in embedded mode without OpenShift.
PROPOSED: <This sentence seems to be missing something? Maybe add the word "can"?> You can configure Infinispan in embedded mode without OpenShift.

Suggestion: Make 'MicroProfile Reactive Streams' and 'MicroProfile Metrics' into links for the actual Liberty features? (second time these features are mentioned)

**Comment by ManasiGandhi** [comment]
@nmittles I worked on your technical review. Here is the draft with updates https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/sessionCache-1.0.html
- [x] CURRENT: Configuring Infinispan in client/server mode with OpenShift
PROPOSED: Configuring Infinispan in client/server mode on OpenShift
- [x] CURRENT: You can configure Infinispan in client/server mode with OpenShift to connect to a remote Infinispan server with Open Liberty to access cached HTTP session data from applications.
PROPOSED: You can configure Infinispan in client/server mode on OpenShift to connect to a remote Infinispan server with Open Liberty to access cached HTTP session data.
- [x] CURRENT: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library to load the Infinispan JAR files.
PROPOSED: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library which loads the Infinispan JAR files.
- [x] CURRENT: After you configure Infinispan in client/server mode, you need to start an Infinispan in the OpenShift environment.
PROPOSED: After you configure Infinispan in client/server mode, you need to start an Infinispan server in the OpenShift environment.
- [x] CURRENT: Configuring Infinispan in embedded mode with OpenShift
PROPOSED: Configuring Infinispan in embedded mode on OpenShift
- [x] CURRENT: You can configure Infinispan in embedded mode with OpenShift to enable multiple embedded servers to form a cluster that provides high availability of user HTTP session data.
PROPOSED: You can configure Infinispan in embedded mode on OpenShift to enable multiple embedded servers to form a cluster that provides high availability of user HTTP session data.
- [x] Suggestion: Make 'MicroProfile Reactive Streams' and 'MicroProfile Metrics' into links for the actual Liberty features?
- [x] CURRENT: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library to load the Infinispan JAR files.
PROPOSED: The libraryRef attribute in the httpSessionCache element specifies the InfinispanLib value to reference a shared library which loads the Infinispan JAR files.
- [x] CURRENT:The uri attribute specifies the file:${shared.resource.dir}/infinispan/infinispan.xml value to reference the Infinispan.xml file.
PROPOSED: The uri attribute specifies the file:${shared.resource.dir}/infinispan/infinispan.xml value to reference the Infinispan configuration file <provide link to Infinispan Declarative Configuration here, https://infinispan.org/docs/11.0.x/titles/configuring/configuring.html#declarative-configuring >.
- [x] CURRENT: You must also configure the infinispan element to enable clustering, as shown in the following example:
PROPOSED: In the Infinispan configuration file you must configure the infinispan element to enable clustering, as shown in the following example:
- [x] CURRENT: You configure Infinispan in embedded mode without OpenShift.
PROPOSED: <This sentence seems to be missing something? Maybe add the word "can"?> You can configure Infinispan in embedded mode without OpenShift.
- [x] Suggestion: Make 'MicroProfile Reactive Streams' and 'MicroProfile Metrics' into links for the actual Liberty features? (second time these features are mentioned) - **Linked previously in the doc.**

**Comment by nmittles** [comment]
@ManasiGandhi The Infinispan example look good to me from a technical perspective. Thanks!

**Comment by dmuelle** [comment]
# Content review:
We should avoid repeating the same example with different implementations, as appears on this page with examples for both Hazelcast and Infinispan that are identical except for the library and config files, which are specific to the vendors and not OL.

All config example headings should be declarative statements per [guidance](https://github.com/OpenLiberty/docs/wiki/How-to-add-config-examples-to-generated-feature-docs#example-headings)

## Minimum configuration to persist session data with Hazelcast as the JCache provider
---> Persist HTTP session data with Hazelcast as the JCache provider

The description should make clear that this config applies if you want to use Hazelcast
Suggested edit:
The sessionCache feature does not include a JCache implementation, so you must pick one and reference it as a library in your `server.xml` file. You must define a location for the implementation files with the `library` element and reference that library by specifying the `libraryRef` attribute for the `httpSessionCache` element. 

In the following example, Hazelcast in specified as the JCache implementation by defining and referencing a library that is named `JCacheLib` that contains the Hazelcast JAR file: 


## Providing additional Hazelcast configuration
--->
Customizing the JCache implementation.

The description doesn't really match. This example shows how to how to reference a Hazelcast configuration file to apply custom configuration to a Hazelcast implementation. It should also state that the file is optional and provide a link back to your concept topic for an example of the config file. The description of the library element could go in the previous example. Here the important detail is the `uri` attribute, which defines the config file.

Suggested edit:

You can provide a configuration file to customize the how your JCache implementation manages HTTP session caching. To specify the file location, usethe `uri` attribute for the `httpSessionCache` element. In the following example, the `uri` specifies the location of a Hazelcast configuration file: 


[ example- replace `server1` with `${server.config.dir}`]

The Hazelcast configuration file is optional. For more information, see **Distributed HTTP session caching**. 

## Configuring Infinispan in client/server mode on OpenShift
--->Specify JCache vendor-specific properties
You can specify vendor-specific properties in your JCache configuration with the `properties` element. For information about the properties that are available, see the documentation for your chosen implementation. 

In the following example, Open Liberty is configured to access cached HTTP session data from a remote Infinispan server in `client/server` mode on OpenShift:
[example]

Then leave  text after the example as you have it.

I think the final three examples on this page should be removed, they don't provide any unique config info and probably belong in Richards Infinispan topic.We definitely dont want the infinispan config file example as that's docmumenting someone else's product.

**Comment by dmuelle** [comment]
Hi Manasi- the updates look good, I just saw two things that need edits. I'll add the content reviewed label and you can address them with any changes from Richards review:

In the first example description:
You must define a location for the implementation files with the library element...
--->
You must define a location for the implementation files with the `library` element...


Then in the final example, I know we discussed removing the extended explanation and providing a link to the infinispan topic. I think the introduction to that example could focus a little more on the properties, as that is the point of the example. Something like:  

In the following example, Open Liberty is configured to access cached HTTP session data from a remote Infinispan server in `client/server` mode on OpenShift. Vendor-specific Infinispan properties are passed to the JCache implementation in the `properties` elements:

**Comment by Rwalls1** [comment]
# Peer review

## Persist HTTP session data with Hazelcast as the JCache provider

TYPO: Change “Hazelcast in specified” to “Hazelcast is specified”

## Customizing the JCache implementation

* Typo: Change “customize the how” to “customize how”
* Typo: Change “the `uri`” to “the `uri` attribute"

**Comment by ManasiGandhi** [comment]
@rw2513 I worked on your review comments https://draft-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/feature/sessionCache-1.0.html

# Peer review

## Persist HTTP session data with Hazelcast as the JCache provider

- [x] TYPO: Change “Hazelcast in specified” to “Hazelcast is specified”

## Customizing the JCache implementation

- [x] Typo: Change “customize the how” to “customize how”

- [x] Typo: Change “the `uri`” to “the `uri` attribute"
