### ISSUE TITLE
Provide good server configuration snippets that users can easily find and consume

### ISSUE THREAD

**Issue by cajaygle** [OpenLiberty/docs#131]
From https://bigblue.aha.io/features/ENGAGE-11

Today, when you need to figure out a server configuration, you look in our documentation, you look at the information for the particular configuration element, you try to understand what is described but you will have a hard time trying to piece together which attribute will work with which and how everything fits together for what you want to get done.  Soon, you will scratch your heard, have to dig around even harder to no avail, and eventually, may have to resort to asking an exert i.e. calling IBM.  This is undesirable for both OL and WL.

If we can provide sample configuration snippets that work, encapsulate best practices, put proper description and guidance, and make them easily accessible and available to developers and users, that will go a long way to make what we have much more consumable, enable users to get going much faster, and providing a pleasant if not improved user experience.

**Comment by cajaygle** [comment]
Graham says, "We created these a long time ago.  I think security examples are typically the most verbose/complex."
https://developer.ibm.com/wasdev/downloads/#filter/assetTypeFilters=CONFIG_SNIPPET

**Comment by lauracowen** [comment]
- [ ] Collect snippets.
- [ ] Add to server feature doc (requires support for manual enhancements to generated docs).

Then snippets can be added as on-going effort by developers after this issue is closed.

**Comment by lauracowen** [comment]
Also some from here? https://developer.ibm.com/wasdev/downloads/#filter/assetTypeFilters=CONFIG_SNIPPET (checking with @NottyCode )

**Comment by lauracowen** [comment]
Asked Graham/Alasdair which of the WASdev snippets are relevant to OL.

**Comment by Charlotte-Holt** [comment]
This is ongoing. Issues are being tracked by the **enhance generated docs** label. Examples of published config snippets:
- https://openliberty.io/docs/20.0.0.10/reference/feature/jdbc-4.3.html
- https://www.openliberty.io/docs/20.0.0.10/reference/feature/socialLogin-1.0.html
