### ISSUE TITLE
Feature overview topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#132]
To be published at this URL: https://openliberty.io/docs/ref/feature/

Similar to https://openliberty.io/docs/ref/config/

Compile from information throughout the KC. Discuss with @NottyCode who has started looking at this.

This is required by issue https://github.com/OpenLiberty/openliberty.io/issues/489

**Comment by NottyCode** [comment]
Questions I think this page should answer:

1) What is a feature?
2) How do I use features?
3) Why should I care about features? (Zero Migration)
4) Are there any feature combinations that just don't work together?

Some WebSphere Liberty KC docs that might be useful in writing this content:

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_arch.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_prog_model_supported_combos_7_8.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_feat_mgmt.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_feat.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_prog_model_jee8behaviors.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_migration.html
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_about.html

**Comment by lauracowen** [comment]
https://ibm.box.com/s/mlpgx7a01g492v0l86hamsth1av6fbyf

**Comment by Charlotte-Holt** [comment]
@NottyCode, could you review the working notes/draft that I have for this topic at https://ibm.box.com/s/mlpgx7a01g492v0l86hamsth1av6fbyf? Are there any important points that I'm missing? Is there anything extraneous included? This is just a first draft, so let me know your thoughts. Thanks!

**Comment by NottyCode** [comment]
@Charlotte-Holt I don't have access to that box note. Can you make it public?

**Comment by Charlotte-Holt** [comment]
@NottyCode Just sent you an invite to edit it!

**Comment by NottyCode** [comment]
@Charlotte-Holt I've added my thoughts. I think a lot of the doc can be removed since it is talking about how to write features which I don't think we need in an overview of what features are.

**Comment by Charlotte-Holt** [comment]
@NottyCode I made updates based on your comments. Let me know what additional changes you think are necessary.

**Comment by Charlotte-Holt** [comment]
@NottyCode I built this to the draft site at https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#featureOverview.html. Two things to note: 

1. The tables are off. They looked fine in my AsciiDoc previewer, but I'm not sure what's going on with them on the site. I couldn't find any general formatting difference between these and the table at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#runnablejarfiles.html, for example. Any ideas?
2. I know that this topic should appear as 'OVERVIEW' (the landing page) when a user clicks Server features from the home page (the way the Server config overview topic does when a user clicks Server config from the home page), but I'm not sure how to get it there. 

When you have the chance, let me know what updates need to be made to this doc. I'll work on the above two issues. Thanks!!

**Comment by lauracowen** [comment]
@steven1046 Are you able to help with Charlotte's two issues above?

**Comment by steven1046** [comment]
It looks like the `draft` branch was deleted?

**Comment by steven1046** [comment]
Nevermind the draft branch is restored, i'm still working on the feature overview problem at the moment.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/ref/feature/. Closing this issue.
