### ISSUE TITLE
Update documentation for Fault Tolerance 2.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/docs#136]
Fault Tolerance 2.0 is going to beta in 19.0.0.2. This task is to update the documentation for OpenLiberty/open-liberty#4078

In addition to the auto-generated feature documentation, please can we update this page: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_fault_tolerance.html

I'd suggest the following changes:
* Everywhere in the page where we say "1.0 or 1.1", we now need to include 2.0 as well
* In the first paragraph, remove the reference to Failsafe (2.0 makes minimal use of Failsafe)
* In "Before you begin", replace the 1.1 specification link with a link to the 2.0 specification here: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html
* In "Procedure 1" update the server.xml snippet to say `mpFaultTolerance-2.0`
* In "Procedure 2" remove the text "The code snippet requires that the Liberty concurrent-1.0 feature is specified in the server.xml file in addition to the mpFaultTolerance-1.0 or mpFaultTolerance-1.1 feature."
  * As far as I can work out this was a mistake as all `mpFaultTolerance-x.x` features include `concurrent-1.0` so the user should not need to include it themselves.
* In "Procedure 2" we want to add a fourth example for `@Asynchronous` which should be inserted between the examples for Retry and Bulkhead.
  * Fault tolerance provides the ability to run methods asynchronously by annotating them with `@Asynchronous` and making the method return a `Future` or (FT 2.0 only) `CompletionStage`. This functionality can make other fault tolerance annotations more powerful, for example allowing a Bulkhead to queue waiting method calls, or allowing a `@Timeout` to return a result as soon as the time limit is reached, even if the method does not respond to being interrupted.
* Add a third entry to the "Procedure" section before the code snippets with the following information
  * You can override the parameters of any Fault Tolerance annotation at runtime using MicroProfile config. For more information on this feature, see [Spec Chapter 12](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#configuration)
  * (for FT 1.1+) Metrics are automatically exported for each method annotated with a fault tolerance annotation so that it can be monitored. For more information on this feature, see [Spec Chapter 11](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#_integration_with_microprofile_metrics) and this [OpenLiberty Blog post](https://openliberty.io/blog/2018/10/05/microprofile-faulttolerance-1.1-metrics.html)
  * (for FT 2.0) Fault Tolerance is implemented using a CDI interceptor. If your application also uses other CDI interceptors, you can adjust the priority of the Fault Tolerance interceptor to configure how it interacts with other interceptors. For information on how to do this, see [Spec Chapter 3](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#fault-tolerance-interceptor)
  * For a summary of the changes between different versions of the Fault Tolerance, please see the [Spec release notes](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#_release_notes_for_microprofile_fault_tolerance_2_0)

Asynchronous code snippet 1: Create an AsynchronousBean with methods which return `Future` or `CompletionStage`.

```
@RequestScoped
public class AsynchronousBean {
    
    @Asynchronous
    public Future<String> serviceA() {
        try {
            // Sleep to simulate work
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            throw new RuntimeException("serviceA interrupted", e);
        }
        // Return the result in a completed CompletableFuture
        return CompletableFuture.completedFuture("serviceA OK");
    }
    
    // Note: returning a CompletionStage requires Fault Tolerance 2.0
    @Asynchronous
    public CompletionStage<String> serviceB() {
        try {
            // Sleep to simulate work
            Thread.sleep(3000);
        } catch (InterruptedException e) {
            throw new RuntimeException("serviceB interrupted", e);
        }
        // Return the result in a completed CompletableFuture (which implements CompletionStage)
        return CompletableFuture.completedFuture("serviceB OK");
    }

}
```

Asynchronous code snippet 2: Use the AsynchronousBean.

```
@Inject AsynchronousBean asyncBean;

// serviceA and serviceB methods will run in parallel because they are annotated with @Asynchronous
Future<String> resultA = asyncBean.serviceA();
CompletionStage<String> resultB = asyncBean.serviceB();

// The CompletionStage returned from serviceB allows us to add actions which take place when the serviceB method finishes
resultB.thenAccept((r) -> System.out.println("ServiceB result: " + r))
       .exceptionally((ex) -> {
           System.out.println("ServiceB failed");
           ex.printStackTrace();
           return null;
       });

// For the Future returned from serviceA, we need to wait for it to finish, then we can handle the result
try {
    System.out.println("serviceA result: " + resultA.get());
} catch (ExecutionException ex) {
    System.out.println("ServiceA failed");
    ex.printStackTrace();
} catch (InterruptedException ex) {
    System.out.println("Interrupted waiting for serviceA");
}
```

**Comment by Azquelt** [comment]
@Emily-Jiang do these changes sound good to you?

**Comment by Emily-Jiang** [comment]
@Azquelt looks good. Based on our chat, it is a good idea to add one more bulletin point to clearly document the release note for MicroProfile releases

**Comment by Azquelt** [comment]
@Emily-Jiang thanks, I've updated the top comment to include that.

**Comment by Rwalls1** [comment]
@Azquelt When you mention adding a third entry to the procedure section, are you referring to adding a third step right above the circuit breaker code snippet?

**Comment by Rwalls1** [comment]
@Azquelt Please review the changes: https://www-03preprod.ibm.com/support/knowledgecenter/SSEQTP_liberty_temp/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_fault_tolerance.html

**Comment by Azquelt** [comment]
1. There's a stray `.` after `1.1` in the first paragraph
2. Can we add some of the information back to the first paragraph? Maybe add this sentence to the end: "It provides a programming model to support resilient microservices through patterns that include retries, circuit breakers, bulkheads, timeouts, and fallbacks."
3. In Procedure 2, under the paragraph about Asynchronous methods, please add links to the asynchronous code snippets further down the page (as is done for the other points in Procedure 2
4. The code snippets appear to follow on from Procedure 3, but actually they're related to Procedure 2.
  I think it makes sense to keep them on their own at the end, could we take them out of the numbered list and maybe give them their own heading?
5. Please put the Asynchronous code snippets after the Fallback and Retry code snippets so that they match the order they're described in Procedure 2.
6. In Procedure 2, please change "(FT 2.0 only)" with "(if using mpFaultTolerance-2.0)"
6. Please remove the blank line at the top of both asynchronous code snippets.
7. Procedure 3 has a 19.0.0.2+ flag, which is incorrect. Please remove it.
8. Please replace "(for FT 1.1+)" with "When using mpFaultTolerance-1.1 or later, "
9. Please replace "(for FT 2.0) Fault Tolerance is implemented using a CDI interceptor. If your application also uses other CDI interceptors" with "Fault Tolerance is implemented using a CDI interceptor. If you are using mpFaultTolerance-2.0 and your application also uses other CDI interceptors"
10. Where there are links to specific sections of the spec, the bit of the url after the `#` is getting lost when it goes through the "Leaving the IBM Web site" warning page. These need to be retained.
11. Fault Tolerance 2.0 is currently in beta. I don't know if we need a beta tag next to the parts which relate only to Fault Tolerance 2.0?

Example of the last point:
Original link: https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#configuration
Warning page link (doesn't link to the correct place in document): https://www.ibm.com/links?url=https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html#configuration

It looks like you can create a link through the warning page which does work by replacing `#` with `%23`: https://www.ibm.com/links?url=https://download.eclipse.org/microprofile/microprofile-fault-tolerance-2.0/microprofile-fault-tolerance-spec.html%23configuration Not sure if you can change something to have it generate the link like this?

**Comment by Rwalls1** [comment]
@Azquelt Here's the latest update, the issue with the links is actually a KC bug which we dont have a fix for at the moment, Also the 19002+ is the tag that will show as beta once it is published, would you still like it removed?

**Comment by Azquelt** [comment]
> the issue with the links is actually a KC bug which we dont have a fix for at the moment

That's annoying. Without the anchors, the links aren't very useful. I assume there's no hope of this getting fixed any time soon? I guess there's an issue raised somewhere?

> Also the 19002+ is the tag that will show as beta once it is published, would you still like it removed?

Ah, that makes sense. I think it's fine where it is now.

**Comment by Azquelt** [comment]
On the KC bug, if it's going to be fixed soonish, I think this doc can be published as is. If it's not going to be fixed for a while, we should probably change or remove the links, as at the moment they don't go to where the link text says they do, which is confusing.

**Comment by Rwalls1** [comment]
@Azquelt At the moment, I am not sure when the bug will be fixed, to avoid confusion, I will remove the links as you mentioned

**Comment by Rwalls1** [comment]
@Azquelt Actually, it may be best to leave them in until investigated further, it may be a simple fix that can be addressed soon, I will  investigate.

**Comment by Azquelt** [comment]
Something came up when I was doing the Service Transfer Education. We have a few small changes of behaviour between Fault Tolerance 1.1 and Fault Tolerance 2.0 and should probably document them.

Could we add a new page named "Fault Tolerance 2.0 behavior changes" underneath "Improving microservice resilience in Liberty" with this content:

The Fault Tolerance 2.0 implementation contains behavior changes which may cause an application written for an earlier implementation to behave differently or to fail when using the Fault Tolerance 2.0 feature. These changes were needed due to additional requirements in the Fault Tolerance 2.0 specification.

## Interactions between Fault Tolerance annotations

The Fault Tolerance 2.0 specification defines how fault tolerance annotations interact when used together on the same method or class. In particular:

* When using `@Asynchronous`, a method call will never throw an exception. Any exception which occurs will instead be propegated through the returned `Future` or `CompletionStage` object
  * Fault Tolerance 1.0 and 1.1 will throw an exception from an `@Asynchronous` method call if the exception occurs before the asynchronous task is started. In particular, this meant that a `BulkheadException` would always be thrown directly from the method call

* When using `@Asynchronous`, `@Bulkhead` and `@Retry` together, each retry attempt will check whether there is space in the Bulkhead to execute before running and release its space when it finishes. This means that it's possible for any Retry attempt to fail with a `BulkheadException`.
  * In Fault Tolerance 1.0 and 1.1, once an execution has acquired a space on the Bulkhead, it does not release it until all retry attempts have run and finished

## Priority of the Fault Tolerance interceptor

In Fault Tolerance 2.0, Fault Tolerance is implemented using an interceptor with a priority of 4010, as required by the specification. Fault Tolerance 1.0 and 1.1 use an interceptor with a priority of 1000.

If you want to revert to the previous behavior, Fault Tolerance 2.0 allows the priority of the interceptor to be configured by setting the `mp.fault.tolerance.interceptor.priority` property to `1000` using Microprofile Config.

**Comment by Rwalls1** [comment]
@Azquelt Please review: https://www-03preprod.ibm.com/support/knowledgecenter/SSEQTP_liberty_temp/com.ibm.websphere.wlp.doc/ae/rwlp_microprofile_fault_tolerance.html

**Comment by Azquelt** [comment]
@Rwalls1 Can we change "due to more requirements" to "due to **new** requirements" or "due to **additional** requirements" in the first paragraph?

I don't think "due to more requirements" reads very well in this context.

Change "release its space when it finishes" to "**releases** its space when it finishes"

Otherwise looks good, thanks

**Comment by Azquelt** [comment]
I've seen your latest update, all looks good now.
