### ISSUE TITLE
MicroProfile Context Propagation docs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#137]
When the MP Concurrency feature is GA status, the information proposed by Nathan Rauh to be published as OL docs.

See for details: https://github.ibm.com/was-liberty/liberty-docs/issues/1090

This information will first be published as a blog post on OL.io to mark the availability of the MP Concurrency capability in the OL development builds (ie 'beta' status though we don't call it a beta on OL). When the doc topic(s) is/are published (in OL docs), the blog post URL will be redirected to the doc topic to avoid duplication of content and to so that people with the blog post URL will find the new doc.

**Comment by lauracowen** [comment]
I've updated the description above because the type of information must be assessed before the topic(s) is/are created. Consider whether all the information is reference or whether enough of it is concept and should be created separately (this may or may not be appropriate - record the decision in this issue).

Also, can you check whether is any Concurrency info in the KC that we can use to base some OL concurrency docs on? Then raise an issue on this backlog to create a concept topic concurrency in Java SE, Java EE, and MicroProfile (maybe some of the new info would go here).

There's an old topic on WASdev.net (that may get published as a blog post on OL.io in the interim) that can provide some information to supplement what's in the KC: https://github.com/lauracowen/blogs/blob/concurrency/drafts/concurrency.adoc

**Comment by Rwalls1** [comment]
@lauracowen We will publish the info in a single reference topic. Also, I will investigate the concurrency info in KC and contact you with my thoughts about possible new topics that may require an issue

**Comment by lauracowen** [comment]
Okay, but check the Open Liberty docs backlog for priority of work.

**Comment by lauracowen** [comment]
Moved file to here for now: https://github.com/OpenLiberty/docs/tree/mpconcurrencybeta/concept

(It accidentally got published in its draft state and before the capability is GA because it was in the `develop` branch and the website team needed to do some merging. Discussing with Alasdair and the website team how to handle this better in future so that we can still do doc previews on the staging site.)

**Comment by lauracowen** [comment]
Moving this issue back to New column because the Concurrency capability is not GA yet. In the meantime, the info is available in this blog post which says it's in 'beta' status still: https://openliberty.io/blog/2019/03/01/microprofile-concurrency.html

**Comment by lauracowen** [comment]
@njr-11 Before we publish any [new MP Context Propagation doc](https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microprofile-concurrency.html) (when the new MP feature is GA) , we need to make sure we have at least one other topic introducing the concept of concurrency based on the blog posts you've written in the past for WASdev (see above comments) but updated to mention the MP support (or re-framed if appropriate). Can you keep that in mind and take a look at what you think needs doing? Happy to chat about it. For OL, all docs published need to make coherent sense in the context of what is already there and to support developers writing microservices for the cloud.

The new topic linked at the top of this comment seems to come in assuming a lot of knowledge and context already, which isn't assumed by your older WASdev blog post. We need to provide that context. We can do that asap - doesn't need to wait until the MP feature is ready.

**Comment by lauracowen** [comment]
Closing for clarity in favour of the newer #473
