### ISSUE TITLE
Update MP Rest Client guide with new 1.2 features

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/docs#139]
The existing MP Rest Client guide ( https://openliberty.io/guides/microprofile-rest-client.html ) uses MP Rest Client 1.1 APIs, and with MP Rest Client 1.2 about to release, we should probably update the guide to take advantage of some of the new features in 1.2 - specifically:
- adding the URI directly in the `@RegisterRestClient` annotation on the rest client interface
- using the new `@ClientHeaderParam` annotation to send hardcoded or computed HTTP headers

Most of the other features in 1.2 are used for integration with other technologies like MP Open Tracing or MP Fault Tolerance.  These features could be added in different guides that focus on these other technologies.

**Comment by lauracowen** [comment]
Moved to the guides backlog for prioritisation and addressing by YK's team: https://github.com/OpenLiberty/guides-common/issues/240
