### ISSUE TITLE
We should document how a server config "defaultValue" fits into the MP Config sources ordinal list

### ISSUE THREAD

**Issue by scottkurz** [OpenLiberty/docs#1495]
From conversation with developers, it seems the ordinal list for the default set of MP Config sources is:

600 = appProperties from server.xml
500 = Variables in server.xml
400 = System Properties
300 = Environment Variables
100 = microprofile-config.properties
1 = Default Values for variables in server.xml

This should be documented,  possibly 
1. here:    https://openliberty.io/docs/ref/general/#mp-config.html  which references the guide here:  https://openliberty.io/guides/microprofile-config-intro.html#background-concepts      
 OR
2. maybe even back here:  https://openliberty.io/docs/ref/config/  ?

One **incorrect** interpretation/assumption one might make without this doc would be something like:  "a non-overridden defaultValue gets treated as a server.xml variable in MP config property substitution, so gets ordinal 500".       Just making the case to document..

**Comment by Charlotte-Holt** [comment]
Try to add these to https://www.openliberty.io/docs/20.0.0.10/reference/config/server-configuration-overview.html. Make sure that the the [MP Config topic](https://www.openliberty.io/docs/20.0.0.10/external-configuration.html) makes sense with this new info.

**Comment by dmuelle** [comment]
This information is now documented in the [Default Configuration sources table](https://www.openliberty.io/docs/latest/external-configuration.html#_default_configuration_sources)
