### ISSUE TITLE
ID: LG-255: Provide ability to omit specified fields from JSON logging output 

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#1541]
Transferred from WAS Liberty docs backlog- originally https://github.ibm.com/was-liberty/liberty-docs/issues/1883

### Does the documentation apply to all platforms? 
- [x] Yes  
- [ ] No. Specific platforms: ______

### Does the documentation apply to all editions 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
For each new topic, complete the following information:
**Current jsonFieldMappings description:**
When logs are in JSON format, use this attribute to replace default field names with new field names. Configure the new field name by using the following format:
defaultFieldName:newFieldName
For field names that are associated with logs of a specified source, use the following format:
[source:]?defaultFieldName:newFieldName
where [source] is the source you want to specify (such as message, trace, or accessLog).
To rename multiple fields, specify a comma-separated list of field name mappings.

**Change to:**
When logs are in JSON format, use this attribute to replace default field names with new field names or to omit fields from the logs. To replace a field name, configure the new field name by using the following format: defaultFieldName:newFieldName?. For field names that are associated with logs of a specified source, use the following format: [source:]?defaultFieldName:newFieldName?, where [source] is the source you want to specify, such as message, trace, or accessLog. To omit a field from the logs, specify the field name without a replacement, as shown in the following example: defaultFieldName:. To rename or omit multiple fields, specify a comma-separated list of field name mappings.

Links effected:
https://www.openliberty.io/docs/ref/general/#logging.html
https://www.openliberty.io/docs/ref/config/#logging.html

**Comment by dmuelle** [comment]
Preview of changes: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#logging.html

changes will go to production with 20.0.0.6

@Yushan-Lin please review- thanks.

**Comment by Yushan-Lin** [comment]
@dmuelle 
beginning should be updated as well to this:

When logs are in JSON format, use this attribute to replace default field names with new field names or to omit fields from the logs. To replace a field name, configure the new field name by using the following format: `defaultFieldName:newFieldName?`.

**Comment by dmuelle** [comment]
Thanks @Yushan-Lin - draft is updated

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#logging.html

**Comment by Yushan-Lin** [comment]
@dmuelle looks good!

**Comment by dmuelle** [comment]
Thanks! closing this issue, updates will publish with the 20.0.0.6 release
