### ISSUE TITLE
Directory locations and properties

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1568]
Move information from https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_dirs.html into a new reference topic for OL. Integrate the "TIP" information into the body of the topic. Don't include the **Programmatic access to location properties** section, as this section should go elsewhere. 

When this is moved over, cross-check what's in the README for accuracy.

**Comment by Charlotte-Holt** [comment]
@cbridgha Could you review https://draft-openlibertyio.mybluemix.net/docs/ref/general/#directory-locations-properties.html? Please let me know if any additional updates are needed. Thanks!

**Comment by Charlotte-Holt** [comment]
Comment from @cbridgha: The only comment I have is you “could” add more hyperlinks for a bunch of the folders - could get busy… but its also enough for them to search on their own..  for example you could link the various property files to https://openliberty.io/docs/ref/config/serverConfiguration.html page…

**Comment by cbridgha** [comment]
The content is valid and helpful, and with additional hyperlinks, this doc would be a quick reference for new developers

**Comment by Charlotte-Holt** [comment]
@cbridgha I added links to the server config files. @lauracowen Can you review this topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#directory-locations-properties.html?

**Comment by lauracowen** [comment]
- The shortdesc at the top sounds as if the whole point of the article is to talk about the properties but then when you get to the table it says _if_ there's a property for the folder, it's displayed in the second column, and, actually, a lot of the rows don't have properties. Is it possible to reword the opening para slightly to say it's about telling you the default directory structure in Liberty and what all the dirs are for,  and also properties that are used to specify...etc?
- "specify file locations" - I was a bit unsure about what this meant. For example, `wlp/` - is the `wlp.install.dir` property specifying the location of the `wlp` folder? (directory location, not file location) or that the installation directory that contains all the installation fles is called `wlp`? (I think it's the former). Same question for the other properties listed I think. I just wasn't entirely sure of the purpose of the property file and how it relates to the dir in that row of the table.
- The description at the top of this issue says _not_ to include the "Programmatic access" section as it should go elsewhere. So I think it should be removed and put in a new issue?
- Really minor thing - should all the sentences in the last column end in periods? :)

**Comment by Charlotte-Holt** [comment]
@lauracowen Addressing your feedback: 

- [X] The shortdesc at the top sounds as if the whole point of the article is to talk about the properties but then when you get to the table it says if there's a property for the folder, it's displayed in the second column, and, actually, a lot of the rows don't have properties. Is it possible to reword the opening para slightly to say it's about telling you the default directory structure in Liberty and what all the dirs are for, and also properties that are used to specify...etc?
- [X] "specify file locations" - I was a bit unsure about what this meant. For example, wlp/ - is the wlp.install.dir property specifying the location of the wlp folder? (directory location, not file location) or that the installation directory that contains all the installation files is called wlp? (I think it's the former). Same question for the other properties listed I think. I just wasn't entirely sure of the purpose of the property file and how it relates to the dir in that row of the table.
- [X] The description at the top of this issue says not to include the "Programmatic access" section as it should go elsewhere. So I think it should be removed and put in a new issue? - Lol, good point. Removed the section and created issue #1799.
- [X] Really minor thing - should all the sentences in the last column end in periods? :)

**Comment by lauracowen** [comment]
Thanks. One last question - where are the properties specified? I think it would be useful to say. And to link to the page that explains more about it (I assume the config overview topic?).

**Comment by Charlotte-Holt** [comment]
@lauracowen I asked Chuck, and they can be specified in different places. You're right that the server config overview talks about it, so I linked out to that. Let me know if you think it needs more explanation! 

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#directory-locations-properties.html

**Comment by lauracowen** [comment]
Thanks. I think it needs a wee bit more explanation - the link in your topic takes me to the variable substitutions section which I'm not sure is the same thing? The rest of the config overview topic doesn't explicitly talk about what properties are set where. I think in your topic, where you have an example of setting the wlp.install.dir property, could you also say "it can be set in the x file or the y file depending on abc. See config overview topic for more information about these files." (config overview does describe how, and the order in which, the files are processed but not what's in them)

**Comment by Charlotte-Holt** [comment]
@lauracowen I consulted with @cbridgha to add a short example about where you can declare variables: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#directory-locations-properties.html. Let me know if you think it still needs more!

**Comment by lauracowen** [comment]
Nice. Thanks. Signing off.

**Comment by Charlotte-Holt** [comment]
Requesting peer review from @ManasiGandhi. Here's the topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#directory-locations-properties.html.

**Comment by ManasiGandhi** [comment]
#peer review @Charlotte-Holt ,the topic looks good. One small suggestion,

- “Some directories have properties that are associated with them that can be used to specify file locations when you configure the server.”  Can you change this to,
“Some directories have properties that can be used to specify file locations when you configure the server.” for conciseness.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic at https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/directory-locations-properties.html

**Comment by chirp1** [comment]
Hi Charlotte, Nice! Here are my comments:
- The headers for the table columns are in all capital letters. Make the headers sentence style. Are table headers in other topics all capitals? If so, or you don't know, open a defect to check the table headers in all the topics and make changes as appropriate.
- Although I see that the original topic says "...see the GitHub repository.", how about if you change it to "...see the ci.ant GitHub repository." to  make it a little more descriptive.
- For "User-customized server variables that apply to all servers (optional).", I see that in the original topic that this text links to "https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_customvars.html". Is twlp_admin_customvars.html on the list to be moved to Open Liberty? If so, do we have a defect that says to make the " "User-customized server variables ..." text a link when the new topic becomes available? If not, would you open a defect? 
- Ditto for "creating a server.". (I looked in the guides, but didn't see anything.) However, the answer might to link to the server create command at https://openliberty.io/docs/20.0.0.12/reference/command/server-create.html because that topic actually seems to include the necessary info from the topic that the WL topic at https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_dirs.html, which links to https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_setup_new_server.html - For "...creating a client",  ditto about opening a defect if necessary. I didn't see anything in the guides about creating a client.
- For "${server.output.dir}", put a noun after it.
- Reword "configuration (applications)." so that "applications" isn't in parentheses.
- Put a noun after "wlp/etc/jvm.options".
- Put a noun after "${server.output.dir}".
- Remove parentheses for "(log files and workarea)." and reword, maybe "...server, such as log files and the workarea directory. (I think that workarea is a directory or sub-directory.
- Change "after the server is run." to "after the server runs."in multiple places.
- Put First Failure Data Capture (FFDC)  on first occurrence of FFDC. You can leave on later occurrences or remove them from all occurrences but the first one. If you do leave them on existing occurrences, make sure FFDC is spelled out on all occurrences.
- Put a noun after "wlp/etc/client.jvm.options".

**Comment by Charlotte-Holt** [comment]
@chirp1 I addressed your feedback:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/directory-locations-properties.html

- [ ] The headers for the table columns are in all capital letters. Make the headers sentence style. Are table headers in other topics all capitals? If so, or you don't know, open a defect to check the table headers in all the topics and make changes as appropriate. **I think this has to do with the website styling and isn't something I can change. I think we could take this up with the website team.**
- [x] Although I see that the original topic says "...see the GitHub repository.", how about if you change it to "...see the ci.ant GitHub repository." to make it a little more descriptive.
- [ ] For "User-customized server variables that apply to all servers (optional).", I see that in the original topic that this text links to "https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_customvars.html". Is twlp_admin_customvars.html on the list to be moved to Open Liberty? If so, do we have a defect that says to make the " "User-customized server variables ..." text a link when the new topic becomes available? If not, would you open a defect? - **We have a [topic on environment variables](https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/default-environment-variables.html), but it's not published yet.** 
- [x] Ditto for "creating a server.". (I looked in the guides, but didn't see anything.) However, the answer might to link to the server create command at https://openliberty.io/docs/20.0.0.12/reference/command/server-create.html because that topic actually seems to include the necessary info from the topic that the WL topic at https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_dirs.html, which links to https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_setup_new_server.html - For "...creating a client", ditto about opening a defect if necessary. I didn't see anything in the guides about creating a client. **I linked "creating a server" to the server create command.**
- [x] For "${server.output.dir}", put a noun after it.
- [x] Reword "configuration (applications)." so that "applications" isn't in parentheses.
- [x] Put a noun after "wlp/etc/jvm.options".
- [x] Put a noun after "${server.output.dir}".
- [x] Remove parentheses for "(log files and workarea)." and reword, maybe "...server, such as log files and the workarea directory. (I think that workarea is a directory or sub-directory.
- [x] Change "after the server is run." to "after the server runs."in multiple places.
- [x] Put First Failure Data Capture (FFDC) on first occurrence of FFDC. You can leave on later occurrences or remove them from all occurrences but the first one. If you do leave them on existing occurrences, make sure FFDC is spelled out on all occurrences.
- [x] Put a noun after "wlp/etc/client.jvm.options".

**Comment by chirp1** [comment]
Hi Charlotte, 
- As we discussed over slack, open a defect about the table headers being all caps. Add the defect number to this issue.
- For "User-customized server variables that apply to all servers (optional).", do something such as open a defect to make sure the link is added to your topic when the topic on environment variables is published. If you open a defect, add the defect number to this issue.
- I see now that the topic has a few more "Change "after the server is run." references. Would you change "server is run" to "server runs" in all instances?

**Comment by Charlotte-Holt** [comment]
@chirp1 I addressed your feedback:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/directory-locations-properties.html

- [x] As we discussed over slack, open a defect about the table headers being all caps. Add the defect number to this issue. - **Issue created: https://github.com/OpenLiberty/openliberty.io/issues/2045**
- [x] For "User-customized server variables that apply to all servers (optional).", do something such as open a defect to make sure the link is added to your topic when the topic on environment variables is published. If you open a defect, add the defect number to this issue. **Doc bug created: https://github.com/OpenLiberty/docs/issues/3678**
- [x] I see now that the topic has a few more "Change "after the server is run." references. Would you change "server is run" to "server runs" in all instances?

**Comment by chirp1** [comment]
The updates looks good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3693 and already in the KC spreadsheet
