### ISSUE TITLE
Default port numbers

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1569]
Move information from https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_portnums.html into a new reference topic for OL. Don't include the `collectiveController` feature information.

**Comment by Charlotte-Holt** [comment]
Review comments:

- I think you can use the full plain-text feature name and link to the latest version of the feature (assuming it applies?) 
- I also think you can link to the relevant server config in the OL docs, like the KC article does (e.g., "For more information about SIP endpoints, see HTTP SIP Endpoint (sipEndpoint)."
- I think the actual port numbers can be monospaced. I know they aren't in the KC, and maybe it looks better that way, but I'd try monospacing them to what's best. 

Looking good!

**Comment by cbridgha** [comment]
Content looks good - Like the fact the specific feature version isn't mentioned, but the latest version is still hyperlinked. - Thanks

**Comment by lauracowen** [comment]
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#default-port-numbers.html

**Comment by lauracowen** [comment]
Looks good thanks. I'll sign it off.

Some things that I spotted that are really more Karen's review but I'll include them here so you can take a look first:
- "ephemeral"? Could it just be "temporary"?
- "defines default port numbers" -> "defines the default port numbers"?
- Use bullet points (unordered list) in the table instead of a numbered (ordered) list. eg for "IIOP port: 2809" - there's no reason that it should be ordered before "IIOP/SSL port: 9402".

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi Looks good! Peer review feedback: 

- Agree with Laura on changing "ephemeral" to "temporary"
- Agree with Laura on "defines default port numbers" -> "defines the default port numbers"
- Agree with Laura on "Use bullet points (unordered list) in the table instead of a numbered (ordered) list. e.g., for "IIOP port: 2809" - there's no reason that it should be ordered before "IIOP/SSL port: 9402"."
- The link to "Server Configuration" is broken. Also, I'd say "...see the Server configuration overview."
- I'd update, "The following table defines default port numbers of Open Liberty features and an example of how you can override the default port in your server configuration." to something like "The following table defines default port numbers of Open Liberty features and provides examples of how you can override default ports in your server configuration."
- I don't think you need "(httpEndpoint)" in "For more information about HTTP endpoints, see HTTP Endpoint (httpEndpoint)." I'd consider just "For more information about HTTP endpoints, see HTTP Endpoint."
- Same thing as the previous comment for "For more information about WAS JMS endpoints, see WAS JMS Endpoint (wasJmsEndpoint)."

**Comment by chirp1** [comment]
Hi Manasi, I'm returning this issue to in progress because when I click on the link to the draft, the first part of topic shows some of the topic source. Also, the topic title does not display. After you have the issues resolved, you can move the topic back to the editorial column.

**Comment by ManasiGandhi** [comment]
New link to the draft https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/default-port-numbers.html

**Comment by ManasiGandhi** [comment]
@chirp1 20.12 updated link https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/default-port-numbers.html.

**Comment by dmuelle** [comment]
looks good except link formats need to be updated- once that's done we can publish this with 21.0.0.6

**Comment by ManasiGandhi** [comment]
@dmuelle I worked on the link formats for this issue. Here is the link to the draft https://draft-openlibertyio.mybluemix.net/docs/21.0.0.7/reference/default-port-numbers.html

**Comment by dmuelle** [comment]
LGTM thanks- think we can send this to staging for 21.0.0.7

**Comment by dmuelle** [comment]
changes will publish with 21.0.0.7

**Comment by dmuelle** [comment]
https://openliberty.io/docs/latest/reference/default-port-numbers.html

This topic is being worked on as part of #5707
