### ISSUE TITLE
Limits to password encryption

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1573]
Modified from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_pwd_encrypt.html. 

Draft ready for review at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#password-encryption.html.

**Comment by lauracowen** [comment]
Some comments:

- Feels like it could do with some sub-headings to break it up a bit. Maybe "Password encryption on Open Liberty" before the second para, then "Server configuration files" (or something) before the bit about using an include.
- The lead-in to the bullet points was a bit awkward to read - why am I considering these two scenarios? I don't think I quite made the link between them and the previous sentences.
- Could do with some guidance as to when you should use the server.xml include file vs bootstrap.properties (and link to the Server Config overview topic which describes what the files are and when they're loaded during startup, in case that matters to the user). It's just kind of thrown in at the end as another option - if they're equal alternatives, they could do with being introduced as such then say why for each; if we think one is better, it's fine as it is but needs a 'why' still.

**Comment by Charlotte-Holt** [comment]
@lauracowen Thx for your feedback! Updated draft at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#password-encryption.html.

**Comment by Charlotte-Holt** [comment]
Requesting peer review from @Rwalls1

**Comment by Rwalls1** [comment]
The topic looks good, I just have a few comments: 
- In the opening paragraph, I think the link to the security utility command doc should be placed elsewhere, maybe in the first section about password encryption with Open Liberty, as I think the link would benefit from more contextual information surrounding it than what is presented in the intro. Moving the link will also help to make the short description more concise . Also, I think for consistency purposes across each topic, I think you should maybe change the syntax for the link to, “For more information, see”.
- In the phrase, “As such, it can be configured”, I think you could remove "As such" here as I think the sentence doesn't lose its meaning without its inclusion.
- In the sentence, "The Open Liberty configuration is highly composable and sharable.”, I think you could remove the word "highly" here as it may not add value to the statement without additional context. In general, I think it is usually best to avoid qualitative statements that may not be verifiable without a point of comparison or additional information.
- Make sure to run Acrolinx again as I noticed a couple things that were flagged.
- In the phrase, “In Open Liberty, the encryption key used for decrypting can be overridden from the default by setting”, I think it may be good add a noun after “default” to clearly specify what is being referred to and avoid any confusion.

**Comment by Charlotte-Holt** [comment]
@chirp1 Topic on https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/password-encryption.html.

**Comment by Charlotte-Holt** [comment]
Updates made: 

- "When you use this option for protecting system passwords in the Open Liberty configuration, you need to understand the limits to the protection it provides." **-->** "When you use this option for protecting passwords in the Open Liberty configuration, you need to understand the limits to the protection that AES encryption provides." - **DQTI, Chapter 6, Clarity, Use pronouns correctly** 
- "When a password is encrypted, someone who can see the encrypted password but doesn’t know the encryption key can't easily recover the password." **-->** "When a password is encrypted, someone who can see the encrypted password can't easily recover the password unless they know the encryption key." - **DQTI, Chapter 6, Clarity, Eliminate wordiness**

**Comment by Charlotte-Holt** [comment]
Comment from @utle:

We are talking in length to suggest customer to put the key.xml in protected place and out side of the normal configuration directory but the example is in the `${shared.config.dir}/key.xml`. It's probably better to have something like `/protected/key.xml`

```
<server>
  ...
  <include location="${shared.config.dir}/key.xml" />
</server>
```

`This separate configuration file must contain only a single property declaration, and it must be stored outside the normal configuration directory for the server.`

**Comment by Charlotte-Holt** [comment]
@utle I've addressed your previous comment. Thanks! https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/password-encryption.html

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/20.0.0.11/password-encryption.html. Still requires final editorial review.

**Comment by chirp1** [comment]
Hi Charlotte,
Here are my comments:
- The "Password encryption" and "Password encryption with Open Liberty" titles are too similar. Maybe change the section title to something like "Password encryption limitations".
- Spell out AES on the first occurrence.
- Remove extra words. Change "...you need to understand..." to "...Understand...".
- For the "Password encryption with Open Liberty" section, the second sentence sort of contradicts the first sentence. Go back to the original article. The "it only means" phrase pulls the two sentences together so that they make sense together. Rewrite the two sentences to get the original intent across.
- For "However, you might still consider encrypting passwords ..." a little bit of the original sentence is missing, and so the current sentence sort of misses the point. It's missing "there are still reasons why". 
- For "...It can be configured without an administration subsystem...", I don't think "can be" is the right phrase. In going back to the original topic, the wording is "Liberty is designed to be configured without an administration subsystem...".
- For the "Server configuration files" title, I think the section could use a different title to describe what the intent of the section is- Something like "Encryption key protection", "Default key override", etc. 
- For "...configuration file that’s included by the server.xml file...", change "by" to "in".

**Comment by Charlotte-Holt** [comment]
@chirp1 I made all of your updates: 

- [x] The "Password encryption" and "Password encryption with Open Liberty" titles are too similar. Maybe change the section title to something like "Password encryption limitations".
- [x] Spell out AES on the first occurrence.
- [x] Remove extra words. Change "...you need to understand..." to "...Understand...".
- [x] For the "Password encryption with Open Liberty" section, the second sentence sort of contradicts the first sentence. Go back to the original article. The "it only means" phrase pulls the two sentences together so that they make sense together. Rewrite the two sentences to get the original intent across.
- [x] For "However, you might still consider encrypting passwords ..." a little bit of the original sentence is missing, and so the current sentence sort of misses the point. It's missing "there are still reasons why".
- [x] For "...It can be configured without an administration subsystem...", I don't think "can be" is the right phrase. In going back to the original topic, the wording is "Liberty is designed to be configured without an administration subsystem...".
- [x] For the "Server configuration files" title, I think the section could use a different title to describe what the intent of the section is- Something like "Encryption key protection", "Default key override", etc.
- [x] For "...configuration file that’s included by the server.xml file...", change "by" to "in".

**Comment by chirp1** [comment]
Hi Charlotte,
I'm pondering the title a little more. The original WebSphere Liberty topic mentioned limitations in the title. I think that having a reference to limitations in the title will guide customers to look at the topic. How about these changes:
- Change the title from "Password encryption" to "Password encryption limitations".
- Remove the "Password encryption limitations" section title, and don't replace it with another one.
- Update the "securityUtility encode" topic (securityUtility-encode.html) by changing "For more information about limits to password encryption, see Password encryption." to "For more information, see Password encryption limitations.". <= Keep "Password encryption limitations" as a link.
- Update the "Password encryption" section of the "Server configuration security hardening" topic (server-configuration-hardening.html#password-encryption) by adding "For more information, see Password encryption limitations.". <= Make "Password encryption limitations" a link.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updates made:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/password-encryption.html
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/securityUtility-encode.html
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/server-configuration-hardening.html

- [x] Change the title from "Password encryption" to "Password encryption limitations".
- [x] Remove the "Password encryption limitations" section title, and don't replace it with another one.
- [x] Update the "securityUtility encode" topic (securityUtility-encode.html) by changing "For more information about limits to password encryption, see Password encryption." to "For more information, see Password encryption limitations.". <= Keep "Password encryption limitations" as a link.
- [x] Update the "Password encryption" section of the "Server configuration security hardening" topic (server-configuration-hardening.html#password-encryption) by adding "For more information, see Password encryption limitations.". <= Make "Password encryption limitations" a link.

**Comment by chirp1** [comment]
Hi Charlotte,
One last thing that I see I didn't mention:
For the SecurityUtility topics where you say _--password=pwd_, just italicize the variable, which is "pwd" so that it looks like --password=_pwd_.

**Comment by chirp1** [comment]
Updates look good!

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3693 and KC spreadsheet updated.
