### ISSUE TITLE
server package command contains too many examples

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1683]
I don't think all the examples are necessary - it makes it difficult to see the one you want. Also, one of the options shown in one of the examples isn't doc'd in the table of options.

I think remove the following examples:
- `server package myserver --archive=linux.zip --include=minify --os=Linux` - it's covered by the next one on the page.
- `server package myserver --include=runnable` - covered by the longer one following it
- `server package --include=wlp` - the one with the archive option is probably more useful
- `server package myserver --server-root="mywlp"` - just don't think it's necessary in addition to the option being described in the table.

Also:
- the `--archive="package_file_name.zip"` option - must it have quotation marks around the file name/path? In some of the examples it does; in some it doesn't. I suspect it's not necessary. If it's not necessary, remove quotation marks from the option in the table and from the examples. I suspect it's only necessary if you have spaces in the file path, in which case anyone who uses a command line will understand they need to use quotations so it's not necessary to specify. But check what's required by the command.
- the `--server-root` description doesn't really explain why you'd need it. Is it for if you don't want the root folder in the archive to be the default `wlp`? Why might that be the case? Or is it if the root folder that you're archiving is already not `wlp` at the point when you run this command? Also, as for the archive option, I'm not sure quotation marks are necessary. The variable in the quotation marks could be shorter and simpler and explained in the description, rather than trying to explain itself?

**Comment by ManasiGandhi** [comment]
https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/command/server-package.html
