### ISSUE TITLE
 JSON logging updates for Log and trace configuration doc

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#1694]
Overview of JSON logging with Open Liberty

- Not the default format, has to be configured
- why should devs care? 
- enables modern logging tools like prometheus, grafana
- basics of config- focus on _what_ you need to configure and _why_, point out to reference topics for details on _how_
- include info on custom fields, changing field names and removing fields and why these capabilities are useful

SME: Don Bourne

Potential Sources (ask Don if there are others):
- https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html
- https://www.openliberty.io/docs/ref/general/?_ga=2.109890821.188692436.1591628908-2076895440.1590072036#logging.html
- https://openliberty.io/blog/2019/10/11/configure-logs-JSON-format-190010.html#jlog

Some info from https://draft-openlibertyio.mybluemix.net/docs/ref/general/#managing-logging.html might go here, then link from that topic.

**Comment by dmuelle** [comment]
After talking with @donbourne - this information will be added to [the Log and trace configuration doc](https://www.openliberty.io/docs/20.0.0.7/log-trace-configuration.html), instead of a new doc.

Will also include info from #1898, as follows:

Create a doc from this blog post: https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html

Although there are config examples in the post, it's more reference than task. This is mostly application-side config to connect with Liberty LogRecordContext. API. Explain why adding fields is useful for troubleshooting and provide examples from the post. Dont think we need the ELK screencap though. Check with SMEs to make sure the examples are current and relevant to most users

SMEs: Yushan Lin, Don Bourne

**Comment by dmuelle** [comment]
Make the following improvements to [Log and Trace configuration: JSON logging](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/log-trace-configuration.html#_json_logging)

- [x] revise section introduction

- [x] remove option to configure JSON logs in server.xml

- [x] provide more information on the value of "Configuring JSON field names"

- [x] Add section for "Adding custom fields to JSON logs" based on [this blog post](https://openliberty.io/blog/2019/12/03/custom-fields-json-logs.html)

- [x] Add anchor list of sections to top of doc and edit throughout for style and clarity

**Comment by dmuelle** [comment]
Hi @donbourne - based on the discussion from our last call, I've revised the JSON Logging section of the log and trace configuration doc. Can you provide technical review of the updated draft?

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/log-trace-configuration.html#json

see the previous comment for the items I've addressed so far. I also did some general editing for style and clarity throughout this page so if there's anything not in the JSON sections that also needs to be addressed I can update as part of this issue as well.

If possible, can you get back with me by Tuesday 9/1? Thanks!

**Comment by donbourne** [comment]
Hi @dmuelle , sorry for taking so long to get back to you.  Here are my comments...

Expanded JSON HTTP access log fields
->
Custom HTTP access log JSON fields
___
with an expanded set of fields
->
with a custom set of fields
___
replace the default JSON HTTP access log fields
->
replace the default HTTP access log JSON fields
___



Custom JSON log fields
->
Custom message and trace JSON fields
___
- You can add custom fields to your JSON logs -> You can add custom fields to your JSON-formatted message and trace output
- "To add fields with boolean, float, int, or long values, the extension name must include the suffixes _bool, _float, _int, or _long, as shown in the following examples:" - should explain that the presence of the suffix in the extension name ensures that the resulting JSON is formatted without putting the value in quotes.
___
To add a string-valued field to your application logs, include the following line in your application: 
-> 
To add a string-valued field to your application logs, include the following line in your application.  The newly specified field will be subsequently added to log and trace entries created on the same thread.

**Comment by dmuelle** [comment]
Hi @donbourne , thanks for reviewing. I've made the changes you requested and have a couple questions:

## Questions

- "To add fields with boolean, float, int, or long values, the extension name must include the suffixes _bool, _float, _int, or _long, as shown in the following examples:" - should explain that the presence of the suffix in the extension name ensures that the resulting JSON is formatted without putting the value in quotes.

I'm not sure I understand. Does this mean that you need to use quotes when you specify the extension values, but if you use a suffix, the values that are specified in the logs will not include quotes? Because only string values are enclosed in quotes in the log output? I still need to update this but wanted to clarify the meaning first


- The newly specified field will be subsequently added to log and trace entries created on the same thread.

In this context, what does "the same thread" mean? There's no discussion of threads in this description so, for me at least, it's not clear if "same" refers to log and trace entries being on the same thread or "the same thread" where you specified the extension

- Re: custom fields. I had tried using the word "expanded" for the HTTP access log fields in order to avoid using the word "custom" to mean two different things in the same doc. I know expanded isn't the right word here but is there any other way to describe these fields? 

Right now, "custom" means one thing for "Custom message and trace JSON fields" and something different for "Custom HTTP access log JSON fields":

- **Custom message and trace JSON fields:** Fields that the user/admin specifies to track particular issues. Custom in the sense that they are custom-designed by the user/admin.
- **Custom HTTP access log JSON fields**: a predetermined set of fields that are only available if you explicitly enable them. Not "custom" in the same sense as the fields which the user/admin supplies.

I'm concerned that this might cause confusion, with users possibly mistaking one capability for the other. It was confusing for me at first until I realized that there were  two different kinds of "custom" fields. Thoughts?

## Changes made 
- replaced "Expanded JSON HTTP access log fields" with "Custom HTTP access log JSON fields" throughout doc
- changed replace the default JSON HTTP access log fields->replace the default HTTP access log JSON fields
- changed Custom JSON log fields-> Custom message and trace JSON fields throughout doc
- changed To add a string-valued field to your application logs, include the following line in your application:
->To add a string-valued field to your application logs, include the following line in your application. The newly specified field will be subsequently added to log and trace entries created on the same thread. (see question above)

**Comment by donbourne** [comment]
@dmuelle , here are my answers to your questions... will review the rest once the whole doc is ready.

> I'm not sure I understand. Does this mean that you need to use quotes when you specify the extension values, but if you use a suffix, the values that are specified in the logs will not include quotes? Because only string values are enclosed in quotes in the log output? I still need to update this but wanted to clarify the meaning first

you always need to use quotes to specify the extension values (since the addExtension method only accepts Strings as the second parameter).  it does mean that the values in the JSON written to the logs will not include quotes.  And it's correct that only string values are enclosed in quotes in the log output.

> In this context, what does "the same thread" mean?

It just means that the Java thread that executes the addExtension method puts the name/value pair into a threadLocal variable.  That means that when, later in time, on the same thread, a logging call is made, that value from the threadLocal will be used.

> Right now, "custom" means one thing for "Custom message and trace JSON fields" and something different for "Custom HTTP access log JSON fields":
maybe we could say...
- Programmatically-specified message and trace JSON fields
- Selectable HTTP access log JSON fields

**Comment by dmuelle** [comment]
Hi @donbourne, I've updated the doc based on your comments. It's ready for comprehensive review now.

Updates from your most recent coments:

- clarified that JSON output for non-string values is not enclosed in quotes
- clarified "same thread" as thread that executes the addExtension method
- replaced "Custom HTTP access log fields" with "Selectable HTTP access log fields"

**Comment by donbourne** [comment]
Configurable JSON field names
- At the end of this section, should we add a link to the list of all the default field names (ie. to the JSON field reference)?

Custom message and trace JSON fields
- should we change this section name to stress that it requires code change... ie. "Programmatically-specified message and trace JSON fields"?
- "the resulting JSON fields are not enclosed in quotes in the logs" -> "the resulting JSON field values are not enclosed in quotes in the logs"
- "Only string-valued JSON fields are enclosed in quotes in the logs." -> "Only string-valued JSON field values are enclosed in quotes in the logs."
- "To remove custom fields from the logs, use the following method to remove the extension that created the field:" -> "To remove custom fields from the logs, use the following method:"

Selectable HTTP access log JSON fields
- need a first sentence to say that this only pertains to when you are using JSON logging with the accessLog source.
- "with a larger set of fields" -> "with a different set of fields" (this option replaces the set of fields with what's in the accessLogging logFormat -- it doesn't just add to the default fields)

**Comment by dmuelle** [comment]
Hi @donbourne I made the following changes per your review
Configurable JSON field names

- [x] At the end of this section, should we add a link to the list of all the default field names (ie. to the JSON field reference)?

Custom message and trace JSON fields

- [ ] should we change this section name to stress that it requires code change... ie. "Programmatically-specified message and trace JSON fields"?

 **I left this as "custom" since I think custom describes fields that are specified by the user more concisely than "Programmatically-specified", which would then have to replace "custom" throughout this section. I think since we're no longer using "custom" for the HTTP access log fields it's less ambiguous. I can change it if you disagree**

- [x]  "the resulting JSON fields are not enclosed in quotes in the logs" -> "the resulting JSON field values are not enclosed in quotes in the logs"

- [x]  "Only string-valued JSON fields are enclosed in quotes in the logs." -> "Only string-valued JSON field values are enclosed in quotes in the logs."

- [x]  "To remove custom fields from the logs, use the following method to remove the extension that created the field:" -> "To remove custom fields from the logs, use the following method:"

Selectable HTTP access log JSON fields

- [x]  need a first sentence to say that this only pertains to when you are using JSON logging with the accessLog source.

- [x]  "with a larger set of fields" -> "with a different set of fields" (this option replaces the set of fields with what's in the accessLogging logFormat -- it doesn't just add to the default fields)

Let me know if this needs any further changes or if you're ready to sign off. Thanks!

**Comment by donbourne** [comment]
Hi @dmuelle , everything looks good except this one thing:
- "For a full list of the default JSON field names, see the JSON log events reference list."
    - the link seems to point to https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/log-trace-configuration.html#json-log-events-lis.adoc , instead of the intended doc

**Comment by dmuelle** [comment]
Sorry about that! I fixed the typo that caused the link to fail and [rebuilt the draft](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/log-trace-configuration.html#names). Let me know if anything further is needed or, if you're ready to sign off, please add the `technical reviewed` label to the issue. Thanks

**Comment by dmuelle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/log-trace-configuration.html#json

**Comment by lauracowen** [comment]
- minor thing - think there's a typo in `accesLogging` in the Selectable... section.

Think it looks good though. Thanks both. Signing off.

**Comment by dmuelle** [comment]
Thanks for catching that @lauracowen - fixed 

Requesting peer review from @Rwalls1

**Comment by Rwalls1** [comment]
## Peer review
The topic looks good, I just have a few comments:
- For “Direct human consumption”, I think you should use a simpler term that will provide more  clarity.
- I think you should change “fully configured in server.xml” to “fully configured in the server.xml file” to increase clarity and maintain consistency throughout topics.
- Similarly, I think you should change “before server.xml” to "before the server.xml file” and change “through server.xml” to "through the server.xml file”
- I think the phrase, "redirecting the process stdout and stderr may need to be rewritten. To provide more clarity, I think you should add a noun after “stdout” and “stderr” to indicate what is being referenced.
- Global comment: I think to maintain consistency and clarity that you should always refer to files explicitly with a file reference, such as “the messages.log file”. The file references are not consistent throughout the topic.
- I think you should change “use the following configuration” to “you can use the following configuration” to avoid phrasing the sentence as a command.
- Similarly, change “include the following” to “you can include the following”
- For the “Log configuration settings” table, I think the overall design strategy may need to be revisited as the table contains some inconsistencies that makes the information harder to follow. For instance, the table contains an "ENV VAR” column that contains several empty entries which I think undermines the need to have a dedicated column for it. Also, some of the descriptions, particularly for “traceSpecification” and “jsonFieldMappings”, are very long and not parallel with other entries which makes the content harder to follow. There may not be a better way to present this information but I think it may be worth rethinking.

**Comment by dmuelle** [comment]
Thanks for reviewing @Rwalls1. I made the following updates per your review: 
- [x] For “Direct human consumption”, I think you should use a simpler term that will provide more  clarity.
- [x] I think you should change “fully configured in server.xml” to “fully configured in the server.xml file” to increase clarity and maintain consistency throughout topics.
- [x] Similarly, I think you should change “before server.xml” to "before the server.xml file” and change “through server.xml” to "through the server.xml file”
- [x] I think the phrase, "redirecting the process stdout and stderr may need to be rewritten. To provide more clarity, I think you should add a noun after “stdout” and “stderr” to indicate what is being referenced.
- [x] Global comment: I think to maintain consistency and clarity that you should always refer to files explicitly with a file reference, such as “the messages.log file”. The file references are not consistent throughout the topic.
- I think you should change “use the following configuration” to “you can use the following configuration” to avoid phrasing the sentence as a command.
- [x] Similarly, change “include the following” to “you can include the following”
- [x] For the “Log configuration settings” table, I think the overall design strategy may need to be revisited as the table contains some inconsistencies that makes the information harder to follow. For instance, the table contains an "ENV VAR” column that contains several empty entries which I think undermines the need to have a dedicated column for it. Also, some of the descriptions, particularly for “traceSpecification” and “jsonFieldMappings”, are very long and not parallel with other entries which makes the content harder to follow. There may not be a better way to present this information but I think it may be worth rethinking. **Agree that it needs rethinking. I went through and tried to make the entries parallel and reduce some of the longer entries by linking out for further info instead of including in the cell. I'm going to open a separate docbug to address this table so this issue can focus on the JSON updates**

**Comment by dmuelle** [comment]
doc bug for the config settings table: https://github.com/OpenLiberty/docs/issues/3087

**Comment by dmuelle** [comment]
edits for clarity and concreteness in #3092 
-Make the syntax of sentences clear
- reduce wordiness
- use technical terms appropriately and consistently
- Use words with a clear meaning

Re- checked against the [KC  and OL blog post sources ](https://github.com/OpenLiberty/docs/issues/1694#issue-638003348)

**Comment by lauracowen** [comment]
- Should the "Configure JSON logging with environment variables:" sentence before the example say "in the `server.env` file."?
- The link to the 20.0.0.08 release blog post - does that info not fit into this doc topic? If not and it should be a different doc topic, can you create an issue to create that topic too (then when that's done the link can be changed in this topic). I don't think we should rely long-term on pointing people to a section of a release blog posts as they're quite bitty in terms of being a mix of info (as opposed to the full, standalone blog posts that are basically like doc topics just in the Blog section). But fine for the interim.

Aside from that, I think I signed this off before anyway so I'm good with this topic.

**Comment by dmuelle** [comment]
Doc is now on vNext branch, will publish with 20.0.0.12 on 11.20

draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/log-trace-configuration.html

**Comment by dmuelle** [comment]
https://openliberty.io/docs/latest/log-trace-configuration.html
