### ISSUE TITLE
Random "Copy" word pasted into the example config in Application Security feature topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1730]
Copy/paste error somewhere in the first example. After the closing tag, it has the word "Copy" which shouldn't be there.

https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#appSecurity-3.0.html

**Comment by Rwalls1** [comment]
@lauracowen I made the correction: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#appSecurity-3.0.html

**Comment by lauracowen** [comment]
Brill, thanks :)
