### ISSUE TITLE
Open Liberty title edits

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#1743]
We need to revise the titles of some of the open liberty topics

- remove gerunds from any titles that are not tasks. Make sure task topics have a gerund that expresses user goals for the task
- remove "Open Liberty" from topic titles (Except for "About Open Liberty")
- make longer titles more concise to improve readability in the TOC. If necessary, the title in the TOC can be a short version of the topic title, which remains unchanged.
- change filenames to match new titles **and update any. links**

Writers should take ownership of changing the title, filename, and links to any topics they wrote. In the comments please note any topics you've updated and what the new title is. **See the comment below for the titles/ files you should update**

**Comment by dmuelle** [comment]
Hi @lauracowen - can you review the above list to confirm that all these titles should be changed? or if there are any not listed here that need updating. For the longer titles- should we change the title and filename or just provide an alias for the TOC?

**Comment by dmuelle** [comment]
Update your unpublished topics on draft. Please comment in this issue when your titles, filenames and associated links have been updated. I will take care of all the published topics in a single branch to avoid merge conflicts. 


@Charlotte-Holt 
- Application configuration security hardening- update filename and nav alias per discussion
- Configuring SPNEGO authentication in Open Liberty: remove OL from title/ filename `configuring-SPNEGO-authentication` 
- Deploying Open Liberty applications on OpenShift: **new titile** Deployment on OpenShift (Charlotte) /filename `deployment-openshift`
- Gathering and displaying Open Liberty metrics:  Delete again 
- Introduction to Open Liberty server hardening for production **new titile**: Security hardening for production / filename `security-hardening`
- JMX metrics reference list / filename `jmx-metrics-list` 

@Rwalls1 
- Audit support for server runtime environment and applications **new titile**: Audit logs / filename: `audit-logs`
- JSON logging reference list **new titile**: JSON log events reference list / filename `json-log-event-list` 
- Log management: filename `log-management`
- delete obsolete SSO topics

@ManasiGandhi 
- Documenting microservice APIs with OpenAPI **new titile**: API documentation with OpenAPI filename: `documentation-openapi`
- Slow and hung request detection: filename: `slow-hung-request-detection` 
- Testing microservice applications **new titile**: True-to-production integration testing  / filename: `integration-testing`

@dmuelle will handle the already published topics and links as well as my own topics
- Authentication filters for specifying authentication mechanisms **new titile**: Authentication filters/ filename `authentication-filters`
- Authentication in Open Liberty : remove Open Liberty from title and filename
- Authorization in Open Liberty  remove Open Liberty from title and filename
- Building resilient microservices **new titile**: Fault tolerance / filename: `fault-tolerance`
- Dependency injection in microservices with MicroProfile **new titile**: Context and dependency injection beans  filename: `cdi-beans`
- Designing cloud-native microservices: **new titile** Cloud-native microservices  filename `cloud-native-microservices`
- Development mode for deploying, testing, and debugging applications *new titile**: Development mode / filename: `development-mode`
- Differences between Fault tolerance 1.0 and 2.0 **new titile**: Differences between Fault tolerance 1.x and 2.0 filename `fault-tolerance-1-diff ` (check for relevance)
- Differences between Metrics 1.0 and 2.0: filename `metrics-1-diff`
- Enabling microservice health checks **new titile**: Health checks for microservices 
- Enhancing concurrency with MicroProfile Context Propagation **new titile**: Concurrency with MicroProfile Context Propagation
- Externalizing the configuration in microservices **new titile**:  External configuration of microservices  filename `external-configuration`
- JAAS auth- delete 
- Logging and tracing **new titile**: Log and trace configuration/ filename `log-trace-configuration` (David)
- Managing concurrency in microservices **new titile**: Concurrency in microservices
- Metric reference list: filename `metrics-list`
- MicroProfile simplifies developing cloud-native Java microservices *new titile**: Microprofile 
- REST clients: filename `rest-clients` (David)
- RESTful microservices: filename `rest-microservices` 
- Secure communication with transport layer security: alias as Secure communication with TLS
- Serializing data with JSON-P and JSON-B **new titile**: JSON-P and JSON-B/ filename json-b-json-p
- Synchronous and Asynchronous rest- change to hyphens

**Comment by Charlotte-Holt** [comment]
@dmuelle I made all my updates and checked links while I was in there. I'll keep an eye out in my other docs for link/title updates as well.

**Comment by Rwalls1** [comment]
@dmuelle I've updated the file names and topic titles. The SSO topics have also been removed.

**Comment by ManasiGandhi** [comment]
@dmuelle, @Charlotte-Holt 
Updated filenames and titles

- [x] Documenting microservice APIs with OpenAPI new titile: API documentation with OpenAPI filename: documentation-openapi
    

- [x] Slow and hung request detection: filename: slow-hung-request-detection

    

- [x] Testing microservice applications new titile: True-to-production integration testing / filename: integration-testing

**Comment by dmuelle** [comment]
All title and filename edits are complete, changes pushed to draft, and where applicable, develop and master
