### ISSUE TITLE
directory names for config examples must match the feature name exactly

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1765]
The directory name needs to match the feature name so that it is unambiguous which feature the directory relates to. eg `JCacheSessionPersistence` should be `sessionCache`. Can someone check all the directory names and update them appropriately, ideally before we publish them.

![image.png](https://images.zenhubusercontent.com/583eaf59b9dc3c622022b986/0f36421c-31ce-4884-8d56-0eb60d815e3f)

**Comment by dmuelle** [comment]
all directory names match feature names exactly on both `draft` and `vNext`, any extra directories with the old names have been removed. Closing this issue
