### ISSUE TITLE
Configuring OpenID Connect Client - new property when behind proxy

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#178]
For details, see: https://github.ibm.com/was-liberty/liberty-docs/issues/1116

New property was added in 19003. It was not documented because it was added at request from an internal team who know or can work out from the generated config doc how to use it.

If added in future, the whole topic needs to be broken down into reference material with specific common/important tasks as proper task topics - not just appended to this long 14-step topic that contains many optional steps (https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_config_oidc_rp.html).

**Comment by Charlotte-Holt** [comment]
Config example for OIDC server w/ #676

**Comment by dmuelle** [comment]
internal request, closing
