### ISSUE TITLE
MP intro editorial improvements

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#181]
Reviewed the MP Intro topic (https://openliberty.io/docs/intro/microprofile.html) with Dan Kehn. I applied some of the edits we documented here (in blue and marked 'Done' in red): https://ibm.box.com/s/eaeuvpt16u9n0suz79zrb0z31kxvk6k0

The remaining suggested edits should also be applied to improve the readability of the article (marked in red with 'TODO').

**Comment by dmuelle** [comment]
feedback no longer available- closing
