### ISSUE TITLE
MicroProfile docs: REST foundation layer

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#182]
Documentation around the basic REST standards provided by the bottom layer of MP features.

![microprofile-layers.png](https://images.zenhubusercontent.com/583eaf59b9dc3c622022b986/98f00a91-607a-4b64-85f7-b25cfdd5faf7)

**Comment by Charlotte-Holt** [comment]
Closing epic issues. Can reopen if we find these are missed or useful.
