### ISSUE TITLE
server help command issue

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#1841]
Update the [server help command ](https://openliberty.io/docs/ref/command/#server-help.html) so it doesn't have an option. Just have `server help actionName` in the syntax, as in the [securityUtility help command](https://draft-openlibertyio.mybluemix.net/docs/ref/general/#securityUtility-help.html).

**Comment by Charlotte-Holt** [comment]
Updates made at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/command/server-help.html

**Comment by lauracowen** [comment]
LGTM

**Comment by Charlotte-Holt** [comment]
This is on `vNext` after being validated on `staging`: https://staging-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/command/server-help.html
