### ISSUE TITLE
Disabling cookies config examples

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#1880]
Add to the following three features, the relevant example and brief explanation provided in this blog post:

appSecurity feature: https://openliberty.io/blog/2020/07/02/disable-default-cookies-20007.html#LTPA-cookie
spnego feature: https://openliberty.io/blog/2020/07/02/disable-default-cookies-20007.html#LTPA-cookie
JWT feature: https://openliberty.io/blog/2020/07/02/disable-default-cookies-20007.html#JWT-cookie

But re-write the explanations to be descriptions after the example that describe/explain what the example shows, not the more abstract approach taken in the blog post.

Also, only give the specific line as the example config - enabling the feature is shown elsewhere in the gendoc.

**Comment by Charlotte-Holt** [comment]
#894 #954 #1964

**Comment by Charlotte-Holt** [comment]
@lauracowen I updated the SPNEGO config example (#954) with the example from the blog: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#spnego-1.0.html. Let me know what you think!

**Comment by lauracowen** [comment]
Looks good, thanks. The last paragraph verges on getting a bit conceptual but I see you've included the explanation of what the cookie is so that you can describe what happens when it's disabled as that process isn't described elsewhere.

I wonder if we need to update the LTPA bit here: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#authentication.html? The explanation you have in the ref topic is nice and clear and maybe a little more informative than what's currently in the Auth topic LTPA section. Could just add the info from the ref topic then remove all but the sentence "In this example configuration..." from the ref topic (and link to the concept topic)?

**Comment by Charlotte-Holt** [comment]
@lauracowen Yeah, that's a good idea. @dmuelle Are you still working on the authentication topic? If so, maybe you could make that small change on your end so we don't hit conflicts?

**Comment by Charlotte-Holt** [comment]
@lauracowen Updated the feature doc at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/spnego-1.0.html. @dmuelle also updated the authentication doc at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/authentication.html.

**Comment by lauracowen** [comment]
Looks good, thanks.

**Comment by Charlotte-Holt** [comment]
@Rwalls1 When you get the chance, could you add this example to #894?

**Comment by Rwalls1** [comment]
@Charlotte-Holt It's been added, @lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/appSecurity-3.0.html

**Comment by lauracowen** [comment]
Ok, looks good (as far as I understand it). Thanks

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi I think you have #1964, which is the last feature that needs this example added. Could you add it when you start working on the JWT SSO feature config?

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt Sure. Will do.

**Comment by Charlotte-Holt** [comment]
This example was published in: 
- https://openliberty.io/docs/20.0.0.11/reference/feature/spnego-1.0.html
- https://openliberty.io/docs/20.0.0.11/reference/feature/jwtSso-1.0.html
- https://openliberty.io/docs/20.0.0.11/reference/feature/appSecurity-3.0.html
