### ISSUE TITLE
ID: LG-286: Allow JSON written to System.out to pass without wrapping

### ISSUE THREAD

**Issue by t-koman** [OpenLiberty/docs#1911]
### Does the documentation apply to all platforms? 
- [x] Yes  
- [ ] No. Specific platforms: ______

### Does the documentation apply to all editions 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
For each new topic, complete the following information:
In the logging table, add another row for the new attribute:

SERVER XML ATTRIBUTE | BOOTSTRAP PROPERTY | ENV VAR | DESCRIPTION
-- | -- | -- | --
appsWriteJson | com.ibm.ws.logging.apps.write.json |   WLP_LOGGING_APPS_WRITE_JSON | When message log or console is in JSON format, allow applications to write JSON-formatted messages to those destinations, without modification.

Links effected:
https://www.openliberty.io/docs/ref/general/#logging.html

##### To create a topic:
- [ ] Specify a first draft of the topic that you want added:
- [ ] Specify a link to the section in the navigation where the topic should go:
##### To update to an existing topic:
- [x] Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:
- [x] Specify a link to the topics that are affected:
##### To add a custom property, complete the following checklist:
- [ ] Specify a link to the topic that will contain the custom property:
- [ ] The name and a description of the custom property
- [ ] Default values and other values
- [ ] Behavior of the values

### This issue was erroneously placed in the WAS/Liberty GitHUB - https://github.ibm.com/was-liberty/liberty-docs/issues/2011

**Comment by Yushan-Lin** [comment]
Created new issue to keep track #1938
