### ISSUE TITLE
ID: LG-265: Add custom access log fields to JSON logs and logstashCollector

### ISSUE THREAD

**Issue by t-koman** [OpenLiberty/docs#1912]
### Does the documentation apply to all platforms? 
- [x] Yes  
- [ ] No. Specific platforms: ______

### Does the documentation apply to all editions 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
For each new topic, complete the following information:

Add new doc subsection under JSON Logging:

**Receiving custom access logs**
When logs are in JSON format, you can use the `jsonAccessLogFields` attribute to replace the default access log fields with access log fields from the `accessLogging logFormat` property. 
- In server.xml:
    ```
    <!-- HTTP access logging must be enabled to receive JSON access logs -->
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"> 
        <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
    </httpEndpoint>
    <logging jsonAccessLogFields="logFormat"/>
    ```
Links effected:
https://www.openliberty.io/docs/ref/general/#logging.html

--

Also, please add another row to include the new attribute from https://www.openliberty.io/docs/ref/config/#logging.html to https://www.openliberty.io/docs/ref/general/#logging.html.

##### To create a topic:
- [ ] Specify a first draft of the topic that you want added:
- [ ] Specify a link to the section in the navigation where the topic should go:
##### To update to an existing topic:
- [x] Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:
- [x] Specify a link to the topics that are affected:
##### To add a custom property, complete the following checklist:
- [ ] Specify a link to the topic that will contain the custom property:
- [ ] The name and a description of the custom property
- [ ] Default values and other values
- [ ] Behavior of the values

### I am creating this issue in the Open Liberty GITHUB where it applies.   The issue was previously created in the was-liberty GITHUB ----> https://github.ibm.com/was-liberty/liberty-docs/issues/2008

**Comment by t-koman** [comment]
Open Liberty issue: https://github.com/OpenLiberty/open-liberty/issues/10618

**Comment by Yushan-Lin** [comment]
Created new issue to keep track #1939
