### ISSUE TITLE
API-30: Oracle UCP Doc (Follow-on to Liberty-docs #1157)

### ISSUE THREAD

**Issue by alexsm82** [OpenLiberty/docs#192]
Oracle UCP support is targeted to GA in 19.0.0.4. Below is a draft of what this content should look like:

Database connectivity with Oracle UCP

Oracle Universal Connection Pool (UCP) is a standalone JDBC connection pool. When using Oracle UCP with Open Liberty you are using the Oracle UCP connection pool instead of using Open Liberty's built-in connection pooling functionality. Some of Oracle's high availability database functionality requires the use of Oracle UCP. Support for Oracle UCP was added in Open Liberty version 19.0.0.4.

Configuring a Data Source using Oracle UCP

Ensure that one of the JDBC features is enabled in server configuration. Oracle UCP can be used with any version of JDBC supported by Open Liberty, but support for any specific specification functionality will be limited to what is supported by Oracle UCP.

```
<featureManager>
    <feature>jdbc-4.2</feature>
    <feature>jndi-1.0</feature> <!-- Required only if JNDI is desired to look up resources -->
</featureManager>
```

Configure the datasource and library in server config. The UCP driver and Oracle JDBC driver can be obtained from Oracle.
```
<dataSource id="oracleUCPDS" jndiName="jdbc/oracleUCPDS" >
    <jdbcDriver libraryRef="OracleUCPLib" />
    <properties.oracle.ucp URL="jdbc:oracle:thin:@//localhost:1521/SAMPLEDB" />
</dataSource>

<library id="OracleUCPLib">
    <fileset dir="C:/Oracle/Drivers" includes="ojdbcx.jar ucp.jar"/>
</library>
```

Note that Oracle UCP might require some properties to be set in the properties.oracle.ucp element, such as the user and password, depending on the version used.
Since the Liberty connection pool is disabled, some of the Open Liberty datasource and connection manager configuration values are ignored and overridden. The following connection manager properties cannot be used with Oracle UCP:

agedTimeout
connectionTimeout
maxIdleTime
maxPoolSize
minPoolSize
purgePolicy
reapTime
maxConnectionsPerThread
maxConnectionsPerThreadLocal

Additionally, the datasource properties statementCacheSize and validationTimeout cannot be used when using UCP with Open Liberty, as Open Liberty's statement caching and connection validation are disabled.

For most of those datasource and connection manager properties, Oracle UCP provides equivalent functionality. See Oracle's documentation for more details and note that some default property values differ between Open Liberty's connection manager and Oracle UCP. The Oracle UCP properties can be applied to the `properties.oracle.ucp` properties element.

The dataSource types of ConnectionPoolDataSource and Driver are not supported with Oracle UCP since the UCP driver does not provide an implementation of those interfaces.

The data source can be accessed and utilized by the application using the standard JDBC APIs.

**Comment by chirp1** [comment]
@alexsm82 Hi Alex, from my understanding for Laura Cowen, Alasdair is doing some work so that developers can add examples to generated docs. So, before you write any documentation, Alasdair will first need to complete this work, which won't be done until after 19004 goes out. However, Laura Cowen indicated that the generated docs will go out for 19004. So at least some of the information that relates to your feature will be in the generated docs.

**Comment by alexsm82** [comment]
@chirp1 So are we not placing docs for features here https://openliberty.io/docs/ref/general/? I guess if we can't get this published before GA I can include more of the info in the blog post for the feature.

**Comment by lauracowen** [comment]
@alexsm82  We're prioritising work to publish sections of doc coherently instead of publishing disconnected updates as the function is completed (see https://ibm.box.com/s/m57ei3khzrg84o7l4ossc0h2j51cmnn9 for the doc strategy presented at the recent runtime kickoff call for more explanation in the speaker notes). So new doc requirements are raised on the docs backlog and then prioritised but may not be published for the next release.

The blog post means that there is some documentation in the meantime about how to get started using the new capability. Which blog post are you referring to and what other info would you want to add?

**Comment by lauracowen** [comment]
Some links to the properties mentioned:

- The connection manager properties not available to UCP configurations are here: https://openliberty.io/docs/ref/config/dataSource.html#connectionManager
- The two properties not available when using UCP with OL are here: https://openliberty.io/docs/ref/config/dataSource.html
- The new ucp properties element will be (I deduce) here: https://openliberty.io/docs/ref/config/#dataSource.html#dataSource/properties.oracle.ucp
- All are available from this base URL: https://openliberty.io/docs/ref/config/dataSource.html

**Comment by alexsm82** [comment]
Hi @lauracowen, thanks for the info!  I must have been distracted and misinterpreted some of the information from the kickoff.  In terms of the blog it was mentioned here for the beta: https://openliberty.io/blog/2019/03/01/sharding-keys-jdbc43-19002.html, and looking at it again most of the information is already there, although there are a couple of updates needed (which I’m finishing and will place here: https://github.com/OpenLiberty/open-liberty/issues/7261).

**Comment by dmuelle** [comment]
We are including a section for Oracle UCP in our new doc on JDBC data sources, which is now [available for review on our draft site](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/relational-database-connections-JDBC.html#Oracleucp). This doc is scheduled to publish with 20.0.0.12
