### ISSUE TITLE
ID: LG-265: Add custom access log fields to JSON logs and logstashCollector

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/docs#1939]
### Does the documentation apply to all platforms? 
- [x] Yes  
- [ ] No. Specific platforms: ______

### Does the documentation apply to all editions 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
For each new topic, complete the following information:

Add new doc subsection under JSON Logging:

**Receiving custom access logs**
When logs are in JSON format, you can use the `jsonAccessLogFields` attribute to replace the default access log fields with access log fields from the `accessLogging logFormat` property. 
- In server.xml:
    ```
    <!-- HTTP access logging must be enabled to receive JSON access logs -->
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"> 
        <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
    </httpEndpoint>
    <logging jsonAccessLogFields="logFormat"/>
    ```
Links effected:
https://www.openliberty.io/docs/ref/general/#log-trace-configuration.html

--
Add a new doc section:
**Receiving custom access logs**
In Logstash Collector, you can use the `jsonAccessLogFields` attribute to replace the default access log fields with access log fields from the `accessLogging logFormat` property. 
- In server.xml:
    ```
    <!-- HTTP access logging must be enabled to receive JSON access logs -->
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"> 
        <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
    </httpEndpoint>

    <logstashCollector 
        source="accessLog" 
        jsonAccessLogFields="logFormat">
    </logstashCollector>
    ```
Links effected: https://openliberty.io/docs/ref/feature/#logstashCollector-1.0.html

--

Please add another row to include the new attribute (I believe it is autogenerated) from https://www.openliberty.io/docs/ref/config/#logging.html to https://www.openliberty.io/docs/ref/general/#log-trace-configuration.html.

##### To create a topic:
- [ ] Specify a first draft of the topic that you want added:
- [ ] Specify a link to the section in the navigation where the topic should go:
##### To update to an existing topic:
- [x] Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:
- [x] Specify a link to the topics that are affected:
##### To add a custom property, complete the following checklist:
- [ ] Specify a link to the topic that will contain the custom property:
- [ ] The name and a description of the custom property
- [ ] Default values and other values
- [ ] Behavior of the values

**Comment by jennifer-c** [comment]
Edited main issue body to add a section for Logstash Collector as well.

**Comment by dmuelle** [comment]
Hi @jennifer-c @Yushan-Lin - can you provide a brief statement of the value of this feature so the user understands why they might want to replace the http access log fields? We are updating the Log and trace configuration doc to add a little more info on the JSON logging config.

**Comment by dmuelle** [comment]
also- is this heading correct?

**Receiving custom access logs**
When logs are in JSON format, you can use the `jsonAccessLogFields` attribute to replace the default access log fields with access log fields from the `accessLogging logFormat` property. 

The heading says "receiving custom access logs" but the description says "...replace the default access log fields..." . I understand these two statements are related to the same purpose but it would be better if the heading was consistent with the description. Is "Replacing default access log fields" an acceptable heading?

**Comment by jennifer-c** [comment]
>can you provide a brief statement of the value of this feature so the user understands why they might want to replace the http access log fields? 

This feature allows the user to replace the default set of JSON access log fields with a custom set of fields as defined in the httpAccessLogging logFormat attribute. The user is now able to receive information previously not available in JSON logs, such as the remote user ID, request headers, etc. These logs can be used in log analysis tools, such as the ELK (Elasticsearch, Logstash, Kibana) stack, to better monitor your server.

I'm not sure if you want a list of the new fields available, but they are as follows:

Field | Description
-- | --
ibm_remoteIP | Remote IP address, e.g. 127.0.0.1
ibm_bytesSent | Response size in bytes excluding headers.
ibm_cookie_{cookiename} | Cookie value from the request.
ibm_requestElapsedTime | The elapsed time of the request - millisecond accuracy, microsecond precision.
ibm_requestHeader_{headername} | Header value from the request.
ibm_responseHeader_{headername} | Header value from the response.
ibm_requestFirstLine | First line of the request.
ibm_requestStartTime | The start time of the request, in NCSA format.
ibm_accessLogDatetime | The time when the message to the access log is queued to be logged, in normal NCSA format.
ibm_remoteUserID | Remote user according to the WebSphere Application Server specific $WSRU header

>Is "Replacing default access log fields" an acceptable heading?

"Replacing default access log fields" is fine.

**Comment by dmuelle** [comment]
For the table on the log and trace configuration page:

Please add another row to include the new attribute (I believe it is autogenerated) from https://www.openliberty.io/docs/ref/config/#logging.html to https://www.openliberty.io/docs/ref/general/#log-trace-configuration.html.

The logging table is autogenerated but it does not contain the values for the equivalent bootstrap property or environmental variable- can you provide these?

**Comment by dmuelle** [comment]
Thanks @jennifer-c!
 As to the new fields- will they be documented anywhere else? Will they appear in the autogen for `httpAccessLogging` ? If so I can just link to that page.

**Comment by jennifer-c** [comment]
>The logging table is autogenerated but it does not contain the values for the equivalent bootstrap property or environmental variable- can you provide these?

Bootstrap: `com.ibm.ws.json.access.log.fields`
Env: `WLP_LOGGING_JSON_ACCESS_LOG_FIELDS`

> As to the new fields- will they be documented anywhere else? Will they appear in the autogen for httpAccessLogging ?

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.8/json-log-events-list.html#_http_access_log_events will have the field names and the descriptions - however, there is no indication that these fields are new/optional and I'm not sure when it'll be published. `httpAccessLogging` has not changed, so I don't believe there will be any additional documentation on that side. 

I was sifting through the openliberty docs but I can't seem to find an equivalent of this page (which lists all of the logFormat specifiers e.g. `%a` `%b`): https://www.ibm.com/support/knowledgecenter/SSEQTP_9.0.5/com.ibm.websphere.base.doc/ae/rrun_chain_httpcustom.html. If you know where it's documented on the OL docs, I think you can link that page.

**Comment by dmuelle** [comment]
I don't think we have the "HTTP transport channel custom properties" in Open Liberty yet but I'll add it to our backlog.

I think the best solution is to break these fields out into a separate table under the HTTP access log events on the JSON log events reference log page. It might be a while before that page publishes though. In the meantime- do you know in the release blog post for 20.0.0.8 wil contain this information? If so, I can link to that until the other page publishes

**Comment by jennifer-c** [comment]
No, the release blog doesn't contain a list of new fields. I can try to get that added in since it's not published yet - does that sound like the best way to do this?

**Comment by dmuelle** [comment]
I think so- The fields don't really belong in this doc and the JSON reference list doc is still in development/review. Am I correct in understanding that these fields are only available if you specify `<logging jsonAccessLogFields="logFormat"/>` in the server.xml?

**Comment by jennifer-c** [comment]
Yes, these fields are only available if that property is set. I'll speak with the blog author to get the table added in.

**Comment by dmuelle** [comment]
One more question! Do the new fields replace the defaults or are they available in addition to the defaults? ie, if you set the property, are the default fields still available?

**Comment by jennifer-c** [comment]
The new fields replace the default fields when `jsonAccessLogFields="logFormat"`. However, all of the default fields correspond to some logFormat token. For example, `ibm_userAgent` (which is part of the default fields) can be set alongside the custom/new ones by adding `httpAccessLogging logFormat="%{User-Agent}i"`. Similarly, `ibm_queryString` is part of the default fields, but can be set alongside the custom/new fields by adding `httpAccessLogging logFormat="%q"`.

Would it be helpful to have a list of those somewhere?

**Comment by dmuelle** [comment]
Probably- Unfortunately I'm not particularly familiar with the logging configuration so I'm not sure where that info belongs.

To clarify:
`jsonAccessLogFields="logFormat"`, replaces the default  fields with those that are specified by  `accessLogging logFormat=` in the `httpEndpoint` element. However, you can add more access log fields to the JSON logs by specifying `logFormat` for `httpAccessLogging` ?

**Comment by dmuelle** [comment]
Hi @jennifer-c , please review the draft of this update:

[Replacing default HTTP access log JSON fileds](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.8/log-trace-configuration.html#_replacing_default_http_access_log_json_fields)

Let me know if the text and table updates look ok. I will add a link to the blog before it publishes, unless we can determine a better source of information. 

Ultimately, I think the reference table for the custom fields should be added to the JSON log events reference list page, along with information about how to optionally restore any default fields that are replaced (if that is something a user is likely to want to do). I can add that information to the issue for the reference list- #210 

For this doc, lets just make sure we have the basic info needed for the 20.0.0.8 release. Let me know what you think. Thanks!

**Comment by dmuelle** [comment]
For the logstashCollector update- we have an example file in development- #1095. Once the text here is approved, I will add the same info to that issue for inclusion in the doc

**Comment by jennifer-c** [comment]
>jsonAccessLogFields="logFormat", replaces the default fields with those that are specified by accessLogging logFormat= in the httpEndpoint element. 

Yes, this is correct. 

>However, you can add more access log fields to the JSON logs by specifying logFormat for httpAccessLogging

Sorry, I've been using `httpAccessLogging` and `accessLogging` interchangeably which may have gotten confusing. `httpAccessLogging` and `accessLogging` both do the same thing (and you can only use one at a time per httpEndpoint anyway). So you can add or remove access log fields via `logFormat` for `httpAccessLogging`/`accessLogging`

e.g.
Using `<accessLogging logFormat='%a %C'/>` will print out the new fields: `ibm_remoteIP` and `ibm_cookie`
Using `<accessLogging logFormat='%a %q'/>` will print out the new field `ibm_remoteIP`, as well as print out `ibm_queryString` which is part of the default fields.

**Comment by dmuelle** [comment]
Thanks @jennifer-c - I think I have a better understanding now. I'm going to update the draft but I have two quick questions

* Does [this table](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.8/access-logging.html#_http_access_log_format) contain the log tokens a user would need to specify the custom fields?
* Why would a user choose `accessLogging` vs `httpAccessLogging` ? Is there an advantage either way? It would be best to document one of the two consistently, and then if necessary, mention that you could also use the other.

**Comment by dmuelle** [comment]
Is this correct for the Logstash configuration?

    ```
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"> 
        <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
    </httpEndpoint>

    <logstashCollector 
        source=",accessLog" 
        jsonAccessLogFields="default">
    </logstashCollector>
    ```
Should the `jsonAccessLogFields` be set to "default"? In the regular logging confg it's set to "logFormat". Just checking as it seems counterintuitive to replace defaults by specifying "default"

**Comment by jennifer-c** [comment]
>Does this table contain the log tokens a user would need to specify the custom fields?

Yes, all of them are there!

>Why would a user choose accessLogging vs httpAccessLogging ? Is there an advantage either way? It would be best to document one of the two consistently, and then if necessary, mention that you could also use the other.

I'm not sure what the equivalent OL doc is, but there's an explanation here: https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/rwlp_http_accesslogs.html
httpAccessLogging is used for common log config, accessLogging is for distinct logs per endpoint. For the docs, using `accessLogging` is better I think.

>Is this correct for the Logstash configuration?

Oops, sorry, you're absolutely right. It should be `logFormat`. I've updated the body with this:

```
    <!-- HTTP access logging must be enabled to receive JSON access logs -->
    <httpEndpoint httpPort="9080" httpsPort="9443" id="defaultHttpEndpoint"> 
        <accessLogging logFormat='%R{W} %u %{my_cookie}C %s'/>
    </httpEndpoint>

    <logstashCollector 
        source="accessLog" 
        jsonAccessLogFields="logFormat">
    </logstashCollector>
```

**Comment by dmuelle** [comment]
Thanks @jennifer-c - please review the updated draft

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.8/log-trace-configuration.html#_replacing_default_http_access_log_json_fields

If the update looks ok, can you add the `technical reviewed` label to this issue? If not, please let me know any further edits that are needed. This doc is targeted to publish tomorrow with 20.0.0.8. Thanks!

**Comment by jennifer-c** [comment]
Looks great, thanks @dmuelle!

**Comment by dmuelle** [comment]
changes to logging doc are published to production: https://www.openliberty.io/docs/20.0.0.8/log-trace-configuration.html

Further updates for logstash collector are being tracked in the issue for that doc (#1095)
