### ISSUE TITLE
Social Media Login first sentence update

### ISSUE THREAD

**Issue by ManasiGandhi** [OpenLiberty/docs#1979]
Social Media Login https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#socialLogin-1.0.html

Update the first sentence from, "Social Media Login feature provides a form of single sign-on (SSO) that enables users to sign in to a secured website by using their existing social media account."

to,

"The Social Media Login feature provides a form of single sign-on (SSO) that enables users to sign in to a secured website by using their existing social media account."

**Comment by Charlotte-Holt** [comment]
Updated at https://github.com/OpenLiberty/open-liberty/pull/13853/files
