### ISSUE TITLE
Commands landing page 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2008]
We need a landing page for the **Commands** section of the OL navigation. See #1960 for other landing pages. This commands landing page can summarize the different commands that we have for OL so a user can see at a glance which command(s) they might be looking for.

**Comment by Charlotte-Holt** [comment]
@lauracowen First draft at https://draft-openlibertyio.mybluemix.net/docs/20.0.0.10/reference/command/command-introduction.html.

**Comment by lauracowen** [comment]
yes, I think that works. :)

**Comment by cbridgha** [comment]
I like the short explanations of each command, and I know more of the missing commands are coming when ready (Already talked to Charlotte about this).  

Can we add more detail to "To learn how you can modify the behavior of the featureUtility commands" Changed to: "To learn how you can modify behavior such as shared and local feature repositories..."

Can you also add server "dump" to the suggested "server" commands?  

Also in general we should think about a Service page?  like how to create a dump, setup tracing etc..  Any must gather info...  we don't "support" OL, but we can provide tips for investigating issues?

**Comment by Charlotte-Holt** [comment]
@lauracowen I addressed Chuck's feedback: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/command/command-introduction.html. Let me know if any additional updates are needed!

**Comment by lauracowen** [comment]
LGTM :)

**Comment by Charlotte-Holt** [comment]
Requesting peer review from @ManasiGandhi

**Comment by ManasiGandhi** [comment]
@Charlotte-Holt The topic looks good! A few edit suggestions

- [x] In the first sentence, can you fix the typo. The word "available" is mentioned twice.

- [ ] Under "featureUtility commands", it says, "The featureUtility commands make it easier to install Open Liberty features and view your Maven repository settings." Acrolinx is flagging "easier". Could you replace it with something else, for example, "The featureUtility commands helps" or rephrase the sentence? 

- [x] Under "server commands", could you change the sentence, "The server commands perform Open Liberty server functions, including creating a server, starting a server, and stopping a server. ", to, "The server commands perform Open Liberty server functions that include creating a server, starting a server, and stopping a server. "

**Comment by Charlotte-Holt** [comment]
Thanks, @ManasiGandhi! I addressed your comments. For your second point, I do see where Acrolinx is flagging "easy", but in the Acrolinx guidance it says that it might be appropriate to use "easier" in some cases, and I think this falls under one of those cases. @chirp1 - Any thoughts on this? 

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/command/command-introduction.html

**Comment by chirp1** [comment]
Hi Charlotte,
Here are my comments:
- We don't use "following" in the opening sentence because what we want to direct users to later in the topic generally won't display in the search results for the topic. Rewrite the opening paragraph to explain what the purpose of the commands are. You might include a few commands as examples. 
- Check the list of commands in the commands section. I think you need to add the "springBootUtility" command. Others might also need to be added.
- To reduce wordiness, remove "When you need to install features,".

**Comment by Charlotte-Holt** [comment]
@chirp1 I addressed your feedback:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/command/command-overview.html

- [x] We don't use "following" in the opening sentence because what we want to direct users to later in the topic generally won't display in the search results for the topic. Rewrite the opening paragraph to explain what the purpose of the commands are. You might include a few commands as examples.
- [ ] Check the list of commands in the commands section. I think you need to add the "springBootUtility" command. Others might also need to be added. - **The springBootUtility command isn't published yet, so I can't link to the documentation. I can add a section about it if you're sure that you can edit those topics before 21.0.0.3. Otherwise, I'll just make a note in that issue that this overview needs to be updated when it's ready to publish.**
- [x] To reduce wordiness, remove "When you need to install features,".

**Comment by chirp1** [comment]
Hi Charlotte,
Here are my comments:
- The intro paragraph is looking better! Would you rewrite it so that it's a maximum of two sentences?
- Let's go with you adding a note to the issue for the springBootUtility command to indicate that this overview topic needs to be updated when the springBootUtility command topic is ready to publish.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updates made! 

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/command-overview.html

- [x] The intro paragraph is looking better! Would you rewrite it so that it's a maximum of two sentences?
- [x] Let's go with you adding a note to the issue for the springBootUtility command to indicate that this overview topic needs to be updated when the springBootUtility command topic is ready to publish. - **Note added to https://github.com/OpenLiberty/docs/issues/776**

**Comment by chirp1** [comment]
HI Charlotte, 
For the opening paragraph, how about if we add some extra info- something like: You can use commands to complete tasks such as installing, securing, and administering the Open Liberty server.

**Comment by Charlotte-Holt** [comment]
@chirp1 Updated!

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/command/command-overview.html

**Comment by chirp1** [comment]
The updates look good.

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3693
