### ISSUE TITLE
RESTful microservices (MP05)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#205]
What is a RESTful microservice? Why are microservices a good thing to do (standards, independence, etc)? What things to know about re APIs with expected behaviours. JAX-RS

Base on IBM Cloud docs: IBM Cloud: https://cloud.ibm.com/docs/java?topic=cloud-native-rest-api#rest-api but ensure it's slightly different so it doesn't mess up their SEO. Also it doesn't need to be implementation agnostic so can refer to the MicroProfile capabilities as appropriate (eg when discussing OpenAPI can refer to how MP OpenAPI provides this capability...etc).

**Comment by lauracowen** [comment]
Added this to Milestone 19.0.0.4 instead of #35 because it's more related to #36 than #35 is.

**Comment by dmuelle** [comment]
working draft at https://ibm.ent.box.com/notes/442669065898

**Comment by dmuelle** [comment]
So far this draft is content that was moved over from the REST clients draft, supplemented with some info about MicroProfile & REST, adapted from the OL Microprofile intro. Looking at the cloud doc referenced above- it seems to be mostly organized around best practices- is that what we are looking for here?  Organizing the content under similar headings but connecting the practices to MicroProfile features?

**Comment by dmuelle** [comment]
working draft at https://github.com/OpenLiberty/docs/blob/draft/concept/rest_microservices.adoc

**Comment by dmuelle** [comment]
This topic is now live on Open Liberty docs- https://www.openliberty.io/docs/ref/general/#/docs/concept/rest_microservices.html

closing this issue
