### ISSUE TITLE
Add Java EE compatibility sentence to MicroProfile intro

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#209]
Update https://openliberty.io/docs/intro/microprofile.html

In the section "Rapidly deploy cloud-native Java microservices at scale", add sentence to the end of the second paragraph something like:

"If you need more capabilities in your application, you can add Java EE features too. If you are using MicroProfile 2.0 and above on Open Liberty, you can add Java EE 8 features to your application. If you are using MicroProfile 1.x on Open Liberty, you can add Java EE 7 features."

(feel free to make it slicker and less wordy if you can!)

This came from feedback from a Java EE user that they were unaware that, on Liberty, that you can use MP features with Java EE.

**Comment by lauracowen** [comment]
I think that looks fine, thank you. Might be worth double-checking technical accuracy of the new sentences with @aguibert

**Comment by aguibert** [comment]
LGTM 👍

**Comment by Charlotte-Holt** [comment]
Published, and looks good: https://openliberty.io/docs/intro/microprofile.html.
