### ISSUE TITLE
Update three more file names

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2101]
We need to update the file names of the following three topics:

- [Server configuration overview](https://openliberty.io/docs/20.0.0.7/reference/config/serverConfiguration.html) (`serverConfiguration.adoc` --> `server-configuration-overview.adoc`)
- [Feature overview](https://openliberty.io/docs/20.0.0.7/reference/feature/featureOverview.html) (`featureOverview.adoc` --> `feature-overview.adoc`)
- [Runnable JAR files](https://openliberty.io/docs/20.0.0.7/runnablejarfiles.html) (`runnablejarfiles.adoc` -->`runnable-jar-files.adoc`)

**Comment by dmuelle** [comment]
Updated server configuration, runnable jar files and their nav entries. Feature overview is blocked by a weird merge conflict issue.

**Comment by dmuelle** [comment]
fix delivered to vNext in #2361
