### ISSUE TITLE
Add config snippet examples to enhance `audit` feature topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#211]
Enhance the Audit feature doc here: https://openliberty.io/docs/ref/feature/#audit-1.0.html in a similar way to https://www.openliberty.io/docs/ref/feature/#jdbc-4.3.html

Specifically:
- [ ] Take the content from "This will enable the default audit file handler..." to the end of the topic (in this unpublished file https://github.com/OpenLiberty/docs/blob/audit/temp/audit-config.adoc), and use the examples to add an Examples section in the `audit-1.0.html` topic.
  - [ ] Make use of the information and example code to provide useful, usable examples in the audit-1.0.html topic in the same way as we've done in the Examples section of https://www.openliberty.io/docs/ref/feature/#jdbc-4.3.html
  - [ ] Don't include the table of config attributes as they are already documented here: https://www.openliberty.io/docs/ref/config/#auditFileHandler.html (link to that topic in the appropriate place instead).
- [ ] Check whether the text in the table in the audit-config.adoc file is better than in the generated #auditFileHander.html file.
  - [ ] Compare the text [in the table of `auditFileHandler` attributes](https://github.com/OpenLiberty/docs/blob/audit/temp/audit-config.adoc) with the text in the table in https://openliberty.io/docs/ref/config/#auditFileHandler.html The former is sometimes better than the latter so we need to improve the latter.
  - [ ] Make a list of what updates should be made to the generated topic and paste into a comment below (we'll need development to make those updates so I'll work with you on raising that with the right person).
- [ ] When the new topic is approved and published, delete the https://github.com/OpenLiberty/docs/blob/audit/temp/audit-config.adoc file.

Contact:
Emily Tuckowski
Ask Alasdair to review as well.

Background:
The Audit feature provides a load of events (data emitted from Open Liberty) in production so that Ops teams can gather the data for audit purposes (ensuring integrity of systems, data, etc).

**Comment by Rwalls1** [comment]
@lauracowen can you update this issue what work is still needed for this issue? I created an audit.examples file but it seems to have gotten overwritten.

**Comment by lauracowen** [comment]
I wasn't aware that you'd created the file. Can you re-create it and paste a link to it here? I'm not sure why it would be overwritten but we can investigate that when you've re-created it.

**Comment by Rwalls1** [comment]
@lauracowen I have recreated the file here: https://github.com/OpenLiberty/docs/blob/draft/ref/feature/examples/audit.examples

**Comment by lauracowen** [comment]
I realised the first step in my instructions at the top of this issue wasn't very explicit so I've clarified and expanded it a bit to add some more of the info we discussed on the phone.

Please can you review all the steps of the instructions at the top of this issue (the `audit.examples` file currently only addresses the first step).

Then address the feedback below, as well as anything in the instructions not currently addressed:

- [ ] Remove the first bit about the featureManager element. That information is already in the `audit-1.0.html` topic. The `audit.examples` topic is only for the Examples section of the topic.
- [ ] Remove the table of config attributes (see my instructions above about this table).
- [ ] Take the examples from the audit_config.adoc file and edit them into the format used in the Examples section of the JDBC feature topic.
- [ ] Where there are example code snippets, remove blank lines between lines in the XML and indent lines of XML appropriately.
- [ ] For example code snippets, add `[source,xml]` tags above the opening `----` tagging in the asciidoc.
- [ ] Go through the whole topic and make highlighting consistent throughout.
- [ ] Ensure that the text throughout makes sense and hangs together. If you're not sure, ask another David or Charlotte to read it and give their thoughts.

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://github.com/OpenLiberty/docs/blob/draft/ref/feature/examples/audit.examples

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#audit-1.0.html

**Comment by lauracowen** [comment]
Thanks. I assume you applied all the changes I listed from my previous review? Did you have any problems with any of it. I still see a problem with the syntax highlighting which I mentioned previously - did you have problems getting this working?

Since you started this, we've worked through stylistic decisions on other topics like this and gradually built up some guidance. Some of the points below are changes based on that - sorry, some of the changes below might be related to that.

One caveat when you come to implement these changes: We're currently restructuring the directories for these 'include' files. Make sure you are working with the latest version of the files. The changes haven't yet been published so if you want to just get on with this, that's fine (I'll fix up the files for you before publishing - the content of the files doesn't change, just the file names and directories). I just wanted to let you know so you don't get surprised by different files!

**Some general points**
- [ ] I'm pretty sure the `[.underline]` bits shouldn't be in any of the config examples. I know they're also showing in the .adoc file you copied them from (I'm not sure why - must've been something dodgy in the .pdf file I copied them from). Can you update the config examples to remove those rogue tags because they'll break the file if copied and used for real?
- [ ] Other than the first config example, there's no syntax highlighting in the code examples. If you compare them in the source file, this is because the subsequent examples are missing the line `[source,xml]` which is present in the first example. Can you add it in for each of the examples? (The `xml` bit tells the build to display the appropriate language's syntax highlighting. If the code is, say, Java, you'd put `java` instead of `xml`, and so on.)
- [ ] In general, the examples need to be more clearly described so that an operations person coming to it without previous knowledge of what the Audit feature does, can get started with it for the most common scenarios. So I'm going to suggest some wording changes but you're welcome to suggest others if, on reflection, you think it still doesn't make sense - talk to EmilyT to ask her to explain things further as necessary to make this topic make sense.

**Audit File Handler example**
  - [ ] Change the heading to something more meaningful - if you don't know what the audit file handler is, the heading doesn't mean much. What do they achieve from it? eg "Manage the audit log files" or something better than that? (check with EmilyT whatever).
  - [ ] Remove the first sentence from that section because I don't think it adds any value. I think there needs to be a first sentence instead that is something like "The audit file handler (auditFileHandlers - link to the config topic) manages the storage space used by the log files produced by the audit." Then the second sentence can be part of the same paragraph (each sentence doesn't need to be its own paragraph).
  - [ ] Highlight attribute names and file names etc with backticks so they display in monospace (eg `audit.log` or `maxFiles`).
  - [ ] The sentence starting "The following example…" is along the right lines but is just describing what you can already see in the code example itself so doesn't really provide value by itself (every sentence in a topic needs to provide value - either technical content or context to the technical content). There is some explanation after the example but it would be useful to explain why the user might bother to set these values. So, in the lead-in sentence, you could say that "by default, the audit file handler writes audit records to an audit log file until the file reaches 20 MB size; the audit log file is then archived and a new audit log file is started. By default, the maximum number of archived audit log files is 100, after which the oldest archived log file is overwritten. The following example shows how to increase the individual file size to 100 MB and reduce the maximum number of archived audit log files to 50. The example also specifies the `compact` attribute which makes the log file, which is written in JSON, write the audit records all on the same line in the log file:"
  - [ ] Remove the whole `<featureManager>…</featureManager>` section of the example. The examples need to be as compact and focused as possible. The important bit in this example is the `<auditFileHander>…</auditFileHandler>` section so show only that.
  - [ ] If all the explanation is in the text above the example code, I think you can then remove the text below the code. The last sentence of the section "All audit events…" doesn't seem to make sense in this section - I'm not sure why it's there?

**Events section**
  - [ ] Maybe change the heading to "Logging only a subset of events" or "Specify which events to log" or something? (check with EmilyT for accuracy)
  - [ ] There seem to be two lead-in sentences at the start of this section, so it doesn't really make sense at the moment. Maybe replace with something that summarises the benefit of the settings, such as "Only certain audit events and outcomes might be relevant in a particular environment, so the `event` element can be used to specify which audit events and outcomes are captured. In the following example, only security authentication events whose outcome is success…" and so on, then show the example.
  - [ ] The example needs the `featureManager` lines removing as it's the `auditFileHandler` lines that are relevant to this example.

**Encrypting and Signing Audit**
  - [ ] Make the heading more meaningful; eg "Encrypting and signing audit data"
  - [ ] If the text refers to the name of an attribute or element, highlight the name in backticks (monospace), eg the `encrypt` attribute.
  - [ ] I think you need to break up the explanation and example to make it clearer what's happening. So, maybe end the second line of the text with a colon then put the code example line that starts "<keyStore id="auditEncKeyStore”" after it. Then do the same for the third line of text and put the code example line that starts "<keyStore id="auditSignKeyStore"" after it. Then provide an explanation of what the `auditFileHandler` line is demonstrating, followed by the line from the code example itself. (So that the lines of code are each explained separately.
  - [ ] Remove the `featureManager` lines completely.
  - [ ] Tidy up the formatting of each config example: remove `[.underline]` dodgy tags; insert break the lines at each attribute (indent each though) so that the lines don't horizontally scroll, if possible - check that the XML will still work if copied when this is done.
  - [ ] After the code example, perhaps put the "SHA256…" sentence. I'm not sure why the sentence "All audit events…" is there.

**And finally...**
- [ ] For any of the sentences I've said to remove on the basis that they don't contribute anything, check that that information is available in the separate concept topic you've been editing. It's not that the info is completely irrelevant, just that it shouldn't necessarily be in this particular topic.

**Comment by Rwalls1** [comment]
@lauracowen Please review, I think I've addressed most of the feedback. For your comment about breaking up the explanation under "Encrypting and Signing Audit", I spoke with Emily about the example and I don't think that the proposed breakdown would be accurate, I can work with her to figure out an alternative.

**Comment by lauracowen** [comment]
Okay, thanks. Looks good. I think the example is fine as it is then.

Can you do a final proofread for typos/capitalisations and consistent highlighting? Then I think this one is good to go. Thank you

**Comment by ManasiGandhi** [comment]
Some suggestions,

- "When the maximum number of archived audit logs is reached, after the audit.log file that is being written to reaches its maximum size, then the oldest archived audit log is overwritten."

Is this info necessary "after the audit.log file that is being written to reaches its maximum size,"? If it does not add any context, remove it.

- "By default, the maximum number of archived audit log files is 100 after which the oldest archived log file is overwritten."

Change to,

"Then, the maximum number of archived audit log files is 100, by default,  after which the oldest archived log file is overwritten."

to avoid repetition of the phrase 'by default' at the beginning of the sentence.

- "The example also specifies the compact attribute, which makes the log file that is written in JSON write the audit records all on the same line in the log file:" 

break up this sentence

 "The example also specifies the compact attribute. The compact attribute makes the log file that is written in JSON to write the audit records all on the same line in the log file:"

- "In the example, only the security authentication events whose outcome is SUCCESS, REDIRECT, or FAILURE, and security authorization events whose outcome includes all supported outcomes are captured."

Add a colon,

"In the example, only the security authentication events whose outcome is: SUCCESS, REDIRECT, or FAILURE, and security authorization events whose outcome includes all supported outcomes are captured."

Or maybe a bulleted list if the format allows.

- "It is important for the recorded audit data to be preserved in a way that not only can restrict access but also ensure that the data itself is tamper-proof."

change to

"It is important for the recorded audit data to be preserved in a way that can not only restrict access but also ensure that the data is tamper-proof."

- "To encrypt audit records, the encrypt attribute must be specified in the auditFileHandler element, along with the alias name of the certificate that is used to encrypt the audit data, and the keystore in which that certificate exists."

change to

"To encrypt audit records, the encrypt attribute must be specified in the auditFileHandler element, in addition to the alias name of the certificate used to encrypt the audit data, and the keystore in which that certificate exists."

- Similar for this sentence "To sign audit records, the sign attribute must be specified in the auditFileHandler element, along with the alias name of the certificate that is used to sign the audit data, and the keystore in which that certificate exists."

change to

"To sign audit records, the sign attribute must be specified in the auditFileHandler element, in addition to the alias name of the certificate used to sign the audit data, and the keystore in which that certificate exists."

**Comment by lauracowen** [comment]
https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#audit-1.0.html

**Comment by lauracowen** [comment]
I broadly agree with Manasi's points above but have slightly different suggestions for some of them:

- first and second bullet points - make a good point but I think I'd solve it by combining the second and third paragraphs - the information given in the second para is repeated in the third. The info about the default max number of logs should be with the info about what happens when the max number of logs is reached.
- third bullet - I'm not sure this suggestion would add much - the current sentence reads ok, I think?
- fourth bullet - I don't think a colon is correct here but I think her point is right that the sentence is a bit long and windy to understand: "In the example, only the security authentication events whose outcome is SUCCESS, REDIRECT, or FAILURE, and security authorization events whose outcome includes all supported outcomes are captured." Maybe try re-writing as something like "In the example, the only events that are captured are security authentication events whose outcome is SUCCESS, REDIRECT, or FAILURE, and security authorization events with any outcome."
- fifth bullet - again, I agree with the point but I don't think the suggestion is technically accurate (the meaning subtley changes). I think I'd suggest "It is important for the recorded audit data to be preserved in a way that not only restricts access but also ensures that the data itself is tamper-proof."
- sixth and seventh bullets - I think this is a matter of taste. :)

Thanks both for this. After addressing these points, I think this topic is good to go.

**Comment by Rwalls1** [comment]
@lauracowen Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#audit-1.0.html

**Comment by lauracowen** [comment]
Hi Richard, I know I was ready to sign this off before but, on taking another look (now we've got a clearer idea of what the Examples section should provide), I think it needs a bit more editing. Sorry, I know this has been dragging on for ages.

The examples look good but there's too much conceptual info in this topic and should be moved to the concept topic (sorry, I know I've just signed that topic off). This topic should just be about the config and what the examples show (see https://ibm.box.com/s/v3oejxfcv1e63me9hxgot3qdkjrmjby4). Explanation about the concept should be in the concept topic.

For example, in the Managing audit log files section, most of the text should really go in the Audit handler section of the concept topic (explaining how the audit logs work). In this topic, assume they understand that (because they've already read about it in the concept topic) and now they just want to know how to configure it. So move everything from that section above the sentences "The following example shows...". And move the explanation from beneath the example too as that also talks about how the logging files works.

For the Specifying the logging of events section, again, make sure the conceptual info is in the concept topic, then edit the text here so that it deals only with what's in the example (eg "AuditEvent_1 is captured if its outcome is SUCCESS"), don't comprehensively describe anything not in the example (that info should be in the concept topic).

Encrypting section - again, this info should be a section in the Audit concept topic, then just have the example and some explanation about what the example shows.

You might need to create some additional sections or sub-sections in the concept topic. Sorry, I know this one has bounced around a bit and I didn't catch these points earlier. I discussed it with David to get his thoughts, so please get him to take a look when you've made updates to both topics and then I'll re-review. Thanks

**Comment by Rwalls1** [comment]
@NottyCode Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#audit-1.0.html

**Comment by NottyCode** [comment]
The code examples have an escape character where there should be none. For example:

    <keyStore id="auditSignKeyStore" password="\{#xor#}EzY9Oi0rJg==" location="$\{server.config.dir}/resources/security/AuditSigningKeyStore2.#jks#" type="JKS" />

the \ before { should not be there. The # around jks and xor should not be there. No example should use xor encoded passwords, it should be aes.

The first example should either be broken up, or the description should be collapsed to a single sentence.

> The following example shows how to increase the individual file size to 100 MB and reduce the maximum number of archived audit log files to 50. The example also specifies the compact attribute, which makes the log file that is written in JSON write the audit records all on the same line in the log file

I would choose a different title to this:

> Specifying the logging of events

perhaps:

> Configuring the events to log

I'd like an example of configuring the audit data to be fed into the json log format since that is likely going to be popular in kubernetes.

**Comment by rw2513** [comment]
@lauracowen Please review, I think I've addressed most of the feedback: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#audit-1.0.html

**Comment by Rwalls1** [comment]
@lauracowen Please review, I think I've addressed most of the feedback: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#audit-1.0.html

**Comment by lauracowen** [comment]
Thank you!

**Comment by Charlotte-Holt** [comment]
@rw2513 Peer review feedback:

Looks good, just a few things:
- In, "The following example shows how to increase the individual file size to 100 MB, reduce the maximum number of archived audit log files to 50, and specify the compact attribute:", I think that "compact" should be in backticks since it's an attribute.
- In, "... the `<events>` element can be defined with...", I don't think that `<events>` needs the side brackets around it. The other element (`auditFileHandler`) doesn't have them. 
- In, "...how to configure the audit feature...", I think that "audit" should be capitalized since it's the proper name of the feature.

**Comment by Rwalls1** [comment]
@Charlotte-Holt Thanks, I've addressed your feedback.

**Comment by Rwalls1** [comment]
New link to topic: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/audit-1.0.html

**Comment by dmuelle** [comment]
need to replace `${server.config.dir}` variable with an example (use `server1` for consistency ) per #1877. Once the file is updated, please mark it off from the checklist in that issue- thanks!

**Comment by Rwalls1** [comment]
PR: https://github.com/OpenLiberty/docs/pull/1653/files

**Comment by Rwalls1** [comment]
Editing Reference: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch06.html

**Comment by dmuelle** [comment]
Doc is now on vNext branch, will publish with 20.0.0.12 on 11.20

**Comment by chirp1** [comment]
Hi Richard, The examples look good! Just one sentence to tweak:

- For "Manage audit log files", reword the sentence. Use the descriptions in https://openliberty.io/docs/21.0.0.7/reference/config/auditFileHandler.html. You're not showing how to increase or decrease. You're setting the maximum size of files and the maximum number of archived audit log files. Also, state what compact does in a few words.

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.8/reference/feature/audit-1.0.html

**Comment by chirp1** [comment]
Hi Richard,
- One last update- Highlight 100, 50, and true in the "Manage audit log files" section. After you  make the update, you can move this issue directly to the Ready to Publish column - no need to give it back to me.

**Comment by Rwalls1** [comment]
Staging: https://staging-openlibertyio.mybluemix.net/docs/21.0.0.8/reference/feature/audit-1.0.html

**Comment by Rwalls1** [comment]
Updates have been merged to Vnext and will publish with 21.0.0.8
