### ISSUE TITLE
typo in metrics topic

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/docs#2153]
at https://openliberty.io/docs/20.0.0.7/microservice-observability-metrics.html:

`@SimpleTimed` -> `@SimplyTimed`

**Comment by dmuelle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/microservice-observability-metrics.html

Typo fixed on draft, changes will go to production with 20.0.0.9, leaving this bug open until they publish

**Comment by dmuelle** [comment]
fix delivered to vNext in #2361
