### ISSUE TITLE
Some feature names are inconsistent in the reference section

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2193]
The following feature names don't follow the correct format for feature names:

- [JMS 2.0 Client for Message Server](https://openliberty.io/docs/20.0.0.8/reference/feature/wasJmsClient-2.0.html)
- [Java EE 8 Application Client](https://openliberty.io/docs/20.0.0.8/reference/feature/javaeeClient-8.0.html)
- [JavaScript Object Notation Binding 1.0 via Bells](https://openliberty.io/docs/20.0.0.8/reference/feature/jsonbContainer-1.0.html)
- [JavaScript Object Notation Processing 1.1 via Bells](https://openliberty.io/docs/20.0.0.8/reference/feature/jsonpContainer-1.1.html)
- [Spring Boot Support version](https://openliberty.io/docs/20.0.0.8/reference/feature/springBoot-2.0.html)
- [OpenID Connect Client](https://openliberty.io/docs/20.0.0.8/reference/feature/openidConnectClient-1.0.html) - issue opened in the `open-liberty` repo a bit back: https://github.com/OpenLiberty/open-liberty/issues/11703

We need to figure out which files to update, confirm that we can make these updates, and get the feature names into the correct format. See the [Application Security feature](https://openliberty.io/docs/20.0.0.8/reference/feature/appSecurity-3.0.html) for an example of the correct feature name format. For the Spring Boot Support version feature, find out what the correct name of the feature should be. I think maybe just "Spring Boot Support"? If so, the navigation also needs to be updated to reflect the correct feature name.

**Comment by mbroz2** [comment]
The first 4 are correct, and purposefully have the name not at the end.  For the last two, here are the issues that will resolve them:
Spring Boot Support version: https://github.com/OpenLiberty/open-liberty/issues/13422
OpenID Connect Client: https://github.com/OpenLiberty/open-liberty/issues/11703 & https://github.com/OpenLiberty/open-liberty/issues/13426

I think this issue can be closed now.

**Comment by Charlotte-Holt** [comment]
Thanks for confirming, @mbroz2. Closing the issue.
