### ISSUE TITLE
Move About page content to docs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#223]
https://openliberty.io/about/

The critical info from this page (to answer "what is Liberty and why should I care?") should be on the homepage. Visitors will expect it to be there and not have to navigate to a separate About page. If they want to learn more detail, they'll seek out the Docs.

In the Docs there should be an About Liberty section introducing Liberty (and MicroProfile) with architecture etc.

Though, actually, I was mis-remembering what was on the About page at the moment (was thinking it was more like this: https://wasdev.net/about) and probably when we've done the new homepage, most of it will be redundant and not missed if we remove the About page.

Keeping this issue for now as a reminder to review the About page when we've done the new homepage and check if there's anything that needs capturing in the Docs; eg maybe mentioning the other vendors in an intro to MicroProfile?

**Comment by lauracowen** [comment]
https://openliberty.io/about/

The critical info from this page (to answer "what is Liberty and why should I care?") should be on the homepage. Visitors will expect it to be there and not have to navigate to a separate About page. If they want to learn more detail, they'll seek out the Docs.

In the Docs there should be an About Liberty section introducing Liberty (and MicroProfile) with architecture etc.

Though, actually, I was mis-remembering what was on the About page at the moment (was thinking it was more like this: https://wasdev.net/about) and probably when we've done the new homepage, most of it will be redundant and not missed if we remove the About page.

Keeping this issue for now as a reminder to review the About page when we've done the new homepage and check if there's anything that needs capturing in the Docs; eg maybe mentioning the other vendors in an intro to MicroProfile?

**Comment by lauracowen** [comment]
Find the WASdev About page content here: https://github.ibm.com/was-WASdev/WASdevnet-website/blob/master/developer.ibm.com/wasdev/websphere-liberty/index.html

**Comment by mbroz2** [comment]
See YK's recent comment regarding this here:
https://github.com/OpenLiberty/openliberty.io/issues/1584#issue-587198214

**Comment by lauracowen** [comment]
Right, having chatted briefly with @yeekangc, can we:

- remove/delete the `/about` page completely
- create a redirect from `/about` to the homepage (which now contains all that info and more)

**Comment by mbroz2** [comment]
Yes, I'll update https://github.com/OpenLiberty/openliberty.io/issues/939 to reflect the decision of redirecting /about to the homepage (instead of some /doc/[page])

**Comment by mbroz2** [comment]
In which case, I think we can close this issue.

**Comment by lauracowen** [comment]
closing. We'll have #951 for the docs and see above re redirecting.
