### ISSUE TITLE
Update nav.adoc file

### ISSUE THREAD

**Issue by ellenwyllie** [OpenLiberty/docs#2324]
The nav.adoc file needs to be updated with "Java EE Application Client" instead of "Java EE 8/7 Application Client". We just want the ToC to show "Java EE Application Client" like this:
<img width="805" alt="Screen Shot 2020-08-11 at 1 16 43 PM" src="https://user-images.githubusercontent.com/22085207/89933613-eaf9a380-dbd4-11ea-995b-fc4575e191fe.png">

**Comment by dmuelle** [comment]
@ellenwyllie @mbroz2 

I've updated the nav on `draft` per this issue- can you review: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/javaeeClient-8.0.html

If it looks ok, I'll make a PR to staging and also backport to 20.0.0.7 and 8 as needed

**Comment by ellenwyllie** [comment]
The toc title looks good on 20.0.0.9 and it would be great if you could backport to 20.0.0.7 and 20.0.0.8 as well.

Did you end up making the title change for that doc? The title is different for 20.0.0.9 so it looks like your change might still be there. I updated the python script so that that woulnd't be necessary.

**Comment by dmuelle** [comment]
Strange- those changes never went to draft and I dont see them in the git history for the doc. What should the title be?

Right now in the file on both draft and vNext its `Java EE 8 Application Client`

**Comment by ellenwyllie** [comment]
That is very strange. `Java EE 8 Application Client` is the correct title, but that's not what I see on the draft site for 20.0.0.9. 
<img width="858" alt="Screen Shot 2020-08-12 at 3 25 08 PM" src="https://user-images.githubusercontent.com/22085207/90064195-07b6d980-dcb0-11ea-83bf-33b10dd4fcc8.png">

**Comment by ellenwyllie** [comment]
I think it's an issue with the python script so I'll debug and fix it

**Comment by dmuelle** [comment]
Changes have all posted to vNext and 20.0.0.7 & 8. Keeping this open till they go to production with 20.0.0.9

**Comment by mbroz2** [comment]
My recommendation is to close an issue once it has been delivered to vNext and/or backported to any necessary branches, as at that point the work is done and there is nothing more to do for that issue.
For reference, the development team closes their issues once it has been delivered/integrated into integration (or master) branches, and not once the product GAs every 4 weeks.

**Comment by dmuelle** [comment]
OK- point taken, closing this issue
