### ISSUE TITLE
acmeCA config examples

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#2363]
Config examples for a new Liberty feature acmeCA (SEC 27)

- concept doc for the new feature is developed in #1699 
- The feature issue is OpenLiberty/open-liberty#9017
- SME is @kristip17 

from #1699 

The acmeCA feature requires configuration. The minimum configuration requires the URL of the Certificate Authority provider and the name of one or more domains.

```
<acmeCA directoryURI="https://acme.host.com/directory" >
    <domain>mtcrumpit.com</domain>
</acmeCA>

<httpEndpoint host="*" httpPort="80" httpsPort="443" id="defaultHttpEndpoint"/>
<keyStore password="password" id="defaultKeyStore"/>
```

## Terms of Service ##
Some Certificate Authorities provide Terms of Service. The link to the ACME CA's Terms of Service is logged when it is received from the CA. If the ACME CA modifies its Terms of Service, it may require the user agree to the new Terms Of Service manually. If the user does not agree to the modified Terms of Service, the ACME CA server may refuse any future requests made by the account until the modified Terms of Service are agreed to. For this reason, it is highly recommended that the user provide an account contact that specifies a monitored email address so that the ACME CA server can warn the user about new Terms of Service and the user can agree to the new terms of service before they could possibly cause a service disruption.

```
<acmeCA ...>
    <accountContact>mailto:thegrinch@mtcrumpit.com</accountContact>
</acmeCA ...>
```

## Renew or revoke certificate: ##
If configured, the Liberty server will automatically renew expiring and / or revoked certificates. The Liberty server will renew the certificate based on the time configured from the renewBeforeExpiration property. To stop Liberty from renewing certificates based on expiration, set renewBeforeExpiration to zero. To stop Liberty from renewing certificates based on revocation status, set the 'enabled' attribute within the 'acmeRevocationChecker' configuration element to "false".

## Additional configuration tips ##
Some ACME CA providers require an initial public certificate if they are not included in the JRE's cacerts and you wish to use the HTTPS protocol to retrieve the certificate. To configure a truststore for (only) the acmeCA-2.0 feature use the 'acmeTransportConfig' server configuration element. The acmeCA-2.0 feature will still trust all certificates in the JRE's cacerts even when provided the custom truststore. 

In some cases, if fetching the certificate fails due to a configuration or temporary problem (such as network connectivity), the Liberty server must be restarted to fetch and store a certificate again.

If an email address is not provided with an account, this can result in the loss of account access, lack of expiration notification and lack of Terms of Service changes. It is strongly recommended to provide an email address with the acmeCA configuration. Liberty provides a warning when an email address is not provided in the configuration.

## Update contact address ##
To update or add a contact addresses to your ACME account, update them in the acmeCA configuration in the server.xml. When the acmeAccont configuration is changed, the ACME service will update your account on the ACME CA server.

## Tips for using a  local or test Certificate Authority##
You can test with frameworks such as Pebble or Boulder. These allow you to tests without owning the domain that the CA will call back to.

Some ACME CA providers require an initial public certificate if they are not included in the JRE's cacerts and you wish to use the HTTPS protocol to retrieve the certificate. To configure a truststore for (only) the acmeCA-2.0 feature use the 'acmeTransportConfig' server configuration element. The acmeCA-2.0 feature will still trust all certificates in the JRE's cacerts even when provided the custom truststore.

For testing purposes only with Pebble or Boulder, the `open-liberty\dev\com.ibm.ws.security.acme_fat\publish\files\cacerts.p12` can be used. No support is provided for this trustStore.

```
<acmeCA ...>
    <acmeTransportConfig trustStore="${server.config.dir}/resources/security/cacerts.p12" trustStorePassword="password"/>
</acmeCA>
```

Sample server.xml with administrator and reader roles defined for the REST API.

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<server description="Generation date: Wed May 27 16:37:32 CDT 2020">
    <featureManager>
        <feature>acmeCA-2.0</feature>
        <feature>appSecurity-3.0</feature>
        <feature>audit-1.0</feature>
    </featureManager>

<!--- Replace the directory URI with Pebble/Boulder URI --->
    <acmeCA directoryURI="https://localhost:33081/directory">
<!--- A real certificate authority like Lets Encrypt has certs by default in Java. For Boulder/Pebble, we need a local certificate to talk to them initially. Copy the cacerts.p12 from your open-liberty\dev\com.ibm.ws.security.acme_fat\publish\files directory and update the trustStore location (or use the example path). --->
        <acmeTransportConfig trustStore="${server.config.dir}/resources/security/cacerts.p12" trustStorePassword="acmepassword"/>
        <domain>domain1.com</domain>
    </acmeCA>

<!--- These roles allow you to use the REST interface for acmeCA --->
    <basicRegistry realm="basicRealm">
        <user name="administrator" password="adminpass"/>
        <user name="reader" password="readerpass"/>
    </basicRegistry>

    <httpEndpoint host="*" httpPort="5002" httpsPort="5003" id="defaultHttpEndpoint"/>

    <keyStore password="acmepassword" id="defaultKeyStore"/>
    <administrator-role>
        <user>administrator</user>
	</administrator-role>
    <reader-role>
        <user>reader</user>
	</reader-role>
    <SSLDefault/>
</server>
```

When running with containerized versions of ACME CA servers, the OCSP responder URL defined in the certificate may not be reachable. You can override the OCSP responder URL in the certificate by specifing the 'ocspResponderUrl' attribute in the 'acmeRevocationChecker' element. If this is not configured, a warning can occur during revocation checks ` CWPKI2058W: Certificate revocation status checking ignored soft failures. Revocation checking might be incomplete. The failures are: '[java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error, java.security.cert.CertPathValidatorException: Unable to determine revocation status due to network error]'.`

```
<acmeCA ...>
    <acmeRevocationChecker ocspResponderUrl="127.0.0.1:4567" />
</acmeCA>
```

Alternatively, during testing, revocation checking can be disabled.
```
<acmeCA ...>
    <acmeRevocationChecker enabled="false" />
</acmeCA>
```

**Comment by dmuelle** [comment]
This feature is now targeted for 20.0.0.10

**Comment by dmuelle** [comment]
Hi @kristip17 - now that the acmeCA autogen is in the doc build, I've added some config examples to the page, based on your original doc info from #1699. These will publish together with [that concept topic](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/acme-cert-management.html), ideally in 20.0.0.11.

They'll need some more work I'm sure but when you have a chance, take a look and let me know what you think

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/acmeCA-2.0.html

Are these examples likely to be valuable to most users of the feature? Are there any missing or should any of these be removed?

For the `Renew expiring certificates` example, I had to infer the config from other examples since I didn't have a direct example of that, probably needs a close look.

One general question I have is about closing tags- is it possible for all the examples to use a concise open/closing tag, rather than re-stating the element name in the closing tag? So instead of

`<accountContact>mailto:my_email_addr@theDomainThatIOwn.com</accountContact>`

use
`<accountContact mailto:my_email_addr@theDomainThatIOwn.com/>`

Not sure if that's viable syntax for these examples but that's how I've seen it for other feature config

**Comment by kristip17** [comment]
I think all the examples should stay in.

I will double check on the syntax.

Review comments:

You can configure the amount of time before a certificate expires that the ACME Support feature renews the certificate by specifying a value for the renewBeforeExpiration property. The default value for the renewBeforeExpiration property is seven days. In the following example, the feature requests a certificate renewal 24 hours before the expiration date:

Maybe add this before "In the following example:

When the certificate enters renew timeframe, a renew request can occur at server startup, after a configuration update or during daily internally scheduled certificate checks.

Also, I don't know if we are if we use numbers or spelled out numbers consistently (seven vs 24).

---

I know this is from my text, but let's take out "For testing purposes, Open Liberty provides the open-liberty\dev\com.ibm.ws.security.acme_fat\publish\files\cacerts.p12 certificate file. You can copy this file into a truststore that you configure for the ACME Support feature." Even if we label it for testing, we don't want to support this file if things change with pebble/boulder.

---

To configure a custom truststore specifically for the Acme Support feature, use the 'acmeTransportConfig' server configuration element, as shown in the following example:

Acme >> ACME ? 
Does 'acmeTransportConfig'  need different formatting/markdown.

---

When you run containerized versions of ACME CA server
Maybe tweak to --
When you run containerized or test versions of ACME CA server

---

There seem to be too many elements under "Feature configuration elements" -- I think only the first 3 are valid? Not sure if the links are supposed to be working yet.

--

**Comment by kristip17** [comment]
I like specific examples -- wondering if it would be too specific to add this to `Minimum configuration` (maybe at the end of that section?)

For example, to use Lets Encrypt (https://letsencrypt.org/) , the directory URL could be `directoryURI="https://acme-v02.api.letsencrypt.org/directory"` (production server) or `directoryURI="https://acme-staging-v02.api.letsencrypt.org/directory"` (test server).

**Comment by kristip17** [comment]
Could we include this server.xml with simple REST config information?

Minimum recommended configuration with REST

To use the REST APIs to view, renew or revoke the certification, add an administrator and optional reader role user. The following configuration includes an administrator role using a Basic Registry.

```
<?xml version="1.0" encoding="UTF-8"?>
          <server description="acme server">

              <!-- Enable features -->
              <featureManager>
                  <feature>acmeCA-2.0</feature>
                  <feature>appSecurity-3.0</feature> 
              </featureManager>

              <httpEndpoint id="defaultHttpEndpoint" host="*" httpPort="80" httpsPort="443" />
              <keyStore id="defaultKeyStore" password="password_for_keystore"/>

              <basicRegistry realm="BasicRealm">
                  <user name="adminuser" password="password_for_adminuser" />
              </basicRegistry>

              <administrator-role>
                  <user>adminuser</user>
              </administrator-role>

              <!-- ACME configuration. -->
              <acmeCA directoryURI="https://acme-staging-v02.api.letsencrypt.org/directory" 
                      domain="Provide_Domain_Name" accountContact="mailto:my_email_addr@theDomainThatIOwn.com" />

          </server>

**Comment by dmuelle** [comment]
Thanks for reviewing @kristip17. I've updated the doc per your review:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/acmeCA-2.0.html

- [x]   add this before "In the following example:
When the certificate enters renew timeframe, a renew request can occur at server startup, after a configuration update or during daily internally scheduled certificate checks. **done**

- [x]  I don't know if we are if we use numbers or spelled out numbers consistently (seven vs 24).
 **in general, guidance is that 1-10 are spelled out, the rest are numerals. Does look a little strange when they're close together like that**

- [x] take out "For testing purposes, Open Liberty provides the open-liberty\dev\com.ibm.ws.security.acme_fat\publish\files\cacerts.p12 certificate file. You can copy this file into a truststore that you configure for the ACME Support feature. **done**

- [x]  Acme >> ACME ? 
Does 'acmeTransportConfig'  need different formatting/markdown. **fixed**

- [x] When you run containerized versions of ACME CA server -->
When you run containerized or test versions of ACME CA server

- [x] There seem to be too many elements under "Feature configuration elements" -- I think only the first 3 are valid? Not sure if the links are supposed to be working yet.
 **The stuff under `Feature configuration elements` is autogenerated- the changes would have to come from the source code. For the broken links- that's a bug on the draft site only, which is being fixed today, hopefully.**

- [x] specific examples -- wondering if it would be too specific to add this to Minimum configuration
**I replaced the url in the example with the Lets Encrypt url you provided and added a sentence to the explanation. For the staging URL, that will go in the REST API Example**


For the REST API example- per OL docs style guidelines, we generally do not use an entire server.xml file example, or include the featuremanager code, since it's generated at the top of the page. I'll put together an example with this info that fits our style guidelines and if that doesn't work we'll figure it out.

**Comment by lauracowen** [comment]
I think this is generally clear. I'm a little wary of config examples in feature docs turning into being task topics but I think the first three config examples are fine.

The "Use a test server" is probably also fine but I wondered whether it should at least be flagged up more in the other ACME topic? Maybe not - maybe just need a link from the relevant bit of the ACME and OL section directly to the examples in Use a test server (is that possible?)?

And maybe needs some links from the feature doc back to the relevant bits of the concept topic? So that the user can find all the info whichever topic they come to first.

In general, though, as long as they find both topics, I think they get the info they need.

I'll sign off but see what you think about the above bits (both here and more generally in future issues).

**Comment by dmuelle** [comment]
Requesting peer review from @Charlotte-Holt

**Comment by dmuelle** [comment]
published at https://www.openliberty.io/docs/20.0.0.11/reference/feature/acmeCA-2.0.html

**Comment by Charlotte-Holt** [comment]
@dmuelle Peer review feedback:

### Minimum configuration
- I think it should be "LetsEncrypt" based on your other topics
- Consider monospacing "80" in "port 80"

### Renew expiring certificates
- In your ACME topic, you used the number 7 in for the default value of `renewBeforeExpiration`.

### Use an ACME test server
- "`acmeTransportConfig` configuration element" to "`acmeTransportConfig` element" maybe? I think you just used "element" elsewhere in the examples. 
- Should OCSP be spelled out on first mention? 
- Backticks instead of apostrophes around `"ocspResponderUrl"

**Comment by dmuelle** [comment]
@Charlotte-Holt thanks for reviewing. I made the following updates per your review:

- [x] I think it should be "LetsEncrypt" based on your other topics- **The correct name is "Let's Encrypt". I fixed it in the concept topic in this docbug #3091** 
- [x] Consider monospacing "80" in "port 80"
- [x] In your ACME topic, you used the number 7 in for the default value of `renewBeforeExpiration`. **fixed in the ACME topic to following the convention of writing out numerals one through ten**
- [x]  "`acmeTransportConfig` configuration element" to "`acmeTransportConfig` element" maybe? I think you just used "element" elsewhere in the examples. 
- [x] Should OCSP be spelled out on first mention? 
- [x]  Backticks instead of apostrophes around `"ocspResponderUrl"

**Comment by dmuelle** [comment]
Draft updated : https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/acmeCA-2.0.html

**Comment by dmuelle** [comment]
https://openliberty.io/docs/latest/reference/feature/acmeCA-2.0.html

**Comment by dmuelle** [comment]
Checklist edits are on vNext and will publish with the 23.0.0.10 release
