### ISSUE TITLE
Update Javadoc for MP Reactive Messaging

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/docs#2371]
Hello, I'm on the guides team and we're creating a new guide to add to our MicroProfile Reactive Messaging series. This guide covers message acknowledgement, and you can find the draft [here](http://lgdev1.fyre.ibm.com:4020/guides/microprofile-reactive-messaging-acknowledgement.html). In the guide we link to the OL docs to explain the default applied acknowledgement strategies as well as what the strategies mean. We feel like the Javadoc does not contain enough information, and needed to check the MPRM spec for more information. Could the Javadoc be updated to contain more thorough information to fill the gap? Thanks. See: [Javadocs on OL site](https://openliberty.io/docs/20.0.0.8/reference/javadoc/microprofile-3.3-javadoc.html#package=org/eclipse/microprofile/reactive/messaging/package-frame.html&class=overview-summary.html) vs [the MPRM spec](https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_acknowledgement)

**Comment by lauracowen** [comment]
@Charlotte-Holt @dmuelle  we'll need to find the code repo for the feature and raise a separate issue there. I can show you the problem though on one of our calls.

**Comment by lauracowen** [comment]
I've raised an issue for the MP developers here: https://github.com/eclipse/microprofile-reactive-messaging/issues/111

@Charlotte-Holt @dmuelle I think I'll put this in the Icebox so we can check back on it at some point (closing it would mean the whole thing is out-of-mind). Unless you have a better way to track such things?

**Comment by dmuelle** [comment]
javadoc was updated in https://github.com/eclipse/microprofile-reactive-messaging/issues/111
