### ISSUE TITLE
incorrect logging format names

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/docs#2412]
Fixes needed for https://openliberty.io/docs/20.0.0.8/log-trace-configuration.html ...

"The required format for the console. Valid values are basic or json format. By default, consoleFormat is set to basic."
->
"The required format for the console. Valid values are dev, simple, or json format. By default, consoleFormat is set to dev."

"The required format for the messages.log file. Valid values are basic or json format. By default, messageFormat is set to basic."
->
"The required format for the messages.log file. Valid values are simple or json format. By default, messageFormat is set to simple."

**Comment by dmuelle** [comment]
This page is updated on draft to fix this bug

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/log-trace-configuration.html

changes will go to production with the 20.0.0.9 release
