### ISSUE TITLE
Configuring class loaders and libraries

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#2419]
Moving information over from https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_classloader.html

Work with the SME to determine what is most relevant. @andymc12 says all the information here is up to date and would be good to bring over. Need to determine the best format, one or more task topics or a conceptual overview.

- see user comment from #1439  (Though that particular task will be developed in another issue, might inform choice of content)

SME @andymc12

**Comment by dmuelle** [comment]
- https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_use_lib.html | In containers, always package libraries with the app.

-https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_shared_libs.html | In containers, wouldn't do this.
-https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_global_libs.html | In containers, wouldn't do this.

-https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_3p_apis.html | Alasdair: yes it's relevant but best practice is not what's described. Lead with the bit that's tagged 18.0.0.3+ (that's the best practice).

**Comment by dmuelle** [comment]
see discussion in #1439 for more info

**Comment by dmuelle** [comment]
## Assessment of existing KC content

Brief summary of classloader doc in KC to help develop doc(s) for OL.io

### [Configuring class loaders and libraries for Java EE applications](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader.html)

- overview should explain why/when to configure classloading as opposed to defaults, best practices for contanerized app
- what else?

### [Using a Java library with a Java EE application](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_use_lib.html)

- how to provide a library to the app by putting it on the server?
- is this strategic? Shouldn't library be packaged with the app or use defaults?
- what are some specific use cases examples?

### [Sharing a library across multiple Java EE applications](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_shared_libs.html)

- same as the previous task, but the lib is available to multiple apps? main dif is private lib vs common lib ref
- is this strategic? Do multiple apps even run on the same server?

### [Providing global libraries for all Java EE applications](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_global_libs.html)

- Is this even a good idea? Or is it more like, "you probably don't want to do this but just in case, here's how"
- what is an example use case?

### [Accessing third-party APIs from a Java EE application](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_3p_apis.html)

- in this scenario- is the library an app needs avaialble from a third party api that OL supports? and you're enabling the app to communicate with that api via the server to load certain class libraries?
- @NottyCode commented that the part tagged `18.0.0.3` is current best practice and should be foreground- is this the core task that containerized app developers are likely to need? 
- Is it best practice to get the library from an API rather than put it on the server?

### [Removing access to third-party APIs for a Java EE application](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_no_ibm_apis.html)

- this should just be part of/ follow-on from the previous task

### [Overriding a provided API with an alternative version](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_classloader_alt_api.html)

- this seems relatively straightforward, and  _if_ it's better to package a library with the app than to get it from the server, seems like it is useful info. _But_ a comment from @andymc12 in #1439 ([here](https://github.com/OpenLiberty/docs/issues/1439#issuecomment-676621671)) suggests using `parentLast` can be problematic. How best to include/position this info? 
- if using `parentLast` is problematic, what is the preferred alternative?
-  note from KC spreadsheet: "don't doc it."
--

**Comment by dmuelle** [comment]
## Global questions

- does this topic need to reference or address solutions with the BELLS feature?
- does this topic need to reference or address the role of the `*Container` features?
- how to discuss "Java EE applications" vs "Jakarta EE applications" in this context- which term(s) to use at a high level?

**Comment by ggam** [comment]
In addition to all the configuration info, please also dedicate a section to Liberty classloading internals. https://github.com/OpenLiberty/docs/issues/1439#issuecomment-676621671 @andymc12 comment was very insightful for me (perhaps this can be a different topic)

**Comment by dmuelle** [comment]
Hi @andymc12 - the initial draft of this concept topic is ready for your review:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/class-loader-library-config.html

To start, I've just adapted the KC pages that are linked in my previous comment above. When you have a chance, let me know what other information should be included, and whether what I have so far is correct, current, and necessary.

I had a few questions about some of the info that was in these KC topics, which I'm including here under the relevant sections of the draft.

## Access third-party APIs from an application
In general, there is very little info in KC specifically about the Liberty 3rd party APIs- what they are, their purpose, what the difference between them and the defaults. As such, this section was a difficult to introduce. If there is any more context we can succinctly provide, I think it would be helpful.

---
`By default, applications do not have access to the third-party APIs that are available in Open Liberty. `

This was brought over from KC, and seems to contradict the definition of the `stable` API type, which is a default value:
`stable third-party specification APIs that are available by default for both compile and run time`

I'm assuming the distinction is between third-party APIs and third-party _specification_ APIs but wonder if it should be more clear.

---
the example in this section comes from the KC- but I'm wondering if an actual worked example, similar to the one that you provided in https://github.com/OpenLiberty/docs/issues/1439#issuecomment-676621671, would be more useful. The examples using Alexandria, Scholar, etc seem more vague than something that works through an actual use case, ie substituting Hibernate for Eclipse as a JPA provider. Unless that makes it _too_ specific to generalize.

---
## Configure an application to use a Java library that is on an Open Liberty server
Is this section necessary? Or is the config basically already covered in the previous example?

## Configure applications to use a shared library
I included this based on our recent conversation, my understanding is that it would re4ally only apply to legacy configurations as most containerized apps should be 1 per server. 

Global libraries- not sure if we should doc this, but if so, can we give more context? What's the real difference between a common library and a global library?

`You can provide global libraries that can be used by any Java™ EE application..... However, the global libraries cannot be used by other applications, for example, by OSGi applications.`

by "other applications".. does this mean other kinds of applications than Java/Jakarta EE? 

---

**Comment by andymc12** [comment]
Hi @dmuelle - overall, this looks really good.  A few comments:

- It looks like the "`" got messed up in this section (including picture since I'm not sure cutting and pasting the text would show the issue that I'm seeing - take a look at "Academy~server") :
![Screen Shot 2020-10-15 at 2 47 20 PM](https://user-images.githubusercontent.com/21365299/96179363-60942f80-0ef6-11eb-8a05-38630f7c0986.png)

- Under Configuring Global Libraries
I think I would change this first sentence from:
>Some existing configurations might need to access global libraries, which can be used by any Jakarta EE application.

to something like:
>Global libraries are available to all Jakarta EE applications in the server - this includes applications in the `dropins` directory that are not explicitly configured in the server.xml file.

That gives a little more background on the use case for global libraries.

Other than that, I think it looks great!  Thanks so much!

**Comment by dmuelle** [comment]
Thanks for reviewing @andymc12,  made the following changes per your review

- fixed formatting error
- updated first sentencee under Global libraries and added mention of dropins directory in the page introduction.

If any further changes are needed, let me know, If it looks good, can you add the `technical reviewed` label to this issue? 

Per our Slack convo, we can work in the diagram from  https://github.com/OpenLiberty/docs/issues/1439#issuecomment-676621671 once you've had a chance to revise it.

**Comment by andymc12** [comment]
Looks good to me - thanks @dmuelle!

**Comment by dmuelle** [comment]
@lauracowen this topic is ready for your review

**Comment by dmuelle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/latest/class-loader-library-config.html

**Comment by lauracowen** [comment]
Thanks! I like the examples - much clearer like this than in fragmented task topics.

Really minor things:
- "In the following example," is mentioned twice in the same paragraph for the same example. Is it possible to tweak the wording a bit so that's not necessary? (doesn't really matter if not)
- Don't think you need "The" at the start of the See also link. Just "classloader configuration element" would be fine/easier to read.

Aside from that, I'll sign it off.

**Comment by dmuelle** [comment]
Thanks @lauracowen - I fixed both items you cited.

requesting peer review from @ManasiGandhi

**Comment by ManasiGandhi** [comment]
@dmuelle Peer review. The doc looks good! A few suggestions

**Title**

- [x] Can the title be “Class loader configuration”? Not sure if it is technically correct, but the current title implies both that it is (Class loader + Library) configuration, and (Class loader)+ (library configuration).

- [x] In the second paragraph, it says “For example, the servlet APIs are available by default if the Java Servlets feature is enabled. By default, each application can access these provided APIs and any internal classes and libraries that are packaged with the application.” Maybe start the second sentence differently, for example, “Also, each application can access these”, or “Further, each application can access these, each application can access these”, to avoid repetition of “By default”

**Access third-party APIs from an application**

- [x] “To learn what third-party APIs are available for an Open Liberty feature, see the feature documentation.” Do you plan to add a link for the “feature documentation” sometime?

**Configure applications to use a shared library**

- [x] “In containerized environments, typically only one application runs on an Open Liberty.” Here, do you mean “runs on an Open Liberty server” or “runs on Open Liberty”?

**Comment by dmuelle** [comment]
Thanks for reviewing @ManasiGandhi. I made the following changes per your review:

- changed title to "Class loader configuration". 
- removed 2nd instance of "default" from the sentence you mentioned
- reworded the feature documentation" sentence to make it more clear that it would be a different page depending on the feature- "To learn which third-party APIs are available for an Open Liberty feature, see the documentation for that feature."
- added "runs on an Open Liberty server”

-----
Edits for concreteness & clarity in #3491 
- Use specific language- distinguish between common and private library refs and make example clearer-->
- Make code examples and samples easy to use "
-  Eliminate wordiness (intro)
- Use technical terms consistently and appropriately (consistently use an article before "server" or "application")

**Comment by dmuelle** [comment]
https://openliberty.io/docs/latest/class-loader-library-config.html

**Comment by dmuelle** [comment]
edited content is on vNext and will publish with 23.0.0.10- closing as completed
