### ISSUE TITLE
Host IBM API/SPI JavaDoc

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/docs#2422]
Looking at the documentation I accidentally found some features export IBM APIs and also SPIs (that I guess would be used with `bell`s) that look interesting. See https://openliberty.io/docs/20.0.0.8/reference/feature/servlet-4.0.html#_spi_packages_provided_by_this_feature for an example.

However, the JavaDoc for those classes is not available on openliberty.io. Google takes me to ibm.com where some links are even broken.

I suggest hosting that JavaDoc and linking to it directly from the list of exported packages (same for Jakarta EE and MP, which are already hosted).

**Comment by Charlotte-Holt** [comment]
Thanks, @ggam! We have issue #1430 open for this. Closing this issue.
