### ISSUE TITLE
Update the contributing doc

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2426]
Update https://github.com/OpenLiberty/docs/blob/vNext/CONTRIBUTING.adoc with the new branch structure.

**Comment by Charlotte-Holt** [comment]
@lauracowen I made a few updates to the contribution doc to make it accurate for people who might want to contribute to the OL docs. I'm not sure I got the line right for where we'd expect contributors part to stop and OL docs members to pick up publishing, but I gave it a shot! Let me know what you think: https://github.com/OpenLiberty/docs/blob/draft/CONTRIBUTING.adoc.

**Comment by lauracowen** [comment]
I think that works. :)

**Comment by Charlotte-Holt** [comment]
Cool :) I'll merge to `staging` and `vNext` and close this out.

**Comment by Charlotte-Holt** [comment]
https://github.com/OpenLiberty/docs/blob/vNext/CONTRIBUTING.adoc. Closing this issue.
