### ISSUE TITLE
Server process info

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#256]
From this topic: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_server.html

Shouldn't be in the server command ref topics. Overlaps with Config Overview topic (https://openliberty.io/docs/ref/config/). Do we need to integrate it there? Or do something else with it?

Topic currently included here: https://github.com/OpenLiberty/docs/blob/master/ref/commands/server/server-serverprocess.adoc

**Comment by dmuelle** [comment]
closing- work was completed in other issues
