### ISSUE TITLE
Update Logstash Collector source description

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/docs#2581]
For https://openliberty.io/docs/20.0.0.9/reference/config/logstashCollector.html:
Change the description for `source` from:
Specifies a source to be used by the logstash collector.
->
The list of comma-separated sources used by logstash collector. Valid values are` message`, `trace`, `accessLog`, `ffdc`, `garbageCollection` and `audit`. Note: To use the audit source, enable the Liberty audit feature.

**Comment by lauracowen** [comment]
Hi thanks @Yushan-Lin - I think this issue should go in the `open-liberty` repo as it's part of the runtime. Could you make a PR directly to update the relevant files, pls? You could have someone in ID review the PR I guess?
