### ISSUE TITLE
Jakarta and Java EE API landing pages 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2610]
See #1960 for other landing pages.

**Comment by Charlotte-Holt** [comment]
Related to #2611

**Comment by dmuelle** [comment]
Jakarta EE 9 moved to 21.0.0.12

**Comment by dmuelle** [comment]
Also create a Java EE page- per slack conversation with @mbroz2 , we will have separate landing pages for Java and Jakarta APIs

**Comment by dmuelle** [comment]
changes are on vNext, will publish with 21.0.0.11
