### ISSUE TITLE
Reactive Java (MP40)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#264]
Don't start working on this until there's more reactive support in Liberty.

Introduction to reactive programming in Java with:
- MP Reactive Streams Operators
  - see https://openliberty.io/blog/2019/04/26/reactive-microservices-microprofile-19004.html
- JAX-RS reactive extensions
  - see https://openliberty.io/blog/2019/04/10/jaxrs-reactive-extensions.html
- MP Reactive messaging

Contacts:
 - Andy McCright 

Starting point:
 - Talk to Andy about what questions the information should answer about reactive programming with Java (to be able to write reactive apps that run on OL) and work out a rough skeleton topic or topics.

Resources: 
- https://www.youtube.com/watch?v=WU8x8AIsqjQ&feature=youtu.be
- Reactive OL guides
- https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_microprofile_reactive_messaging
- https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging.html
- https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_acknowledgement

**Comment by hutchig** [comment]
GH to write summary of what questions they should expect to be answered by this topic
then get reviewed by Andy McCright.
The article at https://www.openliberty.io/docs/ref/general/#concurrency.html might give some idea of an example.

**Comment by chirp1** [comment]
Here is the issue for a 19.0.0.9 blog post: https://github.com/openliberty/open-liberty/issues/6682 and the gist for the blog post https://gist.github.com/Azquelt/056e096f3879ed66f2adfc54a0b3b230 The feature is mpReactiveMessaging-1.0

**Comment by Charlotte-Holt** [comment]
Opened #2806. Closing this issue.
