### ISSUE TITLE
Server-sent events (MP39)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#266]
What they are and why they're useful. For example, @andymc12 has an example of how a transaction can be completed in one microservice and then it can notify another microservice about it so that the second microservice can act on that information.

Contact:
Andy McCright

And see his blog post: https://www.linkedin.com/pulse/my-favorite-part-jax-rs-21-implementers-view-j-andrew-mccright/ (technically his copyright, not IBM's so make sure he approves etc if you use any of it verbatim).

**Comment by dmuelle** [comment]
we now have a [guide for SSE](https://www.openliberty.io/guides/reactive-messaging-sse.html)
