### ISSUE TITLE
Formatting improvements for command topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#267]
Add [source,sh] to each of the server command usage examples (cos they're shell commands)

To generate… should be more descriptive than instructional.

Syntax at the top before Usage examples.
Don't need to explain 'servername' or 'options' - find common way to show it's an input parameter eg angle brackets. Options further down after that. In Options table, collapse 'include' together.

Priority: Low

**Comment by Charlotte-Holt** [comment]
Check the variable syntax
