### ISSUE TITLE
Microservice metrics for observability

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#270]
What are metrics in microservices? Why are they important? What uses do they have? What types of metrics can you get from apps, from the server runtime, from  can connect to data stores and monitoring tools, etc.

- Talk in terms of annotating code, not the metrics registry approach that's currently prioritised in the [KC topic](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_mp_metrics_add.html) (the MP Metrics spec literally says: “It will be possible to use the non-annotations API, but using the annotations will generally be easier for developers.”. 90% of developers will use only the annotations so this is what we should focus on.)

Start from this draft in Box: https://ibm.box.com/s/yi55q3jmriacn4ijsy82mlm4sbi09pxs (I'm still working on what should be included in the topic so it might change.)

Related links:
- Topic: MP Metrics annotations
- Guide: https://openliberty.io/guides/microprofile-metrics.html
- Topic: MP FT metrics
- Web: https://prometheus.io/docs/instrumenting/exposition_formats/
- feature doc for mpMetrics feature [shows how to enable it]
- Javadoc for the annotations which define the fields that can be set on the annotations.

Contacts:
Don Bourne (or someone he can nominate from his team)
Felix Wong

**Comment by lauracowen** [comment]
Shout when you're ready to start this - there's something I need to check before my notes in the boxnote are ready.

**Comment by lauracowen** [comment]
Following on from our discussion last Thurs, see #273 re the metrics catalog background.

**Comment by lauracowen** [comment]
Javadoc links for developers implementing each type of metric:

- Counted: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Counted.html
- Gauge: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Gauge.html
- Metered: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Metered.html
- Timed: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Timed.html

General Javadoc for Metrics annotations: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=overview-summary.html

**Comment by lauracowen** [comment]
@Charlotte-Holt  There are some changes to MP Metrics in the 19007 release. If you agree, you could incorporate those changes into this work and then we'll plan this topic to publish in line with the 19007 release (rather than as soon as it's ready to publish). I'm not sure how significant the pages are.

Can you meet with @Channyboy when he's back on Monday, show him what you're working on already and get his input on what would need adding/changing for 19.0.0.7?

I believe some of the changes will have an impact on apps using MP Metrics already and will require some migrating effort. Don't address the migration impact in this topic - just assume they're writing the app with the latest version. But, ask @Channyboy to write a paragraph or so about what a developer needs to do to migrate their app between versions and to send that to me (I'll arrange to publish a separate blog post about it and some other stuff at 19007 release, which you can link to from this topic).

**Comment by Charlotte-Holt** [comment]
Link to draft site: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#monitoring_microservices_w_metrics.html

**Comment by Charlotte-Holt** [comment]
@lauracowen @fmhwong I've made further updates to this topic at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#monitoring_microservices_w_metrics.html. Can you please review this topic and provide feedback? Let me know what changes may need to be made. Thanks!!

**Comment by fmhwong** [comment]
@Channyboy Please review ^^^

**Comment by lauracowen** [comment]
@Charlotte-Holt 

- Can you change the file name to be more similar to the new title? eg microservice_observability_metrics.adoc
- I wonder if there should be a summing up sentence or two at the end that says something like "these types of metrics are available to add to your applications to make them observable. In production, operations peeps (not sure what the best term is) can use these metrics to monitor the application, along with metrics that are automatically emitted from the JVM and the Open Liberty server runtime." then when we have the catalogue topic, link to that topic for a full list of metrics (the link doesn't need to be really prominent - could just be at the end of the topic as 'See also' - because the developer might not care so much about the non-app metrics, but it would be good to link them together).
- Could do with adding links to the Javadoc (either for each type of metric maybe or just at the end of the topic as 'See also' links.

In general, though, looks good! See what @Channyboy thinks.

**Comment by Charlotte-Holt** [comment]
We need to make sure to add a link to this topic (once completed) to the MP Metrics Migration blog post and the 19.0.0.7 release blog post.

**Comment by Charlotte-Holt** [comment]
Thanks for the feedback, @lauracowen! I incorporated your updates: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microservice_observability_metrics.html. @Channyboy, please review and let me know if you have any suggested changes.

**Comment by Channyboy** [comment]
Looks good! LGTM!

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/ref/general/#microservice_observability_metrics.html. This topic also finished up part of #332.
