### ISSUE TITLE
Create server status topic

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#271]
We need a topic under the 'Server commands' section for 'server status'. We'll also need this included on the 'Server commands overview' page. 
- See https://www.ibm.com/support/knowledgecenter/SSD28V_9.0.0/com.ibm.websphere.wlp.core.doc/ae/twlp_admin_script.html. 

For relevant server commands, see attached Word doc. 
[Exit Codes Sections.docx](https://github.com/OpenLiberty/docs/files/3188528/Exit.Codes.Sections.docx)

**Comment by Charlotte-Holt** [comment]
@lauracowen @cbridgha I created the `server status` command page and added it to the server commands overview. Please review and let me know what additional information may be necessary:

- https://draft-openlibertyio.mybluemix.net/docs/ref/command/
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-status.html

**Comment by cbridgha** [comment]
This looks good...  very simple command with no known options

**Comment by Charlotte-Holt** [comment]
This is live at https://openliberty.io/docs/ref/command/#server-status.html and https://openliberty.io/docs/ref/command/#server-commands.html. Closing the issue.
