### ISSUE TITLE
Metrics catalog (MP29)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#273]
Create a catalogue of all the metrics in a single topic, regardless of where they come from. This is for Ops people who are working with microservices in production. The developer has set up a bunch of app metrics and the server itself and JVM can emit metrics to the /metrics endpoint too. The Ops person has to set up a system to collate all those metrics (eg using Prometheus) and stick them in a database. They can then visualise the data in a dashboard (eg Grafana) and analyse the data to monitor the microservices/system.

Could sub-divide (or otherwise indicate in some way) the metrics that are vendor-specific (and need monitor-1.0 enabled as well as the mpMetrics feature) but otherwise "it is interesting to almost nobody" (Don Bourne) that there are base vs vendor vs other - not useful categories.

Having a single place to find all the metrics would be great - other appservers don't do it and it makes it really hard to find a full list of them. Ops people would find it really useful to be able to see a complete list of all the available metrics regardless of where they come from. Inc the app metrics, basic JVM metrics, the vendor-specific metrics that we've done (monitor-1.0), eg connection pool, etc, and the fault tolerance metrics.

Target audience is both developers and ops - see if it's possible to make this make sense for both.

**Comment by Charlotte-Holt** [comment]
Hi @Channyboy, could you take a look at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics_catalog.html and let me know what changes may be required. Are there any metrics that I'm missing? Thanks!!

**Comment by lauracowen** [comment]
In general, I really like the topic. One question (@Channyboy you might have a strong opinion on this?):

Is it necessary to split the tables by ‘vendor’ vs ‘non-vendor’. Could we instead have a single table with an asterisk or something marking the Open Liberty-specific metrics, and have a brief explanation that those marked metrics require the `monitor-1.0` feature to be enabled as well (and link to that feature). I’m not sure the emphasis on vendor-specific vs non-vendor-specific is that useful other than for config.

(I know I mentioned it as a potential division of the metrics in the issue but I was quoting something Don said, and he wasn't that keen for it IIRC.

**Comment by Charlotte-Holt** [comment]
Updated: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics_catalog.html. 

Looking a little better. @lauracowen, I incorporated some of the changes that we talked about. @Channyboy, I updated the classloader metrics that you mentioned to me. 

We still need to determine whether we want the tables separate or consolidated.

**Comment by Channyboy** [comment]
I think separate tables are fine? I don't particularly have a strong opinion 

But going off that idea, should we also asterisk  the `ft.*` metrics since those are fault-tolerant related and are only available when fault-tolerance annotations are used. Otherwise there won't be any `ft.*` metrics.  

Or fault tolerance related metrics might need a new table or section?

OR vendor + non-vendor metrics can be put together with asterisks indicating which ones are vendor metrics AND fault tolerance metrics are in another section/table?

**Comment by lauracowen** [comment]
For the fault tolerance metrics, there could be a different symbol or the description for each FT metric could just state something like "Available when fault tolerance annotations are used." or something?

**Comment by Channyboy** [comment]
@lauracowen  Both sound good to me? I don't quite have a preference between the two. I'm not sure which one is more _usability_ friendly?

**Comment by Charlotte-Holt** [comment]
@lauracowen @Channyboy 
I think I like the idea of consolidating all the metrics into one alphabetized table. 

Then, have an asterisk (`*`)with the note:
```This is a metric that is specific to Open Liberty. Enable the `monitor-1.0` feature to gather this metric data.```

And then maybe a (`^`) with the note:
```This metric is available when fault tolerance annotations are used.```

**Comment by lauracowen** [comment]
@Charlotte-Holt Yes, I like that approach and those words.

**Comment by Charlotte-Holt** [comment]
@lauracowen Cool. I'll update this and rebuild it today for you both to look at.

**Comment by Charlotte-Holt** [comment]
@lauracowen @Channyboy Updated! What do you think? 

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics_catalog.html

Do the asterisks/carets look okay? I also took out the threadpool metrics at @Channyboy's request.

**Comment by lauracowen** [comment]
I like the table. I don't think the asterisks/carets are clear enough at the moment :( I think the approach is right but the font is making them really indistinct. Not sure what to suggest... I also wondered whether there is a way to handle that kind of thing for accessibility in general (I guess Karen would know)?

Can you collapse the caption into the previous paragraph (ie don't have the caption), or just remove the 'Table 1' title if you want to keep the asterisk/caret info in the italics - we don't label tables elsewhere because we don't generally need to refer to tables from anywhere but the text immediately surrounding them.

What were the threadpool metrics?

**Comment by Charlotte-Holt** [comment]
@lauracowen, I agree. They were hard to read :-( I updated the table to use star and diamond HTML character references. What do you think of this? I think you're right, though, that I should check with Karen about accessibility in these instances. 

I got rid of the "Table 1. Open Liberty metrics." part of the caption and updated the rest. 

@Channyboy mentioned to me that we didn't implement threadpool.activeThreads{pool=%s} and threadpool.size{pool=%s} since they were optional. He said that they could be implemented by another company with their server, but since it's an OL doc, and we don't have them, they probably shouldn't be included here.

**Comment by lauracowen** [comment]
Those icons are easier to read - maybe look like a dodgy character rendering but with the explanation at the top it may be okay. Yes, see what the accessibility guidance is. What happens if you use the original asterisk and caret outside of the monospace font?

**Comment by Charlotte-Holt** [comment]
@lauracowen @Channyboy I made more changes. Please review https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics_catalog.html and let me know what else you think may need updating. Thanks!!

**Comment by Channyboy** [comment]
Hmm, the fault tolerance related metrics seems a little bit awkward to figure out (i.e they have to read the description). She would also mention from what type of fault tolerant annotations the metric may stem from?

**Comment by Charlotte-Holt** [comment]
@Channyboy, based on our discussion today, I updated the topic: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics_catalog.html. Does this work in enough of the information about the FT annotations? 

@lauracowen What do you think of this update?

**Comment by Channyboy** [comment]
Looks good!

**Comment by lauracowen** [comment]
Looks good to me too. I think the `ft` prefix makes it easy to spot once you've seen the description of a couple of them. Having the annotations makes sense and seems useful. :) Thanks for sticking with this, both!

**Comment by donbourne** [comment]
- might work better to say if it's a base or vendor metric instead of the OL designation (and then have some description to say what base and vendor metrics are)
- needs to mention that these are the metric names from mpMetrics-2.0
(which aren't the same as metrics names from mpMetrics-1.1)

**Comment by lauracowen** [comment]
@donbourne

- The wording is my fault. I wasn't sure that 'base' vs 'vendor' would mean much as terms to the ops people using the metrics but if you think they're fine to use, ok.
- Are there likely to be people using mpMetrics-1.1 in production now who would be confused by us just documenting the later version?

**Comment by donbourne** [comment]
@lauracowen 
I think if we have trouble ourselves classifying a particular metric than the likelihood of it really mattering to customers is small.  For that reason I'd probably suggest we skip the "OL" categorization, and I've suggested to @Charlotte-Holt that we publish without any classification as a first shot at this.

Yes - mpMetrics-1.1 name would be useful to add as well as another column.  Our current list of names is all mpMetrics-2.0.

**Comment by lauracowen** [comment]
If we have the Metrics-1.1 names as a separate column, the Metrics-2.0 column should go first because that's the one we want to encourage people to use. It's fine for the first column then to have the only emphasis, as that's the more important one.

**Comment by lauracowen** [comment]
When I shrink the width of my browser window, it can only wrap the contents of the last column. The first two columns are limited by the width of the longest metrics name. Not sure what we can do about that though.

**Comment by lauracowen** [comment]
Yes. I'm not sure that there's anything we can do about that though. @steven1046 do you have any ideas?

**Comment by lauracowen** [comment]
> I do not see an easy way for us to control the other cells wrapping.

Yes, I don't think there's anything we can do about it whilst still providing this information.

**Comment by Charlotte-Holt** [comment]
@donbourne, updated! 

@lauracowen, since we don't see a way to fix the wrapping, do you think this one is ready to publish?

**Comment by lauracowen** [comment]
Yes, if the content is all good, I'm happy to publish.

**Comment by Charlotte-Holt** [comment]
Published at https://openliberty.io/docs/ref/general/#metrics-catalog.html. Closing this issue.
