### ISSUE TITLE
SSO Hyperlinks are not working

### ISSUE THREAD

**Issue by wrodrig** [OpenLiberty/docs#2741]
The following hyperlinks are not working

Here is the link
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html
Under SPNEGO the hyperlink
 **Configuring SPNEGO authentication in Open Liberty.** is not working. 

Also under SAML
You can configure Open Liberty to enable SAML single logout. SAML single logout is a near-simultaneous logout of a user from a specific authentication session and from all active service provider sessions that are associated with the authentication session. Single logout can be initiated by both the service provider and the identity provider. To configure SAML for your application, you can enable the **samlWeb** feature.

samlWeb is not working

**Comment by Rwalls1** [comment]
@wrodrig Please review, I've fixed the links:https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html

**Comment by wrodrig** [comment]
Hi, 
Thank you for your review. It seems like some of the links two links that were reported are now working but now, the Transport Layer Security TLS hyperlink is broken:
 
You can configure Transport Security Layer (TLS) to encrypt communication between services for any SSO method that you choose so that the authentication tokens are not intercepted during transmission. For more information, see **Secure communication with Transport Layer Security (TLS).**

And the social login hyperlink is broken:
To configure Social Media Login for your application, you can enable the **socialLogin** feature.

Thanks again for all the hard work with this documentation.

Regards,

**Comment by Rwalls1** [comment]
@wrodrig Please review, the links should be fixed now: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html
