### ISSUE TITLE
SPNEGO Configuration Documentation

### ISSUE THREAD

**Issue by wrodrig** [OpenLiberty/docs#2745]
First of all I really like the new approach to this KC. Is really easy to follow and it does a good job explaining the concepts and what steps are needed for the customer to configure it. Really Good Job!

I'm still reading through the information but I wanted to briefly talk about the SPNEGO configuration article.
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html

First of all, I love that the steps to generate the keytab file and configure the Browser are clearly outlined. I'm sure that customers are also going to love it.  One suggestion is that I think that it would be awesome to add is the Liberty Configuration side as well. The reason why I recommend this, is because it makes it a lot easier for customers to know what they need to do and they would know that once they are done with the documentation, they can proceed to configure the next thing. 

I have some thoughts on how it could be done. For example, maybe at the steps at bottom of the same page. If this is not possible, could the team consider adding an arrow, or a large obvious hyperlink that says "Wait there is more...". Basically something that our customers will know that they are not done configuring SPNEGO. 

I think that would help a lot and will really enhance this documentation for both our customers and our support team. 

Thank you again so much! Really appreciate it.

**Comment by Rwalls1** [comment]
@wrodrig Please review, I've fixed the links:https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html

**Comment by wrodrig** [comment]
I found something else that might help the consideration of my proposal. I was looking at this link:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html

In the SPNEGO Section it mentions this

For more information, see **Configuring SPNEGO authentication in Open Liberty.**

Which redirects to the link that this issue is talking about. 

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/configuring-spnego-authentication.html

If we were to keep the documentation as it is, then the statement **Configuring SPNEGO authentication in Open Liberty.** will not be accurate since the above link only talks about configuring KDC and the browser. There is no mention of Open Liberty server configuration for SPNEGO. This can result in confusion for our clients.

Thanks again for your consideration.

**Comment by Charlotte-Holt** [comment]
Thanks for the feedback, @wrodrig! Moved this information over to #1479. I'll follow up with you there to address it. Closing this issue.
