### ISSUE TITLE
Should we link to the UserRegistry interface doc?

### ISSUE THREAD

**Issue by utle** [OpenLiberty/docs#2746]
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/authentication.html

-   Should we link to the UserRegistry interface?
If your application needs to reference a user registry other than a basic or LDAP user registry, you can configure a custom user registry by implementing the `UserRegistry` interface

-  Should we have to same SSO order with https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html? Also the SSO provider link seem to link to the article not specific to the SSO provider.
Open Liberty supports the following options for SSO authentication:

```
Social Media Login
JSON Web Tokens (JWT)
Lightweight Third Party Authentication (LTPA)
Security Assertion Markup Language (SAML)
Simple and Protected GSS-API Negotiation Mechanism (SPNEGO)
```
The SSO article have:

```
Social Media Login
JSON Web Tokens (JWT)
Simple and Protected GSS-API Negotiation Mechanism (SPNEGO)
Security Assertion Markup Language (SAML)
Lightweight Third Party Authentication (LTPA)

```

**Comment by dmuelle** [comment]
closing this issue and copying these comments into #893 to track the updates there
