### ISSUE TITLE
SSO article comments - https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/single-sign-on.html

### ISSUE THREAD

**Issue by utle** [OpenLiberty/docs#2749]
- The TLS link does not work `Secure communication with Transport Layer Security (TLS).`

- The SPNEGO configuration link does not work.  For more information, see `Configuring SPNEGO authentication in Open Liberty.
`

**Comment by dmuelle** [comment]
closing this issue and copying these comments into #1676 to track the updates there
