### ISSUE TITLE
Developer feedback from Gitter

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#2772]
On gitter developer experience forum,  @scottkurz was recommending Liberty Hardening document to an external user mdagit. 
He has a lot of things to say about Liberty and Security.   Before I lose this very helpful info from Scott.  Let me open an issue please.   We will go over later.... 

https://gitter.im/OpenLiberty/developer-experience#

**Comment by Charlotte-Holt** [comment]
The ACME stuff mentioned in Gitter is covered in @dmuelle's topic on ACME. I'll follow up on the hardening suggestions.
