### ISSUE TITLE
ID: APSFOUND-73: open-liberty documentation

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#2805]
This issue duplicates info from https://github.ibm.com/was-liberty/liberty-docs/issues/2109- we will include the doc with other EJB related content coming over from KC (TBD)

SME: @tkburroughs 

### Does the documentation apply to all platforms? 
- [x] Yes  
- [ ] No. Specific platforms: ______

### Does the documentation apply to all editions 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
For each new topic, complete the following information:

##### To create a topic:
- [x] Specify a first draft of the topic that you want added:  See Below
- [x] Specify a link to the section in the navigation where the topic should go: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_ejb_dev.html
##### To update to an existing topic:
- [ ] Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:
- [ ] Specify a link to the topics that are affected:
##### To add a custom property, complete the following checklist:
- [ ] Specify a link to the topic that will contain the custom property:
- [ ] The name and a description of the custom property
- [ ] Default values and other values
- [ ] Behavior of the values

# Draft

The feature APSFOUND-73 for Liberty (https://github.com/OpenLiberty/open-liberty/issues/7918) basically implements the following information from tWAS documentation:

https://www.ibm.com/support/knowledgecenter/SSEQTP_9.0.5/com.ibm.websphere.base.doc/ae/cejb_bindingsejbfp.html

So, the link above from tWAS should be used as the starting point for nearly identical documenation for liberty linked off the following Liberty doc : https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_ejb_dev.html

The following changes should be made to the tWAS version of the doc for Liberty:

### Remove 1st sentence of 2nd paragraph:

~~Starting in Version 8.0, bindings support in the EJB container is expanded.~~

### Remove the entire section with the following heading:

~~Naming considerations in clustered and cross-server environments~~

### Remove the information about :

~~Extensions defined in META-INF/ibm-ejb-jar-ext-pme.xml file~~

i.e. includes the removal of Table 8.

**Comment by chirp1** [comment]
Hi David, The issue needs to be opened by Tracy.
