### ISSUE TITLE
Reactive Java

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2806]
Introduction to reactive programming in Java with:

- MP Reactive Streams Operators
  - see https://openliberty.io/blog/2019/04/26/reactive-microservices-microprofile-19004.html
- JAX-RS reactive extensions
  - see https://openliberty.io/blog/2019/04/10/jaxrs-reactive-extensions.html
- MP Reactive messaging

Contacts:

- Andy McCright

Starting point:

- Talk to Andy about what questions the information should answer about reactive programming with Java (to be able to write reactive apps that run on OL) and work out a rough skeleton topic or topics.

Resources:

- **Presentation on MicroProfile Reactive Streams:** https://www.youtube.com/watch?v=WU8x8AIsqjQ&feature=youtu.be
- **Reactive guides:** https://openliberty.io/guides/#reactive_service
- **MicroProfile Reactive Messaging specification:** 
  - https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_microprofile_reactive_messaging
  - https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_message_acknowledgement
- **Blog:** https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging.html
- WASdev blog on rxJava, see if it's relevant: https://github.ibm.com/was-WASdev/WASdevnet-website/tree/master/developer.ibm.com/wasdev/docs/introduction-to-using-rxjava-with-websphere-liberty

**Comment by Charlotte-Holt** [comment]
Issues in this epic:
- #266 
- #2887

**Comment by dmuelle** [comment]
superseded by #6928
