### ISSUE TITLE
IDEs and build tools overview topic

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2828]
We need a single overview topic that introduces users to the IDEs that work with Open Liberty (IntelliJ, VS Code, Eclipse) and the build tools (Maven and Gradle). Also include information about using Docker as a dev tool. Link off to the guides where possible. 

Contact: YK Chang 

Guides:
- https://openliberty.io/guides/maven-intro.html
- https://openliberty.io/guides/gradle-intro.html
- https://openliberty.io/guides/docker.html

**Comment by dmuelle** [comment]
Open Liberty Tools IDE extensions:
https://github.com/OpenLiberty/open-liberty-tools-vscode
https://github.com/OpenLiberty/open-liberty-tools-intellij

**Comment by dmuelle** [comment]
closing as superseded by other issues, mainly Liberty Tools doc
