### ISSUE TITLE
JavaMail reference could use an example

### ISSUE THREAD

**Issue by jeshan** [OpenLiberty/docs#2829]
On pages like https://openliberty.io/docs/20.0.0.10/reference/feature/javaMail-1.6.html ,
we can't figure out how to configure JavaMail 

I got the following example on [IBM Knowledge Centre](https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_admin_javamail.html) working:

```xml
<mailSession 	mailSessionID="examplePop3MailSession"  
		jndiName="ExampleApp/POP3Servlet/exampleMailSession"
		description="POP3 javax.mail.Session"
		storeProtocol="pop3"
		transportProtocol="smtp"
		host="exampleserver.com"
		user="iamanexample@example.com"
		password="example"
		from="smtp@testserver.com">
	 <property name="mail.pop3.host" value="pop3.example.com" />
	 <property name="mail.pop3.port" value="3110" />
</mailSession>
```

Minimal examples like these would provide a better experience for users.

**Comment by Charlotte-Holt** [comment]
@jeshan Thanks for your feedback. We've been working on adding code examples to some of our feature documentation, and it's great to know that this example was helpful. I created issue #2831 to have this example and potentially other examples added to the JavaMail feature doc.
