### ISSUE TITLE
Consider changing "API Documentation" to "Documenting APIs"

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/docs#2835]
@barecode mentioned in #840 that the "API Documentation" header made him expect to find the content/APIs that's currently under "References" section.  I suggest we rename this section to instead be "Documenting APIs" to help make it clear that it's not about our documentation for our APIs, but rather documentation on how to document their APIs.

**Comment by Charlotte-Holt** [comment]
@dmuelle @lauracowen I updated "API documentation" to "Documenting APIs" in the nav: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/overview.html. Are you good with me going ahead and merging this change to `staging` and `vNext`?

**Comment by lauracowen** [comment]
Yup!

**Comment by barecode** [comment]
This looks great, thank you!

**Comment by Charlotte-Holt** [comment]
This was merged to `vNext` in #3119. It'll publish with 20.0.0.12. Closing this issue.
