### ISSUE TITLE
Intro to reactive programming with OL 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#2887]
Need a topic that talks about "here's how reactive works in Open Liberty". Introduce MicroProfile Reactive Messaging and message brokers (Kafka, specifically). Start by looking through the guides and 

**Contacts:** Gordon Hutchison and Andrew Rouse

**Resources:**
- https://openliberty.io/guides/#reactive_service
- https://download.eclipse.org/microprofile/microprofile-reactive-messaging-1.0/microprofile-reactive-messaging-spec.html#_microprofile_reactive_messaging
- https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging.html

**Comment by dmuelle** [comment]
Don't prioritize until discussing with Alasdair

**Comment by dmuelle** [comment]
this will be handled in #6928
