### ISSUE TITLE
error in logging config element

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#2997]
There is a syntax error in the autogen explanation of `hideMessage` attribute of [the logging config element
](https://www.openliberty.io/docs/20.0.0.11/reference/config/logging.html).

`Avoid trouble: Use the com.ibm.ws.logging.hide.messages property, except in cases where you are trying to change the configuration dynamically after startup.`

the property should be `com.ibm.ws.logging.hideMessages`

**Comment by Rwalls1** [comment]
This issue has already been addressed: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/config/logging.html

**Comment by dmuelle** [comment]
Confirmed on vNext as well, closing this issue
