### ISSUE TITLE
Update Jwt feature autogen desrciption

### ISSUE THREAD

**Issue by ManasiGandhi** [OpenLiberty/docs#3000]
Updates per Karen's review
"Hi Manasi,

Some of the updates that I list might be in development code. If they are, and you can't make the changes, then open a defect for development so that they make the changes. Add to your issue a link to the defect. Review with me the changes that you are considering putting into the defect before you put them in so that we agree on those changes.

    Change "This feature allows runtime..." to "This feature allows the runtime...:
    Review "JWT tokens". Does the wording seem right to you?
    Change "...declaration into your ..." to "...declaration to your...". <= Change "into" to "in"."

**Comment by dmuelle** [comment]
change will publish with 21.0.0.7
