### ISSUE TITLE
Incorporate hardening question from stack product and answer (WASSEC L2 lead) into hadening doc

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#3035]
https://github.ibm.com/was-liberty/WS-CD-Open/issues/20559 
raised by WCM team. 

Slack converstation here. 
https://ibm-cloud.slack.com/archives/C324NP6H5/p1604059249212100

Under LTPA hardening topic please.  Thanks in advance!

**Comment by dmuelle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.6/network-hardening.html

@jacksonleonard reviewed the update on draft

**Comment by dmuelle** [comment]
changes are on vNext and will publish for 21.0.0.6
