### ISSUE TITLE
Missing prefix value in description for Server configuration -> Classloader -> apiTypeVisibility

### ISSUE THREAD

**Issue by gjwatts** [OpenLiberty/docs#3058]
On the openliberty.io site -> https://openliberty.io/docs/latest/reference/config/classloader.html

The description text in the first entry, `apiTypeVisibility`, looks like it is missing something.  It says
`... If a prefix of   or - is added to API types...`
I am assuming the space between the words `of` and `or` should have a character (perhaps a plus sign `+`?).

It is the exact same way on the external, staging and draft sites that I checked since 20.0.0.8.  I could not find the classloader config value prior to 20.0.0.8, so I am guessing that is when it was introduced.

**Comment by Rwalls1** [comment]
This update has already been made to the source: https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.classloading/resources/OSGI-INF/l10n/classloader.properties. The update is not showing on the draft site: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/config/classloader.html.

**Comment by dmuelle** [comment]
opened https://github.com/OpenLiberty/open-liberty/pull/17316 to add an escape character

**Comment by dmuelle** [comment]
copy on site will be fixed with 21.0.0.8 but still waiting on fixes to generator in https://github.ibm.com/websphere/WS-CD-Open/issues/24533

**Comment by dmuelle** [comment]
The doc generator is now updated to fix these issues programmatically
