### ISSUE TITLE
Update dev mode documentation to include container support

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/docs#3066]
We are working on the following feature to support dev mode with containers: https://github.com/OpenLiberty/ci.maven/issues/659 , which we intend to release in the next version of the Liberty Maven/Gradle plugins.

This issue is to update the dev mode documentation (https://openliberty.io/docs/20.0.0.11/development-mode.html) to include information about container support.

It should cover the following:
- A brief overview of dev mode with containers
- What is needed in the user's project (specifically, it requires a Dockerfile that is intended to be used for both development and production.  And dev mode's recommended approach for copying config files is described in the numbered point 1 in the [readme](https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#devc-container-mode) to allow those config files to be hot deployed upon changes).
- How to start dev mode with containers
- Pointers to the Maven/Gradle readmes for further information

Reference material:
Maven readme for dev mode with containers: https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md#devc-container-mode
Gradle readme for dev mode with containers: https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#libertydevc-task-container-mode
Previously published blog post for the tech preview of this feature: https://openliberty.io/blog/2020/08/25/dev-mode-containers-preview.html
Sample/demo project showing usage of dev mode with containers: https://github.com/OpenLiberty/demo-devmode/tree/devc

**Comment by dmuelle** [comment]
Hi @ericglau 

These updates are now on [the Open Liberty draft site](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/development-mode.html#_container_support_for_dev_mode). Let me know if anything is missing or if edits are needed. These updates will publish with the 20.0.0.12 release.

**Comment by ericglau** [comment]
`For Maven projects, specify the Liberty Maven plug-in with version 3.3-M3` -> change to version 3.3.  Also applies to the snippet beneath it.
`For Gradle projects, specify the Liberty Gradle plug-in with version 3.1-M2` -> change to version 3.1.  Also applies to the snippet beneath it.

**Comment by dmuelle** [comment]
Updated the versions as specified: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/development-mode.html#_start_dev_mode_with_container_support

**Comment by ericglau** [comment]
It looks good, thanks.

**Comment by dmuelle** [comment]
Ok thanks, closing this issue- will continue working on the Intellij section in #3179
