### ISSUE TITLE
ID: 19.0.0.7: LG-75: mpHealth v2.0 - Implementation

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/docs#308]
### Does the documentation apply to all platforms? 
- [x] Yes  
- [ ] No. Specific platforms: ______

### Does the documentation apply to all editions 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
For each new topic, complete the following information:

##### To create a topic:
- [ ] Specify a first draft of the topic that you want added:
- [ ] Specify a link to the section in the navigation where the topic should go:
##### To update to an existing topic:
- [x] Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ:
- Need to update the following documentation to include the mpHealth-2.0 feature.
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_healthcheck.html
- [ ] Specify a link to the topics that are affected:
##### To add a custom property, complete the following checklist:
- [ ] Specify a link to the topic that will contain the custom property:
- [ ] The name and a description of the custom property
- [ ] Default values and other values
- [ ] Behavior of the values

**Comment by lauracowen** [comment]
@pgunapal Can you outline here what has changed in the developer experience and benefit of using MP Healthcheck since the previous version, pls?

**Comment by lauracowen** [comment]
From brief discussion with @pgunapal:

MP Healthcheck 2.0 introduces two new endpoints: `/health/live` and `/health/ready` to show the liveness and the readiness of the microservice. This info should be updated in the topic planned in #343.

The update to 2.0 means a breaking change between 1.0 and 2.0 is that JSON attribute names that responds  has changed from 'outcome' to 'status', so migration is needed for existing applications. I don't think that information should be provided in the topic written for #343 (assume the latest version in that topic). However, we need to provide it somewhere. Initially, we'll provide a 'migration' blog post so the #343 topic should link to the blog post.

**Comment by chirp1** [comment]
After discussion with Alasdair, we'll write the MPHealth 2.0 doc as an OL topic. This topic in KC is for 

MPHealth 1.0: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_healthcheck.html Alasdair does not want the 1.0 doc in KC anymore as the 1.0 feature is, as he described it, fatally flawed. However, keep the page, just remove ALL the content. Then add a blurb to this topic that points the users to the MPHealth 2.0 topic(s) in the OL docs. 

David, do you have what you need from Prashanth?

**Comment by dmuelle** [comment]
Yes- I will work with @pgunapal to revise my draft. 

@lauracowen do you know if any of the forthcoming guides are planned to update MP Health to reflect new endpoints and annotations?

**Comment by lauracowen** [comment]
Yes! :) https://github.com/OpenLiberty/guides-common/issues/289 Looks like it's next on the list.

(the guides backlog is here, if you ever need it for something else: https://github.com/OpenLiberty/guides-common/projects/1#workspaces/open-liberty-static-guides-workspace-5a60d7d16d83c32af0fc975b/board?repos=102646509&showPipelineDescriptions=false)

**Comment by dmuelle** [comment]
Ok- should we provide any task-based content in the concept topic for MP Health?

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#health-check-microservices.html

I've asked @pgunapal for code examples that show the new endpoints and annotations in context. Do we need to recreate a procedure like the one in this KC page in the concept topic or just link to the guides? Until the guides are updated, we don't have any code examples for MPH 2.0

**Comment by lauracowen** [comment]
Hmm... @yeekangc Do you know when this guide updates are likely to be published? https://github.com/OpenLiberty/guides-common/issues/289

**Comment by yeekangc** [comment]
Targeting them for our next cycle.  Earliest in August and latest in September?

@gkwan-ibm can offer better insights.  If we will have help, we can move faster.  @pgunapal, feel free to discuss directly with Gilbert.

**Comment by dmuelle** [comment]
This KC topic now instructs users to visit Open LIberty documentation for MPH2.x 

https://www-03preprod.ibm.com/support/knowledgecenter/en/SSEQTP_liberty_temp/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_healthcheck.html

Full explanation/ examples of new 2.x annotations and endpoints are included in the MicroProfile Health concept topic (#343), expected to publish by 7.25

**Comment by lauracowen** [comment]
@dmuelle Will the link in the KC be updated to point to the specific OL topic? It currently just lands you on the OL.io homepage.

**Comment by dmuelle** [comment]
@lauracowen the plan at this point, as I understand it, is to have all KC->OL redirect messages point to the OL homepage

**Comment by lauracowen** [comment]
I spoke with @chirp1 and @Charlotte-Holt after I posted that comment. The (reasonable) concern was that the OL docs URLs might change. It is possible that they would be we wouldn't do that without providing redirects of the old to new URLs so it shouldn't be a problem and we can link from KC directly to the relevant OL topic.

**Comment by dmuelle** [comment]
Link is now updated to point directly to the MPHealth concept doc

https://github.ibm.com/was-liberty/liberty-docs/pull/1547

this change will be picked up with the next build and will be published with 19.0.0.7 on 7.25
