### ISSUE TITLE
Landing pages

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#3125]
The following pages can be moved up to become second level landing pages

~~RESTful services - https://openliberty.io/docs/ref/general/#rest-microservices.html
API documentation - https://draft-openlibertyio.mybluemix.net/docs/ref/general/#documentation-openapi.html
Concurrency - https://openliberty.io/docs/ref/general/#concurrency.html
Fault tolerance - https://openliberty.io/docs/ref/general/#fault-tolerance.html
Observability - https://openliberty.io/docs/ref/general/#microservice-observability-metrics.html
Testing - https://draft-openlibertyio.mybluemix.net/docs/ref/general/#integration-testing.html
Server configuration - https://draft-openlibertyio.mybluemix.net/docs/ref/config/
Features - https://draft-openlibertyio.mybluemix.net/docs/ref/feature/
Commands - https://www.openliberty.io/docs/latest/reference/command/command-overview.html
Security hardening - https://www.openliberty.io/docs/latest/security-hardening.html
Logs- https://www.openliberty.io/docs/latest/log-trace-configuration.html
Metrics- https://www.openliberty.io/docs/latest/introduction-monitoring-metrics.html
Admin Center- https://www.openliberty.io/docs/latest/admin-center.html~~

We still need landing pages for the following sections, planned in the linked issues
~~Commands - #2008 (DONE)~~
~~Java EE API - #2610 (DONE)~~
~~MicroProfile API - #2611 (DONE)~~
~~Troubleshooting security- #3392~~ 
~~Data Sources - #4630~~

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Could not find associated sections for the following in **nav.adoc**:
1. Server configuration - https://draft-openlibertyio.mybluemix.net/docs/ref/config/
2. Features - https://draft-openlibertyio.mybluemix.net/docs/ref/feature/
3. Commands - https://www.openliberty.io/docs/latest/reference/command/command-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
leaving this epic open until EE4j landing page publishes with 21.0.0.12

**Comment by ramkumar-k-9286** [comment]
All landing pages are currently published. Proceeding to close this issue.
