### ISSUE TITLE
Update wiki info for config examples to reflect new process

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#3134]
The ["How" section of the wiki](https://github.com/OpenLiberty/docs/wiki/How-to-add-config-examples-to-generated-feature-docs#how) needs to be updated for the new generated docs process

**Comment by Charlotte-Holt** [comment]
Just read through https://github.com/OpenLiberty/docs/wiki/How-to-add-config-examples-to-generated-feature-docs#how, and the info looks accurate to me. Thanks, @dmuelle!
