### ISSUE TITLE
Please update Liberty performance consideration (Closed - No ID work needed)

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#3144]
Hello, 

Per customer's request, please add this performance hints and tips to Liberty's performance KC document.  

My customer  (SOMPO) was affected by the following Apache CXF default behavior that could cause their application to stop for 10 seconds every 10 hours.  

Although it is not Liberty's code,  Apache CXF is shipped with Liberty.  So customer felt it is Liberty's behavior.. They think IBM should document this in the official KC doc as performance consideration.   There will be a meeting with customer's executive and IBM.   The IBM account team wants to be able to say they put in the request to KC so it will be updated soon. 

Kevin Grigorenko (Performance/SWAT team) kindly provided a nice write-up below. He will include it in his performance cookbook.  I would like KC to have the similar description.  

Thank you in advance! 

```
Apache CXF
Apache CXF is a Java framework for executing and processing JAX-RS or JAX-WS web services. The source is available at https://github.com/apache/cxf.

JDKBugHacks
CXF may intitiate periodic full garbage collections through calls to sun/misc/GC.currentLatencyTarget. These calls are generally not required as it was a workaround for bugs in older JDKs and this GC function may be disabled with:
-Dorg.apache.cxf.JDKBugHacks.gcRequestLatency=true
```

**Comment by ManasiGandhi** [comment]
@una-tapa Could you please add more information on this issue? Do you want it documented in the KC or Open Liberty?

**Comment by una-tapa** [comment]
Hi, Thanks for looking.  It has been a year since this issue was opened.  Customer seems to be very happy with the Performance cookbook so I am closing this issue.
