### ISSUE TITLE
Dodgy character in XML example

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3156]
In https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/appSecurity-3.0.html#_administrative_rest_api_access_role_configuration

First example has a superfluous `<`

**Comment by Charlotte-Holt** [comment]
Fixed in https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/appSecurity-3.0.html.

**Comment by Charlotte-Holt** [comment]
This is on vNext in #3181. Closing this issue.
