### ISSUE TITLE
Direct links to doc content don't render

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/docs#317]
@steven1046 commented on [Wed Jun 05 2019](https://github.com/OpenLiberty/openliberty.io/issues/1206)

Direct links to doc topics don’t display properly. eg https://openliberty.io/docs/ref/general/#/docs/concept/sync_async.html If I navigate to that location, the topic displays fine. If I click the link directly (Firefox or Chrome), the topic content doesn’t display:

---

@steven1046 commented on [Wed Jun 05 2019](https://github.com/OpenLiberty/openliberty.io/issues/1206#issuecomment-499121153)

Direct links work on https://demo1-openlibertyio.mybluemix.net/docs/ref/general/#runnablejarfiles.html which is latest as of May 3, so it is a recent regression.

---

@steven1046 commented on [Wed Jun 05 2019](https://github.com/OpenLiberty/openliberty.io/issues/1206#issuecomment-499133347)

The bug is due to the structure of the https://github.com/OpenLiberty/docs where one of the general references is in docs/concept/ instead of docs/ref/general/

**Comment by lauracowen** [comment]
I've restructured the docs directory structure.
