### ISSUE TITLE
New topic on Variable substitution 

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#3192]
https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/config/server-configuration-overview.html#variable-substitution

This section is the only place in the docs where the "built-in" config variables for OL are listed- but they're just stuck at the end of the section. This section could properly be renamed as just "Variable substitution", and re-focused to also explain best practice for using variables in the config vs hard coded values- generally, when a value points to an external source, using a variable is best practice bcse enables portability. Also relevant to dev-prod parity since you can define the variable and use the same config in test container and prod

We need info to point to re variables from other examples and topics.

**Comment by Charlotte-Holt** [comment]
Pull info from the server config overview topic into a new topic about Variable substitution. Link from the server config overview to the new topic.
