### ISSUE TITLE
Lack of clarity in possible values and examples for com.ibm.ws.logging.trace.specification

### ISSUE THREAD

**Issue by dalfredson** [OpenLiberty/docs#3288]
This documentation doesn't provide  definition of the values that are to be provided to com.ibm.ws.logging.trace.specification.  Without this you need to guess what to provide to enable your own logging.  There should be clarity in the definition (ie tell me all the possible values) and there should be examples that are real world (ie not IBM classes, but some list of application classes)

**Comment by dmuelle** [comment]
Following up on this comment as part of content design for #3290
