### ISSUE TITLE
ID: MicroProfile OpenTracing 2.0 Implementation

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#3290]
Epic: https://github.com/OpenLiberty/open-liberty/issues/11474
Target: 21.0.0.2

As per Karen, I just put what has been changed in MicroProfile OpenTracing 2.0 in this issue.

The breaking change that mpOpenTracing-2.0 introduced is the OpenTracing API level change.  In mpOpenTracing-1.3, it supports OpenTracing API 0.31.0.  In mpOpenTracing-2.0, the OpenTracing API has been upgraded to 0.33.0.  There are breaking changes in version 0.33.0.

For JAX-RS applications that just rely on MicroProfile OpenTracing automatic tracing instrumentation and do not use OpenTracing API (e.g. `io.opentracing.Tracer`) directly, there is no impact on their applications.  For those applications that directly use OpenTracing API, see the [OpenTracing Javadoc](https://javadoc.io/doc/io.opentracing/opentracing-api/latest/index.html) to see the breaking changes.  Version 0.32.0 introduced all the new changes and marked some methods deprecated.  Version 0.33.0 has removed the deprecated methods and therefore it introduced the breaking changes.

In addition, MicroProfile OpenTracing 2.0 also updated its dependencies.
- MicroProfile Config 2.0
- MicroProfile Rest Client 2.0

**Comment by chirp1** [comment]
From a discussion with Laura, the capabilities of this OpenTracing feature would be part of a larger discussion on distributed tracing. Apparently, Don has some changes going on with the distributed tracing implementation. So, some of the OL writers will be addressing the docs for that with Don after the new year.

**Comment by dmuelle** [comment]
Adding this comment from #3288 
https://github.com/OpenLiberty/docs/issues/3288#issue-746885378

**Comment by dmuelle** [comment]
Open Tracing will be replaced by Open Telemetry after 220008
