### ISSUE TITLE
Add page-layout, page-type attributes to command adocs

### ISSUE THREAD

**Issue by lavenal** [OpenLiberty/docs#33]
To help with the new server command doc page in the openliberty.io site, the following updates to the asciidoc are required:
- add 
      page-layout: server-command 
   to the following files:
      runnablejarfiles.adoc, server-commands.adoc, server-create.adoc, server-debug.adoc, server-dump.adoc, server-exitcodes.adoc, server-help.adoc, server-javadump.adoc, server-list.adoc, server-package.adoc, server-pause.adoc, server-resume.adoc, server-run.adoc, server-serverprocess.adoc, server-start.adoc, server-stop.adoc, and server-version.adoc

   The page-layout attribute is the name of the layout used to format the doc.
- add 
     page-type: overview
   to server-commands.adoc
- add 
     page-type: command 
   to server-create.adoc, server-debug.adoc, server-dump.adoc,  server-help.adoc, server-javadump.adoc, server-list.adoc, server-package.adoc, server-pause.adoc, server-resume.adoc, server-run.adoc, server-start.adoc, server-stop.adoc, and server-version.adoc 

- add
     page-type: reference
   to runnablejarfiles.adoc, server-exitcodes.adoc, and server-serverprocess.adoc

The page-type attribute is to use for grouping. There are three types in the server command. They are command (that would appear in the table of content), overview (which is an overview doc that appears in the table of content), and reference (that appears in the doc content but would not appear in the table of content).

In addition, the following fixes have to be made:
- server-debug.adoc should have a title of "server debug command" not "server package command"
- server-resume.adoc: remove the following 2 lines

   -yserver --target=MDBApplication#MDBModule.jar#Bean
    -----

**Comment by lauracowen** [comment]
@lavenal @kinueng @mbroz2 Do you know what is meant to be happening with this issue? It looks like work stopped on it and maybe it should be reassigned?

**Comment by lauracowen** [comment]
Have pinged @lavenal on Slack to ask when this work is planned or who this should be re-assigned to.

**Comment by lavenal** [comment]
The work was done back in September with the PR referenced by the issue.
