### ISSUE TITLE
Backport 20.0.0.12 topic to 11

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/docs#3309]
Based on slack conversation with Laura about this topic https://openliberty.io/docs/20.0.0.12/kerberos-authentication-jdbc.html for a feature introduced in 20.0.0.11

> We could backport this particular topic to 20.0.0.11 as a one-off (as it was very close to matching the runtime release date) but we don’t do it routinely. Create an issue on the OL docs backlog and tag it doc bug and @Charlotte Holt or @david.mueller1 will be able to take a look next week.

**Comment by dmuelle** [comment]
Hi @frowe - the [JDBC kerrberos](https://www.openliberty.io/docs/20.0.0.11/kerberos-authentication-jdbc.html) and [JDBC overview](https://www.openliberty.io/docs/20.0.0.11/relational-database-connections-JDBC.html) topics, as well as the [example config updates for the JDBC feature](https://www.openliberty.io/docs/20.0.0.11/reference/feature/jdbc-4.2.html), are all now available in 20.0.0.11 doc. Closing this issue, let me know if anything further is needed. Thanks!
