### ISSUE TITLE
Feature and server config overview topics have disappeared from nav in 20.0.0.12

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3316]
They were in the generated nav but not now that the generated docs are handled separately.

Maybe just add them back into the Reference section for now until you have the container topics ready?

**Comment by Charlotte-Holt** [comment]
This is fixed and live at https://openliberty.io/docs/20.0.0.12/overview.html, and the fix was also merged to `vNext` in #3353.
