### ISSUE TITLE
[19.0.0.7] ID: LG-50: MicroProfile Metrics 2.0

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#332]

**Comment by lauracowen** [comment]
@fmhwong Can you add details of what documentation you expect to be created for this? I've found `#11720` on WL code backlog but no detail there.

**Comment by fmhwong** [comment]
@lauracowen We opened the epic in WS-CD instead of OL.  (Future OL epics will be opened in OL git.)

This is to document the new enhancements of MicroProfile Metrics.  SME @Channyboy is on vacation right now.  This will go out in 19.0.0.7.  What is the deadline for this?

**Comment by lauracowen** [comment]
There's no guarantee about when the docs will be released (the team is working through a prioritised backlog) but it would help me prioritise the backlog and identify what topics or other updates are needed if I can know what documentation you think is needed asap.

**Comment by Channyboy** [comment]
ToDos:
Metrics 2.x updated document: https://github.com/OpenLiberty/docs/issues/270
GA Blog: https://github.com/OpenLiberty/open-liberty/issues/8022

**Comment by Charlotte-Holt** [comment]
@lauracowen @Channyboy I created a topic for this, and the it's at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#mp_metrics_migration.html. Looks like this is going to be a blog post for now, but I wanted to share what I'd typed up from David's content.

**Comment by Charlotte-Holt** [comment]
Closing this issue. 
Blog published at https://openliberty.io/blog/2019/07/24/microprofile-metrics-migration.html.
Topic published at https://openliberty.io/docs/ref/general/#microservice_observability_metrics.html.
