### ISSUE TITLE
Suggested example config: JSON-B and JSON-B via BELLs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3325]
From reviewing the KC (so check if it's a good example for one or both features).

https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_jsonb.html

https://www.openliberty.io/docs/latest/reference/feature/jsonb-1.0.html
https://www.openliberty.io/docs/latest/reference/feature/jsonpContainer-1.1.html

SME: Andy Guibert

**Comment by Rwalls1** [comment]
New SME contact: Nathan Mittlestat

**Comment by dmuelle** [comment]
this is now covered in this is now covered in https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/json-p-b.html#_third_party_json_p_and_json_b_providers
