### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3327]
Might be worth someone going through and checking for all broken links. Visually you can see them displayed in red text but the asciidoc/Antora logs should provide a list I think, so worth asking the website team for a copy before trying to check all the topics manually.

eg
- https://www.openliberty.io/docs/20.0.0.12/runnable-jar-files.html#reference:config/serverConfiguration.adoc
- https://www.openliberty.io/docs/20.0.0.12/reference/command/server-package.html#ROOT:runnablejarfiles.adoc ("See also" link at the end and in the table is broken)
- https://www.openliberty.io/docs/20.0.0.12/relational-database-connections-JDBC.html (see "See also" section)

**Comment by Rwalls1** [comment]
In addition to the links referenced above, @mbroz2 provided a log that contained the following error that indicated broken links, these links has now been fixed:
`asciidoctor: ERROR: authentication-filters.adoc: line 26: include target not found: ../../reference/pages/feature/socialLogin-1.0/example`

**Comment by Rwalls1** [comment]
Links to topics that contained broken links that are now fixed: 
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/reference/command/server-package.html
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/runnable-jar-files.html
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/authentication-filters.html

**Comment by Rwalls1** [comment]
Staging: 
https://staging-openlibertyio.mybluemix.net/docs/21.0.0.1/runnable-jar-files.html
https://staging-openlibertyio.mybluemix.net/docs/21.0.0.1/reference/command/server-package.html
https://staging-openlibertyio.mybluemix.net/docs/21.0.0.1/authentication-filters.html
