### ISSUE TITLE
Additional Windows-only server commands

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3329]
You need to unzip Open Liberty on a Windows machine to be able to run these commands and see their command help.

As for #3314, get the info from the online command help by running the following commands:

- `./wlp/bin/server registerWinService --help`
- `...startWinService...`
- `...stopWinService...`
- `...unregisterWinService...`

See KC topic https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_setup_new_server_winserv.html but make sure the OL docs info matches whatever's in the online cmd help (which you see when you run the command above).

**Comment by Charlotte-Holt** [comment]
Based on information in the epic, the programmatic helps should be sufficient for these commands. Closing.
