### ISSUE TITLE
Suggested topic: Persisting session data

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3338]
From KC review (so check with SME).

In the OL docs, we have in draft a topic about [distributed session caching with JCache](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/distributed-session-caching.html). However, the [blog post on which that was based](https://openliberty.io/blog/2018/03/22/distributed-in-memory-session-caching.html) and a [topic in the KC](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_session_persistence.html) also mention doing session caching with a relational database (I guess this is not "distributed" session caching?).

Talk to @aguibert  about whether there's enough to discuss about database session caching for another topic (in which case, make sure to provide links to/from the JCache topic too), or whether it would make more sense to just make Manasi's [distributed session caching topic](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/distributed-session-caching.html) into a "Persisting session data", or "Session caching", topic that discusses both options and when you might want to do one or the other.

SME: Andy Guibert

**Comment by dmuelle** [comment]
this is covered in https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/sessionDatabase-1.0.html and https://draft-openlibertyio.mybluemix.net/docs/latest/create-session-table.html, closing
