### ISSUE TITLE
Suggested security examples

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3345]
There are a load of security role mapping examples in the JMX KC docs: https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_mapadmin.html

I'm not sure that there's anything specific to JMX about them. Several of them we already have in the OL docs (I think). So I think they should be checked and looked to see whether any of the examples should be used in the OL security docs (eg LDAP role mapping in the LDAP feature gendoc?). The JMX docs (which Manasi has started on in #1695) should then link to the role mapping info in the security topics as appropriate. The JMX docs shouldn't duplicate security info that's elsewhere.

**Comment by dmuelle** [comment]
suggested placement for the examples/info in this topic:

The minimal JMX info in the intro is largely covered in OL in [Configuring JMX connections](https://openliberty.io/docs/latest/configuring-jmx-connection.html). For this issue, we only need to be concerned with migrating the role mapping examples. This information needs to be clarified on the examples in OL

> You can also use any supported user registry. You cannot use the quickStartSecurity element if you have already configured another user registry. In this case, map users or roles from the registry to the administrator role.

I'm using numbered steps here for reference, though they are unordered steps in the topic.

## Steps 1 and 2

this is mostly covered in [Configure REST API management roles](https://openliberty.io/docs/latest/reference/feature/restConnector-2.0.html#_configure_rest_api_management_roles).
- I think we need to add the basic user registry stanza from the example in step 2 of the ibm docs topic to the first example in the Configure REST API management roles section.
- also need to add the quickstart example in step 1 to this section, clarifying that this is for dev/test purposes, and link to it from the quickstart example in [Configure a basic user registry with QuickStart security](https://openliberty.io/docs/latest/reference/feature/appSecurity-3.0.html#quick).

## Step 3

add this example to the LDAP User Registry page, just after [Configure an LDAP user registry](https://openliberty.io/docs/latest/reference/feature/ldapRegistry-3.0.html#simple). Provide a link from the Admin REST connector page and specify that you have to enable that feature in the example that you add.

## step 4-6

already covered on the admin rest connector page

## step 7

add to the [MPJWT feature page](https://openliberty.io/docs/latest/reference/feature/mpJwt-1.0.html), include also an example of role mapping and link back to admin REST feature. We also need to add an anchor of the examples to this page at the start of the examples section.

## step 8

add to [SAML Web Single Sign-On](https://openliberty.io/docs/latest/reference/feature/samlWeb-2.0.html) page, similar to JWT example in previous step

**Comment by hiltoncv** [comment]
Updates are available at:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/restConnector-2.0.html
Section "Configure REST API management roles"
"You can use the basic registry for administrative..
...
...password="keystorePassword"/>"

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpJwt-2.0.html
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/samlWeb-2.0.html

**Comment by dmuelle** [comment]
on the restconnector page:

this is the code block needs edits:

```xml
<reader-role>
    <user-access-id>https://idp.example.com/bob@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/EmployeeGroups</group-access-id>
</reader-role>

<administrator-role>
    <user-access-id>group:https://idp.example.com/wanda@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/ManagerGroups</group-access-id>
</administrator-role>
```
it should be:

```xml
<reader-role>
    <user-access-id>user:https://idp.example.com/bob@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/EmployeeGroups</group-access-id>
</reader-role>

<administrator-role>
    <user-access-id>user:https://idp.example.com/wanda@example.com</user-access-id>
    <group-access-id>group:https://idp.example.com/ManagerGroups</group-access-id>
</administrator-role>
```

**Comment by dmuelle** [comment]
Hi @hiltoncv - in the [admin rest connector page](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/restConnector-2.0.html), avoid using "here is" as in " Here is an example...". In this context, "Here is.." is an expletive, which IBM style advises against using, mainly due to translation concerns I believe. For more info, see acrolinx guidance: https://ibmid.acrolinx.cloud/htmldata/en/rules/309246d4649b198e4ac1a39c430ac0600c14cee6.html

also

You can use quickStartSecurity element for a single user mapping.
--->
You can use the `quickStartSecurity` element to quickly configure a single administrator for testing and development purposes. This option automatically configures a registry with only one user who is granted the administrator role.

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpJwt-2.0.html#_assign_an_administrative_role_to_a_user_authenticated_by_the_sso_server

I think you have the wrong example here. Step 7 in the IBM Docs topic shows the default mapping- this example uses example from step 6- an easy mistake since the steps aren't actually numbered :)

the title of the example should probably be something like " Define access-id values for users and groups that are authenticated by MicroProfile JWT". 

We should explain what the default format is, then show an example of mapping to role. SO in addition to the two examples in step 7, something like

The following example shows mapping for a JWT-authenticated user and group. The user is mapped to the administrator role and the group is mapped to the reader role. In this example, the JWT for the user includes an `iss` value of `myCo` and a upn value of `lisa@myco.com`. The JWT for the group includes an `iss` value of `myCo` and a `groups` value of `readers`.

```xml
<administrator-role>
     <user-access-id> user:myCo/lisa@myco.com</user-access-id>
</administrator-role>

<reader-role>
     <group-access-id>group:myCo/readers</group-access-id>
</reader-role>
```

The example on the SAML page should follow a similar format, but with no group example. Also, the last sentence after the SAML example is not needed

**Comment by hiltoncv** [comment]
@David Thanks for the feedback. 
"for testing and development.." This part is not in the original document.

**Comment by dmuelle** [comment]
@hiltoncv - I added that in to clarify the intended use for Quickstart in this doc. It's consistent with how we discuss it elsewhere:

https://openliberty.io/docs/latest/user-registries-application-security.html#_quickstart_security

**Comment by hiltoncv** [comment]
> on the restconnector page:
> 
> this is the code block needs edits:
> 
> ```
> <reader-role>
>     <user-access-id>https://idp.example.com/bob@example.com</user-access-id>
>     <group-access-id>group:https://idp.example.com/EmployeeGroups</group-access-id>
> </reader-role>
> 
> <administrator-role>
>     <user-access-id>group:https://idp.example.com/wanda@example.com</user-access-id>
>     <group-access-id>group:https://idp.example.com/ManagerGroups</group-access-id>
> </administrator-role>
> ```
> 
> it should be:
> 
> ```
> <reader-role>
>     <user-access-id>user:https://idp.example.com/bob@example.com</user-access-id>
>     <group-access-id>group:https://idp.example.com/EmployeeGroups</group-access-id>
> </reader-role>
> 
> <administrator-role>
>     <user-access-id>user:https://idp.example.com/wanda@example.com</user-access-id>
>     <group-access-id>group:https://idp.example.com/ManagerGroups</group-access-id>
> </administrator-role>
> ```

**Updated**

**Comment by hiltoncv** [comment]
> @hiltoncv - I added that in to clarify the intended use for Quickstart in this doc. It's consistent with how we discuss it elsewhere:
> 
> https://openliberty.io/docs/latest/user-registries-application-security.html#_quickstart_security
"The registry that is configured by this option is not intended for production environments. However, it is useful in test scenarios, particularly for testing secured JMX connections that require administrator access. "
Why to include this statement in the customer-facing document? If the option isn't intended for the production environments, probably it fits in internal docs. Are we on the same page?

**Comment by hiltoncv** [comment]
Ignore this comment as we had a lengthy discussion on it over Slack.

**Comment by dmuelle** [comment]
Hi @hiltoncv - a few suggestions:

## https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/restConnector-2.0.html

> You can use any supported user registry. 

Move this sentence so it is right after the sentence that ends "... defined in a user registry access to select administrative REST APIs."

Three users are added to the user registry in the example.
--->
In this example, three users in the user registry are granted roles

### Access IDs

Looking at this more closely, I think the access id information should get its own subheading: " Configure REST API management roles by using access IDs"

I also now think the JWT and SAML info should be on this page. It only makes sense in the context of the rest of the access ID information

In the initial example, update the access id examples to use italics in the variables- eg

```
[source,xml]
----
user:<security realm name>/<user name>
----
```

would become

```
[subs=+quotes]
----
user:< _security realm name_ >/< _username_ >
----
```

similar changes for the group access ID example

Then include the JWT and SAML examples on this page, similar to the ibm docs topic. (remove them from the other pages)

**Comment by hiltoncv** [comment]
@dmuelle Incorporated comments. 
Updates are available at:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/samlWeb-2.0.html

**Comment by dmuelle** [comment]
@hiltoncv the updates at https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/restConnector-2.0.html look good. Thanks!

**Comment by dmuelle** [comment]
one last thing to do for this issue- I think we should put a link to the restconnector examples from the [Authorization](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authorization.html) page.

On that page,at the end of the introduction section, add the following sentence.

> In addition to configuring authorization to application resources, you can configure management roles  that grant access to select administrative Open Liberty REST APIs. For more information, see feature:restConnector[display=Admin REST Connector: Configure REST API management roles].

**Comment by hiltoncv** [comment]
Updated the Authorization page:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authorization.html

**Comment by hiltoncv** [comment]
Fixed the issues listed in #6430
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpJwt-2.0.html#_validate_microprofile_jwt_claims_with_the_user_registry

**Comment by dmuelle** [comment]
Looks good- ready for staging

**Comment by hiltoncv** [comment]
Updates pushed to vNext.
