### ISSUE TITLE
Suggested topic: DB2 client re-routing

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3349]
From KC review. Ask Alasdair first if this should be included. DB2 is proprietary but then someone might be using it if they're using OL in business. Check also with him or with SMEs about whether this is relevant in cloud/containerised world - eg are there other ways that you'd handle re-routing to other DB2 database servers in that context, rather than configuring Liberty itself?

See KC topic: https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_config_reroute_db2.html

SME contact: @frowe

**Comment by frowe** [comment]
I'd recommend waiting on including this because it is proprietary and I don't have a clear sense of how many OL customers are going to use it.

**Comment by lauracowen** [comment]
@frowe Ah ok. Good point. Thanks, that's useful to know.

@Charlotte-Holt I'll update the spreadsheet so we have a record, then you can maybe icebox or even close this issue? (there's a link to it in the spreadsheet so you could always re-open it?)
