### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3352]
Check with a CORS expert to see if any important information would be lost if this [CORS KC topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_webcontainer_cors_config.html) were replaced with a redirection to the [CORS guide](https://openliberty.io/guides/cors.html). I don't think there is and, if that's the case, just make sure that the CORS guide is available in the OL docs nav in a relevant place for developers to find.

I've raised an issue against the CORS guide to include a reference to the [`cors` config gendoc](https://www.openliberty.io/docs/latest/reference/config/cors.html): https://github.com/OpenLiberty/guide-cors/issues/69

For SME, try checking who contributed to the CORS guide repo, and if you can't work it out from that, ask the guides team if they know who wrote it.

SME contact: @andymc12

**Comment by andymc12** [comment]
Hi @lauracowen and @Charlotte-Holt - I'm probably not the best person for SME on CORS.  I worked with @griffinhadfield on it last week for the SSE guide, and we were able to hack our way through CORS config to make the distributed SSE scenario work, but somebody else should probably be the SME for a CORS guide - I'd suggest starting with @pnicolucci or somebody on his team.  Thanks!

**Comment by pnicolucci** [comment]
I believe @yongja79 @leochr  would be good contacts for this.

**Comment by leochr** [comment]
The OL CORS guide is great and provides useful information, but it's a lot of information to navigate through. CORS config gendoc on the other hand provides minimum information, it doesn't have a sample config.

But the CORS KC topic provides a simple summary and sample snippet for someone looking for just that. I don't think any information will be lost if it's removed, but for the above reason, it should be considered to keeping its content and adding the link to OL CORS guide and/or CORS config gendoc.

**Comment by Rwalls1** [comment]
@leochr Thank you for your feedback.

**Comment by Rwalls1** [comment]
Based on feedback and further review, it was decided that all important information is covered in the guide and there isn't a need for additional documentation. A note was added to the [KC spreadsheet ](https://ibm.ent.box.com/services/box_for_office_online/4881/608276299537/bea857.5e8db60a915328510d69f06b7d1c5cf45e55dd88dd390e5483373f82f0b12512?node_type=file)to reflect this decision.
