### ISSUE TITLE
Add a tiny bit more to LTPA section in SSO topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3364]
We have a brief section on LTPA in the [OL SSO topic](https://www.openliberty.io/docs/20.0.0.12/single-sign-on.html). A lot of people ask if Liberty supports LTPA (it's a format that came from IBM/tWAS) so it's good to show that we do support it but don't need all the detail that the [Liberty KC topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_authentication.html#cwlp_authentication__ltpa) currently provides.

From talking with Alasdair, it would be useful to add a little to that section giving a bit more detail about what an LTPA token consists of and how it works. Don't need more than that for most use cases.

Talk to SME about what that most useful info would be.

**Comment by Rwalls1** [comment]
Staging: https://staging-openlibertyio.mybluemix.net/docs/21.0.0.1/single-sign-on.html
