### ISSUE TITLE
Distributed tracing of microservices (MP36)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#341]
Introduce distributed tracing with MP OpenTracing.

See the KC topic https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_dist_mptracing.html but you might need background info from other nearby KC topics on non-MP opentracing to give a full picture of what distributed tracing involves and why it's important.

See also #310 which was raised to capture updates to the capability by adding Jaeger support.

Contact:
- Felix Wong

**Comment by dmuelle** [comment]
Awaiting specification updates

**Comment by dmuelle** [comment]
following up on this in #3290
