### ISSUE TITLE
Update links to javadoc for Fault Tolerance 3.0 and MicroProfile Health 3.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/docs#3414]
This page contains links into the Fault Tolerance javadoc: https://github.com/OpenLiberty/docs/blob/vNext/modules/ROOT/pages/fault-tolerance.adoc

When Fault Tolerance 3.0 is released alongside MicroProfile 4.0, those links should be updated to point to the MicroProfile 4.0 javadoc instead.

**Comment by dmuelle** [comment]
Waiting on the updated gendoc to make these edits

**Comment by dmuelle** [comment]
We're having problems building the MP 4.0 javadoc. Steven and Alasdair are working on a fix. In addition to [the Fault tolerance topic](https://www.openliberty.io/docs/latest/fault-tolerance.html), the [Health checks for microservices topic](https://www.openliberty.io/docs/latest/health-check-microservices.html) needs to be updated  once this is fixed

**Comment by dmuelle** [comment]
also need to update link to MP Javadoc in external-configuration.adoc when the others are updated

**Comment by dmuelle** [comment]
changes sent to vNext in #4043. Closing this issue

**Comment by Azquelt** [comment]
Thanks David :smiley:
