### ISSUE TITLE
Instructions for running OL in FIPS-enabled cluster

### ISSUE THREAD

**Issue by jantley-ibm** [OpenLiberty/docs#3416]
These instructions were put together by Monica Tamboli in SVT for CP4Apps, but they really apply to Open Liberty. We can discuss whether it would be best as a blog post or guide.

Below instructions are to config, depoy and run any Liberty application with FIPS enabled. 

Pre-requisites:
* OCP cluster is deployed. For this testing FIPS was enabled on the OCP cluster. These instructions should work on OCP cluster which does not have FIPS enabled.
* CP4Apps 4.3 is installed. Below instruction is only using OpenLibertyOperator which was installed using CP4Apps. So CP4Apps is not required as OpenLibertyOperator can be installed independently of CP4Apps.

**Note:**  OpenLiberty application with OpenJDK deploys fine on FIPS enabled OCP but it does not have FIPS enabled for Liberty
```
product = Open Liberty 20.0.0.12 (wlp-1.0.47.cl201220201111-0736)
wlp.install.dir = /opt/ol/wlp/
server.output.dir = /opt/ol/wlp/output/defaultServer/
java.home = /opt/java/openjdk/jre
java.version = 1.8.0_272
```

**Procedure:**

**1. Create Liberty Image with FIPS enabled**
Here is the  general [doc link](https://github.com/OpenLiberty/ci.docker#container-images) on creating Liberty images.
* Make sure to use the open liberty image which use IBM JDK to enable FIPS for Liberty. Replace liberty image in Dockerfile `FROM openliberty/open-liberty:20.0.0.12-full-java8-ibmjava-ubi`
* Make sure SSL is enabled for liberty server. Add `<feature>transportSecurity-1.0</feature>` to server.xml
*  Set the `com.ibm.jsse2.usefipsprovider` system property to enable FIPS mode in the IBMJSSE2 provider. Create or update `jvm.options` file in server config directory to set this property. Check this [link](https://www.ibm.com/support/knowledgecenter/en/SSYKE2_8.0.0/com.ibm.java.security.component.80.doc/security-component/jsse2Docs/enablefips.html) for more details: 
```
#cat jvm.options
-Dcom.ibm.jsse2.usefipsprovider=true
#The com.ibm.jsse2.JSSEFIPS=true system property is deprecated because it does not support TLS 1.1, TLS 1.2, elliptic curve, AES-GCM or other new cipher suites.
```
* Ensure that the JCE FIPS provider `com.ibm.crypto.fips.provider.IBMJCEFIPS
` that you want to use is in the provider list in the JAVA_HOME/jre/lib/security/java.security file.
* Copied the java.security file from the existing liberty container with IBM JDK and updated to add FIPS provider.
  $oc rsync <libertycontainer>:/opt/ibm/java/jre/lib/security/java.security .
  $ vi java.security
```
#Added the security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS on top
security.provider.1=com.ibm.crypto.fips.provider.IBMJCEFIPS
```
* Make sure Dockerfile copies updated server.xml, jvm.options and java.security to appropriate locations
```
FROM openliberty/open-liberty:20.0.0.12-full-java8-ibmjava-ubi

COPY --chown=1001:0 src/main/liberty/config /config/
COPY --chown=1001:0 <app> /config/apps
COPY --chown=1001:0 java.security /opt/ibm/java/jre/lib/security
RUN configure.sh
```
* Login to ocp cluster using `oc login` command
* Create a project for your liberty application
$  oc new-project ol-app
* Build updated Liberty image
$docker build -t <image_name> -f Dockerfile.ibmjdk  .
* Login to your image registry and push the image. In this example, using OCP internal registry:
$ docker tag default-route-openshift-image-registry.apps.mst45fips.cp.fyre.ibm.com/ol-app/<image_name>
$ docker push default-route-openshift-image-registry.apps.mst45fips.cp.fyre.ibm.com/ol-app/<image_name>

**2. Deploy Liberty Image to OpenShift Cluster**
* There are various ways to deploy this Liberty image to OCP cluster. will OpenLibertyOperator is used here. It is important that route for application is enabled for SSL to use FIPS. Here is the [guide](https://github.com/OpenLiberty/open-liberty-operator/blob/master/doc/user-guide.adoc) for OpenLibertyOperator for more details.
```
$ cat app-deploy_ssl.yaml
apiVersion: openliberty.io/v1beta1
kind: OpenLibertyApplication
metadata:
  name: inventory-ibmjdk
spec:
  replicas: 1
  applicationImage: default-route-openshift-image-registry.apps.mst45fips.cp.fyre.ibm.com/ol-app/inventory_ibmjdk
  expose: true
  route:
    termination: reencrypt
  service:
    annotations:
      service.beta.openshift.io/serving-cert-secret-name: inventory-ibmjdk-svc-tls
    certificateSecretRef: inventory-ibmjdk-svc-tls
    port: 9443
```
* Deploy the application to OCP
$ oc deploy -f app-deploy_ssl.yaml
* Check application pod and route
```
$ oc get pods
inventory-ibmjdk-687487479-4rxk7   1/1     Running   0          36h
$ oc get routes|grep jdk
inventory-ibmjdk   inventory-ibmjdk-ol-app.apps.mst45fips.cp.fyre.ibm.com          inventory-ibmjdk   9443-tcp   reencrypt     None
```
* Open a browser and access the above route on `https`.  For example,  https://inventory-ibmjdk-ol-app.apps.mst45fips.cp.fyre.ibm.com

**3. Verify FIPS is enabled on Liberty server**
 * Enable the trace by updating jvm.options to add this property and rebuild liberty image and redeploy the new image to OCP.
```-Djavax.net.debug=all
```
* Access the liberty application on https again.
* Check logs on liberty container:
```
 $oc rsh inventory-ibmjdk-687487479-4rxk7 bash
bash-4.4$ more /logs/messages.log
....
[12/10/20 1:39:30:329 UTC] 0000002a SystemOut                                                    O IBMJSSE2 will use default FIPS provider IBMJCEFIP
S
[12/10/20 1:39:30:330 UTC] 0000002a SystemOut                                                    O Installed Providers =
[12/10/20 1:39:30:331 UTC] 0000002a SystemOut                                                    O      IBMJCEFIPS
[12/10/20 1:39:30:331 UTC] 0000002a SystemOut                                                    O      IBMJSSE2
[12/10/20 1:39:30:331 UTC] 0000002a SystemOut                                                    O      IBMJCE
[12/10/20 1:39:30:332 UTC] 0000002a SystemOut                  
...
$  grep ClientHello /logs/messages.log
[12/10/20 1:41:05:885 UTC] 00000042 SystemOut                                                    O *** ClientHello, TLSv1.2
```

**Comment by Charlotte-Holt** [comment]
This won't be a blog post or guide, but it will go into the OL docs. SME: @acdemyers.

**Comment by anneqm** [comment]
@Charlotte-Holt thank you!   Can you share what the preprod and final link will be for this?  what's the date this will be published?  We want to reference it from our new "Considerations for FIPS compliance testing" page in CP4Apps.

**Comment by Charlotte-Holt** [comment]
@anneqm It's ready for review on the draft site now! You can review it at https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/running-ol-fips-cluster.html. We're targeting this to publish in the 21.0.0.2 release on 2/19. 

@acdemyers This is ready for your review. Please let me know if you have any questions.

**Comment by acdemyers** [comment]
I've looked a the document.  How to setup the JDK to use FIPs looks good to me.   I'm not familiar with the docker and oc command so please have some one more familiar with docker and oc to ensure the commands are correct.

**Comment by mtamboli** [comment]
@Charlotte-Holt - Couple of minor updates:

1. Do we want to add link to setting [OCP cluster in FIPS mode](https://docs.openshift.com/container-platform/4.6/installing/installing-fips.html)
https://www.openshift.com/blog/transferring-files-in-and-out-of-containers-in-openshift-part-1-manually-copying-files

2. Step 5) $ oc rsync :/opt/ibm/java/jre/lib/security/java.security .
It should be $ oc rsync <pod_name>:/opt/ibm/java/jre/lib/security/java.security .
Here is the link to the rsync command: https://www.openshift.com/blog/transferring-files-in-and-out-of-containers-in-openshift-part-1-manually-copying-files

**Comment by anneqm** [comment]
@Charlotte-Holt What will be the final URL?  We'll add a link to this new page from our KC.  Thank you!

**Comment by jantley-ibm** [comment]
@anneqm the final URL will be https://openliberty.io/docs/latest/running-ol-fips-cluster.html

**Comment by Charlotte-Holt** [comment]
@mtamboli I addressed your feedback. Could you review https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/running-ol-fips-cluster.html again? Thanks!

**Comment by mtamboli** [comment]
@Charlotte-Holt It looks good to me.

**Comment by anneqm** [comment]
A couple updates after another review with Monica, Michael Cheng, and Jeff Antley this afternoon. 

In the "Creating an Open Liberty Docker image that has FIPS enabled" section, we suggest that this be more focused on how to do without dependency on OpenShift. 
so, the follow items should be updated:
Step 5. "Run the oc rsync command and the..."  to re-write with alternative to OpenShift, ie using Docker - @mtamboli or Michael Cheng will help. 
Step 6.   And a link back to the OL docs for the how to create RUN configure.sh command
Step 7 and 8) Move these two steps to next section titled, Deploying the Open Liberty image to your OpenShift Cluster" as new step 1 and step 2.. Existing step 1 becomes step 3 and so on.

**Comment by anneqm** [comment]
@Charlotte-Holt

**Comment by anneqm** [comment]
link to draft blog post: https://draft-openlibertyio.mybluemix.net/blog/2021/02/17/running-ol-fips-cluster.html

**Comment by NottyCode** [comment]
This is not a blog post. A blog post is not just a bulleted list. Blog posts tell a story, they have a beginning, middle and end and this is just a middle, and not a very engaging one.

Some feedback on the bullets:

1. Step 3 talks about enabling JSSE trace which I don't think should be here.
2. Step 4 says to verify the java.security file lists the IBMJCEPlus, but we provide the base image and Java so we should know this.
3. We should make it clear these instructions only apply to IBM Java 8
4. Step 6 seems to be telling the customer to rebuild the IBM provided docker image. We should not do that.
5. Step 7 have a typo for the docker command line
6. Step 7 shows retagging the image, but why wouldn't we just set the tag name in step 6 when docker build is run?
7. All instances of SSL should be changed to TLS
8. The verification example relies on enabling trace to determine if FIPS is enabled. I think this is problematic since I doubt anyone would want to run this in production.
9. We should talk about container images rather than docker images.

**Comment by Charlotte-Holt** [comment]
Corresponding Liberty KC issue: https://github.ibm.com/websphere/liberty-docs/issues/2212. We won't be including this topic in the OL docs.
