### ISSUE TITLE
Fix incorrect link in Security Hardening topic

### ISSUE THREAD

**Issue by arkarkala** [OpenLiberty/docs#3417]
The "Configure applications to run on a virtual host" link in Network Hardening under Security Hardening topic (https://openliberty.io/docs/20.0.0.12/security-hardening.html) is taking to a wrong link (https://openliberty.io/docs/20.0.0.12/logstash-events-list.html#_server_and_host_names_in_virtualized_environments). We should also provide more info. on the security hardening that virtual hosts configuration provides.

**Comment by irobins** [comment]
Regarding "We should also provide more info. on the security hardening that virtual hosts configuration provides."...
Specifically " Configure applications to run on a virtual host" is not sufficient for a hardened configuration - the requirement is that there should not be a hostAlias that matches to * in a hardened configuration.

**Comment by Charlotte-Holt** [comment]
I moved this information to https://github.com/OpenLiberty/docs/issues/3318, which is the high priority item for a new topic on virtual hosts. Closing this issue.

**Comment by dmuelle** [comment]
Re-opening this issue as we are publishing a topic on Virtual hosting ( #3318) with 21.0.0.10. Need to update the link in the network hardening doc, but also add a section for securing virtual hosts

**Comment by dmuelle** [comment]
changes on vNext, doc will publish with 21.0.0.10
