### ISSUE TITLE
Italicize variables in command topics 

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3422]
When @chirp1 reviewed the `featureUtility` commands, she noted two things that need to be reviewed and possibly fixed:

1. Italicize ` _path_to_liberty_ `
2. Italicize variables in the syntax statements like `featureUtility installServerFeatures serverName [options]`. `serverName` might normally be in italics, and `[options]` probably should be, too.

**Comment by ManasiGandhi** [comment]
https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/command/featureUtility-find.html
https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/command/featureUtility-help.html
https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/command/featureUtility-installFeature.html
https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/command/featureUtility-installServerFeatures.html
https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/command/featureUtility-viewSettings.html
