### ISSUE TITLE
Java SE support - 2Q 2021

### ISSUE THREAD

**Issue by irobins** [OpenLiberty/docs#3423]
By2Q21 adoptopenjdk.net should have been transitioned to Eclipse Adoptium. The Java SE support doc https://openliberty.io/docs/20.0.0.10/java-se.html will need to be updated to change references from AdoptOpenJDK to Eclipse Adoptium distributions and/or others including IBM and RH.

**Comment by irobins** [comment]
Per @gcharters
We'll also need to update https://www.ibm.com/support/pages/single-stream-continuous-delivery-sscd-software-support-lifecycle-policy-websphere-liberty
Our licenses reference IRB, so so long as IRB gets updated to reflect the Adoptium change, then we're good.

**Comment by dmuelle** [comment]
Hi @irobins, I was just reviewing this issue and found this information from [the Adoptium blog](https://blog.adoptium.net/2021/03/eclipse-adoptium-announcement/):

"It will take some time to fully migrate our build farm and code, so in the meantime AdoptOpenJDK will continue to make binaries available as usual. The current expectation is that the first formal release of Eclipse Temurin binaries will be the July quarterly updates."

In light of this information, should we wait to update our references and links from AdoptOpenJDK--->Adoptium until the migration of binaries is complete?

**Comment by dmuelle** [comment]
new URL should be https://adoptium.net/

no binaries available yet

**Comment by dmuelle** [comment]
Draft is now updated:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.9/java-se.html

Note that we left references to AdoptOpenJDK for Java SE 15 since neither semeru nor Adoptium offer 15.
for further discussion, see [this slack thread](https://ibm-cloud.slack.com/archives/C31DW78RG/p1628520516034000)

updates will publish with 21.0.0.9 docs release

@irobins @mbroz2

**Comment by dmuelle** [comment]
updated the Semeru link to point directly to downloads page

**Comment by dmuelle** [comment]
Changes are now on vNext and will publish with 21.0.0.9 on 9/3
