### ISSUE TITLE
Authorization - role to group bindings

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3424]
From KC review of [Authorization topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_authorization.html#cwlp_authorization__auth_subject) with Alasdair (check with Ajay).

In Java EE they address the all_authenticated with a special role name and we should definitely document that. Ajay knows what it is (Alasdair can never remember.) Add into the Authorization topic - something about configure role to group bindings, which is the gap. Just slot it into there. See also the [KC section on role mapping binding](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_authorization.html#cwlp_authorization__role_mapping_binding). By default we map roles to groups with same name (eg fred:fred) - as most people just specify group names and consider them role names. Can specify mapping manually if they don't match then.

Background (also from Alasdair so check this actually is relevant and I've not just misunderstood something):

>special subjects - when you've got an app with security enabled, it's defined as roles: people with this role can do x, people with that role can do y. Then map users and groups to roles. Sometimes you don't care about giving people users or groups, just care that they're authenticated. So could go in backend repo and generate a group that contains everyone in registry (which isn't good for perf if you have a reg of 400k people), so instead you could just set so any resource that claims it needs this role, everyone's Settings page, say. In Twitter, access to Settings page wouldn't only let certain users access settings page - anyone authn can access it as long as they're logged in (with the right settings on it - it's the same page with different data). They might also have a page for superusers and make sure that only certain people in their user reg (eg certain Twitter employees) can access that page at all.

**Comment by dmuelle** [comment]
I believe all this is now covered in the https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/authorization.html#_define_roles_in_your_application section, how to map roles to groups and specify when any authn user can access a resource
