### ISSUE TITLE
Microservice health checks (MP37)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#343]
Target audience: microservice developer

Write short conceptual topic introducing MP Health, focus on annotations approach, and link to relevant guides.

(Talk to Laura about what's changed in MP Healthcheck. see also #308)

Sources of info:
- https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_microprofile_healthcheck.html

Don't write this until version 3.0 comes out.

**Comment by dmuelle** [comment]
Initial draft/ outline at 

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#monitoring.html

Needs tech review- particularly the endpoint descriptions

Will this topic include code examples? I don't think we have examples of the new endpoints anywhere in the guides yet- not sure if they should go here or be linked to a forthcoming guide/ blogpost

**Comment by dmuelle** [comment]
Hi @fmhwong, can you provide a tech review of this short draft? Particularly the endpoint descriptions

**Comment by dmuelle** [comment]
@lauracowen just heard from @pgunapal that MPH 3.0 won't be out until 3Q or 4Q-
At the top of this issue it says "Don't write this until version 3.0 comes out." Does that mean this should be put into the backlog until 3.0 is out?

**Comment by pgunapal** [comment]
@dmuelle I reviewed the short draft, for the end point descriptions. below are more suggestions:

/health/ready: returns the readiness of a service, or whether it boots successfully. This endpoint corresponds to the Kubernetes readiness probe.

Change to:
/health/ready: returns the readiness of a service, or whether if it is ready to process requests. This endpoint corresponds to the Kubernetes readiness probe.

/health/live: returns the liveness of a service, or whether it has encountered a bug or deadlock. This endpoint corresponds to the Kubernetes liveness probe.

Change to:
/health/live: returns the liveness of a service, or whether it has encountered a bug or deadlock. This endpoint corresponds to the Kubernetes liveness probe. This means that if this check fails, the service cam discarded (terminated or shut down).

**Comment by dmuelle** [comment]
New draft available at

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#health-check-microservices.html

needs code examples, whether a sample config with new endpoints and annotations or something more procedural is TBD

**Comment by dmuelle** [comment]
New draft with code examples

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#health-check-microservices.html

**Comment by dmuelle** [comment]
New draft with code examples covering new annotations and endpoints

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#health-check-microservices.html

**Comment by dmuelle** [comment]
Doc is now published at https://www.openliberty.io/docs/ref/general/#health-check-microservices.html
