### ISSUE TITLE
Update tuning server config gendoc

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3430]
This [KC topic about Tuning](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_tun.html) is mostly manually written duplicate of the server config gendoc topic for [httpoptions](https://www.openliberty.io/docs/latest/reference/config/httpOptions.html), [connectionmanager](https://www.openliberty.io/docs/latest/reference/config/connectionManager.html), [datasource](https://www.openliberty.io/docs/latest/reference/config/dataSource.html). There seems to be a bit more info in the KC topic about some of the options at least.

Go through the options and, if the KC description of any is better, raise issues against `open-liberty` repo to get the source updated.

**Comment by dmuelle** [comment]
opened the following PRs on the Open Liberty repo to address these issues:
- https://github.com/OpenLiberty/open-liberty/pull/16123
- https://github.com/OpenLiberty/open-liberty/pull/16124
- https://github.com/OpenLiberty/open-liberty/pull/16125

**Comment by dmuelle** [comment]
closing this issue, updates will be addressed in the previously referenced PRs on the Open/open-liberty repo
