### ISSUE TITLE
Check if other locations for configuration should be listed in MP Config topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3436]
The [external configuration](https://www.openliberty.io/docs/latest/external-configuration.html) topic lists locations where config can be done in order of precedence. However, there are more locations listed in the [KC topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_microprofile_appconfig_validsources.html).

Check with SME/Alasdair if these other locations should be included in the OL topic. Also consider how this info fits in with relevant info in the [Server Config overview topic](https://www.openliberty.io/docs/latest/reference/config/server-configuration-overview.html) (if applicable, avoid duplication and link between the topics as necessary to make it all make sense).

**Comment by Charlotte-Holt** [comment]
Possibly do this work with #3443

**Comment by ManasiGandhi** [comment]
Tracking this with #3443
