### ISSUE TITLE
Investigate what else would need documenting for MP Config

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3437]
The [KC topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_microprofile_overview.html) seems to be a dump of the spec when not all that info is probably needed in order to just use MP Config in the most productive way. Work with an SME to identify useful pieces of info that a developer would need to understand to be able to use MP Config as described in the [guides](https://www.openliberty.io/guides/#configuration) and/or extend what's demonstrated in the guides.

Make sure not to duplicate info that's in the [MP Config feature doc](https://www.openliberty.io/docs/20.0.0.12/reference/feature/mpConfig-1.4.html) and MP Config Javadoc (https://www.openliberty.io/docs/modules/reference/microprofile-3.3-javadoc/org/eclipse/microprofile/config/package-frame.html, https://www.openliberty.io/docs/modules/reference/microprofile-3.3-javadoc/org/eclipse/microprofile/config/inject/package-frame.html, https://www.openliberty.io/docs/modules/reference/microprofile-3.3-javadoc/org/eclipse/microprofile/config/spi/package-frame.html).

**Comment by Joseph-Cass** [comment]
Comparing the current documentation to the guides, [this guide](https://www.openliberty.io/guides/microprofile-config-intro.html#background-concepts) describes 5 default config sources, where [the documentation](https://www.openliberty.io/docs/20.0.0.12/external-configuration.html) only describes 3.

**Comment by ManasiGandhi** [comment]
Tracking this with #3443
