### ISSUE TITLE
Update Metrics Reference List for Fault Tolerance 3.0

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/docs#3438]
Fault Tolerance 3.0 changes the metrics produced by Fault Tolerance.

All the existing metrics in the [Metrics Reference List][metrics-list] which are added by Fault Tolerance should be removed and replaced with the new [Fault Tolerance 3.0 metrics list][ft30-list].

In addition the `ft-metric-features` placeholder will need to be updated to list mpFaultTolerance-3.0 and mpMetrics-3.0.

[metrics-list]: https://openliberty.io/docs/20.0.0.12/metrics-list.html
[ft30-list]: https://gist.github.com/Azquelt/a550707e8edb89383669e14084077717

**Comment by Charlotte-Holt** [comment]
@Azquelt Updated. Please review the updates at https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/metrics-list.html.

**Comment by Charlotte-Holt** [comment]
Feedback from @Azquelt:

- The "Version introduced" column should probably list "MicroProfile Fault Tolerance 3.0" rather than a version of MP Metrics
- Since the metrics are defined in the FT spec, rather than the metrics spec
- They can all say FT 3.0 since all the metrics changed in 3.0

**Comment by Charlotte-Holt** [comment]
@Azquelt I incorporated these changes. Could you take another look: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/metrics-list.html.

**Comment by Azquelt** [comment]
Looks good :+1: thanks

**Comment by dmuelle** [comment]
peer reviewed in #3277

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3734
