### ISSUE TITLE
Investigate what, if any, additional info is required for MP JWT

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#3439]
Investiaget what's needed beyond the info in https://www.openliberty.io/docs/latest/single-sign-on.html#_json_web_token_jwt and https://www.openliberty.io/guides/microprofile-jwt.html for the majority of users to use it. We also have javadoc and gendoc for MP JWT, so don't duplicate that.

**Comment by Charlotte-Holt** [comment]
This work will be covered in #3511
