### ISSUE TITLE
Add missing info into MP Metrics Javadoc (MP32)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#344]
Based on the MP Metrics spec, provide text for the missing fields in the MP Metrics Javadoc. See https://ibm.box.com/s/0wwr2eaxtg39jbeue02usw7e4di32zc0 for examples of problems.

Javadoc pages to review and provide updates for:

- Counted: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Counted.html
- Gauge: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Gauge.html
- Metered: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Metered.html
- Timed: https://www.openliberty.io/docs/ref/microprofile/2.2/#package=org/eclipse/microprofile/metrics/annotation/package-frame.html&class=org/eclipse/microprofile/metrics/annotation/Timed.html

Spec from which to obtain missing information:
- https://download.eclipse.org/microprofile/microprofile-metrics-2.0.0/microprofile-metrics-spec-2.0.0.html#api-annotations

Process to submit new text:
- You probably won't be able to make the edits directly as Javadoc is generated from the source code. Talk to Laura and Emily Jiang about how it is best to raise the changes. It may be that raising issues is sufficient or providing some file of the suggested changes. Follow whatever process is agreed with Emily and document the process briefly.

Style:
- Follow Javadoc best practices for how to structure the sentences. See https://ibm.box.com/s/3uy0l7mph3h94it5x4rmogyyr07h2bk1 (public link) for a list of sources I compiled a while back. And to see examples of why it's important to developers to have good Javadoc (ie they use it in IDEs as context help, not just reading it in HTML pages in the Docs).

**Comment by chirp1** [comment]
This issue would be fore development to address. ID doesn't write or maintain the javadoc.

**Comment by lauracowen** [comment]
The action is to review and provide the information that is considered to be missing and then to raise an issue against it which development can then implement. Javadoc is part of the documentation experience for developers, and is the primary documentation they use often (eg it appears as context help in their IDE). Poor Javadoc impacts on their experience of using MicroProfile.

**Comment by chirp1** [comment]
Hi Laura, Ming and I discussed this issue. He and I agree that this particular issue is something to be addressed elsewhere than the ID team. There seems to be a problem with the javadoc process, The cause of the problem should be identified by somebody, likely someone that handles the javadoc process.  For instance, they could investigate the cause of the missing information in the javadoc fields and come up with a solution, likely automated since the javadoc is generated, so that the javadoc does not have missing information.

**Comment by lauracowen** [comment]
Issues raised against developers: https://github.com/eclipse/microprofile-metrics/issues/511
