### ISSUE TITLE
Metrics Reference List Missing Required Features for GRPC metrics in 20.0.0.12

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/docs#3458]
The page; https://openliberty.io/docs/20.0.0.12/metrics-list.html

The listed GRPC metrics require a feature (besides) `mpMetrics-2.x` to be available.

The `grpc.server.*` metrics require [grpc-1.0](https://openliberty.io/docs/20.0.0.12/reference/feature/grpc-1.0.html) and the `grpc.client.*` metrics require [grpcClient-1.0](https://openliberty.io/docs/20.0.0.12/reference/feature/grpcClient-1.0.html) feature.

**Comment by Charlotte-Holt** [comment]
@Channyboy Updated! Please review https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/metrics-list.html.

**Comment by Channyboy** [comment]
Looks good! LGTM

**Comment by Charlotte-Holt** [comment]
Merged to `vNext` in https://github.com/OpenLiberty/docs/pull/3734
