### ISSUE TITLE
Update Logstash Collector setup instruction to use PKCS12 keystore type

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#3468]
Page to be updated: https://openliberty.io/docs/20.0.0.12/forwarding-logs-logstash.html

Since Liberty 19.0.0.3, default keystore type has been changed from JKS to PKCS12.  We need to update the above page to use the new keystore type.

Steps:-

3. Complete the following steps for each Open Liberty server that you want to collect events from:
  
3a. Acquire or create a keystore for the Open Liberty server. To create a self-signed certificate, run the `securityUtility` command from `wlp_install_dir/bin` folder. Customize the server name, password, and subject as needed:
```
securityUtility createSSLCertificate --server=server1 --password="Liberty" --subject=CN=myHostname,OU=server1,O=ibm,C=us
```
  The default keystore `key.p12` is created under `wlp_install_dir/usr/servers/server1/resources/security` folder.  Add the server configuration snippet from the command output to the `server.xml` file.

  3b. Import the `logstash.crt` file that you created in step 1 into the `key.p12` file in your server with the `keytool` command from the JDK. In the following example, customize the `wlp_install_dir` directory and server name as needed. When prompted for a password, use the certificate password that you specified in step 3a:
```
keytool -importcert -noprompt -alias logstash -file logstash.crt -keystore wlp_install_dir/usr/servers/server1/resources/security/key.p12 -storepass Liberty
```

**Comment by dmuelle** [comment]
Hi @fmhwong , I've updated this file on our draft site, can you please review the changes/
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/forwarding-logs-logstash.html

I had two questions

"Add the server configuration snippet from the command output to the server.xml file."

Can we provide an example of what this looks like? I want top make sure it's clear to the user. I tried running the command on a test server but I didn't have enough of the necessary config in place to generate example output.

"Import the logstash.crt file that you created in step 1 into the key.p12 file in your server with the keytool command _from the JDK_." 

Does this mean the JDK provides the keytool command?

Thanks!

**Comment by fmhwong** [comment]
The output from the createSSLCertificate:

```
Creating keystore wlp_install_dir/usr/servers/server1/resources/security/key.p12

Created SSL certificate for server s1. The certificate is created with CN=myHostname,OU=server1,O=ibm,C=us as the SubjectDN.

Add the following lines to the server.xml to enable SSL:

    <featureManager>
        <feature>ssl-1.0</feature>
    </featureManager>
    <keyStore id="defaultKeyStore" password="{xor}EzY9Oi0rJg==" />
```

The `keytool` command is provided from the JDK.

**Comment by fmhwong** [comment]
I also corrected a mistake I made before.

In step 3a, I updated the server name of the command.

```
securityUtility createSSLCertificate --server=server1 --password="Liberty" --subject=CN=myHostname,OU=server1,O=ibm,C=us
```

**Comment by dmuelle** [comment]
Thanks, @fmhwong. Please review the updated draft: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/forwarding-logs-logstash.html

If anything further is needed, just let me know. If it looks good, please add the `Developer reviewed` label to this issue.

**Comment by fmhwong** [comment]
Two minor changes needed:

1)
From:
```
d:\wlp\bin\securityUtility createSSLCertificate --server=server1 --password="Liberty" --subject=CN=myHostname,OU=defaultServer,O=ibm,C=us
```
to 
```
d:\wlp\bin\securityUtility createSSLCertificate --server=server1 --password="Liberty" --subject=CN=myHostname,OU=server1,O=ibm,C=us
```

2)
From:
```
Created SSL certificate for server s1. The certificate is created with CN=myHostname,OU=server1,O=ibm,C=us as the SubjectDN.
```
to 
```
Created SSL certificate for server server1. The certificate is created with CN=myHostname,OU=server1,O=ibm,C=us as the SubjectDN.
```

**Comment by dmuelle** [comment]
Thanks @fmhwong - I've updated the draft: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/forwarding-logs-logstash.html

**Comment by dmuelle** [comment]
changes are on vNext and will publish with the 21.0.0.1 docs release. Closing this issue
