### ISSUE TITLE
Bug in ACME example

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3474]
@NottyCode found a bug. In https://openliberty.io/docs/20.0.0.12/reference/feature/acmeCA-2.0.html, 

```
<acmeCA>
    ...
    <renewBeforeExpiration>24h</renewBeforeExpiration>
</acmeCA >
```

should be:

`<acmeCA renewBeforeExpiration="24h" />
`

The old example might work, but it doesn't meet the schema

**Comment by Charlotte-Holt** [comment]
@NottyCode I updated the example in https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/reference/feature/acmeCA-2.0.html. Let me know if further changes are needed.

**Comment by NottyCode** [comment]
looks good to me.

**Comment by Charlotte-Holt** [comment]
Merged to `vNext`.
