### ISSUE TITLE
The menu on the left side of the website cannot be clicked

### ISSUE THREAD

**Issue by meilka1** [OpenLiberty/docs#3495]
![image](https://user-images.githubusercontent.com/45584068/105000469-5770ac80-5a69-11eb-8963-1886f719d43f.png)
The menu on the left side of the website cannot be clicked ！！！

**Comment by dmuelle** [comment]
Hi @meilka1 -Are you still experiencing this issue? I cannot re-create the problem on my end, the navigation is working as expected. When you visit https://www.openliberty.io/docs/20.0.0.12/overview.html, the TOC should already be expanded, not collapsed as in your screenshot.  It shouldn't matter, but what browser were you using?

**Comment by meilka1** [comment]
Hi, thank you for your response. I use chrome and I opened f12 yesterday to look for the problem. And I find the browser cant download the jquery-3.3.1 script of this page&nbsp; that made the problem I found.&nbsp; But this morning, this problem has been solved. thank you .



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "David Mueller"<notifications@github.com&gt;; 
发送时间: 2021年1月20日(星期三) 凌晨1:34
收件人: "OpenLiberty/docs"<docs@noreply.github.com&gt;; 
抄送: "Tian."<121079747@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [OpenLiberty/docs] The menu on the left side of the website cannot be clicked (#3495)





 
Hi @meilka1 -Are you still experiencing this issue? I cannot re-create the problem on my end, the navigation is working as expected. When you visit https://www.openliberty.io/docs/20.0.0.12/overview.html, the TOC should already be expanded, not collapsed as in your screenshot.  It shouldn't matter, but what browser were you using?

**Comment by dmuelle** [comment]
Thanks- glad to hear you are no longer experiencing the problem. Let us know if you have any further trouble. Closing this issue
