### ISSUE TITLE
mpRestClient-2.0 updates

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/docs#3501]
The documentation at https://openliberty.io/docs/20.0.0.12/rest-clients.html could be updated to include new information for MicroProfile Rest Client 2.0 (currently in beta).

This document overall is still relevant - the concepts of MP Rest Client has not changed, but one sentence should be updated to reflect changes in Rest Client 2.0:
> If the return type is a `CompletionStage`, the service is invoked asynchronously; all other return types are invoked synchronously.

Server Sent Events are a new part of MP Rest Client 2.0, and consuming SSEs is done asynchronously, but it does not use the `CompletionStage` return type - instead, it uses the `Publisher` return type (provided by the [Reactive Streams APIs](https://www.reactive-streams.org/announce-1.0.3)).

I chatted with Karen about rephrasing this:
> Andy McCright 10:58AM
Hi Karen - regarding MP Rest Client ID - Emily suggested this page might need updates: https://openliberty.io/docs/20.0.0.12/rest-clients.html
It is basically a concept page, and the concepts are still the same.  All of the text in the page is still accurate except this one sentence:
If the return type is a CompletionStage, the service is invoked asynchronously; all other return types are invoked synchronously.
Server Sent Events in Rest Client 2.0 are also asynchronous and they use a Publisher  return type.  So we could change this sentence to be something like:
If the return type is a CompletionStage or Publisher  (for Server Sent Events), the service is invoked asynchronously; all other return types are invoked synchronously.
Would you like me to open an issue for this?
oh, and welcome back!  :slightly_smiling_face:

> Karen Deen  11:48 AM
Hi Andy, Yes, open an issue and indicate what needs to be changed. Would you let me know the issue number?  I think you are saying that before Rest Client 2.0, that one sentence was accurate. So, I think we would want to tell the writer to leave the info from the original sentence in the topic, but clarify that the info is for the feature versions before Rest Client 2.0. And then the new sentence is for Rest Client 2.0 and later.

> Andy McCright  12:25 PM
Yes, that's correct. I'll open an issue shortly.

**Comment by Rwalls1** [comment]
@andymc12 Please review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/rest-clients.html

**Comment by andymc12** [comment]
> In MicroProfile Rest Client versions before MicroProfile Rest Client 2.0, if the return type is a CompletionStage, the service is invoked asynchronously and all other return types are invoked synchronously. With MicroProfile Rest Client 2.0, the service invokes asynchronously and invokes all other return types synchronously if the return type is a Publisher. One advantage of asynchronous behavior is that multiple services can be invoked simultaneously, resulting in faster overall execution.

In 2.0, methods with return types of `CompletionStage` are still asynchronous - the main difference is that in 2.0, `Publisher` is also asynchronous.  So maybe we could re-phrase it something like:

> If the return type is a CompletionStage, the service is invoked asynchronously and all other return types are invoked synchronously. With MicroProfile Rest Client 2.0, a method with the return type of Publisher is also invoked asynchronously. One advantage of asynchronous behavior is that multiple services can be invoked simultaneously, resulting in faster overall execution.

**Comment by Rwalls1** [comment]
@andymc12 Thanks, please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/rest-clients.html

**Comment by andymc12** [comment]
HI @Rwalls1 - the latest changes look good to me!  Thanks!

**Comment by Charlotte-Holt** [comment]
@Rwalls1 This update looks good to me from a content perspective. Thanks! You can send this off to peer review.

**Comment by andymc12** [comment]
@Charlotte-Holt @Rwalls1 - just FYI, the MP 4.0 project (which includes `mpRestClient-2.0`) has slipped to 21.0.0.3 (possibly later). The docs look good, but will need to wait until at least the next release before it should go on the public website.  Thanks again for all the work on this!

**Comment by dmuelle** [comment]
## Peer review

Hi @Rwalls1 - I just see a few minor things with this topic- not necessarily specific to your updates but would be good to fix with we're working on it. Mostly problems from my original draft :(

### MicroProfile Rest client

The template interface you build maps to the remote service that you want to call.
--->
The template interface that you build maps to the remote service that you want to call.

This saves you the time and trouble of having to write the boilerplate code...
--->
This template saves you the trouble of writing the boilerplate code ...

You only need to define...
--->
You need to define only...

### Synchronous & asynchronous REST clients

Before MicroProfile Rest Client 2.0, if the method has a CompletionStage return type  
--->
In MicroProfile Rest Client 2.0 earlier, if the method has a CompletionStage return type

With MicroProfile Rest Client 2.0,
--->
In MicroProfile Rest Client 2.0 and later,

### Consuming RESTful APIs

 look for language mechanisms that enable you to ignore unknown variables
 --->
 look for language mechanisms that can ignore unknown variables

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've addressed your feedback.

**Comment by dmuelle** [comment]
Hi Richard- a few more minor edits:

- [x] to avoid merge conflicts in your branch, change `image::REST_example_2.png[REST client example, 1075, 381]` to `image::REST_example_3.png[REST client example, 1075, 381]` (only the number in the filename changes)
- [x] change: `This template saves you the time and trouble of having to write the boilerplate code, such as setting up a client class, connecting to the remote server, or invoking the correct URI with the correct parameters.` ---> `This template saves you the trouble of writing boilerplate code, such as setting up a client class, connecting to the remote server, or invoking the correct URI and parameters. 
- [x] Synchronous & asynchronous REST clients--> Synchronous and asynchronous REST clients`
- [x] Throughout, replace "invoke" with "call"

**Comment by Rwalls1** [comment]
These updates have been merged to vnext and will publish in the upcoming release.
