### ISSUE TITLE
Document mpOpenAPI limitations

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/docs#3508]
mpOpenApi currently has some limitations which users might not be expecting.

When generating the OpenAPI document, only one web module of one application is considered.

[In the knowledge center][kc-limitation] we have this text:
> If multiple applications are deployed, one application is selected to produce the OpenAPI documentation. An informational message is output to identify the application that was selected. If the selected application is running, all other applications are ignored by the application processor. After the selected application is stopped, the next application is processed.

Some additional text is probably needed here:
> If multiple web modules are included in the selected application, one web module is selected to produce the OpenAPI documentation.

These limitations are currently true for mpOpenApi-1.0, 1.1 and 2.0, though we have an issue open to review it in 2.0 OpenLiberty/open-liberty#15032

I'm not sure of the best place to document this in the OL docs as we currently don't have much documentation for OpenAPI. It could probably be integrated into #340 when that's done but I'm not sure where it should go until then.

[kc-limitation]: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_mpopenapi.html

**Comment by dmuelle** [comment]
see also #3445

**Comment by ManasiGandhi** [comment]
This has been tracked with the issue #340
