### ISSUE TITLE
Update Maven version in JDBC doc

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#3538]
per @srl295 in #3493 :

update for 3.3 final plugin.

<filter> seems to be no longer recognized

refs:

OpenLiberty/blogs#857 (comment)
OpenLiberty/ci.maven#705 (comment)

**Comment by srl295** [comment]
> `<filter>` seems to be no longer recognized

^ fixed

**Comment by dmuelle** [comment]
change delivered to `vNext`, will publish with 21.0.0.2 docs release
