### ISSUE TITLE
MicroProfile Context Propagation 1.2 documentation

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/docs#3562]
The existing MicroProfile Context Propagation documentation on openliberty.io doesn't require any updates for v1.2
https://openliberty.io/docs/20.0.0.12/microprofile-context-propagation.html

The following issues are opened for beta and GA blog posts announcing it:

Beta blog:
https://github.com/openliberty/open-liberty/issues/15617

GA blog:
https://github.com/openliberty/open-liberty/issues/15209

**Comment by chirp1** [comment]
@njr-11 As we discussed on slack, my misunderstanding- ID has no requirements to write doc for this issue. Closing. 
The epic is https://github.com/OpenLiberty/open-liberty/issues/8750 I approved the epic.
