### ISSUE TITLE
auditUtility command

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3578]
From https://github.com/OpenLiberty/docs/issues/3314, we need to document the `auditUtility` commands. See https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_audit.html and  https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_auditutil.html in the KC for more info. This doc should follow the same format as the other command docs.

**Comment by dmuelle** [comment]
need to find exit codes for these commands

**Comment by emilytee** [comment]
Reviewed the draft and approve.

**Comment by ManasiGandhi** [comment]
@dmuelle Can you content review this draft https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/auditUtility-auditReader.html?

**Comment by dmuelle** [comment]
# Content review

Looks good, just a few things to sort. You might compare against the [server package command](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/server-package.html) for consistency 

- [ ] add to the toc and add a title to the page
- [ ] `The auditUtility auditReader command decrypts and unsigns an audit log that is encrypted and signed.`
The IBM docs source says: `... that is encrypted, signed, or both.`, which is not the same thing. I think IBM docs desc is more precise
- [ ] the current usage example should be where the syntax example is. The usage example should be one of the examples from the "Usage" section of https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_auditutil.html
- [ ] for consistency with other command topics, remove the actionName section
- [ ] entires for  `auditFileLocation` and `outputFileLocation` should state that they are required options
- [ ] description of `debug` should use complete sentences and fix unclosed monospace on `true`
- [ ] check monospace throughout- `encrypted` description needs monospace around `false`
- [ ] `encKeyStoreLocation` and `signingKeyStoreLocation`- in the description, I think "file URL location" should be "file location". Check with the SME- I see IBM docs says "URL location" but the command help does not. I'm not sure why it would be a URL.  
- [ ] Title for the exit code table is leftover copy/paste

**Comment by ManasiGandhi** [comment]
@dmuelle I worked on your review. Here's the updated draft  https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/auditUtility-auditReader.html:

- [x] add to the toc and add a title to the page
- [x] `The auditUtility auditReader command decrypts and unsigns an audit log that is encrypted and signed.`
The IBM docs source says: `... that is encrypted, signed, or both.`, which is not the same thing. I think IBM docs desc is more precise
- [x] the current usage example should be where the syntax example is. The usage example should be one of the examples from the "Usage" section of https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_command_auditutil.html
- [x] for consistency with other command topics, remove the actionName section
- [x] entires for  `auditFileLocation` and `outputFileLocation` should state that they are required options
- [x] description of `debug` should use complete sentences and fix unclosed monospace on `true`
- [x] check monospace throughout- `encrypted` description needs monospace around `false`
- [x] `encKeyStoreLocation` and `signingKeyStoreLocation`- in the description, I think "file URL location" should be "file location". Check with the SME- I see IBM docs says "URL location" but the command help does not. I'm not sure why it would be a URL.  
- [x] Title for the exit code table is leftover copy/paste

**Comment by dmuelle** [comment]
Looks good @ManasiGandhi - just a few small fixes:

- [ ]  add the topic to the toc navigation
- [ ] add the topic to the [Commands overview page](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/command-overview.html). See existing entries for reference
- [ ] Suggested edit:
`The command must specify the location of the audit log to be read as well as location of the output file.`
--->
`The command must specify the locations of the audit log and the output file.`

- [ ] Typo:
`The following example demonstrates the proper syntax to unsign and audit log that is signed:`
--->
`The following example demonstrates the proper syntax to unsign an audit log that is signed:`

- [ ] `Specify the fully-qualified file location of the keystore that stores the certificate used to decrypt the audit records.`
--->
`Specify the fully-qualified file location of the keystore that stores the certificate that is used to decrypt the audit records.`

**Comment by ManasiGandhi** [comment]
@dmuelle I worked on your review. Here's the link to the updated draft https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/auditUtility-auditReader.html

- [x]  add the topic to the toc navigation
- [x] add the topic to the [Commands overview page](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/command-overview.html). See existing entries for reference
- [x] Suggested edit:
`The command must specify the location of the audit log to be read as well as location of the output file.`
--->
`The command must specify the locations of the audit log and the output file.`

- [x] Typo:
`The following example demonstrates the proper syntax to unsign and audit log that is signed:`
--->
`The following example demonstrates the proper syntax to unsign an audit log that is signed:`

- [x] `Specify the fully-qualified file location of the keystore that stores the certificate used to decrypt the audit records.`
--->
`Specify the fully-qualified file location of the keystore that stores the certificate that is used to decrypt the audit records.`

**Comment by ManasiGandhi** [comment]
https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/auditUtility-auditReader.html
