### ISSUE TITLE
Consider new topic for loose applications

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3586]
From https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_loose_applications.html in the KC. 

Notes from Alasdair in the spreadsheet: Keep this topic. Useful if a third party wants to integrate. However, where do we want this to go? Doesn't necessarily need to go on the website. On the wiki potentially? Consider options.

**Comment by Charlotte-Holt** [comment]
Incorporate info from https://github.ibm.com/websphere/liberty-docs/issues/2209, too.

**Comment by dmuelle** [comment]
duplicated by #6852
