### ISSUE TITLE
Make config example headings consistent

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#3606]
Check config examples on feature pages to ensure that headings are consistent:

- Use short declarative phrases that focus on the use goal. Avoid gerunds or awkward noun phrases not gerunds. 
- Make headings on the same page parallel. 
- update wiki] guidance

**Comment by dmuelle** [comment]
The following published feature pages will be updated for this issue:

- [x] [Application Security](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/appSecurity-3.0.html)
- [x] [Audit](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/audit-1.0.html)
- [x] [ACME](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/acmeCA-2.0.html)
- [x] [JDBC](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jdbc-4.2.html)
- [x] [Java RESTful Services Client](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/jaxrsClient-2.1.html)
- [x] [LDAP User Registry](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/ldapRegistry-3.0.html)
- [x] [Logstash Collector](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/logstashCollector-1.0.html)
- [x] [Mp Metrics](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/mpMetrics-2.3.html)
- [x] [Transport security](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/transportSecurity-1.0.html)

**Comment by dmuelle** [comment]
Updated the [wiki guidance](https://github.com/OpenLiberty/docs/wiki/How-to-add-config-examples-to-generated-feature-docs#example-headings)

**Comment by Rwalls1** [comment]
# Content review

The updated headings look good I just have a few comments:

- While the “Use an ACME test server” heading on the ACME page uses the right syntax, I’m not sure it captures the use case of the included examples. I think a better header would be something like “Manage certificates to use an ACME test server” or “Configure access to ACME test server”, to highlight more of the purpose of the examples.
- I think the “Configure a data source with authentication” heading from the JDBC page could be simplified to “Configure data source authentication” to make the purpose clearer as the phrase “with authentication” could be a bit misleading.
- I think you could also change the “Use JDBC driver classes from an application” heading from the JDBC page to something like “Enable access to JDBC driver classes” to make the purpose of the example clearer.

**Comment by dmuelle** [comment]
@Rwalls1 thanks for reviewing, I updated the headings for ACME and JDBC features per your suggestions

**Comment by ManasiGandhi** [comment]
# Peer review
- [x] **Application Security**-The level 3 link for [Disable LTPA cookies for TAI](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/appSecurity-3.0.html#_disable_ltpa_cookies_for_tai) is the only level 3 heading. Can it be removed and the heading rephrased to be used as the first sentence of the following paragraph, unless it is an important use case.

**Comment by dmuelle** [comment]
Thanks for review @ManasiGandhi , That was an oversight. I changed it to be the same level as the other examples

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/appSecurity-3.0.html#_disable_ltpa_cookies_for_tai

**Comment by dmuelle** [comment]
All updates are on vNext and will publish with 21.0.0.3
