### ISSUE TITLE
Update first paragraph of the JavaMail feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3617]
For the first paragraph of https://draft-openlibertyio.mybluemix.net/docs/21.0.0.2/reference/feature/javaMail-1.6.html. 

Suggested update [from the KC](https://www-03preprod.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_admin_javamail.html):
>If you have an external mail server, you can use the JavaMail API to send and receive email on applications that are running on an Open Liberty server. The API allows applications to interact with the external mail server by providing common store and transport protocols, such as POP3, IMAP, and SMTP.

**Comment by dmuelle** [comment]
opened a PR on the open liberty code repo for this fix: https://github.com/OpenLiberty/open-liberty/pull/16097

**Comment by dmuelle** [comment]
closing this issue, updates will be addressed in the previously referenced PR on the Open/open-liberty repo
