### ISSUE TITLE
New SIP Container custom properties 

### ISSUE THREAD

**Issue by annaguri** [OpenLiberty/docs#3651]
[1] Add a new custom property to the first table in
https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_config_sipContainer.html

Name | Type | Default | Description
-- | -- | -- | --
enableSetOutboundIF | boolean | false | On a multi-homed host, the custom property should be set to true to mandate the use of a particular outbound interface. In case the custom property is not applied or set to false, the container shall apply default behavior of interface selection.
enableSetLBOutboundIF | boolean | false | On a multi-homed host, when a loopback adapter is used as an outbound interface, the custom property should be set to true to mandate the use of the selected outbound interface. In case the custom property is not applied or set to false, the container shall apply default behavior of interface selection.
addIBMPOLBMsg | boolean | true | By default, the IBM-PO header is set in any request. The header field is used internally and  defines the outbound interface that should be used when sending a message to the destination. Setting the custom property to false avoids setting the header field when a request is sent over a loopback adapter.

 
[2] Add a new custom property to the first table in

https://www.ibm.com/support/knowledgecenter/SS7K4U_liberty/com.ibm.websphere.liberty.autogen.zos.doc/ae/rwlp_config_sipStack.html

Name | Type | Default | Description
-- | -- | -- | --
useLPFromOutbound | boolean | false |  On a multi-homed host, the custom property should be set to true to mandate the SIP Container to create a connection from the selected outbound interface. 
strictOutboundLocalPort | boolean | false | The custom property should be set to true to mandate the SIP Container to send a request from the SipProvider instance that is selected by the application using SipProvider.sendRequest(). By default, a request is sent using any provider.
cloneAckOn2xxRetransmission | boolean | false |  Indicates whether to clone an ACK request for 2xx retransmissions. By default, the same ACK instance is sent on every retransmission causing issues when the ACK request is modified by the next element upstream. When set to true, the original ACK request is cloned and the copy of the original request is sent on every retransmission.

**Comment by dmuelle** [comment]
Hi @annaguri , the page from KC you are referencing here, as well as its [corresponding page in the Open Liberty doc](https://www.openliberty.io/docs/21.0.0.2/reference/config/sipContainer.html), is autogenerated from the metatype files in the source code. These files are not manually updated by the ID team. However, the new properties shouyld be picked up by the build and automatically added to the generated doc, provided the code  in the [OpenLiberty/open-liberty repo](https://github.com/OpenLiberty/open-liberty) is properly documented.

**Comment by annaguri** [comment]
@dmuelle  thanks for the clarification. I'll take care of that.

**Comment by dmuelle** [comment]
You're welcome @annaguri! Closing this issue since it does not involve work from the docs team.
