### ISSUE TITLE
Add example for default DS on Database Connectivity feature page

### ISSUE THREAD

**Issue by sdaschner** [OpenLiberty/docs#369]
The example usages on the feature pages are helpful.

In order to improve the [Database Connectivity feature page](https://openliberty.io/docs/ref/feature/#jdbc-4.3.html), we should include the, from my experience, very usual case of defining and using a default datasource:

- simple datasource setup as default datasource, similar to `<dataSource id="DefaultDataSource" ...>`
- `EntityManager` used in the code, injected with `@PersistenceContext`

Happy to provide a PR if agreed.

**Comment by NottyCode** [comment]
Hi, We already have a link from the JPA page to the JDBC feature pages. You need to scroll down a long way to find it, but it is there. I think a more direct example on the jpa feature pages would be good though.

**Comment by dmuelle** [comment]
Example for configuring default data source will publish with 20.0.0.12:

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.12/reference/feature/jdbc-4.3.html#_configuration_of_the_default_data_source

tracked in #2867
