### ISSUE TITLE
Update "Kerberos authentication for JDBC data sources" topic to indicate Oracle kerberos limitation

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/docs#3703]
Update section https://www.openliberty.io/docs/21.0.0.2/kerberos-authentication-jdbc.html#_kerberos_configuration_for_jdbc_data_sources to indicate the following limitation:
From Oracle's documentation, the Oracle JDBC thin driver only supports the Oracle JDK or OpenJDK kerberos implementation.  It is not possible for the Oracle JDBC thin driver to authenticate via kerberos when using IBM Java 8.

**Comment by dmuelle** [comment]
Hi @frowe , when you have a chance, please review the update on draft:
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/kerberos-authentication-jdbc.html#_kerberos_configuration_for_jdbc_data_sources

a couple questions-
- your comment above mentions "From Oracle's documentation..." but I couldn't seem to find anything that specifically mentioned krb5 and the thin driver w/r/t supported JDKs. I'd like to provide a link to their doc if there is a particular source for this info- can you recommend anything?
- In this context, does the "Oracle thin driver" refer to the client-side or server-side think driver? or both?
- "IBM Java 8" is not a recognized product name. I think it refers to "[the IBM SDK, Java Technology Edition, Version 8.](https://www.ibm.com/support/knowledgecenter/SSYKE2_8.0.0/welcome/welcome_javasdk_version.html)". Is this correct?

Thanks!

**Comment by frowe** [comment]
@dmuelle I get a 404 when I click on that link.
To your questions:
1) this info can only be found in an OTN (Oracle Tech Network) doc, you could post the link to it, but the way OTN works is very cheesy.  You can see the question, but to see the answer you must have an OTN login which requires a typical Oracle click-thru license which I don't think we want to promote.
2) it refers to the client-side/JDBC driver.  It is what Oracle calls their standard JDBC driver, the terminology should be familiar to Oracle users 
3) you're correct, that's the terminology for today :)

**Comment by dmuelle** [comment]
Thanks @frowe - sorry about the 404, it's an unfortunate side effect of the build process that the draft site goes offline for a few minutes before each refresh. Here's an alternate URL that should be more frequently available:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/kerberos-authentication-jdbc.html#_kerberos_configuration_for_jdbc_data_sources

The update is just the final sentence in the linked section. If it looks ok, you can add the `technical reviewed` label to this issue to sign off. If any further updates are needed, just let me know. Thanks

**Comment by frowe** [comment]
Looks good to me.

**Comment by dmuelle** [comment]
change pushed to vNext
