### ISSUE TITLE
Add histogram information to metrics topic

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#3729]
When reviewing https://github.com/OpenLiberty/docs/issues/3277#issuecomment-786148627, David identified that we need to add information about histogram to https://openliberty.io/docs/latest/microservice-observability-metrics.html. I think just a new section in the doc for the histogram metric that's similar to the other sections will make the topic more complete. Note that there isn't an annotation for histogram, so that should be made explicit, since the other sections focus on using annotations for metrics.

**Comment by dmuelle** [comment]
doc is published
