### ISSUE TITLE
Documentation needed - supported JAXRS Client properties 

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/docs#374]
Related to https://github.com/OpenLiberty/open-liberty/issues/8032, we do not have documentation for all of our supported JAXRS client properties.

I am leaving https://github.com/OpenLiberty/open-liberty/issues/8032 open since there may need to be a new property added to wrap the CXF `http.redirect.relative.uri` property.

**Comment by NottyCode** [comment]
Closing since I moved #8032 to this repo as #375
