### ISSUE TITLE
Spring feature and Liberty Security are not integrated

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#3763]
Per discussion with Tom, Anjum, Ajay, Ut, opened this issue.  

In our recent support work, we found that when SpringBoot feature is enabled, Liberty security feature may not work. 
We would like to have it documented so we can just point to it. 

Thomas & Anjum's team will be able to help with the contents. Please reach out to them when doc team is ready. 

Thank you. 

Please find details here. 
https://ibm.box.com/s/tfvlzktmhbvvnanecambqms1h8obx5ho

**Comment by dmuelle** [comment]
@anjumfatima90 @una-tapa Hi- are there any further details availalble for this issue to document the problem with the spring feature and appSecurity? If someone can add details to this issue we can prioritize it and get the fix published. Thanks!

**Comment by anjumfatima90** [comment]
Hi,

We can add a paragraph at the end of this [page](https://www.ibm.com/docs/en/was-liberty/nd?topic=architecture-spring-boot-programming-model-support). The paragraph would like below

Liberty support for Spring Boot is integrated with support for web containers using features like servlet-3.1, servlet-4.0, jsp-2.3. Other features like ssl-1.0 or websocket-1.0/websocket-1.1 should be enabled if https or websocket support is needed. All other server configuration is handled by spring boot application properties. For example, security properties can be set using spring.security.* application properties. The Spring Boot Liberty features (springBoot-1.5 and springBoot-2.0) do not integrate with the functionality provided by other Liberty features, such as appSecurity-2.0 and jaxrs-2.1.  If an application needs additional functionality then the Spring Boot project provides a number of Spring Boot starters that can be included in the application.  For example, spring-boot-starter-security or other third party starters like cxf-spring-boot-starter-jaxrs. Including such Spring Boot starters in the application will allow the application to use technologies provided by the Spring Boot starter instead.

**Comment by dmuelle** [comment]
@anjumfatima90 yes I can add a statement to that page- since it is in IBM Docs for commercial (WebSphere) Liberty, I'll open an issue on [that backlog](https://github.ibm.com/websphere/liberty-docs/issues) to track it.

Is the same information equally applicable/important for Open Liberty users? If so, we could add a similar statement to the [Spring Boot feature page in the Open Liberty docs](https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.6/reference/feature/springBoot-2.0.html). Would the same statement work there?

**Comment by dmuelle** [comment]
WebSphere Liberty docs issue: https://github.ibm.com/websphere/liberty-docs/issues/2343

**Comment by dmuelle** [comment]
statement added to the [Spring Boot feature page](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/springBoot-2.0.html). Text approved in https://github.ibm.com/websphere/liberty-docs/issues/2343. Update will publish with 21.0.0.6, closing this issue
