### ISSUE TITLE
RequestTiming-1.0 doc update for LG-293: Add ability for requestTiming hungRequest detection to not collect javacores

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/docs#3764]
There is a new RequestTiming-1.0 feature documentation draft that is being written for openliberty.io, that is being covered in issue https://github.com/OpenLiberty/docs/issues/1094.

The above draft should be updated to include the updates made by this new feature LG-294 (https://github.com/OpenLiberty/open-liberty/issues/13694).

**OL Blog :** https://openliberty.io/blog/2021/02/19/mpcontextpropagation-requesttiming-21003-beta.html

This feature introduces a new boolean Request Timing server configuration attribute called `enableThreadDumps`, where you can now control whether the Request Timing feature collects thread dumps dumps or not when a hung request is detected. By simply configuring the NEW `enableThreadDumps` Request Timing server configuration attribute, to false, thread dumps will not be created during hung requests. Thread dumps will be created, by default, if the new server configuration attribute is set to true or not specified at all.

The new Request Timing server configuration attribute can be configured in your server.xml as follows:

`<requestTiming includeContextInfo="true" slowRequestThreshold="120s" hungRequestThreshold="10s" sampleRate="1" enableThreadDumps="false"></requestTiming>`

The `enableThreadDumps` server configuration attribute can also be used in embedded Request Timing sub-elements:
`<servletTiming/>` or `<jdbcTiming/>`, as follows:

`<requestTiming includeContextInfo="true" slowRequestThreshold="120s" hungRequestThreshold="10s" sampleRate="1">
        <servletTiming appName="MyApp" servletName="MyServletApp" slowRequestThreshold="100s" hungRequestThreshold="5s" enableThreadDumps="false"/>
    </requestTiming>`

Note: An embedded `<servletTiming/>` or `<jdbcTiming/>` element's configuration attributes in the server.xml file overrides the configured attributes that are defined in `<requestTiming/>`.

Also, whenever hung requests are detected, the thread dump files that get created are named differently, based on the Java being used. I suggest adding the following snippet, as the description for the new server configuration attribute:
**enableThreadDumps:** 
`Indicates whether thread dumps will be created if a hung request is detected. A thread stack of the particular thread exceeding the threshold is always produced as part of the hung thread warning in messages.log; however, thread dumps are additional diagnostics showing details of all threads in the process at the time. For OpenJ9 and IBM Java, these are called Java Dumps and are each written to a unique javacore.txt file (e.g. into the current working directory of the process). For HotSpot Java, these are each text snippets appended to stdout (e.g. console.log). Thread dumps may be useful to investigate a broader range of issues such as lock contention, deadlocks, etc. They are generally lightweight (e.g. up to a few hundred milliseconds); although, by default, both JVMs do not bound their disk usage (as compared to messages.log), so extra configuration (e.g. -Xdump) or additional care must be taken to avoid disk exhaustion with many hung threads.`

**Comment by chirp1** [comment]
Reviewed, discussed with Richard. Richard has the info needed to do the documentation for the LG-293 feature. Approving the feature.

**Comment by Rwalls1** [comment]
The updates related to the feature config example have been completed in issue #1094, update to server configuration attribute description will be completed with issue #4053 for 21.0.0.5.
