### ISSUE TITLE
Update KC Liberty Features List

### ISSUE THREAD

**Issue by scottcurtis2605** [OpenLiberty/docs#3767]
The following list of [Liberty features on the Knowledge Centre](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_feat.html) is outdated. This does not provide a comprehensive list of the available features in Liberty as of March 2021. This should be updated.

**Comment by dmuelle** [comment]
talked with Scott via slack- The mpOpenAPI-1.1 feature is missing from the features table. I'll add the feature to the table and run a full check of the features list to make sure no others are missing.

**Comment by dmuelle** [comment]
actually just realized this was on the Open Liberty repo, closing it and re-opening on the Websphere Liberty docs repo.

https://github.ibm.com/websphere/liberty-docs/issues/2239
