### ISSUE TITLE
Add new JAX-RS config examples for MP 4.0

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/docs#3775]
SME: Andy McCright
Suggested updates from issue #3511:

# Content proposal for new [JAX-RS config examples](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html)
The following suggested updates are drawn from steps 6 and 7 from the [Configuring the MicroProfile JSON Web Token topic](https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/twlp_sec_json.html):
## Access security details with a context object
In Jax-RS applications, you can use annotations to access information from HTTP requests with dependency injections of context objects. Context objects are used to access any information that is associated with the application. In the following example, the `@Context` annotation injects the `SecurityContext` context object that provides access to security details:
```java
@GET
@Path("/getGroups")
public Set<String> getGroups(@Context SecurityContext sec) {
       Set<String> groups = null;
       Principal user = sec.getUserPrincipal();
       if (user instanceof JsonWebToken) {
                JsonWebToken jwt = (JsonWebToken) user;
                groups= = jwt.getGroups();
       }
       return groups;
}
```
To access security details, the `SecurityContext` context object uses the `sec.getUserPrincipal()` method that determines the identity of the user that makes the HTTP request. The `if` statement specifies the `JSONWebToken` claims that identify the user.

## Inject the MicroProfile JWT interface
You can inject interfaces in JAX-RS applications to access resources. In the following example, the `@Inject` annotation injects the `JsonWebToken` interface to obtain the `jwtPrincipal` object that contains details that identify the user:
```java
@RequestScoped
public class JwtEndpoint {
       @Inject
       private JsonWebToken jwtPrincipal;
       @GET
       @Path("/getInjectedPrincipal")
       public String getInjectedJWT() {
          return  this.jwtPrincipal.getName();
       }
}
```

**Comment by Rwalls1** [comment]
Comments from @andymc12:
@Rwalls1 - thanks - this looks good.  Just a few minor comments:


> In Jax-RS applications, you can use annotations to access 

"Jax-RS" should be "JAX-RS".


> Context objects are used to access any information that is associated with the application.

Context objects go beyond just the application so maybe this sentence could say something like:
_Context objects can provide information associated the application, the specific request or response, or the environment that the application is operating in._


The source code for the `getGroups` method is technically correct, however, I have been advising users not to put `@Context` objects in as method parameters. This is because a future version of JAX-RS will replace the `@Context` annotation with `@Inject` and the `@Inject` annotation does not apply to method parameters. So it might make less work in the future to change this code to be:
```
@Context
SecurityContext sec

@GET
@Path("/getGroups")
public Set<String> getGroups() {
       Set<String> groups = null;
       Principal user = sec.getUserPrincipal();
       if (user instanceof JsonWebToken) {
                JsonWebToken jwt = (JsonWebToken) user;
                groups= = jwt.getGroups();
       }
       return groups;
}
```

> The if statement specifies the JSONWebToken claims that identify the user.

"JSONWebToken" should be "JsonWebToken".



As for your questions...
> For the Inject the MicroProfile JWT interface example, I wasn't sure what the phrase "through Raw Type, ClaimValue, javax.inject.Provider, and JSON-P types" from step 7 meant so I just highlighted the injection of the JWT interface.

I'm not entirely sure what that means either... It looks like `ClaimValue` is part of the MP JWT APIs.  I'm not sure what "Raw Type" means in this context... presumably that you can directly inject a `JsonWebToken`.  I don't think it is necessary to mention the `javax.inject.Provider` as that is just another way to inject using CDI.  And I'm not sure how JSON-P relates to injection in this case.  So, I agree with just highlighting the injection of the JWT interface and calling it good.  Teddy or somebody from the security team may have more info.

> Also, can you review step 8? Do you think the information in that step is important? If so, can you provide an example of what that content would look like?

I don't think it is necessary to document, but Teddy or somebody from the security team may have a different opinion.  My preference would be to keep it simple, so I would leave it out.

Thanks again!

**Comment by Rwalls1** [comment]
#3794

**Comment by Rwalls1** [comment]
@andymc12 Please review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html

**Comment by andymc12** [comment]
@Rwalls1 - this looks good.  Thanks so much!

**Comment by dmuelle** [comment]
## Content review

Theses examples look good, just a few comments. 

- I think both examples need to specify where this code is, generally at least. Since (i think), it's application code, need to be clear about that since most of our config examples are server code
### Access security details with a context object
 "In the following example, the @Context annotation injects the SecurityContext context object that provides access to security details:"
 Can you be a bit more specific than "security details"? Maybe "provides access to security details, such as the identity of the user that made the HTTP call" _If_ that's correct. What specific details would you expect to obtain from the example? Why would someone implement the code?
 
 ### Inject the MicroProfile JWT interface
 I think the title for this example could be more user focused, rather than feature focused. What is the benefit of injecting the MpJWT? The title should reflect why someone would want to do it.  Maybe even something like "Obtain details about a user by injecting the MicroProfile JWT interface."
 
"You can inject interfaces in JAX-RS applications to access resources such as user details"
I think this could be more specific to the example, maybe something like
You can inject interfaces in JAX-RS applications to access details about a user, such as...
or 
You can inject interfaces in JAX-RS applications to determine a user's identity and ...

also, I think we need a link of some kind from the MP-JWT feature examples to these and vice versa

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html

I think we should address interlinking in a separate issue as that may be something we should revisit across each of the feature pages in alignment with the planned revisions to the autogen descriptions.

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html

I think we should address interlinking in a separate issue as that may be something we should revisit across each of the feature pages in alignment with the planned revisions to the autogen descriptions.

**Comment by dmuelle** [comment]
Looks good- one more question for "Inject the MicroProfile JWT interface to access application resources". Only the title references MpJWT, it's not mentioned in the description or evident in the code example. Can you clarify in the description that the JsonWebToken interface is part of the the MPJWT API? If that's correct...

**Comment by Rwalls1** [comment]
@dmuelle Please review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrsClient-2.1.html

**Comment by Rwalls1** [comment]
@dmuelle Thanks, I've addressed your latest feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html

**Comment by dmuelle** [comment]
LGTM, signing off

@ManasiGandhi this is ready for peer review

**Comment by ManasiGandhi** [comment]
# Peer review

## Examples

- Add a sentence or two between “Examples” and “Access security details with a context object”

## Access security details with a context object

- “In JAX-RS applications, you can use annotations to access information from HTTP requests with dependency injections of context objects.” Can you change it to “In JAX-RS applications, you can use annotations with dependency injections of context objects to access information from HTTP requests” , for clarity.

- In, “In the following example, the @Context annotation injects the `SecurityContext` context object in the Java API that provides access to security details, such as user credentials” can “`SecurityContext`  object” work instead?

- Same here, “To access security details, the `SecurityContext` context object uses the `sec.getUserPrincipal()` method that determines the identity of the user that makes the HTTP request.”

## Inject the MicroProfile JWT interface to access application resources

- “MicroProfile JWT that identify the user:” change to “MicroProfile JWT that identifies the user”

**Comment by Rwalls1** [comment]
@ManasiGandhi Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.3/reference/feature/jaxrs-2.1.html

We've previously discussed adding descriptions before each set of examples on the feature pages and Karen indicated that it wasn't necessary. I think if we do decide to add descriptions we should open a separate issue to add descriptions to each feature page to maintain consistency. Also, I think it would be best to state the phrase as, "`SecurityContext` context object". It may sound a bit awkward but I think it works to ensure clarity.

**Comment by ManasiGandhi** [comment]
@Rwalls1 The changes looks good to me.

**Comment by Rwalls1** [comment]
These updates have been merged to vnext and will publish in the upcoming release.
