### ISSUE TITLE
Add %D and %{R}W to NCSA Logging Examples

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/docs#3782]
The [HTTP access logging page](https://openliberty.io/docs/latest/access-logging.html) does not use `%D` nor `%{R}W` in its examples. These are low-overhead and invaluable in figuring out response time issues. The former provides the total response time of each request. The latter provides the service time which can help isolate whether a response time issue is within Liberty or in the network/client.

**Comment by kgibm** [comment]
@mrsaldana Hey Manuel, can you please review this doc change? This is adding `%D` and `%{R}W` to the HTTP access logging examples. Here are the draft updates: https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.3/access-logging.html

Here is a test:

```
$ docker run --rm openliberty/open-liberty:full-java8-ibmjava-ubi sh -c "curl https://raw.githubusercontent.com/kgibm/samplewar/main/samplewar.war -so /config/dropins/sample.war && echo '<?xml version=\"1.0\" encoding=\"UTF-8\"?><server><httpEndpoint id=\"defaultHttpEndpoint\" host=\"*\" httpPort=\"9080\" httpsPort=\"9443\"><accessLogging filepath=\"\${server.output.dir}/logs/access.log\" logFormat=\"%h %u %t &quot;%r&quot; %s %b %D %{R}W\" /></httpEndpoint></server>' > /config/configDropins/overrides/server.xml && (/opt/ol/wlp/bin/server run defaultServer &) && sleep 2 && tail -99999f /logs/messages.log | grep -q CWWKF0011I && curl -sv --trace-time http://localhost:9080/sample/servlet && cat /opt/ol/wlp/output/defaultServer/logs/access.log && /opt/ol/wlp/bin/server stop defaultServer"
[...]
127.0.0.1 - [09/Mar/2021:20:23:05 +0000] "GET /sample/hello HTTP/1.1" 200 311 81140 76313
```

**Comment by dmuelle** [comment]
changes went to vNExt with #3803 , will publish with 21.0.0.3.
