### ISSUE TITLE
KRB5: Troubleshooting for Ldap Kerberos

### ISSUE THREAD

**Issue by kristip17** [OpenLiberty/docs#3807]
This is a follow up to #3571

Target 20.0.0.5, but 20.0.0.6 is fine. Not sure if this should be a new page, or added onto the LdapRegistry page.

## Users fail to login even if non-Kerberos enabled registries are available

All registries (Basic, Ldap, Custom) are federated and must be searched to confirm the user logging is unique. 
If the `allowOpIfRepoDown` attribute is not enabled, the application server must be able to successfully search for the user in all participating registries to verify the user is unique to one repository. If a Kerberos enabled LDAP server in a federated repository uses a Kerberos ticket cache to hold the credential and the credential expired, a failure results when searching on the LDAP registry. To resolve the problem, refresh the credential. Set the `allowOpIfRepoDown` attribute to `true` on the `federatedRepository ` element.

Example:
```
<federatedRepository>
        <primaryRealm name="FederatedRealm" allowOpIfRepoDown="true">
            <participatingBaseEntry name="o=SampleBasicRealm"/>
            <participatingBaseEntry name="o=ibm,c=us"/>
        </primaryRealm>
   </federatedRepository>
```

## Using a krb5TicketCache, but the failure indicates the principal was not found in keytab

If a `krb5TicketCache` file is defined for an LdapRegistry, the ticket cache is checked first. If the global `Kerberos` configuration is defined with a `keytab` file attribute defined, it was be checked next if the user is not found in the ticket cache. The `Kerberos` element is global and shared with all features using Kerberos authentication.

## Slow performance with Kerberos

If the LdapRegistry uses a `krb5TicketCache` file to store the Kerberos credentials, the Kerberos service tries to renew credentials before they expire. If the credentials are expired, this could cause a login failure for all users. If the credentials are expired, but `allowOpIfRepoDown` is enabled on the `federatedRepository` element, the failure is ignored, but could impact the performance. Storing credentials using a keytab file (see the `Kerberos` element) is an alternate way to do Kerberos authentication.

**Comment by kristip17** [comment]
@dmuelle  -- this can be reviewed and prioritized. I might have some more ideas, but we can add them on as bug updates, etc.

**Comment by dmuelle** [comment]
Hi Krisiti- whenever you have a moment- I'm working on the troubleshooting page for LDAP krB5 and I have a couple questions
## Users fail to login even if non-Kerberos enabled registries are available. 
We've already documented this in the federated user registry feature config. It's ok to dupl;cate if we expect that people will have problems, but just checking to make sure.

## Using a krb5TicketCache, but the failure indicates the principal was not found in keytab
I'm not sure what we're telling people to do with this one. We have already documented that the keytab file in the  kereberos element is an alternative to krb5TicketCache. I can't tell from the text in the issue what additonal info we're telling here. Is it that someone might see an error message re "keytab" bu they configured a ccache and don't understand why message says keytab? If so, can we reproduce the message text in this item?

## Slow performance with Kerberos
I understand this is telling people that enabling allowOpIfRepoDown could slow down krb5 auth. It says using the global keytab is an alternative, but why would that help? Wouldn't the fed repository config be the same regardless of whether the credentials were in ccache or keytab? or would we expect less performance degradation because keytab deosnt try to auto renew? Or is it because keytab file credentials don't expire?

For the time being, these items will go on their own page, but the plan is to move them to a larger Security troubleshooting page soon.

**Comment by kristip17** [comment]
_We've already documented this in the federate_
I wanted to point out the expiring ticketCache issue -- it tripped us up during tWAS dev of this feature quite a bit when the UI team was testing and would get locked out of the console. We could integrate it into the Fed Repo config page instead of that would be better.

_Is it that someone might see an error message re "keytab" bu they configured a ccache and don't understand why message says keytab?_
Yes, that was my thinking
 _If so, can we reproduce the message text in this item?_
I'll get an example message

_or would we expect less performance degradation because keytab deosnt try to auto renew?_ Yes -- the keytab doesn't expire and therefore doesn't need to autorenew.

**Comment by dmuelle** [comment]
Hi @kristip17, here's the troubleshooting draft:

https://draft-openlibertyio.mybluemix.net/docs/latest/troubleshooting-krb5-ldap.html

I think we just need to incorporate an example error message into the second item, and add some text to explain it. If you see anything else that needs a fix or m ore info, just let me know. Thanks!

**Comment by kristip17** [comment]
We can remove this section `Using a krb5TicketCache, but the failure indicates the principal was not found in keytab`

Add a new section related to expiring credentials in the ticket cache.

**The Kerberos principal name is not in the Kerberos ticket cache file**
If the Kerberos principal name is not in the Kerberos ticket cache file, the product logs the CWIML type message. A missing Kerberos principal name can occur for the following reasons:
- A credential that was not generated for the Kerberos principal name, causing an incorrect Kerberos configuration.
- An expired credential in the Kerberos ticket cache.

In either case, refresh the Kerberos ticket cache to resolve the problem.

Depending on the type of JDK, the message that you can receive is similar to one of the following examples:

CWIML4507E: Kerberos login failed with the user1@SAMPLE.COM Kerberos principal and the C:\krb5\krb5-user1.cc Kerberos credential cache (ccache). javax.security.auth.login.LoginException: Unable to obtain password from user

CWIML4520E: The LDAP operation could not be completed. The LDAP naming exception javax.naming.AuthenticationException: GSSAPI [Root exception is javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Ticket expired (32))]] occurred during processing.

CWIML4520E: The LDAP operation could not be completed. The LDAP naming exception javax.naming.NamingException: CWIML4507E: Kerberos login failed with the user1@SAMPLE.COM Kerberos principal and the C:\krb5\krb5-user1.cc Kerberos credential cache (ccache). javax.security.auth.login.LoginException: Unable to obtain password from user

To review the expiration time of the Kerberos principal user, run the Java klist tool.

**Comment by dmuelle** [comment]
Hi Krisiti, the updated draft is ready for review: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.5/troubleshooting-krb5-ldap.html

**Comment by ManasiGandhi** [comment]
@dmuelle The topic looks good! A few edit suggestions
# Content review
## Troubleshooting Kerberos authentication to LDAP servers

- [x] Change, “The following information can help determine the cause of common problems and error messages that are associated with Kerberos authentication to LDAP servers.”, to, “The following information can help determine the causes of common problems and error messages that are associated with Kerberos authentication to LDAP servers.” As there are multiple possible causes.
## Users cannot log in, even if non-Kerberos enabled registries are available.

- [x] Change,“If multiple user registries are configured for an Open Liberty server, all basic, custom, and LDAP user registries are federated into a single federated user registry.”, to “If multiple user registries are configured for an Open Liberty server, all basic, custom, and LDAP user registries are combine into a single federated user registry.” To avoid repetition.
- [x] Change, “By default, the server must be able to successfully search for the user in all participating user registries to verify that the user is unique within the federated user registry.”, to, “ By default, the server must successfully search for the user in all participating user registries to verify that the user is unique within the federated user registry.”, for conciseness.
- [x] “To avoid failures if any user registry is unavailable”, to possibly , “To avoid failures if a user registry is unavailable”
## Performance is slow when Kerberos is configured for a federated user registry.

- [x] “To avoid this problem, you can specify Kerberos credentials in a keytab file with the kerberos element.”, could you begin this sentence in a new paragraph to refer to the solution to the problem.
## The Kerberos principal name is not in the Kerberos ticket cache file.

- [x] “If the Kerberos principal name is not in the Kerberos ticket cache file,”, do you mean “If the Kerberos principal name is not found in the Kerberos ticket cache file,”? If so, up date as appropriate.
- [x] “An expired credential is in the Kerberos ticket cache.”, would it be more accurate to say, “The Kerberos ticket cache contains an expired credential.”?

**Comment by dmuelle** [comment]
Thanks for reviewing @ManasiGandhi - I've updated the topic per your suggestions:
 https://draft-openlibertyio.mybluemix.net/docs/latest/troubleshooting-krb5-ldap.html

**Comment by Rwalls1** [comment]
# Peer review
The doc looks good, I just have a couple comments:
Global comment: I think you should change instances of “refresh” to “renew” to maintain consistency with how the action is referenced on the Java kinit tool reference page that is linked to.
## Users cannot log in, even if non-Kerberos enabled registries are available
After the phrase," set the allowOpIfRepoDown attribute to true on the primaryRealm subelement of the federatedRepository element”, I think you should specify the location where this configuration happens, such as a `server.xml` file.

**Comment by dmuelle** [comment]
Thanks for reviewing @Rwalls1 - I made both these changes:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.5/troubleshooting-krb5-ldap.html

**Comment by dmuelle** [comment]
doc is published w/ 21005
