### ISSUE TITLE
Broken links in Slow and hung request detection

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#3877]
https://openliberty.io/docs/21.0.0.2/slow-hung-request-detection.html

Slow and hung request detection

The request timing links in the following paragraphs are broken.

The Request Timing feature identifies requests that run longer than a slow request threshold. The Request Timing feature documents slow and hung requests as they occur, so you don’t need to re-create the problem to collect more data. In addition to the global settings for slow and hung request thresholds, you can set thresholds for specific servlets or JDBC requests. For more information, see the Request Timing feature.

They point to https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#requestTiming-1.0.html and got the following back.

```
404 Not Found: Requested route ('draft-openlibertyio.mybluemix.net') does not exist.
```

**Comment by Rwalls1** [comment]
I've confirmed that the feature links referenced above are working. This issue was probably caused by the draft site going down while the content was being rebuilt, which causes the `404 Not Found` message to display.

**Comment by fmhwong** [comment]
@rwalls1 Are the links supposed to point to the draft server?  Will this be the official version?

https://openliberty.io/docs/21.0.0.3/reference/feature/requestTiming-1.0.html
