### ISSUE TITLE
HTTP access logging

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#388]
Create a reference topic in OL docs containing the information from this KC topic: https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_http_accesslogs.html

Do not include the last section (Writing HTTP access log to console or message log using JSON format).

Tidy up the topic as necessary (style, formatting, add additional explanation if necessary). Please don't format the 'Note' as a separate callout/note; it should just be a paragraph/sentence in the topic.

**Comment by dmuelle** [comment]
Hi @lauracowen 

Draft of this topic is now up at

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#access-logging.html

In one instance I was able to replace a link to Liberty KC with the equivalent page on Open Liberty. there two other links that I could not find an analog for- one to IBM Apache config doc and the other to WAS KC access channel properties- are there sources in OL that either of these should point to?

**Comment by lauracowen** [comment]
Thanks

- Can you check the httpAccessLogging link works - it looks like it should go to the generated config docs but it's currently broken (that may just be that the staging server isn't up-to-date with the generated docs - I'm not sure).
- The Apache link - I think we should link to the version on the Apache domain. The one I found googling is v2.4 rather than the v2.2 that IBM hosts. I don't know how important that is - maybe pointing at v2.4 is better. See what you think.
- is the syntax highlighting enabled in the asciidoc? The XML snippets looks a bit black like there should be highlighting but isn't...
- "HTTP access log format" section: I think the purpose of the link here is to get a definitive list of all the characters that you can use to indicate the log format.
+
I don't know much of the detail about logging config so I can't help from a technical perspective here but I'm just looking at the reference to `httpAccessLogging` and `accesslogging`. The first exists in the OL server config doc (https://www.openliberty.io/docs/ref/config/#httpAccessLogging.html) but the second doesn't. I'm not sure why. Let's assume that's intentional for now but ask your tech reviewer to confirm.
+
I'm inclined to say to just take the list of options and their descriptions and stick them in a table in this new OL topic for now (without the explanation around that's around the table in the current KC topic). Remove the sentence "For a list of the available log format properties..." from your OL topic. Then get the whole thing reviewed and check that all of those options are relevant to the HTTP access log format section in your topic. I *think* the reason that the section refers to the KC topic is simply to refer to the list of valid characters that can be used to define the log format. It may be that we need to later break that list out into a separate topic but as no other OL topic refers to it at the moment, I think it's fine to just put it in this topic. You could create a separate file containing just the table and then include it as an 'include' in the OL topic (that way, it's already broken out and can be included in other topics if necessary later).

We may need Alasdair to review this (as he requested this particular topic and may have something specific in mind) but you could try @wtlucy or @ebreijo in the meantime for technical accuracy.

**Comment by dmuelle** [comment]
Hi @lauracowen - this doc has been updated

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#access-logging.html

- `Can you check the httpAccessLogging link works` Fixed
- `The Apache link - I think we should link to the version on the Apache domain.`  Agreed- there was an end of life notice for 2.2 on the Apache page. I've updated the link to point to http://httpd.apache.org/docs/current/mod/mod_log_config.html
- `is the syntax highlighting enabled in the asciidoc? The XML snippets looks a bit black like there should be highlighting but isn't...` Fixed
- `HTTP access log format" section` I transferred the table from the KC page to this one. I'll work on getting tech review but see what you think re layout, content order. One thing I want to check- there are some log format options listed on the OL server config page but this table includes a number of options not listed there so want to be sure they apply to OL. Also one of the properties- 

`%u | Remote user according to the WebSphere Application Server-specific $WSRU header.`

is WAS specific so want to be sure its relevant to OL users.

**Comment by dmuelle** [comment]
I've also made changes to reflect the tech review I got from Bill, which included removing the link to Apache Module mod_log_config as it doesn't make sense here.

**Comment by lauracowen** [comment]
Cool, thanks. I like the table. We shouldn't mention WebSphere in OL docs so when Bill gets back about exactly what is/isn't relevant to OL, decide whether that row should be removed or reworded.

"OL server config page" - where do you mean?

**Comment by dmuelle** [comment]
OL server config for httpAccessLogging- https://www.openliberty.io/docs/ref/config/#httpAccessLogging.html

There is a table row there for log formats but its more example than exhaustive.

I had asked Bill about the Websphere format and he said `$WSRU` is still used in OL- but i can remove it if we don't need to document it here. Not sure we can reword it since it is specifically for Websphere. 

Bill and Manuel Saldana reviewed the doc and said they both thought everything looked good.

**Comment by dmuelle** [comment]
This doc is now live at 

https://www.openliberty.io/docs/ref/general/#access-logging.html

closing this issue...
