### ISSUE TITLE
java.util.logging.Logger

### ISSUE THREAD

**Issue by JeeSteveM** [OpenLiberty/docs#3881]
In the LO documentation it states the java.util.logging.Logger should work

"Logging data that is written by applications by using the System.out, System.err, or java.util.logging.Logger streams is combined into the server logs."

however I cannot get this to work, and have to use System.out's what am I missing? I prefer the logger.

**Comment by donbourne** [comment]
It's possible the root Logger's Handlers that OL relies on have been removed/replaced.  Try running the `bin/server dump` command on your server that is having problems logging and again on a fresh Liberty server.  Compare the LoggingIntrospector's list of Handlers from the two generated dumps.  

One thing that can alter the list of Handlers is SLF4J's `SLF4JBridgeHandler.resetHandlersForRootLogger()` method.
