### ISSUE TITLE
update links in external-configuration.adoc

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#3886]
links in the default configuration table [external-configuration.adoc](https://github.com/OpenLiberty/docs/blob/vNext/modules/ROOT/pages/external-configuration.adoc) need to be updated to be relative links instead of absolute URLs that link to 21.0.0.2

**Comment by dmuelle** [comment]
Additionally, need to make edits to address @Joseph-Cass [comment in #3443](https://github.com/OpenLiberty/docs/issues/3443#issuecomment-806516760):

> All META-INF/microprofile-config.properties properties

 These are files, not properties, so should probably be:

> All META-INF/microprofile-config.properties files

**Comment by ManasiGandhi** [comment]
Changes sent to vNext in #4043
