### ISSUE TITLE
Add new Admin Rest Connector feature config examples

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/docs#3958]
SME: Fred Rowe
Proposed updates related to issue #1558

**Comment by Rwalls1** [comment]
@frowe Please review: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/restConnector-2.0.html

**Comment by frowe** [comment]
I wouldn't repeat examples of config listing and validation in this feature overview, the samples and explanations are too terse to useful.  I'd point out the rest connector, among other things, can be used for this and refer to the other doc.  If retained, the paragraphs below the first and second server.xml sample will need to be edited, let me know.

**Comment by Rwalls1** [comment]
@frowe Thanks, if the examples are not valuable and would be better used in the manner that you described, I think it's best to not create these examples and close this issue.
