### ISSUE TITLE
Updates server command topics about config variables (Doc APSFOUND-54)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#409]
See https://github.ibm.com/was-liberty/liberty-docs/issues/1133

Specifically, @NottyCode said:

"most of this is covered in the [serverConfiguration.adoc](https://openliberty.io/docs/ref/config/serverConfiguration.html) already. The point about command line provided variables is not. I'm not clear on whether it should go in serverConfiguration or server commands doc, or possibly both. I think we need to mention variables on startup in the resolution order in the config override. However I don't think that is where we should describe how to set them. I think we should do that in the [command documentation](https://openliberty.io/docs/ref/command/)."

**Comment by Charlotte-Holt** [comment]
@brenthdaniel @NottyCode I made updates in the options tables of the following command documentation:
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-run.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-start.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-debug.html

I also added the bit about the runnable JAR files to the server config overview under variable substitution: 
- https://draft-openlibertyio.mybluemix.net/docs/ref/config/

Please comment with your approval if this is okay to close, or let me know if additional updates are required.

**Comment by brenthdaniel** [comment]
Sorry I missed this in the review but I think there are additional changes needed.. Specifically, the format for specifying variables in the non-runnable jar case needs to be covered. 

I don't know where it fits on the server run/debug/start  command page (probably in the description for `--name=variable-value` ), but we need something about how `--` needs to be specified before `--name=variable-value`. For example, in the run/start/debug case, a command line would look like:
`server run server1 -- --variable1=value --variable2=value`

The same information needs to go in the variable substitution section next to the part about runnable jars.

**Comment by Charlotte-Holt** [comment]
Thanks, @brenthdaniel. I updated the server commands:
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-run.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-start.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-debug.html

I also updated the **Variable substitution** section in the Server configuration overview:
- ttps://draft-openlibertyio.mybluemix.net/docs/ref/config/

And I moved the syntax portion about running from a JAR to the Runnable JAR files doc:
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#runnablejarfiles.html

**Comment by brenthdaniel** [comment]
Looks good, thanks

**Comment by Charlotte-Holt** [comment]
These changes are live at:
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-run.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-start.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-debug.html
- https://draft-openlibertyio.mybluemix.net/docs/ref/config/
- https://draft-openlibertyio.mybluemix.net/docs/ref/general/#runnablejarfiles.html
