### ISSUE TITLE
Update Metrics Reference List for 21.0.0.6 (21.0.0.5 beta)

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/docs#4112]
The document: https://openliberty.io/docs/21.0.0.4/metrics-list.html

Related to: 
LG-301 - https://github.com/OpenLiberty/open-liberty/issues/15781

Add to the table:
| MPMETRICS-3.X NAME | MPMETRICS-3.X PROMETHEUS NAME(S) | TYPE AND DESCRIPTION | FEATURE(S) REQUIRED | VERSION INTRODUCED|
| ------------- | ------------- | ------------- | ------------- | ------------- |
| requestTiming.activeRequestCount|  vendor_requestTiming_activeRequestCount | The number of servlet requests currently running. The metric is a Gauge. | [MiroProfile Metrics 2.x and up](https://openliberty.io/docs/latest/reference/feature/mpMetrics-3.0.html) and [Request Timing](https://openliberty.io/docs/21.0.0.4/reference/feature/requestTiming-1.0.html) | [mpMetrics-2.x and up ](https://openliberty.io/docs/ref/feature/#mpMetrics-3.0.html) | 
| requestTiming.requestCount| vendor_requestTiming_requestCount_total | The number of servlet requests since the server started. The metric is a Counter. | [MiroProfile Metrics 2.x and up](https://openliberty.io/docs/latest/reference/feature/mpMetrics-3.0.html) and [Request Timing](https://openliberty.io/docs/21.0.0.4/reference/feature/requestTiming-1.0.html) | [mpMetrics-2.x and up ](https://openliberty.io/docs/ref/feature/#mpMetrics-3.0.html) | 
|requestTiming.hungRequestCount|  vendor_requestTiming_hungRequestCount | The number of servlet requests that are currently running but are hung. The metric is a Gauge. | [MiroProfile Metrics 2.x and up](https://openliberty.io/docs/latest/reference/feature/mpMetrics-3.0.html) and [Request Timing](https://openliberty.io/docs/21.0.0.4/reference/feature/requestTiming-1.0.html) | [mpMetrics-2.x and up ](https://openliberty.io/docs/ref/feature/#mpMetrics-3.0.html) | 
|requestTiming.slowRequestCount|  vendor_requestTiming_slowRequestCount | The number of servlet requests that are currently running but are slow. The metric is a Gauge. | [MiroProfile Metrics 2.x and up](https://openliberty.io/docs/latest/reference/feature/mpMetrics-3.0.html) and [Request Timing](https://openliberty.io/docs/21.0.0.4/reference/feature/requestTiming-1.0.html) | [mpMetrics-2.x and up ](https://openliberty.io/docs/ref/feature/#mpMetrics-3.0.html) |

**Comment by dmuelle** [comment]
Hi @Channyboy - we generally don't doc beta-release stuff in the docs, just the beta blog post. If these metrics are targeted for GA with 21.0.0.6 we can have the doc update ready for that though

**Comment by dmuelle** [comment]
Hi @Channyboy the draft for these updates is ready for review;

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.6/metrics-list.html

The four new entries were added to the table in alphabetical order. Let me know if  any further edits are needed. If it looks good, you can add the `Developer reviewed` label to this issue. Thanks!

**Comment by dmuelle** [comment]
changes are merged to vNext and will publish with 21.0.0.6
