### ISSUE TITLE
Enable and run sipservlets on openliberty

### ISSUE THREAD

**Issue by chrisrmartineau** [OpenLiberty/docs#4152]
[guide-getting-started.zip](https://github.com/OpenLiberty/docs/files/6453299/guide-getting-started.zip)

.war file attached as requested

**Comment by annaguri** [comment]
I was able to reproduce the issue in my environment. I could not see what you have defined in `package-info` as the source is not available. 
Uploading a similar application that works fine in my local environment. 

[uas.zip](https://github.com/OpenLiberty/docs/files/6462280/uas.zip)

**Comment by chrisrmartineau** [comment]
Hi,

I have built your example directly into my environment and still get the same issue.

I still suspect that it is something to do with how the environment is set up.

There was no server.xml in the war file, do you have examples of the underlying config files for the openliberty server itself?

Thanks

Chris

**Comment by annaguri** [comment]
I believe it's related to the `war` file as I was able to reproduce the issue locally. 

Here's the `server.xml` file 
```
<?xml version="1.0" encoding="UTF-8"?>
<server description="new server">

    <featureManager>
        <feature>sipServlet-1.1</feature>
    </featureManager>

    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />

    <sipEndpoint host="*" sipTCPPort="5060" sipUDPPort="5060"/>

    <!-- Automatically expand WAR files and EAR files -->
    <applicationManager autoExpand="true"/>

    <!-- Default SSL configuration enables trust for default certificates from the Java runtime -->
    <ssl id="defaultSSLConfig" trustDefaultCerts="true" />

</server>
```

**Comment by chrisrmartineau** [comment]
Hi,

Okay, I created a new project and just put your code on its own there and it works.

So there must be something in the additional code I have that is causing it to have an issue.

I can build from there and will let you know when I find what specifically is causing the problem.

Thanks for your help.

Chris

**Comment by dmuelle** [comment]
closing this issue- if any more questions remain, feel free to reopen it or start another
