### ISSUE TITLE
Document exit codes for commands

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4216]
Return codes were documented in IBM Docs for f[eatureManager](https://www.ibm.com/docs/en/was-liberty/nd?topic=command-featuremanager),[ installUtility](https://www.ibm.com/docs/en/was-liberty/nd?topic=command-installutility), and other commands. Return codes are not documented in OL for any commands.

Based on recent dev feedback from [Gitter](https://gitter.im/OpenLiberty/developer-experience?at=60a20cf4233397424dc91c73) and [Slack discussion](https://ibm-cloud.slack.com/archives/C30NGGFH6/p1621260395059100), we need to document these codes for OL. 

SME: @bensonlatibm @jjiwooLim 
Will get back to us with a list of codes

**Comment by dmuelle** [comment]
Hi @bensonlatibm @jjiwooLim, per the slack discussion linked above, can you provide a list of return codes for Open Liberty commands? I'm hoping to document the codes with the 21.0.0.7 docs release if possible. Thanks!

**Comment by dmuelle** [comment]
I did find this list in IBM docs for the `server` command. I'm not sure if these codes apply to other commands or if each command has its own set of return codes. Also, in IBM docs, they are called "exit codes"- are exit codes and return codes the same thing? If so, we should use one term consistently

```
Exit codes
The following exit codes are available for the server command and the equivalent executable JAR file ws-server.jar:
0
OK. 0 indicates successful completion of the requested operation. For server status, 0 indicates that the server is running.
1
For server status, 1 indicates that the server is not running. For other operations, it indicates invocation of a redundant operation. For example, starting a started server or stopping a stopped server. This code might also be returned by JVM if invalid Java options are used.
2
The server does not exist.
3
An unsupported action was called on a running server. For example, the server is running when the package action is called.
4
An unsupported action was called on a stopped server. For example, the server is not running when the dump action is called.
5
Unknown server status. For example, the workarea directory is missing, or the Attach API fails to work.
>=20
Return codes greater than or equal to 20 indicates that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
```

**Comment by jjiwooLim** [comment]
### featureUtility Exit codes

**find:**

```
0 	The command successfully completed the requested operation.

20 	One or more arguments are not valid.

21 	A runtime exception occurred when connecting to a repository. 
```

**help:**

```
0 	The command successfully completed the requested operation.

20 	One or more arguments are not valid.
```


**installFeature:**

```
0 	The command successfully completed the requested operation.

20 	One or more arguments are not valid.

21 	A runtime exception occurred because of one or more of the following conditions:
		- A runtime exception occurred during the installation of the .esa subsystem archive file.
		- A license is not accepted or acknowledged.
		- The .esa subsystem archive file did not extract correctly.

22 	The feature to be installed exists.

23	The feature definition was not valid for one or more of the following reasons:
		- The feature does not have a valid manifest file.
		- The version of the feature is not supported in this Liberty environment.
		- The .zip or .jar file that contains the feature files does not exist.

24 	The .esa subsystem archive file is missing content.

25 	An IO exception occured during the installation of the .esa sussystem archive file.

29	The feature is not valid for the current product.
```


**installServerFeatures:**

```
0 	The command successfully completed the requested operation.

20 	One or more arguments are not valid.

21 	A runtime exception occurred because of one or more of the following conditions:
		- A runtime exception occurred during the installation of the .esa subsystem archive file.
		- A license is not accepted or acknowledged.
		- The .esa subsystem archive file did not extract correctly.

22 	The feature to be installed exists.

23	The feature definition was not valid for one or more of the following reasons:
		- The feature does not have a valid manifest file.
		- The version of the feature is not supported in this Liberty environment.
		- The .zip or .jar file that contains the feature files does not exist.

24 	The .esa subsystem archive file is missing content.

25 	An IO exception occured during the installation of the .esa sussystem archive file.

29	The feature is not valid for the current product.
```

**viewSettings:**

```
0 	The command successfully completed the requested operation.

20 	One or more arguments are not valid.

21     A runtime exception occurred when connecting to a repository. 
```

**Comment by jjiwooLim** [comment]
> I did find this list in IBM docs for the `server` command. I'm not sure if these codes apply to other commands or if each command has its own set of return codes. Also, in IBM docs, they are called "exit codes"- are exit codes and return codes the same thing? If so, we should use one term consistently
> 
> ```
> Exit codes
> The following exit codes are available for the server command and the equivalent executable JAR file ws-server.jar:
> 0
> OK. 0 indicates successful completion of the requested operation. For server status, 0 indicates that the server is running.
> 1
> For server status, 1 indicates that the server is not running. For other operations, it indicates invocation of a redundant operation. For example, starting a started server or stopping a stopped server. This code might also be returned by JVM if invalid Java options are used.
> 2
> The server does not exist.
> 3
> An unsupported action was called on a running server. For example, the server is running when the package action is called.
> 4
> An unsupported action was called on a stopped server. For example, the server is not running when the dump action is called.
> 5
> Unknown server status. For example, the workarea directory is missing, or the Attach API fails to work.
> >=20
> Return codes greater than or equal to 20 indicates that an error occurred while performing the request. Messages are printed and captured in log files with more information about the error.
> ```

They are the same thing

**Comment by dmuelle** [comment]
Thanks @jjiwooLim ! These codes will be added to the Open Liberty 21.0.0.6 docs release. I am also looking for return codes for the `securityUtility` commands. Do you have access to that info, or can you recommend anyone to contact who might?

**Comment by utle** [comment]
securityUtility exit code:    

- 0
Indicates successful completion of the requested operation.
- 1
Generic error.
- 2
The Server is not found.
- 3
The client  is not found.
- 4
The path can not be created.
- 5
The file already exists.

**Comment by dmuelle** [comment]
Thank you @utle - For exit code 1- generic error, can we provide any more information, such as an example of a generic error?

**Comment by utle** [comment]
Sample for exit code 1:
securityUtility createLTPAKeys
Error:  Missing argument --password

**Comment by dmuelle** [comment]
changes will publish with 21.0.0.7
