### ISSUE TITLE
Update "Health Checks for Microservices" document for MpHealth 3.1

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/docs#4327]
MP Health 3.1 Epic: https://github.com/OpenLiberty/open-liberty/issues/16626
OL Beta Blog: https://github.com/OpenLiberty/open-liberty/issues/17503

The "Health Checks for microservices" document (https://openliberty.io/docs/21.0.0.5/health-check-microservices.html) needs to be updated with the new updates from mpHealth-3.1.

- Add mentions of the new Startup health check introduced in MpHealth-3.1, which allows applications to define startup probes that are used for initial verification of the application before the Liveness probe takes over. This is useful for applications which require additional startup time on their first initialization.
- Add the new convenient `@Startup` annotation to create your own health check procedures to verify that your microservices have fully initialized.
- Add that the new Startup Health checks can also interact with the [Kubernetes Startup Probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes).
- Update the microservices-based banking application example, to include the use case for Startup health checks, if the microservice is slow to start up, the Kubernetes Startup probe will provide sufficient time to allow the microservice to start up and fully initialize, since it "blocks" the Liveness and Readiness probes, when the Kubernetes Startup Probe is configured.
- Add the new REST endpoint `/health/started`, which allows you to verify if your deployed applications have started or not.
- Need to update the section at the end, where we talk about the overall default readiness status is DOWN, if deployed applications in Open Liberty have not started yet, to include the same behaviour for the overall default Startup status as well. Similarly, we need to include the new MP Config property for the new Startup health checks to override the overall default Startup status, while the deployed applications are starting up: `mp.health.default.startup.empty.response=UP`
- Add a code example for the new `@Startup` annotation, as follows:
```
@Startup
@ApplicationScoped
public class StartupCPUUsageCheck implements HealthCheck {

    @Override
    public HealthCheckResponse call() {

        if (getCpuUsage() < 0.90) {
           return HealthCheckResponse.up(“startupCpuUsage”);
        }
        else {
           return HealthCheckResponse.down(“startupCpuUsage”);
        }
    }
}
```
- Add a JSON payload response example for the new `/health/started` endpoint, as follows:
```
{
  "status": ”UP",
  "checks": [
    {
      "name": ”startupCpuUsage",
      "status": ”UP",
    }
  ]
}
```

**Comment by pgunapal** [comment]
Created following issue (https://github.ibm.com/websphere/liberty-docs/issues/2361) for doc updates for WebSphere Liberty side.

**Comment by dmuelle** [comment]
Hi @pgunapal - I've updated the draft for this topic:

https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.8/health-check-microservices.html

Let me know if any further edits are needed. When you're satisfied with the draft, you can add the `technical reviewed` label to this issue to sign off. Thanks!

**Comment by pgunapal** [comment]
@dmuelle - Looks good! Added the `technical reviewed` label.

**Comment by chirp1** [comment]
@pgunapal Info included looks good. Approving the epic.

**Comment by dmuelle** [comment]
changes are now on vNext and will publish with the 21.0.0.8 docs release on 8/6. Closing this issue

**Comment by chirp1** [comment]
Mp 4.1, 3.1 moved to 21.0.0.9

**Comment by dmuelle** [comment]
Rolled back doc changes until 3.1 is approved for release

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 21.0.0.9
