### ISSUE TITLE
Address consistency and relevancy concerns in command reference docs

### ISSUE THREAD

**Issue by Rwalls1** [OpenLiberty/docs#4357]
Comments from issue #776:

- Use a complete sentence for the intro sentence. Some of the other commands in OL use complete sentences for the intro sentence.
- Leave off "options One or more optional parameters." The WL topics don't use the phrase. Calling options both options and parameters muddy what they are. I'm gathering that some of the options, such as --sourceAppPath=path, are required. So, saying that something is optional when it is required doesn't make sense.

These comments apply to several command reference docs and should be addressed consistently across each.

**Comment by dmuelle** [comment]
all commands are updated to use a complete sentence for intro and to remove  redundant "Options" headings. Other improvements include:
- consistent table formatting in each command topic
- consistent use of italics for variables that the user replaces
- various copyedit improvements

These changes will be delivered in 21.0.0.7 as part of #4216
