### ISSUE TITLE
Using the features bom on openLiberty appears to search for websphere liberty resources

### ISSUE THREAD

**Issue by mjwhale** [OpenLiberty/docs#4414]
Document: featureUtility installServerFeatures
http://openliberty.io/docs/21.0.0.6/reference/command/featureUtility-installServerFeatures.html

running the command:
`/opt/ol/wlp/bin/featureUtility installServerFeatures defaultServer --featuresBom=io.openliberty.features:features-bom:21.0.0.6 
`
results in the following error:
`CWWKF1408E: Unable to find the Websphere JSON file at the /opt/ol/wlp/tmp//com/ibm/websphere/appserver/features/features/21.0.0.6/features-21.0.0.6.json file location.`

would expect to see the file used:
`/io/openliberty/features/features/21.0.0.6features-21.0.0.6.json`

and not the com/ibm/websphere/appserver ones

**Comment by dmuelle** [comment]
As explained in [this comment](https://github.com/OpenLiberty/docs/issues/4413#issuecomment-878317824) on a related issue, the featuresBom option is not a valid command parameter and was the result of a known issue that was fixed in the 21.0.0.7 release.
