### ISSUE TITLE
Open Liberty docs version 21.0.0.7 removed from website

### ISSUE THREAD

**Issue by lfielke** [OpenLiberty/docs#4445]
Yesterday I was able to view the Open Liberty docs for the latest version 21.0.0.7 at https://openliberty.io/docs/21.0.0.7/ however today this shows a not found error page.

I also can no longer see "21.0.0.7" in the "Version" drop down at the top-left of the docs page at https://openliberty.io/docs

The https://openliberty.io/downloads/ page shows "21.0.0.7", so I expected to be able to read the docs for this version.

**Comment by dmuelle** [comment]
HI @lfielke - are you still unable to see the 21.0.0.7 version of the docs? I'm able to see them on my end and am not aware of any reason why they would have been unavailable. Most likely there was some kind of temporary server outage or error that has since been resolved. Sorry for the inconvenience. Please let us know if you still can't see 21.0.0.7 or if it happens again

**Comment by lfielke** [comment]
It's now working -- my link works, I can see 21.0.0.7 in the version dropdown and clicking docs on the homepage goes to 21.0.0.7.

**Comment by lfielke** [comment]
I've just noticed this has occurred again. It seems like the website thinks the latest docs are 21.0.0.6:
* Clicking "Docs" on https://openliberty.io/ navigates to https://openliberty.io/docs/21.0.0.6/overview.html
* The version dropdown top-LHS of that docs page doesn't list 21.0.0.7
* To rule out any browser quirks, I ran `curl -v -L https://openliberty.io/docs/`, which gets redirected to this sequence of URLs:
    * 302: https://openliberty.io/docs/latest/
    * 302: https://openliberty.io/docs/21.0.0.6/
    * HTML: `<meta http-equiv="refresh" content="0; url=overview.html">`

However I noticed if I keep trying that curl command, sometimes https://openliberty.io/docs/latest/ redirects to https://openliberty.io/docs/21.0.0.7/, which then returns HTTP 404.

HTTP exchange for that last 404 request in case this helps diagnose the issue:
```
* Connection #0 to host openliberty.io left intact
* Issue another request to this URL: 'https://openliberty.io/docs/21.0.0.7/'
* Found bundle for host openliberty.io: 0x55c326b9ebe0 [can multiplex]
* Re-using existing connection! (#0) with host openliberty.io
* Connected to openliberty.io (2606:4700:10::ac43:ffd) port 443 (#0)
* Using Stream ID: 5 (easy handle 0x55c326ba6ea0)
> GET /docs/21.0.0.7/ HTTP/2
> Host: openliberty.io
> user-agent: curl/7.68.0
> accept: */*
> 
< HTTP/2 404 
< date: Fri, 30 Jul 2021 06:06:56 GMT
< content-type: text/html
< x-backside-transport: FAIL FAIL
< cache-control: no-cache
< content-language: en-US
< content-security-policy: default-src 'self' 'unsafe-inline' 'unsafe-eval' maxcdn.bootstrapcdn.com fonts.googleapis.com ajax.googleapis.com code.jquery.com fonts.gstatic.com  *.githubusercontent.com api.github.com www.googletagmanager.com tagmanager.google.com www.google-analytics.com cdnjs.cloudflare.com data: buttons.github.io www.youtube.com *.twitter.com *.twimg.com video.ibm.com https://start.openliberty.io/
< expires: Thu, 01 Dec 1994 16:00:00 GMT
< last-modified: Thu, 08 Jul 2021 17:46:00 GMT
< referrer-policy: no-referrer
< set-cookie: JSESSIONID=xxxREDACTEDxxx; Path=/; Secure; HttpOnly
< set-cookie: __VCAP_ID__=xxxREDACTEDxxx; Path=/; HttpOnly; Secure
< strict-transport-security: max-age=31536000; includeSubDomains
< vary: Accept-Encoding
< x-content-type-options: nosniff
< x-frame-options: SAMEORIGIN
< x-powered-by: Servlet/4.0
< x-xss-protection: 1; mode=block
< x-global-transaction-id: 36a38c19610397007567e571
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
< cf-ray: 676c6762def93e69-ADL
```

**Comment by dmuelle** [comment]
@steven1046 can you look into this? @lfielke is experiencing an intermittent issue where the 21.0.0.7 docs are not available on the website. The docs default to 21.0.0.6 and 21.0.0.7 is not in the version picker. 

I haven't been able to reproduce this error on my end and I'm wondering if it might be a regional server issue. Details are in the previous issue comments.

**Comment by dmuelle** [comment]
@lfielke although we have not been able to reproduce this result, we pushed a few updates to our our build process recently that might have been delivered to some region servers before others. Most likely your were in or re-routed to a server that had not received the fix yet, but has since received it. Please let us know if you continue to see this problem. Thanks
