### ISSUE TITLE
Add/Clarify Gradle info in JDBC page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4446]
The following comment was [originally posted in #2867](https://github.com/OpenLiberty/docs/issues/2867#issuecomment-885359391) by @lfielke. Opening a new issue here to track the work to update the page. 

---
Some constructive criticism, for this page if I may: I had some trouble following this documentation page using the Open Liberty Gradle plugin. The page talks about using the Maven plugin to copy dependencies to the server config directory, however it doesn't mention the Gradle plugin.

We're already using Gradle to build our other projects, so I went searching for more information. I did find a blog post at https://openliberty.io/blog/2021/02/18/dev-mode-container-liberty-maven-gradle-plugins.html that describes that:
> In this blog post, we introduce the general availability of container support in dev mode and support for copying dependencies. **Both of these new capabilities are included** in the latest releases of the Liberty Maven **and Gradle** Plug-ins.

Based on this I thought there should be a way to configure the Gradle plugin to copy dependencies. I couldn't find any examples of this in the docs or elsewhere on the web, so I opened an issue https://github.com/OpenLiberty/ci.gradle/issues/619 to see if I had overlooked this. The suggestion was to use a Gradle copy task to achieve this, which makes sense because it's easy to add ad-hoc Gradle tasks to a build.

So reflecting on this, I humbly suggest a couple of things to help steer new users in the right direction:
* On the docs page, mention why the JDBC driver cannot be managed with the rest of the application's dependencies (eg the aim is to get it loaded by the right classloader because Open Liberty wants to do connection pooling, make it available of JNDI, the same driver cannot be loaded by multiple web applications, etc. Not sure if these are relevant to Open Liberty or there are other specific reasons for this, as I'm a newcomer to Open Liberty).
* Mention the desired end result: getting the driver JAR in the `server/config/jdbc` dir so that is included when you package the server, eliminating the need to manually install the driver on the server.
* Suggest a Gradle copy task could be used to achieve this, perhaps including the example from issue 619 above.
* Amend the blog post to not suggest that the Gradle plugin directly supports copy dependencies.

For reference, the docs page I'm referring to is:
https://openliberty.io/docs/21.0.0.7/relational-database-connections-JDBC.html#_jdbc_driver_library_configuration
However the version 21.0.0.7 docs don't seem to be available currently, but the version 21.0.0.6 page seems to be the same.

_Originally posted by @lfielke in https://github.com/OpenLiberty/docs/issues/2867#issuecomment-885359391_

**Comment by dmuelle** [comment]
additional comments from @mattbsox on slack:

The only other thing I might add is an example of a project’s dependencies. Something similar to the example dependencies provided by the user in the ci.gradle issue. That would eliminate potential confusion related to the Gradle dependency configuration reference in the from line in the Copy task example.
Something like this maybe:

```
configurations {
	jdbcLib //Declare the configuration
}
dependencies {
	jdbcLib 'some:jdbc:driver' //Add a dependency to jdbcLib
}
task copyJDBC { //Copy all jar files contained in the resolved jdbcLib configuration to {server.config.dir}/jdbc
    doLast {
        copy {
            from configurations.jdbcLib
            into '$buildDir/wlp/usr/servers/<YourServerName>/jdbc'
            include '*.jar'
        }
    }
}
deploy.dependsOn 'copyJDBC' //Add copyJDBC as a dependency for deploy so it will be called at the right time of the build
```

**Comment by dmuelle** [comment]
comment from OpenLiberty/ci.gradle#619

> You can use a `Copy` task to accomplish this. You'll just need to add it to your current build lifecycle.
> 
> ```
> task copyJDBC {
>     doLast {
>         copy {
>             from configurations.libertyLib
>             into ""$buildDir/wlp/usr/servers/<YourServerName>/jdbc""
>             include '*.jar'
>         }
>     }
> }
> ```
> 
> This will copy the jars into a `jdbc` folder in the server directory (server.config.dir) like `copyDepednencies` does in our Maven plugin.
> 
> You'll want to set it up to run after the server has been created. I would probably add it as a dependency for the `deploy` task.
> 
> ```
> deploy.dependsOn 'copyJDBC'
> ```
> 
> This ensures that the server has been created and will run before the application is deployed to the server.

**Comment by dmuelle** [comment]
Hi @mattbsox , can you provide technical review of the new section I've added to the JDBC doc draft?

[JDBC driver configuration with Maven or Gradle](https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.8/relational-database-connections-JDBC.html#_jdbc_driver_configuration_with_maven_or_gradle)

I've included the examples we discussed via Slack and tried to address the concerns @lfielke raises in the issue description. Let me know if anything is inaccurate and unclear from a build perspective. Thanks!

**Comment by mattbsox** [comment]
The changes look good to me. Think you've got everything there.

**Comment by lfielke** [comment]
I'm impressed to see some work done towards this so quickly after my suggestion, thanks for taking it constructively.

A comment about the draft `build.gradle` snippet -- I think the way the task is created doesn't allow up-to-date checks to work. This means that the JAR files will get copied every deploy, which is doing unnecessary work. You can see this by running the `deploy` task two times in a row without changing any source code, notice how most tasks print "UP-TO-DATE" but the copy task doesn't (for me there are a two other non-incremental tasks: `installFeature` and `deploy`).

As a bonus, the correct version with task inputs/outputs is also less verbose. The task I'm using is:

```groovy
task copyJdbcLibs(type: Copy) {
    from configurations.jdbcLib
    into '$buildDir/wlp/usr/servers/<YourServerName>/jdbc'
}
deploy.dependsOn copyJdbcLibs
```

By using the `Copy` task, we get the input/output checks for free without needing to declare anything further. The [docs for the Copy task](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html) show some more examples.

**Comment by dmuelle** [comment]
thanks for this feedback, @lfielke. I ran it by @mattbsox and he agreed that using  `type: Copy` is preferable to using the `copy` method. I've updated the draft accordingly:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.8/relational-database-connections-JDBC.html#_jdbc_driver_configuration_with_maven_or_gradle

**Comment by lfielke** [comment]
Sorry, I missed the pull request otherwise I would have commented in there. Looks good to me, aside from two minor nits:

- Indentation: the contents of the Gradle snippet blocks seem to be indented with 8 spaces, compared to 2 or 4 for the other snippets on that page. And the task block contents are indented an extra level compared to the other blocks in the snippet.
- Snippet language: The page shows that snippet is Javascript, but build.gradle files are Groovy.

Screenshot:

![image](https://user-images.githubusercontent.com/6062998/127936248-74f73f60-e258-4758-adc4-223b63827b30.png)

**Comment by dmuelle** [comment]
these issues were addressed in #4469

**Comment by dmuelle** [comment]
changes are now on vNext and will publish to production on 8/6.  Thanks again for your input @lfielke @mattbsox 

closing this issue

**Comment by dmuelle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/latest/relational-database-connections-JDBC.html#_jdbc_driver_configuration_with_maven_or_gradle
