### ISSUE TITLE
problem with Sinch Api Voice in android new version

### ISSUE THREAD

**Issue by meir1958** [OpenLiberty/docs#4531]
<html>
<body>
<div class="aju" style="cursor: default; float: none; padding: 0px 16px; align-items: center; display: flex; height: 80px; min-width: 40px; color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="aCi" style="position: relative;"><img id=":ns_24-e" name=":ns" src="https://lh3.googleusercontent.com/a-/AOh14GjtzQaaB6qaOCBu8pkAeZmls5b89V6zM8KJNzJ8pg=s40" class="ajn" jid="meirdahane@gmail.com" data-hovercard-id="meirdahane@gmail.com" data-name="מאיר דהאן" aria-hidden="true" style="display: block; width: 40px; height: 40px; border-radius: 50%;"></div></div><div class="gs" style="margin: 0px; padding: 0px 0px 20px; width: 1120px; color: rgb(34, 34, 34); font-family: Roboto, RobotoDraft, Helvetica, Arial, sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="gE iv gt" style="padding: 20px 0px 0px; cursor: auto; font-size: 0.875rem;">

מאיר דהאן <meirdahane@gmail.com‏> | מאיר דהאן <meirdahane@gmail.com‏> | 8:31 (לפני שתי דקות) |   |  
-- | -- | -- | -- | --
מאיר דהאן <meirdahane@gmail.com‏>
support | support
support

</div><div id=":rv"><div class="qQVYZb"></div><div class="utdU2e"></div><div class="lQs8Hd" jsaction="SN3rtf:rcuQ6b" jscontroller="i3Ohde"></div><div class="btm"></div></div><div class=""><div class="aHl" style="margin-right: -38px;"></div><div id=":257" tabindex="-1"></div><div id=":11r" class="ii gt" style="font-size: 0.875rem; direction: rtl; margin: 8px 0px 0px; padding: 0px; position: relative;"><div id=":ys" class="a3s aiL " style="overflow: hidden; font: small / 1.5 Arial, Helvetica, sans-serif;"><div dir="rtl"><div style="text-align: left;">Good Morning.   11/8/21<br>.I use<span> </span><b>Sinch Api Voice</b><br>.My app name is: myAppPhone<br>.My  registered email is:  <a href="mailto:meirdahane@gmail.com" target="_blank" style="color: rgb(17, 85, 204);">meirdahane@gmail.com</a><br>.I am using Android Studio Arctic Fox (2020.3.1) &amp; Android Gradle plugin 7.0 in Java<br>.before this version i used very well in Sinch Api Voice<br>.now in this version in is not recognized<br>:At the previous version i used this in Gradle<br>}  allprojects <br> }  repositories     <br>  }  flatDir      <br>            dirs 'libs'         <br>       {      <br>{  <br>{<br>   }   dependencies <br>implementation(name:'sinch-<wbr>android-rtc', version:'+', ext:'aar')         <br>{<br>:now in the new Gradle we have this code<br>} repositories <br>()google     <br>()mavenCentral    <br>{<br>.it is not allowed to use all projects anymore<br>:the error i get is<br>Could not find any matches for :sinch-android-rtc:+ as no versions of :sinch-android-rtc are available</div><div style="text-align: left;">?can anyone knows how to solve it<br>Regards<br></div></div></div></div></div></div>
</body>
</html>

**Comment by dmuelle** [comment]
Hi @meir1958 - does this error relate to [Open Liberty documentation](https://www.openliberty.io/docs/21.0.0.8/overview.html)? This repo is for documentation issues only.

If your issue relates to Open Liberty server errors, you might find help from our [community support resources](https://www.openliberty.io/support/). If the issue pertains specifically to Android, Maven or Gradle, you might find help from the Github or community resources for those products.
