### ISSUE TITLE
TS006458435 skill case requires update to two Open Liberty topics

### ISSUE THREAD

**Issue by t-koman** [OpenLiberty/docs#4534]
**TS006458435 skill case  requires an update to two Open Liberty Topics**
(1) topic: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/password-encryption.html
Change
Open Liberty supports Advanced Encryption Standard (AES) encryption for passwords that are stored in the server.xml file. When you use this option for protecting passwords in the Open Liberty configuration, understand the limits to the protection that AES encryption provides.
TO
Open Liberty supports Advanced Encryption Standard (AES) encryption for passwords that are stored in the server.xml file. When you use this option for protecting passwords in the Open Liberty configuration, understand the limits to the protection that AES encryption provides. **Currently, Open Liberty supports AES 128 encryption.**

(2) Topic: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/securityUtility-encode.html
The description in the Options table for --encoding=encoding_type 
CHANGE
Specifies how to encode the password. Supported encodings types are xor, aes, and hash. If this option isn’t specified, a default encoding type of xor is used. 
TO
Specifies how to encode the password. Supported encodings types are xor, aes, and hash. If this option isn’t specified, a default encoding type of xor is used. **Currently, aes type uses AES 128 encryption.**

NOTE: The **BOLD** identifying the update need not be in the topic update.  It is added here to identify the text that needs to be added.

**Comment by t-koman** [comment]
I located another topic that is worth updating:
https://openliberty.io/docs/20.0.0.10/server-configuration-hardening.html#password-encryption
@una-tapa Hiroko - Please confirm.....  Is this topic worth an update that says in section **Password encryption**
Change
Use AES encryption for passwords instead of Base64 encoding. AES encryption is also preferable to XOR encryption because an XOR-encoded password is visible to any administrator.
TO
Use AES encryption for passwords instead of Base64 encoding. AES encryption is also preferable to XOR encryption because an XOR-encoded password is visible to any administrator. **Currently, Open Liberty supports AES 128 encryption.**

**Comment by ramkumar-k-9286** [comment]
@t-koman 

Hi,
Please find below the links to the draft versions of the documents with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/password-encryption.html
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/reference/command/securityUtility-encode.html

Please do confirm if they are fine.

Regards
Ramkumar

CC @dmuelle

**Comment by t-koman** [comment]
@ramkumar-k-9286 Ralm, I've reviewed these updates and they look good to me..... you can close.... thanks

**Comment by ramkumar-k-9286** [comment]
Issue documented and moved to vNext. Will be available in 21.0.0.9
Proceeding to close the issue.

Regards,
Ramkumar
