### ISSUE TITLE
Clarify HTTP access log %D documentation

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/docs#4536]
[HTTP Access Log custom formats](https://openliberty.io/docs/latest/access-logging.html) says:

> %D | The elapsed time of the request - millisecond accuracy, microsecond precision

This matches what [WAS traditional says](https://www.ibm.com/docs/en/was-nd/9.0.5?topic=chains-http-transport-channel-custom-properties).

However, [Liberty's implementation now uses nanosecond accuracy](https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.transport.http/src/com/ibm/ws/http/channel/internal/values/AccessLogElapsedTime.java#L36), so Liberty's documentation is no longer accurate. Better to say:

> %D | The elapsed time of the request in microseconds

@wtlucy please confirm

**Comment by wtlucy** [comment]
+1 from me. This will be more correct _and_ understandable.

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Updated.
The draft document link:
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/access-logging.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- i think this is ready to go to staging

**Comment by ramkumar-k-9286** [comment]
@kgibm , @wtlucy 

Updates have been made to the document as suggested.

The draft document link:
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.9/access-logging.html

Please confirm if this is fine.

Regards,
Ramkumar

**Comment by kgibm** [comment]
@ramkumar-k-9286 Looks good, thank you!

**Comment by wtlucy** [comment]
@ramkumar-k-9286 likewise, looks good to me!

**Comment by ramkumar-k-9286** [comment]
Issue documented and moved to vNext. Will be available in 21.0.0.9
Proceeding to close the issue.

Regards,
Ramkumar
