### ISSUE TITLE
Document schemaGen command

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4550]
We need to document the `schemaGen` command for Open Liberty, which is run from `wlp/bin` and generates a server schema .xsd file. Should follow the convention of other command reference topics

the command help is not working currently, but partial help documentation is available if you run `schemaGen -help` from `wlp/bin/tools`

see https://github.ibm.com/websphere/liberty-docs/issues/2423  and [this slack thread](https://ibm-cloud.slack.com/archives/C30NGTBFS/p1628780776093500) for context. 

possible SMEs @frowe @cbridgha

**Comment by dmuelle** [comment]
epic for command wrapper

https://github.com/OpenLiberty/open-liberty/issues/18191

this doc should target whatever release that epic goes into

**Comment by jimblye** [comment]
The documentation for this is here:  https://www.ibm.com/docs/en/was-liberty/core?topic=line-generating-liberty-configuration-schema-from-command

It just needs moved(copied?) to open liberty.

The following changes need to be made so that we are documenting the command script rather than the JAR.

They will still be able to use the JAR, but that's not the preferred way, and we should really only document running it from a script.

<img width="1064" alt="image" src="https://user-images.githubusercontent.com/16544901/150231763-db516ad0-1888-485c-a0d0-554c504122b2.png">

**Comment by dmuelle** [comment]
@jimblye are there any exit codes for `schemaGen` ?

**Comment by dmuelle** [comment]
Hi @jimblye - this doc update is ready for review at:

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/reference/command/schemaGen.html

I also add a redirect statement to the WAS Liberty doc:
https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=line-generating-liberty-configuration-schema-from-command
(the link here won't work until the doc publishes with 22002 though)

2 questions:
1. Are there any valid exit codes for this command? We list them for most (though not all) other commands. I've got a placeholder table for them in the draft doc that I'll need to either update or remove before we publish.
2. For the `ignorePidsFile` option, what does PID stand for in this context? I've got "persistent identifier" in the doc but not sure if that's correct.

Thanks!

**Comment by jimblye** [comment]
@dmuelle 
First, note that target has changed to 22.0.0.3.

I'm not seeing PID in this context documented anywhere except in an error message:  "CWWKG0021E: The same configuration **persisted** identity (PID) {0} is defined in multiple metatype.xml files."

Clearly we are talking about something that isn't documented.  So spelling it out doesn't help much, but here's a little more info that I got from Brent Daniel: 
 PID is a unique ID that identifies a configuration.  PIDs are specified in metatype.xml using either  a \<pid\> or \<factoryPid\> element.   “PID” refers to either one.  Though, ‘factoryPid’ is much more common than 'pid'.
 
 Users will still have difficulty with this as I could not find any documentation for factoryPid, even when searching for metatype.xml, but I suppose adding this little tidbit of information is better than nothing.

Exit Codes
   0 - OK, No error
   20 - Invalid Argument
   21 - An runtime exception occurred

**Comment by dmuelle** [comment]
ok thanks @jimblye - I've updated the draft and changed our tags to not publish it until at least 22.0.0.3

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/command/schemaGen.html

**Comment by dmuelle** [comment]
need to add `compactOutput` to the options

**Comment by dmuelle** [comment]
Hi @jimblye - circling back on this now that we've got 22.0.0.2 out the door.

I thought I remembered from your EOI demo there was an option we had not documented- `compactOutput`. So I downloaded the 22003 beta to check it out in the help.  I'm not sure that the beta includes the finished command so maybe none of this matters. But- none of the options listed in the help match what we have documented- in this draft or in the IBM docs topic.

 Here's what I'm seeing in the help:

```
$ schemaGen -help
Usage: schemagen [-options ...] <java files> 
Options: 
    -d <path>             : specify where to place processor and javac generated class files
    -cp <path>            : specify where to find user specified files
    -classpath <path>     : specify where to find user specified files
    -encoding <encoding>  : specify encoding to be used for annotation processing/javac invocation 
    -episode <file>       : generate episode file for separate compilation
    -disableXmlSecurity  :  disables XML security features for usage on xml parsing apis 
    -version              : display version information
    -fullversion          : display full version information
    -help                 : display this usage message
```

The only one of those we've documented is `encoding`. Also, for the help, we document
`schemaGen --help`
but that only works because OL doesn't recognize the option and defaults to printing the help. You have to run 
`schemaGen -help` (one dash) to get the help to run properly. 

I'm wondering if this is the case for the other options too, but I can't check it because I can't get the command to work. Even running it with no options gets `error: Could not find class file for 'schema.xsd'.` Which might just be because its not finished in the beta.

I can hold off on this if it's still in progress but just need to figure out
1. what the options are and is the help correct ?
2. does the command syntax use 1 or 2 dashes to specify options?

Thanks

**Comment by dmuelle** [comment]
Also- where does the command put the output file when no path is specified?

**Comment by jimblye** [comment]
@dmuelle
When you typed the command "schemaGen -help" as you did above, you actually invoked a different schemaGen command.   If you enter the command "which schemaGen" you will find where that other schemaGen command script is located.

To invoke the Liberty schemaGen script, do this:

cd wlp/bin
./schemaGen -help

The output in the current version that I have looks like this:

```
The schemaGen command generates the XML schema for the                       
Liberty core configuration and other installed products                
extensions in a single output file.

Usage: ./schemaGen [options] outputFile

Options:

--compactOutput
The output schema will not contain indenting 
spaces, new line feeds, or XML comments.

--encoding
The character encoding to use for the output.

--ignorePidsFile
A file name containing a list of pids to ignore.

--locale
The language to use when you are creating the output
file. This string consists of the ISO-639 two-letter lowercase language
code, optionally followed by and underscores and the ISO-3166 uppercase
two-letter country code.

--outputVersion
If outputVersion=2.0 is specified, only the xsd:any element is used    
in the output file, so that unknown elements pass XSD validation at    
the expense of losing validation for known elements.

--schemaVersion
If schemaVersion=1.1 is specified, then both explicitly named child    
elements and the xsd:any element are written to the output file.
```

If I type the command with no arguments, I get the short and sweet version:

```
The schemaGen command generates the XML schema for the                       
Liberty core configuration and other installed products                
extensions in a single output file.

Usage: ./schemaGen [options] outputFile
```

**Comment by dmuelle** [comment]
Thanks, I had missed the crucial detail that the command needs `./` to work. I still can't test it, I suspect because I don't have a 22.0.0.4-beta server handy. The only thing I wanted to test for is to see where the outputFile gets created. If you only provide a file name and no path, where does the schema file show up?

**Comment by jimblye** [comment]
@dmuelle If you don't specify a path, the output file is written to the current directory.

**Comment by dmuelle** [comment]
Thanks @jimblye - just to make sure I've got this right- by the current directory, do you mean the `bin` directory where you run the command from?

**Comment by jimblye** [comment]
@dmuelle 

wlp/bin is where the command resides, but the "current" directory refers to the directory from which you run the command.  For example, if the "current" directory in my command prompt is "wlp" then I can still execute the schemaGen command.  I just need to give the path to the command, like this:

bin/schemaGen schemaGen.xsd

That will put the output file, schemaGen.xsd in the "wlp" directory.  

In the previous example of "./schemaGen", the "." is the path.  In this context, the "." is a symbol that refers to the "current" directory.  So when I put "./" in front of the command, I'm telling the OS to look for the command in the current directory.

 The concept of "current" directory is not something you need to explain.  Programmers will know what it means.

**Comment by dmuelle** [comment]
Moving to 22.0.0.5 with the Epic

**Comment by dmuelle** [comment]
current draft for review: https://draft-openlibertyio.mybluemix.net/docs/latest/reference/command/schemaGen.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
-----

The `schemaGen` command generates a schema for an entire Open Liberty installation in a single output file in the current directory. **This command generates a schema for an entire Open Liberty installation.** 
To generate a schema for a specific server, use the [serverSchemaGen command](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/command/serverSchemaGen.html).

**This command generates a schema for an entire Open Liberty installation.** --> Repeats the 1st sentence. Remove?

---

Generate a schema for the Open Liberty installation in a file that is called `schema.xsd` in the current directory.
`schemaGen schema.xsd`
Generate a schema in the Brazilian Portuguese language for the Open Liberty installation in a file that is called `schema.xsd`.
`schemaGen --locale=pt_BR schema.xsd`
--->

Removed **that is** 

Generate a schema for the Open Liberty installation in a file called `schema.xsd` in the current directory.
`schemaGen schema.xsd`
Generate a schema in the Brazilian Portuguese language for the Open Liberty installation in a file called `schema.xsd`.
`schemaGen --locale=pt_BR schema.xsd`

---

In the **Options for the schemaGen command** table

For the `--compactOutput` option, the Description starts off as "When this option is specified,"

For the rest  of the  options, the Description starts off as "This option specifies...."

Should there be similar across the table, like in the exit codes table?

---
`--locale=language` - This option specifies the language to use in the generated output file, where language is an ISO-639 two-letter lowercase language code, optionally followed by an underscore and the ISO-3166 uppercase two-letter country code.

**Acrolinx - Sentence too long - 33 words.**

**Suggested**
`--locale=language` - This option specifies the language to use in the generated output file. Language is an ISO-639 two-letter lowercase language code and can be followed by an underscore and the ISO-3166 uppercase two-letter country code.

---


The following exit codes are available for the `schemaGen` command:

**Suggested**
The following exit codes are available for the `schemaGen` command.

**"."** is used for the previous table. 

---
This code indicates successful completion of the requested operation.

**Suggested**
This code indicates **the** successful completion of the requested operation.

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - all suggestions incorporated except for the following:

- The second sentence is somewhat redundant but I think it's warranted in this case to make the distinction between schemaGen and serverSchemaGen clear.
- removing *that is*:  For translation purposes, when you use a past  participle like "named", must conjoin it with "that is"
- fixed the definition for --locale=language by removing one word- "generated"

**Comment by dmuelle** [comment]
changes are on vNext and will publish with the 22.0.0.5 docs release- closing this issue.
