### ISSUE TITLE
Update FeatureUtility command to include new options 

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/docs#4559]
FeatureUtility Epic: https://github.com/OpenLiberty/open-liberty/issues/8986

- The FeatureUtility `installFeature` and `installServerFeatures` commands need to be updated with the new options. 

|Option               |  Description|
----------------| -----------
|--featuresBom | Specify the Maven coordinate for the features BOM file to install user features. Ensure that the repository also contains the  associated features JSON file in the same groupId as the BOM.|
|--to                   | Specify the extension location to install user features. If this option is not specified, the feature is installed to default {wlp.install.dir}/usr/extension directory. | 

- Also need to add new property under "Modifications for featureUtility commands" (https://openliberty.io/docs/21.0.0.5/reference/command/featureUtility-modifications.html)

You can specify the maven coordinate for the features BOM file to install user features by adding the `customBomFileName.featuresbom` property in the featureUtility.properties file. 
Example:
`customBomFileName.featuresbom=my.maven.coordinate:my-features-bom:version`

**Comment by ramkumar-k-9286** [comment]
Hi @jjiwooLim @bensonlatibm 

Please find below the links to the draft versions of the documents with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/command/featureUtility-installFeature.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/command/featureUtility-installServerFeatures.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/command/featureUtility-modifications.html

Please do confirm if they are fine.

Regards
Ramkumar

@dmuelle

**Comment by bensonlatibm** [comment]
Changes look good to me!

**Comment by bensonlatibm** [comment]
feature just missed 21.0.0.10.  it will be in 21.0.0.11 instead.

**Comment by dmuelle** [comment]
## peer review

### Modifications for featureUtility commands

- the new property that @jjiwooLim requested in the issue description is missing from the page. Add the property as described in this issue to the end of the page. For clarity, create subject headings for the last two examples: `Define custom repositories` and `Install user features`
- the `http_proxy` and `https_proxy` environment variables are in lowercase, unlike the other env vars. Please confirm whether this is correct and edit if needed. 
***********************************
( Confirmed with **Sarah (Jiwoo) Lim**, the environment variables are meant to be in lowercase, so no update required, correct as is displayed)-**edit by Ram**. 
***********************************
### installFeatures and installServerFeatures

`Specify the Maven coordinates for the features BOM file to install user features`
 For clarity and parallelism with the other definitions --->

`Specifies the Maven coordinates for a features BOM file. Use this option to install custom user features from a Maven repository.`

**Comment by dmuelle** [comment]
please add the following examples to the "Usage Examples" sections for installFeature and installServerFeatures, respectively

- `featureUtility installFeature userFeature-1.0 --featuresBom=my.user.features:myBOM:<runtime-version>`
- `featureUtility installServerFeatures serverName --featuresBom=my.user.features:myBOM:<runtime-version>`

introduce each example with a concise description, similar to the existing examples

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Peer review incorporation with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-installFeature.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-installServerFeatures.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-modifications.html

**Noticed issues with featureUtility-installFeature & featureUtility-installServerFeatures - _runtime-version_ not getting _Italicised_.**

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Peer review incorporation with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-installFeature.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-installServerFeatures.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-modifications.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-modifications.html

just noticed this is the wrong document- the update should have been applied to [the featureUtitlty landing page](https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-commands.html)- not the old "Modifications" page. This page should be removed

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Peer review incorporation with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-commands.html

The pull request for the update. (https://github.com/OpenLiberty/docs/pull/4833/files)

**Comment by ramkumar-k-9286** [comment]
Changes are on vNext and will publish with the 21.0.0.11 docs release.

**Comment by dmuelle** [comment]
need to update the mention of `_runtime-version_` to include a noun (value) per Karen's comment
