### ISSUE TITLE
Updates to open liberty docs for feature 9786

### ISSUE THREAD

**Issue by brenthdaniel** [OpenLiberty/docs#4567]
Release: targeted for 21.0.0.9 but has a good chance of slipping to 21.0.0.10

https://openliberty.io/docs/21.0.0.8/reference/directory-locations-properties.html

Need to add `variables` directory under "servers->server_name" (same level as dropins, configDropins, etc.) The property is blank, and the description is "Default directory for files to be loaded as configuration variables. For more information see (link to server-configuration-overview)"

https://openliberty.io/docs/21.0.0.8/reference/default-environment-variables.html

Add `VARIABLE_SOURCE_DIRS` with the description `The directories that contain files to be loaded as configuration variables. The default value is ${server.config.dir}/variables.` 

Also, the description for `LOG_DIR` is missing a period after the first sentence. 

https://openliberty.io/docs/21.0.0.8/reference/config/server-configuration-overview.html

Under "Variable Substituion Precedence", add in between `java system properties` and `variable values declared in the server.xml file`,  `Variables loaded from files in the ${server.config.dir}/variables directory`

Somewhere in the same section, probably after it talks about command line variables and environment variables, we need something like:
```
Variables can be loaded from files located in directories specified by the VARIABLE_SOURCE_DIRS environment variable. The default location is ${server.config.dir}/variables. The name of the file will be used as the variable's name, and the contents of the file will be used as the variable's value. For example, if you create a file in the "variables" directory named "httpPort" with a value of "9080", you can then use the variable ${httpPort} in the server.xml file and it will resolve to "9080". 

If a file is located in a directory underneath the "variables" directory then the parent directory will be added to the variable name. For example, if the "variables" directory contains a directory named "ports", and that directory contains a file name "httpPort", then you can use the variable ${ports/httpPort} in server.xml.

Variables in the VARIABLE_SOURCE_DIRS directories can also be defined in properties files. If the name of the file ends in ".properties", each property in the file will be used to create a variable. For example, if the "variables" directory contains a file named "ports.properties" with the contents:
httpPort=9080
httpsPort=9443

the variables ${httpPort} and ${httpsPort} can be used in server.xml and the values will be 9080 and 9443. 
```

**Comment by dmuelle** [comment]
Hi @brenthdaniel, is  this epic for this issue: https://github.com/OpenLiberty/open-liberty/issues/9786 ?

**Comment by dmuelle** [comment]
perhaps I should have looked at the title 😅

**Comment by tevans78** [comment]
#9786 isn't fully approved yet so moved to 21.0.0.10

**Comment by ramkumar-k-9286** [comment]
Hi @brenthdaniel 

I have a few doubts which I wanted to clarify with you.

1. In the [default-environment-variables](https://openliberty.io/docs/21.0.0.8/reference/default-environment-variables.html) page, while adding the environment variable `VARIABLE_SOURCE_DIRS`, in the description there is mention of another variable `WLP_CONFIG_DIR`. This has not been mentioned on the default-environment-variables page. 
There is no mention of this variable in the `wlp>bin> server.bat` file as well.
 
Please confirm if `WLP_CONFIG_DIR` needs to be documented on the default-environment-variables page. 

2. In the [server-configuration-overview](https://openliberty.io/docs/21.0.0.8/reference/config/server-configuration-overview.html) page, 
`Variables can be loaded from files located in directories specified by the VARIABLE_SOURCE_DIRS environment variable. The default location is ${server.config.dir}/variables. The name of the file will be used as the variable's name, and the contents of the file will be used as the variable's value. For example, if you create a file in the "variables" directory named "httpPort" with a value of "9080", you can then use the variable ${httpPort} in the server.xml file and it will resolve to "9080". `

Is there a syntax for the content within the file? How will the content look?

`If a file is located in a directory underneath the "variables" directory then the parent directory will be added to the variable name. For example, if the "variables" directory contains a directory named "ports", and that directory contains a file name "httpPort", then you can use the variable ${ports/httpPort} in server.xml.`

Can this be combined with the first example?

`Variables in the VARIABLE_SOURCE_DIRS directories can also be defined in properties files. If the name of the file ends in ".properties", each property in the file will be used to create a variable. For example, if the "variables" directory contains a file named "ports.properties" with the contents:`
httpPort=9080
httpsPort=9443
`The variables ${httpPort} and ${httpsPort} can be used in server.xml and the values will be 9080 and 9443.`

Is there a syntax for the content within the file?  for example httpPort="9080" as mentioned in a previous example.


Thanks & Regards,
Ramkumar.

**Comment by brenthdaniel** [comment]
1. You're right, that should be `server.config.dir` -- I updated the original description. 
2. There is no syntax for what's in the file -- It is just a text string that will be used as the value for the variable. 
3. If you think it makes more sense to combine the examples for ${httpPort} and ${ports/httpPort} that's fine, but I think it's worthwhile to point out how both scenarios work (either a simple file, or a file located in a subdirectory.)

**Comment by ramkumar-k-9286** [comment]
Hi @brenthdaniel 

Please find below the links to the draft versions of the documents with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/directory-locations-properties.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/default-environment-variables.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/config/server-configuration-overview.html

Please do confirm if they are fine.

Regards
Ramkumar

@dmuelle

**Comment by dmuelle** [comment]
This feature might not make the 21.0.0.10 release. I think we can continue with the review process but please hold off on sending any changes to staging until we confirm the target release. Thanks

**Comment by ramkumar-k-9286** [comment]
Noted.

**Comment by chirp1** [comment]
@ramkumar-k-9286 Hi Ram, whether the epic for this issue, and therefore this issues, goes into 21.0.0.10 will be decided on September 22.

**Comment by brenthdaniel** [comment]
@ramkumar-k-9286 Looks good to me

**Comment by ramkumar-k-9286** [comment]
Hi @brenthdaniel

As you are aware these updates were made for 21.0.0.10 but got pushed to 21.0.0.11.

Just wanted to make sure that there are no additional changes/modifications included as a part of the 21.0.0.11 release.

Please find below the links to the draft versions of the documents with the suggested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/directory-locations-properties.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/default-environment-variables.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/config/server-configuration-overview.html

Please confirm if they are fine. Also, request you to add the `technical reviewed` label if the changes are as per your requirement.

Regards
Ramkumar

@dmuelle

**Comment by dmuelle** [comment]
## Peer review:
[Directory locations and properties](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/directory-locations-properties.html)

The description for `+- variables` says: "For more information about this file, see the Server configuration overview.", but `variables` is a directory, not a file. Also, I think this should directly to the `Variable substitution precedence` section of the server config overview:
`For more information, see xref:reference:config/server-configuration-overview.adoc#variable-substitution[Variable substitution precedence]`

[Server configuration overview](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/config/server-configuration-overview.html).

The information you added splits two examples that are related to one another. The sentence that starts "For versions 19.0.0.3 and earlier.." and the code example that accompanies it should be moved up to be directly after the list that ends with "3. MY_ENV_VAR"

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Peer Review Incorporation: in 2 documents

directory-locations-properties.adoc
server-configuration-overview.adoc

https://github.com/OpenLiberty/docs/pull/4816

**Comment by dmuelle** [comment]
confirmed changes on draft- looks good

**Comment by ramkumar-k-9286** [comment]
@dmuelle

**For Review: ( Staging Version )**

Please find the draft links for the documentation:

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/directory-locations-properties.html

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/default-environment-variables.html

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/config/server-configuration-overview.html

**Comment by ramkumar-k-9286** [comment]
Changes are on vNext and will publish with the 21.0.0.11 docs release.
