### ISSUE TITLE
Add searching capability (Duplicate- no ID work needed)

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/docs#4574]
The docs are fairly complete now, but it's difficult to find what you are looking for if you are not familiar with the page structure. I usually end up searching directly in Google.

My request is to add a search box on the documentation.

**Comment by dmuelle** [comment]
Hi @ggam - I agree! As the docs grow, we really need a search solution. We have [an issue open for this on the OL website backlog](https://github.com/OpenLiberty/openliberty.io/issues/1943) and have been evaluating solutions

**Comment by dmuelle** [comment]
closing this issue as we already have an issue for search on the website backlog, and the strategy/decision for how to provide will be worked out there
