### ISSUE TITLE
Update links in dev mode documentation

### ISSUE THREAD

**Issue by ericglau** [OpenLiberty/docs#4587]
Certain links in https://openliberty.io/docs/21.0.0.8/development-mode.html point to https://github.com/OpenLiberty/ci.maven/blob/master/docs/dev.md (or `#` sections within that).

The `master` branch of https://github.com/OpenLiberty/ci.maven is no longer up to date.  The default branch has been changed to `main`.  We should change all links that reference `master` to point to `main`, e.g. https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md

For consistency, also change ci.gradle links from https://github.com/OpenLiberty/ci.gradle/blob/master/docs/libertyDev.md#libertydev-task to https://github.com/OpenLiberty/ci.gradle/blob/main/docs/libertyDev.md#libertydev-task (even though GitHub redirects that already).

**Comment by dmuelle** [comment]
Thanks for catching this @ericglau - I've added the changes to our vNext branch and they will publish with the 21.0.0.9 docs release. 

I also ran a grep to search for similar URLs across the docs. Was able to fix another topic, though several others remain as the GH repos they target have not yet updated master-->main.
