### ISSUE TITLE
Update command pages organization

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4631]
- [x] make commands overview the top level (L1) landing page, reorganize as necessary to point to new L2 pages
- [x] create L2 pages for each command group (feature, server, etc)
- [x] include the "modifications for featureUtility" on the L2 featureUtility page
- [x] make existing command pages L3

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 - one other command change to make. On the [server help command page](https://www.openliberty.io/docs/21.0.0.9/reference/command/server-help.html), the formatting for the intro statement is messed up- can you fix  the formatting so it displays correctly? LMK if you have any questions

**Comment by dmuelle** [comment]
found this in an older issue re command pages: 

Add [source,sh] to each of the server command usage examples (cos they're shell commands)

**Comment by dmuelle** [comment]
## Peer review

### commands landing page

Various commands are available for use in Open Liberty. You can use commands to complete tasks such as installing, securing, and administering the Open Liberty server.
--->
Various commands are available in Open Liberty. You can use commands for tasks such as installing, securing, and administering the Open Liberty server from a command-line interface.

You can also see the following documentation for more information about commonly used commands in Open Liberty:
--->
For more information, see the following documentation about commonly used commands in Open Liberty:

### featureUtility commands landing page

Before "modifications" section, add a linked list of the featureUtility commands, similar to what you have for securityUtility

### server commands
add a linked list of the featureUtility commands, similar to what you have for securityUtility

### springBootUtility commands
For more information, see [Containerizing, packaging, and running a Spring Boot application].
--->
For more information, see the [Containerizing, packaging, and running a Spring Boot application] guide.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Peer Review comments incorporated:

Please find the draft links for the documentation:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/command-overview.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-commands.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/server-commands.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-commands.html

**Comment by dmuelle** [comment]
LGTM- we can PR this to staging- nice work!

**Comment by ramkumar-k-9286** [comment]
@dmuelle

**For Review: ( Staging Version )**

Please find the draft links for the documentation:

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/command-overview.html

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/featureUtility-commands.html
**( Pending second update, currently in drafts, 2 examples with headings will come in with that)**

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/server-commands.html

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-commands.html

**Comment by ramkumar-k-9286** [comment]
Changes are on vNext and will publish with the 21.0.0.11 docs release.
