### ISSUE TITLE
updates for springBootUtility commands

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4687]
https://www.openliberty.io/docs/21.0.0.9/reference/command/springbootUtility-help.html

- italicize _path_to_liberty_
- remove "actionName" section

https://www.openliberty.io/docs/21.0.0.9/reference/command/springbootUtility-thin.html
- add exit codes

**Comment by ramkumar-k-9286** [comment]
Had a conversation with **Tom Watson**, with regards to exit codes for springbootUtility-thin.html

Info Shared via slack:

**Tom Watson** 
0 - OK status (it worked)
1 - A general error occurred
2 - Specified application could not be found.
3 - Specified application target file is an existing directory.
4 - Specified library cache target directory is an existing file.
5 - Error making the required directories. (edited) 

can we just say
0 - OK (Success)
>0 - Exit codes that are greater than 0 indicate that an error occurred while performing the request. Messages are printed with more information about the error.

**Ramkumar** 
I was checking **securityUtility-createLTPAKeys.html**, they have all the different codes specified from 0 to 5

**Tom Watson**
ok, I just don't see the need to be that specific.  I would prefer we didn't for the spring util.  I don't see any script being able to automate based off the different errors from the spring util.

**Ramkumar K** 
ok. Got it. anyway will discuss with my team. loop you on the update i make.

Updates made, based on this discussion.

**Comment by ramkumar-k-9286** [comment]
For Review: 

Please find the draft links for the documentation:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/command/springbootUtility-help.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.10/reference/command/springbootUtility-thin.html

CC @dmuelle

**Comment by dmuelle** [comment]
HI @ramkumar-k-9286 - The changes look good. There is one other fix to make, which I missed when I opened this issue (sorry).
on the help page, the intro statement should be a complete sentence, as it is on other command pages:

Prints help information for the `springBootUtility` command, with details about its actions and options.
--->
The `springBootUtility help` command prints help information for the `springBootUtility` command, with details about the command actions and options.

**Comment by ramkumar-k-9286** [comment]
For Review:

Please find the draft links for the documentation:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-help.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-thin.html

Should I share this issue with Tom for review (`Technical Reviewed`)? Was not sure as you opened the issue. 

CC @dmuelle

**Comment by dmuelle** [comment]
add title attributes to tables on `thin` command. See `server create` file for reference

**Comment by ramkumar-k-9286** [comment]
@dmuelle

For Review:

Please find the draft links for the documentation:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-help.html

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-thin.html

**Comment by dmuelle** [comment]
looks good to me- when you have a chance, open the PR to staging

**Comment by ramkumar-k-9286** [comment]
@dmuelle

**For Review: ( Staging Version )**

Please find the draft links for the documentation:

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-help.html

https://docs-staging-openlibertyio.mybluemix.net/docs/21.0.0.11/reference/command/springbootUtility-thin.html

**Comment by ramkumar-k-9286** [comment]
Changes are on vNext and will publish with the 21.0.0.11 docs release.
