### ISSUE TITLE
Add a "JAX-RS" section to the RESTful microservices page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4696]
The RESTful microservices page should be the top-level page of the RESTful services section, but we need to add some info about JAX-RS applicatons. Work with the SME to determine what makes sense. At minimum, in brief:

- explain JAX-RS as EE spec, what types of function it enables
- typical use cases, context
- how open Liberty helps develop and run JAX-RS apps and services

SME @andymc12

**Comment by dmuelle** [comment]
needed for the Landing pages epic

**Comment by dmuelle** [comment]
Hi @andymc12 - when you have a moment, can you review the updates to the REST services page to make it a more suitable top-level page for this section of the doc? I made the following changes

- added section for JAX-RS
- added section for REST clients
- removed some of the API doc info that was duplicated on the API docs topic in this section

https://draft-openlibertyio.mybluemix.net/docs/latest/rest-microservices.html

These sections are intended to be concise high level overviews that point to other topics and guides for more info, but if any crucial details are missing, or if anything is inaccurate/ misrepresented, please let me know. Thanks!

**Comment by andymc12** [comment]
Hi @dmuelle - the changes look good to me!  Thanks!

**Comment by dmuelle** [comment]
changes are on vNext, will publish with 21.0.0.11
