### ISSUE TITLE
doc for MicroProfile Context Propagation

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/docs#471]
_The following is a draft article for openliberty.io general docs on the MP Context Propagation 1.0 feature:_

Use MicroProfile Context Propagation to ensure that `CompletionStage` actions run with predictable and reliable thread context.

**Overview**

The Java SE [CompletionStage](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletionStage.html) interface and its built-in [CompletableFuture](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html) implementation comprise a powerful mechanism for enabling applications to react to events and other actions by setting up pipelines of dependent actions.

MicroProfile Context Propagation enhances this model by adding the ability to propagate context from the requesting thread (for example, which invokes [thenApply](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletionStage.html#thenApply(java.util.function.Function)) or [thenRun](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletionStage.html#thenRun(java.lang.Runnable))) to the dependent stage action. MicroProfile Context Propagation also preserves the managed executor from which the initial stage was created as the default executor for all dependent actions that are requested with the `*Async(action)` methods.  This means that all of these async actions run on the automatically-tuned Liberty global thread pool, subject to the concurrency constraints of the managed executor.

**Configuration in Open Liberty**

To enable, add the `mpContextPropagation-1.0` feature to your server configuration,

```
<featureManager>
    <feature>mpContextPropagation-1.0</feature>
    <feature>cdi-2.0</feature>  <!-- used in example -->
    <feature>jndi-1.0</feature> <!-- used in example -->
    ... other features
</featureManager>
```

**Obtaining a ManagedExecutor or ThreadContext instance**

You have several options for obtaining instances of [ManagedExecutor](https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ManagedExecutor.html) and [ThreadContext](https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ThreadContext.html).

* The MicroProfile Context Propagation specification defines a fluent builder pattern.  When the application builds instances of managed executor, the executor's life cycle is managed by the application, which means the application is responsible for invoking the `shutdown` or `shutdownNow` method on managed executors to ensure that resources are properly cleaned up.
```
  ManagedExecutor executor = ManagedExecutor.builder()
      .maxAsync(10)
      .propagated(ThreadContext.APPLICATION, ThreadContext.SECURITY)
      .cleared(ThreadContext.ALL_REMAINING)
      .build();

  ThreadContext threadContext = ThreadContext.builder()
      .propagated(ThreadContext.APPLICATION, ThreadContext.CDI)
      .cleared(ThreadContext.ALL_REMAINING)
      .build();

  ...
  executor.shutdown(); // once finished using the managed executor
```

* If you are using Java EE Concurrency, another way to obtain a `ManagedExecutor` is to cast your existing [ManagedExecutorService](https://openliberty.io/docs/ref/javadocs/liberty-javaee8-javadoc/javax/enterprise/concurrent/ManagedExecutorService.html) to `ManagedExecutor`.  Open Liberty provides this ability as an extension to the specification.  In this case, the life cycle of the executor is tied to the that of the server.  A `ManagedExecutorService` can be defined in server configuration, with the [managedExecutorService](https://openliberty.io/docs/ref/config/#managedExecutorService.html) configuration element, or you can look up the default instance, which requires the `jndi-1.0` feature,
```
  ManagedExecutor executor = InitialContext.doLookup("java:comp/DefaultManagedExecutorService");
```

* If you are using the `cdi-2.0` feature, you can use application scoped CDI producers in combination with the builder pattern to help manage the life cycle of managed executors,
```
  // CDI qualifier which is used to identify the executor instance
  @Qualifier
  @Retention(RetentionPolicy.RUNTIME)
  @Target({ ElementType.FIELD, ElementType.METHOD, ElementType.PARAMETER })
  public @interface AppAndCDIContext {}

  // Example producer field, defined in a CDI bean,
  @Produces @ApplicationScoped @AppAndCDIContext
  ManagedExecutor appAndCDIContextExecutor = ManagedExecutor.builder()
      .propagated(ThreadContext.APPLICATION, ThreadContext.CDI)
      .build();

  // Example disposer method, also defined in the CDI bean,
  void disposeExecutor(@Disposes @AppAndCDIContext exec) {
      exec.shutdownNow();
  }

  // Example injection point, defined in a CDI bean,
  @Inject @AppAndCDIContext
  ManagedExecutor executor;
```

**Using a ManagedExecutor**

The [ManagedExecutor](https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ManagedExecutor.html) interface includes similar methods to [CompletableFuture](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletableFuture.html) for creating an initial stage.  This initial stage and all dependent stages that are created from it, and from those stages, and so forth, are backed by the `ManagedExecutor`, which provides thread context capture and propagation, as well as the ability to clear certain types of thread context, if so configured.  Beyond creation of the initial stage, usage of the `CompletionStage` and `CompletableFuture` API is no different than normal.  For example,

```
CompletableFuture<Integer> managedExecutor.supplyAsync(supplier)
    .thenApply(function1)
    .thenApply(function2)
    .thenApply(i -> {
        try {
            DataSource ds = InitialContext.doLookup("java:module/env/jdbc/ds1");
            ...
            return result;
        } catch (Exception x) {
           throw new CompletionExeption(x);
        }
    });
```

**Using a ThreadContext**

The [ThreadContext](https://openliberty.io/docs/ref/javadocs/microprofile-3.0-javadoc/org/eclipse/microprofile/context/ThreadContext.html) interface includes methods to pre-contextualize completion stage actions. This is useful when adding dependent stages to a completion stages that is not backed by a `ManagedExecutor` and would otherwise lack reliable thread context propagation. For example,

```
CompletableFuture<Long> stage = CompletableFuture.supplyAsync(supplier)
    .thenApply(function1)
    .thenApply(threadContext.contextualFunction(function2));
```

Thread context for the first two stages above (`supplier` and `function1`) is nondeterministic. Thread context for the stage that runs `function2`, however, is always captured from the thread that invoked `contextualFunction`, regardless of whether it runs on same thread, the thread of the `supplyAsync` method, a thread that forcibly completes the previous stage, or another thread which invokes an operations such as `get` or `join` which can trigger completion of stages.

**Propagation of CDI Context**

MicroProfile Context Propagation adds the concept of propagating CDI context with finer granularity than application scope. (Propagation of application scope is covered by ThreadContext.APPLICATION, which propagates the identity of the application and its components). With ThreadContext.CDI enabled, dependent stage actions can access any request scoped beans that you have already accessed within the request being propagated, as of the point in time when thread context is captured.

```
@Inject MyRequestScopedBean bean1;
@Inject OtherRequestScopedBean bean2;
@Produces @ApplicationScoped
ManagedExecutor executor = ManagedExecutor.builder().propagated(ThreadContext.CDI).build();
...
bean1.getHeight();
// bean2 is not accessed before this point
stage = executor.supplyAsync(() -> {
    if (useBean1)
        return bean1.getLength(); // bean1 is accessible while request remains active
    else
        return bean2.getWidth(); // causes stage to complete exceptionally
});
```

**Propagation of Transaction Context**

MicroProfile Context Propagation adds the ability to propagate JTA transaction context for serial use. This is an advanced capability and should only be used with caution and full awareness of its implications. By default, Open Liberty clears transaction context, which means that any transaction that might have been active on the thread is suspended for the duration of the completion stage action, allowing you to begin and end your own transactions within the implementation of your dependent stage actions.

If you have a scenario where you wish to include multiple completions stage actions within a single transaction, there are a number of considerations that you will need to be aware of. This includes guaranteeing that the transaction is rolled back if any of the stages fail, suspending the transaction from is original thread and enforcing serial usage of the transaction, determining if all of the enlisted resource types support usage across multiple threads, and considering connection pooling/sharing implications that could lead to extra resource consumption.

The following example shows a transaction that is started and later suspended from the main thread with its sole purpose being the capturing of its context. The transaction is suspended via an Open Liberty-specific transaction manager API.  The transactional operations occur at a future point in response to the completion of a triggering action.

```
ManagedExecutor executor = ManagedExecutor.builder()
    .propagated(ThreadContext.TRANSACTION, ThreadContext.APPLICATION)
    .build();
...
// Some example actions that perform simple transactional operations,
Function<Integer, Integer> actionA = numUpdates -> {
    try (Connection con = dataSource.getConnection(); Statement st = con.createStatement()) {
        return numUpdates + st.executeUpdate(sqlA);
    } catch (SQLException x) {
        throw new CompletionException(x);
    }
};
Function<Integer, Integer> actionB = numUpdates -> {
    try (Connection con = dataSource.getConnection(); Statement st = con.createStatement()) {
        return numUpdates + st.executeUpdate(sqlB);
    } catch (SQLException x) {
        throw new CompletionException(x);
    }
};
// This stage must not complete until the transaction is no longer active on the main thread.
CompletableFuture<Integer> initialStage = executor.newIncompleteFuture();
// Arrange for dependent stages to run under the transaction
tx.begin();
try {
    finalStage = initialStage.thenApply(actionA)
                             .thenApply(actionB)
                             .whenComplete((result, failure) -> {
        try {
            if (failure == null && tx.getStatus() == Status.STATUS_ACTIVE)
                tx.commit();
            else
                tx.rollback();
        } catch (Exception x) {
            if (failure == null)
                throw new CompletionException(x);
        }
    });
} finally {
    com.ibm.tx.jta.TransactionManagerFactory.getTransactionManager().suspend();
}
```

After this point, complete the initial stage from any thread to cause the dependent actions to run under the transaction:
```
initialStage.complete(0);
```

Once the executor is no longer needed:
```
executor.shutdown();
```

**Comment by lauracowen** [comment]
Don't have the section about 'configuring'. Instead, point users to the generated feature doc (which will have its own entry below here https://www.openliberty.io/docs/ref/feature/). Then say somewhere that the examples assume that the cdi and jndi features are included in the config (or something) if that's important to understand (can link to those features too if useful). If it's not important (or its blindingly obvious that you'd need to include those features in the examples), just don't mention it.

**Comment by njr-11** [comment]
> Don't have the section about 'configuring'. Instead, point users to the generated feature doc (which will have its own entry below here https://www.openliberty.io/docs/ref/feature/). Then say somewhere that the examples assume that the cdi and jndi features are included in the config (or something) if that's important to understand (can link to those features too if useful). If it's not important (or its blindingly obvious that you'd need to include those features in the examples), just don't mention it.

It isn't obvious that the jndi-1.0 feature would be needed for the examples to work.  I'm of the opposite opinion here, that it is extremely valuable to have examples that are fully copy&pastable for users.  If they need to figure something out, even if it's the combination of features to add, that's another obstacle to picking up the technology.  If we have the ability to tell them how to get an initial example working without any errors, then why not share that with the user.  It is much easier to start out with something working and then if you make changes from there and get errors, then you can isolate what caused it.  That said, if you want to overrule me on this, here is the link that will exist for the feature doc once it gets generated:
https://openliberty.io/docs/ref/feature/#mpContextPropagation-1.0.html

**Comment by lauracowen** [comment]
Then have that configuration example as part of the example. At the moment, it's presented as how to configure the feature, not as how to make the example work.

How commonly would the JNDI feature be used alongside the MP CP feature? If it's a common configuration that many users would need, we should provide it as a code example in the feature doc itself (like we have for JDBC here: https://www.openliberty.io/docs/ref/feature/#jdbc-4.3.html). Whether or not that is, are there any other common configurations we could/should provide like that for the MP CP feature?

**Comment by njr-11** [comment]
The difference is that the jdbc-4.3 example which you referenced doesn't actually utilize the jndi-1.0 feature at all, so the mention of it as a side-note vs in the config snippet is appropriate there.  The jdbc-4.3 code example runs cleanly without it.  But for the context propagation example, jndi-1.0 is specifically required for one of the code examples to work.

I'm fine with it the feature config being moved down to the example.

**Comment by dmuelle** [comment]
when this doc publishes, need to restore link to it in https://www.openliberty.io/docs/ref/general/#concurrency.html

**Comment by dmuelle** [comment]
Is this issue completed by Nathan's blog post?

**Comment by lauracowen** [comment]
Ultimately, we should move the blog post into being a doc topic (with some editing if nec) and redirect the blog post URL to it - I just published it as a post because of the release but also because it's easier to share online and we can submit it to the MicroProfile.io blog syndicator for greater audience.

I think we should leave it as a post for now but keep this issue to address in, say, a few weeks time. I'll move it back to the backlog lower down. Unless you want to prepare the doc topic for publishing and then we'll do the actual publish and redirect later?

**Comment by dmuelle** [comment]
I'll hang on to this issue- once we have a pipeline for when the content should be published it wont take long to edit and transfer to the ref/general docs- maybe with 19009/10?

**Comment by lauracowen** [comment]
Okay, let's aim at publishing the article (and redirecting the blog post) at some time during the 19.0.0.10 release (ie sometime in Sept). I've changed the milestone label.

**Comment by dmuelle** [comment]
New draft adapting @njr-11 blog post for a ref/gen topic:

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#context-propagation.html

**Comment by dmuelle** [comment]
Updated draft addressing @lauracowen edit requests

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microprofile-context-propagation.html

**Comment by dmuelle** [comment]
Updated doc is now live at https://www.openliberty.io/docs/ref/general/#microprofile-context-propagation.html
