### ISSUE TITLE
Update "Metrics reference list" with information on filtering PMI data (for perf).

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/docs#4762]
Document: Metrics reference list
http://openliberty.io/docs/21.0.0.6/metrics-list.html

FROM:
MicroProfile Metrics 2.3 explicitly enables the feature:monitor-1.0[display=Performance Monitoring] feature.
If you use a version earlier than 2.3 of the MicroProfile Metrics feature, then you must also enable the Performance Monitoring feature.

TO:
When using MicroProfile Metrics with the feature:monitor-1.0[display=Performance Monitoring] feature you will enable the reporting of _vendor_ metrics on the `/metrics` endpoint. Prior to MicroProfile Metrics 2.3, the Performance Monitoring feature (`monitor-1.0`) will need to be explicitly configured. In MicroProfile Metrics 2.3 and up the `monitor-1.0` feature will be automatically enabled by the MicroProfile Metrics feature during startup. It is worth noting that the _REST base metrics_ introduced in MicroProfile Metrics 2.3 also relies on the feature:monitor-1.0[display=Performance Monitoring] to function.

The feature:monitor-1.0[display=Performance Monitoring] feature retrieves statistical data from all available monitoring components. However, MicroProfile Metrics only uses a subset of those components.
The latest release of MicroProfile Metrics sources data from the following monitoring components: ConnectionPool, ThreadPool, RequestTiming, Session, WebContainer, REST, GrpcClient, GrpcServer. You can identify with which MicroProfile Metrics release the associated metrics are offered in by identifying the relevant metric in the table below and the version it was introduced in. For example the Request Timing vendor metrics were introduced in MicroProfile Metrics 2.0.

Note: The superset of monitoring components also include: JVM, SIPContainerBasic, SIPContainerInboundRequests, SIPContainerInboundResponse, SIPContainerOutboundRequests, SIPContainerOutboundResponse, SIPContainerQueueMonitor, SIPContainerTaskDuration.

By default, all monitoring components are enabled. You can configure the exact monitoring components to be enabled by configuring the`server.xml` with the `filter` attribute for the `monitor` configuration element.

To enable only the monitoring components used by MicroProfile Metrics you can configure the `server.xml` like this:
```
<monitor  filter="ConnectionPool,ThreadPool,RequestTiming,Session,WebContainer,REST,GrpcClient,GrpcServer"/>
```

Note: Jaxws vendor metrics can not be filtered and will always be available.

To disable all _vendor metrics_, but to keep the REST _base metrics_ configure the `server.xml` like this:
```
<monitor  filter="REST"/>
```

To disable all monitoring components you can configure the `server.xml` like this:

```
<monitor  filter=" "/>
```

**Comment by dmuelle** [comment]
slack comment from @Channyboy

"...was discussing with someone (peformance guy) and decided it was best to add that additional info on on being able to tune the amount of data being processed (for the sake of performance) You've always been able to do that, it's just not documented."

**Comment by dmuelle** [comment]
Hi @Channyboy - we have a few questions. Hoping to streamline the info a bit and also provide a little more context. 

- this draft refers to "monitoring components", but[ the config doc for the filter attribute](https://openliberty.io/docs/21.0.0.10/reference/config/monitor.html) says:

> Allows user to enable/disable monitors based on group name such as WebContainer,JVM,ThreadPool,Session,ConnectionPool and so on.

Should they be referred to as "components" or "group names"? Are these groups/components documented anywhere else? Is there a categorical way to associate a given metric with its group/component?


- the table description on this page says 
> The table also lists the metric types, metric units, and descriptions of _all metrics that are available for Open Liberty_. 

But I don't see any metrics to associate with some of the components in the superset- eg `SIPContainerBasic` (or any SIP metrics). Is the statement incorrect or is the table incomplete?

**Comment by Channyboy** [comment]
@dmuelle 

> Should they be referred to as "components" or "group names"? Are these groups/components documented anywhere else? Is there a categorical way to associate a given metric with its group/component?

I suppose component does sound better!
Unfortunately I don't think they're documented anywhere. I think the KC _does sort of_ list it _somewhere_, but that is out of date most likely. These components I sourced from looking through the codebase to find the appropriate annotations in the build files. 
The "way" so far seems to just match the names up to the relevant component (i.e. session component has the word "session" in it).

> But I don't see any metrics to associate with some of the components in the superset- eg SIPContainerBasic (or any SIP metrics). Is the statement incorrect or is the table incomplete?

Right, so I had a little bit of trouble explaining that one.
The metrics that are sourced from the monitoring "components" is just a subset. Metrics doesn't provide metrics from all of these components.  The monitoring data from SIP was never offered as metrics.

Maybe the complexities above was a reason why we never decided to explain it until somebody explicitly asked us to :b

**Comment by dmuelle** [comment]
Thanks @Channyboy - looking at this, I think the _least_ confusing option is to add a column to the metrics table for `Monitoring component` to list the component that is associated with each group of metrics. 

Then all we have to do is explain they can filter to include only certain metric groups by component and point them to the table for the values they need to filter on. We can still provide the brief config examples but they will be easier to follow because we won't have to rattle off a bunch of component names up front and people can just grab and go w/ what they need.

Most of the component names you listed are easy to map- however there are some metrics in the table that are hard to match to a component. Can you help us fill in the blanks?

 - ConnectionPool = connectionpool.connectionHandles, etc
 - ThreadPool = threadpool.activeThreads, etc.
 -  RequestTiming = requestTiming.activeRequestCount, etc
 -  Session = session.activeSessions ,etc
 -  REST = REST.request, etc
 -  GrpcClient = grpc.client.receivedMessages.total, etc
 -  GrpcServer = grpc.server.receivedMessages.total, etc
 - JVM = jvm.uptime (?) 
 -  WebContainer =  **??**
 - **??** = classloader. metrics
 - **??** = cpu metrics
 - **??** = ft. (fault tolerance) metrics
 - **??** = gc metrics
 - **??** = jaxws.server metrics
 - **??** = jaxws.client metrics
 - **??** = memory metrics
 - **??** = servlet metrics
 - **??** = Thread metrics

**Comment by Channyboy** [comment]
Base metrics do not rely on the monitoring component/feature to get data, except for REST metrics which does rely on the monitoring componenet/feature.

Vendor metrics completely rely on the monitoring component/feature. **HOWEVER**, the jaxws metrics can't seem to be filtered, they have no associated monitoring component, but just seem to exist :(. I couldn't find the component for it and did some testing and It seems the code that registers the relevant Mbeans aren't the typical way so I guess it has some backdoor access :S

----
JVM = jvm.uptime (?) <- yes

?? = classloader. metrics - _Base metric, no monitoring component associated., will always be available._
?? = cpu metrics - _Base metric, no monitoring componenet associated, will always be available._

?? = ft. (fault tolerance) metrics - _Base metric, is available when MP Fault Tolerance feature is enabled._

?? = gc metrics - _Base metric, no monitoring component associated., will always be available._
?? = jaxws.server metrics - _no associated monitoring componenet, will always be available._
?? = jaxws.client metrics  - _no associated monitoring componenet, will always be available._
?? = memory metrics - _Base metric, no monitoring component associated., will always be available._
**(WebContainer)** = **servlet metrics**
?? = Thread metrics - _Base metric, no monitoring component associated., will always be available._

**Comment by dmuelle** [comment]
This is indeed confusing but is making more sense now :) 

just trying to figure out the best way to elide some of the complexity for the user

In general, is there a definition of base metrics vs vendor metrics other than base are what's collected by MPM and vendor are what comes from Perf monitor? ie is there anything about a vendor metric that makes it "vendor" other than it's collected by the `monitor` associated components?

**Comment by Channyboy** [comment]
@dmuelle 

`Base metrics` are metrics that the provider (i.e. OpenLiberty or another platform/implementation) has to provide. With the exception of the REST metrics. Those are base metrics but are "optional" for a provider to provide.

 `Vendor metrics` are metrics that provider/implementation feels like providing. So for us, we took the data from the `monitor-1.0` and re-reported them as metrics with mpMetrics. These are completely optional, a provider/implementation does not need to provide any vendor metrics at all.
Metrics that developer instruments in their own code is `application metrics`

**Comment by ramkumar-k-9286** [comment]
@dmuelle David,

The draft version of the doc:
https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html

**Comment by dmuelle** [comment]
@ramkumar-k-9286 

- dont use backtics for "vendor"
- provide links to the MicroProfile Metrics and Performance Monitor feature pages on first mention- use versionless feature macro syntax
- suggested edit to combine these sentences into fewer paragraphs and change their order slightly (include links, monospace as needed):

"When the MicroProfile metrics feature is enabled, a set of base metrics are always reported. You can augment this set of metrics by collecting vendor metrics, which are available from different monitoring components within your Open Liberty server. When you enable both the Performance Monitoring and the MicroProfile metrics features, you enable the reporting of vendor metrics on the /metrics endpoint. The Performance Monitoring feature retrieves the statistical data from all available monitoring components.

Before MicroProfile Metrics 2.3, the Performance Monitoring feature had to be explicitly configured. From MicroProfile Metrics 2.3, the Performance Monitoring feature is automatically enabled by MicroProfile Metrics during startup. The REST base metrics that were introduced in MicroProfile Metrics 2.3 also rely on the Performance Monitoring feature.

By default, all monitoring components are enabled. You can configure only a subset of these monitoring components to be reported by specifying the filter attribute for the monitor configuration element in your server.xml file. If your server is collecting more metrics data than you need, you can improve the server performance by collecting only those metrics that you intend to use. You can identify the relevant monitoring component for each metric by referencing the Metrics that are available for Open Liberty table."


- Remove this sentence, it doesn't tell you anything that isn't already in the table:
> You can identify the relevant metric associated with the MicroProfile Metrics release in the Metrics that are available for Open Liberty table, and the version it was introduced in. For example, the Request Timing vendor metrics were introduced in MicroProfile Metrics 2.0.
- the backticks on "server.xml" before the first example need fixing
- add the following info
The table also lists the metric types, metric units, and descriptions of all metrics that are available for Open Liberty
--->
The table also lists the metric types, metric units, and descriptions of all metrics that are available for Open Liberty. For the vendor metrics, the associated monitoring component that you can use to filter the metric is also included. 

- add monospace to all the monitoring components in the table. Don't monospace  "Base metric" or "N/A" fields

**Comment by ramkumar-k-9286** [comment]
@dmuelle

All the review comments specified above have been incorporated.

Proceeding to Merge the PR. Will share the draft link for review.

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

The review comments have been incorporated. Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
>  When the MicroProfile metrics feature is enabled, a set of base metrics are always reported

--->
When the MicroProfile metrics feature is enabled, a set of base metrics is always reported.


> When you enable both the Performance Monitoring and the MicroProfile metrics features

 `MicroProfile metrics` is in monospace, but should be a link to the feature page. Throughout the page, don't monospace feature names- only feature short names should be in monospace


> _REST base metrics_ that were introduced...

---> `REST` base metrics that were introduced...


> the monitor configuration element 

---> the `monitor` configuration element 


>  file.If your server

add a space after period


>  by referencing the Metrics that are available for Open Liberty table

link table name to table


>  all _vendor metrics_, but to keep the REST _base metrics_

remove italics


> To disable all monitoring components you can configure the server.xml like this:

--->
To disable all monitoring components, add the following code to your `server.xml` file:


>  The last column of the table includes the feature or features that must be enabled to obtain that metric data.

--->
 The **Features required** of the table includes the feature or features that must be enabled to obtain that metric data.


Change the column name: Feature(s) required--->Features required


add the following sentence to the end of the table intro:
The **Version introduced** column specifies the minimum versiuon of the feature that you must enable to collect the metric.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The review comments specified above were incorporated. Proceeding to Merge the PR.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The review comments specified above were incorporated. Proceeding to Merge the PR.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, except for one small change. For the link text on the table link:

Metrics that are available for Open Liberty [table].
--->
[Metrics that are available for Open Liberty] table.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The comments specified above were incorporated. Proceeding to Merge the PR.

Link to the draft version of the document:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, I think this is ready for technical review from @Channyboy

**Comment by ramkumar-k-9286** [comment]
Hi David @Channyboy

Please find below the draft links for the requested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html

Please review the same. If the section has turned out as expected, please add the `Technical reviewed` label.

In case changes are needed please add your comments to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by Channyboy** [comment]
Looks good!
Sounds a lot more fluid and digestible than what I tried to write out earlier :b

**Comment by dmuelle** [comment]
# peer review

The topic looks good. I just have few minor suggestions. I think some of the sentences can be reorganized to improve the flow of information.

I think paragraphs 3 & 4 can be combined into a single paragraph, with a slightly different sentence order:

`When the MicroProfile metrics feature is enabled, a set of base metrics is always reported. You can augment this set of metrics by collecting vendor metrics, which are available from different monitoring components within your Open Liberty server. When you enable both the Performance Monitoring and the MicroProfile metrics features, you enable the reporting of vendor metrics on the /metrics endpoint. The Performance Monitoring feature retrieves the statistical data from all available monitoring components.`

`Before MicroProfile Metrics 2.3, the Performance Monitoring feature had to be explicitly configured. From MicroProfile Metrics 2.3, the Performance Monitoring feature is automatically enabled by MicroProfile Metrics during startup. The REST base metrics that were introduced in MicroProfile Metrics 2.3 also rely on the Performance Monitoring feature.`

---->

`When the MicroProfile metrics feature is enabled, a set of base metrics is always reported. You can augment this set of metrics by collecting vendor metrics, which are available from different monitoring components within your Open Liberty server. When you enable both the Performance Monitoring and the MicroProfile metrics features, you enable the reporting of vendor metrics on the /metrics endpoint. The Performance Monitoring feature retrieves the statistical data from all available monitoring components. The REST base metrics that were introduced in MicroProfile Metrics 2.3 also rely on the Performance Monitoring feature. Before MicroProfile Metrics 2.3, the Performance Monitoring feature had to be explicitly configured. In MicroProfile Metrics 2.3, and later, the Performance Monitoring feature is automatically enabled by MicroProfile Metrics during startup.`

a few more minor adjustments to the next paragraph:

`By default, all monitoring components are enabled. You can configure only a subset of these monitoring components to be reported by specifying the filter attribute for the monitor configuration element in your server.xml file. If your server is collecting more metrics data than you need, you can improve the server performance by collecting only those metrics that you intend to use. You can identify the relevant monitoring component for each metric by referencing the Metrics that are available for Open Liberty table.`

--->

`By default, all monitoring components are enabled. If your server is collecting more metrics data than you need, you can improve the server performance by collecting only those vendor metrics that you intend to use. To configure only a subset of vendor metrics to be reported, specify the components that you want to monitor in the filter attribute for the monitor configuration element in your server.xml file. You can identify the relevant monitoring component for each vendor metric by referencing the **Monitoring component** column of the Metrics that are available for Open Liberty table.`


Feel free to copy these suggestions if you agree but be careful not to lose the text and link formatting from your draft as I haven't recreated it here.

**Comment by ramkumar-k-9286** [comment]
David @dmuelle 

I have incorporated the Peer Review comments. Re-organized the content in para 3, 4 &5 as suggested.

Please find below the draft site links for the requested changes:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/metrics-list.html


Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, thanks

**Comment by dmuelle** [comment]
content is now on vNext and will publish with 21.0.0.12
