### ISSUE TITLE
Create a "REST alternatives" section

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/docs#4848]
Currently, we only have "RESTful services" section in our doc.  We need to add a section for "REST alternatives" (after RESTful services) which would cover items such as: graphQL, websockets, gRPC.

We have already added this section to [guides](https://staging-openlibertyio.mybluemix.net/guides/#rest_alternatives).

@andymc12 would be the SME this content.  We can also likely pull some content from previous blogs that have covered these topics.

**Comment by dmuelle** [comment]
REST alternative section on draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/rest-alternatives.html

Section includes:

- landing page
- graphQL topic
- gRPC topic
- WebSocket topic
- link to REST alternative guides

**Comment by dmuelle** [comment]
content is on vNext and will publish with 23.0.0.4- closing as completed

**Comment by mbroz2** [comment]
Should the "to" in "might be better suited to some application scenarios." be instead "for" or "in"?

I'd advocate for 'Alternatives to REST' to come after 'RESTful services' in the ToC, not at the bottom.

I believe in all sections other then this one and Observability, we reference other sections using "See Also" rather then a list of direct child objects.  I always thought this was to avoid having 'overview' pages for the sake of having 'overview' pages.
How does ID decide which style to use for which content?

**Comment by dmuelle** [comment]
Thanks, @mbroz2 - I made the suggested edit and moved the section to be directly after 'RESTful services' in the ToC. As we discussed via slack, the list of summarized topics only appears on parent pages that do not otherwise have substantial content.

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/rest-alternatives.html
