### ISSUE TITLE
MicroProfile Rest Client 3.0 Docs

### ISSUE THREAD

**Issue by andymc12** [OpenLiberty/docs#4855]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

This issue is still somewhat of a work in progress as we discover behavior changes.  Like Jakarta REST (JAX-RS) 3.0, MP Rest Client 3.0 is moving to RESTEasy (from CXF), so there is likely to be some migration issues that may need to be documented - many of which may already be documented under changes to the JAX-RS 3.0 Client docs (see #4825).

Like other MP 5.0 features, the dependencies have changed from EE 8 to EE 9.1 (`javax.*` package to `jakarta.*`), but there should not be any other changes to the API.

This issue is required for epic issue https://github.com/OpenLiberty/open-liberty/issues/17947.

**Comment by dmuelle** [comment]
HI Andy- I suspect the package name changes will be covered in the autogenerated doc as we generally don't document the packages in the manually written docs except in special cases where a user would need more info than what's in the javadoc/ generated doc. In this case I think we'd want to doc

- any breaking changes?
  - if they are the same as what will be documented in  #4825, we could just add a statement to the [REST clients topic](https://www.openliberty.io/docs/21.0.0.11/rest-clients.html) and point to the JAX-RS differences topic
- Is the REST clients topic still up to date? Any behavior changes we should document. For instance, I noticed on that page we currently document that `Publisher` was became an async return type with MPRC 2.0. So any details that would enhance simplify  the capabilities would be good to capture. 
 - So far, we haven't documented the underlying implementation of MPRC but if that is a detail the user is likely to need in order to use the feature we can add some info

**Comment by andymc12** [comment]
Hi @dmuelle - I'm still investigating the behavior changes in the MP Rest Client between CXF and RESTEasy, but I found one that I wanted to mention before I forget:
Per the [JAX-RS integration section](https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#_jax_rs) in the MP Rest Client spec, it is _optional_ whether `@Context` injection is performed  in `ClientHeadersFactory` instances.  CXF performed this injection, but RESTEasy does not.  Since `@Context` is planning to be removed in JAX-RS 4.0, I don't think RESTEasy will ever support it, so we should document that code like this (that would have worked in MP Rest Client 2.0) will fail in MP Rest Client 3.0:
```
public class CustomClientHeadersFactory implements ClientHeadersFactory {
    @Context
    private UriInfo uriInfo;

    @Override
    public MultivaluedMap<String, String> update(MultivaluedMap<String, String> incomingHeaders,
                                                 MultivaluedMap<String, String> clientOutgoingHeaders) {
        MultivaluedMap<String, String> myHeaders = new MultivaluedHashMap<>();
        URI uri = uriInfo.getAbsolutePath(); // this will throw a NullPointerException in mpRestClient-3.0
        myHeaders.putSingle("INJECTED_URI_INFO", uri == null ? "null" : uri.toString());
        return myHeaders;   
    }
}
```

**Comment by dmuelle** [comment]
Hi Andy, just circling back on this- is there any new information we need to document other than what you have in the previous comment?

**Comment by andymc12** [comment]
Hi @dmuelle - sorry for the slow reply.

Other than what has been mentioned above there are two other behavior changes that should be documented:

1) The MP Fault Tolerance annotation, `@Timeout` will not behave the same when placed on synchronous rest client interface methods in Liberty's MP Rest Client 3.0 implementation as it did in the 2.0 implementation.  The older implementation essentially read the value in the `@Timeout` annotation and automatically configured the rest client's connect and read timeout values to match it - essentially, the rest client configured itself using the MP Fault Tolerance annotation.  This is no longer the case in the MP Rest Client 3.0 implementation - instead, if users want their synchronous rest client methods to time out at a certain time, they will need to use MP Rest Client timeouts (which are already documented).  Note that the `@Timeout` annotation will still work the same for asynchronous rest client methods.

2) If a user packages CDI interceptors and binds them to a rest client interface, the interceptor(s) must be enabled using `@Priority`, whereas in previous versions of MP the user could also enable them using the `beans.xml` file. 

If you have any questions on these (or would like code examples, etc.), please let me know.  Thanks!

**Comment by dmuelle** [comment]
Thanks Andy- I think we could cover this info in a "Behavior changes..." doc that is linked from the REST clients doc and feature page.

As far as examples, for your comment from 11/4- the example you provided shows what will no longer work in 3.0- would it be helpful to show how you could replace this code to get it to work?

In the previous comment

1. where are MP REST client timeouts documented? I'm not finding anything in our docs or guides
2. Can we provide an example for enabling interceptors with `@Priority`?

**Comment by andymc12** [comment]
Hi David,

There isn't a good way to replace the code from 11/4. Basically the user would need to provide their own method of getting the context information in the provider class...

One approach would be that the user could register a `ClientRequestFilter` and then obtain things like the URI, etc by getting them from the passed-in `ClientRequestContext` object - then store those objects in a `ThreadLocal` that could be read in the `CustomClientHeadersFactory` class.  

It's definitely not ideal, but it should be better in future versions.

> 1. where are MP REST client timeouts documented? I'm not finding anything in our docs or guides

Yeah, I thought that we had documented the Rest Client timeouts, but I agree that they are not in the Open Liberty guides or docs.  It is documented in the spec at https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/microprofile-rest-client-spec-3.0.html#mpconfig (for using MP Config) and https://download.eclipse.org/microprofile/microprofile-rest-client-3.0/apidocs/ (see connectTimeout and readTimeout methods - for programmatic configuration).

FWIW, it might be good to add one of those approaches to the MP Rest Client guide at: https://openliberty.io/guides/microprofile-rest-client.html#building-the-client-with-restclientbuilder

> 2. Can we provide an example for enabling interceptors with @Priority?

Yes, the changes in PR https://github.com/OpenLiberty/open-liberty/pull/19610 show how to do this.  Basically, the user would just need to add the `@Priority` annotation to their interceptor class - something like this:
```
@Loggable
@Interceptor
@Priority(10) // <-- the 10 is arbitrary but is used to determine the order in which interceptors are invoked if there are more than one.
// I believe the order is from highest to lowest (i.e. an interceptor with @Priority(11) would be invoked before this one)
//- but you'd want to confirm that with somebody from the CDI team - like Emily J/Tom E/Andrew R/Benjamin C/etc)
public class LoggableInterceptor { //...
```

**Comment by dmuelle** [comment]
Thanks Andy, I'll send the draft when I have it ready

**Comment by dmuelle** [comment]
Hi @andymc12 - here is the initial draft for the MPRC 3.0 behavior changes doc:

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/mprc-dif.html

Let me know what changes are needed. Thanks!

**Comment by andymc12** [comment]
Hi @dmuelle, I think this doc looks great.  Only one suggestion:

In the `@Timeout` section, can we change this sentence:
> Instead, to configure your synchronous REST client methods to time out at a certain time, you must configure MicroProfile REST Client timeouts with MicroProfile Config.

to something like:
> Instead, to configure your synchronous REST client methods to time out at a certain time, you must use the `RestClientBuilder#connectionTimeout` and/or `RestClientBuilder#readTimeout` APIs or configure the timeouts with MicroProfile Config.

That way, it includes the programmatic approach to setting the timeouts.

Thanks so much!

**Comment by dmuelle** [comment]
Hi @andymc12, I've updated the draft with that change:

https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/mprc-dif.html

If you see anything else that needs a fix just let me know. Otherwise, you can sign off by adding the `technical reviewed` label to this issue and the doc will publish with 22.0.0.1. Thanks!

**Comment by andymc12** [comment]
Hi @dmuelle - it looks good to me!  Thanks again!

**Comment by ramkumar-k-9286** [comment]
# Peer Review

With the release of the MicroProfile REST Client 3.0 feature (mpRestClient-3.0), the underlying MicroProfile REST Client implementation for Open Liberty **changed** from Apache CXF to RESTEasy.
--->
With the release of the MicroProfile REST Client 3.0 feature (mpRestClient-3.0), the underlying MicroProfile REST Client implementation for Open Liberty **changes** from Apache CXF to RESTEasy.

In MicroProfile REST Client 3.0 and later, Open Liberty does not support the `@Context` annotation as a portable injection mechanism in `ClientHeadersFactory` instances. 
--->
In MicroProfile REST Client 3.0 and later, Open Liberty does not support the `@Context` annotation as a portable injection mechanism in **the** `ClientHeadersFactory` instances. 

Code similar to the following example worked with MicroProfile REST client 2.0, but fails in version 3.0.
--->
Code similar to the following example **works** with MicroProfile REST client 2.0 but fails **with** version 3.0.

In MicroProfile REST client 2.0 and earlier, you could use `@Timeout` annotation to set timeouts for synchronous REST client interface methods.
--->
In MicroProfile REST client 2.0 and earlier, you **might** use `@Timeout` annotation to set timeouts for synchronous REST client interface methods.

This configuration is not valid in the MP Rest Client 3.0 implementation
--->
Do we use short forms like MP Rest Client - Not sure.

In this example, the `10` is a sample value that determines the order in which interceptors are invoked when more than one exists.
--->
In this example, the `10` is a sample value that determines the order in which **the** interceptors are invoked when more than one exists.

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 all suggestions are incorporated in[ the updated draft](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/mprc-dif.html) except for the following:

- In MicroProfile REST Client 3.0 and later, Open Liberty does not support the @Context annotation as a portable injection mechanism in the ClientHeadersFactory instances.
- In this example, the 10 is a sample value that determines the order in which the interceptors are invoked when more than one exists.

In both these sentences, the noun clause refers to a general instance rather than a specific instance, so "the" isn't needed. "The" is used to refer to a specific or particular member of a group. For more info, see [Using Articles](https://owl.purdue.edu/owl/general_writing/grammar/using_articles.html).


- In MicroProfile REST client 2.0 and earlier, you might use @Timeout annotation to set timeouts for synchronous REST client interface methods.
"Could" doesn't violate Acrolinx guidance in this case, which permits it for "the past conditional form"

**Comment by ramkumar-k-9286** [comment]
LGTM - Adding the `Peer Reviewed` label.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Topic is on vNExt and will publish with 22.0.0.1 on 1/18. Closing this issue
