### ISSUE TITLE
Documentation updates for Jakarta EE 9

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/docs#4863]
As part of https://github.com/OpenLiberty/open-liberty/issues/9876 , the documentation needs to be updated to include some information about Jakarta EE 9.

Part of the documentation updates should include some information about differences with Jakarta EE 9 and what customers need to know in order to transition to Jakarta EE 9.  Some of this is documented in the Jakarta Enterprise Beans and RESTful Web Services Epics for changes with those features.

Key things that should be added / updated for Jakarta EE 9 include new feature and API jars and package versions in those API jars.  I know there is some work done to document the updated feature names in the Jakarta / Java EE technology sections already.  I believe you also were looking at giving some more details information to customers on how to use the transformer in order to update their applications to work with Jakarta EE 9.

21.0.0.12 is the release that we are planning to have Jakarta EE 9 support go to GA, so that is the release we would target for these documentation updates.

**Comment by dmuelle** [comment]
Hi @jhanders34 - we also have this overlapping issue to provide a reference table and information about the differences: https://github.com/OpenLiberty/docs/issues/4626

Not sure if what is there already and in #4855 & #4825 cover what we're looking for.

I believe the updates for "new feature and API jars and package versions in those API jars" will be covered in the generated doc, though we can address any gaps there in the manual documentation.

I thin k the best way to track everything would be to convert this issue to a docs Epic and then associate the related issues with it.

**Comment by dmuelle** [comment]
Also tracking updates for the EE 9.1 Javadoc and generated docs under this issue

**Comment by dmuelle** [comment]
all docs in this epic are published, as are the EE9.1 Javadoc and feature updates.
