### ISSUE TITLE
Only add a couple of lines to say namespace update

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/docs#4879]
Add a couple of line is to be added to the doc regarding javax to jakarta namespace update

**Comment by Emily-Jiang** [comment]
MicroProfile 5.0 aligns with Jakarta EE 9.1. With this release, applications can use MicroProfile APIs together with Jakarta EE 9.1 APIs. MicroProfile 5.0 has the same functionalities as MicroProfile 4.1 except the depeendency update from javax.* to jakarta.*.

**Comment by chirp1** [comment]
Epic is at https://github.com/OpenLiberty/open-liberty/issues/16991

**Comment by dmuelle** [comment]
Also need to update MP javadoc for 5.1, will track as part of this issue

**Comment by dmuelle** [comment]
Hi @Emily-Jiang - I've added the following statement to both the [MicroProfile 5.0 feature page](https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/microProfile-5.0.html) and the [MicroProfile overview](https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile.html).

> MicroProfile 5.0 aligns with Jakarta EE 9.1. With this release, applications can use MicroProfile APIs together with Jakarta EE 9.1 APIs. MicroProfile 5.0 has the same functions as MicroProfile 4.1 except for dependency updates that account for changes in Jakarta API package names from javax.* to jakarta.*.

If any further edits are needed, let me know. If not, you can sign off by adding the `Technical reviewed` label to this issue and the update will publish with the 22.0.0.1 docs release on 1/18. Thanks!

**Comment by Emily-Jiang** [comment]
Looks good @dmuelle ! thanks

**Comment by dmuelle** [comment]
topic is on Vnext and will publish with 22.0.0.1
