### ISSUE TITLE
Docs update for server JVM working directory

### ISSUE THREAD

**Issue by hlhoots** [OpenLiberty/docs#4880]
Hi.  I am adding a new environment variable as part of https://github.com/OpenLiberty/open-liberty/issues/15128.  I am opening this issue to track the ID changes needed for that which I believe should go into this location for OL: https://openliberty.io/docs/21.0.0.11/reference/default-environment-variables.html

Environment variable:SERVER_WORKING_DIR
Description: The directory containing output files from the JVM used by the server.  For example the javadump files.  The default value is the location ${WLP_OUTPUT_DIR}/serverName. If set with an absolute path (ex, C:\logs or /logs), that location will be utilized, else if a relative path (ex, logs, or logs\javadumps\) is set, it will be a path relative to the default location.

Target date is now 22.0.0.1

**Comment by hlhoots** [comment]
@dmuelle I modified the Description text above based on a design change did.  Also the target date is now 22.0.0.1 which I see you have marked as the milestone.  Thanks!

**Comment by dmuelle** [comment]
Hi @hlhoots - here is the draft for this update:

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/default-environment-variables.html

Let me know if any further edits are needed. If not, you can add the `Technical Reviewed` label to this issue and the changes will publish with 22.0.0.1. Thanks!

**Comment by hlhoots** [comment]
@dmuelle Draft write up looks good to me.

**Comment by ramkumar-k-9286** [comment]
# Peer Review

The ${wlp.install.dir} configuration variable has an inferred location that is set to the parent of the directory that contains the launch script.
--->
The `${wlp.install.dir}` configuration variable has an inferred location that is set to the parent of the directory that contains the launch script. 
(Not sure if this needs to be in monospace, confused as it is mentioned as a variable)

Whether to allow remote debugging or not. This variable can be set to `y` to allow remote debugging. 
--->
Whether to allow remote debugging or not. This variable can be set to `Y` to allow remote debugging.
(Not sure if this has any relevance, but should `y` be in caps `Y`)

The port to use when running the server in debug mode. The default value is `7777`.
--->
The port to use **for** running the server in debug mode. The default value is `7777`.

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 , all suggestions incorporated in [the updated draft ](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/default-environment-variables.html)except for the following:

- Not sure if this has any relevance, but should y be in caps Y

No- the value would be specified lowercase, only the ENV variable is all caps

**Comment by ramkumar-k-9286** [comment]
LGTM - Adding the `Peer Reviewed` label.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Topic is on vNExt and will publish with 22.0.0.1 on 1/18. Closing this issue
