### ISSUE TITLE
Document JVM_ARGS on Default environmental variables page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4910]
on the [Default environmental variables page](https://www.openliberty.io/docs/21.0.0.11/reference/default-environment-variables.html), all the env variables from the `wlp/bin/server.bat` file are documented except JVM_ARGS. We need to add it to the table. Here's the defintion from the .bat file

JVM_ARGS   - A list of JVM command line options,             
              e.g. system properties or -X parameters
             The value will be expanded by cmd.exe (use quotes for spaces)
             
check with an SME- probably @cbridgha - to make sure we should document it and also provide just a little more context as to what it is for/ why you'd use it.

**Comment by dmuelle** [comment]
use `4880-ENV` branch to edit the env variable doc

**Comment by ramkumar-k-9286** [comment]
**Conversation with Chuck Bridgham ( For Reference)**
___
**Ramkumar K**
Hi Chuck. I had another question regarding an issue I needed to document (edited) 
on the [Default environmental variables](https://www.openliberty.io/docs/21.0.0.11/reference/default-environment-variables.html) page, all the env variables from the `wlp/bin/server.bat` file are documented except `JVM_ARGS`.
should we be documenting `JVM_ARGS`?
also could you please provide just a little more context as to what it is for/ why you’d use it.

**Chuck Bridgham**
no the `JVM_ARGS` are defined in the `jvm.options` file….  here is a doc explaining: [https://www.ibm.com/docs/en/was-liberty/base?topic=manually-customizing-liberty-environment]()
couldn’t find that info on the OL docs….
might be missing

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

The suggested changes have been made to the document.

Draft page link: https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/default-environment-variables.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
suggested edit:

The list of JVM command line options like system properties or -X parameters. The value is expanded by cmd.exe and quotations are used to enclose space in values.
--->
A list of command-line options, such as system properties or -X parameters, that are passed to the JVM when the server starts. Any values that contain spaces must be enclosed in quotes.


I think we should avoid cmd.exe as it is windows specific

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Corrections made as per request.

Draft page link: https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/default-environment-variables.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- you can send it to staging

**Comment by ramkumar-k-9286** [comment]
Send to Staging.

**Comment by dmuelle** [comment]
Topic is on vNExt and will publish with 22.0.0.1 on 1/18. Closing this issue
