### ISSUE TITLE
Docs to cover the use of podman/buildah

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/docs#4917]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

Wherever we describe the use of the Docker(e.g. to build or run application images based on our Liberty container images), we should generalize and describe how one works with "container images" vs "Docker images". Use of the docker CLI should be accompanied by equivalent description of usage using podman/buildah.

Should review what we have in the existing docs and work out the relevant and necessary updates.  @leochr and team can provide additional guidance and insights.

**Comment by yeekangc** [comment]
Cc @chirp1 @dmuelle

**Comment by dmuelle** [comment]
the following files contain references to "Docker" that should updated to "container". Several topics container Docker CLI examples that should be updated to include OS alternatives

- [x] integration-testing.adoc

- [x]  security-hardening.adoc & server-configuration-hardening.adoc 

- [x] relational-database-connections-JDBC.adoc (added podman examples)

- [x] log-trace-configuration.adoc (added podman examples)

- [x] cloud-native-microservices.adoc

- [x] development-mode.adoc

- [x] logstash-events-list.adoc (added podman examples)

- [x] springbootUtility-thin.adoc

- [x] server-package.adoc

**Comment by dmuelle** [comment]
- [True-to-production integration testing](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/integration-testing.html)
Replaced references to "Docker" with "container" 
- [ Server configuration security hardening](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/server-configuration-hardening.html#ol-images)
Per conversation with @leochr, replaced references to "Docker" and "Docker Hub" with "container" and "official container registries and provided a link to the OL image GitHub, which links to those registries
- [Relational database connections with JDBC](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/relational-database-connections-JDBC.html#_common_data_source_configuration_examples)
Provided Podman alternatives for all Docker CLI examples
- Log and trace configuration: [Container image logging configuration](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/log-trace-configuration.html#container)
Provided Podman alternatives for all Docker CLI examples and replaced references to "Docker" with "container" 
- [Cloud-native microservices](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/cloud-native-microservices.html)
replaced references to "Docker" with "container"
- [Dev mode](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/development-mode.html)
Replaced references to "Dockerfile" with "Dockerfile or Containerfile"
- [ Logstash collector events reference list](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/logstash-events-list.html)
Provided Podman alternative for Docker CLI example
- [springBootUtility thin command](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/reference/command/springbootUtility-thin.html)
Replaced references to "Docker" with "container" 
- [server package command](https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/reference/command/server-package.html)
Replaced references to "Docker" with "container"

**Comment by dmuelle** [comment]
verified podman code example substitution with @leochr via slack

changes are on vNext and will publish with 22.0.0.2
