### ISSUE TITLE
Clarify info for server dump command

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4927]
The [OL server dump command](https://www.openliberty.io/docs/21.0.0.11/reference/command/server-dump.html) topic says
`If no server is specified, a server called defaultServer is automatically created to run the command against.`

but the[ IBM docs topic](https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=line-generating-liberty-server-dump-from-command) says:
`If you do not specify a server name, defaultServer is used.`

I tested this and the latter is correct- the command tries to use `defaultServer` if no name is specified, but it doesnt create defaultServer if it doesnt exist already, instead the command fails. Need to update the doc to reflect this and also add this sentence, which was left out:
`The resulting file is created by using UTF-8 encoding for entry names, so the tool that you use to open the file must be able to use UTF-8 encoding for entry names. The jar command in a Java SDK uses this format.`

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

The Changes specified have been added.

Draft site link:https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/command/server-dump.html

**Doubt:**  WRT this sentence, which was left out:
`The resulting file is created by using UTF-8 encoding for entry names, so the tool that you use to open the file must be able to use UTF-8 encoding for entry names. The jar command in a Java SDK uses this format.`

I have not seen any Note: section in Open Liberty. ( mentioned as a note in W/S Liberty) 
So, I am not sure about the placement that I have done currently. Pls, confirm.

Regards
Ramkumar

**Comment by dmuelle** [comment]
As discussed, just need to move the statement to be just above the "Usage Examples" section

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The Changes specified have been added, moved the statement to be just above the "Usage Examples" section.

Draft site link:https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/command/server-dump.html

Regards
Ramkumar

**Comment by dmuelle** [comment]
looks good- one more minor change that I just noticed- need to monospace the reference to the `jar` command.

"The `jar` command in a Java SDK uses this format."

otherwise this is ready to go to staging

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The Change specified - **monospace the reference to the `jar` command**. have been done.

Draft site link:https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/command/server-dump.html

Regards
Ramkumar

**Comment by dmuelle** [comment]
reading this again- I wonder if this sentence might be unclear:

"If the defaultServer does not already exist, the command fails."

maybe it should be

"If no existing server is named `defaultServer`, the command fails when no server name is specified."


also noticed this- in the introduction it says:
"the _result_ file contains server configuration, log information, and details of the deployed applications in the work area directory. "

then in the newly added statement, it says
"The _resulting_ file is created by using UTF-8 encoding for entry names..."

its a minor nit but I think we should use "resulting" in both cases

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The corrections specified have been done.

Draft site link:https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/command/server-dump.html

Regards
Ramkumar

**Comment by dmuelle** [comment]
I just realized that every Liberty package contains a server that is called `defaultServer` so whaty we have is not 100% accurate.  Also in the previous sentence, need a noun identifier for `defaultServer`.

 If you do not specify a server name, the command uses `defaultServer` for the name value. If no existing server in the `wlp/usr/servers` directory is named `defaultServer`, the command fails when no server name is specified.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The correction has been done.

Draft site link:https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/command/server-dump.html

Regards
Ramkumar

**Comment by dmuelle** [comment]
LGTM, you can send it to staging when you have a chance

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.1
