### ISSUE TITLE
Missing word in sentence, other changes, in server create command topic

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#4942]
For https://openliberty.io/docs/21.0.0.11/reference/command/server-create.html
Change "Do not begin the with a dash (-) or a period (.)." to "Do not begin the name with a dash (-) or a period (.)." (Add "name".)

For "Server serverName created", italicsize "serverName".

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

The suggested changes have been made to the document.
Changes Suggested:
**Change "Do not begin the with a dash (-) or a period (.)." to "Do not begin the name with a dash (-) or a period (.)." (Add "name".)
For "Server serverName created", italicsize "serverName".**

Draft site link: **https://draft-openlibertyio.mybluemix.net/docs/22.0.0.1/reference/command/server-create.html**

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- you can send it to staging when you have a chance

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Changes in vNext, will publish with 22.0.0.1

Regards,
Ramkumar
