### ISSUE TITLE
Update the page of Network security hardening on Rate Limiting

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#4946]
**current text**
Firewalls

Production environments need to run inside a firewall. Firewalls help prevent security intrusions by monitoring network traffic and blocking specific traffic based on security rules. Use a firewall to shield production Open Liberty servers so that they don’t run in the DMZ. The DMZ is an intermediary zone where proxy and web servers run between public and private networking zones. Typically, a network setup includes two firewalls, a perimeter firewall and a backend firewall. The perimeter firewall exists between the public zone and the DMZ, and the backend firewall exists between the DMZ and the private zone. The backend firewall, or overall network design, limits ingress traffic to trusted addresses and limits egress traffic to the minimum addresses required by the application.

Security in container environments

(Add new section of `Request Rate Limiting`)
![image](https://media.github.ibm.com/user/26206/files/cf2d1080-43c8-11ec-8d59-368cd21df4a2)

**to be changed**

Firewalls

Production environments need to run inside a firewall. Firewalls help prevent security intrusions by monitoring network traffic and blocking specific traffic based on security rules. Use a firewall to shield production Open Liberty servers so that they don’t run in the DMZ. The DMZ is an intermediary zone where proxy and web servers run between public and private networking zones. Typically, a network setup includes two firewalls, a perimeter firewall and a backend firewall. The perimeter firewall exists between the public zone and the DMZ, and the backend firewall exists between the DMZ and the private zone. The backend firewall, or overall network design, limits ingress traffic to trusted addresses and limits egress traffic to the minimum addresses required by the application.

Request Rate Limiting

Rate limiting can be used to prevent individual users from consuming disproportionate server resources, and to help prevent denial of service attacks. Configure your reverse proxy servers or web application firewalls (WAFs) to enforce rate limitations. 

Security in container environments

**Comment by dmuelle** [comment]
originally opened as https://github.ibm.com/websphere/liberty-docs/issues/2530

@meiaus @

**Comment by dmuelle** [comment]
@wtlucy as discussed in https://wasrtc.hursley.ibm.com:9443/jazz/web/projects/WS-CD#action=com.ibm.team.workitem.viewWorkItem&id=287422, this issue is opened to make an update to the Liberty doc.

@jmulvey @gpicher @pnicoluc per discussion with @wtlucy, we'd like to get your review/approval on the new content update to remediate the pen test issue reported as described in RTC defect 287422 (above link). I'll add your permission to the box file attached in 287422 for reference. Thanks in advance.

**Comment by dmuelle** [comment]
Hi @meiaus, here is the draft update for Open Liberty:

https://draft-openlibertyio.mybluemix.net/docs/21.0.0.12/network-hardening.html#rate-limiting

Let me know if any further edits are needed. Thanks!

**Comment by meiaus** [comment]
Reviewed from https://docs-draft-openlibertyio.mybluemix.net/docs/21.0.0.12/network-hardening.html#rate-limiting.
Looks good.
Thanks.

**Comment by dmuelle** [comment]
content is now on vNext and will publish with the 21.0.0.12 docs release
