### ISSUE TITLE
Interlinking between existing topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#497]
eg RESTful microservices and REST clients topics should each link to the other at some point.

Check for any others. Not many topics yet so a quick review should be easy and help guide approach in future.

**Comment by Charlotte-Holt** [comment]
General linking guidance at https://ibm.box.com/s/ww5eybttrnioz53wvl9c2mztvzobqmse. This was discussed with the ID team. Closing this issue.
