### ISSUE TITLE
Updates for Admin Center topic 

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#4991]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

- For "Manage Open Liberty with Admin Center" topic at https://openliberty.io/docs/21.0.0.10/oidc-tools.html
The tool box screenshot has four tools in it, including one with the openliber.io icon on it. However, the four tools described do not include openliber.io. The tool described instead is for OpenID Conect. Make the tools in the tool box match the tools in "The following tools are available from the Admin Center:".

- For "The following tools are available from the Admin Center:", the wording implies that only the tools listed are in Admin Center. Change the wording to something like "Admin Center includes the following tools in addition to other tools:".
- Change the "Monitor your server with the Explore tool" title. The title talks only about monitoring, but the section describes other things that one can do with the Explore tool. 
- Include how to uninstall a tool from Admin Center, as described in https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=center-customizing-toolbox#twlp_ui_toolbox__uitbuninst

**Comment by dmuelle** [comment]
the `feautreManager` tool is not available in OL, so the uninstall operation is not valid in this context.

**Comment by dmuelle** [comment]
- the open liberty link, which a default for the toolbox, is described in the sentence preceding the screenshot
>After you log in to Admin Center, the browser displays the Toolbox, which contains tools such as the Server Config and Explore tools and a bookmark to openliberty.io. The following screen capture shows the Admin Center Toolbox:

The OpenID connect tools are only available when you enable OIDC. The link to the OL site is there by default. I've replaced the screenshot with one that doesn't contain the Java batch icon, so the screenshot contains only the default tools you see when you first log in if the OIDC and Java Batch features are not enabled. The statement after the image explains that you only see those icons if the features are enabled.

- `"The following tools are available from the Admin Center:", the wording implies that only the tools listed are in Admin Center.` These are the only tools that are available in Open Liberty Admin center. The `Deploy` tool is used to manage collectives and is not available for OL.
- Changed the explore tool heading to "Monitor and manage resources with the Explore tool"
- the feautreManager tool is not available in OL, so the uninstall operation is not valid in this context.


https://docs-draft-openlibertyio.mybluemix.net/docs/latest/admin-center.html

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.1
