### ISSUE TITLE
Config docs - single table of attributes with TYPE marking cardinality (and thus whether can be child element)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#504]
**Background**

Some server.xml config attributes can occur only once or more than once in a configuration. When they can appear more than once, the attribute can be shown in the XML as an attribute of the element or as a child element of the element.

For example, in the [mongo configuration](https://openliberty.io/docs/ref/config/#mongo.html):

```
<mongo>
   <hostNames>ahost</hostNames>
   <hostNames>aHost2</hostNames>
   <ports>5555</ports>
   <ports>23454</ports>
</mongo>
```
can also be presented as the equivalent:

```
<mongo hostNames="ahost,aHost2" ports="5555,2345" />
```

In the generated config docs, attributes that can occur multiple times (and therefore can be shown in the XML either as an attribute or as a child element) are not listed in the table of attributes alongside other attributes that are valid on the element.

**Proposed change**

List all attributes in a single table then, in the `TYPE` column, indicate whether the attribute can occur only once or more than once (and therefore can also be used as a child element).

Not sure how to word this without taking up loads of space in the `TYPE` cell...

**Comment by dmuelle** [comment]
this was fixed by #1434 but never closed
