### ISSUE TITLE
Add missing info to transport security feature page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5042]
add the following information to the transport security feature page as an extended description:

When the transportSecurity-1.0 feature is enabled, the Liberty server sets a custom SSL Socket factory that uses the ssl.SocketFactory.provider Java security property. This security property is automatically set when the transportSecurity-1.0 feature is enabled. When you are using the transportSecurity-1.0 feature, the process SSLContext is the SSLContext of the Java Secure Socket Extension (JSSE). A call to SSLContext.getDefault() returns the default context SSLContext of the JSSE. A call to SSLSocketFactory.getDefault() returns an SSLSocketFactory that is based on the Liberty server custom socket factory provider that uses the Liberty SSLContext.

from:  https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-enabling-ssl-communication-in

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

An extended description has been added to the following link.

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/reference/feature/transportSecurity-1.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
per our conversation with Alaine- jere's a draft of the updated statement:

When the Transport security feature is enabled, the SSL context for the process is the default SSL context of the Java Secure Socket Extension (JSSE). Therefore, the `SSLContext.getDefault()` method returns the default SSL context of the JSSE. However, when this feature is enabled, Liberty also sets a custom SSL socket factory. Therefore, the `SSLSocketFactory.getDefault()` method returns an SSL socket factory that is based on the Liberty custom socket factory provider, which uses the Liberty SSL context instead of the JSSE default.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Corrections have been made to the extended description as suggested.

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.2/reference/feature/transportSecurity-1.0.html

Noticed that: 
Enabling this feature

To enable the Transport Security 1.0 feature, add the following element declaration into your server.xml file, inside the featureManager element:

mentions Transport Security 1.0 feature, I remember you mentioning that we do not specify versions. However, I was not able to locate where this is actually documented to fix this.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
the updated text looks good- except for consistency with the rest of the page, we should replace Liberty with Open Liberty

When the Transport security feature is enabled, the SSL context for the process is the default SSL context of the Java Secure Socket Extension (JSSE). Therefore, the SSLContext.getDefault() method returns the default SSL context of the JSSE. However, when this feature is enabled, Open Liberty also sets a custom SSL socket factory. Therefore, the SSLSocketFactory.getDefault() method returns an SSL socket factory that is based on the Open Liberty custom socket factory provider, which uses the Open Liberty SSL context instead of the JSSE default.


as to the "Enabling this feature" section- that's autogenerated so don't need to worry about it. It will automatically update for future versions of the feature

Once you replace Liberty with Open Liberty, this is ready to go to staging.

**Comment by ramkumar-k-9286** [comment]
Moved from `Staging` to `vNext`. Will be published as part of `22.0.0.3` 

Proceeding to close the issue.
