### ISSUE TITLE
Evaluate "Tuning Liberty"

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5046]
This topic doesnt exist in OL: [Tuning Liberty](https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=tuning-liberty)

Check it against https://www.openliberty.io/docs/21.0.0.12/thread-pool-tuning.html and the OL gendoc- either add any missing info to the gendoc or create a new "tuning topic"

**Comment by dmuelle** [comment]
per comment from alasdair and michal:



Although tuning is mostly automatic, the tunning info that is mentioned in the WL topic doesn't exist in one place in Open Liberty. The user can't rely on cocenptual info in one place to understand manual tuning. Create a tuning topic for manually tuning Open Liberty???? -1 not defined in Open Liberty.- opened https://github.com/OpenLiberty/docs/issues/5046  ... 1/24/22 Have one section in OL nav, troubleshooting. Group tuning info together. Could expand threadpool tuning to more general tuning with setion on threadpool tuning.

**Comment by dmuelle** [comment]
when this doc is created, include a link to the entry on "`numConnectionsPerThreadLocal` of connectionManager" from JDBC feature example for [Customize connection pool settings](https://www.openliberty.io/docs/latest/reference/feature/jdbc-4.3.html#_customize_connection_pool_settings)

**Comment by dmuelle** [comment]
## Peer review
 GLobally, introduce examples with a period instead of a colon, like

To reduce idle server CPU time, add the following attributes to the server.xml file.

[example]

### Intro
- Remove "of Open Liberty" from the second and 3rd sentences

> Open Liberty supports different attributes in the server.xml file to influence application performance. You can tune these parameters and attributes of Open Liberty to achieve better performance.

We say `server.xml` here, but the very first section about tuning the JVM is not in the server.xml. I think you should rewrite the short description- The idea to get across is that OL offers various configuration options to improve application performance. You can tune the settings to fit the needs and constraints of your applications and your development or production environment.

### Tune the JVM
- spell out Java virtual machine on first mention
-  the sentence about development environment from the IBM docs is missing.
- what does the example show? we should describe what the setting is, See the "Customize JVM options by using jvm.options files." step in [Customizing the Liberty environment ](https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=manually-customizing-liberty-environment) for details.
- link to [jvm.options](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/config/server-configuration-overview.html#jvm-options) for more information

### Transport channel services

> For applications on Open Liberty, the following attributes are available for different elements that can be used to improve runtime performance, scalability, or both
--->

> You can tune the following attributes to improve runtime performance, scalability, or both.

- SSL connections ---> TLS connections
- "you might start with a 1:1 mapping to the coreThreads attribute." ---> "you might start with a 1:1 mapping to the `coreThreads` attribute."
- for` purgePolicy`, since there is more information about the settings in the gendoc, I think we should include "For more information, see [connectionManager: purgePolicy]"

>  It might be better to purge only the failing connection.
--->

>  In some cases you might want to purge only the failing connection by specifying the `FailingConnectionOnly` value.

- thread local ---> thread-local
- The bulleted list in the description for `numConnectionsPerThreadLocal` is not rendering properly. You can either fix the syntax or rewrite to not use a list since there are only two items
- same problem with `statementCacheSize`

> ...which in turns controls the level of database locking. 
--->

> which in turn controls the level of database locking. 

### Executor
link to Thread pool tuning is broken

### Decrease response time of servlets
add after example: This setting prevents the server from searching the meta-inf directory for application resources. 

I think we'll need a little more info on this one but need SME input 

### Reduce idle server CPU time
The `updateTrigger` attribute can also be set to the value of MBean
--->
You can also set the  `updateTrigger` attribute to the `MBean` value

### Tuning startup time
- For parallelism, change heading to "Tune startup time"

> Implicit archive scanning for annotations can be disabled by setting the `enableImplicitBeanArchives` value to `false`. 
--->

> You can disable implicit archive scanning by setting the `enableImplicitBeanArchives` attribute to `false`. 

- The last sentence is too long. When you revise it, should specify "The Jakarta Contexts and Dependency Injection feature might be included _in your server configuration_..."

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Incorporated comments into the draft document:

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.4/performance-tuning.html

For Review.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Changes look good- a few more suggestions:

## Intro
The two sentences in the short description basically just say the same thing twice. I think you could edit the second sentence to give a better overview of the information- maybe something like:

> Open Liberty supports various parameters and configuration options to influence application performance. You can tune settings for the Java virtual machine (JVM), the transport channel services, and more to achieve better performance.

## Tune the JVM

I think the introduction for the example needs some work. Need to make it clear that the example just shows some of the kind of things you can set. 

> You can maximum heap size to 1024m, set a system property, enable verbose output for class loading and enable verbose garbage collection. Specify the JVM arguments, one option per line, as shown in the following example.
--->

> The following example specifies one JVM option per line to set maximum heap size to `1024m`, set an example system property, and enable verbose garbage collection. 

if you go with this suggestion, remove `-verbose:class` from the example.

- the link to jvm.options is broken and also has a typo in the link text.

## Tune transport channel services

lists are still not rendering in descriptions for `numConnectionsPerThreadLocal`  and `statementCacheSize` . You can either fix the syntax or rewrite to not use a list since there are only two items

- add monospace formatting to the attributes in the Attribute column

## Tune startup time

I think you could add a little more clarification about CDi feature being enabled by other features, like:


The Jakarta Contexts and Dependency Injection feature might be included in your server configuration even if it is not explicitly specified in your server.xml file because other features might implicitly enable it. For example, the MicroProfile feature and the Jakarta EE Web Profile feature each enable the Jakarta Contexts and Dependency Injection feature by default.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

For Review : 
https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
## Peer review

### Tune the JVM
- suggested edit

> When you tune the JVM for Open Liberty, use the jvm.options file in the ${server.config.dir} directory. You can specify each of the JVM arguments that you want to use, one option per line.

You can use jvm.options files at the runtime and server levels to specify more server startup options.

--->

> To tune the JVM for Open Liberty, you can specify JVM arguments,  one option per line, in the jvm.options file in the ${server.config.dir} directory. 

~~You can use jvm.options files at the runtime and server levels to specify more server startup options.~~

> For a development environment, you might be interested in faster server startup. So, consider setting the minimum heap size to a small value, and the maximum heap size to whatever value is needed for your application. 
--->
> For faster server startup in a development environment, consider setting the minimum heap size to a small value and the maximum heap size to whatever value is needed for your application. 


 In some cases you might want to purge only the failing connection
--->
 In some cases, you might want to purge only the failing connection

- remove stray slash: ." \ Ensure to use the same credentials for all connection requests."
- add monospace to attribute value
The following example shows how to reduce the amount of CPU time that is used when you set the `updateTrigger` attribute to the value of `MBean`.
- suggested edit
> This feature can increase startup time substantially and have the most effect on larger applications.
--->
> This feature can increase startup time substantially, particularly in larger applications.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

For Review :
https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - looks goood. I have two very minor suggestions but I think this is ready for technical review.

 You can tune settings for the Java virtual machine (JVM), the transport channel services, and more to achieve better performance.
--->
You can tune settings for the Java virtual machine (JVM), the transport channel services, and more to improve performance.

- put all the content for Tune the default executor in the same paragraph

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made suggested corrections:
https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM thanks- I'll send the draft to Alasdair and Michal and ask if there's anyone else who should review

**Comment by dmuelle** [comment]
Review comments from @gjdeval via slack:

- at the end of the 'Tune the JVM' section, we could point to the OpenJ9 doc for more guidance about JVM tuning options for IBM Java
https://www.eclipse.org/openj9/docs/
- the "Reduce idle server CPU time" section might benefit from a couple sentences of preamble to set the context before getting into the tunables ... something like

By default, Open Liberty monitors for configuration and application changes by periodically checking for file system updates in the relevant areas of the server installation. The default settings and functions for config and application monitoring are described in these documents:
https://openliberty.io/docs/22.0.0.3/reference/config/config.html
https://openliberty.io/docs/22.0.0.3/reference/config/applicationMonitor.html

- 'Tune startup time'  repeatedly uses the "full and official name" of CDI, like
By default, the Jakarta Contexts and Dependency Injection feature scans all ...
For me, the discussion is easier to digest if the acronym is used, spelled out the first time, like
By default, the CDI (Jakarta Contexts and Dependency Injection) feature scans all ...
and then just 'CDI' on future occurrences.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Review comments incorporated. Please check:
https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
now that there are 2 more information links in the JVM section, I think we should clarify the first

For more information, see [jvm.options](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#jvm-options).
--->
For more information about the Open Liberty` jvm.options` file, see [jvm.options](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#jvm-options).


By default, Open Liberty monitors for configuration and application changes, by periodically checking for file system updates in the relevant areas of the server installation. For more information on the default settings and functions for config and application monitoring, see the following links:
--->
By default, Open Liberty monitors for configuration and application changes by periodically checking for file system updates in the relevant areas of the server installation. For more information on the default settings and functions for configuration and application monitoring, see the following configuration attributes.


CDI (Jakarta Contexts and Dependency Injection) feature
--->
Jakarta Contexts and Dependency Injection (CDI) feature


also- see the recent additions to[ the slack thread](https://ibm-cloud.slack.com/archives/C017Z9D5WJZ/p1650916995366139?thread_ts=1650893000.741869&cid=C017Z9D5WJZ) for further updates

**Comment by dmuelle** [comment]
For the comment linked in the slack thread, include something like:


Open Liberty provides [convenience features](https://openliberty.io/docs/latest/reference/feature/feature-overview.html#_convenience_features), such as MicroProfile or JakartaEE, which include many individual Liberty features. The convenience features are handy for development environments, when the scope of application function might not be finalized and you wants to have all the features readily available. However, each added feature requires server resources during server startup.
You can improve startup times by including only the necessary features in your deployment configuration.  A configuration that includes features that are not actually used by the deployed application might require more CPU, memory, and time to start than necessary.  You can [use Open Liberty dev mode to automatically generate a list of the features that your application needs](https://openliberty.io/blog/2022/02/08/feature-generation-tech-preview.html).


but use the proper asciidoc syntax for the links

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Comments incorporated. Please check:
https://draft-openlibertyio.mybluemix.net/docs/latest/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
theres a typo in **Tune startup time**

attibute--->attribute

also:
A configuration that includes features that are not ~~actually~~ used by the deployed application might require more CPU, memory, and time to start than necessary.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Typo fixed -> attibute--->attribute

Deleted -> ~~actually~~

Please check:
https://draft-openlibertyio.mybluemix.net/docs/latest/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, thanks. I think this is ready for technical review

**Comment by ramkumar-k-9286** [comment]
Hi Gary @gjdeval 

Could you please review the performance tuning document.

Link: https://draft-openlibertyio.mybluemix.net/docs/latest/performance-tuning.html

you could leave your comments in the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Conversation with Gary 
---

[Ramkumar K](https://app.slack.com/team/U0270NV9V2P)  [3:25 PM](https://ibm-cloud.slack.com/archives/D03F2DH7AP7/p1652349305891509)
Hi Gary,

[3:27](https://ibm-cloud.slack.com/archives/D03F2DH7AP7/p1652349433963939)
Hope you are having a good day.
Could you have a look at the performance tuning document.
Issue link: https://github.com/OpenLiberty/docs/issues/5046
You could leave your review comments in the issue.
Thanks & Regards,
Ramkumar

[Gary DeVal](https://app.slack.com/team/W4WMY6GAW)  [5:13 PM](https://ibm-cloud.slack.com/archives/D03F2DH7AP7/p1652355782537709)
Hello Ramkumar
I looked through the doc yesterday briefly and saw no issues ... will take a more careful look today, and let you know. :slightly_smiling_face:

Ramkumar K  5:13 PM
Thanks.

[Gary DeVal](https://app.slack.com/team/W4WMY6GAW)  [12:47 AM](https://ibm-cloud.slack.com/archives/D03F2DH7AP7/p1652383051049809)
Looks good to me, Ramkumar. Thanks for the chance to review, and for making the updates. :slightly_smiling_face:

**Comment by dmuelle** [comment]
LGTM, thanks- you can send to staging when you have a chance.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

For verification: Performance tuning doc in the staging site.

Link: https://docs-staging-openlibertyio.mybluemix.net/docs/latest/performance-tuning.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- created https://github.com/OpenLiberty/docs/pull/5503 to send to vNExt

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 22006
