### ISSUE TITLE
Server Config Overview missing enabler in the example

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/docs#5125]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

.
.
.
**The following page has an example which is missing the  "# enable_variable_expansion":**

https://openliberty.io/docs/22.0.0.1/reference/config/server-configuration-overview.html

**This example:**

_The following server.env file example shows the syntax for expansion variables on Linux. The values for the WLP_USER_DIR and LOG_DIR environment variables contain expansion variables._

```
JAVA_HOME=/opt/ibm/java
WLP_USER_DIR=/home/${USER}/wlp-usr
LOG_DIR=${WLP_USER_DIR}/logs
```

**It should have the enabling comment at the beginning:** 
```
# enable_variable_expansion
JAVA_HOME=/opt/ibm/java
WLP_USER_DIR=/home/${USER}/wlp-usr
LOG_DIR=${WLP_USER_DIR}/logs
```

The doc does say earlier that you need the "# enable_variable_expansion",  but then we omitted it in the example.

**Comment by ramkumar-k-9286** [comment]
Hi Jim @jimblye 

The comment has been incorporated. The draft link for the page is:
https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.2/reference/config/server-configuration-overview.html

Please add the `Technical Reviewed` label if the page looks good.
Please add comments in the issue, in case you need any additional changes.

Regards,
Ramkumar

cc @dmuelle

**Comment by ramkumar-k-9286** [comment]
Moved to vNext. Will publish 15-Feb with 22.0.0.2.
