### ISSUE TITLE
Intro document for monitoring/observability

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/docs#513]
Consider an intro document for monitoring/observability (from an Ops standpoint) like the MicroProfile intro one.  This is to introduce the audience to the general topic of observability covering the likes of logging, metrics, tracing and health checks.

This can be linked from the main homepage as the "Learn More" for "Monitoring Microservices".

**Comment by Charlotte-Holt** [comment]
**SME**: Don Bourne - "This could be useful to provide dev and ops teams a roadmap of what capabilities they should pay attention to."

**Comment by ManasiGandhi** [comment]
Draft link https://draft-openlibertyio.mybluemix.net/docs/ref/general/#observability-monitoring.html

**Comment by Rwalls1** [comment]
The draft looks good, I just had a few more comments:

**Intro**
- For "Whereas, logs collect textual information", I think it might be better to use a simpler word and combine it with the previous sentence to say, "Metrics collect numerical information from the application and platform and logs collect textual information."
- For "Tracing, on the other hand", I think you should remove "on the other hand" or replace it with something simpler such as "however"

**Metrics**
- Typo: Change "three are factors are involved" to "there are three factors involved"

**Tracing**
- I think you should maybe spell out what "IIS" stands for to help avoid any possible confusion.
- For "This includes any form of authentication", I think you should add a noun after "This" to make it clearer what is being referred to.

**Health Checks**
- For "The API endpoint handler performs various checks, such as the status of the connections to the infrastructure services used by the service instance, the status of the host, for example, disk space, and application specific logic.", this appears to be a run-on sentence and should probably be simplified to make it easier to read. Maybe end the first sentence after "instance" then start a new sentence with the other information.

**Comment by yeekangc** [comment]
- Consider revising the below.  Both mentioned Grafana but once as a "processor" and another time as a "service".  It's a bit confusing as to what they are and the differences.

> Processors like Grafana, use all of the aggregated data. Services like Grafana process aggregated metrics for visualization by using dashboards.

- Useful include examples of (tools to use with) Logs and Tracing (in the context of Kubernetes platform) like what we have done for Metrics and Health Checks.

- Health Checks: May be define and describe what Health Checks offer first like the other sections before going into details of how it is implemented or can be done.

**Comment by donbourne** [comment]
need a crisper definition of observability.  eg. Observability is the ability of a system to expose information about its internal state to facilitate problem determination, performance analysis and other investigations.


In a microservices environment, your application needs to be functional as a whole...
    - at this point in the doc you might want to describe the need for the types of data you're about to describe and that you need to use them together to help troubleshoot.

Metrics
    - the industry talks more about sources of metrics, time series databases, dashboards, thresholds, alerts, anomaly detection, AIOps, etc.  not sure people would recognize producers, aggregators and processors.
    - need to keep this topic general/conceptual.  details about how prometheus works seem out of place here.  People that already understand what Prometheus is probably don't need this topic.
    - could talk about JMX vs. REST metrics to help people understand what they are and how to choose

Logs
    - again, seems like a mix of very conceptual info ("log messages are strings with contextual information...") and very specific info ("you can use a volume for log data with a simple bind mount...").  I think you want to stay conceptual.

Health Checks
    - before saying a health check is a REST API, need to describe what a health check is as a concept.
    - "A health check client; a monitoring service,..." - gets a bit too specific about a bunch of new concepts without really explaining why they call the health checks.  would be better to provide one specific example and say what it does with the info it gets back from the health check.

**Comment by Charlotte-Holt** [comment]
@ManasiGandhi I'm going to move this to the icebox, so you don't need to keep working on it for the time being. After talking with @lauracowen and @dmuelle, I think that we need to wait until we have more of the observability topics further along before we decide whether this topic is needed and, if so, what should be in it.
