### ISSUE TITLE
Update the page admin-center.html

### ISSUE THREAD

**Issue by meiaus** [OpenLiberty/docs#5178]
To update the existing topic: 
https://openliberty.io/docs/22.0.0.1/admin-center.html

**Current Text:**

The Source mode enables direct access to edit the file text and provides tooltip descriptions for file elements. Hover on elements and parameters to view their documentation. You can press Ctrl+Space to use content assist, which helps you add new elements, parameters, and values.

**To be changed:**

The Source mode enables direct access to edit the file text and provides tooltip descriptions for file elements. Hover on elements and parameters to view their documentation. You can press Ctrl+Space to use content assist, which helps you add new elements, parameters, and values. Be careful as the editor will allow you to make changes that could cause the server to fail.

**Comment by meiaus** [comment]
@dmuelle  Thanks.

**Comment by meiaus** [comment]
@k8vance88 please review and if more update to be added.  Thanks.

**Comment by dmuelle** [comment]
Hi @meiaus - for this edit can we provide a little more context? Does this warning pertain to content-assist in particular? It might be helpful to provide some kind of example so users are not left to wonder what could make the server fail.

**Comment by meiaus** [comment]
Hi @dmuelle, @k8vance88 the Admin Center dev agrees to add the example.  In the meantime, we're wondering if the page supports the "note" or "alert" type of box like it seen in tWAS doc:

![image](https://user-images.githubusercontent.com/27024803/153032031-70779de3-8e08-4ac6-9081-4214860dbc41.png)

**Comment by meiaus** [comment]
The idea of making the note to the user is to avoid the possible failure of server startup when an invalid update is made.

**Comment by dmuelle** [comment]
we don't have note boxes on the OL site, but we can add more context to the description to make it clear that while the editor can make content assist suggestions, it cannot detect whether the configuration values are valid

**Comment by k8vance88** [comment]
It's more of a general warning, like when you go into your browser settings or OS settings and they say I hope you know what you are doing.  They are editing server config and any number of wrong configurations could mes up their server.

**Comment by dmuelle** [comment]
Hi @k8vance88 @meiaus this  update is now available for review on draft:

https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.2/admin-center.html#server

I tried to add a little more context to give users an idea of why/when they might encounter a problem. Let me know if any further edits are needed. If not, you can add the `technical reviewed` label to this issue and the changes will publish with the 22.0.0.2 docs release. Thanks!

**Comment by meiaus** [comment]
@dmuelle thank you very much.  I reviewed and liked the way you edited with key words such as `does not validate`, `entering invalid configuration`.

**Comment by dmuelle** [comment]
changes are on vNExt and will publish with tomorrow's release. Closing this issue, thanks!

**Comment by meiaus** [comment]
Thanks @dmuelle
