### ISSUE TITLE
Add Semeru 17 link to the Java Support table

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#5232]
The Java Support table on the Java SE Support page doesn't include a link to Semeru 17.

The Java Support table is here: https://openliberty.io/docs/22.0.0.2/java-se.html

Semeru 17 is here: https://developer.ibm.com/languages/java/semeru-runtimes/downloads?os=macOS

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

The link has been added to the document. The Draft-site link is added below.

https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.3/java-se.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- I think you can send it to staging

**Comment by dmuelle** [comment]
please add the java 18 info specified in this PR: https://github.com/OpenLiberty/docs/pull/5250/files

this info should publish with 22.0.0.3 so we can handle it here to avoid branch conflicts

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 22003
