### ISSUE TITLE
Need additional clarity on how to work with Multipart objects in RESTFul Webservices

### ISSUE THREAD

**Issue by csandersdev** [OpenLiberty/docs#5259]
In the RESTful Web Services user guide there is [a page](https://openliberty.io/docs/22.0.0.2/send-receive-multipart-jaxrs.html) that discusses how to work with multipart form requests. The code examples in that page reference classes IAttachment and AttachmentBuilder which come from a custom OpenLiberty API dependency, but that is never mentioned in the docs. We should include a reference to how to obtain the necessary API JAR (e.g. Maven Coordinates) and show the appropriate imports for those packages in the code samples.

I discussed this in the IBM internal Slack [here](https://ibm-cloud.slack.com/archives/C31G324KW/p1646766045509859?thread_ts=1615558872.028900&cid=C31G324KW) if you want the complete conversation. Per the dev staff on that thread, the correct coordinates for a Maven build are as follows...

```xml
<dependency>
  <groupId>io.openliberty.api</groupId>
  <artifactId>io.openliberty.jaxrs30</artifactId>
  <version>1.0.62</version>
</dependency>
```

And the Java examples should import the classes as follows...
```java
import com.ibm.websphere.jaxrs20.multipart.AttachmentBuilder;
import com.ibm.websphere.jaxrs20.multipart.IAttachment;
import com.ibm.websphere.jaxrs20.multipart.IMultipartBody;
```

**Comment by dmuelle** [comment]
as part of the work for this issue alos need to fix broken links to [Jakarta RESTful Web Services](https://openliberty.io/docs/22.0.0.2/reference/feature/restfulWS-3.0.html) in doc versions prior to 22.0.0.2

**Comment by dmuelle** [comment]
Hi @csandersdev @jhanders34 @WhiteCat22 

I've added the Maven dependency example and also my best guess at a Gradle equivalent (thanks to @cherylking). I also updated the java examples to add import statements and fixed the broken link issue that @jhanders34 found in the older versions of the doc. You can review the draft here:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/send-receive-multipart-jaxrs.html 

I have a few questions:

1. can someone please test the dependency and the `import` statements? It wasn't available when the initial slack discussion took place but should have become available with 22.0.0.3, which was released yesterday.
2. what is the `scope` of the Maven dependency and should the example include a `scope` element? 
3.  Is this dependency in Maven central? 
4. Once EE 10 is supported, will the dependency and/or import statements still be needed?
5. This is just for my own understanding- why do we have to declare an explicit dependency when we already tell the user to enable the `restfulWS-3.0` feature, which automatically enables the `restfulWSClient-3.0` feature, which provides the `com.ibm.websphere.jaxrs20.multipart` package?

Please let me know if any changes are needed for the examples or text. If not, you can add the `technical reviewed` label to this issue and the update will publish with the next docs release.

Thanks!

**Comment by csandersdev** [comment]
1. I see an update in the Maven Central Repository from 03/16/2022, so I think it is there now. @jhanders34 should confirm since it was there before, but there was a packaging issue.
2. Good question. I imagine this should be provided scope. The APIs are present in Liberty, so the JAR doesn't need to be included in the user's application. See Andy's response [here](https://stackoverflow.com/questions/68638926/get-multipart-form-data-parts-with-iattachment) for a similar example from an older version of Liberty. You've actually got it right in your Gradle example, but are missing the `<scope>provided</scope>` in your Maven example.
3. As mentioned above, I believe so. You can see it here -  ![image](https://user-images.githubusercontent.com/25621588/158679973-f0ff380e-4b92-44d5-b023-7b5223405d15.png)
4. Andy was working on updates to the public specification so that Liberty would not need its own specific implementation of these classes in EE10. I am not privy to those details, so I'll defer to @jhanders34 for more information.
5. The API jars are available in the Liberty *server*, but the Liberty *client app* needs visibility to those APIs during compile time. Normal JEE APIs get pulled in via something like the `jakarta.platform:jakarta.jakartaee-api:9.1.0:provided` dependency in the client app, but this one isn't included in that JAR because it is Liberty specific/not part of the public specification. Thus, we need a separate dependency block.

**Comment by jhanders34** [comment]
> 1. I see an update in the Maven Central Repository from 03/16/2022, so I think it is there now. @jhanders34 should confirm since it was there before, but there was a packaging issue.

Yes the 22.0.0.3 version is correct.

>     2. Good question. I imagine this should be provided scope. The APIs are present in Liberty, so the JAR doesn't need to be included in the user's application. See Andy's response [here](https://stackoverflow.com/questions/68638926/get-multipart-form-data-parts-with-iattachment) for a similar example from an older version of Liberty. You've actually got it right in your Gradle example, but are missing the `<scope>provided</scope>` in your Maven example.

I completely agree.  The version though you may just want 1.0 so it picks the latest?

>     3. As mentioned above, I believe so. You can see it here -  ![image](https://user-images.githubusercontent.com/25621588/158679973-f0ff380e-4b92-44d5-b023-7b5223405d15.png)

Yes Liberty APIs are published in both maven central and DHE.  I usually go to https://repo.maven.apache.org/maven2/io/openliberty/api/ to see the io.openliberty.api group.

>     4. Andy was working on updates to the public specification so that Liberty would not need its own specific implementation of these classes in EE10. I am not privy to those details, so I'll defer to @jhanders34 for more information.

RESTful Web Services 3.1 is where the Jakarta community is introducing the multi part functions into the specification.  To use the RESTful Web Services 3.1 way of doing it will require application changes to use the new jakarta.ws.rs APIs instead of the com.ibm APIs

> Please let me know if any changes are needed for the examples or text. If not, you can add the technical reviewed label to this issue and the update will publish with the next docs release.

I think it would be best to get @WhiteCat22 and/or @jim-krueger to provide the `technical reviewed` label sign off since they are the developers responsible for this function.  Obviously some of the updates mentioned above by @csandersdev should be done.

**Comment by WhiteCat22** [comment]
The doc look great David! Thank You!

**Comment by dmuelle** [comment]
Thanks all , I've updated the draft to add the `provided` scope to the Maven example and changed the version to 1.0 for both Maven and Gradle.

https://docs-draft-openlibertyio.mybluemix.net/docs/22.0.0.4/send-receive-multipart-jaxrs.html

My last question is whether there is any issue or epic on the dev side of things that we can make a note for RESTful web services to update this doc when 3.1 comes out and the dependency is no longer required?

**Comment by WhiteCat22** [comment]
Here is the epic for RESTfulWS 3.1: https://github.com/OpenLiberty/open-liberty/issues/18739

**Comment by dmuelle** [comment]
Changes are on vNExt and will publish with the 22.0.0.4 docs release. Closing this issue, thanks all
