### ISSUE TITLE
Access Log documentation should not mention XCT

### ISSUE THREAD

**Issue by mrsaldana** [OpenLiberty/docs#5269]
Cross Component Tracing (XCT) is not supported in Liberty. As such, the %{X}W directive is invalid. The access log documentation should be cleaned up to remove mentions of XCT.

Proposed change: 

The file `modules/ROOT/pages/access-logging.adoc` should remove lines 124 through 126:

```
> |%{X}W
> |The Cross Component Tracing (XCT) Context ID
>
```

**Comment by mrsaldana** [comment]
Fixed by #[5268](https://github.com/OpenLiberty/docs/pull/5268)

**Comment by dmuelle** [comment]
the draft shows the row is removed:

https://draft-openlibertyio.mybluemix.net/docs/22.0.0.3/access-logging.html

I'll send the change to staging
