### ISSUE TITLE
MIgrate LTPA info to example in appSec page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5311]
Compare  https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-configuring-ltpa-in and with https://www.openliberty.io/docs/22.0.0.3/reference/feature/appSecurity-4.0.html#_specify_ltpa_keys and migrate any missing info.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

For review:
https://draft-openlibertyio.mybluemix.net/docs/22.0.0.5/reference/feature/appSecurity-4.0.html
Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
link broken. will fix.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
you don't need to specify `/reference` in the syntax because the file you are linking from is also in the reference section

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The link has been fixed. For review:

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/appSecurity-4.0.html#_specify_ltpa_keys

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- PR it to staging when you have a chance

**Comment by dmuelle** [comment]
we need to add a redirect statement to the IBM docs page

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Added redirect statement to the IBM docs page:
https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-configuring-ltpa-in

**Comment by ramkumar-k-9286** [comment]
content is on vNExt and will publish with 22005

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Added the updated redirect statement to the IBM docs page:

https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-configuring-ltpa-in

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks good except I dont think you need to spell out "Lightweight Third Party Authentication (LTPA)" since it's already spelled out in the previous sentence. Also, could reorganize the sentence to make clear that you arer not specifying keys on the OL website 

> In version 20.0.0.5 and later, see the documentation for specifying the Lightweight Third Party Authentication (LTPA) keys on the [Open Liberty website](https://www.ibm.com/links?url=https%3A%2F%2Fopenliberty.io%2Fdocs%2Flatest%2Freference%2Ffeature%2FappSecurity-4.0.html%23_specify_ltpa_keys).

--->

> In version 20.0.0.5 and later, see the documentation on the Open Liberty website for [specifying the Lightweight Third Party Authentication (LTPA) keys ](https://www.ibm.com/links?url=https%3A%2F%2Fopenliberty.io%2Fdocs%2Flatest%2Freference%2Ffeature%2FappSecurity-4.0.html%23_specify_ltpa_keys).
