### ISSUE TITLE
Update the Security vulnerabilities list for CVES found to apply to 22.0.0.2 

### ISSUE THREAD

**Issue by clarkek123** [OpenLiberty/docs#5355]
After GA of 22.0.0.2 we assessed some new open source CVEs that were found to be fixed in 22.0.0.2. Now that interim fixes are published, those CVEs need to be added to the CVE list.

The PR is https://github.com/OpenLiberty/docs/pull/5354

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.4
