### ISSUE TITLE
We should document the DDLs required for Liberty components using JDBC

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#5357]
We have a bunch of components in Liberty that use a Database, for example the transaction manager, session persistence and ejb timers. We don't consistently document the DDL for databases which means users who don't want to auto define tables are unable to manually create them without referring to the WebSphere Liberty docs.

**Comment by dmuelle** [comment]
see https://github.ibm.com/websphere/twas-docs/issues/5293

**Comment by dmuelle** [comment]
slack comment from Alasdair:

>  there is this closed item which was opened to update tWAS docs, but I pointed out that wasn't appropriate because  tWAS doesn't support Postgresql. So if all you do is document the session persistence DDL based on this I guess we are good on the OL DDL doc: https://github.ibm.com/websphere/twas-docs/issues/5293

**Comment by dmuelle** [comment]
initial draft at https://docs-draft-openlibertyio.mybluemix.net/docs/latest/create-session-table.html

**Comment by frowe** [comment]
@dmuelle Reviewed, was able to create postgres sessions table using DDL so I think you're good.

**Comment by dmuelle** [comment]
thanks @frowe 

@ramkumar-k-9286 this issue is ready for peer review

**Comment by ramkumar-k-9286** [comment]
Peer Review
---
The following `server.xml` file example shows a data source configuration for a Db2 database.
--->
In the following example, the `server.xml` file shows a data source configuration for a Db2 database.

Also, should we monospace the `Db2` database?

---

The `httpSessionDatabase` element references the configured data source and identifies a manually created table that is called `sessionTable` within the database to store session data.
--->
The `httpSessionDatabase` element references the configured data source and identifies the `sessionTable` table, a manually created table within the database to store session data.

---

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - we dont need to monospace Db2 because it's a product name. I also think the original wording there is more concise and a common formulation in the docs.

I updated the second sentence per your recommendation, though slightly differently. Let me know what you think

**Comment by dmuelle** [comment]
File is on vNext branch and will publish with 22.0.0.6
