### ISSUE TITLE
Update server-configuration-hardening.adoc to address data at rest

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5382]
per comment from @emilytee in #5374:

Per CISO, must address client data at rest, which in Liberty's case consists of passwords.

Proposing the doc be updated to include the following (at line 166):

[#Client data at rest]
== Client data at rest
Use password encryption to secure client data at rest, i.e., passwords.

**Comment by dmuelle** [comment]
Hi @emilytee - the draft is now updated:

https://draft-openlibertyio.mybluemix.net/docs/latest/server-configuration-hardening.html#client-data

it seems a little redundant in it's own section just sitting directly above the rest of the password encryption info- but if the intention is to have a specific heading for client data at rest, this is the best place for it. Let me know if any further edits are needed. This will go out with the 22.0.0.5 docs release

**Comment by emilytee** [comment]
Looks good, thank you

**Comment by dmuelle** [comment]
update will publish with 22005, closing this issue
