### ISSUE TITLE
Update the Liberty security hardening topics to refer to the Liberty CIS benchmark

### ISSUE THREAD

**Issue by arkarkala** [OpenLiberty/docs#5387]
Now that we have the CIS (Center for Internet Security) benchmark (draft) published, we need let our customers know that this is the place they they need to go to find all the Liberty specific hardening requirements. CIS is a well-known industry standard that provides security recommendations using its benchmark/guidelines format. One can open tickets, discussions here for any issues/comments. We have included here all the current Liberty specific hardening information from Liberty docs, blogs, presentations and more.

One can find more information, signuo and provide feedback at  https://workbench.cisecurity.org. They need to join the IBM WebSphere Liberty benchmark. The direct link to the Liberty benchmark is https://workbench.cisecurity.org/benchmarks/7724.

**Comment by chirp1** [comment]
From a discussion with Ajay during his team's scrum today, we'll keep the Hardening topics in Open Liberty for now and link to CIS from the hardening topics. We can add the CIS link to the parent hardening topic and its children. After the CIS documentation is finalized, we can remove the OL hardening topics.

**Comment by chirp1** [comment]
You can open tickets on CIS to make further doc updates to the CIS document. See Ajay if you have questions.

**Comment by dmuelle** [comment]
link to download the WebSphere benchmark: https://www.cisecurity.org/benchmark/websphere

**Comment by ramkumar-k-9286** [comment]
The process a user encounters is as follows:

1. Click the https://www.cisecurity.org/benchmark/websphere link.

**Note:** Clicking on https://workbench.cisecurity.org/ or https://workbench.cisecurity.org/benchmarks/7724 takes you to the **CIS WorkBench** page. You would need to log in by specifying your **E-mail** or **Username** and the **password**.

 2. Clicking on the https://www.cisecurity.org/benchmark/websphere link in **step 1**, takes you to the **CIS IBM WebSphere Benchmarks** page.
 
 3.  Click the **DOWNLOAD LATEST CIS BENCHMARK** button.
  
**Note:** This benchmark is freely available to everyone for IBM WebSphere 1.0 (CIS IBM WebSphere Liberty Benchmark version 1.0.0).

4. On the **Download Our Free Benchmark PDFs** page, you need to complete an information form to access all of the benchmark PDFs for free.

5. In the information form, the following information is **MANDATORY**.

- Specify the **First Name**
- Specify the **Last Name**
- Specify the **Organization**
- Select the **Sector**
- Select the **Role**
- Specify the **Email**
- Select the **Country**
- Select the **Terms of use** checkbox

6. Click the **GET FREE BENCHMARKS NOW** button.
An email is sent to the specified Email address with the link that takes you to the benchmarks download page.

7. In your Email inbox, select the CIS mail, and click the **Access PDFs** button.
Your browser opens with the **CIS Benchmarks** page. You now have access to all of the CIS Benchmark PDFs.

8. Scroll down to the **IBM WebSphere** `Virtualization` section.

9. Click the **Download PDF** button.
The **CIS IBM WebSphere Liberty Benchmark v1.0.0** is downloaded.

**Comment by ramkumar-k-9286** [comment]
The steps mentioned above need to be performed by the user to download the CIS IBM WebSphere Liberty Benchmark v1.0.0.
Not sure if this entire process needs to be mentioned in the document.

but then again, 

not sure how much we can avoid as well.

**Comment by dmuelle** [comment]
Thanks for documenting this process

the `virtualization` category is an error that they have [an internal ticket](https://workbench.cisecurity.org/tickets/15543) open for- we should be under "Server technologies".

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Updates for CIS benchmarks made to the security hardening topic.

Link: https://draft-openlibertyio.mybluemix.net/docs/latest/security-hardening.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
## Peer review

- I think this information should be under its own subheading "Liberty CIS benchmarks"
- Link [Center for Internet Security](https://www.cisecurity.org/) on first mention

> The Center for Internet Security (CIS) benchmarks are a collection of industry-wide cybersecurity standards to configure networked digital resources and ensure their compliance with the established best practice cybersecurity standards for security and privacy.
--->

> The Center for Internet Security (CIS) benchmarks are a collection of industry-wide cybersecurity standards to configure networked digital resources and ensure their compliance with  established best practices for security and privacy.


- all of this information can go in the same paragraph- except "You can review them and open tickets there to address any questions or concerns." This needs more context because you can only open tickets if you have a CIS user account. In separate paragraph after the rest of the information, something like:

> If you have a free CIS user account, you can  open tickets to address any questions or concerns with the benchmarks in the [Liberty benchmarks user portal](https://workbench.cisecurity.org/benchmarks/7724).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Review Comments incorporated.

Draft link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/security-hardening.html

Regards
Ramkumar

**Comment by dmuelle** [comment]
Looks good except there's a missing space here:

> ...ensure their compliance with the established best practices for security and privacy.Open Liberty...

also, the info for users with a CIS account should come after the info to DL the benchmarks, so this would be the last sentence in the section:

> If you have a free CIS user account, you can open tickets to address any questions or concerns with the benchmarks in the [Liberty benchmarks user portal](https://workbench.cisecurity.org/benchmarks/7724).

Also, for the DL instructions, don't put each sentence in a separate paragraph

**Comment by ramkumar-k-9286** [comment]
Hi Ajay @arkarkala 

Updates for CIS benchmarks made to the security hardening topic.

Draft link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/security-hardening.html

Regards
Ramkumar

**Comment by arkarkala** [comment]
Looks good. Thanks

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.7
