### ISSUE TITLE
SEC 380: Migrate "Configuring the authentication cache in Liberty" to openliberty.io

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/docs#5388]
For feature: [SEC380: Support for distributed Auth Cache in Liberty](https://github.com/OpenLiberty/open-liberty/issues/9005)

As part of SEC 380 (distributed security caches) we need to move the [Configuring the authentication cache in Liberty](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-configuring-authentication-cache-in) topic to the openliberty.io site.

We can start by moving this topic over, but I will also need to add some edits for the final version when the SEC 380 feature is GA'd.

**Comment by chirp1** [comment]
Do #5389 with this issue. #5389 migrates a topic from WebSphere Liberty, and adds some information to the migrated topic.

**Comment by dmuelle** [comment]
Hi @jvanhill - I've migrated this information to the Open Liberty docs:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/appSecurity-4.0.html#cahce

Let me know if any further changes are needed for this issue. If not, you can add the `technical reviewed` label to sign off. I believe you intend to address changes to this info w/r/t your new feature in a different issue. If not, we can leave this one open. Thanks!

**Comment by jvanhill** [comment]
I updated the epics and the doc issues to be 22008. That seems most likely, with slight change of 22007.
