### ISSUE TITLE
SEC 380: Migrate "Configuring the Liberty server to track logged out LTPA tokens" to openliberty.io

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/docs#5389]
For feature: [SEC380: Support for distributed Auth Cache in Liberty](https://github.com/OpenLiberty/open-liberty/issues/9005)

As part of SEC 380 (distributed security caches) we need to move the [Configuring the Liberty server to track logged out LTPA tokens](https://www.ibm.com/docs/en/was-liberty/base?topic=cwsrpil-configuring-liberty-server-track-logged-out-ltpa-tokens) topic to the openliberty.io site.

We can start by moving this topic over, but I will also need to add some edits for the final version when the SEC 380 feature is GA'd.

**Comment by chirp1** [comment]
Do this issue with #5388.

**Comment by dmuelle** [comment]
Hi @jvanhill - this information is migrated to Open Liberty at:

https://draft-openlibertyio.mybluemix.net/docs/latest/reference/feature/appSecurity-4.0.html#_track_logged_out_ltpa_tokens

Let me know what further edits are needed. Thanks

**Comment by jvanhill** [comment]
@dmuelle - Looks good.

I will need to open another issue to update this topic when my feature is ready.

**Comment by dmuelle** [comment]
Thanks @jvanhill - going by the labels It looks like SEC-380 was targeted for 22.0.0.4- is that the feature/epic we'll be updating for?

**Comment by dmuelle** [comment]
any updates for the documentation associated with this epic? Thanks

**Comment by jvanhill** [comment]
@dmuelle - My team had reviewed the first half of my changes, and then I haven't been able to circle back in the last week due to pressing customer issues.

**Comment by dmuelle** [comment]
ok thanks- I'll be out next week but can pick up whatever is ready when I return. If this is still targeted for 22.0.0.8, the doc freeze for that release is 7/28
