### ISSUE TITLE
Analyze "Application Bindings"

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5439]
Work with SME to analyze https://www.ibm.com/docs/en/was-liberty/base?topic=manually-application-bindings and migrate relevant info to OL. Information is useful though needs to be reframed for OL/microservices.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Migrated the document from WL to OL.

Draft link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/application-bindings.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
## Initial peer review

I think this topic would benefit from having sub-headings for the various sections. You could split it up into the following headings (these will probably change with SME review, but as a start...)

### Binding precedence
Starts with "Open Liberty supports ..."

### Bindings for specific modules in an application
Starts with "For bindings and extensions that apply to a specific module..."

### Considerations for specifying bindings in the server.xml file
Starts with "In some cases, configuration that was specified in the bindings and extensions files..."

### Examples
includes the last 3 examples. Add an introductory sentence, something like

> The following examples demonstrate binding configurations in the server.xml file for different application scenarios.


---

some general fixes-

> Traditionally, these bindings and extensions are specified in XML files inside the application archive. For example, web application bindings can be defined in the ibm-web-bnd.xml file. In Open Liberty version X.X.X.X and later, bindings and extensions can be specified as part of the application configuration in the server.xml file.
--->

> Traditionally, these bindings and extensions are specified in XML files inside the application archive. For example, web application bindings can be defined in the ibm-web-bnd.xml file. In Open Liberty, you can also specify bindings and extensions as part of the application configuration in the server.xml file.


Move this sentence to the end of the introduction and remove the reference to WDT:

> Some elements that are specified in the bindings and extensions files are not in use by the Open Liberty runtime. For example, in the web application extensions the value of the reload interval attribute is ignored because in Open Liberty reload behavior is controlled by the applicationMonitor configuration. No errors result from specifying these elements in the server.xml configuration. ~~However, specifying these elements in the server.xml configuration can result in unrecognized element warnings when you edit the configuration in the WebSphere Developer Tools.~~


this link is broken, and also not useful (there is no such list in the topic):

> For the full list of bindings and extensions that can be specified in the server.xml file, see [configuration elements in the server.xml file](https://docs-draft-openlibertyio.mybluemix.net/docs/latest/application-bindings.html#server-configuration-overview.adoc#configuration-files).

Instead, link directly to the config elements (use the macro syntax for the links):

For more information about the  bindings and extensions that you can specify in the server.xml file, see the following configuration elements:
- application
- webApplication
- ejbApplication
 
maker sure to run acrolinx- there are a few overlong sentences to fix

 Thanks

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated review comments. 

Draft link: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/application-bindings.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks good- a few minor things things

### Intro
- revise short description to remove passive voice.

> Application bindings and extensions provide ways to define application resources and control various application behaviors. Application bindings can apply to enterprise applications, web applications, or EJB applications.

---->

> You can use application bindings and extensions to define application resources and control various application behaviors. Application bindings can apply to enterprise applications, web applications, or EJB applications

- reduce wordiness

> All enterprise bean (EJB) references and resource references that are defined in the application must be bound to the actual artifacts (enterprise beans or resources) defined in the application server. Only then can you proceed to start the application installed on the application server.

--->

> All enterprise bean (EJB) references and resource references that are defined in the application must be bound to the actual enterprise beans or resources that are defined in the application server.


> Some elements that are specified in the bindings and extensions files are not in use by the Open Liberty runtime. For example, in the web application extensions the value of the reload interval attribute is ignored because in Open Liberty reload behavior is controlled by the applicationMonitor configuration. No errors result from specifying these elements in the server.xml configuration.

--->

> Open Liberty does not use some elements that are specified in the bindings and extensions files. For example, in the web application extensions, the value of the `reload interval` attribute is ignored because in Open Liberty reload behavior is controlled by the `applicationMonitor` configuration. However, no errors result from specifying these elements in the server.xml configuration.


- put the second and 3rd sentences in the intro in the same paragraph.


### Bindings for specific modules in an application

> Similarly for an EJB application that is defined in the stockData.jar file, the following server.xml configuration would specify a data source binding.
--->

> Similarly, the following `server.xml` configuration specifies a data source binding for an EJB application that is defined in the `stockData.jar` file.


In the following example, if the stockDisplay.war file and the stockData.jar file from the previous example were stand-alone applications instead of modules for the stockPrices.ear application, the following configuration can be used.
--->
The following example shows the configuration when the `stockDisplay.war` and `stockData.jar` files from the previous example are stand-alone applications, instead of modules for the `stockPrices.ear` application.


Considerations for specifying bindings in the server.xml file
--->
Child element configuration in the server.xml file

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated additional review comments.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/application-bindings.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
- make sure short description is just 2 sentences
- For bindings and extensions that apply to a specific module within an application, _it might be necessary_ to specify a moduleName attribute in the configuration.
 ---->
For bindings and extensions that apply to a specific module within an application, you might need to specify a moduleName attribute in the configuration.

Change the last heading: Examples----> Server.xml binding examples
for each of the three examples:

The following examples ----> The following example demonstrates

**Comment by ramkumar-k-9286** [comment]
Comments in Was-Liberty Chat group:
--

**Fred Rowe**
Topic is still relevant for a containerized env.  

Comments:
1. The following example shows the configuration when the `stockDisplay.war` and `stockData.jar` files from the previous example are stand-alone applications, instead of modules for the `stockPrices.ear` application.
 The examples location names don't seem quite right.

2. "Specifying a child element as an attribute affects cases."  I don't understand what this means?

3. "For example, web application bindings can be defined in the `ibm-web-bnd.xml` ".  I think it would be useful to list all the xml files used for bindings and extensions because a customer migrating for traditional to Liberty w/o using the TA tools might not know exactly where to look for the config they might want to override in server config. 

Consider instead
"In some cases, configuration that was specified in the bindings and extensions files as a child element must be specified as an attribute in the `server.xml` file.  If the child element has only one possible attribute value, such as shared-session-context in the application extensions file or context-root in the web extensions file, the child element name in the extensions file becomes an attribute name in `server.xml` file. The value of the child element’s single attribute becomes the attribute value in `server.xml.`"

For another review, @bhdaniel is very familiar with this code.

**Comment by ramkumar-k-9286** [comment]
Comments in Was-Docs Chat group:
--
**Brent Daniel**
Hi, it mostly looks OK to me.. I'm not sure what this is trying to say:
`Specifying a child element as an attribute affects cases.`

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated comments.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/application-bindings.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM except for a few minor edits- run acrolinx and fix any issues. Also

The following example demonstrates binding configurations in the server.xml file for resource reference for a managed bean inside an EJB application.
--->
The following example demonstrates binding configurations in the server.xml file for **a** resource reference for a managed bean inside an EJB application.

I think you should also post the updated draft to the slack thread and ask them to confirm whether Deployment is the correct section of the TOC for this topic. Otherwise, I think it's ready to go for 22.0.0.8. Thanks

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated your comment. Ran Acrolinx.

There are 2 sentences that acrolinx says are long. The reason being it has attribute names etc make it long. I did not replace them. This is because reading them made sense and trying to rephrase them would distort the meaning.

The 2 sentences are:

If a security role that is defined in the `server.xml` file matches the security role that is defined in the `ibm-application-bnd.xml` file, the role from the `server.xml` file overwrites the role from the application. 

If the child element has only one possible attribute value, such as `shared-session-context` in the application extensions file or `context-root` in the web extensions file, the child element name in the extensions file becomes the attribute name in `server.xml` file.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/application-bindings.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
a few suggestions:

If a security role that is defined in the server.xml file matches the security role that is defined in the ibm-application-bnd.xml file, the role from the server.xml file overwrites the role from the application.
--->
If a security role in the server.xml file matches a security role in the ibm-application-bnd.xml file, the role from the server.xml file overwrites the role from the application.

---

If the child element has only one possible attribute value, such as shared-session-context in the application extensions file or context-root in the web extensions file, the child element name in the extensions file becomes the attribute name in server.xml file. The value of the child element’s single attribute becomes the attribute value in server.xml.

The following example shows the configuration of context-root in the web extensions file.

--->

Some child elements in these files have only one possible attribute value, such as `shared-session-context` in the application extensions file or `context-root` in the web extensions file. If a child element has only one possible attribute value, the child element name in the extensions file becomes the attribute name in server.xml file. The value of the child element’s single attribute becomes the attribute value in server.xml.

The following example shows the configuration of the `context-root`child element in the web extensions file.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Staging site link: https://staging-openlibertyio.mybluemix.net/docs/latest/application-bindings.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.8, closing this issue
