### ISSUE TITLE
updates to Password encryption doc

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5441]
migrate missing info from https://www.ibm.com/docs/en/was-liberty/base?topic=security-limits-protection-through-password-encryption to https://openliberty.io/docs/latest/password-encryption.html

A few details were omitted from Open Liberty when this was migrated. Add first step in WL topic to OL and check the rest of the page for missing info.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Made some minor updates to the file.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/password-encryption.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

For Review. 

Corrections were made as per Ajay, your suggestions in the chat discussion.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/password-encryption.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Corrections were made as per your suggestions in the chat discussion yesterday.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/password-encryption.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
I still think this could be more clear- it might help is the examples were reversed in order, so we show how to declare the property in a separate file first, and then show how to include that file from the server.xml

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Corrections were made - examples have been reversed in order. 
1. How to declare the property in a separate file. 
2. How to include that file from the server.xml.

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/password-encryption.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks good except

> You can set the property in a separate configuration file and include it in the server.xml file, as shown in the following example.

We just told them before the previous example that you can set the prop in a separate file so this seems redundant.
This introduction statement needs to be revised so that it flows from the previous example. It should make clear that this server.xml configuration is to include the property file from the previous example in the server configuration.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Comment incorporated. 

Draft link: https://draft-openlibertyio.mybluemix.net/docs/latest/password-encryption.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, thanks

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Staging site link: https://staging-openlibertyio.mybluemix.net/docs/latest/password-encryption.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.8, closing this issue
