### ISSUE TITLE
Documention of properties subelement of dataSource is misleading

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/docs#5444]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

The information on https://openliberty.io/docs/latest/relational-database-connections-JDBC.html misled a customer into configuring both `<properties>` and `<properties.postgresql>` under a single `<dataSource>`, leading the customer to open issue https://github.com/OpenLiberty/open-liberty/issues/20971 again Open Liberty.

Recommend changes:

Replace:
"If the JDBC driver data source has setter methods with a String or primitive parameter, you can configure these properties by specifying the `properties` attribute in the `dataSource` element."
with
"If the JDBC driver data source has setter methods with a String or primitive parameter, you can configure these properties by specifying a single `properties` or `properties.{JDBC_VENDOR_TYPE}` subelement under the `dataSource` element."

Replace
```
<properties someProperty="someValue" anotherProperty="5" />
```
with
```
<dataSource jndiName="jdbc/myDB" jdbcDriverRef="myDriver"/>
    <properties someProperty="someValue" anotherProperty="5" />
</dataSource>
```

Replace
```
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties serverName="localhost" portNumber="1234" databaseName="myDB"
                user="exampleUser" password="examplePassword"
                currentLockTimeout="30s"/>
</dataSource>
```
with
```
<dataSource jndiName="jdbc/myDB">
    <jdbcDriver libraryRef="jdbcLib"/>
    <properties.db2.jcc
                serverName="localhost" portNumber="50000" databaseName="myDB"
                user="exampleUser" password="examplePassword"
                currentLockTimeout="30s"/>
</dataSource>
```

**Comment by bmarwell** [comment]
Not a native speaker, but maybe adding the word "either" helps to clarify even better.

"... properties by EITHER specifying X or y"

**Comment by dmuelle** [comment]
Hi @njr-11 @bmarwell, I've made the specified update in our draft doc:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/relational-database-connections-JDBC.html#_data_source_configuration

Would it also be helpful to explain when a user might use `properties` vs `properties.{JDBC_VENDOR_TYPE}` ? We've provided examples for both, but how would a user know whether they need a specific vendor element or just the generic `properties` ? If we can clarify that further, it might make it more clear that they are mutually exclusive and you dont need both.

Either way, i think we can get this update included in the 22.0.0.5 docs release next week. Let me know what you think.

Thanks

**Comment by bmarwell** [comment]
LGTM! Thank you for your great work! 🙏🏻

**Comment by njr-11** [comment]
> Would it also be helpful to explain when a user might use `properties` vs `properties.{JDBC_VENDOR_TYPE}` ? We've provided examples for both, but how would a user know whether they need a specific vendor element or just the generic `properties` ? If we can clarify that further, it might make it more clear that they are mutually exclusive and you dont need both.

@dmuelle Thanks for adding these updates!  And good idea - if you want to add that, a good place might be,

"... subelement under the dataSource element.  Use a `properties.{JDBC_VENDOR_TYPE}` subelement if Liberty provides one for the JDBC driver that you are using.  Otherwise, use a `properties` subelement."

**Comment by dmuelle** [comment]
updated the draft to clarify properties vs vendor specific properties element:

https://draft-openlibertyio.mybluemix.net/docs/latest/relational-database-connections-JDBC.html


if no further changes are needed, the updates are set to publish on 5/10 with the 22.0.0.5 docs release. Thanks!

**Comment by dmuelle** [comment]
updated the draft to clarify properties vs vendor specific properties element:

https://draft-openlibertyio.mybluemix.net/docs/latest/relational-database-connections-JDBC.html#_data_source_configuration


if no further changes are needed, the updates are set to publish on 5/10 with the 22.0.0.5 docs release. Thanks!

**Comment by dmuelle** [comment]
changes are on vNext and will publish with the 22.0.0.5 docs release- closing this issue.
