### ISSUE TITLE
Update the JSON logs events reference list with new app name field

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/docs#5472]
As part of the feature [LG-331: Add application name to LogRecordContext Extension](https://github.com/OpenLiberty/open-liberty/issues/19641), a new default JSON field (`ext_appName`) was added to the JSON logs. 
Need to update the following documentation: https://openliberty.io/docs/latest/json-log-events-list.html

In the above documentation, the following tables should be updated to add the following row:

- [ ] In the Messages event fields, add the following row:

| **Field** | **Description** |
| ------------- | ------------- |
| ext_appName  | The name of the application that logged the message. |

Update the message event example to include the new field, as follows:
```
{
    "type":"liberty_message",
    "host":"9e1eceec70c1",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"defaultServer",
    "message":"BADAP0004W: BadApp Angry for test",
    "ibm_threadId":"0000009f",
    "ibm_datetime":"2020-05-04T12:33:26.064+0000",
    "ibm_messageId":"BADAP0004W",
    "module":"com.ibm.ws.lumberjack.badness.Angry",
    "loglevel":"WARNING",
    "ibm_methodName":"doGet",
    "ibm_className":"Angry",
    "ibm_sequence":"1588595606064_0000000000024",
    "ext_thread":"Default Executor-thread-108",
    "ext_appName":"BadApp"
}
```
- [ ] In the Trace event fields, add the following row:

| **Field** | **Description** |
| ------------- | ------------- |
| ext_appName  | The name of the application that logged the message. |

Update the trace event example to include the new field, as follows:
```
{
    "type":"liberty_trace",
    "host":"9e1eceec70c1",
    "ibm_userDir":"\/opt\/ol\/wlp\/usr\/",
    "ibm_serverName":"defaultServer",
    "message":"BadApp Angry test",
    "ibm_threadId":"0000009f",
    "ibm_datetime":"2020-05-04T12:33:26.066+0000",
    "ibm_messageId":"BADAP0001W",
    "module":"com.ibm.ws.lumberjack.badness.Angry",
    "loglevel":"FINE",
    "ibm_methodName":"doGet",
    "ibm_className":"Angry",
    "ibm_sequence":"1588595606066_0000000000001",
    "ext_thread":"Default Executor-thread-108",
    "ext_appName":"BadApp"
}
```

**Comment by dmuelle** [comment]
Hi @pgunapal - the epic says the target is 21.0.0.7 beta- is that correct? If not, when should we target the update to publish?

**Comment by pgunapal** [comment]
@dmuelle The feature is being beta'ed for 21.0.0.7-beta. We will be targetting to GA it for 21.0.0.7. So, I believe the doc updates should go in for 21.0.0.7.

**Comment by dmuelle** [comment]
I assume you mean 22.0.0.7? I wasn't sure if this was something that had previously been in beta that was never released

**Comment by pgunapal** [comment]
Yes, I do mean 22.0.0.7! :) I fixed the Epic label as well, to indicate 22.0.0.7-beta.

**Comment by dmuelle** [comment]
Hi @pgunapal - this update is now on draft:

https://draft-openlibertyio.mybluemix.net/docs/latest/json-log-events-list.html

Let me know if any further changes are needed. If not, you can add the `technical reviewed` label to this issue to sign off and the update will publish with the 22.0.0.7 docs release. Thanks!

**Comment by pgunapal** [comment]
@dmuelle Changes looks good, added the `technical reviewed` label. Thanks!

**Comment by dmuelle** [comment]
content is on vNext and will publish with 22.0.0.7- closing this issue
