### ISSUE TITLE
Update `Log and trace configuration` page to include new stack join feature

### ISSUE THREAD

**Issue by Channyboy** [OpenLiberty/docs#5477]
Related EPIC: https://github.com/OpenLiberty/open-liberty/issues/1598

Update the page to include the new stack join feature configuration.

**Comment by dmuelle** [comment]
Hi @Channyboy - this update is now on draft at the end of the table here:

https://draft-openlibertyio.mybluemix.net/docs/latest/log-trace-configuration.html#settings

Let me know if any further changes are needed. If not, you can add the `technical reviewed` label to this issue to sign off and the update will publish with the 22.0.0.7 docs release. Thanks!

**Comment by dmuelle** [comment]
just realized this is dependent on [stackTraceSingleEntry](https://github.com/OpenLiberty/open-liberty/pull/21348) and the attribute name is changing

**Comment by Channyboy** [comment]
Oh yes, sorry, will need to change the configuration assuming nothing else goes wrong :D

**Comment by dmuelle** [comment]
new draft with  `stackTraceSingleEntry`, `com.ibm.ws.logging.stack.trace.single.entry`, and `WLP_LOGGING_STACK_TRACE_SINGLE_ENTRY` as the final entry in the table:

https://draft-openlibertyio.mybluemix.net/docs/latest/log-trace-configuration.html#settings

**Comment by Channyboy** [comment]
@dmuelle  The bootstrap properties was `com.ibm.ws.logging.stackTraceSingleEntry`

**Comment by dmuelle** [comment]
updated draft to fix that bootstrap property: https://draft-openlibertyio.mybluemix.net/docs/latest/log-trace-configuration.html#settings

**Comment by dmuelle** [comment]
changes are on vNExt and will publish with 22.0.0.7
