### ISSUE TITLE
Update dev mode doc for feature generation

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/docs#5550]
Update documentation for Liberty dev mode to include description of new feature generation functionality

**Comment by TrevCraw** [comment]
Update suggestions for the Dev mode page: https://openliberty.io/docs/latest/development-mode.html

For the "Detect, recompile, and deploy code changes" section

(paragraph below the bullet points - remove last line)

Resource file, configuration file, and configuration directory changes are copied into your target directory. New dependencies in your pom.xml file or build.gradle file are added to your class path. ~~New features are installed and started.~~ 

(add new paragraph right after the one above)

Dev mode detects the required Liberty features for your application based on API usage and generates a feature list in a new server configuration file named `generated-features.xml`, which is created in the `src/main/liberty/config/configDropins/overrides` directory. Java source file changes, server configuration changes, and build file changes may result in new Liberty features being generated. New features, whether manually added or generated, are installed and started automatically. You can toggle the automatic generation of features on and off by typing `g` and pressing `Enter`.

(update last paragraph in this section - italics are new additions)

You can configure how dev mode handles changes to your code by specifying parameters when you start dev mode. _You can also view a help menu of available dev mode console actions by typing `h` and pressing `Enter`._ For more information about configuration parameters _and console actions_, see [the dev goal of the Open Liberty Maven plug-in](https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#dev) or [the libertyDev task of the Open Liberty Gradle plug-in](https://github.com/OpenLiberty/ci.gradle/blob/main/docs/libertyDev.md#libertydev-task).

**Comment by TrevCraw** [comment]
Another request is to change all references to `Open Liberty Maven plug-in` to `Liberty Maven plug-in` and `Open Liberty Gradle plug-in` to `Liberty Gradle plug-in`

**Comment by dmuelle** [comment]
Draft is now updated with these changes:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/development-mode.html

Im wondering if its worth putting feature generation under a heading? Depending on how consequential it is to the overall Dev Mode user experience. The text reads fine, but I wonder if someone went looking for this info they might miss it

**Comment by TrevCraw** [comment]
> Im wondering if its worth putting feature generation under a heading? Depending on how consequential it is to the overall Dev Mode user experience. The text reads fine, but I wonder if someone went looking for this info they might miss it

Updated suggestion:

(Still remove last line)
Resource file, configuration file, and configuration directory changes are copied into your target directory. New dependencies in your pom.xml file or build.gradle file are added to your class path. **~~New features are installed and started.~~**

(New paragraph)
_Liberty features will be automatically generated in server configuration.  New features, whether manually added or generated, are installed and enabled automatically._

(Small update to console action section)
You can configure how dev mode handles changes to your code by specifying parameters when you start dev mode. **_Once dev mode is started,_** you can also view a help menu of dev mode console actions by typing h and pressing Enter. For more information about configuration parameters and console actions, see [the dev goal of the Liberty Maven plug-in](https://github.com/OpenLiberty/ci.maven/blob/main/docs/dev.md#dev) or [the libertyDev task of the Liberty Gradle plug-in](https://github.com/OpenLiberty/ci.gradle/blob/main/docs/libertyDev.md#libertydev-task).

(New sub-heading)
_Automatic generation of Liberty features in server configuration_

(small change in paragraph)
Dev mode detects the Liberty features that your application requires based on API usage and generates a feature list in a new server configuration file. The file is named generated-features.xml and is created in the src/main/liberty/config/configDropins/overrides directory. Java source file changes, server configuration changes, and build file changes might result in new Liberty features being generated. **_Generated features are installed and enabled automatically._** You can toggle the automatic generation of features on and off by typing g and pressing Enter.

**Comment by dmuelle** [comment]
updated draft: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/development-mode.html

**Comment by dmuelle** [comment]
content is on vNext and will publish with 22006, closing this issue.
