### ISSUE TITLE
Update OL docs topic log-trace-configuration

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/docs#5575]
cf. slack thread https://ibm-cloud.slack.com/archives/C31GDK73P/p1654623828676159

Info in https://openliberty.io/docs/latest/log-trace-configuration.html could be made more clear.  For the third bullet of the second paragraph consider this change:

trace.log - This file is created only if you enable trace and contains all the content of messages.log plus any enabled trace. This file does not contain messages that are written directly by the JVM process.

Alasdair mentioned in a slack thread the KC version of this doc is under consideration for deletion in favor of OL docs.  If it is not deleted, I would suggest similar updates and correct this:

Table 2. Valid logging levels. The following table lists the valid levels for application servers at **WebSphere Application Server Version 6 and later.**

**Comment by dmuelle** [comment]
Hi @frowe - I've updated the draft at https://docs-draft-openlibertyio.mybluemix.net/docs/latest/log-trace-configuration.html per your comments here and in the slack thread.

Although this topic will replace the IBM Docs topic at some point, I made similar updates there:
https://ibmdocs-test.mybluemix.net/docs/en/SSAW57_liberty_test?topic=liberty-logging-trace
 
I removed references to tWAS 6.0

**Comment by dmuelle** [comment]
Sorry, just realized I misread your comment.  I removed reference to WAS 6.0 from the table description

**Comment by frowe** [comment]
looks good

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.7
