### ISSUE TITLE
Explaining GraphQL concept suggestion

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#5576]
Document: Build GraphQL applications with MicroProfile GraphQL
http://openliberty.io/docs/latest/microprofile-graphql.html

Just been reading this topic to find out what the GraphQL support is about.

I would suggest that the following paragraph (from the first sub-section), which nicely explains why you should care about GraphQL would be better at the start of that section (and even touched on in the first para/abstract of the article even), rather than talking about schemas etc and how GraphQL works first. Don't really care how it works if you don't understand what the point of it is in the first place.

> "You can use a GraphQL service to obtain data from multiple sources such as APIs, databases, and other services. The GraphQL service can then collate this data into a single object, which simplifies the data retrieval. You make only a single request to the GraphQL service, instead of multiple requests to the individual data sources. GraphQL services require less data fetching than REST services, which results in faster application load times and lower data transfer costs. GraphQL also enables clients to better customize requests to the server."

**Comment by dmuelle** [comment]
Thanks @lauracowen , will fix this as part of the other GQL issue #5577
