### ISSUE TITLE
systemd

### ISSUE THREAD

**Issue by alanlima25** [OpenLiberty/docs#5586]
Document: Default environment variables
http://openliberty.io/docs/22.0.0.5/reference/default-environment-variables.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by dmuelle** [comment]
Hi @alanlima25 - can you give us some information about the specific problem you are having with this page? Thanks

**Comment by dmuelle** [comment]
closing due to lack of information- feel free to re-open or open another if you are having trouble with the doc. Thanks
