### ISSUE TITLE
Update `access-logging` and `log-trace-configuration` with timed log rollover configuration options

### ISSUE THREAD

**Issue by ellen-lau** [OpenLiberty/docs#5637]
Related OpenLiberty Epic: https://github.com/OpenLiberty/open-liberty/issues/16067

Add explanation sections for new logging server configuration attributes `rolloverStartTime` and `rolloverInterval` in `access-logging` and `log-trace-configuration` docs.

Add new logging server configuration attributes `rolloverStartTime` and `rolloverInterval` to `log-trace-configuration` doc's configuration settings section.

**Comment by ellen-lau** [comment]
1.

**Edit file: `modules/ROOT/pages/access-logging.adoc`, adding section to describe new attributes with examples:**

Time-based HTTP access log rollover

You can enable time-based periodic rollover of your HTTP access log file by specifying a log rollover start time and a log rollover interval duration. The specified rollover start time is your desired time of day when the HTTP access log file should first roll over. The rollover interval duration is the time interval in between consecutive HTTP access log file rollovers.

 For example, a server with a rollover start time of midnight and a rollover interval of 1 day will roll over its HTTP access log once every day, at midnight.

 Enable time-based rollover of your HTTP access log file by using the `rolloverStartTime` and `rolloverInterval` attributes of the `httpAccessLogging` or `accessLogging` elements in the `server.xml` file. The following table lists the two attributes, and their respective descriptions and permitted values.

Time-based log rollover attribute | Description |
--- | ---
rolloverStartTime | Use this setting alone or with the `rolloverInterval` attribute to enable time-based log rollover for your HTTP access log file. This setting specifies the scheduled time of day for logs to first rollover. The `rolloverInterval` setting duration begins at `rolloverStartTime`. Valid values follow a 24-hour ISO-8601 date-time format of HH:MM, where 00:00 represents midnight. Padding zeros are required. If the `rolloverInterval` attribute is specified, the default value of the `rolloverStartTime` attribute is 00:00, midnight.
rolloverInterval | Use this setting alone or with the `rolloverStartTime` attribute to enable time-based log rollover for your HTTP access log file. This setting specifies the time interval in between log rollovers, in minutes if a unit of time is not specified. Specify a positive integer followed by a unit of time, which can be days (d), hours (h), or minutes (m). For example, specify 5 hours as 5h. You can include multiple values in a single entry. For example, 1d5h is equivalent to 1 day and 5 hours. If the `rolloverStartTime` attribute is specified, the default value of the `rolloverInterval` attribute is 1 day.

The following examples have time-based periodic rollover enabled for the HTTP access log file in the `httpAcccessLogging` and `accessLogging` elements, with the `rolloverStartTime` attribute set to  midnight and the `rolloverInterval` attribute set to 1 day:

```
<httpAccessLogging rolloverStartTime="00:00" rolloverInterval="1d"/>
```

 or

```
 <httpEndpoint id="defaultHttpEndpoint" httpPort="9080" httpsPort="9443">
    <accessLogging filepath="${server.output.dir}/logs/http_defaultEndpoint_access.log"
                  rolloverStartTime="00:00" rolloverInterval="1d" />
 </httpEndpoint>
```

2.

**Edit file: `modules/ROOT/pages/log-trace-configuration.adoc`:**
a) Adding section to describe new attributes with examples:

Time-based log rollover

You can enable time-based periodic rollover of Liberty messages and trace logs by specifying a log rollover start time and a log rollover interval duration. The specified rollover start time is your desired time of day when logs should first rollover. The rollover interval duration is the time interval in between consecutive log rollovers.

 For example, a server with a rollover start time of midnight and a rollover interval of 1 day will roll over its messages and trace logs once every day, at midnight.

 You can configure rollover for Open Liberty messages and trace logs by either editing the `bootstrap.properties` file, specifying environment variables, or using server configuration attributes. The following examples show the configuration for each of these options, with a log rollover start time of midnight and a log rollover interval of 1 day:

 * Configure time-based log rollover in the `bootstrap.properties` file:

```
 com.ibm.ws.logging.rollover.start.time=00:00
 com.ibm.ws.logging.rollover.interval=1m
```
 * Configure time-based log rollover with environment variables in the `server.env` file:

```
 WLP_LOGGING_ROLLOVER_START_TIME=00:00
 WLP_LOGGING_ROLLOVER_INTERVAL=1m
```
 * Configure time-based log rollover with server configuration attributes in the `server.xml` file:
```
 <logging rolloverStartTime="00:00" rolloverInterval="1d"/>
```

b) Adding the descriptions for the two new attributes under Section "Configuration settings by source":

Server XML Attribute | bootstrap property | Env var | Description
--- | ---  | ---  | ---
rolloverStartTime | com.ibm.ws.logging.rollover.start.time | WLP_LOGGING_ROLLOVER_START_TIME | Use this setting alone or with the `rolloverInterval` attribute to enable time-based log rollover for `messages.log` and `trace.log` files. This setting specifies the scheduled time of day for logs to first rollover. The `rolloverInterval` setting duration begins at `rolloverStartTime`. Valid values follow a 24-hour ISO-8601 date-time format of HH:MM, where 00:00 represents midnight. Padding zeros are required. If the `rolloverInterval` attribute is specified, the default value of the `rolloverStartTime` attribute is 00:00, midnight. The `console.log` does not roll so this setting does not apply.
rolloverInterval | com.ibm.ws.logging.rollover.interval |WLP_LOGGING_ROLLOVER_INTERVAL | Use this setting alone or with the `rolloverStartTime` attribute to enable time-based log rollover for `messages.log` and `trace.log` files. This setting specifies the time interval in between log rollovers, in minutes if a unit of time is not specified. Specify a positive integer followed by a unit of time, which can be days (d), hours (h), or minutes (m). For example, specify 5 hours as 5h. You can include multiple values in a single entry. For example, 1d5h is equivalent to 1 day and 5 hours. If the `rolloverStartTime` attribute is specified, the default value of the `rolloverInterval` attribute is 1 day. The `console.log` does not roll so this setting does not apply.

**Comment by dmuelle** [comment]
Hi @ellen-lau - these updates are now ready for review on our draft site:

https://draft-openlibertyio.mybluemix.net/docs/latest/access-logging.html#_time_based_http_access_log_rollover

On this page, we provide two examples at the end of the section

> The following examples demonstrate how to enable time-based periodic rollover for the HTTP access log file in the httpAcccessLogging and accessLogging elements, with the rolloverStartTime attribute set to midnight and the rolloverInterval attribute set to 1 day.

What is the functional difference between these two configurations? Is `httpAcccessLogging` a global setting and `httpEndpoint>accessLogging` applies only to the specified endpoint?

---


https://draft-openlibertyio.mybluemix.net/docs/latest/log-trace-configuration.html#rollover

~~For this page and the other- all the `rolloverStartTime` examples use 00:00 as the value- but isn;'t that the default? Do you need to specify it at all if you want it to roll over at midnight? If so, what is the significance of the default?~~

Thanks!

**Comment by dmuelle** [comment]
Disregard that last question- i think the doc makes it evident that the default start time is applied if you specify an interval without a start time.

**Comment by ellen-lau** [comment]
Hi @dmuelle,

The updates on the draft pages look good.

Regarding your question:

What is the functional difference between these two configurations? Is httpAccessLogging a global setting and httpEndpoint>accessLogging applies only to the specified endpoint?

Yes, that's correct:

`httpAccessLogging` is access logging config with an id, which is shareable across HttpEndpoints.
```
httpAccessLogging
```

`accessLogging` within `httpEndpoint` is the "anonymous" access logging config within the scope of 1 endpoint.

```
httpEndpoint
    accessLogging
```

Thanks,
Ellen

**Comment by dmuelle** [comment]
Hi Ellen,

I made some minor edits to clarify this info in the examples:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/access-logging.html#_time_based_http_access_log_rollover

If any further edits are needed, just let me know. If not, you can add the `technical reviewed` label to this issue and the updates will publish with the 22.0.0.8 docs release. Thanks

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.8, closing this issue
