### ISSUE TITLE
Suggested updates for the JDBC driver trace doc

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5644]
opened to track updates provided by @KyleAure in #5639

**Comment by dmuelle** [comment]
Hi @KyleAure - these updates are now ready for review on our draft site:

https://draft-openlibertyio.mybluemix.net/docs/latest/jdbc-tracing.html#PostgreSQL

If any further changes are needed, just let me know. Otherwise, you can sign off by adding the technical reviewed label to this issue and the changes wil publish with the next release. Thanks!

**Comment by KyleAure** [comment]
Received a 404 from the domain https://draft-openlibertyio.mybluemix.net.  I'll check back later today to see if the site is back up.

**Comment by dmuelle** [comment]
sorry about that- should be back now but you can also try

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/jdbc-tracing.html#PostgreSQL

**Comment by dmuelle** [comment]
changes are on vNext and will publish with the 22.0.0.8 release. Closing this issue. Thanks!
