### ISSUE TITLE
 Updates to dev mode doc 

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5645]
opened to track changes proposed by @ilovechai in in #5643 

Docs team will recreate the changes from a vNext based branch and deliver to draft for review, per [docs process](https://github.com/OpenLiberty/docs#updating-an-existing-topic)
 
 Also update auto feature generation info to be off by default

**Comment by dmuelle** [comment]
Hi @KyleAure - these updates are now ready for review on our draft site:

https://draft-openlibertyio.mybluemix.net/docs/latest/jdbc-tracing.html#PostgreSQL

If any further changes are needed, just let me know. Otherwise, you can sign off by adding the `technical reviewed` label to this issue and the changes wil publish with the next release. Thanks!

**Comment by TrevCraw** [comment]
Proposed changes to reflect new default functionality regarding automatic generation of features. Suggested changes are in bold:

"Detect, recompile, and deploy code changes" section

**If automatic generation of features is turned on (off by default in dev mode),** Liberty features that your application requires are automatically generated in your server configuration. New features, whether added manually or generated, are installed and enabled automatically.


"Automatically generate Liberty features in your server configuration" section


**If automatic generation of features is turned on (off by default in dev mode),** dev mode detects the Liberty features that your application requires based on API usage and generates a feature list in a new server configuration file. The file is named generated-features.xml and is created in the src/main/liberty/config/configDropins/overrides directory. Java source file changes, server configuration changes, and build file changes might result in new Liberty features being generated. Generated features are installed and enabled automatically. 

**(suggestion to split into two paragraphs)**

When dev mode is running, you can toggle the automatic generation of features on and off by typing g and pressing Enter. **Or, before starting dev mode, you can set the** `generateFeatures` **parameter to be true from the command line to have automatic generation of features turned on from dev mode startup, as shown in the examples below:**


**Maven:** `mvn liberty:dev -DgenerateFeatures=true`

**Gradle:** `gradle libertyDev --generateFeatures=true`

**Comment by dmuelle** [comment]
Hi Trevor- here's the updated draft:

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/development-mode.html#auto

If any further changes are needed, just let me know. Otherwise, you can add the `technical reviewed` label to this issue and the edits will publish with 22.0.0.8. Thanks!

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.8, closing this issue
