### ISSUE TITLE
Remove 20.0.0.7 documentation and update doc publication instructions

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/docs#5657]
Remove the 20.0.0.7 documentation from openliberty.io (i.e. remove from antora playbook) and keep the 20.0.0.7 documentation on GitHub.

Update the documentation instructions to remove documentation for Open Liberty releases that are over 2 years old. This can be done in the instructions for release new versions https://github.com/OpenLiberty/docs-playbook#publishing-the-docs-and-preparing-for-the-next-release

# To-do list
- [x] Remove 20.0.0.7 from all development sites and openliberty.io
- [x] Update instructions to remove versions when adding new versions

**Comment by dmuelle** [comment]
Hi Kin-  a few questions:
- Do we only need to remove `20.0.0.7` from the list of branches in the [docs-playbook](https://github.com/OpenLiberty/docs-playbook)/antora-playbook.yml file to pull 20.0.0.7 from openliberty.io? 
- if this change doesn't go live until the next docs release, we'll probably want to remove 20.0.0.8 as well?

**Comment by dmuelle** [comment]
revised my question list after reading your description more closely

**Comment by kinueng** [comment]
Hi @dmuelle,

> - Do we only need to remove 20.0.0.7 from the list of branches in the [docs-playbook](https://github.com/OpenLiberty/docs-playbook)/antora-playbook.yml file to pull 20.0.0.7 from openliberty.io? 

Yes, removing `v20.0.0.7` from the two arrays in [antora-playbook.yml](https://github.com/OpenLiberty/docs-playbook/blob/491e1ec97982b8584642eb2fde9420a52c5600e4/antora-playbook.yml#L6-L9) will cause openliberty.io to ignore the `v20.0.0.7` branches in repo https://github.com/OpenLiberty/docs and https://github.com/OpenLiberty/docs-generated during the build. The playbook tells the build which branches to `git clone` during build time.

> - if this change doesn't go live until the next docs release, we'll probably want to remove 20.0.0.8 as well?

I think it is fine to go ahead and remove `v20.0.0.7` from the playbook now and we can refresh production. I am also OK with waiting for when we are preparing 20.0.0.8 and including the removal work too.

# Additional details

We also have to decide what to do the removed versions in our `staging` and `draft` development sites. Currently, we have `v20.0.0.7-staging` and `v20.0.0.7-draft` branches on repo `OpenLiberty/docs` and `OpenLiberty/docs-generated`. The playbook uses a regular expression to pull in any branches that match `v*.0.0.*-staging` and `v*.0.0.*-draft`. I am leaning towards deleting `*-staging` and `*-draft` related to versions that have been removed from openliberty.io (but still remain as a branch on GitHub). @mbroz2, what is your opinion on `*-staging` and `*-draft` documentation branches belonging to versions that have been removed from openliberty.io?

**Comment by mbroz2** [comment]
regarding draft and staging, I recommend removing them from the draft & staging playbooks, but not touching the branches (aka, the exact same thing as prod).  And again, just make sure it's documented as such.

The reason we don't want to keep building these old branches in draft and staging is because it incurs extra build cost (both time to build, and resulting image size... and then the memory (disk & ram) necessary to run it).  The reason I don't want to delete the branches is because there's no added value in doing so, and it's an extra step (time) that someone has to do each release.  Also, in the unlikely event that we'd want to go back and make older docs available, we'd have them readily available.

**Comment by dmuelle** [comment]
ok- I created a[ PR to remove 20.0.0.7](https://github.com/OpenLiberty/docs-playbook/pull/207) from the list of branches in production,  but staging and draft define the branches differently:

```yaml
  - url: https://github.com/OpenLiberty/docs.git
    branches: [v*.0.0.*-staging, staging]
  - url: https://github.com/OpenLiberty/docs-generated.git
    branches: [v*.0.0.*-staging, staging] 
```

is there a way to exclude 20.0.0.7 from the wildcard or do I need to recreate the list of branches in the draft and staging yaml files?

**Comment by dmuelle** [comment]
is there a way to exclude 20.0.0.7 from the wildcard or do I need to recreate the list of branches in the draft and staging yaml files?

**Comment by mbroz2** [comment]
you can negate with `!` as documented on Antora: https://docs.antora.org/antora/latest/playbook/content-branches/#branches-key

**Comment by kinueng** [comment]
The Antora build did not like how the `!` is used in the `draft` branch playbook. **EDIT: I suspect the fix is to wrap the `!` in single quotes**
```
[20:46:54.790] FATAL (antora): tag suffix cannot contain flow indicator characters (7:48) in /workspace/dc584cb5-7637-4950-9c3f-a2b20edcc0fc/src/main/content/docs/antora-playbook.yml (cwd: /workspace/dc584cb5-7637-4950-9c3f-a2b20edcc0fc, playbook: src/main/content/docs/antora-playbook.yml)

 4 |  ... 
 5 |  ... 
 6 |  ... /github.com/OpenLiberty/docs.git
 7 |  ... *.0.0.*-draft,!v20.0.0.7-draft, draft]
-----------------------------------------^
 8 |  ... /github.com/OpenLiberty/docs-generated.git
 9 |  ... raft]
    Cause: YAMLException
        at generateError (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:183:10)
        at throwError (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:187:9)
        at readTagProperty (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1275:7)
        at composeNode (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1407:12)
        at readFlowCollection (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:780:5)
        at composeNode (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1442:11)
        at readBlockMapping (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1164:11)
        at composeNode (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1441:12)
        at readBlockSequence (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1008:5)
        at composeNode (/root/.nvm/versions/node/v16.16.0/lib/node_modules/@antora/cli/node_modules/js-yaml/lib/loader.js:1472:45)
Job execution ended at Wed Jul 20 20:46:54 UTC 2022
```

**Comment by kinueng** [comment]
`staging` test fix https://github.com/OpenLiberty/docs-playbook/commit/940e9be58013317274d8acce5d95ee202d7c75f0
`draft` test fix https://github.com/OpenLiberty/docs-playbook/commit/0634657e30811c2455a8c9d35f54604b8bcddd93

**Comment by dmuelle** [comment]
sorry- missed that in the antora doc, thanks for fixing

**Comment by dmuelle** [comment]
updated instructions and will apply for releases going forward
