### ISSUE TITLE
VARIABLE_SOURCE_DIRS

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/docs#5668]
The name of the `VARIABLE_SOURCE_DIRS` variable indicates that multiple directories can be specified. However, the documentation on https://openliberty.io/docs/latest/reference/default-environment-variables.html or https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#variable-substitution does not mention what separator to use when specifying multiple directories. 

Also, on https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#variable-substitution step 5 is described as `Variables loaded from files in the ${server.config.dir}/variables directory` which seems a bit incomplete. Maybe that can be clarified by saying `Variables loaded from files in the ${server.config.dir}/variables directory or other directories as specified by the VARIABLE_SOURCE_DIRS environment variable`

**Comment by dmuelle** [comment]
Thanks- @jgawor - What separator would you use to define multiple directories in this variable? Would it be a pipe or a comma? or semicolon? Could you provide an example?

**Comment by jgawor** [comment]
Based on the code it looks like the it's the path separator (`;` on windows and `:` on *nix). @brenthdaniel can you confirm?

**Comment by brenthdaniel** [comment]
yes, it's the system specific path separator

**Comment by ramkumar-k-9286** [comment]
Hi Jarek @jgawor 

The suggested corrections have been made to the files.
The draft links for the pages are added below.

Draft links: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/default-environment-variables.html

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/config/server-configuration-overview.html#variable-substitution

Regards,
Ramkumar

CC @dmuelle

**Comment by jgawor** [comment]
@ramkumar-k-9286 looks good. thank you!

**Comment by dmuelle** [comment]
Looks good-  a slight edit to clarify and remove passive voice:

The system-specific path separator that is used to define multiple directories in this variable is a ; on Microsoft Windows or a : on Unix.
-->
To define a list of directories as the value for this variable, separate each directory with the path separator for your operating system. For Windows, the path separator is a semicolon (`;`). For Unix-based systems, the path separator is a colon (`:`).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Suggested comments incorporated.

Draft links: https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/default-environment-variables.html

https://docs-draft-openlibertyio.mybluemix.net/docs/latest/reference/config/server-configuration-overview.html#variable-substitution

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- send it to staging when you get a chance, thanks

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Staging site links:

https://docs-staging-openlibertyio.mybluemix.net/docs/latest/reference/default-environment-variables.html

https://docs-staging-openlibertyio.mybluemix.net/docs/latest/reference/config/server-configuration-overview.html#variable-substitution

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
changes are on vNext and will publish with the 22.0.0.9 release. 

Closing this issue. Thanks!
