### ISSUE TITLE
Docs updates for MP OpenAPI 3.1

### ISSUE THREAD

**Issue by Azquelt** [OpenLiberty/docs#5678]
The only things I can see that would need doing are:
* The config examples on the [MP OpenAPI 3.0 feature page][30-feature-page] should be carried across to the 3.1 page. I'm not sure whether this happens automatically or needs to be done manually.
* The [guide] should be updated to the latest version
* Documenting the `mp.openapi.scan.beanvalidation` property. This is already listed on OpenLiberty/docs#505 and I don't think there's anything else to do here.

Epic: OpenLiberty/open-liberty#20040

[30-feature-page]: https://openliberty.io/docs/latest/reference/feature/mpOpenAPI-3.0.html
[guide]: https://openliberty.io/guides/microprofile-openapi.html

**Comment by dmuelle** [comment]
Hi @Azquelt - I'm not sure we have any actual updates to make in the docs-

- config examples from MP OpenAPI 3.0 will go across to 3.1 automatically
- the guides are managed separately from the docs and are handled by the guides team. I'm not sure what their update process is but I [opened an issue in the repo for this guide](https://github.com/OpenLiberty/guide-microprofile-openapi/issues/154) to request the update.
-  `mp.openapi.scan.beanvalidation` is documented on the [MP Config properties page](https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html#openapi), which in currently in draft but is targeted to publish with 22.0.0.9. We don't currently list a minimum version for this property- is it available from 1.0? And are there any changes to it in the 3.1 version?

Let me know if any further edits are needed. If not, I think we can close this issue. Thanks

**Comment by gkwan-ibm** [comment]
hi @Azquelt is MP OpenAPI 3.1 belongs to MP 5.x? In https://github.com/eclipse/microprofile/releases, I didn't see any MP 5.0+.

**Comment by Azquelt** [comment]
@dmuelle
> We don't currently list a minimum version for this property- is it available from 1.0?

No, it's only available from 3.1 onwards.

**Comment by Azquelt** [comment]
@gkwan-ibm No, the spec will be included in MP 6.0.

**Comment by Azquelt** [comment]
There's been a change to when we want to release this feature. Originally we were targeting 22.0.0.9, but now we're going to wait and release it alongside the rest of MicroProfile 6.0.

**Comment by dmuelle** [comment]
ok, i think the only needed change is to hold the `mp.openapi.scan.beanvalidation` property out from  the [MP Config properties page](https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html#openapi) if that goes live before MP 6.0. I'll keep this issue open to keep track of that. Thanks

**Comment by dmuelle** [comment]
Hi @Azquelt - the property is now documented on the [draft MP config properties page](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-config-properties.html#openapi) and ready to publish w/ 23.0.0.3.

Should anything be added to the [Differences between MicroProfile 6.0 and 5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/mp-50-60-diff.html) page for OpenAPI 3.1?

**Comment by dmuelle** [comment]
Hi @Azquelt - the blurb on the "Differences.." page is ready for review when you have a chance:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/mp-50-60-diff.html#openapi

**Comment by dmuelle** [comment]
Updates per this issue:

[MP Config properties page](https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html#openapi)
[DIfferences between OpenPAI 3.1 and 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/mp-50-60-diff.html#openapi)

@Azquelt I believe this issue is ready for final review. If any further edits are needed, please let me know. If not, you can sign off by adding the `Technical reviewed` label to this issue. Thanks

**Comment by Azquelt** [comment]
Yep, it looks good to me, thanks @dmuelle

**Comment by dmuelle** [comment]
@ramkumar-k-9286 = this is ready for peer review

[MP Config properties page](https://draft-openlibertyio.mybluemix.net/docs/latest/microprofile-config-properties.html#openapi)
[DIfferences between OpenPAI 3.1 and 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/mp-50-60-diff.html#openapi)

**Comment by ramkumar-k-9286** [comment]
Peer Review
---
**MP Config properties page**

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-config-properties.html#openapi

**mp.openapi.extensions.liberty.merged.info**

The value must be a [valid OpenAPI info section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#infoObject) in JSON format.
->
The value must be a [valid OpenAPI info section](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.3.md#infoObject) in JSON format. ( the link goes to the desired page but #infoObject does not seem to have an effect as the page loads from the beginning and not at the  info Object section) 

**mp.openapi.schema**

 This property is functionally equivalent to the @Schema annotation on a Java class. 
->
 This property is functionally equivalent to the `@Schema` annotation on a Java class. 

**Differences between MicroProfile OpenAPI 3.1 and 3.0**
No comments

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - all suggestions implemented
