### ISSUE TITLE
Config examples for social media login feature

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#569]
@brutif 's blog post about security features in Liberty includes an example [Social Media Login feature](https://www.openliberty.io/docs/ref/feature/#socialLogin-1.0.html) configuration that we could use in the generated docs.

Bruce suggested that we should also have one showing how to configure having a 'chooser' function which lets the app user pick a provider before sending them off to authenticate.

**Comment by Charlotte-Holt** [comment]
@lauracowen Is this for the same feature as https://github.com/openliberty/docs/issues/637?

**Comment by lauracowen** [comment]
Yes, I think so. Have moved this info to the other and will close this.
