### ISSUE TITLE
Small deployment on openshift updates

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/docs#5691]
Document: Deployment on OpenShift
http://openliberty.io/docs/latest/deployment-openshift.html

* First mention of OpenShift is not a link but the second one is. It would probably make sense to make the first one a link. 
* The doc mentions "and [Kubernetes Application Navigator (kAppNav)](https://kappnav.io/) integration." -  that's a broken link at this point and I think this whole bit can be removed at this point. 
* The link in "The [Operator is also available as a Red Hat-certified Operator](https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator) from OpenShift Container Platform (OCP)" bit appears to no longer to point to the operator anymore. It should probably point to: https://catalog.redhat.com/software/containers/ibm/open-liberty-operator-bundle/5f7f4aed69aea3467fdceb99

@leochr @halim-lee please review

**Comment by ramkumar-k-9286** [comment]
Hi @jgawor  

The suggested corrections have been made.

- [X] First mention of OpenShift is not a link but the second one is. It would probably make sense to make the first one a link.

- [X] The doc mentions "and [Kubernetes Application Navigator (kAppNav)](https://kappnav.io/) integration." - that's a broken link at this point and I think this whole bit can be removed at this point.
 
- [X] The link in "The [Operator is also available as a Red Hat-certified Operator](https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator) from OpenShift Container Platform (OCP)" bit appears to no longer to point to the operator anymore. It should probably point to: https://catalog.redhat.com/software/containers/ibm/open-liberty-operator-bundle/5f7f4aed69aea3467fdceb99

Please check and let us know if the corrections are to your liking. If so please add the `Developer Reviewed` label.

**Draft Link: **https://draft-openlibertyio.mybluemix.net/docs/latest/deployment-openshift.html****


Regards,
Ramkumar.

CC @dmuelle

**Comment by jgawor** [comment]
@ramkumar-k-9286 thank you! this looks good to me but i'll let @leochr confirm the right link to the operator entry in the red hat catalog.

**Comment by ramkumar-k-9286** [comment]
Hi @leochr 

Could you verify the link added in the following document? Corrections done based on the following information.

The link in "The [Operator is also available as a Red Hat-certified Operator](https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator) from OpenShift Container Platform (OCP)" bit appears to no longer to point to the operator anymore. It should probably point to: https://catalog.redhat.com/software/containers/ibm/open-liberty-operator-bundle/5f7f4aed69aea3467fdceb99

**Draft Link for document: https://draft-openlibertyio.mybluemix.net/docs/latest/deployment-openshift.html**

Regards,
Ramkumar.

CC @dmuelle

**Comment by leochr** [comment]
@ramkumar-k-9286 I am not able to access the draft, so reviewed the doc at https://openliberty.io/docs/latest/deployment-openshift.html.  The operator install instructions provide all install options including Red Hat certified catalog, so the links can be removed from this doc. Thank you

- [ ] Remove this sentence "You can [install the Open Liberty Operator](https://operatorhub.io/operator/open-liberty) from OperatorHub for use on Kubernetes or OpenShift. The [Operator is also available as a Red Hat-certified Operator](https://access.redhat.com/containers/#/registry.connect.redhat.com/ibm/open-liberty-operator) from OpenShift Container Platform (OCP)." 
- [ ] Instead add this: "You can install the Open Liberty Operator for use on Kubernetes or OpenShift. For more information, refer to the Open Liberty Operator [installation documentation](https://ibm.biz/olo-install)"
- [ ] Remove "The Operator automates updates of binding information among applications, meaning that it connects applications and maintains information about whether a particular application produces or consumes a service."

**Comment by ramkumar-k-9286** [comment]
Hi @leochr 

I added the draft link a few weeks ago. As you might be aware draft links for OL had been changed. This is why the shared link did not work.

Adding the new link. Changes were made to this link and I need that verified. Please have a look at this.

Draft Link for document: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/deployment-openshift.html

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
Hi @leochr

Incorporated your comments.

**Draft Link for document: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/deployment-openshift.html**

Please check and let us know if the corrections are to your liking.

Regards,
Ramkumar.

**Comment by leochr** [comment]
@ramkumar-k-9286 Use the short-url https://ibm.biz/olo-install within "For more information, refer to the Open Liberty Operator [installation documentation](https://ibm.biz/olo-install)". We'll update this short-url to point to the latest version's install instructions, hence it wouldn't be outdated in the doc. Otherwise, changes look fine. Thanks.

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle 
Incorporated comments. Please do a Peer Review.

Draft Link for document: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/deployment-openshift.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
## Peer review

This is news to me but acrolinx flags every instance of "OpenShift":
 `Use "Red Hat OpenShift" for each reference. Do not write "OpenShift" without "Red Hat"` 
 Seems ridiculous but that's pretty explicit so we should update the doc accordingly

single-sign on ---> single sign-on

For more information, refer to the Open Liberty Operator installation documentation.
--->
For more information, see the Open Liberty Operator installation documentation.

Otherwise LGTM

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.10. Closing this issue
