### ISSUE TITLE
Default Port number doc doesn't link to any documentation about command port

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#5707]
The page https://openliberty.io/docs/latest/reference/default-port-numbers.html contains the following:

> For the command port, the Open Liberty server acquires a temporary port to be used by the command listener. You can configure this port in the bootstrap.properties file. For more information, see [Server Configuration overview](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html).

However the referenced server configuration overview doesn't define anything about the command port.

I also cannot find a page that does talk about what properties in bootstrap.properties have special meanings. Doing a google I find [this page](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-specifying-bootstrap-properties) which does cover this kind of material, but I couldn't find equivalent in Open Liberty docs. It would be good to review that document to see what is/should be covered in Open Liberty docs.

Even if that information were imported, I'd still be requesting that we do more on this page about the command port because I don't think searching for `command.port` in a page of bootstrap.properties is that usable. I think we should probably talk more about this ephemeral port in the default port numbers page, so I suggest adding a new row for the command port with the content below:

Column 1: Kernel
Column 2:  

```Command Port: 0 
bootstrap.properties
  command.port=0
```

**Comment by ramkumar-k-9286** [comment]
Hi Alasdair @NottyCode

Made the suggested change.

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/default-port-numbers.html

Noticed a few things in the doc which I wanted to clarify with you.

1. For the command port, the Open Liberty server acquires a temporary port to be used by the command listener. You can configure this port in the `bootstrap.properties` file. For more information, see [Server Configuration overview](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html).

Should i take off this section or just ( For more information, see [Server Configuration overview](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html).)?

2. Should we not be replacing mentions of java ( [Enterprise JavaBeans Remote](https://openliberty.io/docs/latest/reference/feature/ejbRemote.html), [Java Servlets](https://openliberty.io/docs/latest/reference/feature/servlet.html) ) with Jakarta in this document as well?

Regards,
Ramkumar

CC @dmuelle

**Comment by dmuelle** [comment]
Also note that we opened #5708 to create a page for bootstrap properties in Open Liberty

> I also cannot find a page that does talk about what properties in bootstrap.properties have special meanings. Doing a google I find [this page](https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-specifying-bootstrap-properties) which does cover this kind of material, but I couldn't find equivalent in Open Liberty docs. It would be good to review that document to see what is/should be covered in Open Liberty docs.

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - for 2 yes please update to the current feature names

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Update to the current feature names

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Corrections have been made based on your comments.

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/default-port-numbers.html

Regards,
Ramkumar.


Saw a mistake. did the correction and merged again.

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 - after looking more closely at https://www.ibm.com/docs/en/was-liberty/base?topic=liberty-specifying-bootstrap-properties I think this needs a few edits. I also think we should migrate most if not all of that topic to a new Open Liberty doc, which should be linked to from the description here (per #5708) .

For this page

- the description doesn't need to be a bulleted list and both sentences can be in the same paragraph. 

> For the command port, the Open Liberty server acquires a temporary port that is used by the command listener. You can configure this port in the `bootstrap.properties` file. 

- for the example, the code block doesn't need to include `bootstrap.properties`. Also, `0` is the default value for the command port  so the example should show a different value, like `1`. 
- The description should state that the default value is `0`.
- After the example, include a "For more information, see..." link that points to the section of the new topic from #5708 that talks about command port

**Comment by dmuelle** [comment]
For more information, see [command port](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/bootstrap-properties.html)

add an anchor to the "Set the command port" section of the target doc and link directly to that. also, change link text and add a period.

For more information, see [Set the command port](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/bootstrap-properties.html).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

anchor added and linked to the "Set the command port" section

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/default-port-numbers.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
Sorry, the link looks good but the sentence is still a little awkward. 

For more information about how command port property is set in a bootstrap.properties file, see [set the command port](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/bootstrap-properties.html#command-port).

--->

For more information about how the command port property is set in a bootstrap.properties file, see [Set the command port](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/bootstrap-properties.html#command-port).

or just

For more information see [Set the command port](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/bootstrap-properties.html#command-port).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Staging Link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/default-port-numbers.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
published with 22.0.0.12
