### ISSUE TITLE
Documentation for Jakarta EE 10: Support Jakarta Security 3.0 

### ISSUE THREAD

**Issue by teddyjtorres** [OpenLiberty/docs#5722]
Documentation for Jakarta EE 10: Support Jakarta Security 3.0 Epic https://github.com/OpenLiberty/open-liberty/issues/18741.

For the new feature document for “Application Security (Jakarta Security ) 5.0” in https://openliberty.io/docs/latest/reference/feature/appSecurity-5.0.html, please add the following:

1. A note in the description:

This feature enables support for securing the server runtime environment and applications using Jakarta Security 3.0. Jakarta Security 3.0 allows using the new `OpenIdAuthenticationMechanismDefinition` annotation to configure a built-in OpenID Connect authentication mechanism to function as an OpenID Connect client, or Relying Party (RP), so that you can use an OpenID Connect Provider (OP) as a single-sign-on identity provider.

2. A new section under “Examples” with the following content, preferably at the end:

### Using the OpenIdAuthenticationMechanismDefinition annotation to enable an OpenID Connect client for an application

You can use the `OpenIdAuthenticationMechanismDefinition` annotation in a Web or JAX-RS application to enable an OpenID Connect client for that application. The following example shows a servlet with a minimal OpenIdAuthenticationMechanismDefinition:

```
@WebServlet("/OidcAnnotatedServlet")
@OpenIdAuthenticationMechanismDefinition(
                                         providerURI = "https://localhost:8920/oidc/endpoint/OP",
                                         clientId = "clientId",
                                         clientSecret = "clientSecret",
                                         redirectURI = "https://localhost:8940/MyApp/Callback")
@DeclareRoles("all")
@ServletSecurity(@HttpConstraint(rolesAllowed = "all"))
public class OidcAnnotatedServlet extends HttpServlet {
…
}
```

This minimal annotation enables an OpenID Connect client for protected resources in `MyApp` application, using the OpenID Connect Provider (OP) at "https://localhost:8920/oidc/endpoint/OP". When the user tries to access a protected resource in `MyApp`, the user is redirected to the OP’s authorization endpoint obtained from the OP’s discovery metadata. The OP redirects the user back to "https://localhost:8940/MyApp/Callback" with the authorization code after the user authenticates successfully. The OpenID Connect client validates the authentication response and uses the authorization code to get the access token, identity token, and optionally the userinfo token. The tokens are verified and an authenticated subject is established before dispatching the request to the callback servlet. The OpenID Connect client uses the default TLS configuration that is specified by the server for requests to the OP’s token and userinfo endpoints. Therefore, the OP’s signer certificates need to be imported in the default truststore configured for the default TLS configuration.

The application needs to provide an implementation for the callback servlet when using the minimal annotation. The callback servlet needs to obtain the original request URL using the new `OpenIdContext` API and redirect to the original resource. For example:

```
…
import jakarta.security.enterprise.identitystore.openid.OpenIdContext;
…

@WebServlet("/Callback")
public class CallbackServlet extends HttpServlet {

    @Inject
    private OpenIdContext context;

    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        …
        if (context != null) {
            Optional<String> originalRequest = context.getStoredValue(request, response, OpenIdConstant.ORIGINAL_REQUEST);
            String originalRequestString = originalRequest.get();
            response.sendRedirect(originalRequestString);
        }
    }

}
```

You can avoid creating a callback servlet by setting the `redirectToOriginalResource` attribute to `true` in the annotation. The OpenID Connect client will automatically redirect to the original resource. For example:

```
@OpenIdAuthenticationMechanismDefinition(
                                         redirectToOriginalResource = true,
                                         …
```

You can also override the metadata obtained from the OP’s discovery endpoint by adding a `providerMetadata` attribute to the annotation. The following example overrides the authorization and token endpoints:

```
@OpenIdAuthenticationMechanismDefinition(
                                         providerMetadata = @OpenIdProviderMetadata(
                                                                                    authorizationEndpoint = "https://localhost:8920/oidc/endpoint/OP/authorize",
                                                                                    tokenEndpoint = "https://localhost:8920/oidc/endpoint/OP/token"),
                                         …
```

All attributes support Jakarta Expression Language 5.0 (EL). You can specify the EL expression directly in a String attribute. For example, if you do not want secrets in your annotation and you have a bean providing the secret, you can do the following:

```
@OpenIdAuthenticationMechanismDefinition(
                                         clientSecret = "${openIdConfig.clientSecret}",
                                         …
```

You can use alternative attributes designed for EL expressions for attributes that are not String. The boolean result for the EL expression in the `useSessionExpression` attribute in the following example overrides the value of the `useSession` boolean attribute:

```
@OpenIdAuthenticationMechanismDefinition(
                                         useSession = true,
                                         useSessionExpression = "#{openIdConfig.useSessionExpression}",
                                         …
```

You can use the `claimsDefinition` attribute whenever the OP creates tokens that do not use a `preferred_username` claim for the user name or a `groups` claim for the groups. Since a Liberty OP creates an identity token with the `sub` and `groupIds` claims, you need to use the `claimsDefinition` attribute to specify the name claim and groups claim when the `providerURI` attribute points to a Liberty OP.  The following example shows how to use the `sub` claim for the caller name and the `groupIds` claim for the groups:

```
@OpenIdAuthenticationMechanismDefinition(
                                         providerURI = "https://localhost:8920/oidc/endpoint/LibertyOP",
                                         claimsDefinition = @ClaimsDefinition(callerNameClaim = "sub", callerGroupsClaim = "groupIds"),
                                         …
```

If there are no role mappings for the application, the role protecting the resource is automatically mapped to the corresponding group from the claim named by the `callerGroupsClaim` attribute. For example, an application protected with the `all` role would then require an `all` group in the `groupIds` claim.

You can now check for tokens expirations and what happens when they are expired. The following example shows how to use the `logout` attribute with a `LogoutDefinition` annotation to enable checking for access token and identity token expiration and enable an RP-Initiated Logout with the OP’s `end_session_endpoint` when any of those tokens expire:

```
@OpenIdAuthenticationMechanismDefinition(
                                         logout = @LogoutDefinition(
                                                                notifyProvider = true,
                                                                accessTokenExpiry = true,
                                                                identityTokenExpiry = true),
                                         …
```

Please refer to the section [2.4.4. OpenID Connect Annotation](https://jakarta.ee/specifications/security/3.0/jakarta-security-spec-3.0.html#openid-connect-annotation) of the Jakarta Security 3.0 specification for more information about the `OpenIdAuthenticationMechanismDefinition` annotation and its attributes. The Jakarta Security 3.0 specification also introduces the `OpenIdContext` bean and various APIs for handling the access token, identity token, and refresh token. The JavaDoc for the Jakarta Security 3.0 APIs are available from https://github.com/jakartaee/security/tree/3.0.0-RELEASE.

**Comment by arkarkala** [comment]
The work here is mostly related to the new Jakarta security specification, so do not expect a lot of updates. Couple of potential topics to doc are
1) Make the annotated config work with our server/OP (config samples for example)
2) Any differences compared to the current OIDC support using existing config (server.xml/non-annotated)
3) Any clarifications needed for any of the annotated attributes - more than what the spec is describing. 
4) Integrate with the current OIDC docs.

Expecting 3-5 pages of new info to be added.

**Comment by arkarkala** [comment]
We also have the authentication and authorization feature changes for Jakarta 10 but no additional docs are needed since all the relevant information should be in the spec. All we need is the new features show up in the docs - which I think is automatic.

**Comment by dmuelle** [comment]
Just to clarify- are all the examples under (2.) specific to appSecurity 5.0? If all the information applies only to 5.0 and later, we will filter it out from earlier versions of the feature, but if some of the examples apply to earlier versions as well, we can add them to those pages as well.

**Comment by arkarkala** [comment]
In 2) I envision us pointing out to some differences in configuration (for example defaults, additional attributes supported in annotations) between the existing OIDC support (config in server.xml) and the new annotation config (in the source). May be just some bullet points can do to show the difference with a line or 2 of config associated with it.

**Comment by teddyjtorres** [comment]
TODO: Add note about jwksURI and certificate used to verify the tokens in default truststore.

**Comment by dmuelle** [comment]
Hi @teddyjtorres @ramkumar-k-9286 - after reviewing [Rams initial draft](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-4.0.html#OpenIdAuthenticationMechanismDefinition). I'm thinking this information would be better on it's own page in the Security section, under [Single-sign on](https://openliberty.io/docs/latest/single-sign-on.html). It's more involved content than we normally have for feature examples, which are generally concise examples of feature-specific server config. It also might be hard for someone who is looking for OpenID connect information to find it here.

That said, we would keep the extended description from `1.` in the comment above on this appSecurity 5.0 page, and add a link to the new topic in the SSO section. This topic would also be linked from the [openidConnectClient-1.0 feature page](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/openidConnectClient-1.0.html) so OIDC users would be aware of the new capability and from the new [Differences between EE 9.1 and 10 page](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html).

I think to have a standalone topic, we'd need just a little more info to provide context in the introduction:

1. If using this new annotation is an alternative to using openidConnectClient-1.0 and configuring in server.xml, what are the differences/ advantages? Why might someone use annotations instead of server config?
2. If you're using the annotation to configure the client do you need openidConnectClient-1.0 at all?
3. Need info from your comment above "TODO: Add note about jwksURI and certificate used to verify the tokens in default truststore."
4. Are there any other differences between 3.0 and 4.0 that should go on the differences page?

Let us know what you think- thanks!

**Comment by teddyjtorres** [comment]
Thank you @dmuelle and @ramkumar-k-9286 for the draft. I agree in separating this new content into its own page under Single-sign on and keeping a description with a link from the appSecurity 5.0 page to the new page.

For point 1, we would prefer not comparing the Jakarta Security 3.0's config to the openidConnectClient-1.0's config since it could cause confusion.

For point 2, a user does not need the openidConnectClient-1.0 feature at all, only appSecurity-5.0. 

For point 3, please add the following paragraph after the paragraph that starts with "The OpenID Connect client validates the authentication",

> The OpenID Connect client uses the jwks_uri from the OP's discovery metadata by default to obtain the signing key used to validate the tokens' signatures. You can use the `jwksURI` attribute in the `@OpenIdProviderMetadata` annotation of the `providerMetadata` attribute to specify a different JWK endpoint URL, 
> 
> ```
> @OpenIdAuthenticationMechanismDefinition(
>                                          providerMetadata = @OpenIdProviderMetadata(
>                                                                                     jwksURI = "https://localhost:8920/oidc/endpoint/OP/jwk",
>                                          …
> ```
> 

For point 4, if you mean appSecurity-3.0 and appSecurity-4.0, the one difference is the use of the jakarta namespace for the APIs, that is already noted in https://openliberty.io/docs/latest/reference/feature/appSecurity-4.0.html.

Please let me know if any clarifications are needed.

Regards,
Teddy

**Comment by dmuelle** [comment]
Thanks @teddyjtorres - apologies, that was a typo on the final point. It should have read

Are there any other differences between Application Security 4.0 and 5.0 that should go on the [Differences between Jakarta EE 10.0 and 9.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html) page? Most of the other EE10 specs have an entry on that page.

Thanks

**Comment by teddyjtorres** [comment]
Thank you @dmuelle. No problem. We could add a section,

> ### Differences between Jakarta Security 3.0 and 2.0
> 
> The Jakarta Security 3.0 feature introduces a new `@OpenIdAuthenticationMechanismDefinition` annotation to configure a built-in OpenID Connect authentication mechanism to function as an OpenID Connect client, or Relying Party (RP), so that you can use an OpenID Connect Provider (OP) as a single-sign-on identity provider. It also introduces the `OpenIdContext` bean and various APIs for handling the access token, identity token, and refresh token.
> 
> For more information, see the [Jakarta Security 3.0 Javadoc](https://jakarta.ee/specifications/security/3.0/jakarta-security-spec-3.0.html).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

The document has been added to the draft site.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Please look at the same before we send it to Teddy for review.


Regards,
Ramkumar

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 - here are my notes:


- need to add a statement to the intro saying that the annoation is is part of Jakarta Security 3.0 and that this specification is supported in Open LIberty by the Application Security (Jakarta Security) 5.0 feature. You must enable this feature in the `server.xml` file to use the annotation in your app
- run acrolinx and fix any relevant errors- mainly seeing instances of "avoid noun followed by ing" and "use full clause", also 1 overlong sentence.
- wherever possible, remove passive voice. ie "~~a basic OpenID Connect client can be enabled~~...." --> "you can enable a basic OpenID Connect client". Check throughout
- clarify that the text after the first example refers to the example- ie `MyApp` is an example value
- What does OP stand for? spell out on first mention
- OP's-->OP don't use possessive for inanimate entities
- make sure all annotations and attributes in the text are in `monospace `
- By default, the OpenID Connect client uses the jwks_uri from the OP’s discovery metadata---> By default, the OpenID Connect client uses the `jwks_uri`  value from the OP discovery metadata
- It is possible---> You can
- This callback servlet must use the new OpenIdContext API ---> This callback servlet must use the OpenIdContext API 
- The OpenID Connect client will automatically redirect to the original resource as shown in the following example.---> The OpenID Connect client automatically redirects to the original resource, as shown in the following example.
- spell out Relying Party (RP) on first mention
- JavaDoc--->Javadoc
- i think the javadocs will be included on the OL site closer to GA, we should update this link to point to our Javadocs instead.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

suggested corrections were made.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

I've not added the link to our Javadocs, not sure about the link.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 

- Make the title H1 and add the metadata block to the beginning of the file (title is currently H3, no metadata specified)
- link the app security 5.0 feature on first mention
- edit:
The example demonstrates how you can enable a basic OpenID Connect client for protected resources within the MyApp application by using the OpenIdAuthenticationMechanismDefinition annotation.
--->
This example demonstrates how to enable a basic OpenID Connect client for protected resources within an application that is named `MyApp` by using the OpenIdAuthenticationMechanismDefinition annotation.
- add forward slashes before all example URLs in the text so they dont highlight as hyperlinks
- make sure URLs are described as " the https://localhost:8940/MyApp/Callback URL" (for example)

I also think we should add headings to make the topic easier to navigate. I'll propose some headings and we can get feedback from @teddyjtorres to improve them where needed.

1. The first heading should go right after the third sentence in the topic. To start, we can use "Configure an OpenID Connect Client and call back servlet." The second example and it's description should be moved out of this section and into the "Configure custom metadata..." section (see below). The current third and fourth examples should remain in this section and become the second  and third examples.
2.  "Configure custom metadata" this section should include the current second example, after the current 5th example.
3. "Specifiy Expression Language expressions" THis should contain the current 6th and 7th examples
4. "Specify missing claims" THis section should minclude the current 8th example
5. "Check token expirations" This section should contain the current 9th example

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David,

suggested corrections were made.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 looks good just a couple changes

- here and in other docs- the name of the `Application Security` feature should not include `(Jakarta Security)`. Just use `Application Security`. This is a recent change to doc process due to the fact that appSec version numbers don't line up with the Jakarta Security spec numbers that they support and might cause confusion. For example, Application Security 5.0 feature supports Jakarta Security 3.0 so `Application Security (Jakarta Security) 5.0` might cause confusion as to which version(s) are represented.
- call back servlet ---> callback servlet
- To use the OpenIdAuthenticationMechanismDefinition annotation in your application, you must enable ~~this feature~~ the Application Security 5.0 feature in the server.xml file.
- \ https://localhost:8920/oidc/endpoint/OP in the paragraph after the first example, the forward slash to escape link processing on this url; needs to go after the first tic that enables monospace processing- see draft, 2 instances
- the OP token and userinfo endpoints ---> the OP `token` and `userinfo` endpoints
-  it is possible to specify ---> you can to specify 
- it is now possible to examine token---> you can examine token
-  end_session_endpoint --->  `end_session_endpoint`

**Comment by dmuelle** [comment]
one more thing- note that somehow extra indents are being added to all of the code examples, making them too wide for normal browser width. I'm not sure why this is happening but if you look at Teddy's examples from his comment in the "Edit" view, you'll see what I think is the intended level of indent in each example. We need to replicate that in the doc, probably by manually re-indenting the lines

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

suggested corrections were made.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 LGTM, thanks

**Comment by ramkumar-k-9286** [comment]
Hi Teddy @teddyjtorres 

Could you review the following document:

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Regards,
Ramkumar

CC @dmuelle

**Comment by teddyjtorres** [comment]
Thank you @ramkumar-k-9286, the changes are good. If needed, a direct link to the Javadoc is https://javadoc.io/doc/jakarta.security.enterprise/jakarta.security.enterprise-api/latest/jakarta.security/module-summary.html. Otherwise, I am completing the technical review.

Regards,
Teddy

**Comment by dmuelle** [comment]
# Peer review

You can use the OpenIdAuthenticationMechanismDefinition annotation in a web or JAX-RS application to enable an OpenID Connect client for that application. 
-->
You can use the OpenIdAuthenticationMechanismDefinition annotation in a web or RESTful Web Services (JAX-RS) application to enable an OpenID Connect client for that application.

To use the OpenIdAuthenticationMechanismDefinition annotation in your application, you must enable the [Application Security 5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) feature in the server.xml file.
--->
To use the OpenIdAuthenticationMechanismDefinition annotation in your application, you must enable the Application Security 5.0 (`appSecurity-5.0`) feature in the server.xml file.

 The default TLS configuration that is specified by the server is used by the OpenID Connect client...
--->
 The feature:transportSecurity[display=default TLS configuration] that is specified by the server is used by the OpenID Connect client...


You can avoid creating a callback servlet by setting the redirectToOriginalResource attribute to true in the annotation. The OpenID Connect client automatically redirects to the original resource, as shown in the following example.
--->
You can avoid creating a callback servlet by setting the redirectToOriginalResource attribute to true in the annotation, as shown in the following example. The OpenID Connect client automatically redirects to the original resource.  


We also need top add to this page from  the [OpenID Connect Client](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/openidConnectClient-1.0.html) page and the App Security 5.0 page, when it's avaialble

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Incorporated the Peer Review comments, and replaced the Javadoc link.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated the Peer Review comments, and replaced the Javadoc link.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/openidConnectClient-1.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - just a couple things:

The OpenIdAuthenticationMechanismDefinition annotation is a part of the Jakarta Security 3.0 specification and is supported in Open Liberty by the Application Security 5.0 [(appSecurity-5.0)](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) feature.
--->
The OpenIdAuthenticationMechanismDefinition annotation is a part of the Jakarta Security 3.0 specification and is supported in Open Liberty by the  [Application Security 5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) (`appSecurity-5.0`) feature.


The link on the OIDC client page should be moved to be an extended description, and should also state that you need application security feature 5.0

> You can use the `OpenIdAuthenticationMechanismDefinition` annotation in a web or RESTful Web Services (JAX-RS) application to enable an OpenID Connect client for that application. This annotation is supported when you enable the feature:appSecurity-5.0[Application Security] feature version 5.0 or later. You do not need to enable the OpenID Connect Client feature to use this annotation. For more information, see Enable an OpenID Connect client for an application.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated the review comments.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/openidConnectClient-1.0.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
On the new page, only link to Appsecurity 5.0 on first mention. On both pages, don't put the text name of the feature in parentheses- only the code name in parentheses, as in my previous comment

**Comment by dmuelle** [comment]
also, please add the following statement to the 5.0 feature page description, just before the openID info:

If you are updating your application from using the `appSecurity-4.0` feature to using the `appSecurity-5.0` feature, changes in API behavior might require you to update your application code. For more information, see xref:ROOT:jakarta-ee10-diff.adoc#security[Differences between Jakarta Security 5.0 and 4.0].

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Incorporated the comments.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-OpenID-Connect-client.html

Link Added: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/openidConnectClient-1.0.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Checked the links. They are working. Pushing to staging.

Regards,
Ramkumar
