### ISSUE TITLE
Update concurrency.html for Jakarta EE 10

### ISSUE THREAD

**Issue by njr-11** [OpenLiberty/docs#5725]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

This page needs updates for Jakarta Concurrency 3.0 / Jakarta EE 10
https://openliberty.io/docs/latest/concurrency.html

Current text:
Java SE and EE both support concurrency ...

Change to:
Java SE and Jakarta EE both support concurrency ...

Current text:
Concurrency in Java SE and Java EE

Change to:
Concurrency in Java SE and Java/Jakarta EE

Current text:
[MicroProfile Context Propagation](https://github.com/eclipse/microprofile-context-propagation#microprofile-context-propagation) enhances these capabilities...

Change to:
[Jakarta Concurrency 3.0](https://jakarta.ee/specifications/concurrency/3.0/) enhances these capabilities...

Current text:
However, in a Java EE environment, ...

Change to:
However, in a Jakarta EE environment, ...

Current text:
Java EE concurrency extends the ...

Change to:
Jakarta Concurrency extends the ...

Current text:
Concurrency in MicroProfile

Change to
Concurrency in MicroProfile and Jakarta EE 10+

Current text:
MicroProfile applications have many of the same...

Change to:
Microservices and other modern applications have many of the same...

Current text:
The [MicroProfile Context Propagation specification](https://download.eclipse.org/microprofile/microprofile-context-propagation-1.0/microprofile-context-propagation.html) solves this problem by introducing the [ManagedExecutor](https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html#package=org/eclipse/microprofile/context/package-frame.html&class=org/eclipse/microprofile/context/ManagedExecutor.html) subclass, which is nearly identical to and fully compatible with the [ManagedExecutorService](https://openliberty.io/docs/latest/reference/javadoc/liberty-javaee8-javadoc.html#class=javax/enterprise/concurrent/ManagedExecutorService.html&package=allclasses-frame.html) subclass in Java EE, except that it is enhanced with the ability to create consistent, context-aware implementations of the [CompletionStage](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletionStage.html) object.

Change to:
The [Jakarta Concurrency 3.0 specification](https://jakarta.ee/specifications/concurrency/3.0/jakarta-concurrency-spec-3.0.html) solves this problem by introducing a variety of methods to the
the [ManagedExecutorService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/managedexecutorservice) interface that create context-aware implementations of the [CompletionStage](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/concurrent/CompletionStage.html) object.  The [MicroProfile Context Propagation specification](https://download.eclipse.org/microprofile/microprofile-context-propagation-1.0/microprofile-context-propagation.html) similarly adds these same methods to the [ManagedExecutor](https://openliberty.io/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html#package=org/eclipse/microprofile/context/package-frame.html&class=org/eclipse/microprofile/context/ManagedExecutor.html) interface, which is nearly identical to and fully compatible with `ManagedExecutorService`.

Current text:
Commonalities between Java SE and EE concurrency and MicroProfile

Change to:
Commonalities between Java SE, Java EE Concurrency Utilities, Jakarta Concurrency and MicroProfile

Current text:
...closely matches the Concurrency Utilities specifications for Java SE and Java EE.

Change to:
...closely matches the Concurrency specifications for Java SE, Java EE and Jakarta EE.

Current text:
...write applications by using Java SE or Java EE APIs and still take advantage of...

Change to:
...write applications by using Java SE or Java EE or Jakarta EE APIs and still take advantage of...

Remove:
as well as the Java EE interface names (for example, javax.enterprise.concurrent.ManagedExecutorService)

Current text:
which enables context-aware completion stages.

Change to:
which enables context-aware completion stages.  With the [Jakarta Concurrency 3.0 feature](https://openliberty.io/docs/latest/reference/feature/concurrent-3.0.html) feature enabled, these executors already have the ability to create context-aware completion stages.

Current text:
In both Concurrency Utilities for Java EE and MicroProfile Context Propagation...

Change to:
In both Jakarta Concurrency, Concurrency Utilities for Java EE, and MicroProfile Context Propagation...

Current text:
...thread context type `ThreadContext.APPLICATION`.

Change to:
...thread context type `ContextServiceDefinition.APPLICATION` (or `ThreadContext.APPLICATION` in MicroProfile).

Current text:
...which is provided by Concurrency Utilities for Java EE

Change to:
...which is provided by Jakarta Concurrency / Concurrency Utilities for Java EE

Current text:
Concurrency Utilities for Java EE provides a trigger API

Change to:
Jakarta Concurrency / Concurrency Utilities for Java EE provides a trigger API

Current text:
With the [Concurrency Utilities for Java EE](https://openliberty.io/docs/latest/reference/feature/concurrent.html) feature, Liberty provides a robust, fully spec-compliant implementation of Concurrency Utilities for Java EE.

Change to:
With the [Concurrency](https://openliberty.io/docs/latest/reference/feature/concurrent.html) feature, Liberty provides a robust, fully spec-compliant implementation of Jakarta Concurrency.

Also add a note, probably near the top, of the following page,
https://openliberty.io/docs/latest/microprofile-context-propagation.html
stating:

"As of Jakarta Concurrency 3.0, the functionality and API of Microprofile Context Propagation relating to completion stages has been adopted into the Jakarta programming model where it is available on the [ManagedExecutorService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/ManagedExecutorService.html) and [ContextService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/ContextService.html) interfaces."

**Comment by ramkumar-k-9286** [comment]
Hi Nathan @njr-11 

Edits have been made to the suggested topics. Please review the same.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/concurrency.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html

Regards,
Ramkumar.

CC @dmuelle

**Comment by njr-11** [comment]
This mostly looks great - just 2 minor comments:
"As for Jakarta Concurrency 3.0..." sounds awkward and should probably be "As of Jakarta Concurrency 3.0..."
The link to https://javaee.github.io/tutorial/concurrency-utilities.html is based on Glassfish rather than Open Liberty, so we should probably remove this link from our documentation.

**Comment by ramkumar-k-9286** [comment]
Hi Nathan @njr-11

Suggested corrections have been made. Please review the same. Please add the `Developer Reviewed` label if the changes are to your satisfaction.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/concurrency.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html

Regards,
Ramkumar.

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

As discussed, could you peer review the following topics:

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/concurrency.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
# Peer review

## Concurrency in microservices
- Put the first two sentences in a separate paragraph to create the shortdesc
- starting with the sentence that starts "Java SE and Jakarta EE both support concurrency...", move those tywo sentences to the beginning of the "Concurrency in Java SE and Java/Jakarta EE" section.

### Commonalities between Java SE, Java EE Concurrency Utilities, Jakarta Concurrency and MicroProfile

> This commonality means you can write applications by using Java SE or Java EE or Jakarta EE APIs and still take advantage of MicroProfile Context Propagation.

--->

> This commonality means you can write applications by using Java SE, Java EE, or Jakarta EE APIs and still take advantage of MicroProfile Context Propagation.

---

> With the [Jakarta Concurrency 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/concurrent.html) feature enabled, these executors already have the ability to create context-aware completion stages.

--->

> With the [Jakarta Concurrency 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/concurrent.html) feature enabled, these executors can already create context-aware completion stages.

---

This sentence is overlong per Acrolinx (also change Once--->After):

> Once you obtain the completion stage from the managed executor, you interact with it exactly as you would the Java SE API, with the added benefit of a consistent thread context in your completion stage actions

### Thread context awareness

This sentence is overlong per Acrolinx:

> In both Jakarta Concurrency, Concurrency Utilities for Java EE, and MicroProfile Context Propagation, executors are aware of thread context and can propagate the context of the task submitter to the thread where the task or action runs.

Also, don't say "both" as there are 3 specs mentioned.

---

> This enables thread pools that are created by these thread factories to all run under the same thread context, minimizing the costs of thread context switching.

--->

> Therefore, thread pools that are created by these thread factories all run under the same thread context, which minimizes the costs of thread context switching.

---

> For thread context propagation, managed executors and thread factories rely on the Context Service (javax.enterprise.concurrent.ContextService), which is provided by Jakarta Concurrency/ Concurrency Utilities for Java EE.

--->

> For thread context propagation, managed executors and thread factories rely on the Context Service (javax.enterprise.concurrent.ContextService), which is provided by Jakarta Concurrency or Concurrency Utilities for Java EE.

### Triggers and notifications

> Jakarta Concurrency / Concurrency Utilities for Java EE provides a trigger API that allows you to customize scheduling for complex business logic.

--->

> Jakarta Concurrency and Concurrency Utilities for Java EE both provide a trigger API that you can use to customize scheduling for complex business logic.

---

> A trigger allows you to recompute the next execution time each time a task runs. This means that you are no longer limited to scheduling repeating tasks at fixed intervals.

--->

> You can use a trigger to recompute the next execution time each time a task runs, so you are not limited to scheduling repeating tasks at fixed intervals.

---

- add a link to [Concurrency with MicroProfile Context Propagation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html) to the see also section


## Concurrency with MicroProfile Context Propagation

- break first paragraph up to create a proper short description from the first 2 sentences. Remove links from the shortdesc

---

> Beginning with Jakarta [Concurrency 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/concurrent.html) and later, the functionality and API of Microprofile Context Propagation relating to completion stages are adopted into the Jakarta programming model. It is available on the [ManagedExecutorService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/ManagedExecutorService.html) and [ContextService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/ContextService.html) interfaces.

--->

> In Jakarta [Concurrency 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/concurrent.html) and later, the functions and API of Microprofile Context Propagation that relate to completion stages are adopted into the Jakarta programming model. These functions are available on the [ManagedExecutorService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/ManagedExecutorService.html) and [ContextService](https://jakarta.ee/specifications/concurrency/3.0/apidocs/jakarta/enterprise/concurrent/ContextService.html) interfaces.

---

> There is no guarantee under which context the action will run. However, with MicroProfile Context Propagation, the thread context is consistent. It is always captured from the thread that creates the completion stage and then applied when the action runs.

--->

> With MicroProfile Context Propagation, the thread context is consistent. It is always captured from the thread that creates the completion stage and then applied when the action runs.

---

> This is useful when you have an unmanaged completion stage that is not thread-context aware.

--->

> This interface is useful when you have an unmanaged completion stage that is not thread-context aware.


### How to obtain ManagedExecutor and ThreadContext instances

> There are a variety of ways to obtain instances of ManagedExecutor and ThreadContext:

--->

> A variety of options are available to obtain instances of ManagedExecutor and ThreadContext:

---

> With MicroProfile Context Propagation, you can also configure and inject instances by way of CDI (requires the cdi-2.0 feature or higher).

--->

> With MicroProfile Context Propagation, you can also configure and inject instances by way of CDI,  as shown in the following example. Injecting instances by CDI requires the Contexts and Dependency Injection feature, version 2.0 or later.

use latest macro to link to feature ^^^

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Peer review comments have been incorporated.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/concurrency.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
Hi Ram- looks good, a few minor things-

# Concurrency in microservices

## Concurrency in Java SE and Java/Jakarta EE
change this heading to `Concurrency in Java SE and Jakarta EE`

## Commonalities between Java SE, Java EE Concurrency Utilities, Jakarta Concurrency and MicroProfile

> Having the added benefit of a consistent thread context in your completion stage actions.
This is a fragment, needs to be a complete sentence with a subject

## Thread context awareness

> the [ThreadContext](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/javadoc/microprofile-3.3-javadoc.html#package=org/eclipse/microprofile/context/package-frame.html&class=org/eclipse/microprofile/context/ThreadContext.html) API..

this link goes to the MP 3.1 API. We should update to 6.0 once we post that Javadoc- not available yet though

## Try out the Liberty Concurrency and MicroProfile Context Propagation features

> Try it out today, and start enjoying the advantages of concurrency and task scheduling in a Java EE environment.

--->

> Try it out today, and start enjoying the advantages of concurrency and task scheduling in a Java EE or Jakarta EE environment.

## See also
replace the link to  [MicroProfile Context Propagation in Open Liberty](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/blog/2019/08/16/microprofile-context-propagation.html) with
[Concurrency with MicroProfile Context Propagation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html)


# Concurrency with MicroProfile Context Propagation

>  MicroProfile Context Propagation enhances Java SE and Java EE concurrency support by

--->

>  MicroProfile Context Propagation enhances Java SE and Jakarta EE concurrency support by

---

> With MicroProfile Context Propagation, you can also configure and inject instances by way of CDI, as shown in the following example. Injecting instances by CDI requires the [Contexts and Dependency Injection](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/cdi12.html) feature, version 2.0 or later.

The CDI link is pointing to the config element and needs to point to the feature instead

---

> If you are using Java EE Concurrency, you can cast your existing ManagedExecutorService to ManagedExecutor.

--->

> If you are using Java EE Concurrency or Jakarta Concurrency, you can cast your existing ManagedExecutorService to ManagedExecutor.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Peer review comments have been incorporated.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/concurrency.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
looks good- two minor fixes

> The MicroProfile Context Propagation specification closely matches the Concurrency specifications for Java SE, Java EE and Jakarta EE. 

needs a serial comma before "and"

> For example, you can schedule a task that only runs Monday through Friday, 

misplaced "only" belongs before "Monday"

adding peer reviewed label and moving this issue to 22.0.0.13. Need to make sure we check that updated Javadoc link once the new javadocs are posted.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Suggested minor fixes are done.

Draft links:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/concurrency.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-context-propagation.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- please open a PR to staging when you have a chance
