### ISSUE TITLE
Remove reference to Kubernetes Application Navigator

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/docs#5726]
Document: Open Liberty Operator
http://openliberty.io/docs/latest/open-liberty-operator.html

Remove another reference to Kubernetes Application Navigator on this page - similar to 
https://github.com/OpenLiberty/docs/issues/5691.

**Comment by dmuelle** [comment]
i grepped the ol docs and this should be the last remaining instance of https://kappnav.io/

**Comment by ramkumar-k-9286** [comment]
Hi Jarek @jgawor 

The suggested changes have been done.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/open-liberty-operator.html

Please check the same and let me know if any additional changes are to be made to the documents. 

Please add the `Developer Reviewed` label if the changes made are to your satisfaction.

Regards,
Ramkumar

CC @dmuelle

**Comment by jgawor** [comment]
@ramkumar-k-9286 looks good. thank you.

**Comment by jgawor** [comment]
@ramkumar-k-9286 i'm unable to set labels.

**Comment by ramkumar-k-9286** [comment]
changes are on vNext and will publish with the 22.0.0.10 release.

Closing this issue. 

Thanks.
Ramkumar.
