### ISSUE TITLE
Document exit code for installFeature and installServerFeatures

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5729]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by jjiwooLim** [comment]
When there's a conncection failure, it will now return 33 from 22.0.0.11  (same as installUtility). https://github.com/OpenLiberty/open-liberty/pull/22327
`33 The connection to the repository failed.`

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle @jjiwooLim 

Added the exit code information to the suggested topics. Please review the same.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installFeature.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installServerFeatures.html

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
**Slack chat with Sarah Lim**

**Ramkumar K**
Hi Sarah
Please have a look at the following issue, when you have time and confirm that the changes are to your liking:
https://github.com/OpenLiberty/docs/issues/5729
Regards,
Ramkumar

**Sarah Lim**
Thanks, looks good to me!

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The exit code information for the suggested topics was added to the staging site.

Staging site links:

https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installFeature.html

https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-installServerFeatures.html

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
changes are on vNext and will publish with the 22.0.0.11 release.

Closing this issue.

Thanks.
Ramkumar.
