### ISSUE TITLE
Fix docs JEE 9.1 differences page

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/docs#5755]
https://openliberty.io/docs/latest/jakarta-ee-diff.html

1. The nav bar and breadcrumb text is wrong in saying version 8.1;
`Differences between Jakarta EE 9.1 and 8.1` should be `Differences between Jakarta EE 9.1 and 8.0`.

2. The first sentence then mentions EE 9.0 rather than 9.1
`If you are updating your application from using Jakarta EE 8.0 features to using Jakarta EE 9.0 features`
should be
`If you are updating your application from using Jakarta EE 8.0 features to using Jakarta EE 9.1 features`

**Comment by dmuelle** [comment]
This is fixed in #5762 , also backported to previous versions and will update with the next site rebuild

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee-diff.html

Thanks for catching this, closing this issue
