### ISSUE TITLE
LG-60: Make Liberty JSON log field names be configurable

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/docs#578]
Opening this issue as docs for things in OL are tracked in this repo.  Discussion of the changes can be found in https://github.ibm.com/was-liberty/liberty-docs/issues/1563 .

Summary of work to do:

https://openliberty.io/docs/ref/config/#logging.html is generated doc so, if the source is updated, the changes will appear when Alasdair updates the OL generated docs for 19.0.0.9.

https://openliberty.io/docs/ref/general/#logging.html is manually maintained (a rare case where we have both for some of the same info) and will need to be updated as described. The example configuration for renaming a field would also go here (not at the end of the page but with the other examples above the table).

https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_logging.html is now made largely redundant by https://openliberty.io/docs/ref/general/#logging.html so should be handled alongside the other topics in https://github.com/OpenLiberty/docs/issues/276[#276] on the OL docs backlog.

**Comment by lauracowen** [comment]
Likely to be in 19.0.0.9 but should not be published before then (see `min` label).

**Comment by dmuelle** [comment]
The doc at https://draft-openlibertyio.mybluemix.net/docs/ref/general/#logging.html has been updated to reflect the `JSON fields` --> `JSON field mappings` edits.

Progress/discussion on this issue is also tracked at https://github.ibm.com/was-liberty/liberty-docs/issues/1563

**Comment by lauracowen** [comment]
Can we close the internal GHE issue now and just track the work here?

**Comment by dmuelle** [comment]
Updated doc is now published at https://www.openliberty.io/docs/ref/general/#logging.html
