### ISSUE TITLE
Document Liberty Tools for MVP

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#5823]
We need an overview page for the new Liberty Tools for Eclipse, VS Code, and Intellij. 

- most likely in the basics section of the docs nav
- The page should explain the benefits of using the tools in your chosen IDE by giving a high-level overview of the functions:  
  -  dev  mode
   - debug
  - content assist for liberty config
   - content assist for MP
- link out to the individual GitHub repos for more details, installation, etc.
  - https://openliberty.io/blog/2022/08/01/liberty-tools-eclipse.html
  - https://github.com/OpenLiberty/liberty-tools-vscode
  - https://github.com/OpenLiberty/liberty-tools-intellij
- link to marketplaces to obtain tools
   - [Open Liberty Tools for VS Code from the Visual Studio Marketplace](https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext).
   - [Open Liberty Tools for IntelliJ from the JetBrains Marketplace](https://plugins.jetbrains.com/plugin/14856-open-liberty-tools).
   - need marketplace link for eclipse
- Create links to the page from relevant docs incl dev mode, MP overview, and the Website getting started page.
- as part of this issue, review the documentation in the individual GitHub repos to optimize the content and provide a consistent experience across all three. Who is the contact for these pages?
- also review the release blog post

Planned MVP Ga is December 9th. Doc will publish with 22.0.0.13

**Comment by yeekangc** [comment]
Need to link out to marketplace entries for the tools as well.

**Comment by dmuelle** [comment]
comment from slack discussion: [Does Liberty Tools support EE8 and MP4? Determine by pom.xml or server.xml?
](https://ibm-cloud.slack.com/archives/CJ6U2DWPJ/p1668696222008819)
This should be at the top of our doc.
I don't believe we offer any assistance with EE 8... 
[@Kathryn Kodama](https://ibm-cloud.slack.com/team/WAKFM12SG)
 or 
[@tcrawford](https://ibm-cloud.slack.com/team/W4W23LYN5)
 please correct me.
For MP 4, since it's the same classes as MP 3, I believe you can make use of the LS, as long as you stick to the MP 3 subset.

**Comment by kinueng** [comment]
The openliberty.io work item for the new [IDE tools section](https://github.com/openliberty/openliberty.io/issues/2888)

**Comment by dmuelle** [comment]
@cherylking @yeekangc @TrevCraw @scottkurz @kathrynkodama 

The initial draft of the Liberty Tools overview is now available for review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/develop-liberty-tools.html

Please leave any feedback as a comment in this issue- thanks!

**Comment by kathrynkodama** [comment]
@dmuelle A few suggestions, feel free to disregard any:

- 1st section and "Minimum requirements" section: "To use Liberty Tools, your project must specify the [Liberty Maven plug-in](https://github.com/OpenLiberty/ci.maven) or the [Liberty Gradle plug-in](https://github.com/OpenLiberty/ci.gradle) in the project pom.xl file." should say "in your project's  pom.xml or build.gradle file"
- "Develop, test, and debug in your editor" section: "Liberty tools brings these dev mode features directly into the command menu for the Liberty projects in your editor." tools should be capitalized
- Should MicroProfile APIs and Jakarta EE APIs sections more closely align? For ex, both use bullets. "Quick Fix support" is capitalized in MicroProfile APIs, but "quick fixes" is not in the Jakarta EE APIs section. 
- "Try it out" section: "marketplace" is not capitalized in "[Liberty Tools for VS Code](https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext) in the Visual Studio Code marketplace"

General comments:
- In my opinion, "Liberty tool window" is more correct than "Liberty Tools window" when referring to IntelliJ (I guess really it is the Liberty Tools tool window but that seems redundant). 
- For sentences mentioning language server support: "for the MicroProfile API, Jakarta EE API, and Liberty configuration files." should we mention explicitly Java files in addition to configuration files?

**Comment by yeekangc** [comment]
- Please remove "with a general availability release coming soon".
- "... and Jakarta EE 9.0 and later APIs": Please remove "and later" and replace "9.0" with "9.x" to be more accurate.  For instance, we don't have support for 10 yet.  "... and later" is too broad IMO.
- "To use Liberty Tools, your project must specify the ...": It isn't a hard prerequisite to specify the build plugins to use capabilities like the Language Server support.  It's more to work with Liberty in dev mode (using the integration done in the IDE tools) that you should have the build plugins specified.
- May be "Configure with core language support ..." is better framed as "Editing support for Liberty configuration, MicroProfile and Jakarta EE"?
- " Jakarta EE API 9.0 and later" under "Jakarta EE APIs": Same comment as above.
- "[Liberty Tools for VS Code](https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext)": We should spell out VS Code as "Visual Studio Code".
- Let us append IDE to Eclipse too for "[Liberty Tools for Eclipse](https://github.com/OpenLiberty/liberty-tools-eclipse)".  I will submit a PR to update the GH repo too.

Thanks!

**Comment by dmuelle** [comment]
Thanks @yeekangc @kathrynkodama , all comments addressed in the refreshed draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/develop-liberty-tools.html

a few notes:

- For the "Configure with core language support ..." I tried to adapt YKs suggestion to be grammatically parallel with the other headings in the topic and ended up with "Write code with editing support for Liberty configuration, MicroProfile, and Jakarta EE" but can refine that as needed
- For "[Liberty Tools for VS Code](https://marketplace.visualstudio.com/items?itemName=Open-Liberty.liberty-dev-vscode-ext)" - i've updated it to use the fiull product name here but note that the Marketplace page says "Liberty Tools for VS Code"

**Comment by kathrynkodama** [comment]
@dmuelle In the second paragraph, this sentence:
"Liberty Tools automatically detects any projects that specify the Liberty Maven plug-in or the Liberty Gradle plug-in in the project pom.xl file."
needs to be updated to:
"Liberty Tools automatically detects any projects that specify the Liberty Maven plug-in or the Liberty Gradle plug-in in the project's pom.xml or build.gradle file."

Not sure if this is too much detail or whether we should call this out here, but the tools will detect Liberty projects that have a `src/main/liberty/config/server.xml` file and we expect that they have the Liberty plug-in specified in their build file.

**Comment by cherylking** [comment]
Shouldn't it actually be `detect` instead of `detects`...Liberty Tools is plural.

"Liberty Tools automatically detects any projects"

**Comment by cherylking** [comment]
Same in this sentence: "Liberty Tools also provides helpful language-support"
Change `provides` to `provide`.

**Comment by cherylking** [comment]
And " Liberty Tools brings these"...change `brings` to `bring`.
I'm the verb tense police today :-)

**Comment by dmuelle** [comment]
@cherylking - as a product name "Liberty Tools" is treated as a collective noun, ie the title is plural, but as a product it is a singular entity (though made up of component parts).

**Comment by cherylking** [comment]
> @cherylking - as a product name "Liberty Tools" is treated as a collective noun, ie the title is plural, but as a product it is a singular entity (though made up of component parts).

ok, but it reads weird.

**Comment by cherylking** [comment]
Given that "Liberty Tools" is actually referring to three products, it seems plural and reads plural. But I will defer to your judgement.

**Comment by kathrynkodama** [comment]
One more suggestion - can we add to the "Jakarta EE APIs" section that the language features are delivered for Java files. Either at the top or after each bullet like in the "MicroProfile EE APIs" section?

**Comment by dmuelle** [comment]
@cherylking - I was thinking from the opening sentence definition

> Liberty Tools is an intuitive set of developer tools....

When you talk about them collectively as a set of developer tools (or 3 plugins/extensions), that set is singular.
However, It does seem awkward elsewhere in the topic and I think we can update to treat them as  plural. Generally, brand names and product names are treated as singular but I can't find any explicit guidance that says never to treat them as plural.

could maybe in the intro just say

> Liberty Tools are intuitive developer tools....

**Comment by dmuelle** [comment]
Thanks for reviewing @cherylking @kathrynkodama - all comments incorporated except

> Not sure if this is too much detail or whether we should call this out here, but the tools will detect Liberty projects that have a src/main/liberty/config/server.xml file and we expect that they have the Liberty plug-in specified in their build file.

I don't quite understand- does this mean you get language server features as long as you have a src/main/liberty/config/server.xml file, but you'd need the one of  plugins to interact with dev mode?

**Comment by kathrynkodama** [comment]
> I don't quite understand- does this mean you get language server features as long as you have a src/main/liberty/config/server.xml file, but you'd need the one of plugins to interact with dev mode?

This might be too much detail for these docs, so maybe it is fine to leave as-is. The general recommendation is that users have the Liberty plugin already configured. 

To get specific, the project will be populated in the dashboard/tool window if a `src/main/liberty/config/server.xml` file is detected. The tools assume that they have one of the plugins configured already. With Maven, even if they don't have the plugin configured, they will still be able to start dev mode (with the way we call the command). With Gradle, they will need to have the Liberty Gradle plugin configured for dev mode to start correctly. 

The language server support works independently of the dashboard/tool window.
Liberty Config language support will be delivered if one of the [supported files](https://github.com/OpenLiberty/liberty-language-server#supported-files) is opened.
Jakarta EE and MicroProfile API language support will be delivered on any Java file where we can detect usage of a Jakarta EE or MicroProfile API or a `microprofile-config.properties` file.

**Comment by cherylking** [comment]
@dmuelle So to sum up what Kathryn said, I think they will get Liberty language server features for their Liberty config files regardless of whether the LMP/LGP are configured.

**Comment by dmuelle** [comment]
ok- to firm up the minimum requirements section. Now we have


> To use Liberty Tools with dev mode, your project must specify the [Liberty Maven plug-in](https://github.com/OpenLiberty/ci.maven) or the [Liberty Gradle plug-in](https://github.com/OpenLiberty/ci.gradle) in the project pom.xl or build.gradle file. A minimum level of 3.7.1 for the Liberty Maven plug-in or 3.5.1 for the Liberty Gradle plug-in is recommended.

> Language support features are available for MicroProfile 3.0 and 4.0 APIs and Jakarta EE 9.x APIs.


Maybe it should say

> To use Liberty Tools with dev mode, your project must specify the [Liberty Maven plug-in](https://github.com/OpenLiberty/ci.maven) or the [Liberty Gradle plug-in](https://github.com/OpenLiberty/ci.gradle) in the project pom.xl or build.gradle file. A minimum level of 3.7.1 for the Liberty Maven plug-in or 3.5.1 for the Liberty Gradle plug-in is recommended.

> Language support features are available for MicroProfile 3.0 and 4.0 APIs, Jakarta EE 9.x APIs, and select Liberty configuration and Java files. These features are enabled for any Liberty project that includes a `server.xml` file in the `src/main/liberty/config` directory.

**Comment by dmuelle** [comment]
that elides a bit of detail but from a user perspective does it cover all the bases?

**Comment by cherylking** [comment]
> Language support features are available for MicroProfile 3.0 and 4.0 APIs, Jakarta EE 9.x APIs, and select Liberty configuration and Java files. These features are enabled for any Liberty project that includes a server.xml file in the src/main/liberty/config directory.

That last sentence only applies to the Liberty config language server. So that is confusing. Makes it sound like you won't get the Jakarata and MP language server support unless you have a server.xml. I don't think that is correct, is it @kathrynkodama ?

**Comment by kathrynkodama** [comment]
@cherylking Right, it does not apply to the Jakarta and MP language support. They will provide support on any Java file that detects usage of the Jakarta EE and MP APIs

**Comment by dmuelle** [comment]
> To use Liberty Tools with dev mode, your project must specify the [Liberty Maven plug-in](https://github.com/OpenLiberty/ci.maven) or the [Liberty Gradle plug-in](https://github.com/OpenLiberty/ci.gradle) in the project pom.xl or build.gradle file. A minimum level of 3.7.1 for the Liberty Maven plug-in or 3.5.1 for the Liberty Gradle plug-in is recommended.

> Language support features are available for MicroProfile 3.0 and 4.0 APIs, Jakarta EE 9.x APIs, and select Liberty configuration and Java files.


I guess we could say something like

>  To use the full set of Liberty Tools functions for dev mode, your project must specify...

**Comment by scottkurz** [comment]
OK, I'm a bit late to the game, sorry about that.   Some of this has been said already but I'm basing my comments on the latest draft server even if there's some overlap

1. pom.xl => pom.xml      (this still appears twice)
2. plug-in?   I see this is indeed what this doc uses....it's just weird since Maven/Gradle generally use "plugin" and only Eclipse uses this "plug-in" but OK.
3. Liberty Tools singular vs. plural - I see we had a bunch of discussion already.  To me it looks weird to see it plural...most of the time users will encounter it as a singular entity in their IDE and not care about our collective effort.. but.. I'm late to the party and it doesn't look awful as a plural.
4.  In the "Minimum Requirements" sec. when we see the sentence:
`Language support features are available for MicroProfile 3.0 and 4.0 APIs, Jakarta EE 9.x APIs, and select Liberty configuration and Java files` we just read essentially the same thing in the very first section so maybe could delete.
5. "With a just few clicks" =>  "With just a few clicks"
6.  "Virtual Studio Code CodeLens support "  you must have meant "Visual Studio Code CodeLens".... or is just "CodeLens" enough?  I might read this and think it doesn't apply to Eclipse....but if this is the better common name fine.
7. The Liberty Tools Eclipse IDE Eclipse Marketplace link is now live at: 
Liberty Tools Eclipse link: https://marketplace.eclipse.org/content/liberty-tools

**Comment by scottkurz** [comment]
One more detail:
> 
```
These features are available for the following Liberty configuration files
 ...
    Any XML files that contain the server root element and exist in the src/main/liberty/config, configDropins/overrides, configDropins/defaults, usr/shared/config, or usr/servers directory
```

I don't think that accurately describes the current story....e.g. a `src/main/liberty/config/my.xml` won't get the LCLS XML support.  @cherylking correct me if I'm wrong.   Maybe we could just say less and it'd be close enough.   Was there already a comment on this?

**Comment by cherylking** [comment]
> I don't think that accurately describes the current story....e.g. a src/main/liberty/config/my.xml won't get the LCLS XML support. @cherylking correct me if I'm wrong. Maybe we could just say less and it'd be close enough. Was there already a comment on this?

I think it will get support. I will have to verify, but we look for other xml files in the pre-defined config locations for Liberty in addition to any xml file `<include>` from the server.xml.

**Comment by dmuelle** [comment]
Thanks for reviewing @scottkurz - I made the following changes-

1. fixed instances of pom.xl
2. "plug-in" - this is the spelling IBM terminology recommends and also what we use elsewhere in the Open Liberty docs
3. Liberty Tools singular vs. plural- I'm still not 100% sold on them being plural- though I agree with Cheryl that having them singular was awkward in parts of the doc. 
4. removed redundant language support info from the minimum requirements- its mentioned in the intro and detailed in the language support section. Also not technically a minimum requirement for using the tools
5. fixed ""With a just few clicks"
6. Changed VS CodeLens to be just CodeLens- I didn't realize this was available in eclipse as most references on the web only mention vs code. Is it valid for Intellij?
7. added eclipse marketplace link

I left the supported files list as is based on Cheryl's response- can update if needed.

**Comment by cherylking** [comment]
@dmuelle Maybe it would be safer for now to take out the line about the additional XML files in those config folders. We can add it later once we figure out whatever bug we have in that section of code.

**Comment by cherylking** [comment]
@dmuelle After some testing, I think the line just needs to be altered slightly from:

```
    Any XML files that contain the server root element and exist in the src/main/liberty/config, configDropins/overrides, configDropins/defaults, usr/shared/config, or usr/servers directory
```

to 

```
    Any XML files that contain the server root element and exist in the configDropins/overrides, configDropins/defaults, usr/shared/config, or usr/servers directory
```

**Comment by dmuelle** [comment]
@cherylking - updated Liberty config XML  file  list
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/develop-liberty-tools.html#_liberty_configuration_files

**Comment by dmuelle** [comment]
Thanks to all for your work on the overview doc for the early release refresh, it is now published at

https://openliberty.io/docs/latest/develop-liberty-tools.html

I'm going to keep this issue open at the moment to track related ID updates in the various Git repos. Here is the progress on those so far:

[IntelliJ](https://github.com/OpenLiberty/liberty-tools-intellij) and [VS Code](https://github.com/OpenLiberty/liberty-tools-vscode): edited and published the Git docs, including the README, user guide, Developing, Contributing
[Eclipse](https://github.com/OpenLiberty/liberty-tools-eclipse): awaiting updates
[LCLS](https://github.com/OpenLiberty/liberty-language-server/tree/dmuelle-patch-1): Docs edited and updated
[LSP4Jarkarta](https://github.com/eclipse/lsp4jakarta): Docs edited and updated

We can also use this issue to track any changes needed between the early release and GA

**Comment by dmuelle** [comment]
ID work for GA is tracked in #6403, closing this issue
