### ISSUE TITLE
Disclose binary scanner dependency for dev mode

### ISSUE THREAD

**Issue by TrevCraw** [OpenLiberty/docs#5828]
Update the ["Dev mode" page](https://openliberty.io/docs/latest/development-mode.html) to disclose the runtime dependency on the binary scanner and share the license link.

Proposed update to end of the "Automatically generate Liberty features in your server configuration" section:

Note: When automatic feature generation is turned on, dev mode has a runtime dependency on IBM WebSphere Application Server Migration Toolkit for Application Binaries, which is separately licensed under IBM License Agreement for Non-Warranted Programs. See license [here](https://public.dhe.ibm.com/ibmdl/export/pub/software/websphere/wasdev/license/wamt).

**Comment by dmuelle** [comment]
@TrevCraw - would it make sense to explicitly state something like "You do not need to purchase a license or install IBM WebSphere Application Server Migration Toolkit for Application Binaries to use automatic feature generation."

**Comment by ramkumar-k-9286** [comment]
Hi Trevor @TrevCraw 

The suggested changes have been made to the document.

Please review the same. In case of additional changes, please suggest them in the comments.

If the changes are to your liking, please add the `Developer Reviewed` label.

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/development-mode.html

Regards,
Ramkumar

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Changes are on vNext and will publish with the 22.0.0.11 release.

Closing this issue.

Thanks.
Ramkumar.
