### ISSUE TITLE
Document: Jakarta EE 10: Support Jakarta Servlet 6.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/docs#5832]
https://github.com/OpenLiberty/open-liberty/issues/18742

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by pmd1nh** [comment]
Servlet 6.0 provides new API as well as new configurations to set any attribute on a response's cookie.  Application can programmatically set new cookie attributes during the application's startup using jakarta.servlet.ServletContainerInitializer or set a configuration in the deployment descriptor.  Cookie attributes can also set at the request time.

### **Configuration for cookie attributes**
Cookie attributes can be configured in the application's deployment descriptor (i.e web.xml)
An example showing the configuration of <attribute> element:
```
<session-config>
   <cookie-config>
     <name>SampleCookieName</name>
     <domain>my.domain.com</domain>
     <path>/</path>
     <http-only>true</http-only>
     <secure>true</secure>
     <attribute>
        <attribute-name>MyAttributeName</attribute-name>
        <attribute-value>valueExample</attribute-value>
     </attribute>
     <attribute>
        <attribute-name>MyOtherAttribute</attribute-name>
        <attribute-value>OtherValue</attribute-value>
     </attribute>
   </cookie-config>
</session-config>
```

Cookie attributes can also be set dynamically during the application startup by utilizing the jakarta.servlet.ServletContainerInitializer.  Example:

```
@Override
public void onStartup(Set<Class<?>> setOfClasses, ServletContext context) throws ServletException {
      SessionCookieConfig scc = context.getSessionCookieConfig();
      scc.setName("MyDynaCookieName");
      scc.setAttribute("MyDynamicAttribute", "DynamicValue");
      ..........
}
```

In addition, an application can set attributes at request time.

```
Cookie wcCookieAtt = new Cookie(“CookieSetAttributeServlet”, “TestCookieBasic”);
wcCookieAtt.setPath(“BasicPath”);
wcCookieAtt.setDomain(“BasicDomain”);
wcCookieAtt.setHttpOnly(true);
wcCookieAtt.setAttribute(“BasicSetAttribute1”, “BasicAttributeValue1");
wcCookieAtt.setAttribute(“BasicSetAttribute2”, “BasicAttributeValue2");
```

In case of conflicts arising from the cookie configuration, the precedence orders (from high to low) are used to resolve the problems: request time > dynamic startup (i.e ServletContainerInitializer) > web.xml .

### **Change to request Cookie header**
Servlet 6.0 implements the HTTP request cookie's behavior following the RFC 6265 standard which states that HTTP client agents (i.e browsers) are no longer sending back cookie attributes to the application server.

Previously, request Cookie attributes could be included using the dollar sign (i.e `$`) prefix a valid attribute name.  For example, `$Domain=myDomain.com` was treated as the `Domain` attribute for the request Cookie.  Starting in Servlet 6.0, `$Domain` is treated as a new cookie name `$Domain`;  the dollar sign is also part of the cookie name.  The only exception to this rule is `$Version`.

Example: consider HTTP request with Cookie header:

`Cookie: $Version=1; name1=value1; $Path=/Dollar_Path; $Domain=localhost; $NAME2=DollarNameValue;Domain=DomainValue`

Prior to Servlet 6.0, server creates: 
```
cookie1: name1 with the associated attributes: Path=/Dollar_Path; Domain=localhost
cookie2: NAME2
cookie3: Domain
```

Starting from Servlet 6.0, server creates:  
```      
cookie1: name1
cookie2: $Path
cookie3: $Domain
cookie4: $NAME2
cookie5: Domain
```

### **Application debug enhancement**
There are new jakarta.servlet.ServletRequest APIs, as well as new class jakarta.servlet.ServletConnection, to assist application developers in debugging the requests to their application.  With the enhancement, application developers can track or refer to a request via its request ID or obtain details of the network connection what is being used by the request.

Jakarta.servlet.ServletRequest new APIs include:
```
String getRequestId()
String getProtocolRequestId()
ServletConnection getServletConnection()
```
The new jakarta.servlet.ServletConnection object is retrieved from the servlet request getServletConnection().  Its APIs include:
```
String getConnectionId()
String getProtocol()
String getProtocolConnectionId()
boolean isSecure()
```

### URI Path Verification
A direct request is rejected with a 400 Bad Request status if any of the following sequences are presence in the URI:

1. The fragment (#) character either encoded or not.
2. The encoded dot (%2E) character.
3. The encoded forward-slash (%2F) character.
4. The back-slash character either encoded (%5C) or not.
5. Any "." or ".." segment that has a path parameter (;) (e.g. /path/..;/info)
6. Any path starting with an initial segment of ".." (e.g. /../path/info)
7. Any control characters either encoded or not.

Note: the URI path verification is not applied to the query string

### X-Powered-By response header
The `X-Powered-By` header is not included in the response header.  There is no configure option to change the behavior starting in Servlet 6.0

### **Removed APIs**

The following previously deprecated Servlet APIs have been removed:
```
jakarta.servlet.ServletContext - Servlet getServlet(String), Enumeration<Servlet> getServlets(), Enumeration<String> getServletNames(), void log(Exception, String), 

jakarta.servlet.ServletRequest - String getRealPath(String)

jakarta.servlet.ServletRequestWrapper - String getRealPath(String)

jakarta.servlet.UnavailableException - UnavailableException(Servlet, String), Servlet getServlet()

jakarta.servlet.http.HttpServletRequest - boolean isRequestedSessionIdFromUrl()

jakarta.servlet.http.HttpServletRequestWrapper - boolean isRequestedSessionIdFromUrl()

jakarta.servlet.http.HttpServletResponse - String encodeUrl(String), String encodeRedirectUrl(String), void setStatus(int, String)

jakarta.servlet.http.HttpServletResponseWrapper -  String encodeUrl(String), String encodeRedirectUrl(String), void setStatus(int, String)
 
jakarta.servlet.http.HttpSession - HttpSessionContext getSessionContext(), Object getValue(String), String[] getValueNames(), void putValue(String, Object), void removeValue(String)
```

### **Removed classes:**
The previously deprecated Servlet classes have been removed:
```
jakarta.servlet.SingleThreadModel
jakarta.servlet.http.HttpSessionContext
jakarta.servlet.http.HttpUtils
```

To use the Servlet 6.0 feature, add `servlet-6.0` to your `server.xml`:
```
   <featureManager>
       <feature>servlet-6.0</feature>
   </featureManager>
```

**Comment by dmuelle** [comment]
Hi @pmd1nh 

In the list of removed APIs, what is the significance of the methods listed after the API? eg
`jakarta.servlet.UnavailableException - UnavailableException(Servlet, String), Servlet getServlet()`

Are those replacements for the functions in the removed API or are they methods that are also removed?

**Comment by pmd1nh** [comment]
Hi @dmuelle 

Those are the removed constructor and the removed methods of the specific class - i.e `jakarta.servlet.UnavailableException`  is the class which has its constructor `UnavailableException(Servlet, String)` and its method `Servlet getServlet()` removed.

**Comment by dmuelle** [comment]
Hi @pmd1nh , the draft for these updates is now available for review on the Differences between Jakarta EE 10.0 and 9.1 page:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#servlet

It's possible some of this info will move to the servlet-6.0 page once it's available but the content will be the same. Let me know if any further edits are needed. If not, you can sign off by adding the `Technical reviewed` label to this issue and the doc will publish in the same release as EE 10. Thanks!

**Comment by pmd1nh** [comment]
@dmuelle where can I provide feedback/comment on this `Differences between Jakarta EE 10.0 and 9.1 page` draft?

**Comment by dmuelle** [comment]
Hi @pmd1nh - you can leave comments for the Servlet section of the page in this issue. If you have more general comments about the entire page you can leave them here or in #5958.

One thing to consider is whether any of this Servlet information should also or instead appear on the Servlet 6.0 feature page, which is not yet available. but will be closer to GA. Im thinking particularly of  the info about setting cookie attributes, which is useful beyond the context of recent API changes and could be an example on the [Servlet Feature page](https://openliberty.io/docs/latest/reference/feature/servlet-5.0.html).

**Comment by pmd1nh** [comment]
@dmuelle 

I added new section "URI Path Verification" to above text

**Comment by dmuelle** [comment]
Thanks @pmd1nh, I'll update the doc and let you know when it's ready for review

**Comment by dmuelle** [comment]
Hi @pmd1nh - I`ve added the URI Path info:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_uri_path_verification

If any further changes are needed, just let me know. If not, you can sigtn off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by pmd1nh** [comment]
Hi @dmuelle 

1.
Change:
```
Any URI control characters, whether encoded or not
```

To:

```
Any control characters, whether encoded or not
```

Also, you didn't include the NOTE line in this section

```
Note: the URI path verification is not applied to the query string
```
I think it needs to be there to let the customer know that their query string is not subjected to the verification

2.
I also added another section

X-Powered-By response header

**Comment by dmuelle** [comment]
@pmd1nh for 

> The X-Powered-By header is not included in the response header. There is no configure option to change the behavior starting in Servlet 6.0

 does "the behavior" refer to allowing an X-Powered-By header? Is there a more-specific way to describe the option that is not available?

does it mean

>  The X-Powered-By header is not included in the response header. Starting in Servlet 6.0, no configuration option is available to include an X-Powered-By header in the response header.

**Comment by pmd1nh** [comment]
There has been a configure option to send this header in a response.  Starting in Servlet 5.0, the header is no longer sent in the response, but its configure option is still available for customer to change that default behavior.

Starting in Servlet 6.0, this configure option is removed.  The header is not sent in the response, and there is not a way to change it.

@dmuelle

**Comment by dmuelle** [comment]
Thanks @pmd1nh - the draft is now updated, let me know if it needs any further chnages

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_uri_path_verification

**Comment by pmd1nh** [comment]
emailed David about update current doc with the new metatType `SKIP_ENCODED_CHAR_VERIFICATION`

**Comment by dmuelle** [comment]
Thanks @pmd1nh - the draft is updated, let me know if it needs any further changes.

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_uri_path_verification

**Comment by pmd1nh** [comment]
Looks good, Thanks @dmuelle

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this is ready for peer review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#servlet

**Comment by ramkumar-k-9286** [comment]
No Peer Review Comments.

**Comment by dmuelle** [comment]
Thanks, I added the peer reviewed label
