### ISSUE TITLE
Document: Jakarta EE 10: Support Jakarta Standard Tag Library 3.0

### ISSUE THREAD

**Issue by pnicolucci** [OpenLiberty/docs#5836]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

https://github.com/OpenLiberty/open-liberty/issues/18744

**Comment by volosied** [comment]
Tags 3.0 documentation will be under Issue  #5835 (Pages 3.1)
