### ISSUE TITLE
Document: Jakarta EE 10: Support Jakarta Persistence 3.1 

### ISSUE THREAD

**Issue by jgrassel** [OpenLiberty/docs#5842]
https://github.com/OpenLiberty/open-liberty/issues/18738

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by chirp1** [comment]
Left Jody slack, included David, asking when Jody could provide the info to doc.

**Comment by dmuelle** [comment]
based on Slack discussion with Joe, the only updates will be to add a page for the new feature level, which will be generated from the metatype. Leaving this issue open for the time being until I can open an umbrella issue for metatype updates but no further doc work is expected at this time

**Comment by dmuelle** [comment]
closing this issue as only gendoc updates are required, which will be tracked in #5958
