### ISSUE TITLE
Document:  Jakarta EE10 Authorization

### ISSUE THREAD

**Issue by emilytee** [OpenLiberty/docs#5851]

**Comment by emilytee** [comment]
The appAuthorization-2.0 feature introduces the following changes:

   - The jakarta.security.jacc.PolicyConfigurationFactory abstract class now implements two
     new methods to be able to retrieve the PolicyConfiguration:

	- public abstract PolicyConfiguration getPolicyConfiguration();
	- public abstract PolicyConfiguration getPolicyConfiguration(String contextID);

     in addition to the existing 

	- public abstract PolicyConfiguration getPolicyConfiguration(String contextID, boolean remove);    

   - The jakarta.security.jacc.PolicyConfiguration interface defines three new methods to read 
     permissions:

	- public abstract Map<String, PermissionCollection> getPerRolePermissions();
	- public abstract PermissionCollection getUncheckedPermissions();
	- public abstract PermissionCollection getExcludedPermissions();

**Comment by emilytee** [comment]
The appAuthorization-2.0 feature introduces the following changes:

   - The jakarta.security.jacc.PolicyConfigurationFactory abstract class now implements two
     new methods to be able to retrieve the PolicyConfiguration:

	- public abstract PolicyConfiguration getPolicyConfiguration();
	- public abstract PolicyConfiguration getPolicyConfiguration(String contextID);

     in addition to the existing 

	- public abstract PolicyConfiguration getPolicyConfiguration(String contextID, boolean remove);    

   - The jakarta.security.jacc.PolicyConfiguration interface defines three new methods to read 
     permissions:

	- public abstract Map<String, PermissionCollection> getPerRolePermissions();
	- public abstract PermissionCollection getUncheckedPermissions();
	- public abstract PermissionCollection getExcludedPermissions();

**Comment by dmuelle** [comment]
Hi @emilytee - should this be `appAuthorization-3.0`? Or are we just adding new methods to the existing appAuthorization-2.0 feature?

**Comment by dmuelle** [comment]
Ok looking I think it will actually be 2.1 ? https://jakarta.ee/specifications/authorization/2.1/

**Comment by emilytee** [comment]
@dmuelle, that should be 3.0

**Comment by emilytee** [comment]
@dmuelle, even I get confused!

Authentication should be appAuthentication-3.0 and authorization should be appAuthorization-2.1.

**Comment by dmuelle** [comment]
Hi @emilytee- the draft for these updates is now available for review on the Differences between Jakarta EE 10.0 and 9.1 page:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#appAuthz

 Let me know if any further edits are needed. If not, you can sign off by adding the `Technical reviewed` label to this issue and the doc will publish in the same release as EE 10. Thanks!

**Comment by emilytee** [comment]
Looks good

**Comment by chirp1** [comment]
Info to document received in this issue. Approving the epic at https://github.com/OpenLiberty/open-liberty/issues/18726 .

**Comment by chirp1** [comment]
Epic approved at https://github.com/OpenLiberty/open-liberty/issues/18726

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 this is ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#appAuthz

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

1. The [Jakarta Authorization 2.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appAuthorization-2.1.html) feature (appAuthorization-2.1) introduces the following new methods....  The link is not working ( believe it will be fixed when associated pages are introduced).

**Comment by dmuelle** [comment]
features links will resolve once autogen is added, will verify in #5958
