### ISSUE TITLE
Document: Jakarta EE10 Authentication 

### ISSUE THREAD

**Issue by emilytee** [OpenLiberty/docs#5852]

**Comment by emilytee** [comment]
The appAuthentication-3.0 feature introduces the following changes:
   - The jakarta.security.auth.message.config.AuthConfigFactory abstract class now implements
     two new methods to be able to register and remove a server authentication module.  Prior to 
     appAuthentication-3.0, support to register and remove a config provider was only available.
   - Ensuring that the jakarta.servlet.http.isAuthenticationRequest property is set to the value
     "true" when an authentication module is called from within HttpServletRequest.authenticate().

**Comment by emilytee** [comment]
The appAuthentication-3.0 feature introduces the following changes:

   - The jakarta.security.auth.message.config.AuthConfigFactory abstract class now implements
     two new methods to be able to register and remove a server authentication module.  Prior to 
     appAuthentication-3.0, support to register and remove a config provider was only available.

	- public abstract String registerServerAuthModule(ServerAuthModule serverAuthModule, Object context);
	- public abstract void removeServerAuthModule(Ojbect context);

   - Ensuring that the jakarta.servlet.http.isAuthenticationRequest property is set to the value
     "true" when an authentication module is called from within HttpServletRequest.authenticate().

**Comment by dmuelle** [comment]
Hi @emilytee - for this bullet point

> Ensuring that the jakarta.servlet.http.isAuthenticationRequest property is set to the value
"true" when an authentication module is called from within HttpServletRequest.authenticate().

I'm having trouble understanding the context- is setting the value something that the developer needs to do ? IS this point related to the new methods? Thanks

**Comment by emilytee** [comment]
This relatest to the actual request, which is really internal and not something exposed to the customer or for them to
do anything with.

We can just strike that part entirely.

**Comment by dmuelle** [comment]
Hi @emilytee- the draft for these updates is now available for review on the Differences between Jakarta EE 10.0 and 9.1 page:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#appAuthn

 Let me know if any further edits are needed. If not, you can sign off by adding the `Technical reviewed` label to this issue and the doc will publish in the same release as EE 10. Thanks!

**Comment by chirp1** [comment]
Information to doc for the following epic has been received: https://github.com/OpenLiberty/open-liberty/issues/18725 . Approving the epic.

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 this is ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#appAuthn

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

1. The [Jakarta Authentication 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appAuthentication-2.1.html) feature (appAuthentication-3.0) introduces...  The link is not working ( believe it will be fixed when associated pages are introduced.

**Suggestions:**

2. Before this version of the feature, support was available to register and remove only a configuration provider.
->
In the previous feature version, only registration and removal of a configuration provider were supported.

**Comment by dmuelle** [comment]
Thanks @ramkumar-k-9286 

1. links will work when new autogen is added
2. updated with a slightly different edit to preserve the meaning
