### ISSUE TITLE
Documentation: Jakarta EE 10 Mail 2.1 (providing info week of 10/24/22)

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/docs#5853]
Related documentation for the Jakarta Mail 2.1 Feature. 

The `jakarta.mail.util.StreamProvider` interface

This new interface from the Mail 2.1 specification allows users to obtain a `StreamProvider` instance  which provides access to what encoders/decoders are supported by the `mail-2.1` runtime. You can obtain instances of the `StreamProvider` from the `jakarta.mail.Session.getStreamProvider()` method.

**Comment by chirp1** [comment]
I slacked Thomas and David. Thomas will get us the info the week of 10/24/22.

**Comment by dmuelle** [comment]
Hi @neuwerk - I've added this info to the EE10 differences page:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#mail

If any further edits are needed, just let me know. If not, you can add the developer reviewed label to the issue to sign off and the update will publish with the EE10 GA. Thanks!

**Comment by chirp1** [comment]
Info to doc received. Approving epic at https://github.com/OpenLiberty/open-liberty/issues/18734

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 this ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#mail

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

1. The [Jakarta Mail 2.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mail-2.1.html) feature introduces... -> link

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - none of the new feature links will be available until we have the updated gendoc for 22.0.0.3. We can test all these links as part of #5958
