### ISSUE TITLE
Documentation: Jakarta EE 10 XML Web Services 4.0 (providing info week of 10/24/22)

### ISSUE THREAD

**Issue by neuwerk** [OpenLiberty/docs#5854]
Related documentation for the Jakarta XML Web Services 4.0 Feature. 

The changes for xmlWS-4.0 are relatively minor. A few points that could be made:

Changes to XML Webservices 4.0:

Jakarata Web Services Metadata specification has merged into the Jakarta Web Services specification, and the JWS APIs are included in the `dev\api\spec\io.openliberty.jakarta.xmlWS.4.0...jar` 

Changes to SOAP with Attachments 3.0

The deprecated SOAPElementFactory has been removed

The changes mentioned under Restful Web Services 3.1 regarding Global Handlers need to also be qualified as applying to XML WebServices 4.0. 

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#_concurrency_apis_availability

**Comment by chirp1** [comment]
I slacked Thomas and David. Thomas will get us the info the week of 10/24/22.

**Comment by dmuelle** [comment]
Hi @neuwerk - this update is ready for review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#xml

Let me know if any further changes are needed. If not, you can sign off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - this is ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#xml

**Comment by ramkumar-k-9286** [comment]
Peer Review:

1. The [Jakarta XML Web Services 4.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/xmlWS-4.0.html) feature Link -> features links will resolve once autogen is added ( Just mentioning).

2. The Jakarta XML Web Services 4.0 feature includes changes for Global Handlers and the Jakarata Web Services Metadata specification. It also **includes the** removal of a previously deprecated class for the SOAP with Attachments 3.0 API, which is supported in Open Liberty by the Jakarta XML Web Services feature.
->
The Jakarta XML Web Services 4.0 feature includes changes to Global Handlers and the Jakarta Web Services Metadata specification. It also removes a previously deprecated class for the SOAP with Attachments 3.0 API, which is supported in Open Liberty by the Jakarta XML Web Services feature.

3. It also includes the removal of a previously deprecated class for the SOAP with Attachments 3.0 API, which is supported in Open Liberty by the Jakarta XML Web Services feature.
->
Should we be adding the link to - the Jakarta XML Web Services feature? - After rechecking - I realised that the link gets added in the beginning - Pls IGNORE.

4. In Open Liberty, the SOAP with Attachments 3.0 release coincides with the Jakarta XML Web Services 4.0 release. With this release, the previously deprecated SOAPElementFactory class of the SOAP with Attachments 3.0 API is removed.
->
**The SOAP with Attachments 3.0 release in Open Liberty** coincides with the Jakarta XML Web Services 4.0 release. **As part of this release,** the previously deprecated SOAPElementFactory class of the SOAP with Attachments 3.0 API is removed.

**Comment by dmuelle** [comment]
Thanks @ramkumar-k-9286 - fixed (2) but left (4) as is to make clear that this is a detail of how OL implements these specs and reduce overall sentence length
