### ISSUE TITLE
Update sec vuln list for 22.0.0.11

### ISSUE THREAD

**Issue by clarkek123** [OpenLiberty/docs#5870]
Draft branch is updated in PR https://github.com/OpenLiberty/docs/pull/5869

This issue is opened to move the updates along from Draft to final docs.

**Comment by dmuelle** [comment]
The proposed changes were delivered to draft from a vNext based branch in https://github.com/OpenLiberty/docs/pull/5873

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.11 on 10/25. Closing this issue. Thanks
