### ISSUE TITLE
Create "Cloud" section

### ISSUE THREAD

**Issue by jgawor** [OpenLiberty/docs#5926]
Create "Cloud" section in the documentation. Move the "Deployment on OpenShift, Open Liberty Operator, Guides: Kubernetes, Guides Cloud deployment topics (and any new relevant topics) under the new section.

**Comment by dmuelle** [comment]
I think the section would add value but I wonder about the messaging of having a specific "cloud" section in the docs for a cloud-native runtime, where presumably all the sections should be from a cloud perspective. But maybe something like "Cloud Deployment" could work? We currently have a "Deployment" section (based on the same section from the guides) that could be adapted for this purpose. Thoughts?

**Comment by jgawor** [comment]
Per discussion, it was decided to not have a separate "cloud" topic and instead extend the existing "deployment" topic with a specific set of links to cloud related tools, projects, and guides.
