### ISSUE TITLE
Documentation: Jakarta EE 10

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/docs#5969]
[Jakarta EE overview](https://openliberty.io/docs/latest/jakarta-ee.html) page updates are outlined below in **bold**.

Java EE 8 was the last release of the platform by the Oracle corporation before it was moved to the Eclipse foundation, which first released the platform as Jakarta EE 8. Jakarta EE 9 arrived in 2020. The primary change in this release was to replace javax with jakarta in Jakarta package names. In February 2021, Jakarta EE 9.1 was released. Although this release did not include any API changes from version 9.0, it added support for Java SE 11.  **In September 2022, Jakarta EE 10 was released.  This release included many API changes and dropped support for Java SE 8.**

Jakarta EE full platform**, Web Profile and Core Profile**

The Jakarta EE specification defines the full platform Enterprise Edition. The Web Profile is a properly defined subset of the full platform. **The Core Profile is introduced in Jakarta EE 10 and is a properly defined subset of the Web Profile.**

**Core Profile**

**The Core Profile is added in Jakarta EE 10 and includes the Jakarta EE features that are needed for modern cloud native applications.  This subset of function includes all Jakarta EE functions that are required for MicroProfile based applications.**

Web Profile

The Web Profile defines a reasonably complete stack that targets modern web applications. This stack is a subset of the full platform standard APIs that can address the needs of most web applications.

Full platform

The full platform defines the full complement of the Jakarta EE programming model. In addition to the Web Profile features, the full platform has specifications for advanced business capabilities that an enterprise needs, such as for connectivity, enterprise beans, messaging, and application clients.

Consider these definitions when you install Open Liberty and its available features. Each installation option provides the Open Liberty kernel and features that support the full platform or Web Profile. Alternatively, you can install individual Jakarta EE features to your existing Open Liberty kernel installation.

Also, consider these definitions when you deploy applications to an Open Liberty server. If your application needs support for enterprise connectivity APIs, you must add full platform features to your installation or deploy the application to an Open Liberty installation that has full platform features.

To quickly add support for Jakarta EE, specify the [Web Profile](https://openliberty.io/docs/latest/reference/feature/webProfile.html) or [Jakarta EE Platform](https://openliberty.io/docs/latest/reference/feature/jakartaee.html) convenience features in your server.xml file. A third convenience feature, [Jakarta EE Application Client](https://openliberty.io/docs/latest/reference/feature/jakartaeeClient.html), is also available to quickly configure an application client component. For more information about convenience features, see [Convenience features](https://openliberty.io/docs/latest/reference/feature/feature-overview.html#conv).  **A Core Profile convenience feature is not provided.  All Core Profile function is enabled by adding the [Jakarta RESTful Web Services](https://openliberty.io/docs/latest/reference/feature/restfulWS.html) and [Jakarta JSON Binding](https://openliberty.io/docs/latest/reference/feature/jsonb.html) features to your server.xml.**

[Differences between Jakarta EE 10.0 and 9.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html) additions:

**XML Binding APIs availability**

Several Jakarta EE 9.1 Liberty features include a dependency on the `xmlBinding-3.0` Liberty feature even though the specification does not call for those features to depend or expose XML Binding APIs.  More over many of the features are Web Profile features and XML Binding is not a Web Profile feature.

Jakarta EE 10 Liberty features that do not expose the XML Binding 4.0 APIs where their Jakarta EE 9.1 equivalent feature does are: `appAuthentication-3.0`, `connectors-2.1`, `persistence-3.1`, `persistenceContainer-3.1`, and `webProfile-10.0`.  For Open Liberty applications that require the XML Binding APIs, you must now add the `xmlBinding-4.0` Liberty feature to the `server.xml` file.

@njr-11 I would like your feedback on whether this next one is worded to your liking or if you think it it is not needed.

**Connectors Inbound Security replacement** 

The Jakarta EE 9.1 `connectorsInboundSecurity-2.0` Liberty feature does not apply to the Jakarta EE 10 `connectors-2.1` Liberty feature and there is not a new 2.1 equivalent feature.  The Connectors Inbound Security function is now provided by an auto feature when both the `connectors-2.1` and `appSecurity-5.0` Liberty features are included in the `server.xml` file.

**Java SE requirement**

Jakarta EE 9.1 features are able to run with Java SE 8 and later versions.  Jakarta EE 10.0 features all require Java 11 or later as outlined by the Jakarta EE 10 specification.

**JWT feature changes**

When enabling the `jwt-1.0` Liberty feature with Jakarta EE 10 Liberty features, the Servlet APIs are no longer available by default. For Open Liberty applications that require Servlet APIs, you must add the `servlet-6.0` Liberty feature to the `server.xml` file.

Similarly, the `com.ibm.wsspi.rest.handler`, `com.ibm.wsspi.rest.handler.helper` and `com.ibm.wsspi.wab.configure` SPIs are no longer made available to user features when the `jwt-1.0` Liberty feature is enabled with Jakarta EE 10 Liberty features.  For Open Liberty user features that require these SPIs, you must add the `com.ibm.websphere.appserver.restHandler-1.0` or `com.ibm.wsspi.appserver.webBundle-1.0` feature to your user feature `mf` file.

**Comment by njr-11** [comment]
> @njr-11 I would like your feedback on whether this next one is worded to your liking or if you think it it is not needed.
> 
> **Connectors Inbound Security replacement**
> 
> The Jakarta EE 9.1 `connectorsInboundSecurity-2.0` Liberty feature does not apply to the Jakarta EE 10 `connectors-2.1` Liberty feature and there is not a new 2.1 equivalent feature. The Connectors Inbound Security function is now provided by an auto feature when both the `connectors-2.1` and `appSecurity-5.0` Liberty features are included in the `server.xml` file.

Many users will not know or care what an auto feature is.  One way to shorten it, make it sound less negative, and avoid the mention of auto features could be:
"The combination of the `connectors-2.1` and `appSecurity-5.0` Liberty features in Jakarta EE 10 replaces what the `connectorsInboundSecurity-2.0` Liberty feature provided in Jakarta EE 9.1."

**Comment by dmuelle** [comment]
Hi @jhanders34 - these drafts are ready for review:

- [Differences between Jakarta EE 10.0 and 9.1: Global differences between Jakarta EE 10.0 and 9.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#global)
- [Jakarta EE overview](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee.html)

Let me know if any further changes are needed. If not, you can add the `Technical Reviewed` label to this issue to sign off.

Thanks

**Comment by jhanders34** [comment]
@dmuelle 

The Jakarta EE overview changes look good.

Below are my review thoughts on the differences page updates.

I wonder if we should change all references of `10.0` to `10`

`In the Jakarta EE 10 release, these features do not expose the xmlBinding-4.0 feature.` seems unnecessary or needs to be reworded.  If you think it is necessary still, we can follow up on some rewording.

There are some consistency issues with your changes.  In general, it appears that you want to use the feature name with a reference to the feature documentation of that feature and then in parentheses the feature short name.  Below are the changes I think that need to be made to make it consistent.

[xmlBinding-3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/xmlBinding-3.0.html) (`xmlBinding-3.0`)

becomes:

[Jakarta XML Binding 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/xmlBinding-3.0.html) (`xmlBinding-3.0`)

---

- `appAuthentication-3.0`
- `connectors-2.1`
- `persistence-3.1`
- `persistenceContainer-3.1`
- `webProfile-10.0`

becomes:

- [Jakarta Authentication 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appAuthentication-3.0.html) (`appAuthentication-3.0`)
- [Jakarta Connectors 2.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/connectors-2.1.html) (`connectors-2.1`)
- [Jakarta Persistence 3.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/persistence-3.1.html) (`persistence-3.1`)
- [Jakarta Persistence Container 3.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/persistenceContainer-3.1.html) (`persistenceContainer-3.1`)
- [Jakarta EE Web Profile 10.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/webProfile-10.0.html) (`webProfile-10.0`)

---

[xmlBinding-4.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/xmlBinding-4.0.html)

becomes:

[Jakarta XML Binding 4.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/xmlBinding-4.0.html) (`xmlBinding-4.0`)

---

In Jakarta EE 10, the combination of the [connectors-2.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/connectors-2.1.html) and [appSecurity-5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) Liberty features replaces what the [connectorsInboundSecurity-2.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/connectorsInboundSecurity-2.0.html) Liberty feature provided in Jakarta EE 9.1.

becomes:

In Jakarta EE 10, the combination of the [Jakarta Connectors 2.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/connectors-2.1.html) (`connectors-2.1`) and [Jakarta Security 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) (`appSecurity-5.0`) Liberty features replaces what the [Jakarta Connectors Inbound Security 2.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/connectorsInboundSecurity-2.0.html) (`connectorsInboundSecurity-2.0`) Liberty feature provided in Jakarta EE 9.1.

**Comment by dmuelle** [comment]
Thanks @jhanders34 - I;ve updated the doc with these changes:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#global

The only excpetion being I only linked to feature pages on first mention, per our process. Only one instance of multiple mentions in the section though (Jakarta Connectors Inbound Security 2.0)

**Comment by jhanders34** [comment]
A few errors to be corrected.

[Jakarta EE Web Profile 10.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/webProfile-10.html) (webProfile-10)

should be

[Jakarta EE Web Profile 10.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/webProfile-10.0.html) (webProfile-10.0)

Note that the link and the feature short name are both updated.

---

[Application Security (Jakarta Security) 5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) (appSecurity-5.0)

This one is messy.  It is `Application Security 5.0 (Jakarta Security 3.0)`.  Not sure how you want to handle that.  Either use what  just provided or just use `Application Security 5.0` I suppose.

---

In the `Connectors Inbound Security replacement` section I believe it still should be:

Jakarta Connectors 2.1 (`connectors-2.1`)

---

With the change to `10` instead of `10.0`, now the title doesn't match the navigation at the top or the side bar.  I think the title should be updated back to 10.0 on the page to match the navigation, but I am happy with the other changes to remove `10.0` and just call it `10` except for what is reference above.

**Comment by jhanders34** [comment]
If you hadn't merged in your PR I could have put the comments in the PR with suggested updates and you could have done the edits there, but need to do a separate PR now I guess.

**Comment by jhanders34** [comment]
David,

Please add to the differences page as the first things in the global section something like:

New Core Profile

Jakarta EE 10 introduces a new profile called Core Profile.  The Liberty features that provide the Core Profile function are cdi-4.0, jsonb-3.0, jsonp-2.1, and restfulWS-3.1.  A convenience feature for Core Profile is not provided.  All features for Jakarta 10 Core Profile are enabled easily by included both restfulWS-3.1 (which includes both cdi-4.0 and jsonp-2.1) and jsonb-3.0 Liberty features in your server.xml.

**Comment by jhanders34** [comment]
Maybe we should put the Java SE requirement one first and then Core Profile second.  I think that is probably priority wise the order it should be in.

**Comment by dmuelle** [comment]
Hi @jhanders34 - the page is updated:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#global

I wasn't sure how verbose to be with the feature names here, trying to be concise for readability. Let me know what you think. Thanks

**Comment by jhanders34** [comment]
I think it looks good.  The only problem I see is that `3.1` is missing from the `RESTful Web Services` feature name.

**Comment by dmuelle** [comment]
opps- thanks for catching that, fixed in #6422

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this is ready for peer review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee10-diff.html#global

**Comment by ramkumar-k-9286** [comment]
Peer Review
---
Links -> features links will resolve once autogen is added ( Just mentioning).

In Jakarta EE 10, the combination of the Jakarta Connectors 2.1 (connectors-2.1) and [Application Security 5.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html) (appSecurity-5.0) Liberty features replaces what the [Jakarta Connectors Inbound Security 2.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/connectorsInboundSecurity-2.0.html) (connectorsInboundSecurity-2.0) Liberty feature provided in Jakarta EE 9.1.
->
The link not added for Jakarta Connectors 2.1

**Comment by dmuelle** [comment]
The link to Jakarta Connectors 2.1 is already provided in the section so only linked on first mention

**Comment by jhanders34** [comment]
@dmuelle due to last minute changes last week, I need to add another entry to the documentation.  I am thinking something like below, but massage it as you think necessary

---

### Rest Connector availability
The [Jakarta EE Platform 9.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/jakartaee-9.1.html) (`jakartaee-9.1`) Liberty convenience feature included the [Admin Rest Connector 2.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/restConnector-2.0.html) (`restConnector-2.0`) Liberty feature.  The [Jakarte EE Platform 10.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/jakartaee-10.0.html) (`jakartaee-10.0`) Liberty convenience feature no longer includes this Liberty feature.

For Open Liberty applications that require the Admin Rest Connector function, you must now add the Admin Rest Connector 2.0 (`restConnector-2.0`) Liberty feature to your `server.xml` file.

---

Please let me review the PR before merging to avoid extra PRs and delays.
