### ISSUE TITLE
Operator docs page points to old operator docs

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/docs#5970]
This page: https://openliberty.io/docs/latest/open-liberty-operator.html

Has this text: "When you deploy an application with the [Open Liberty Operator](https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide.adoc#open-liberty-operator), the operator watches..."

That link is to docs for the operator 0.71 or earlier.  

We should point to the latest user guide docs here: https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1beta2.adoc

As perhaps a better alternative, the open-liberty-operator user guide page should maintain a link for the latest rather than what they have done which is start new page because this new user-guide-v1beta2.adoc page is going to break when we progress beyond beta2.

**Comment by dmuelle** [comment]
Hi @gcharters - what if we point that link to

https://github.com/OpenLiberty/open-liberty-operator/tree/main/doc#documentation

This page serves as a landing page where reader can choose either the "current" operator doc or earlier versions

**Comment by dmuelle** [comment]
closing as completed, fix will publish with 22.0.0.12
