### ISSUE TITLE
Jakarta 9 differences: JAX-RS 2.1 HttpHeaders.getRequestHeader(String headerName) returns null, not throws IllegalStateException

### ISSUE THREAD

**Issue by realModusOperandi** [OpenLiberty/docs#5977]
Document: Differences between Jakarta EE 9.1 and 8.0
http://openliberty.io/docs/latest/jakarta-ee-diff.html

**Actually, I think the headings for the getRequestHeader and readEntity changes just need to be swapped. getRequestHeader on nonexistent header returns null in 2.1, readEntity on empty entity throws IllegalStateException, but this article says the opposite.**

https://openliberty.io/docs/latest/jakarta-ee-diff.html#headername indicates that the JAX-RS 2.1 behavior of `HttpHeaders.getRequestHeader(String headerName)` is to throw an `IllegalStateException` if no header by the specified name is present. However, my own testing shows it returns null:

```xml
    <featureManager>
         <feature>jaxrs-2.1</feature>
    </featureManager>
```

```java
@GET
@Path("headerNotExist")
@Produces(MediaType.TEXT_PLAIN)
public String headerNotExist(@Context HttpHeaders headers) {
	List<String> header = headers.getRequestHeader("notexist");
	return header.get(0);
}
```

This causes the following error in the logs. The error message indicates that `header` is null so `get(0)` can't be called on it. If it had thrown an `IllegalStateException`, control would never have gotten to that line in the first place.

```
[ERROR   ] SRVE0777E: Exception thrown by application class 'sample.getHeaderStringNotExist.SampleApi.headerNotExist:18'
java.lang.NullPointerException: Cannot invoke "java.util.List.get(int)" because "header" is null
        at sample.getHeaderStringNotExist.SampleApi.headerNotExist(SampleApi.java:18)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at com.ibm.ws.jaxrs20.server.LibertyJaxRsServerFactoryBean.performInvocation(LibertyJaxRsServerFactoryBean.java:656)
        at [internal classes]
```

I think that statement just needs to be adjusted.

**Comment by dmuelle** [comment]
thanks @realModusOperandi , here's the updated draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jakarta-ee-diff.html#headername

If this looks good, you can add the `technical reviewed` label to this issue to sign off. If any further changes are needed, just let me know.

**Comment by dmuelle** [comment]
thanks- update will publish with 22.0.0.12, closing as completed
