### ISSUE TITLE
Java RESTful Services Client 2.1 page has duplicate examples

### ISSUE THREAD

**Issue by rlsanders4** [OpenLiberty/docs#5979]
All examples given on the Java RESTful Services Client 2.1 page (https://openliberty.io/docs/latest/reference/feature/jaxrsClient-2.1.html) are duplicated. Four examples are given, and then the same four examples are listed again with no changes. The pages for the 2.0 and 3.0 versions of this feature do not have this issue.

**Comment by dmuelle** [comment]
Thanks for catching this @rlsanders4. Fixed on draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/restfulWSClient-3.0.html

Change will publish with the 22.0.0.12 docs release

**Comment by dmuelle** [comment]
closing as completed
