### ISSUE TITLE
New --timeout option for command: server stop

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/docs#5992]
Doc for open liberty issue: https://github.com/OpenLiberty/open-liberty/issues/19924

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

@dmuelle @chirp1   - Think I need ID approval for the open liberty issue:  https://github.com/OpenLiberty/open-liberty/issues/19924 

Documentation.    The following page must be updated:

https://openliberty.io/docs/latest/reference/command/server-stop.html

There is a section for options which currently only describes the --force option.
The --timeout option must be added.

--timeout

Specifies the amount of time to wait for the server to stop.

The default time to wait is 30 seconds.

The format for the duration is XXmXXs.   Where 'm' stands for minutes and 's' stands for seconds.   If no units are specified, the value is assumed to be seconds.

For example:
```
   ./server stop myserver                   // 30 seconds
   ./server stop myserver --timeout=45      // 45 seconds
   ./server stop myserver --timeout=45s     // 45 seconds
   ./server stop myserver --timeout=3m20s   // 3 minutes, 20 seconds

**Comment by ramkumar-k-9286** [comment]
Hi @jimblye 

The suggested changes have been added to the document. 

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

If you are happy with the changes, please add the `developer Reviewed` label to this issue.

if any changes are needed, please add a comment to the issue.

Regards,
Ramkumar

CC @dmuelle 

**Note: issue with a code block. please hold off on the review until I fix it.**

**Comment by jimblye** [comment]
In the photo you see that the examples are a bit jumbled.  There should be 4 server stop commands on 4 separate lines..


***@***.***



Earlier on the page, there are usage examples.   We should have one for the command:

server stop myserver –timeout=1m

This sets the timeout value to 1 minute.  The default is 30 seconds.

Thanks,
Jim



From: Ramkumar ***@***.***>
Date: Thursday, November 17, 2022 at 1:23 PM
To: OpenLiberty/docs ***@***.***>
Cc: Jim Blye ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenLiberty/docs] New --timeout option for command: server stop (Issue #5992)
Hi @jimblye The suggested changes have been added to the document. Draft Link: https: //docs-draft-openlibertyio. mqj6zf7jocq. us-south. codeengine. appdomain. cloud/docs/latest/reference/command/server-stop. html If you are happy with the changes,
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @jimblye<https://github.com/jimblye>

The suggested changes have been added to the document.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html<https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html>

If you are happy with the changes, please add the developer Reviewed label to this issue.

if any changes are needed, please add a comment to the issue.

Regards,
Ramkumar

CC @dmuelle<https://github.com/dmuelle>

**Comment by ramkumar-k-9286** [comment]
Hi @jimblye

Corrections have been made to the table and code block.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

If you are happy with the changes, please add the `Developer Reviewed` label to this issue.

if any changes are needed, please add a comment to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by dmuelle** [comment]
Hi @jimblye - this needs a little more work, we'll let you know when it's ready for review.

**Comment by dmuelle** [comment]
ok- think it's ready to go now

**Comment by jimblye** [comment]
@ramkumar-k-9286 @dmuelle 

Suggestion:   In the usage examples, each example has descriptive text above the example.   In the new one, the descriptive text is above and below.   I suggest keeping the description consistently above the example.   Only a suggestion.

<img width="558" alt="image" src="https://user-images.githubusercontent.com/16544901/203072388-b4963275-368d-47d5-a85f-dcb37648b30e.png">

---------

For the --timeout option description, I gave 4 examples:

```
   ./server stop myserver                   // 30 seconds
   ./server stop myserver --timeout=45      // 45 seconds
   ./server stop myserver --timeout=45s     // 45 seconds
   ./server stop myserver --timeout=3m20s   // 3 minutes, 20 seconds
```
   
Of the 4 examples , I see only the 1st & 4th are used.   The 2nd shows that you do not need to use units.  That is not described anywhere.  So it is an important example. The 3rd shows that you can use XXs syntax without the XXm.   If you want to drop an example, the 1st which does not specify a timeout, is the least helpful since the description already says the default is 30s.  I would keep the 2nd, 3rd & 4th examples.   Note also that I have added the **server name** , myserver, to the examples rather than taking the default.  

<img width="633" alt="image" src="https://user-images.githubusercontent.com/16544901/203074231-4c7ac8ec-09be-4b37-bcb1-27b6c2b44227.png">

**Comment by ramkumar-k-9286** [comment]
Hi @jimblye

Corrections have been made to the Usage examples and the examples in the code block.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

If you are happy with the changes, please add the `Developer Reviewed` label to this issue.

if any changes are needed, please add a comment to the issue.

Regards,
Ramkumar

CC @dmuelle

**Comment by dmuelle** [comment]
## Peer review

The existing content page refers to the period of time that the server waits to stop as the "quiesce stage". The new content should also use this term for continuity. Otherwise, it might appear that the quiesce stage is something separate or in addition to the time set by the timeout option. Alternatively, the term could be removed altogether but we might as well keep it, unless @jimblye disagrees.


Set the amount of time to wait for the myserver server to stop
--->
Set the duration of the quiesce stage for the myserver server, which is the amount of time the server waits before it stops.


---

Specifies the amount of time to wait for the server to stop.
--->
Specifies the duration of the quiesce stage, which is the amount of time the server waits before it stops. The default value is 30 seconds.

---

The format for the duration is XXmXXs. Where m stands for minutes and s stands for seconds.
--->
The format for the duration is XXmXXs, where m stands for minutes and s stands for seconds.

**Comment by jimblye** [comment]
@ramkumar-k-9286 @dmuelle

Nope, there are two different timeouts.   Though, I do not believe the document makes this clear, and it should.

The 30-second quiesce phase is a timer that runs on the server.  This phase starts when the server receives the stop request.  The server runs all registered ServerQuiesceListener services and waits for them to finish before beginning to stop the actual server runtime.  These services do things like closing HTTP ports and waiting for application threads to finish.  The maximum amount of time the server will wait is 30 seconds, and this is not configurable.  If you stop the server with the ‘—force’ option the quiesce phase is skipped altogether.

The **server stop** command launches a separate JVM process which sends a stop request to the server via a TCP socket.  The JVM process then monitors the server JVM process for a default time of 30 seconds waiting for the server to stop.  This timeout is configurable using the --timeout option.

Let me know if you have questions.

**Comment by dmuelle** [comment]
Thanks @jimblye  - hmmm that is tricky. So does the quiesce stage run concurrently with the timeout duration? ie at default, they both overlap and end together (ideally). Or does the timeout duration start after the quiesce stage?

**Comment by dmuelle** [comment]
or does it start before? you get the quiesce stage after the timeout duration is up, unless you set `--force` ?

**Comment by jimblye** [comment]
@ramkumar-k-9286 @dmuelle
No, it is not ideal for them to end together.   Ideally, the quiesce phase is quick, milliseconds, and then the server can get on with the process of shutting down the server runtime.   The purpose of the quiesce phase is to not pull the rug out from under the applications and to bring things down in a controlled manner.

When you issue a **server stop --timeout=xx** command, you have essentially started a client which sends a stop request to the server.  The **client** then periodically checks to see if the **server** has stopped.  By default the **client** will continue to poll/wait for a maximum of 30 seconds for the **server** to stop, but you can change the timeout value with the --timeout option.   The **server** might not stop in that amount of time.  So we might have a timeout on the **client** while the **server** is still in the process of shutting down.  The user should increase the value of the timeout if the server frequently takes longer to shutdown than is expected.
 
  The timers have different purposes.   The quiesce timer is making sure we have a controlled shutdown by waiting for things like HTTP ports to close and for application threads to finish.    The --timeout is the one the user can see.  The user enters the command and then there is a period of time before that command finishes waiting for the server to stop, and the command prompt appears.
 
 Keep in mind when explaining this that there is only one timeout value that is configurable.  You probably won't know how long the quiesce phase took.   Possibly we have some logging that will show that.  If the shutdown takes a long time, you won't know whether we were stuck for the full duration in the quiesce phase, or if the quiesce phase terminated quickly, and the shutdown of the runtime got hung up for some time.
 
 Hopefully that helps?

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle

Corrections have been made to the document.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

Regards,
Ramkumar

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle

Corrections have been made to the document.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 I think we should add the default value to the table, even though it's stated earlier on the page. We should also use some of the language that Jim added to the help top make the difference more clear. Also the sentences that talk about the format are fragments and need to be joined into a single sentence. Also need to remove past perfect tense (has stopped).

Suggested edit:

Specifies the maximum amount of time that the server stop command waits for confirmation that the server is stopped. The default value is 30 seconds.

This timeout is not related to the quiesce stage, which is the maximum amount of time the server waits for pre-shutdown work to complete before it starts to shut down the runtime. The quiesce stage timer is not configurable, though it can be skipped by using the `--force` option.

The format for the duration is XXmXXs, where `m` stands for minutes and `s` stands for seconds.

The following example shows how...

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle

Comments have been incorporated.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

Regards,
Ramkumar

**Comment by jimblye** [comment]
The changes look good.   Thanks.

**Comment by dmuelle** [comment]
LGTM- i think you can send this to staging to prepare for the release

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle

Doc has been pushed to staging

Staging Link:
https://staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html


Regards,
Ramkumar

**Comment by dmuelle** [comment]
Hi @ramkumar-k-9286 

Jim got some code review feedback that impacts the doc for --timeout. Basically we want to tell people not to set it for less than the default. I think wee need edits in two places

1. Introduction

The server stop command also includes a 30 second waiting period for confirmation that the server is stopped. You can customize this waiting period with the `--timeout` option.
--->
The server stop command also includes a 30 second waiting period for confirmation that the server is stopped. You can increase this waiting period with the `--timeout` option.

2. Table description
2nd paragraph should be changed to

> This timeout is separate from the quiesce stage, which is the maximum amount of time the server waits for pre-shutdown work to complete before it starts to shut down the runtime.  However, do not configure the `--timeout` option  for a duration less than the default of 30 seconds because confirmation of server stop might be delayed by the quiesce process during that time. The quiesce stage timer is not configurable, though it can be skipped by using the `--force` option.

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle

Comments have been incorporated.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
topic is on vNext and will publish with 22.0.0.13, closing as completed

**Comment by dmuelle** [comment]
this issue was pulled out of 22.0.0.13

**Comment by dmuelle** [comment]
commented out the update until the code is GM, projected 23.0.0.1

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Comment blocks have been removed. The timeout session has been re-introduced.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- when you have a chance, open a PR to staging. Thanks

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

The timeout option was added to staging.

Staging Link:
https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-stop.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, thanks
