### ISSUE TITLE
Document maxFfdcAge

### ISSUE THREAD

**Issue by tonyreigns** [OpenLiberty/docs#6058]
New maxFfdcAge feature: https://github.com/OpenLiberty/open-liberty/issues/19418

Add a new attribute under Section "[Configuration settings by source](https://openliberty.io/docs/latest/log-trace-configuration.html#settings)":

Server XML Attribute | bootstrap property | Env var | Description
--- | ---  | ---  | ---
maxFfdcAge | com.ibm.ws.logging.max.ffdc.age | WLP_LOGGING_MAX_FFDC_AGE | Use this setting to enable FFDC file purging based on age. This setting specifies the maximum desired file age before an FFDC file is deleted. Purges will occur everyday at midnight. Specify a positive integer followed by a unit of time, which can be days (d), hours (h), or minutes (m). For example, specify 2 days as 2d. You can include multiple values in a single entry. For example, 2d6h is equivalent to 2 days and 6 hours.

**Comment by dmuelle** [comment]
Hi @tonyreigns - this update is now on draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/log-trace-configuration.html#settings

The maxFfdcAge entry is about halfway through the table, with other non log-specific settings

If any further changes are needed, just let me know. If not, you can sigh off by adding the `technical reviewed` label to this issue and the update will publish with 22.0.0.13. Thanks!

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 22.0.0.13. Closing as completed
