### ISSUE TITLE
LG-234 mpMetrics-2.1

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#606]
Epic: https://github.com/openliberty/open-liberty/issues/8653

**Comment by Yushan-Lin** [comment]
**For https://openliberty.io/docs/ref/general/#metrics-catalog.html:**
For the reference list, rename the column MPMETRICS-2.0 NAME to MPMETRICS-2.0/2.1 NAME.
Change the above paragraph to:
Some metric names changed between MicroProfile Metrics 1.1 and MicroProfile Metrics 2.0/2.1. The following table lists the mpMetrics-2.0/mpMetrics-2.1 metric names and the corresponding mpMetrics-1.1 metric names. It also lists the metric types, metric units, and descriptions of all metrics that are available for Open Liberty: 

**Create another page similar to https://openliberty.io/docs/ref/feature/#mpMetrics-2.0.html but for 2.1:**

**MicroProfile Metrics 2.1**

This feature provides support for the Eclipse MicroProfile Metrics 2.1 specification for enterprise Java.
**Enabling this feature**

To enable the MicroProfile Metrics 2.1 feature, add the following element declaration into your `server.xml` file, inside the `featureManager` element:
`<feature>mpMetrics-2.0</feature>`

**Feature configuration elements**
Same as 2.0
**Stable API packages provided by this feature**
Same as 2.0
**Features that this feature enables**
Same as 2.0
**Supported Java versions**
Same as 2.0
**Features that enable this feature**
microProfile-3.1

**Developing a feature that depends on this feature**
com.ibm.websphere.appserver.mpMetrics-2.1; type="osgi.subsystem.feature"

**Comment by Yushan-Lin** [comment]
**For https://openliberty.io/docs/ref/general/#microservice_observability_metrics.html:
Update the Gauge section:**
Gauge metrics are implemented by the developer in a way that allows them to be sampled to obtain a particular value. For example, you might use a gauge metric to measure CPU temperature or disk usage. For MicroProfile Metrics 2.1, gauge metrics can only sample numbers.

**Comment by fmhwong** [comment]
`mpMetrics-2.1` will **not** be included in 9.0.0.11.
