### ISSUE TITLE
tWAS constrained delegation doc update

### ISSUE THREAD

**Issue by utle** [OpenLiberty/docs#6061]
https://www.ibm.com/docs/en/was/9.0.5?topic=sign-configuring-kerberos-constrained-delegation-outbound-spnego-tokens
1) Before Procedure
Add a Restriction:
Constrained delegation credential is not serializable so it can not propagate to the down stream server. Customer need to  disable the "Web inbound security attribute propagation". See the "Propagating security attributes among application servers" for how to disable the "Web inbound security attribute propagation".
https://www.ibm.com/docs/en/was/9.0.5?topic=users-propagating-security-attributes-among-application-servers

2) Procedure 1. 
We want to  have `To use S4U2proxy.` before `To use S4U2self.`

3) The procedure to configure Kerberos constrained delegation is also available in the Microsoft Docs website, see [How to configure Kerberos Constrained Delegation for Web Enrollment proxy pages](https://www.ibm.com/links?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Ftroubleshoot%2Fwindows-server%2Fidentity%2Fconfigure-kerberos-constrained-delegation) .

Change to: 

The procedure to configure Kerberos constrained delegation is also available in the Microsoft Docs website, **see step 2. Configure the delegation in this article** [How to configure Kerberos Constrained Delegation for Web Enrollment proxy pages](https://www.ibm.com/links?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Ftroubleshoot%2Fwindows-server%2Fidentity%2Fconfigure-kerberos-constrained-delegation) .

**Comment by dmuelle** [comment]
@utle - this is the Open Liberty docs backlog. Should this issue be on the [tWAS docs backlog](https://github.ibm.com/websphere/twas-docs/issues)?

**Comment by Zech-Hein** [comment]
@dmuelle - yes!

**Comment by dmuelle** [comment]
transferred the info to https://github.ibm.com/websphere/twas-docs/issues/6064, closing this issue
