### ISSUE TITLE
ID: LG-235 mpHealth-2.1

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#607]
Epic: https://github.com/openliberty/open-liberty/issues/8655

**Comment by fmhwong** [comment]
`mpHealth-2.1` will **not** be included in 9.0.0.11.

**Comment by dmuelle** [comment]
@fmhwong @pgunapal the updated doc is now on the OL draft site- Are there any other updates needed for this doc?

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#health-check-microservices.html

**Comment by pgunapal** [comment]
@dmuelle The OL draft doc looks good. It has all the required updates.

**Comment by dmuelle** [comment]
doc is published at https://www.openliberty.io/docs/ref/general/#health-check-microservices.html
