### ISSUE TITLE
Topic on WebSocket or more broadly on client/server communication options?

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#6071]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

The new WebSocket guide (currently in [draft](https://guides-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/guides/jakarta-websocket.html)) doesn't have anywhere to point for the user/developer to find out more about WebSocket and related/alternative technologies/methods (inc maybe Server-sent events(?), which I think we have a blog post on) - when you should use WebSocket vs other alternatives (not sure what they all are so would need to find out) in order to best manage communications. eg WebSocket keeps the connection open for two-way communications so you don't need to poll for responses. This is valuable in some cases but probably not others. WebSocket is faster than HTTP (uses TCP, not HTTP).

**Comment by dmuelle** [comment]
Adding this to the Epic we have for #4848 - which mentions WebSocket as a topic- we already have topics on gRPC and GraphQL, not sure if SSE qualifies as a rest alternative as well. This has been hanging around my prioritization list for a while and I just haven`t had the bandwidth to get to it- hopefully in 1Q23. Part of the work is also a short overview that discusses alternatives to REST- why you might need them, how they compare etc.

**Comment by lauracowen** [comment]
I think one thing to check might be whether "alternatives to REST" is the only way that alternative communications options should be mentioned. The new (in draft) WebSocket guide compares WebSocket with SSE as a capability. So it seems like a useful comparison to make. It might be worth checking what comparable technologies there are (as well as just whether they're RESTful or not).

**Comment by dmuelle** [comment]
Hi @volosied - would you review this topic on webSocket?

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/web-socket.html

**Comment by volosied** [comment]
Article looks great, but I do have just a few small comments: 

`“This request includes an HTTP upgrade request to upgrade the HTTP connection to a TCP connection where the actual WebSocket communication occurs.”`
 - It don’t think it should say that it upgrades to a TCP Connection.   
- Something like this instead?: “upgrade the HTTP connection to use the WebSocket protocol where the new communication occurs.”

`
“REST frameworks”  `
- Can REST be described as a framework? Or is it an architecture / design pattern? I’m not sure of the right terminology.

`By contrast, REST requests establish a new TCP connection for each message, which can lead to higher overhead per message than with WebSocket.`
- You could also add that HTTP Headers, which are sent on every request, could be longer than the application data in some instances.

**Comment by dmuelle** [comment]
Thanks for reviewing @volosied - I made the changes you've suggested as well as some other minor edits.

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/web-socket.html

- [x] I don’t think it should say that it upgrades to a TCP Connection.
- [x] removed references to REST as a "framework"
- [x] You could also add that HTTP Headers, which are sent on every request, could be longer than the application data in some instances.

Let me know if any further changes are needed. If not, you can sign off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by volosied** [comment]
Looked over it one last time, and I don't like the wording I originally suggested. Could you update it to:

`upgrade from the HTTP protocol to the WebSocket protocol where the new communication occurs`. 

Last comment: 

`Every REST request also includes its own HTTP header, ` header should be plural,  I think.

**Comment by dmuelle** [comment]
thanks @volosied , I've made those edits in the updated draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/web-socket.html

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this topic is ready for peer review when you have a chance:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/web-socket.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

The Open Liberty Jakarta WebSocket feature supports applications that use this protocol.
->
Question - Adding link to the **Jakarta WebSocket feature** here.
I remember a conversation where you mentioned that link needs to be added, the first time its mentioned. 
I see a link added for the **Jakarta WebSocket feature** later in the doc. Should it be added the first time or is it that we don't add links in the short description?


 Furthermore, the connection remains open until it is explicitly closed, so messaging can occur in real time without interruptions.
->
**real time** being mentioned in different ways ( **real-time** (short description) & **real time** (here) ) - believe we should stick to one way.


The WebSocket protocol enables two-way communication between client and server endpoints on top of a Transmission Control Protocol (TCP) connection.
->
Acrolinx picking up **top** - I believe it's accessibility-related - usage seems ok to me.
**Rephrased sentence** - The WebSocket protocol enables two-way communication between client and server endpoints **by utilizing/using the** Transmission Control Protocol (TCP) connection.


For example, an online multiplayer racing game might use the WebSocket protocol to receive each player’s position while it sends the location of the other players back out to each browser client.
-> **( Acrolinx by 1 word)**
**Rephrased sentence** - For example, an online multiplayer racing game might use the WebSocket protocol to receive player positions while it sends the location of the other players back out to each browser client.

This feature enables support for applications that use the [Jakarta WebSocket API](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/docs/latest/reference/javadoc/liberty-jakartaee9.1-javadoc.html?package=jakarta/websocket/package-frame.html&class=jakarta/websocket/package-summary.html).
->
Jakarta WebSocket API - Link issue

You can learn how to use Jakarta WebSocket with Open Liberty in the [Bidirectional communication between services using Jakarta WebSocket](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/guides/jakarta-websocket.html) guide.
->
Bidirectional communication between services using Jakarta WebSocket - Link issue
+
Bidirectional communication between services **by using the** Jakarta WebSocket guide. - Acrolinx


WebSocket, REST, and Server Sent Events
->
WebSocket, REST, and **Server-Sent** Events 
( Checked online - mentions of Server Sent Events are shown like **Server-Sent** Events 


Depending on the context, REST communication is still a preferred choice for many web applications, while others might benefit from server sent events (SSE), another alternative to WebSocket.
->
Depending on the context, REST communication is still a preferred choice for many web applications, while others might benefit from **server-sent** events (SSE), another alternative to WebSocket.


By contrast, REST requests establish a new TCP connection for each message, which can lead to higher overhead per message than with WebSocket.
->
Acrolinx picking up - **overhead** - "Do not use - Use terminology that is more specific"


Furthermore, with WebSocket, a client and server can send and receive messages simultaneously, without having to wait for a response. This kind of communication is not feasible with REST, where a server must wait for a request before it sends data to a client.
->
Acrolinx picking up - **Kind of** - "Delete this word, phrase, or punctuation"
Suggestion - This **type of** communication is not feasible with REST, where a server must wait for a request before it sends data to a client.


However, WebSocket can be more complex to set up than SSE, which works on top of HTTP and doesn’t require a separate protocol.
->
Acrolinx picking up **top** - I believe it's accessibility-related - usage seems ok to me.
**Rephrased sentence** -  However, WebSocket can be more complex to set up than SSE, which **operates over** HTTP and doesn’t require a separate protocol.


For more information about SSE with Open Liberty, see the [Streaming updates to a client using Server-Sent Events](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/guides/reactive-messaging-sse.html) guide.
->
Streaming updates to a client using Server-Sent Events - Link issue
 +
Streaming updates to a client **by using the** Server-Sent Events guide. - Acrolinx

**Comment by dmuelle** [comment]
Thanks for reviewing @ramkumar-k-9286 - all suggestions implemented except:

 The Open Liberty Jakarta WebSocket feature supports applications that use this protocol.
->
Question - Adding link to the Jakarta WebSocket feature here.
**no links in shortdesc**

-  ( real-time (short description) & real time (here) ) - as we discussed, use\d in two different ways- compound adjective vs  adjective and noun so, ok.
- no guide links work in the `docs-draft` site

**Comment by dmuelle** [comment]
content is on vNext and will publish with 23.0.0.4- closing as completed
