### ISSUE TITLE
Add column to metrics reference list topic

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#608]
We need to add another column to the table on https://draft-openlibertyio.mybluemix.net/docs/ref/general/#metrics-catalog.html that lists which feature(s) you have to use to get each metric.

For example, you must enable the mpFaultTolerance feature to get the ft.* metrics, etc.

**Comment by Channyboy** [comment]
Metric names that have their Prometheus metric name start with `vendor` are enabled by enabling the `mpMetric-x.x` feature. + `monitor-1.0`

Metric names that have their Prometheus metric name start with `base` are enabled just by the base `mpMetric-x.x` feature.

As mentioned above any metric that start with `ft.*` will need the `mpFaultTolerance` enabled.

**Comment by Charlotte-Holt** [comment]
This is live at https://openliberty.io/docs/ref/general/#metrics-catalog.html. Closing this issue.
