### ISSUE TITLE
logging configuration page is causing confusion about valid trace levels

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/docs#6108]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

### Does the defect apply to an APAR? 
- [ ] Yes
   - Specify the fix pack____.
   - Specify the APAR number____.
   - Add the fix pack number and the APAR number to the title of this issue.
- [x] No 

### Does the documentation apply to all operating systems? 
- [x] Yes  
- [ ] No Specify operating systems: ______

### Does the documentation apply to all editions? 
(Liberty Core, Liberty base, Liberty ND, Liberty z/OS)?
- [x] Yes.
- [ ] No. Specific editions: ______

### Specify what you want documented (required):
Complete the following information:

On page https://openliberty.io/docs/latest/log-trace-configuration.html , we need to fix 2 things:
- eliminate confusion over what trace levels, when enabled, result in creation of a trace.log file 
  - setting trace components to any of config, detail, fine, finer, finest, all levels causes a trace.log file to be created

- eliminate confusion over affect of setting trace component levels to any of severe, warning, audit, info
  - setting Liberty loggers to any of those levels is equivalent to setting them to info level since we don't allow messages at those levels to be filtered out.

there are a few places that cause this confusion 
- the "Logging configuration settings" table lists all the levels.  I suggest we indicate that setting a trace component to any of levels off, fatal, severe, warning, audit, info has the same affect as setting it to info level as info and higher levels cannot be disabled.  we should also state that a trace.log file will only be created and written to if one or more trace components is set to level config or lower.

- the "valid log detail levels for the trace log" table shows log levels and trace levels.  I suggest we also mention here that setting a trace component to any of levels off, fatal, severe, warning, audit, info has the same affect as setting it to info level as info and higher levels cannot be disabled.  we should also state that a trace.log file will only be created and written to if one or more trace components is set to level config or lower.

change:
The following example specifies the audit detail level...
to:
The following example specifies the info detail level...

change (in 2 places):
`logging traceSpecification="*=audit:com.myco.mypackage.*=finest"`
to:
`logging traceSpecification="com.myco.mypackage1.*=fine:com.myco.mypackage2.*=finest"`

change:
The wildcard value *=audit applies to all traceable code that is running on the server. The com.myco.mypackage.*=finest value applies to all classes with the package name that begins with com.myco.mypackage.
to:
The com.myco.mypackage1.*=fine value applies to all classes with the package name that begins with com.myco.mypackage1 and the com.myco.mypackage2.*=finest value applies to all classes with the package name that begins with com.myco.mypackage2.

Question to @pgunapal -- given the trace specification values off, fatal, severe, warning, audit, info all are treated as info, do we need to document the others?  Do the others have an affect on JUL loggers that might be in Liberty or application code?

**Comment by pgunapal** [comment]
I think it would be good to document the others, for completion. No they don't have any affect on JUL Loggers in Liberty or application code, they are all treated as FINE, FINER, and FINEST for trace.

**Comment by hiltoncv** [comment]
Updates are available at:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/log-trace-configuration.html

**Comment by hiltoncv** [comment]
@donbourne and @pgunapal If the updates are fine, please add the label "technical reviewed" to the issue.

**Comment by donbourne** [comment]
The following example specifies the info detail level for all code that is running on the server and the finest detail level for an example package.
->
The following example specifies a trace specification for two groups of components.

**Comment by hiltoncv** [comment]
Incorporated comments!

**Comment by hiltoncv** [comment]
Thanks Don!
