### ISSUE TITLE
Clarify how to install Admin-center feature

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6141]
augment the first sentence in https://openliberty.io/docs/latest/admin-center.html#_set_up_admin_center so that it links to https://openliberty.io/docs/latest/reference/command/featureUtility-installFeature.html so it's clear to the user how to install the feature

also- add a snippet directly to the topic telling user to run featureUtility installFeature adminCenter-1.0 if the feature is not already installed

**Comment by mbroz2** [comment]
lgtm

**Comment by dmuelle** [comment]
changes are on vNext and will publish with 22.0.0.13, closing as completed
