### ISSUE TITLE
Update valid log detail levels for the trace log table

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#6168]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

https://openliberty.io/docs/latest/log-trace-configuration.html#configuaration

Please change the following lines in the Valid log detail levels for the trace log table.

| Logging level | Content or Significance |
|---|---|
| fine | General trace |
| finer | Detailed trace that includes method entry, exit, and return values |

**Comment by fmhwong** [comment]
@donbourne Does this look okay to you?

**Comment by donbourne** [comment]
yes, looks good.

**Comment by hiltoncv** [comment]
@fmhwong Do you mean to say swap the current descriptions of fine/finer in the table?

**Comment by fmhwong** [comment]
> @fmhwong Do you mean to say swap the current descriptions of fine/finer in the table?

Not exactly.  I moved the "that includes method entry, exit, and return values" from fine to finer

**Comment by hiltoncv** [comment]
Updates are available at:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/log-trace-configuration.html
Please validate!

**Comment by fmhwong** [comment]
LGTM

**Comment by hiltoncv** [comment]
Changes are committed to vNext.
