### ISSUE TITLE
Upgrade to EPLv2

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/docs#6169]
This issue is to scan and make sure all existing docs that may have EPLv1 references are switched to EPLv2

We have switched our license, and starting with 23.0.0.1 - We are using this license.

Parent issue here: https://github.com/OpenLiberty/open-liberty/issues/23585

**Comment by hiltoncv** [comment]
No occurrence of "EPLv1" was found in the Open Liberty documentation. Closing the issue.
