### ISSUE TITLE
Clarify supported Java info

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6185]
The[ Java SE support page](https://openliberty.io/docs/latest/java-se.html) lists the supported Java levels and offers guidance on choosing a JVM. We should make it more clear that OL runs on any spec-compliant JVM, so that references to Eclipse and OpenJ9 on the page don't appear to restrict support to those distributions.

1. clarify that the java versions are determined by the specific column for versions in the table.

Open Liberty runs on any of the Java SE versions that are listed in the [Supported Java Releases](https://openliberty.io/docs/latest/java-se.html#supported) table.

--->

Open Liberty runs on any of the Java SE versions that are listed in the _Java SE version_ column of the [Supported Java Releases](https://openliberty.io/docs/latest/java-se.html#supported) table.

~~2. Edit the sentence in the beginning of the JVM paragraph to clarify that any compliant  implementation works for Liberty~~

~~Two commonly used Java virtual machine (JVM) implementations are available: [Eclipse OpenJ9](https://www.eclipse.org/openj9/) and [HotSpot](https://openjdk.java.net/groups/hotspot/).~~

--->

~~Open Liberty can use any specification-compliant Java virtual machine (JVM) that runs with a supported Java SE version. Two commonly used JVMs are [Eclipse OpenJ9](https://www.eclipse.org/openj9/) and [HotSpot](https://openjdk.java.net/groups/hotspot/)....~~

**Comment by NottyCode** [comment]
@dmuelle I don't like the proposed update 2. I understand the concern that was raised, but that is because the reader was conflating JVM with Java distribution and I don't think the update addresses that confusion.

**Comment by ramkumar-k-9286** [comment]
Hi David,

Suggested correction is done to the document.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
The change looks good. We might more directly address the confusion that raised this issue (JVM vs Java Distribution) by making the following edit as well.

Two commonly used Java virtual machine (JVM) implementations are available: [Eclipse OpenJ9](https://www.eclipse.org/openj9/) and [HotSpot](https://openjdk.java.net/groups/hotspot/). They provide similar throughput performance, but make different tradeoffs for memory footprint and startup.
--->
Regardless of which Java SE Version you use, two Java virtual machine (JVM) implementations are available: [Eclipse OpenJ9](https://www.eclipse.org/openj9/) and [HotSpot](https://openjdk.java.net/groups/hotspot/), each of which is packaged in different Java distributions. These JVMs provide similar throughput performance, but make different tradeoffs for memory footprint and startup.


What do you think @NottyCode ?

**Comment by ramkumar-k-9286** [comment]
Hi David,

The suggested correction is done.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle ,

The Staging link.

https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM thanks

**Comment by dmuelle** [comment]
change on vnext, will publish with 23001
