### ISSUE TITLE
Corrections/updates to Relational database connections with JDBC topic

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/docs#6249]
The first sentence of section https://openliberty.io/docs/latest/relational-database-connections-JDBC.html#types is incorrect
>To access a database from your Open Liberty application, your application code must implement the javax.sql.DataSource interface. 
should be 
>To access a database from your Open Liberty application, your application code must use the javax.sql.DataSource interface. 
The first bullet of that section should be reqworded to clarify
>This type of data source is the basic form. It does not provide the interoperability that enhances connection pooling and cannot participate as a two-phase capable resource in transactions that involve multiple resources.
should be
>This basic form of data source does not provide functionality such as connection and statement event listeners which Liberty uses to optimize connection pooling nor can it participate as a two-phase capable resource in transactions that involve multiple resources.

**Comment by ramkumar-k-9286** [comment]
Hi Fred @frowe 

Made the update.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/relational-database-connections-JDBC.html#types

Regards,
Ramkumar


CC: David @dmuelle

**Comment by frowe** [comment]
Hi Ramkumar, one comment, I'm not a fan of "certain functionalities", it seems awkward.  I think the simpler form "functions" is better suited.
>This basic form of data source lacks certain functionalities that are used 
vs
>This basic form of data source lacks functions that are used

**Comment by ramkumar-k-9286** [comment]
Hi Fred @frowe

Made the suggested update.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/relational-database-connections-JDBC.html#types

Regards,
Ramkumar

CC: David @dmuelle

**Comment by frowe** [comment]
@ramkumar-k-9286 Ramkumar, looks good.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Staging Link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/relational-database-connections-JDBC.html#types

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM
