### ISSUE TITLE
Update security vulnerability list for 23.0.0.2

### ISSUE THREAD

**Issue by clarkek123** [OpenLiberty/docs#6252]
Draft is updated in PR https://github.com/OpenLiberty/docs/pull/6251

**Comment by dmuelle** [comment]
draft updates: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

**Comment by dmuelle** [comment]
changes are on vNExt and will publish with 23.0.0.2. Closing as completed. thanks
