### ISSUE TITLE
Garantir signing platform changes - verification steps

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/docs#6262]
Internally IBM is changing the signing platform, and will require some tweaks to the signing verification document we currently publish [here](https://openliberty.io/docs/latest/verifying-package-signatures.html)

To be clear, the old instructions for 23.0.0.1 and previous remain - 

Starting in 23.0.0.2 - new instructions for verifying the binaries:

1) A New public key is being used: WebSphereLiberty_02-13-2023.pem. 
   published to same location: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/

2) No longer using openssl - using "cosign" - the most straightforward method for verification is using cosign app
install info Info  [here](https://github.com/sigstore/cosign/releases/latest)

example command:
`cosign verify-blob --key WebSphereLiberty_02-13-2023.pem --signature testSigs/openliberty-23.0.0.2.zip.cosign.sig openliberty-23.0.0.2.zip`

3) Maven Central verification - Changing key ID value to: 9E68CA00

**Comment by cbridgha** [comment]
More details under the maven central section....  key is different - including the name...

**gpg2 --keyserver hkp://keyserver.ubuntu.com --recv-keys 9E68CA00**

**[root]# gpg2 --edit-key "International Business Machines Corporation <psirt@us.ibm.com>"**
gpg (GnuPG) 2.2.20; Copyright (C) 2020 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.


pub  rsa4096/BD9FD5BE9E68CA00
     created: 2023-02-10  expires: 2027-02-09  usage: SCE 
     trust: unknown       validity: unknown
[ unknown] (1). International Business Machines Corporation <psirt@us.ibm.com>

**gpg> trust**
pub  rsa4096/BD9FD5BE9E68CA00
     created: 2023-02-10  expires: 2027-02-09  usage: SCE 
     trust: unknown       validity: unknown
[ unknown] (1). International Business Machines Corporation <psirt@us.ibm.com>

Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)

  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
  m = back to the main menu

Your decision? 5
Do you really want to set this key to ultimate trust? (y/N) y

**Comment by cbridgha** [comment]
Forgot to add - there is a new public key - so we need to change our link to this file: https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/WebSphereLiberty_02-13-2023.pem

**Comment by dmuelle** [comment]
@cbridgha The website team will have to make that change on the getting started page as ID doesnt maintain or have access to it. I opened https://github.com/OpenLiberty/openliberty.io/issues/3045 on the website backlog for that change

**Comment by dmuelle** [comment]
The updated draft of the doc page is ready for review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verifying-package-signatures.html

Let me know if any further changes are needed. If not, you can sign off by adding the `Technical reviewed` label to this issue.

**Comment by irisleung** [comment]
@dmuelle Should we have *cosign.sig instead of *sig?  The signature file name is now *cosign.sig.

**Comment by dmuelle** [comment]
@irisleung yes, thanks for catching that- I've updated the draft to fix it

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verifying-package-signatures.html

**Comment by cbridgha** [comment]
ok some tweaks...  the correct commend for the gpg2 --edit-key command:  `gpg2 --edit-key "International Business Machines Corporation <psirt@us.ibm.com>"`

**Comment by cbridgha** [comment]
here is the result from the --verify command:  

```
# gpg2 --verify openliberty-runtime-23.0.0.2.zip.asc
gpg: assuming signed data in 'openliberty-runtime-23.0.0.2.zip'
gpg: Signature made Thu 02 Mar 2023 09:02:22 AM PST
gpg:                using RSA key E70E5D6C3F1E452CB0F67DF1BD9FD5BE9E68CA00
gpg: Good signature from "International Business Machines Corporation <psirt@us.ibm.com>" [ultimate]
```

**Comment by dmuelle** [comment]
updated the Maven output:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verifying-package-signatures.html
