### ISSUE TITLE
Document default docker pull behavior on container image page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6288]
on https://openliberty.io/docs/latest/container-images.html#tags, add a note that when you use Docker CLI to pull from ICR, you dont need to specify `latest`- CLI uses it by default

**Comment by dmuelle** [comment]
example of running `docker pull icr.io/appcafe/open-liberty`

<img width="572" alt="Screenshot 2023-02-21 at 12 19 55 PM" src="https://user-images.githubusercontent.com/48686014/220467302-b4c644a5-3324-4936-9e91-1d773ac61647.png">

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Added the following Note in the doc. Not sure about the exact format.

Note: 
When using Docker CLI to pull from IBM Cloud Registry (ICR), there is no need to specify the `latest` tag. This is because the CLI will automatically use the `latest` tag by default if no specific tag is specified. Therefore, you can simply use the command `docker pull <image_name>` to pull the latest version of the image from ICR.

Draft: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html#tags

Regards,
Ramkumar

**Comment by dmuelle** [comment]
I dont think that will pass acrolinx on several points :) 
 
 However there was more discussion about this on the website call today and I would propose a slightly different solution. Basically, this doesn't just apply to Docker CLI.
 
 In the **Container images on IBM Container Registry** section, add a statement after the list of tags.
 

> These tags pull the latest version because they do not specify a version number. You can specify a version other than the latest version in the image tag.   _ If you do not specify a tag value, `latest` is used by default_.  For more information about these tag values, see the [Container image tags naming conventions](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html#tags) section.


Then mention again in the **Container image tags naming conventions**, in the bulleted list where it talks about latest.

> latest: This tag simplifies pulling the full latest Open Liberty release with Java 8. It is an alias for the full-java8-openj9-ubi tag. _If you do not specify a tag value, `latest` is used by default._

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the suggested corrections.

Draft: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM- ready for staging

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Staging Link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM
