### ISSUE TITLE
Enhance generated feature docs with config snippets

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#630]
From Aha feature: https://bigblue.aha.io/features/ENGAGE-11 "Provide good server configuration snippets that users can easily find and consume - in OL documentation"

Creating this epic to collate all the individual config snippets identified to enhance the generated feature doc in OL; eg as prototyped in https://openliberty.io/docs/ref/feature/#jdbc.html

**Comment by Charlotte-Holt** [comment]
Closing epic issues. Can reopen if we find these are missed or useful.
