### ISSUE TITLE
Remove references to "Containerfile" from dev mode page

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6303]
Dev mode in a container doesn't officially support Podman but on our dev mode page in the [Container support for dev mode](https://openliberty.io/docs/latest/development-mode.html#_container_support_for_dev_mode) section it says things like:

> you can use the same Dockerfile or Containerfile file for both development and production.

we need to remove all references to `Containerfile`  from this section.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Removed 3 `Containerfile` references in the dev mode page.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/development-mode.html#_container_support_for_dev_mode

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- ready for staging

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Staging Link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/development-mode.html#_container_support_for_dev_mode

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM
