### ISSUE TITLE
Update JDBC Tracing page with Oracle updates

### ISSUE THREAD

**Issue by KyleAure** [OpenLiberty/docs#6326]
Update the [JDBC Tracing](https://openliberty.io/docs/latest/jdbc-tracing.html#Oracle) page with updates that have been made to customize the location of Oracle Tracing. 
See issue: https://github.com/OpenLiberty/open-liberty/issues/18370

**Comment by dmuelle** [comment]
Hi @KyleAure updates are now on draft: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jdbc-tracing.html#OracleCustom

Let me know if any further edits are needed. If not, you can sign off by adding the `Technical reviewed` label to this issue.
