### ISSUE TITLE
Config examples for Social Media Login feature (MSSEC14)

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#637]
Add config examples to https://openliberty.io/docs/ref/feature/#socialLogin-1.0.html showing how to configure Google login (see https://openliberty.io/blog/2019/08/29/securing-microservices-social-login-jwt.html); also how to configure single- and multiple-provider protected endpoints (see https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_sec_social_form.html). Show good examples for social logins listed in here https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_sociallogin.html Doesn't exist yet but there will be a guide on how to use Social Media login with your app (see https://github.com/OpenLiberty/guides-common/issues/167). Also provide config examples of authentication filters (see https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_auth_filter.html and https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_json.html)

**Comment by brutif** [comment]
Hi @dannemano sorry for the long delay in responding to your question.  The reason a new jwt is created is most social media providers don't issue one (Google is the exception).  Also social supports letting users choose between >1 provider, so creating a new jwt can consolidate that, simplifying things for consumers downstream.

**Comment by lauracowen** [comment]
Taken from #569 (which I accidentally opened as a dupe):
>@brutif 's blog post about security features in Liberty includes an example Social Media Login feature configuration that we could use in the generated docs.

>Bruce suggested that we should also have one showing how to configure having a 'chooser' function which lets the app user pick a provider before sending them off to authenticate.

**Comment by alohr51** [comment]
Is this something that would be done soon? I could really use some examples on setting up social login for OL. What would help me the most is an example that uses GitHub social login, but doesn't lock down the whole app and only a part of the app (by API endpoint)

I found some [KC docs for social login](https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/twlp_sec_sociallogin.html#twlp_sec_sociallogin__github) but they didn't help me much with the implementation. 

I also found the [gameon example that uses github auth](https://github.com/gameontext/gameon-auth/tree/master/auth-app/src/main/java/org/gameontext/auth/github) which is a couple years old, but it doesn't seem to use social login feature which I would assume would be the better way to do it.

**Comment by brutif** [comment]
@alohr51 Not sure how soon this will get done, I'll contact you with some examples.

**Comment by dannemano** [comment]
> Also social supports letting users choose between >1 provider, so creating a new jwt can consolidate that, simplifying things for consumers downstream.

This is a  good point, but in our case we use Azure AD as a identity provider, and all services in the backend authenticate and authorize using OIDC ID tokens.

So the social login together with Azure AD works flawlessly (I am seriously impressed!), but it would be so helpful to actually get hold on the ID and access tokens that Open Liberty retrieves.

Here is my config to make it clearer:

  <oidcLogin id="azurelogin"
                authFilterRef="authfilter"
                clientId="xxx"
                clientSecret='xxx'
                discoveryEndpoint='https://login.microsoftonline.com/xxx/v2.0/.well-known/openid-configuration'
                scope="openid profile email"
                userNameAttribute="email"
                isClientSideRedirectSupported="false"
                sslRef="socialloginssl"
                groupNameAttribute="groups"/>

Then I do a group mapping:
<webApplication id="app" location="app.war" name="security" type="war">
        <application-bnd>
            <security-role id="mapping1" name="MY_APPLICATION_ROLE">
                <group name="5d1c9084-de66-4d73-9b63-e7b4fc23d624" access-id="group:https://login.microsoftonline.com/61f3f299-ee82-4983-b711-f764ff4c40a1/v2.0/5d1c9084-de66-4d73-9b63-e7b4fc23d624"/>
            </security-role>
        </application-bnd>
    </webApplication>

**Comment by brutif** [comment]
@dannemano Thanks for explaining, I'm glad to hear it works!  I think we might have what you want.  I'll take a to-do to add it to the blog.  The UserProfileManager and UserProfile api's should give you access to the tokens. 

https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfile.html

https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.javadoc.liberty.doc/com.ibm.websphere.appserver.api.social_1.0-javadoc/com/ibm/websphere/security/social/UserProfileManager.html

**Comment by dannemano** [comment]
Those methods look helpful. I will try them out.

Thanks a lot and I will be waiting for the blog post :-)

**Comment by lauracowen** [comment]
FYI, there's also a guide on the prioritised backlog: https://github.com/OpenLiberty/guides-common/issues/167 (don't know when but the list shows the order in which the proposed/planned guides will be addressed).

**Comment by dannemano** [comment]
Just tried:
`UserProfile userProfile = UserProfileManager.getUserProfile();`
and it works as expected with all tokens I want present, so great advice @brutif!

A follow-up question though, I guess Open Liberty does not use the refresh token to automatically refresh the access and id tokens returned by `UserProfile`. Is there any way to trigger a refresh?

I understand this is not necessary for the logged in user, as the LPTA-cookie holds state for SSO to OpenLiberty, but when using the access token to call downstream services it will be necessary to sometimes get a new access token for the already signed in user.

**Comment by brutif** [comment]
@dannemano correct, there's no built in way today to use a refresh token to get a new id token.   However that's something we'd like to add in the future. If you'd care to open an enhancement request at https://developer.ibm.com/wasdev/help/submit-rfe/  , that will help get it prioritized.  The more people that vote for it, the sooner it's likely to get done.

**Comment by dannemano** [comment]
Thanks for the info! Sure, I will look into creating a RFE.

**Comment by lauracowen** [comment]
https://www.openliberty.io/docs/ref/feature/#socialLogin-1.0.html

**Comment by brutif** [comment]
Thanks @lauracowen
