### ISSUE TITLE
Liberty Tools docs for GA

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6403]
This is an umbrella issue to track any doc work for the Liberty Tools GA release.

GA DATE: June 23

The following tasks must be completed before GA:

- [x] update/remove all references to "Early release" in the [Liberty Tools overview doc](https://openliberty.io/docs/latest/develop-liberty-tools.html) and GH docs for each IDE
   - check minimum maven/gradle requirements- per slack conv, recommend always using latest
   - check EE and MP support levels
- [x] Update Eclipse docs to use the same basic format as the other 2 IDEs, where appropriate
- [x] review all messages and UI strings as they become available
- [x] ~~document lack of multi-module support in VSC and IntelliJ- in both docs and possibly as contextual help~~ not necessary in overview

**Comment by dmuelle** [comment]
slack conversation re GA items: https://ibm-cloud.slack.com/archives/C0305UUJMCZ/p1685981712224619

**Comment by dmuelle** [comment]
reviewed message strings for IntelliJ and VS Code

- https://github.com/OpenLiberty/liberty-tools-intellij/pull/437
- https://github.com/OpenLiberty/liberty-tools-vscode/pull/263

**Comment by dmuelle** [comment]
reviewed draft of Eclipse messages via slack

**Comment by scottkurz** [comment]
> Liberty Tools automatically detect any projects that specify the Liberty Maven plug-in or the Liberty Gradle plug-in in the project pom.xml or build.gradle file. 

This isn't really how it works in Liberty Tools Eclipse.   I think it'd be better to do a vague "Liberty Tools detect Liberty Maven or Gradle projects....".

**Comment by yeekangc** [comment]
LGTM.  Created #6721 with minor edits.  And, we can adjust what @scottkurz called out too.  Thanks!

**Comment by dmuelle** [comment]
Thanks @yeekangc @scottkurz. I merged YKs PR and made Scott's suggested edit in #6725

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this topic is ready for peer review

**Comment by ramkumar-k-9286** [comment]
LGTM. Adding the `Peer Reviewed` label.

Regards,
Ramkumar

**Comment by cherylking** [comment]
LGTM

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 23.0.0.6
