### ISSUE TITLE
 How to determine if Liberty is using a specific feature

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6407]
We need to add some information about how to determine what features a Liberty server is running, particularly so it's clear whether user is impacted by CVEs

Add a section to the[ Features overview](https://openliberty.io/docs/latest/reference/feature/feature-overview.html#_zero_migration_architecture), just before the "Zero Migration" section, then link to it from [the CVE page](https://openliberty.io/docs/latest/security-vulnerabilities.html). The content of this section should be the information in the following technote, revised per our content guidleines:

[How to determine if Liberty is using a specific feature](https://www.ibm.com/support/pages/node/6553910)

The update on the CVE page should be just before the table and should explain that some features enable other features by default, so it's not always obvious which features are running on a server.  However, you can determine which features are active on your server by reviewing log messages at startup. For more information, see (new section).

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Made the suggested corrections. Added the same information to the CVE page, instead of providing a link.

Draft links: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/feature-overview.html#conv

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 

- On the features overview page, move the new content to be at the end of the "Using Features" section
- on the CVE page replace the current text with the following statement:

> The Common Vulnerabilities and Exposures (CVE) system is a reference of publicly known network vulnerabilities that is maintained by the US National Institute of Standards and Technology (NIST). The CVE list catalogs known cybersecurity vulnerabilities. 
> 
> The following table lists the CVEs that affect Open Liberty, ordered by the release in which they were fixed. The table also includes the Liberty features that are affected by each CVE.  You can determine whether your Liberty configuration might be affected by a CVE by reviewing the features that are installed and running on your server. Occasionally, Liberty features that are not specified in the `server.xml` file are enabled automatically by other features. To confirm whether a particular feature is enabled in a Liberty server, inspect the `CWWKF0012I` message in the `console.log`, `messages.log`, or trace log files from the Liberty server. This message provides a comprehensive list of all the features that are installed and running on the Liberty server.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the suggested corrections.

**Draft links:** 

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/feature-overview.html#conv

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
in both docs- trace log ---> `trace.log`

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the suggested corrections.( `trace.log`)

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/feature-overview.html#conv

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
I think we should add the warning message example to the CVE page and let SMEs decide whether or not to keep it

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Made the suggested correction. Added the warning message example to the CVE page.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/feature-overview.html#conv

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
reading this, I think "installed" should be in quotes for readability, and also a slight edit for concison.

> The CWWKF0012I message uses the word "installed", but it lists features that are both installed and running on the Liberty server.

otherwise LGTM

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle

Suggested corrections are done.
Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/feature-overview.html#conv

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, please open a PR to staging when you have a chance
