### ISSUE TITLE
remove stray dashes in codeblock

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6430]
on the[ Validate MicroProfile JWT claims with the user registry](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpJwt-2.0.html#_validate_microprofile_jwt_claims_with_the_user_registry) example on the MP JWT feature page, the codeblock contains extra dashes that should be removed.

**Comment by hiltoncv** [comment]
This issue is fixed via #3345. 
Updates are available at https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpJwt-2.0.html#_validate_microprofile_jwt_claims_with_the_user_registry

**Comment by hiltoncv** [comment]
The issue is a duplicate of #3345.
