### ISSUE TITLE
Revert back to signature verification using openssl

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/docs#6453]
Because of the issues we discovered with the "cosign" verification tool - We are reverting back to the previous method of verification of our files on DHE and fix-central...

Current directions [here](https://openliberty.io/docs/latest/verifying-package-signatures.html)

example command:

`openssl dgst -sha256 -verify OpenLiberty_02-13-2023.pem -signature openliberty-kernel-23.0.0.3.zip.sig openliberty-kernel-23.0.0.3.zip`

**Comment by cbridgha** [comment]
For open liberty docs we are also using a public key named: [OpenLiberty_02-13-2023.pem](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/OpenLiberty_02-13-2023.pem) (WL files will remain using [WebSphereLiberty_02-13-2023.pem](https://public.dhe.ibm.com/ibmdl/export/pub/software/openliberty/sign/public_keys/WebSphereLiberty_02-13-2023.pem)

AND we are reverting our signature files back to a plain *.sig file.

**Comment by cbridgha** [comment]
Overall tracking defect: https://github.ibm.com/websphere/WS-CD-Open/issues/28984

**Comment by kinueng** [comment]
openliberty.io issue is here https://github.com/OpenLiberty/openliberty.io/issues/3089

**Comment by dmuelle** [comment]
These changes are now delivered to production, as well as vNext for future releases. Corresponding changes on the WebSphere Liberty side are also complete. Closing as completed.
