### ISSUE TITLE
Doc new features

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#649]
Doc with short intro pointing to OL blog homepage?

Could target relevant post for each month but that would require dynamic or manual update

Possibly includes
- new features
- known issues
- bug fixes

**Comment by Rwalls1** [comment]
// Module included in the following assemblies:
//
// <List assemblies here, each on a new line>

[id="new-and-changed-features{context}"]

= New and changed features 

The latest features for Open Liberty provide innovative ways to simplify and modernize applications.

For detailed information about the latest features, see https://openliberty.io/blog/.

**Comment by Rwalls1** [comment]
* New and changed features 

The latest features for Open Liberty provide innovative ways to simplify and modernize applications.

For detailed information about the latest features, see https://openliberty.io/blog/.

**Comment by Rwalls1** [comment]
# New and changed features
The latest features for Open Liberty provide innovative ways to simplify and modernize applications.

For detailed information about the latest features, see https://openliberty.io/blog/.

**Comment by Charlotte-Holt** [comment]
Draft of this is in GitHub at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/new-and-changed-features.adoc.

**Comment by chirp1** [comment]
Hi Richard, as we discussed, instead of giving a list of specific new features, which we would continually need to be updated, give an intro and then the link to the blog. Additionally, point them to the other docs and mention that they can access the guides, the reference topics and the conceptual topics here: https://openliberty.io/docs/

**Comment by chirp1** [comment]
Hi Richard, Here are my suggested edits:

Change "The latest features for Open Liberty are featured in the Open Liberty blog." to "For information about the latest Open Liberty features, see the Open Liberty blog. ".

For additional information related to the latest features, see the Open Liberty docs. to "For additional information about the latest features, see the Open Liberty docs. ".

**Comment by Rwalls1** [comment]
@lauracowen @cbridgha Please review: https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/new-features.adoc

**Comment by chirp1** [comment]
The update look good to me.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681351/Documentation_for_OL_9.30.2019.pdf)
