### ISSUE TITLE
server package command documentation lacking

### ISSUE THREAD

**Issue by cherylking** [OpenLiberty/docs#650]
The documentation here https://openliberty.io/docs/ref/command/#server-package.html is missing the server-root option. It is also not accurate for the archive option. It implies that only zip and jar are valid archives, but tar and tar.gz are also supported. Finally, the include options do not really make it clear that "minify,runnable" and "all,runnable" are valid. Here is what the command line help says for the `server package` command:

<img width="562" alt="Screen Shot 2019-09-20 at 1 52 44 PM" src="https://user-images.githubusercontent.com/29436451/65351779-914c4d00-dbae-11e9-8fa4-0ddc974dcf52.png">

**Comment by Charlotte-Holt** [comment]
@cherylking @cbridgha - Thanks for pointing these issues out. I added the `--server-root` option to the `server package` command documentation. I also added the sentence `ZIP, JAR, TAR, and TAR GZ are all valid archive file options.` to the `--archive` option:

- https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-package.html

Is there anything additional that needs to be included for these two options? 

In regard to the `minify,runnable` and `all, runnable`, I did notice that there's a usage example that shows the `--include=minify,runnable` option, but should this be made clearer? I could add a sentence to the `--include=runnable` option in the table that it can be used with `minify` or `all`.

**Comment by cherylking** [comment]
@Charlotte-Holt I think adding a sentence to the `--include=runnable` option about `minify` and `all` would be a good idea. Also, it would be nice if at least one example showed the TAR or TAR GZ archive file option.

**Comment by Charlotte-Holt** [comment]
@cbridgha @cherylking I added a bit to the `--include=runnable` option about `minify` and `all`, and I added an example with a TAR file archive. Please review and let me know if further updates are needed: https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-package.html.

**Comment by cherylking** [comment]
@Charlotte-Holt Looks good!

**Comment by cbridgha** [comment]
Agreed much better - thanks for the changes!

**Comment by Charlotte-Holt** [comment]
This is live at https://openliberty.io/docs/ref/command/#server-package.html. Closing this issue.
