### ISSUE TITLE
Debugging doc

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#652]
Pull together debugging information for use in RHR doc. Only information that I found in the current OL doc about debug capability is in https://openliberty.io/docs/ref/general/#runnablejarfiles.html.

**Comment by chirp1** [comment]
Note- checked with David: There is no specific“debugging” doc , but there is a debugging assembly, which pulls in tracing requests and enabling heathchecks topics

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue.

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681354/Documentation_for_OL_9.30.2019.pdf)
