### ISSUE TITLE
Example applications (list of guides)

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#653]
Create a topic with introductory paragraph and then point to these guides: 
3.1 - REST API Level 0 (not an entirely direct map) - Creating a RESTful web service: https://openliberty.io/guides/rest-intro.html
3.2 - Externalised configuration - 3 x MicroProfile Config-related guides (with and without K8s): https://openliberty.io/guides/?search=microprofile%20config
3.3 - Relational database backend - JPA intro: https://openliberty.io/guides/jpa-intro.html
3.4 - Health check - 2 x MicroProfile Health Check guides (with and without K8s): https://openliberty.io/guides/?search=health
3.5 - Circuit breaker - MicroProfile Fault Tolerance circuit breaker interactive guide: https://openliberty.io/guides/circuit-breaker.html
3.6 - Secured app - we have a couple of security-related apps but maybe not exactly the same aspects - front-end web app security: https://openliberty.io/guides/security-intro.html and backend JWT security: https://openliberty.io/guides/microprofile-jwt.html
3.7 - Caching - we have an HTTP session caching guide (?): https://openliberty.io/guides/sessions.html

**Comment by lauracowen** [comment]
I think each guide needs to have a brief summary of what it shows (eg the abstract from the guide that's printed on the OL.io website). A list alone doesn't give enough context about why the reader should care about looking at a given guide.

**Comment by lauracowen** [comment]
No longer required.
