### ISSUE TITLE
Developing and deploying apps

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#655]
Write an introductory paragraph about developing and deploying applications, and then point to these guides:
-  Packaging and deploying an app to OL: https://openliberty.io/guides/getting-started.html
- Deploying to OpenShift: https://openliberty.io/guides/cloud-openshift.html#building-and-containerizing-the-microservices

**Comment by Charlotte-Holt** [comment]
@lauracowen @cbridgha As Chuck mentioned in the Slack channel, I think that this issue may be redundant (see issues #651 and #654). I will confirm tomorrow AM on the call.
