### ISSUE TITLE
Maven plug-in doc

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#656]
Needs intro/ abstract?

Simple project: https://openliberty.io/guides/maven-intro.html
Multi-module app: https://openliberty.io/guides/maven-multimodules.html

**Comment by dmuelle** [comment]
## Using the Open Liberty Maven plugin

Open Liberty provides a Maven plugin to simplify and manage build processes.

Once you have defined the details and dependencies of a project, Maven automatically downloads and installs all of the dependencies. It also runs automated tests on an application after building it. If the tests don’t pass after you’ve made a change to the application, the build fails and you know that you need to fix your code.

To learn how to configure a simple web servlet application using Maven and the Liberty Maven plugin, see the Open Liberty guide to [Building a web application with Maven](https://openliberty.io/guides/maven-intro.html).

Java EE applications consist of multiple modules that work together as one entity. To learn how to build an application with multiple modules by using Maven and Open Liberty, see the Open Liberty guide to [Creating a multi-module application](https://openliberty.io/guides/maven-multimodules.html).

**Comment by dmuelle** [comment]
Running draft at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/using-the-maven-plugin.adoc

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681371/Documentation_for_OL_9.30.2019.pdf)
