### ISSUE TITLE
Update transaction service topic

### ISSUE THREAD

**Issue by frowe** [OpenLiberty/docs#6560]
Document https://openliberty.io/docs/latest/transaction-service.html states:
>If you store transaction logs in an RDBMS, each server must have its own tables. You can specify a unique table suffix by using the transactionLogDBTableSuffix attribute for the transaction element. The value for this attribute is a string that is **post-pended** to the table name to make it unique to the server where the table is hosted. In the previous example, MyServer1 is added as a suffix to any table names that are created for this server in an RDBMS.

Is post-pended even a word?  Shouldn't we use the more understandable and translatable "appended"?

**Comment by ramkumar-k-9286** [comment]
Hi Fred

Made the suggested corrections:

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/transaction-service.html

Regards,
Ramkumar.

CC @dmuelle

**Comment by frowe** [comment]
Looks good.

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Staging link:
https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/transaction-service.html

Please verify the staging site.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
@ramkumar-k-9286 LGTM, you can PR staging to vNext when you get a chance

**Comment by dmuelle** [comment]
content is on vNext and will publish with 23.0.0.4- closing as completed
