### ISSUE TITLE
How to restrict OpenIdConnect client to one application 

### ISSUE THREAD

**Issue by hesller** [OpenLiberty/docs#6592]
Hi everyone,

This is more a question than an issue.
At local workspace we have to application running under same server.xml. Lets call it application A, and application B.

openIdConnectClint should SSO for the application A. This is working like a charm. No issues here.

At certain point, application A makes a call to application B. Now it seems application B is triggering SSO, which should not happen. It is just a REST call.

Any ideas how to proceed here? I would like the configuration for openIdConnectClient be restricted to application A only.

Here is the response I get from application B.
```
com.fasterxml.jackson.core.JsonParseException: Unexpected character ('<' (code 60)): expected a valid value (JSON String, Number, Array, Object or token 'null', 'true' or 'false')
 at [Source: (String)"<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<script type="text/javascript" language="javascript">var loc=window.location.href;document.cookie="WASReqURLOidcn370137253="+loc+"; path=/;"</script><script type="text/javascript" language="javascript">window.location.replace("https://preprod.login.w3.ibm.com/v1.0/endpoint/default/authorize?response_type=code&client_id=ZjVjZDBiZDAtYzcyMS00&state=001682205715498psNRokdjt&redirect_uri=https%3A%2F%2Flocalhost%3A9444%2FCreateCMR%2Foidcclient%2Fred"[truncated 107 chars]; line: 1, column: 2]
```

**Comment by ayoho** [comment]
Hi, @hesller. I believe what you are looking for is an authentication filter. You can read more about auth filters here:
- https://openliberty.io/docs/latest/reference/feature/openidConnectClient-1.0.html
- https://openliberty.io/docs/latest/authentication-filters.html

In a nutshell, you need to configure an auth filter that matches all requests coming to application A. You would then add an `authFilterRef` attribute to your `<openidConnectClient>` configuration to point to that authentication filter.

**Comment by dmuelle** [comment]
closing as there is no doc work associated. Thanks
