### ISSUE TITLE
Configuring an application

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#660]
Create an introductory paragraph OL server configuration overview, which introduces the Open Liberty config elements that are used with the features in the server configuration: https://openliberty.io/docs/ref/config/

**Comment by Charlotte-Holt** [comment]
@lauracowen @cbridgha Here's what I currently have for the server configuration doc. Let me know what changes may need to be made:

= Server configuration

The Open Liberty server configuration includes a `server.xml` file and a set of optional files. The `server.xml` file is mandatory and must be in XML. Use the `server.xml` file to configure the features that your application needs to run. For more information about adding features to your server configuration, see the link:https://openliberty.io/docs/ref/feature/[Feature overview].

The following example shows what a default `server.xml` file might look like:

[source,xml]
----
<server description="new server">
    <featureManager>
        <feature>jsp-2.3</feature>
    </featureManager>
    <httpEndpoint id="defaultHttpEndpoint"
                  httpPort="9080"
                  httpsPort="9443" />
    <applicationManager autoExpand="true"/>
</server>
----

This example file configures the server to support the link:https://openliberty.io/docs/ref/feature/#jsp-2.3.html[JavaServer Pages 2.3] feature, listens to incoming traffic to localhost on port `9080`, and automatically expands WAR files when they are deployed.

Open Liberty server configuration files are processed in the following order:

. `server.env` file - The `server.env` files are optional. When present, they specify environment variables that are primarily used to influence the behavior of the `bin/server` script.
. `jvm.options` file - The `jvm.options` files are optional. When present, they determine what options to use when the Open Liberty JVM starts.
. `bootstrap.properties` file - The `bootstrap.properties` file is optional. When present, it provides configuration information for the earliest stages of the server start.
. `server.xml` file - While the other files are optional, the `server.xml` file is required. In this file, `server` is the root element, and any unknown elements or attributes are ignored.

For more information about these files or configuring an Open Liberty server, see the link:https://openliberty.io/docs/ref/config/[Server configuration overview].

.Additional resources

* link:https://openliberty.io/docs/ref/config/[Open Liberty server configuration overview]
* link:https://openliberty.io/docs/ref/feature/[Open Liberty feature overview]

**Comment by cbridgha** [comment]
This is good overall , I may tweak the intro sentence to not mention the XML format - I think that is implied, and this detail will be read if they follow the link.
Something like: "The Open Liberty server configuration includes a mandatory server.xml file and a set of optional files. Use the..."

**Comment by chirp1** [comment]
Hi Charlotte- nice job!

Here are my comments:
Change "includes a server.xml file " to "includes a required server.xml file ".
Delete "The server.xml file is mandatory and must be in XML.".

Move "For more information about adding features to your server configuration, see the Feature overview. " down a line so that it is not in the opening paragraph.

For the four configuration files listed in order, make the list more readable. Here are a few options:

- Use a table instead of a list, with each file in a separate row.
- If you continue to use a list, change the numbered list to an unordered list. Make, for example, "server.env file" bold, and then use a colon instead of a dash.

In the list, make these additional changes:
Change "server.env file" to "server.env files" (add an s)
Change "jvm.options file" to "jvm.options files" (add an s)
Change "While the other files are optional, the server.xml file " to "The server.xml file ".

For "Additional resources", both the links are already provided in the body of the topic. So, either remove "Additional resources" and the links under it or remove "For more information about adding features to your server configuration, see the Feature overview. " and "For more information about adding features to your server configuration, see the Feature overview." Since I think that the two sentences are helpful, I would likely remove the "Additional resources" section.

**Comment by Charlotte-Holt** [comment]
@chirp1 @cbridgha I'll incorporate your suggestions and post a link here when I get this uploaded into GitHub for review. Thank you!

**Comment by chirp1** [comment]
The updates looks OK.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681341/Documentation_for_OL_9.30.2019.pdf)
