### ISSUE TITLE
The server version command does not create a server.

### ISSUE THREAD

**Issue by jimblye** [OpenLiberty/docs#6618]
**This page**
https://openliberty.io/docs/latest/reference/command/server-version.html

**This part**

serverName

The name of the server to run the command against. If no server is specified, a server called defaultServer is automatically created to run the command against.

**The problem**
Just wrong.  No we do not create a server when you do not specify a server name on the _server version_ command.

**Proposed fix**

serverName

The name of the server to run the command against. The server might influence the output of the _server version serverName_ command if the server has a server.env configuration file which specifies a JAVA_HOME variable. 

If no server name is specified, the server name is assumed to be _defaultServer_.   If defaultServer does not exist, the command is not influenced by any server and only reflects the version of the liberty installation.

**Comment by dmuelle** [comment]
Thanks for catching this @jimblye - I'll get it updated. Question:

> The server might influence the output of the server version serverName command if the server has a server.env configuration file which specifies a JAVA_HOME variable.

Does that mean that the command returns the version of Java for the location that is specified by the JAVA_HOME variable in server env, if such a variable exists on the specified server?

**Comment by dmuelle** [comment]
Hi Jim, I've updated the page per your suggestion, with some minor edits to the text. When you have a chance, would you take a look and let me know if I've got it right?

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-version.html

One thing I might need to get sorted is JVM vs JRE with regard to JAVA_HOME. This page talks about JAVA_HOME in the context of JRE, but our [Default Environment variables](https://openliberty.io/docs/latest/reference/default-environment-variables.html) topic defines JAVA_HOME as `Indicates which Java Virtual Machine (JVM) to use`.Are these definitions in conflict? Do one or both need an edit or clarification?

**Comment by jimblye** [comment]
I think the edits are fine.  It's probably best to consistently use JRE on this page.   
Others define JAVA_HOME in terms of JRE or JDK ( https://www.theserverside.com/definition/JAVA_HOME ), but honestly I don't think it will confuse anyone if you leave the JAVA_HOME variable definition as is.    You could change it if you want to be consistent.

**Comment by dmuelle** [comment]
Thanks Jim, I've updated both pages to consistently talk about JAVA_HOME in terms of JRE.

**Comment by dmuelle** [comment]
changes are on vNExt and will publish with 23.0.0.5
