### ISSUE TITLE
Replace MicroShed testing mentions with TestContainers

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#6655]
MicroShed testing hasn't been updated and doesn't work with later Jakarta versions so we need to remove references of it from the docs. We should replace with TestContainers (which MIcroshed was based on anyway). I know this topic mentions both so it'll need a little tweaking to just refer to TestContainers:

https://openliberty.io/docs/latest/integration-testing.html

There is a guide on the backlog to replace the MicroShed guide but it's not ready yet. If there are links to the MIcroShed guide we should probably just remove them for now? (I don't know when the new, replacement guide will be ready.)

/cc @yeekangc

**Comment by ramkumar-k-9286** [comment]
Hi @lauracowen @yeekangc 

This [Integration testing](https://openliberty.io/docs/latest/integration-testing.html) document has many MicroShed-related mentions and a code block with similar information.

Could you suggest a developer we could contact for clarification with the code block and other mentions?

Regards,
Ramkumar

**Comment by lauracowen** [comment]
@ramkumar-k-9286 Hi - try @KyleAure

**Comment by KyleAure** [comment]
Thanks for including me in this conversation. 

Yes, the developer that had been pushing for Microshed Testing left IBM a few years ago so the project is dead unless it gets picked up by someone else in the Open Source community. 

Microshed testing does a lot of background configuration and abstraction which means switching our [Microshed Guide](https://github.com/OpenLiberty/guide-microshed-testing) to use TestContainers natively would basically defeat the purpose of the guide.  I vote we just deprecate this guide, is there a way to do that? 

As for the use of Microshed in our [Liberty Docs](https://openliberty.io/docs/latest/integration-testing.html) I agree this can be refactored to use TestContainers instead of Microshed. 
Do you want me to open a PR for that?

**Comment by lauracowen** [comment]
@KyleAure The Microshed guide won't be updated; there's a [new TestContainers guide](https://github.com/OpenLiberty/guides-common/issues/813) currently being worked on. You should probably be in touch with @gkwan-ibm about it.

**Comment by gkwan-ibm** [comment]
hi @KyleAure, the new TestContainers guide was drafted. May I ask you to do a SME review after our internal review?

**Comment by KyleAure** [comment]
Yes, I can review it, just let me know when it is ready :)

**Comment by ramkumar-k-9286** [comment]
@lauracowen @KyleAure 

Hi Lauren, Kyle 

Made some basic corrections to the existing page ( Example code block and explanation for the same is pending).

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

The content available in the blocks is basically the content that will be replaced. **(In case you wanted to see the previous content)**

@KyleAure I Would need your help with replacing the existing example ( the code block contains an example for MicroShed and would need to be replaced). Could you help me with an example for TestContainers?

Regards,
Ramkumar

CC @dmuelle

**Comment by KyleAure** [comment]
@ramkumar-k-9286 
## Comments on the draft
- Inconsistent capitalization.  Should use `Testcontainers` not `TestContainers`

## Example code

I wrote a test application that mimics the same functionality as what we get from Microshed Testing using just Testcontainers here:

https://github.com/KyleAure/testcontainers-liberty/blob/7ce621264b661a88052f672139dd27ab4a48914d/app/src/test/java/testcontainers/liberty/ServiceTest.java#L23-L86

**Comment by ramkumar-k-9286** [comment]
@KyleAure

Hi  Kyle

Made corrections to the page. Added the new code block that you provided.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

The content available in the blocks is basically the content that will be replaced. (In case you wanted to see the previous content)

Please review the same, and let me know if I need to make corrections.

Regards,
Ramkumar

CC @dmuelle

**Comment by lauracowen** [comment]
Nice. I've had a quick read through and a couple of comments:

* The opening section (four paragraphs) seems like it says the same thing a few times and could be more concise maybe? For example, the last para doesn't really add much.
* There's a link to Jakarta EE but not to MicroProfile - I see that that was the case before but I'm not sure why that would be. Could you MicroProfile link to microprofile.io, pls?

In general, though, it looks good I think. And it's always nice to have up-to-date code examples too :)

**Comment by KyleAure** [comment]
@ramkumar-k-9286 

## Review Comments

###  Intro

Testcontainers can be used as a singular to refer to the singular project.
```diff
- Testcontainers are used to spin up a Docker container
+ Testcontainers is used to start a Docker container
```

### Codeblock

Grammar
```diff
- // Setup RestAssured query our service
+ // Setup RestAssured to query our service
```

Left over from testing, not needed
```diff
- Jsonb jsonb = JsonbBuilder.create();
```

Copy error
```diff
-             .jsonPath(x).getString("name");
+             .jsonPath().getString("name");
```
### Test elements

Suggestion: The section right after the code block should have a section title
```diff
+ === Test Elements
```

Semantics
```diff
- The `@Testcontainers` annotation indicates that this test class uses Docker containers for testing.
+ The `@Testcontainers` annotation is a custom Junit5 extension that controls the lifecycle of the Docker container (create, run, stop, and delete) within the scope of this test class.
```

Consistency
```diff
- The liberty field is annotated with `@Container` and creates a Docker container by
+ The `@Container` annotation marks the field that constructs the Docker container by
```

Formatting / Consistency
```diff
- In the @BeforeAll annotated method `getServiceURL(), the base URL
+ The `@BeforeAll` annotated marks the method that creates the base URL
```

Formatting / Consistency
```diff
- The `testAddPerson()` method is annotated with `@Test` and runs a series of tests on the service.
+ The `@Test ` annotated marks the method that runs a series of tests on the application service.
```

### Test logic

Suggestion: After describing the test elements mark the next section as a description
```diff
+ === Test Logic
```

Consistency
```diff
- The response is validated to ensure a successful status code (200).
+ The response is validated to ensure a successful status code `(200)`.
```

**Comment by ramkumar-k-9286** [comment]
@lauracowen @KyleAure

Hi Laura, Kyle

Made suggested corrections to the page. 

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

Please review the same, and add the `Technical Reviewed` label if you are ok with the changes.

Please let me know if I need to make more corrections.

Regards,
Ramkumar

CC @dmuelle

**Comment by lauracowen** [comment]
Thanks for the changes. The first para looks a lot better.

Could you remove the See also section completely for now? We shouldn't link to the Microshed guide (it won't necessarily work and we've not otherwise mentioned Microshed in the topic now) and we don't have a replacement ready for it yet.

**Comment by ramkumar-k-9286** [comment]
@lauracowen 

Made suggested corrections to the page.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

Please review the same.

Please let me know if I need to make more corrections.

Regards,
Ramkumar

CC @dmuelle

**Comment by KyleAure** [comment]
👍🏼 Looks good to me

**Comment by dmuelle** [comment]
Looks good- two suggestions

similar to Laura's comment above, the first paragraph in the final section is really wordy and kind of says the same thing over and over again. I'd suggest revising to make it more concise.

Also replace:  RestAssured---> [REST Assured](https://rest-assured.io/)

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David

Made suggested corrections to the page. (Reworked on the suggested paragraph).
Also replaced: RestAssured---> [REST Assured](https://rest-assured.io/)

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

Please review the same. Please let me know if I need to make more corrections.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
I still think the first paragraph is the final section is talking a lot without saying much. Maybe something like

The Testcontainers framework empowers developers to create integration tests and deploy applications in diverse environments by using containers. It provides a comprehensive solution for creating and managing containers in a testing environment. Developed specifically for [MicroProfile](https://microprofile.io/) and [Jakarta EE](https://jakarta.ee/) developers, Testcontainers serves as a Java library that simplifies application testing in a production-like setting. It enables developers to achieve development and production parity by thoroughly testing their applications in a

--->

Testcontainers is a Java library that enables you to thoroughly test your [MicroProfile](https://microprofile.io/) and [Jakarta EE](https://jakarta.ee/) applications in a testing environment that closely resembles your production setup.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

Made suggested corrections to the page.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

Please review the same. Please let me know if I need to make more corrections.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
looks good- one more thing I just noticed:

> With Testcontainers, you can write an integration test.

Dont need this sentence because the section is called "Writing integration tests with the Testcontainers framework"

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

Made suggested corrections to the page. (Removed - With Testcontainers, you can write an integration test.)

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, thanks. Adding `Peer reviewed` label

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

Staging site link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/integration-testing.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 23.0.0.6
