### ISSUE TITLE
Add an explanation for specifying variables in Liberty config to Server config overview

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6720]
Document: Server configuration overview
http://openliberty.io/docs/latest/reference/config/server-configuration-overview.html

The page doesn't actually document how to reference variables, it just uses examples. We should add an explanation of the ${variable.name} syntax to the beginning of the Server Config overview, possibly just before the  [Variable substitution precedence](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#variable-substitution) section.

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David

Added an explanation of the ${variable.name} syntax to the beginning of the Server Config overview,  just before the [Variable substitution precedence](https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#variable-substitution) section.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html


Regards,
Ramkumar

**Comment by dmuelle** [comment]
the content LGTM- but it might be hard to find... I think you could add a heading "Configuration variable syntax" at the same level as "Variable substitution precedence", in the same location where you have the content now

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David,

Made the suggested correction. Added heading **Configuration variable syntax** at the same level as **Variable substitution precedence**.

Also, since **Variable substitution precedence** is part of the anchor list, added **Configuration variable syntax** to the list as well.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html

Please review the suggested changes.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
The heading looks good- reading again, I'd suggest slight edits to the first paragraph to remove passive voice and clarify the symbols:

In the Open Liberty server configuration files, variables are referenced by using the ${variable.name} syntax. The use of variables allows you to define reusable values that can be substituted with actual values at runtime. $ indicates the start of a variable reference. {} encloses the name of the variable.

--->

Variables define reusable values that are substituted with actual values at runtime. In Open Liberty server configuration files, you can reference variables by using the `${variable.name}` syntax. The dollar sign (`$`) indicates the start of a variable reference. Curly brackets (`{}`) encloses the name of the variable. 

then at the end of the section,

For more information about specifying variables, see _Variable substitution precedence_.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Made the suggested correction. 

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html

Please review the suggested changes.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
sorry, my suggestion had a typo:

Curly brackets ({}) encloses the name of the variable.
--->
Curly brackets ({}) enclose the name of the variable.

Otherwise LGTM and you can send to staging oncen that correction is made

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Made the suggested correction.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM thanks, you can send to staging when you're ready

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Please find below the staging site link for server-configuration-overview.html.

link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/server-configuration-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, files are on vNext, closing as completed
