### ISSUE TITLE
Should the dev mode doc url be renamed to dev-mode.html?

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/docs#6726]
When I click to the dev mode doc as the attached screenshot, I found the dev mode doc url is `https://openliberty.io/docs/latest/development-mode.html`. Should it be renamed to `dev-mode.html`?

![Screenshot 2023-06-16 at 10 39 21 AM](https://github.com/OpenLiberty/docs/assets/29576299/dbcedde0-7572-416d-9144-9892c498f1dd)

**Comment by gkwan-ibm** [comment]
and redirect development-mode.html to dev-mode.html (or keep both htmls), in case other docs, guides or users directly reference to development-mode.html

**Comment by dmuelle** [comment]
I think there was initially some discussion about whether to use "development mode" vs "dev mode" before the decision to use dev mode was settled. The file can now be updated to `dev-mode.adoc`. We can create a redirect in the playbook so that` /latest/development-mode.html = /latest/dev-mode.html`

**Comment by gkwan-ibm** [comment]
May I assume that the fix for the latest and future versions?
- `https://openliberty.io/docs/23.0.0.4/development-mode.html`
- `https://openliberty.io/docs/23.0.0.4/dev-mode.html -> 404`
- `https://openliberty.io/docs/latest/dev-mode.html`
- `https://openliberty.io/docs/latest/development-mode.html -> https://openliberty.io/docs/latest/dev-mode.html`
- `https://openliberty.io/docs/23.0.0.5/dev-mode.html -> ?`
  - pending on when this issue be fixed 
- `https://openliberty.io/docs/23.0.0.5/development-mode.html -> ?`
  - pending on when this issue be fixed 
- `https://openliberty.io/docs/23.0.0.6/dev-mode.html -> https://openliberty.io/docs/latest/dev-mode.html`
- `https://openliberty.io/docs/23.0.0.6/development-mode.html -> 404`

**Comment by dmuelle** [comment]
The redirect will only fix "latest" and future (23.0.0.7+) versions. 

Links to pre 23.0.0.7 versions that use `development-mode.html` will still work. The only problem would be if someone used the version picker to go from an earlier version to the current version or vice versa. I'll need to ask the site team if there is a workaround for that.

To manually deliver a new file, new TOC entry, and redirects to all 26 versions where the file exists would be nontrivial, possibly requiring ~ 80 individual PRs. We can discuss on the next site call to see what the options are.

**Comment by dmuelle** [comment]
response from @natalie-bernhard on website team:

> Hi David, is this filename change absolutely necessary? The way we know documents are the same across versions is by seeing that they have the same filename.
> 
> The UI is acting as expected for any undefined filename in a version. When the user switches from an older version to latest, it attempts to redirect the user to the file development-mode (retrieved from the previous URL), which is not found in the new version files, so the Document does not exist error occurs. When that error occurs, the logic checks if a link to the file in each version responds with a successful 200 code. However, since the redirect is there, the link exists and returns a 200 even though the file with that name doesn't exist for that version, which is why if you hover over the link matching the current version under Document does not exist, the link actually says development-mode.html, but the redirects handle the url once the link is clicked.
> 
> We could attempt to create a better way to check if the files exist, but this would not result in a successful linking between versions. This would require some source of external data, such as a JSON, to indicate aliases for files, which may be harder to maintain. I understand the motivation for wanting to change the filename, but from the perspective of handling the docs building and logic, the best thing would be to keep the filenames the same for now. If changing the filename is a necessity, let me know and I will look into further options. To be clear though, if we do go ahead with changing the filenames, a good portion of logic would need to be modified to handle it, and you likely would not be able to have differing filenames for at least a month, likely longer with the current resources available for the website.
> 
> We could exclude the current version of the docs when checking if the file exists in other versions, but this would then result in a blank Document does not exist error without alternate suggestions/links

**Comment by dmuelle** [comment]
I'm going to close this issue, since the benefit of the change is unlikely to justify the scope of work for the website team. Feel free to re-open it if you want to continue. We might revisit if this problem comes up more frequently in the future, but for now this is the only file where it has come up.
