### ISSUE TITLE
java17 and zOS

### ISSUE THREAD

**Issue by covener** [OpenLiberty/docs#6763]
Document: Java SE support
http://openliberty.io/docs/latest/java-se.html

We need to work in a way to exclude Java 17 on zOS from the above as it will be incompatible upon release. 

Unfortunately there is no notes column or existing concept of restrictions/minimums/footnotes so i don't have a recommend change or text.  CC @NottyCode for details.

**Comment by dmuelle** [comment]
We dont generally document z/OS on Open Liberty. I think we would just need to clarify this in the z/Os WL docs (per https://github.ibm.com/websphere/liberty-docs/issues/3553). What do you think @NottyCode ?

**Comment by NottyCode** [comment]
Open Liberty doesn't support z/OS which is why we don't support it. There is an upstream product that packages enhancements to enable Liberty to run on z/OS but it isn't part of Open Liberty project.
