### ISSUE TITLE
Clarify required InstantOn capabilities

### ISSUE THREAD

**Issue by kgibm** [OpenLiberty/docs#6766]
https://openliberty.io/docs/latest/instanton.html#linux-capabilities

The first paragraph writes that various capabilities are required for checkpoint and restore. However, the next paragraph that leads into the capabilities list only mentions checkpoint.

Proposed changes as [discussed internally](https://ibm-cloud.slack.com/archives/C03MR7EC3NG/p1688563605219509):

---

Unprivileged (non-root) users are supported by CRIU for checkpointing and restoring application processes. To checkpoint and restore, CRIU requires different [Linux capabilities](https://man7.org/linux/man-pages/man7/capabilities.7.html).

To perform an application process checkpoint, CRIU requires the following Linux capabilities:

- `CHECKPOINT_RESTORE` - This capability was added in Linux 5.9 to separate checkpoint/restore functions from the overloaded SYS_ADMIN capability.
- `SETPCAP` - Required for subsequent restore.
- `SYS_PTRACE` - A powerful capability needed by CRIU to be able to capture and record the full process state. This capability is necessary only when CRIU is checkpointing an application process.

To perform an application process restore, CRIU requires the following Linux capabilities:

- `CHECKPOINT_RESTORE` - This capability was added in Linux 5.9 to separate checkpoint/restore functions from the overloaded SYS_ADMIN capability.
- `SETPCAP` - Allows CRIU to drop capabilities from the restored application process. Because the CRIU binary is granted more capabilities, like `CHECKPOINT_RESTORE`, it needs `SETPCAP` so it can drop those capabilities from the final process that CRIU restored.

**Comment by dmuelle** [comment]
Hi @kgibm - I've updated the draft doc with the new Linux cap section:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html#prereq

Let me know if any further edits are needed. If not, you can sign off by adding the `Technical reviewed` label to this issue. Thanks!

**Comment by dmuelle** [comment]
content is on vNExt and will publish with 23.0.0.7. Closing as completed
