### ISSUE TITLE
The links in the OL operator doc are out-dated

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/docs#6769]
In the doc https://openliberty.io/docs/latest/open-liberty-operator.html, the following links are out-dated:

1. The Open Liberty Operator is based on the [Runtime Component Operator](https://operatorhub.io/operator/runtime-component-operator) -> Error
2. you can specify an [image stream](https://docs.openshift.com/container-platform/3.9/architecture/core_concepts/builds_and_image_streams.html#image-streams) -> points to 3.9 which is not the latest
3. You can [enable persistence for your application](https://github.com/application-stacks/runtime-component-operator/blob/main/doc/user-guide.adoc#persistence) by specifying... -> 404
4. You can [install the Open Liberty Operator from OperatorHub](https://operatorhub.io/operator/open-liberty) for use on Kubernetes or OpenShift. -> The doc has 0.7.0 that is not the latest

**Comment by gkwan-ibm** [comment]
cc @leochr ^ 
and for `#4`, I guess the doc https://operatorhub.io/operator/open-liberty is not maintained by ID. It still be beta and 0.7.0.

**Comment by ramkumar-k-9286** [comment]
@gkwan-ibm 

Hi Gilbert.

Needed some confirmation before I made the updates. 

Please confirm if I have figured out the correct URL. I will proceed to make the updates. 

---

1. The Open Liberty Operator is based on the [Runtime Component Operator](https://operatorhub.io/operator/runtime-component-operator) -> Error

- [ ] **Replacement:** The Open Liberty Operator is based on the [Runtime Component Operator](https://github.com/application-stacks/runtime-component-operator/blob/main/doc/user-guide-v1.adoc)

2. you can specify an [image stream](https://docs.openshift.com/container-platform/3.9/architecture/core_concepts/builds_and_image_streams.html#image-streams) -> points to 3.9 which is not the latest

- [ ] **Replacement:** For example, in the operator deployment file, you can specify an [image stream](https://docs.openshift.com/container-platform/4.13/openshift_images/image-streams-manage.html) in the `applicationImage` field.

3. You can [enable persistence for your application](https://github.com/application-stacks/runtime-component-operator/blob/main/doc/user-guide.adoc#persistence) by specifying... -> 404 - page not found

- [ ] **Replacement:** You can [enable persistence for your application](https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1.adoc#persist-resources) by specifying...

Additional -> For more information about gathering server memory dumps and server traces, see [Day-2 operations](https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide.adoc#day-2-operations). -> 404 - page not found

- [ ] **Replacement:** For more information about gathering server memory dumps and server traces, see [Day-2 operations](https://github.com/OpenLiberty/open-liberty-operator/blob/main/doc/user-guide-v1.adoc#day-2-operations).

4. You can [install the Open Liberty Operator from OperatorHub](https://operatorhub.io/operator/open-liberty) for use on Kubernetes or OpenShift. -> The doc has 0.7.0 that is not the latest

Awaiting response from Leo.

---

Regards,
Ramkumar.

**Comment by gkwan-ibm** [comment]
hi @leochr, would you verify instead of me?

**Comment by leochr** [comment]
@ramkumar-k-9286 The replacements look good.

Regarding the last item, please update the last paragraph with this instead:
You can install the Open Liberty Operator from the integrated OperatorHub on OpenShift. On other Kubernetes platforms, install the Open Liberty Operator using _kustomize_ or _kubectl_. The Open Liberty Operator [documentation](https://ibm.biz/olo-docs) provides details about Operator capabilities, installation, Custom Resource Definition (CRD) parameters and basic/advanced configurations.

Thank you

**Comment by ramkumar-k-9286** [comment]
@gkwan-ibm @leochr 

Hi Gilbert, Leo

Suggested changes have been made. 

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/open-liberty-operator.html

Please review the page when you have time.

Regards,
Ramkumar.

**Comment by gkwan-ibm** [comment]
the draft looks fine to me. Thanks

**Comment by dmuelle** [comment]
One suggestion- for 
you can specify an [image stream](https://docs.openshift.com/container-platform/4.13/openshift_images/image-streams-manage.html)...

instead of specifying 4.13 in the URL, use `latest` so we don't have to edit agin for future versions

https://docs.openshift.com/container-platform/latest/openshift_images/image-streams-manage.html

otherwise LGTM

**Comment by leochr** [comment]
Looks good to me. Thank you

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David

The suggested change has been made. (used `latest` so that edits to URL can be avoided for future versions).

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/open-liberty-operator.html

Please review the page when you have time.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM thanks, you can send to staging when you're ready

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

The staging site link for open-liberty-operator.html

link:
https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/open-liberty-operator.html

Please review the page when you have time.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM, files are on vNext, closing as completed
