### ISSUE TITLE
Documentation of MicroProfile Telemetry 1.1 

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/docs#6776]
Epic: https://github.com/OpenLiberty/open-liberty/issues/25187

Content: TBD

Currently targeting 230010-beta/ 230012 GA

**Comment by Yas-Franco** [comment]
Content is now in #7033 and #7054

**Comment by dmuelle** [comment]
Hi @yasmin-aumeeruddy - the updated draft for this feature is now ready for review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html

I made some changes to the overall structure to reduce repetition and make the page easier to navigate, but the information should be the same as the original PRs. If any further edits are needed, just let me know. When you're satisfied with the topic, you can add the `technical reviewed` label to sign off and the update will publish with 23.0.0.12. Thanks!

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this topic is ready for peer review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

A span represents a single operation in a request and contains a name, time-related data, log messages, and metadata to gather data about what occurs during a transaction.
-> ( Acrolinx - Too Complex)
A span represents a single operation in a request. It includes a name, time-related data, log messages, and metadata to collect information about what happens in a transaction.

---

[MicroProfile Telemetry](https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-telemetry-1.0/plan%E2%80%A8%E2%80%A822.0.0.10-bet) is based on the [OpenTelemetry project](https://opentelemetry.io/), **which is** a collection of open source vendor-independent tools, APIs, and SDKs for creating and managing trace data.
->
[MicroProfile Telemetry](https://projects.eclipse.org/projects/technology.microprofile/releases/microprofile-telemetry-1.0/plan%E2%80%A8%E2%80%A822.0.0.10-bet) is based on the [OpenTelemetry project](https://opentelemetry.io/), a collection of **open-source** vendor-independent tools, APIs, and SDKs for creating and managing trace data.

---

For information about migrating your applications from MicroProfile OpenTracing to MicroProfile Telemetry, see [Differences between MicroProfile Telemetry 1.0 and MicroProfile OpenTracing 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-50-60-diff.html#telemetry).
->
For **more** information about migrating your applications from MicroProfile OpenTracing to MicroProfile Telemetry, see [Differences between MicroProfile Telemetry 1.0 and MicroProfile OpenTracing 3.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-50-60-diff.html#telemetry).

---

For example, to use a Jaeger server, you might add configuration similar to the following example to your bootstrap.properties file:
->
For example, to use a Jaeger server, you might add **a** configuration similar to the following example to your bootstrap.properties file:

---
Enable MicroPRofile Telemetry, as described in [Configuring Open Liberty to use MicroProfile Telemetry](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#ol-config).
->
Enable **MicroProfile** Telemetry, as described in [Configuring Open Liberty to use MicroProfile Telemetry](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#ol-config).

---
[automatic instrumentation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#auto), which automatically
->
[Automatic Instrumentation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#auto), which automatically

[manual instrumentation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#manual), which allows you to
->
[Manual Instrumentation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#manual), which allows you to

[agent instrumentation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#agent), which automatically adds telemetry to
->
[Agent Instrumentation](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html#agent), which automatically adds telemetry to

---

If you set any properties by using environment variables, including the in the `server.env` file, the keys must be in uppercase and all punctuation must be replaced by an underscore. Values must be written normally.
->
If you set any properties by using environment variables, including **those** in the `server.env` file, the keys must be in uppercase and all punctuation must be replaced by an underscore. Values must be written normally.

---
<artifactId>opentelemetry-instrumentation-annotions</artifactId>
->
<artifactId>opentelemetry-instrumentation-annotations</artifactId>
(This is in a code block - annotations spell check)

**Comment by dmuelle** [comment]
Thanks @ramkumar-k-9286, all suggestions implemented, except "a configuration", as I think "configuration" is a collective noun in this context and doesn't need an article. It wouldn't necessarily be incorrect but seems awkward.

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html
