### ISSUE TITLE
JAWS, manual testing 23.0.0.7

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#6788]
JAWS, manual testing for sampling of topics, including the following ones. Ones that pass have a check mark next to them.

Testing includes 23.0.0.6 completed issues and various completed issues since 23.0.0.6

- Note: David did the accessibility scans.

- [x]  From issue 6769, reviewed [Open Liberty Operator](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/open-liberty-operator.html)
- [ ] From issue 6689, reviewed [Social Media login 1.0](https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/socialLogin-1.0.html#privatekeyjwt) and [OpenID Connect Client 1.0](https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/openidConnectClient-1.0.html#privatekey)
- Both have a single version, 1.0. The JAWS experience is different from the experience from someone who does not use JAWS. JAWS recognizes "1.0" as a button. When I click the B key, used to skip to buttons during JAWS testing,  to skip to buttons, the However, the button can't be clicked to take the user someplace. Hovering over or click "1.0" in non-JAWS does not detect a button. For features that have more than one version, say 1.0 and 2.0, both version would have a button for JAWS users and non-JAWS users. The user would click the version number to view the docs for that particular version. 
- [x] From issue #5983 for InstantOn, reviewed [Faster startup for containerized applications with Open Liberty InstantOn](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html)
- [x] From issue 6769, reviewed [Open Liberty Operator](https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/open-liberty-operator.html)

**Comment by dmuelle** [comment]
closing as completed
