### ISSUE TITLE
Logging topic

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#679]
This content is now broken out into its own topic, previously in the monitoring draft (#657)

**Comment by dmuelle** [comment]
Draft:

Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability.

The logging component is controlled through the server configuration. To configure the logging component in the `server.xml` file, use the `logging` element. It is also possible to configure logging by using `bootstrap.properties` and in some cases by using environment variables.

To learn more about Open Liberty's logging configuration, see example configurations and an index of configuration settings by source, see [Logging and tracing](https://www.openliberty.io/docs/ref/general/#logging.html).

To learn how to configure access log settings specifically for HTTP endpoints, and to see a list of log format options, see [HTTP access logging](https://www.openliberty.io/docs/ref/general/#access-logging.html).

.Additional resources
* [Open Liberty server configuration: Logging](https://openliberty.io/docs/ref/config/#logging.html)
* [Enabling distributed tracing in microservices](https://www.openliberty.io/guides/microprofile-opentracing.html)

**Comment by dmuelle** [comment]
@chirp1 updated Logging topic- this incorporates your edit suggestions from #657 

current running draft is at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/configuring-logs.adoc

**Comment by chirp1** [comment]
@Charlotte-Holt @dmuelle   Hi Charlotte/David, here are my suggested updates:

Change the title from "Configuring logging" to "Logging" or "Application logging", etc.

Change "Open Liberty has a unified logging component. It handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability." to "Open Liberty has a unified logging component that handles messages that are written by applications and the runtime, and provides First Failure Data Capture (FFDC) capability.".

Change "The following example uses the server.xml file to configure log files to be stored in JSON format: " to "The following example shows how to configure log files that are stored in JSON format:".

Change "It is also possible to configure logging by using" to "You can also configure logging by using".

Change "To learn more about Open Liberty’s logging configuration, see example configurations and a table of configuration settings by source, see Logging and tracing. " to "For more information about Open Liberty logging, see Logging and tracing. "

Change "To learn how to configure access log settings for HTTP endpoints, and to see a list of log format options, see HTTP access logging." to "For information about logging for HTTP endpoints,see HTTP access logging.".

**Comment by dmuelle** [comment]
@chirp1 I've made  these edits, updated doc is at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/blob/master/docs/modules/logging.adoc

**Comment by chirp1** [comment]
Change "when accessing" to "with".

Now that I see "For more information about logging and tracing, see Logging and tracing." and "For more information about logging for HTTP endpoints, see HTTP access logging." right next to the Additional resources, to me, I think that we should move these two links to "Additional resources' and eliminate the two sentences from the body of the text.

**Comment by dmuelle** [comment]
updated doc at https://github.ibm.com/was-liberty/openliberty-redhat-drafts/pull/10

@cbridgha you reviewed an earlier version of this doc, can you take a look at this update? `Logging` is now a separate topic for `monitoring`.

**Comment by chirp1** [comment]
The updates look OK.

**Comment by Charlotte-Holt** [comment]
Doc included in the attachment. Closing this issue. 

[Documentation_for_OL_9:30:2019.pdf](https://github.com/OpenLiberty/docs/files/3681374/Documentation_for_OL_9.30.2019.pdf)
