### ISSUE TITLE
ID: Using application context root for SSO LTPA/JWT cookie path 

### ISSUE THREAD

**Issue by utle** [OpenLiberty/docs#6793]
Today the SSO LTPA/JWT cookies always had the cookie path set to "/". 
This feature allows you to set the SSO LTPA/JWT cookie path to the application's context root. This allows different SSO LTPA/JWT tokens to be used for different applications.

**Comment by chirp1** [comment]
The epic is at https://github.com/OpenLiberty/open-liberty/issues/16235

**Comment by utle** [comment]
We decided just  auto generate of metatype doc is good enough.
