### ISSUE TITLE
Create landing pages for OL API/SPIs

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6802]
for 23008 need to add top-level landing pages for the new OL API/SPI sections. Content should just be short summary information for API and SPIs.

**Comment by dmuelle** [comment]
1. create a new vNext=based branch in docs
2. create 2 new folders in `docs/modules/reference/pages/ `, one called `api` and one called `spi`
3. add the appropriate landing page file to each folder
4. got the 23.0.0.7 branch in docs and open the reference nav file
5.  copy the last two lines 
`reference:partial$feature-nav-api-openliberty.adoc`
`reference:partial$feature-nav-spi-openliberty.adoc`
6. switch back to your working branch and add them to the reference nav file
7. PR to `draft` _and_ `staging` getb them merged in
8. go to the `23.0.0.7` branch of `docs-generated` and copy the `feature-nav-spi-openliberty.adoc ` and `feature-nav-api-openliberty.adoc` files. from the `modules/reference/partials/` folder to your desktop
9. Create a new vNext based working branch in docs-generated
10. Replace line 1 of each file appropriately.
`* xref:api/open-liberty-apis.adoc[Open Liberty APIs]`
`* xref:spi/open-liberty-spis.adoc[Open Liberty SPIs] `
11. copy both files to the `docs-generated/modules/reference/partials/` folder
12. PR to `staging` (docs-generated) and get it merged in
13. delete all lines except for line 1 from both files
14. PR to `draft`(docs-generated)
15. wait for build and check draft and staging sites

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

The landing pages for OL APIs & SPIs draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/api/open-liberty-apis.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/spi/open-liberty-spis.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
Looks good, but I'd suggest a slight revision of the SPI page for concision and clarity

> Third-party developers can extend and customize the functions of the Open Liberty application server by using Service Provider Interfaces, or Open Liberty SPIs. These SPIs promote flexibility and maintainability by enabling developers to add new functions, incorporate extensions, or connect Open Liberty with other systems, all without altering the core software.

I'd suggest to revise this to be about "you" instead of "third party developers"

**Comment by ramkumar-k-9286** [comment]
Hi Michal @mbroz2 

Created landing pages for OL APIs & SPIs.

Draft links:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/api/open-liberty-apis.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/spi/open-liberty-spis.html

Could you please review these pages?

Regards,
Ramkumar.

CC @dmuelle

**Comment by mbroz2** [comment]
How about something along the lines of:

API:
Open Liberty provides additional Application Programming Interfaces (APIs) which extend and complement the Jakarta and MicroProfile APIs.  These APIs enable various Liberty capabilities that go beyond the aforementioned specifications, with a strong focus on security. 

Thanks to Liberty's [Zero Migration](https://openliberty.io/docs/latest/zero-migration-architecture.html) policy, you can rest assured that future releases will continue to provide these APIs.


SPI:
Open Liberty Service Provider Interfaces (SPIs) enable the extension and customization of various runtime capabilities. Via user features, these SPIs promote flexibility and maintainability by enabling developers to add new functions, incorporate extensions, or connect Open Liberty with other systems, all without altering the core software.

Thanks to Liberty's [Zero Migration](https://openliberty.io/docs/latest/zero-migration-architecture.html) policy, you can rest assured that future releases will continue to provide these SPIs.

**Comment by ramkumar-k-9286** [comment]
Hi Michal @mbroz2

Incorporated your comments for the landing pages of OL APIs & SPIs.

Draft links:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/api/open-liberty-apis.html

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/spi/open-liberty-spis.html

Please check and see if you are satisfied with the changes.

Regards,
Ramkumar.

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Hi David @dmuelle 

Staging links for the landing pages of OL APIs & SPIs.

https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/api/open-liberty-apis.html

https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/spi/open-liberty-spis.html

Please check and see if you are satisfied with the changes.

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM, thanks

**Comment by dmuelle** [comment]
Content is on vNext and will publish with 23.0.0.9. Closing as completed.
