### ISSUE TITLE
Missing options for server create command

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/docs#6806]
Document: server create command
http://openliberty.io/docs/latest/reference/command/server-create.html

The create command is missing the options section:

```
Usage: ./server create serverName [options] [JVM options]

        Create a new server if the specified server does not exist. The
        --template option can be used to specify a template to use when
        creating a new server.

Options:

    --no-password
        Disable generation of default keystore password
    --template="templateName"
        Specify the name of the template to use when creating a new server.
```

**Comment by dmuelle** [comment]
Hi @mbroz2 - the command doc is updated on draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/server-create.html#_options

I didn't explicitly list all the available templates but instead pointed to the `wlp/templates` directories. If we want to maintain an explicit list on this page I can make that update. Let me know what you think. 

Thanks

**Comment by mbroz2** [comment]
Looks good; thanks

**Comment by dmuelle** [comment]
update will publish with 23008. closing as completed.
