### ISSUE TITLE
drop misleading environment variable prefix

### ISSUE THREAD

**Issue by covener** [OpenLiberty/docs#6808]
Document: Server configuration overview
http://openliberty.io/docs/latest/reference/config/server-configuration-overview.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

This snippet is misleading:

> For versions 19.0.0.3 and earlier, you can access environment variables by adding env. to the start of the environment variable name, as shown in the following example:

Alasdair suggested to simply remove the sentence. It is trying to say "In 19.0.03 the `env.` prefix was necessary" but that is dated trivia at this point.

**Comment by dmuelle** [comment]
update will publish with 23008. closing as completed.
