### ISSUE TITLE
Faces Version Wrong in EE10 Migration Doc

### ISSUE THREAD

**Issue by volosied** [OpenLiberty/docs#6834]
I spotted an error in the EE10 Migration doc here: https://www.ibm.com/docs/en/wamt?topic=migration-jakarta-ee-10-behavior-differences

Problematic Text:
```This category contains rules that help migrate to Jakarta Server Faces 3.0. ```

 It should say 4.0.

**Comment by dmuelle** [comment]
sorry @volosied - I misunderstood where the source for this error was. I've opened an issue on the WAMT-DOC backlog to get it fixed

https://github.ibm.com/was-migration-tools/wamt-doc/issues/143

closing this issue
