### ISSUE TITLE
MPTelemetry combined with MPOpenTracing docs

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/docs#6846]
The differences between MpTelemetry and MpOpenTracing are highlighted here: 

https://openliberty.io/docs/latest/reference/diff/mp-50-60-diff.html#telemetry

It would be beneficial to show users how to trace services with OpenTracing and OpenTelemetry together e.g. Having one service with mpOpenTracing and another with mpTelemetry. 

Draft blog post here: 

https://ibm.box.com/s/lhni57u2q0gazucqgei3ctjqeg2cabg2

**Comment by Emily-Jiang** [comment]
@dmuelle can you update the doc accordingly?

**Comment by dmuelle** [comment]
we will add a new subsection to the linked page "Combining OpenTelemetry with OpenTracing"

**Comment by dmuelle** [comment]
Hi @yasmin-aumeeruddy - this draft is ready for review when you have a chance:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-50-60-diff.html#telemetry

I made some edits per Emilys comments on the post. I also have a few questions-

- is it possible to provide a code example to demonstrate the necessary configuration? It's hard to tell what is happening where w/r/t to setting the env var or props

> Both services can collect traces with without losing the parent-child relationship in the spans

Why does this matter? does it mean that the same spans are collected on each service with the same parent/ child relationships span to span? 

- The diagram labels  2 way "context propagation" between the services. but the text deosn't mention context propagaiton at all- what is the significance in this scenario?

> To export distributed traces successfully to the Zipkin backend exporter, service B must include the B3 propagation header for Zipkin by specifying either the OTEL_PROPAGATORS=b3 environment variable or the otel.propagators=b3 configuration property

What about service A? is B3 the default for OpenTracing?

> If more than one propagator is enabled, then all headers are added to outgoing requests and any header is accepted for incoming requests. For example, if you are migrating from using a Jaeger client, you might set the otel.propagators=jaeger configuration property to use the Jaeger propagation protocol. Alternatively, you might set the otel.propagators=jaeger,tracecontext,baggage configuration property to allow use of both the Jaeger and W3C protocols.

- What are examples of incoming/outgoing requests- are those between a & b or between each service and Zipkin?
- Migrating from using Jaeger to what? W3C? The significance is not immediately clear.

**Comment by Yas-Franco** [comment]
Hi @dmuelle 

A `Context` is an object that contains information required to associate spans with each other while `Propagation` is the mechanism that moves this context between services and processes. When spans are created from different services, context propagation is what makes it possible to see their parent-child relationship. This allows developers to see dependenices across services in a request.  If these services are using different frameworks (i.e. OpenTracing and OpenTelemetry), the propagator that is used needs to be properly configured so that the context information is readable to the exporter.

This part of the [documentation](https://opentelemetry.io/docs/concepts/signals/traces/#context-propagation) explains context propagation well. 

The example in the diagram shows that service A is using OpenTracing. Therefore, service B needs to be configured in order to accomadate for it. 

Examples of incoming/outgoing requests would include client requests to service A or B and requests between both of these services. 

All of these examples are stating how to migrate from a tool (e.g. Jaeger client or OpenTracing) to OpenTelemetry. So if service A was using the Jaeger Client instead of OpenTracing, you would set `otel.propagators=jaeger` in service B to accomodate and still maintain span context. The protocol that the user requires is determined by what their existing service is already using for their trace context. 

I hope this helps

**Comment by dmuelle** [comment]
Thanks @yasmin-aumeeruddy - this is very helpful. I've updated my draft slightly. WOuld you review when you have a chance and let me know if any further edits are  needed? When you're satisfied with the draft you can add the `Technical reviewed` label to this issue to sign off and the update will publish with the nest docs release. Thanks!

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/diff/mp-50-60-diff.html#telemetry

**Comment by dmuelle** [comment]
content is on vNext and will publish with 23.0.0.10- closing as completed
