### ISSUE TITLE
Update Java SE support for Java 21

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6856]
feature epic: https://github.com/OpenLiberty/open-liberty/issues/24613

need to update the [Java SE support](https://openliberty.io/docs/latest/java-se.html) page for 230010 to include Java 21

**Comment by dmuelle** [comment]
Hi @gjwatts - the Java SE support page draft is now updated for Java 21

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html

I also removed Java 20 from the table since it is now out of support- let me know if that is not correct. If the table looks good, you can add the `technical reviewed` label to this issue to sign off and the update will publish with 23.0.0.10. Thanks!

**Comment by gjwatts** [comment]
@dmuelle Done.  Thank you for taking care of this David!
