### ISSUE TITLE
SSL handshake error while trying to connect to IBM MQ from liberty server 

### ISSUE THREAD

**Issue by kscuben** [OpenLiberty/docs#6876]
we have configured the server.xml to connect to IBM MQ from this IBM article (https://www.ibm.com/docs/en/was-liberty/nd?topic=dmal-deploying-jms-applications-liberty-use-mq-messaging-provider)  

THe above config is working for non-ssl config but once MQ side SSL is enabled ,we are getting **"unable to find valid certification path to requested target"**

we are using default keystore and trustore and all of them are configured correct( syntactically) ..how to enforce our jms outbound connection to take SSL ? any specific tags for that??

**Comment by dmuelle** [comment]
closing this issue as it's not specifically an Open Liberty doc issue and has been addressed in groups.io
