### ISSUE TITLE
correction to session_liveSessions metric description

### ISSUE THREAD

**Issue by donbourne** [OpenLiberty/docs#6897]
Document: Metrics reference list
http://openliberty.io/docs/latest/metrics-list.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

The number of users that are currently logged in since this metric was enabled. This metric is a gauge.
->
The number of users that are currently logged in. This metric is a gauge.

**Comment by ramkumar-k-9286** [comment]
Hi @donbourne 

Made the update.

Noticed there are 2 session_liveSessions. is the update applicable for both?

Also, many other metrics seem to have a description with similar wordings. Should this also not be corrected?

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/metrics-list.html


Regards,
Ramkumar

CC @dmuelle

**Comment by donbourne** [comment]
> Noticed there are 2 session_liveSessions. is the update applicable for both?

yes - it's applicable to both

> Also, many other metrics seem to have a description with similar wordings. Should this also not be corrected?

I did a scan through all places where we say "since the" or "since this" -- the other places seem fine.  Are there any other descriptions that you see that might be inappropriate?

**Comment by ramkumar-k-9286** [comment]
Hi @donbourne

Made the update for both `session_liveSessions` mentions. 

Draft link: 

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/metrics-list.html

Regards,
Ramkumar

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Updates Done. Verified by Developer. 
Updated for 23.0.0.10 documentation release.

Proceeding to close the issue.

Regards,
Ramkumar

**Comment by dmuelle** [comment]
@ramkumar-k-9286 - have these changes gone to staging and vNext yet?
