### ISSUE TITLE
featureUtility

### ISSUE THREAD

**Issue by fredZhao015** [OpenLiberty/docs#6900]
Document: Develop with Liberty Tools
http://openliberty.io/docs/latest/develop-liberty-tools.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by dmuelle** [comment]
Hi @fredZhao015 - can you give us some details about problems you experienced with this page?

**Comment by dmuelle** [comment]
In case you were looking for information about the featureUtility command- it is documented here:

https://openliberty.io/docs/latest/reference/command/featureUtility-commands.html

**Comment by dmuelle** [comment]
closing due to lack of information- feel free to reopen if needed and provide more context. Thanks
