### ISSUE TITLE
Add canonical link HTML tag to RHR-built guides

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#693]
For each guide built with RHR pipeline, the guide should have a canonical link HTML tag in its source that points back to its URL on the OpenLiberty.io site (to the specific guide's URL, not just a generic link to all the guides).

This is so that search engines don't see it as duplicate content in two different locations but RHR customers can still access all their OL in RHR doc on their portal without having to click out to the OpenLiberty.io website.

**Comment by Charlotte-Holt** [comment]
@lauracowen Since we're not building the guides into the RHR, can I close this one?

**Comment by lauracowen** [comment]
Yup, good point.
