### ISSUE TITLE
Add 'remote includes' for standalone OL doc topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#696]
Pull in relevant existing topics from OL docs (not the guides yet) using remote includes at the appropriate places in the new RHR doc that's been written.

Start by testing with the logging and trace topic and get that building appropriately (updating the new doc text as necessary to make it all make sense and hang together in a usable way).

See instructions at: https://asciidoctor.org/docs/user-manual/#include-uri

**Comment by Charlotte-Holt** [comment]
@lauracowen Do you think we're okay to close this issue? We included several remote includes in the last RHR release, and they worked (other than the macro issue). David's also working on #754 for 19.0.0.12.

**Comment by lauracowen** [comment]
Yes. Closing.
