### ISSUE TITLE
Documentation for HTTP Request Tracing 

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/docs#6966]
### Feature epic details 

- For the title of this issue, type: Documentation, HTTP Request Tracing
- Link to development epic: https://github.com/OpenLiberty/open-liberty/issues/24379
- Target GA release: 23.0.0.11

### Operating systems

Does the documentation apply to all operating systems? 
- [X] Yes  
- [ ] No; specify operating systems: ______

### Summary
Provide a concise summary of your feature. What is the update, why does it matter, and to whom? What do 80% of target users need to know to be most easily productive using your runtime update?

### Configuration
List any new or changed properties, parameters, elements, attributes, etc. Include default values and configuration examples where relevant:

Feature is automatically enabled when `mpTelemetry-1.0` and `mpTelemetry-1.1` is enabled.  No new configuration. 

### Updates to existing  topics
To update existing topics, specify a link to the topics that are affected.  Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ

In this page https://openliberty.io/docs/latest/microprofile-telemetry.html, under the "Automatic Instrumentation" section.  Add the following line.

Starting in 23.0.0.11, spans will be automatically created for incoming HTTP requests such as static files, servlets and JSPs.

**Comment by ramkumar-k-9286** [comment]
@fmhwong @dmuelle 

Hi Felix.

Added the suggested information into the document. Made minor changes to the suggested information.

Also, placed the information towards the beginning of the Automatic Instrumentation section to ensure that the audience is immediately aware of this information when learning about automatic instrumentation.

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/microprofile-telemetry.html

Please review the same and add the `Developer Reviewed` label if you are happy with the change. 

Regards,
Ramkumar

**Comment by fmhwong** [comment]
FYI, there was an issue of mpTelemetry running with InstantOn so we reverting the beta fencing in 23.0.0.11.  We are targeting 23.0.0.12 now.

**Comment by dmuelle** [comment]
Closing this issue as the content is in the telemetry file, which will get technical and peer review as part of #6776 . The changes in this issue are in the same branch as those updates and will be delivered to vNext when that branch is merged.
