### ISSUE TITLE
Update link text in SE support table

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#6976]
for the link text in the [Java SE support table](https://openliberty.io/docs/latest/java-se.html#supported):

change the link text under HotSpot Download from Eclipse Adoptium * to Eclipse Temurin *

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David

The suggested changes have been made to the table.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html#supported

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- send to staging when you have a chance

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

The suggested changes have been made to the table.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html#supported

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- send to staging when you have a chance

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

The suggested changes have been made to the table.

STAGING link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html#supported

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David

Draft -> Staging

Staging link: https://docs-staging-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html#supported

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM, thanks
