### ISSUE TITLE
Documentation for Provide new computed metrics for MicroProfile Metrics feature

### ISSUE THREAD

**Issue by pgunapal** [OpenLiberty/docs#6977]
### Feature epic details 
- Link to development epic: https://github.com/OpenLiberty/open-liberty/issues/25813
- Target GA release: 23.0.0.11

### Operating systems

Does the documentation apply to all operating systems? 
- [x] Yes  
- [ ] No; specify operating systems: ______

### Summary
Provide a concise summary of your feature. What is the update, why does it matter, and to whom? What do 80% of target users need to know to be most easily productive using your runtime update?

New convenience metrics are added to the mpMetrics[3.0-5.1] features' `/metrics` output to make it easier to alert on and visualize important data. With this update, the target users (DevOps) do not need to manually perform calculations on the individual metrics provided by mpMetrics to get computational metrics. They can now get the "elapsedTime" per a particular event (GC Time, Servlet Requests, Connection Pool connections, REST requests) without calculating them explicitly, as some monitoring tools do not support performing complex time series calculations.

These new computed metrics can now be viewed on dashboards using monitoring tools, that do not support complex time series array calculations.

### Configuration
List any new or changed properties, parameters, elements, attributes, etc. Include default values and configuration examples where relevant:

- Just need to enable either one of the mpMetrics[3.0-5.1] in the server.xml

### Updates to existing  topics
To update existing topics, specify a link to the topics that are affected.  Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ

The following two metrics reference list for mpMetrics 5.0+ and mpMetrics-4.0- should be updated to add the new convenience metrics:

### - Metrics 5.0 Table : https://openliberty.io/docs/latest/metrics-list.html#_microprofile_metrics_5_0_metrics_reference

**MicroProfile Metrics 5.0 name :** `cpu.processCpuUtilization`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `cpu_processCpuUtilization_percent{mp_scope="vendor"}`
**Type and description :** `The recent CPU time that is used by the JVM process from all processors that are available to the JVM. The value is between 0 and 1. This metric is a gauge.`
**Monitoring component :** `Base metric`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

**MicroProfile Metrics 5.0 name :** `memory.heapUtilization`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `memory_heapUtilization_percent{mp_scope="vendor"}`
**Type and description :** `The portion of the maximum heap memory that is currently in use. This metric displays -1 if the maximum heap memory size is undefined. This metric is a gauge.`
**Monitoring component :** `Base metric`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

**MicroProfile Metrics 5.0 name :** `gc.time.per.cycle`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `gc_time_per_cycle_seconds{mp_scope="vendor",name="<gcType>"}`
Type and description : `The recent average time spent per garbage collection cycle. This metric displays -1 if the garbage collection elapsed time or count is undefined for this collector. This metric is a gauge.`
**Monitoring component :** `Base metric`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

**MicroProfile Metrics 5.0 name :** `connectionpool.inUseTime.per.usedConnection`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `connectionpool_inUseTime_per_usedConnection_seconds{datasource="<datasourceName>",mp_scope="vendor"} `
**Type and description :** `The recent average time that connections are in use. This metric is a gauge.`
**Monitoring component :** `ConnectionPool`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

**MicroProfile Metrics 5.0 name :** `connectionpool.waitTime.per.queuedRequest`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `connectionpool_waitTime_per_queuedRequest_seconds{datasource="<datasourceName>",mp_scope="vendor"} `
**Type and description :** `The recent average wait time for queued connection requests. This metric is a gauge.`
**Monitoring component :** `ConnectionPool`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

**MicroProfile Metrics 5.0 name :** `REST.request.elapsedTime.per.request`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `REST_request_elapsedTime_per_request_seconds{class="<fully_qualified_class_name>",method="<method_signature>",mp_scope=”vendor"}`
Type and description : `The recent average elapsed response time per RESTful resource method request. This metric is a gauge.`
**Monitoring component :** `REST`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

**MicroProfile Metrics 5.0 name :** `servlet.request.elapsedTime.per.request`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `servlet_request_elapsedTime_per_request_seconds{mp_scope="vendor",servlet="<servletName>"}`
**Type and description :** `The recent average elapsed response time per servlet request. This metric is a gauge.`
**Monitoring component :** `WebContainer`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 5.0`

### - Metrics 4.0 Table : https://openliberty.io/docs/latest/metrics-list.html#_microprofile_metrics_4_0_and_earlier_metrics_reference

**MicroProfile Metrics 4.0 name :** `cpu.processCpuUtilization`
**MicroProfile Metrics 4.0 Prometheus name(s) :** `vendor_cpu_processCpuUtilization_percent`
**Type and description :** `The recent CPU time that is used by the JVM process from all processors that are available to the JVM. The value is between 0 and 1. This metric is a gauge.`
**Monitoring component :** `Base metric`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

**MicroProfile Metrics 4.0 name :** `memory.heapUtilization`
**MicroProfile Metrics 4.0 Prometheus name(s) :** `vendor_memory_heapUtilization_percent`
**Type and description :** `The portion of the maximum heap memory that is currently in use. This metric displays -1 if the maximum heap memory size is undefined. This metric is a gauge.`
**Monitoring component :** `Base metric`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

**MicroProfile Metrics 5.0 name :** `gc.time.per.cycle`
**MicroProfile Metrics 5.0 Prometheus name(s) :** `vendor_gc_time_per_cycle_seconds{name="<gcType>"}`
Type and description : `The recent average time spent per garbage collection cycle. This metric displays -1 if the garbage collection elapsed time or count is undefined for this collector. This metric is a gauge.`
**Monitoring component :** `Base metric`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

**MicroProfile Metrics 4.0 name :** `connectionpool.inUseTime.per.usedConnection`
**MicroProfile Metrics 4.0 Prometheus name(s) :** `vendor_connectionpool_inUseTime_per_usedConnection_seconds{datasource="<datasourceName>"}`
**Type and description :** `The recent average time that connections are in use. This metric is a gauge.`
**Monitoring component :** `ConnectionPool`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

**MicroProfile Metrics 4.0 name :** `connectionpool.waitTime.per.queuedRequest`
**MicroProfile Metrics 4.0 Prometheus name(s) :** `vendor_connectionpool_waitTime_per_queuedRequest_seconds{datasource="<datasourceName>"} `
**Type and description :** `The recent average wait time for queued connection requests. This metric is a gauge.`
**Monitoring component :** `ConnectionPool`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

**MicroProfile Metrics 4.0 name :** `REST.request.elapsedTime.per.request`
**MicroProfile Metrics 4.0 Prometheus name(s) :** `vendor_REST_request_elapsedTime_per_request_seconds{class="<fully_qualified_class_name>",method="<method_signature>"}`
Type and description : `The recent average elapsed response time per RESTful resource method request. This metric is a gauge.`
**Monitoring component :** `REST`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

**MicroProfile Metrics 4.0 name :** `servlet.request.elapsedTime.per.request`
**MicroProfile Metrics 4.0 Prometheus name(s) :** `vendor_servlet_request_elapsedTime_per_request_seconds{servlet="<servletName>"}`
**Type and description :** `The recent average elapsed response time per servlet request. This metric is a gauge.`
**Monitoring component :** `WebContainer`
**Features required :** `MicroProfile Metrics`
**Version introduced :** `MicroProfile Metrics 3.0`

### Create a new topic
To create a topic, specify a first draft of the topic that you want added and the section in the navigation where the topic should go.

**Comment by dmuelle** [comment]
Hi @pgunapal - is this still targeted for 23001- I know mpm 5.1 moved to 230012, not sure if this is separate

**Comment by pgunapal** [comment]
@dmuelle This is separate, since its delivered for mpMetrics-3.0, 4.0, and 5.0.

**Comment by dmuelle** [comment]
Hi @pgunapal - these updates are now ready for review on the draft site:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/metrics-list.html

Let me know if any further edits are needed. When you're satisfied with the edits, you can add the `technical reviewed` label to this issue to sign off and the update will publish with the 230010 release. Thanks!

**Comment by pgunapal** [comment]
@dmuelle 
In both the Metrics 4.0 and 5.0 metric reference tables:
- For the **REST.request.elapsedTime.per.request** metric, the **Monitoring Component**, **Features Required**, and **Version Introduced** columns are incorrect/empty.

- After the **REST.request.elapsedTime.per.request**, the MicroProfile Metrics 5.0 name column seems to have the incorrect contents for the rest of the metrics list...

**Comment by dmuelle** [comment]
Sorry- formatting error. Should be fixed now

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/metrics-list.html

**Comment by pgunapal** [comment]
Looks good, added the `technical reviewed` label.
