### ISSUE TITLE
Decide which guides to include in the RHR docs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#698]
Not all guides are relevant. In my email, I mapped the sections of the doc to a selection of the OL guides.  Based on that and any other discussion, identify a definitive list of the OL guides to include in RHR docs. Then notify @yeekangc to ensure that those guides are prioritised for any of the fixes that are being done under issues https://github.com/OpenLiberty/guides-common/issues/352 and https://github.com/OpenLiberty/guides-common/issues/344

**Comment by yeekangc** [comment]
Please keep @gkwan-ibm in the loop too.  Thank you.

**Comment by lauracowen** [comment]
Done.
