### ISSUE TITLE
InstantOn Standalone MP features

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/docs#7005]
Document: Faster startup for containerized applications with Open Liberty InstantOn
http://openliberty.io/docs/latest/instanton.html

It may not be clear to end users that standalone MP features do not currently have InstantOn support (for example, MP Reactive Messaging).  A suggestion would be to alter the wording to something like 'InstantOn supports the features that these [MP/Jakarta] convenience features make available.'  
or maybe something like 'Note that standalone MicroProfile features, which are not part of the convenience features, are currently not supported for InstantOn'

Also, there's an instance of "ae" in the doc that should be "are":

> You can individually enable the Open Liberty public features that ae enabled by the [Jakarta EE Web Profile](https://openliberty.io/docs/latest/reference/feature/webProfile.html) and [MicroProfile](https://openliberty.io/docs/latest/reference/feature/microProfile.html) features, depending on the needs of your application.

**Comment by tjwatson** [comment]
I think it would be more clear if we did the work to auto-generate a table of InstantOn supported features based on the value of the `WLP-InstantOn-Enabled` feature header.

```
WLP-InstantOn-Enabled: true
```
vs this for features that are enabled when running the beta image:
```
WLP-InstantOn-Enabled: true; type:=beta
```

**Comment by mbroz2** [comment]
I agree, but that seems like a more long-term solution vs updating the current wording for this case.

**Comment by dmuelle** [comment]
Hi @mbroz2 @tjwatson - I've fixed the typo and added the following text to clarify that MP standalone features are not currently supported by InstantOn (new text in italics):

> InstantOn supports a subset of Open Liberty features. If a feature is enabled that InstantOn does not support, a failure occurs when you try to perform a checkpoint of an application process. InstantOn supports the following Jakarta EE and MicroProfile [convenience features](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/feature-overview.html#conv):

- > Jakarta EE Web Profile versions [8.0](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/webProfile-8.0.html) and later
- > MicroProfile versions [4.1](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/microProfile-4.1.html) and later

> You can individually enable the Open Liberty public features that are enabled by the [Jakarta EE Web Profile](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/webProfile.html) and [MicroProfile](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/microProfile.html) features, depending on the needs of your application. This option avoids enabling the complete set of features that are enabled by the convenience features. _However, InstantOn currently does not support standalone MicroProfile features, which are MicroProfile features that are not enabled by any of the convenience features._

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html#supported-features

If any further edits are needed, just let me know. Thanks!

**Comment by mbroz2** [comment]
@cbridgha any idea what level of effort it would take to have the generated docs reflect [Tom's comment](https://github.com/OpenLiberty/docs/issues/7005#issuecomment-1783013380)?
