### ISSUE TITLE
Update Directory Include Processing Docs

### ISSUE THREAD

**Issue by rsherget** [OpenLiberty/docs#7006]
It may be helpful to discuss the onConflict behavior when a directory is used in the `<includes>` element of a server.xml as discussed in this Slack thread https://ibm-cloud.slack.com/archives/C30NGTBFS/p1698251125696169. 

Adding a section in https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#include-processing that reflects the example below will help users better understand the behavior:
```
It should apply the behavior on a file by file basis as it iterates over all the files within the specified directory.

if you use <include location="/directory/" onConflict="REPLACE"> 
and that directory holds a.xml and b.xml, then its the equivalent of saying 
<include location="a.xml" onConflict="REPLACE">
<include location="b.xml" onConflict="REPLACE">
```

It also may be helpful to note that if a directory is used, it must end with an ending slash. For example, if a user were to use `location="./common"`, it would not work, it must be `location="./common/"`

**Comment by rsherget** [comment]
Also, It may be nice to add that if a user adds a URI that points to a directory, that does not work. A URI can still only point to a single resource.

This will just help clarify to users what works and is compatible with the changes done in [feature 25149](https://github.com/OpenLiberty/open-liberty/issues/25149)

**Comment by ramkumar-k-9286** [comment]
> Also, It may be nice to add that if a user adds a URI that points to a directory, that does not work. A URI can still only point to a single resource.
> 
> This will just help clarify to users what works and is compatible with the changes done in [feature 25149](https://github.com/OpenLiberty/open-liberty/issues/25149)

This document does not mention URI and hence it would be better if supplied an example.
similar to the examples we have already on the page.
Would you be able to share an example of the same?

Also could you confirm if we should use URI or URL ( documentation for the include element uses both)

Regards,
Ramkumar.

**Comment by rsherget** [comment]
Just to be consistent with this doc https://openliberty.io/docs/latest/reference/config/include.html, it may be better to state "URI for a remote resource" so a URI for a remote resource cannot be a directory it must be a single file. 

for example Its supported that a user can enter https://website.com/path/to/server.xml
but it is not supported to use https://website.com/path/to/directory

**Comment by evie-lau** [comment]
The [WAS Liberty docs](https://www.ibm.com/docs/en/was-liberty/base?topic=files-using-configuration-dropins-folder-specify-server-configuration) for `configDropins` folders also has a note about lowercasing filenames before sorting. I think it would be helpful to include something similar for the OpenLiberty docs.

The current 23.0.0.10 release [does not do this](https://github.com/OpenLiberty/open-liberty/issues/26818), but should be fixed for 23.0.0.11 in https://github.com/OpenLiberty/open-liberty/pull/26819

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David,

The suggested changes have been made. Please take a look at the draft document.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html


Regards,
Ramkumar

**Comment by dmuelle** [comment]
Hi Ram,

> You can set the location attribute to a relative or absolute file path, a directory, or to an HTTP URL.

This sentence should be moved down with the rest of the info about include locations near the end of this section. Also

HTTP URL--->URI for a remote resource


> For ~~more~~ configuration files that are brought from a directory by using the include element,


Functionally, this is the same as including each file separately with its own onConflict attribute as shown in the following example
--->
Functionally, this configuration is the same as including each file separately with its own `onConflict` attribute, as shown in the following example

> When you are specifying a directory in the include location, make sure that you append a slash(/). For example, (location="./common/"). Omitting the slash(/) after the directory name (location="./common") results in an error and incorrect processing.

add space between "slash" and "(" x2

I think we need to migrate [WAS Liberty docs](https://www.ibm.com/docs/en/was-liberty/base?topic=files-using-configuration-dropins-folder-specify-server-configuration) for configDropins to this page, possibly in a new section just after include section. I'll open an issue.

**Comment by rsherget** [comment]
If I may add one last suggestion, the last server.xml snippet within the includes processing section does not have any spacing on the <include> tag.
```
<server>
<include location="./common/"/>
</server>
```
To be consistent with everything else it may be better to have the same snippet just with spacing for readability and consistency.
```
<server>
    <include location="./common/"/>
</server>
```

**Comment by evie-lau** [comment]
> I think we need to migrate [WAS Liberty docs](https://www.ibm.com/docs/en/was-liberty/base?topic=files-using-configuration-dropins-folder-specify-server-configuration) for configDropins to this page, possibly in a new section just after include section. I'll open an issue.

Additionally, I think this `Include processing` section of the docs doesn't need to mention the configDropins. Just has to note the behavior of being case-insensitive (or converting to lowercase first) before processing alphabetically.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

The suggested corrections have been done. Please take a look at the draft document.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
Looks good except the information about the `location` attribute can be better organized. It jumps around between talking about directories, URIs, and files. Try to rework this section to better chunk that info. ie, start out by stating the kinds of values you can specify for location, then group information/examples about each value type together.

**Comment by dmuelle** [comment]
also, move the `location` info to be before the `onConflict` information, since `onConflict` has details about different locations, need to explain location first. Make the onConflict stuff last in the section.

missing monospace highlighting:

> For example, (location="./common/"). Omitting the slash (/) after the directory name (location="./common") 

For more configuration files that are brought from a directory 
--->
For configuration files that are brought in from a directory

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Document for Peer Review.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
better, but the information about include locations is still mixed up. Starting after the example of `optional`, locations are explained:

1. syntax of specifying a directory as a location
2. processing behavior for directory location
3. different types of valid locations
4. example of directory location
5. syntax of specifying URI location
6. processing behavior for directory location

To properly chunk the information, it be more like 3, 4, 2, 6, 1, 5. 

That way, you first introduce the available types, provide an example, privde details about directories, then details about URIs.


Also-

missing monospace highlighting:

For example, (location="./common/"). Omitting the slash (/) after the directory name (location="./common")

For more configuration files that are brought from a directory
--->
For configuration files that are brought in from a directory

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Incorporated comments.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html

Regards,
Ramkumar
