### ISSUE TITLE
Update CVE list for 23.0.0.11

### ISSUE THREAD

**Issue by clarkek123** [OpenLiberty/docs#7010]
Draft is updated in PR https://github.com/OpenLiberty/docs/pull/7009

**Comment by clarkek123** [comment]
I've reviewed the draft on the staging site and see the update for range 23.0.0.9 - 23.0.0.10 and have verified all links to CVE and features. Looks good.

**Comment by dmuelle** [comment]
update is on vNext and will publish with 230011- closing as completed
