### ISSUE TITLE
add configdropins info to server config overview

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#7031]
Migrate [WAS Liberty docs](https://www.ibm.com/docs/en/was-liberty/base?topic=files-using-configuration-dropins-folder-specify-server-configuration) for configDropins info to Server config overview.

- create a new section just after "include processing"
- make the info match the styloe of the server config overview instead of "task" format.
- confirm w/ dev whether configDropins is  intended for prod use or just dev/test and clarify in doc if needed.

**Comment by ramkumar-k-9286** [comment]
@dmuelle 

Hi David,

I added the suggested information to the Server Configuration Overview Document.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html


Regards,
Ramkumar.

**Comment by dmuelle** [comment]
Looks good, except the title of the section is not parallel with other titles in this topic. Looking more closely at the topic, I see there is already some info about configdropins, including the precedence in the section for the server.xml file: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#server-xml

I think we can just incorporate the info from the new section there, without needing to make a separate section,. Since the precedence and the definition are already in this section, all we really need is the information from the "Types of subdirectories within configDropins" secxtion, which I think cpuld be integrated into the server.xml section without needing it's own heading

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

I made the suggested changes to the document. I removed the section that was added and made modifications in the Server.xml section to add the suggested information.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#server-xml

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- I do see a few small acrolinx issues. If you run acrolinx on the updated text and fix what you can, I think it's ready to go to staging.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Acrolinx issues fixed.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#server-xml

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Acrolinx issues fixed.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#server-xml

Regards,
Ramkumar.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

Acrolinx issues fixed.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#server-xml

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
looks good except-

Formatting on monospace code terms is messed up here:

Configurations in the `configDropins/overrides` directory take precedence over configurations in the `server.xml` file, which in turn take precedence over configurations in the `configDropins/defaults` directory. The configurations in 'configDropins/overrides' and 'configDropins/defaults' supersede any default settings a feature specifies.

Also- 

their order of processing can be inconsistent.
--->
their order of processing might be inconsistent.

**Comment by ramkumar-k-9286** [comment]
@dmuelle

Hi David,

The suggested corrections are done.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#server-xml

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- I think it can go to staging
