### ISSUE TITLE
Access to Admin Center through an HTTP proxy server is not supported.

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#7047]
Discussed with Eric Covener, Thanh Giang.

Add the following wording to the [Admin Center documentation](https://openliberty.io/docs/latest/admin-center.html):

Access to Admin Center is supported only when the access comes directly from a browser. Access through an HTTP proxy server is not supported.

**Comment by ramkumar-k-9286** [comment]
@chirp1 @dmuelle 

The suggested correction was done.

I added the suggested update to the **Log in to Admin Center** section.
This section discusses accessing the Admin Center, how to access the login page, and specifying the hostname and port number.
Placing the sentence here would provide users with important information about the limitations of accessing the Admin Center, specifically regarding the use of HTTP proxy servers.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/admin-center.html

Regards,
Ramkumar

**Comment by dmuelle** [comment]
LGTM, I think that placement makes sense.

**Comment by chirp1** [comment]
@ramkumar-k-9286 Hi Ram, the update looks good to me. You can close the issue when you are ready.
