### ISSUE TITLE
MicroProfile Telemetry Troubleshooting

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/docs#7050]
Add another section to MicroProfile Telemetry for troubleshooting. In particular, users may face issues if they have not closed the current scope properly (More detail in #24290)

**Comment by dmuelle** [comment]
Hi @yasmin-aumeeruddy - closing this issue, since the content is on the same page as the rest of the 1.1 updates, which will get full technical and peer review as part of #6776 . Feel free to reopen this issue if you still need it for any reason. Thanks
