### ISSUE TITLE
Documentation: Configuration options to change the MP OpenAPI endpoints

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#7068]
### Feature epic details 

- Link to development epic: https://github.com/OpenLiberty/open-liberty/issues/25011
- Target GA release: 23.0.0.12

### Operating systems

Does the documentation apply to all operating systems? 
- [x ] Yes  
- [ ] No; specify operating systems: ______

### Summary
Add configuration options to the MicroProfile OpenAPI features which allow the user to change:

the endpoint which serves the OpenAPI yaml/json document (default /openapi)
the endpoint which serves the Swagger UI interface for browsing the documentation (default /openapi/ui)

### Configuration

`<mpOpenAPI docPath="/myOpenAPI/path" uiPath="/myUi/Path" />`

### Updates to existing  topics
Add example to MP OpenAPI feature page

**Comment by dmuelle** [comment]
Hi @abutch3r - here is the draft update tom thew MP OpenAPI feature page for https://github.com/OpenLiberty/open-liberty/issues/25011. When you have a chance, would you review and let me know if any changes are needed?

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpOpenAPI-3.1.html#_configure_microprofile_openapi_documentation_endpoints

When you're satisfied with the update, you can add the `technical reviewed` label to this issue to sign off and the update will publish with 23.0.0.12. Thanks!

**Comment by abutch3r** [comment]
Hi @dmuelle  sole comment is that the feature is available from `mpOpenAPI-1.0` on wards, so should be added to all the mpOpenAPI pages. the old `OpenAPI` feature is unaffected by this feature.

In relation to that, I don't know if for 2.0 downwards how we would phrase ` for Jakarta RESTful Services (formerly JAX-RS) applications ` given that the 2.0 supports jaxrs-2.1 so would correctly be referred to as JAX-RS applications. so for 3.0 and 3.1, we use the current phrasing and for 2.0, 1.1 and 1.0 - `for JAX-RS applications`

The Content is good, so once the details around the versioning have been resolved, happy to approve

**Comment by dmuelle** [comment]
Thanks @abutch3r - that's a good point to keep in mind w/r/t JAX-RS. I've updated the draft to fix that and extendthe example to all versions of the MP OpenAPI feature:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpOpenAPI-1.0.html

Let me know if any further edits are needed. Thanks!

**Comment by abutch3r** [comment]
@dmuelle that is everything, I approve of the content so its good to go

**Comment by dmuelle** [comment]
@ramkumar-k-9286 this update is ready for peer review
