### ISSUE TITLE
Update MP intro topic with GA'd features

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#707]
As I write this that's:
- MP Context Propagation (see David's [concurrency intro](https://openliberty.io/docs/ref/general/#concurrency.html) and the [MP CP topic](https://draft-openlibertyio.mybluemix.net/docs/ref/general/#context-propagation.html))
- MP Reactive Messaging (see [Andy and Gordon's recent blog post](https://openliberty.io/blog/2019/09/13/microprofile-reactive-messaging.html))

Add sub-sections with a brief introduction to what the feature provides.

You'll also need to update the graphi (both CP and RM will appear in the bottom row of the diagram). There is a separate requirement to create an SVG image of the diagram that can be used both on the homepage and here so before you update this graphic, find out the status of that (see https://github.com/OpenLiberty/openliberty.io/issues/1405) and talk to the relevant people to find out where it's prioritised. If it will block you making progress here, maybe do an interim update of the MP Intro's diagram. Otherwise, adopt the new homepage image.

**Comment by dmuelle** [comment]
@lauracowen updated draft at 

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#microprofile.html

Subsections at the end for MP Context Prop and Messaging. Note that we don't have guides published for either of these yet so I linked them to a concept topic and blog post respectively

For now, diagram is unchanged

**Comment by lauracowen** [comment]
Looks good. Thanks.

**Comment by dmuelle** [comment]
changes added to develop branch via #1063 & #1064

**Comment by dmuelle** [comment]
updates are published at https://www.openliberty.io/docs/ref/general/#microprofile.html
