### ISSUE TITLE
CVE Updates for 23.0.0.12

### ISSUE THREAD

**Issue by clarkek123** [OpenLiberty/docs#7079]
Draft is updated in https://github.com/OpenLiberty/docs/pull/7078

This issue is created to move this along in the ID process.

**Comment by dmuelle** [comment]
Hi @clarkek123 - this update is now available for review on the draft site:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

If any further edits are needed, just let me know.
