### ISSUE TITLE
Update FIPS enablement documentation to add information for non-root user setup

### ISSUE THREAD

**Issue by nstewart0206** [OpenLiberty/docs#7164]
There is missing documentation for how to enable FIPS with a non-root user on [this page](https://openliberty.io/docs/latest/enable-fips.html).  In step 4, it should indicate that if prompted to setup a password when importing the keys, to press the Enter key twice to setup an empty password since Semeru Java does not support passwords for FIPS. This is for the first two bullets under step 4. The documentation for [Semeru FIPS](https://www.ibm.com/support/pages/node/6612693) notes the following: 
```
Note: In FIPS mode, IBM Semeru Runtimes does not support usage of the NSS database with password. While importing the PKCS#12 file-based keystore into the NSS database, if the pk12util tool asks to setup the password, press the Enter key twice to setup an empty password.
```
If a password is entered as prompted instead of an empty password, then the user will encounter a `CKR_PIN_INCORRECT` error in the liberty logs.

**Comment by una-tapa** [comment]
We worked with Java team to resolve this non-root issue. (internal link https://ibm-cloud.slack.com/archives/C59HR9D5X/p1690899120052139_  

The Java team documented the steps. Nichole ran into the issue as she followed the Liberty FIPS document. She noticed that it is hard for customers and users to find the information from the Liberty FIPS document. Please make it easier to find the Semeru FIPS steps from Liberty FIPS doc.

**Comment by ramkumar-k-9286** [comment]
Hi @nstewart0206 

Suggested additions have been made to the document.

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-fips.html

Please have a look at the updates and add the `Developer reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar

CC @dmuelle

**Comment by nstewart0206** [comment]
It looks like there's a formatting error in the draft which makes the numbering incorrect.  After step 4, the numbering starts back at 1 instead of being 5.  Otherwise the additions to the document look good.

**Comment by ramkumar-k-9286** [comment]
Hi @nstewart0206

Suggested correction done.

Draft Link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-fips.html

Please have a look at the updates and add the Developer reviewed label if you are satisfied with the changes.

Regards,
Ramkumar

CC @dmuelle
