### ISSUE TITLE
Document the new Java 21 images

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/docs#7171]
Document: Open Liberty container images
http://openliberty.io/docs/latest/container-images.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

- [x] Include the new image tags:

`kernel-slim-java21-openj9-ubi-minimal`
`full-java21-openj9-ubi-minimal`

- [x] Add a note that Java 21 images are based on Universal Base Image (UBI) 9 minimal and includes IBM Semeru Runtimes for Java 21 JRE

- [x] In "Build an application image", replace these:
`kernel-slim-java17-openj9-ubi` --> `kernel-slim-java21-openj9-ubi`
`OpenJ9 distribution of Java 17` --> `OpenJ9 distribution of Java 21`
`FROM icr.io/appcafe/open-liberty:kernel-slim-java17-openj9-ubi` --> `FROM icr.io/appcafe/open-liberty:kernel-slim-java21-openj9-ubi-minimal`

- [x] In "Container image tags naming conventions" section
`<optional fix pack version-><liberty image type>-<java version>-<java type>-ubi` --> `<optional fix pack version-><liberty image type>-<java version>-<java type>-<base image type>`

    Add explanation for `Base image type` (after `Java type`):
    **Base image type**
    Liberty images are available with two different types of Red Hat Universal Base (UBI) images: `ubi-minimal` or `ubi`. 
    `ubi-minimal` offers a minimized pre-installed content set and the package manager `microdnf` for adding additional packages.
    `ubi` offers the standard images with access to `yum` repositories and includes utilities such as `tar` and `gzip`.

- [x] Update the Java type to include the tag values:
Current options are IBM Semeru with Eclipse OpenJ9 and, for Java SE 8 only, the IBM SDK, Java Technology Edition. --> Current options are IBM Semeru with Eclipse OpenJ9, named `openj9` and, for Java SE 8 only, the IBM SDK, Java Technology Edition, named `ibmjava`.

**Comment by ramkumar-k-9286** [comment]
Hi @leochr 

The suggested changes have been made.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

Please add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar

CC @dmuelle

**Comment by tjwatson** [comment]
We need to confirm the availability of the Java 21 images before publishing this update along with #7172

**Comment by leochr** [comment]
@ramkumar-k-9286 Thanks for the draft. 

Please change the following (my mistake):
- [x] `Red Hat Universal Base (UBI) images` --> `Red Hat Universal Base Image (UBI)`
- [x] "which uses the kernel-slim-java21-openj9-ubi tag" --> "which uses the kernel-slim-java21-openj9-ubi-minimal tag"
- [x]  "Current options are IBM Semeru with Eclipse OpenJ9" --> "Current options are IBM Semeru Runtime with Eclipse OpenJ9"

------

Also, I noticed a few more changes that are needed:

- [x] update the references to older versions:
23.0.0.10 --> 24.0.0.1
22.0.0.9 --> 23.0.0.12
22.0.0.6 --> 23.0.0.9

- [x] "The beta images are available only for the latest beta release." --> "The beta image is available only for the latest beta release of Liberty and includes the latest Java JRE."

- [x] "beta: This tag provides the most recent beta release, which includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development." --> "beta: This tag is based on Universal Base Image (UBI) 9 minimal and the latest Java JRE and provides the most recent beta release of Liberty, which includes all the features and capabilities from the most recent release, plus new and updated features that are currently in development."

- [x] "three preformatted tags" --> "the following preformatted tags" or "two preformatted tags"

- [x] "This tag simplifies pulling the full latest Open Liberty release with Java 8. It is an alias for the full-java8-openj9-ubi tag." --> "This tag simplifies pulling the full latest Open Liberty release with the latest Java JRE. It is an alias for the full-java21-openj9-ubi-minimal tag."

- [x] Add the following note - below the note about Java 21 - about other Java version images:
"Java 8, 11 and 17 images with the `openj9` type are based on Universal Base Image (UBI) 8 standard and include IBM Semeru Runtime for the respective Java version with the JDK. 

   Images with the `ibmjava` type are based on Universal Base Image (UBI) 8 standard and include IBM Java 8 JRE."

Thank you!

**Comment by ramkumar-k-9286** [comment]
Hi @leochr

The suggested corrections have been made.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

Please add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar

CC @dmuelle

**Comment by leochr** [comment]
@ramkumar-k-9286 Looks good. Thank you.

**Comment by leochr** [comment]
@ramkumar-k-9286 24.0.0.1 Liberty container images with Java 21 are now published. So the doc update can be published. Thank you
