### ISSUE TITLE
Document InstantOn is supported on Power and Z (s390x) with the Liberty Java 21 images

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/docs#7172]
Document: Faster startup for containerized applications with Open Liberty InstantOn
https://openliberty.io/docs/latest/instanton.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

- [x] Update sections of the documentation that describe the limitation that the X86-64/AMD64 processor architecture must be used with Liberty InstantOn (about 4 references).
- [x] Document that Power and Z (s390x) are supported starting with the Open Liberty Java 21 images.  The Liberty Java 21 images will be documented with issue #7171

**Comment by dmuelle** [comment]
do we also need to update this statement on the same page?

> Currently, InstantOn is supported with IBM Semeru Java version 11.0.19+ and IBM Semeru Java version 17.0.7+.

**Comment by tjwatson** [comment]
> do we also need to update this statement on the same page?
> 
> > Currently, InstantOn is supported with IBM Semeru Java version 11.0.19+ and IBM Semeru Java version 17.0.7+.

Yes, we need to add `IBM Semeru Java version 21.0.1+` there

**Comment by dmuelle** [comment]
Hi @tjwatson - the draft is updated with the changes you approved earlier:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html

Let me know if any further changes are needed- if not, you can add the technical reviewed label to this issue and the updates will publish with 24.0.0.1. Thanks!

**Comment by tjwatson** [comment]
One thing we need to be aware of is the timing of when the Java 21 images will be available.  There is a risk that they may be delayed.  I don't anticipate them to be weeks late.  But wanted to point that out.
