### ISSUE TITLE
[19.0.0.12] SEC-44: reader-role documentation

### ISSUE THREAD

**Issue by jvanhill** [OpenLiberty/docs#719]
There isn't much for security documentation in the Open Liberty doc, especially around administrative roles.

Create or move some of the administrative role documentation from Knowledge Center to Open Liberty Docs.

The updates made for this feature in Knowledge Center are documented in the following issue [IBM INTERNAL]:

> https://github.ibm.com/was-liberty/liberty-docs/issues/1629

**Comment by chirp1** [comment]
Hi Jesse, I updated the issue title by changing from 190011 to 190012. I see here https://github.com/OpenLiberty/open-liberty/issues/7253 that the SEC-443 epic is targeted for 190012. If for some reason SEC-44 is still targeted for 190011, let me know.  Thanks!

**Comment by dmuelle** [comment]
Hi @jvanhill - I've added the config example for admin/reader roles that we discussed via slack to the [Application Security feature page](https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/appSecurity-3.0.html). When you have a chance, can you review the example for `Administrative REST API access role configuration` ? If it looks ok, can you add the `technical reviewed` label to this issue? If any changes are needed, just let me know. Thanks!

**Comment by jvanhill** [comment]
@dmuelle -

The following sentences should be updated to include all the users and groups.

Reader role: monitorGroup, members, monitorUser, Bob
Admin role: adminGroup, managers, adminUser, Wanda

```
In the following example, a user who is named Bob and a group that is named members are granted the reader role. A user who is named Wanda and a group that is named managers are granted the administrator role
```

**Comment by dmuelle** [comment]
Hi @jvanhill I've updated the example per our slack discussion, splitting it into two examples, one of which is for user/group elements and the other for the option of using access IDs

https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/appSecurity-3.0.html#_administrative_rest_api_access_role_configuration

If it needs any further tweaks, just let me know. If it looks good, can you add the `technical reviewed` tag to this issue? Thanks

**Comment by dmuelle** [comment]
Closing this issue as editorial review of these examples will take place in #894
