### ISSUE TITLE
Bad links in "MicroProfile simplifies developing cloud-native Java microservices" article

### ISSUE THREAD

**Issue by cthigh** [OpenLiberty/docs#728]
I am going through https://openliberty.io/docs/ref/general/#microprofile.html and the links to the guides are giving 404s.

See: ref/general/microprofile.adoc

For example:
Try it now: Learn how to create a REST service with JAX-RS, JSON-P, and Open Liberty in our guide to Creating a RESTful web service.  
The link is `https://openliberty.io/guides/rest-intro`, but to get the page to load it needs to be `https://openliberty.io/guides/rest-intro.html`.

Same issue for all - I tried
Consuming RESTful services with template interfaces
Building fault-tolerant microservices with the @Fallback annotation
Failing fast and recovering from errors
Preventing repeated failed calls to microservices
Limiting the number of concurrent requests to microservices
Securing microservices with JSON Web Tokens
Configuring microservices
Separating configuration from code in microservices

**Comment by Charlotte-Holt** [comment]
Thanks, @cthigh. @lauracowen, I was just looking at a PR (#708) that addresses all of these links.

**Comment by cthigh** [comment]
Thanks Charlotte!

**Comment by Charlotte-Holt** [comment]
@cthigh This has been addressed. Thanks for raising the issue! Can you please review the links and confirm that you are okay to close this issue?

**Comment by cthigh** [comment]
Hi Charlotte, Thanks!  The new doc looks good.  Closing.
