### ISSUE TITLE
Update CVE list for 24004

### ISSUE THREAD

**Issue by clarkek123** [OpenLiberty/docs#7299]
Draft is updated in https://github.com/OpenLiberty/docs/pull/7298 and this issue is created to move along from Draft branch

**Comment by dmuelle** [comment]
Hi @clarkek123 - here are those updates on draft

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/security-vulnerabilities.html

If any further edits are needed, just let me know. Thanks

**Comment by clarkek123** [comment]
@dmuelle I've checked all the links and checked the content against the Security bulletin and it looks good to me.

**Comment by dmuelle** [comment]
Fixed by #7302 - updates will go out with 24004 release. Closing as completed, thanks
