### ISSUE TITLE
Doc additions for SEC-381 - Certificate trust changes

### ISSUE THREAD

**Issue by acdemyers** [OpenLiberty/docs#731]
Need to add documentation for new enhancement to setting up trust on SSL connections.

**Comment by acdemyers** [comment]
The new article for open liberty is attached.  
[trustedCerts.docx](https://github.com/OpenLiberty/docs/files/3741215/trustedCerts.docx)

**Comment by lauracowen** [comment]
The example config info should be considered for adding to: https://app.zenhub.com/workspaces/docs-5c7031f61d4580192beb4070/issues/openliberty/docs/631

The additional config option should be included automatically in the generated doc anyway.

**Comment by Charlotte-Holt** [comment]
The config example that @alaine provided is included in https://draft-openlibertyio.mybluemix.net/docs/20.0.0.11/reference/feature/transportSecurity-1.0.html.

**Comment by Rwalls1** [comment]
Example already added to doc in link referenced above, closing
