### ISSUE TITLE
Starting in 24.0.0.5 - a new *.pem.cer file is published for renewed cert.

### ISSUE THREAD

**Issue by cbridgha** [OpenLiberty/docs#7314]
Opened for Openliberty .io to edit the url...    
https://github.com/OpenLiberty/openliberty.io/issues/3726

The [page on OL](https://openliberty.io/docs/latest/verifying-package-signatures.html) doesn't include the link...  but does have the text showing the vert details....  maybe should update with the following:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            06:4b:92:a7:85:44:17:52:dd:6c:29:d0:40:cc:a3:0b
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = US, O = "DigiCert, Inc.", CN = DigiCert Trusted G4 Code Signing RSA4096 SHA384 2021 CA1
        Validity
            Not Before: May  8 00:00:00 2024 GMT
            Not After : May  8 23:59:59 2026 GMT
        Subject: C = US, ST = New York, L = Armonk, O = International Business Machines Corporation, CN = International Business Machines Corporation
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
                Modulus:
```

**Comment by dmuelle** [comment]
Hi @cbridgha - the cert example is now updated:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/verifying-package-signatures.html
