### ISSUE TITLE
Document -Duser.timezone=time_zone_code for a customer issue.

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#7320]
**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

To address a customer issue, make the following updates in https://openliberty.io/docs/latest/reference/config/server-configuration-overview.html#jvm-options

Add the line in bold:
Common uses of jvm.options files include:
Setting JVM memory limits
Enabling Java Agents that are provided by monitoring products
Setting Java System Properties
**Setting time zones**

Add the line in bold:
The jvm.options file format uses one line per JVM option, as shown in the following example:
-Xmx512m
-Dmy.system.prop=This is the value.
**-Duser.timezone=_time_zone_code_**

-------
Add the following text to https://openliberty.io/docs/latest/log-trace-configuration.html

You can use the user.timezone property to set the time zone for your application environments. Set the user.timezone property in the jvm.properties file. The updated time zone information is displayed in the messages.log file and the trace.log file. The following example shows how to set the time zone.
-Duser.timezone=time_zone_code

**Comment by dmuelle** [comment]
Hi @chirp1 - the draft is now updated with these changes

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/config/server-configuration-overview.html#jvm-options

if any further changes are needed, just let me know. Thanks

**Comment by chirp1** [comment]
@dmuelle Hi David, Thanks! The update looks good to me.

**Comment by Channyboy** [comment]
@dmuelle @chirp1 I think it would make sense to also update the log trace and configuration page? (i.e.,  https://openliberty.io/docs/latest/log-trace-configuration.html)

Similar to the work done for the KC update.

**Comment by dmuelle** [comment]
Hi @Channyboy - I added this example to the end of the first section, in the same place it appears in IBM Docs

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/log-trace-configuration.html
