### ISSUE TITLE
Document crac-1.4 feature and InstantOn support for springBoot-3.0 feature

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/docs#7331]
- [x] Add `springBoot-3.0` to list of supported InstantOn features in the docs
- [x] Add a feature page doc for the new `crac-1.4` feature

We need to add the `springBoot-3.0` feature the list of additional features supported by InstantOn at https://openliberty.io/docs/latest/instanton.html#supported-features

We could consider adding something to https://openliberty.io/docs/latest/deploy-spring-boot.html to mention the InstantOn support for Spring Boot 3.0.  But I think it is best left to the guide linked from that page.  I have issue https://github.com/OpenLiberty/guide-spring-boot/issues/169 open for that.  Otherwise we would have to add doc for containerizing SpringBoot applications in order to document how to use InstantOn with it.

I suggest we do add something like the following to `modules/reference/pages/feature/springBoot-3.0/description.adoc`

> The Spring Framework and Spring Boot support of Coordinated Restore at Checkpoint integrates with [Liberty InstantOn](https://openliberty.io/docs/latest/instanton.html) when using the [crac-1.4](https://openliberty.io/docs/latest/reference/feature/crac-1.4.html) feature.  The Spring support for checkpointing and restoring an application manages the lifecycle of resources such as socket, files and thread pools used by the application.  For more information see the Spring Boot documentation on [Checkpoint and Restore](https://docs.spring.io/spring-boot/docs/current/reference/html/deployment.html#deployment.efficient.checkpoint-restore) and the [Spring Framework Checkpoint and Restore support documentation](https://docs.spring.io/spring-framework/reference/6.1/integration/checkpoint-restore.html).

We also need to add a feature page doc for the new crac-1.4 feature.  Here is a draft to get started:

> Coordinated Restore at Checkpoint 1.4
> 
> This feature enables the org.crac Coordinated Restore at Checkpoint APIs.
> 
> The Liberty `crac-1.4` feature provides an implementation of the `org.crac` APIs that integrate with the [Liberty InstantOn](https://openliberty.io/docs/latest/instanton.html) support.
>
> The [org.crac](https://javadoc.io/doc/org.crac/crac/1.4.0/index.html) package provides APIs for receiving checkpoint/restore notifications. These notifications allow applications to perform actions before checkpointing an application process and after restoring the application process. For example, this allows Spring-based applications to support [Checkpoint and Restore](https://docs.spring.io/spring-framework/reference/6.1/integration/checkpoint-restore.html).  The use of `org.crac` is not limited to Spring-based applications.  Any application running on Liberty may choose to receive checkpoint/restore notifications by enabling the `crac-1.4` feature.
>

**Comment by tjwatson** [comment]
For Open Liberty epic https://github.com/OpenLiberty/open-liberty/issues/25594

**Comment by tjwatson** [comment]
One additional thing needs to be added to the `crac-1.4` feature doc about limitations on the [`Core.checkpointRestore()`](https://javadoc.io/static/org.crac/crac/1.4.0/org/crac/Core.html#checkpointRestore--) method.

> The Liberty InstantOn implementation of CRaC does not support the [`org.crac.Core.checkpointRestore()`](https://javadoc.io/static/org.crac/crac/1.4.0/org/crac/Core.html#checkpointRestore--) method. Applications that depend on CRaC to receive notifications of checkpoint/restore should use the Liberty InstantOn [`afterAppStart`](https://openliberty.io/docs/latest/instanton.html#beforeAppStart) option to checkpoint a Liberty application process.

**Comment by dmuelle** [comment]
- added sb3 to the [InstantOn feature list](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html#supported-features)
- added [Faster startup for Spring applications with Liberty InstantOn](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/springBoot-3.0.html#_faster_startup_for_spring_applications_with_liberty_instanton) section to the SB3 feature page
- created extended [description file for crac-1.4](https://github.com/OpenLiberty/docs/blob/draft/modules/reference/pages/feature/crac-1.4/description.adoc) but wont be able to review it in context until 24.0.0.6 autogen is added to `draft`, generally the week before EGa.

**Comment by dmuelle** [comment]
Hi @tjwatson the crac-1.4 draft page is now available for review

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/crac-1.4.html

other updates from this issue:
- added sb3 to the [InstantOn feature list](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html#supported-features)
- added [Faster startup for Spring applications with Liberty InstantOn](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/springBoot-3.0.html#_faster_startup_for_spring_applications_with_liberty_instanton) section to the SB3 feature page

If any further edits are needed, just let me know. Otherwise, you can sign off by adding the `technical reviewed` label to this issue. Thanks!

**Comment by tjwatson** [comment]
Thanks LGTM
