### ISSUE TITLE
When Liberty is configured with Trust Association Interceptor, 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#7339]
Issue Description:

When the TrustAssociationInterceptor calls InitialDirContext with the Java property java.naming.ldap.factory.socket set to a socket factory that is not LibertySSLSocketFactory (e.g., com.ibm.ws.ssl.LibertySSLSocketFactoryWrapper), a NoClassDefFoundException is thrown. This issue was very difficult to debug (security and classloader team)   

We would like this caution documented for OpenLiberty and WebSphere Liberty as well. It should be in the custom TAI development or configuration or troubleshooting section.

**Comment by dmuelle** [comment]
also check whether we should doc on https://www.ibm.com/docs/en/was-liberty/core?topic=liberty-configuring-tai

**Comment by ramkumar-k-9286** [comment]
Hi Hiroko @una-tapa 

Suggested edit done in OL:

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/troubleshooting.html

Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar.

CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Hi Hiroko @una-tapa 

Suggested corrections done in OL:

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/troubleshooting.html

Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar.

CC @dmuelle

**Comment by una-tapa** [comment]
Thanks, the change looks great!
