### ISSUE TITLE
Documentation updates for InstantOn Support for Jakarta Messaging #26039

### ISSUE THREAD

**Issue by dazavala** [OpenLiberty/docs#7340]
For Open-Liberty epic https://github.com/OpenLiberty/open-liberty/issues/26039.

- [x] Add Jakarta Messaging (`jms-2.0`, `messaging-3.0`), Connectors (`jca-1.7`, `connectors-2.0`, `connectors-2.1`), and Enterprise Beans Message-Driven Beans (`mdb-3.2`, `mdb-4.0`) features to the list of [Open Liberty InstantOn supported features](https://openliberty.io/docs/latest/instanton.html#supported-features) 
- [x] Add section for Jakarta Connectors feature limitations to [InstantOn limitations and known issues](https://openliberty.io/docs/latest/instanton-limitations.html) 
- [ ]  Possible mention in section [When to make a checkpoint: beforeAppStart or afterAppStart](https://openliberty.io/docs/latest/instanton.html#beforeAppStart)

**Comment by tjwatson** [comment]
I would like to understand and discuss the restrictions before adding them to the documentation.

**Comment by dmuelle** [comment]
added messaging features to [InstantOn features list](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton.html#supported-features) on draft

**Comment by dazavala** [comment]
@dmuelle Suggested new section content for Jakarta Connectors feature limitations in [InstantOn limitations and known issues](https://openliberty.io/docs/latest/instanton-limitations.html). Thinking the last sentence should bookend both limitation errors rather than appear once at the end of the section.

#### Jakarta Connectors Work Submission before checkpoint

Open Liberty InstantOn does not allow resource adapters to submit Work nor create Timer tasks (schedule periodic Work) before a checkpoint is performed for the application process. This scenario is possible if the resource adapter has [early startup code](https://openliberty.io/docs/latest/instanton.html#beforeAppStart) that attempts to submit Work or create a Timer using the bootstrap context facilities provided by the application server.

Consider the following resource adapter JavaBean code snippet. The `start()` method is invoked when the server starts the resource adapter, which occurs before the checkpoint when using the `afterAppStart` option.

```
public class StartupExample implements ResourceAdapter {
    BootstrapContext bootstrapCtx = null;

    @Override
    public void start(BootstrapContext ctx) {
        bootstrapCtx = ctx;
        WorkManager workMgr = bootstrapCtx.getWorkManager();
        ...

        // work submission is not allowed before checkpoint
        try {
            workMgr.scheduleWork(new ExampleWork());  // same for doWork() and startWork()
        } catch (WorkRejectedException wre) {}
 
        // timer creation is not allowed before checkpoint 
        try {
            Timer timer = bootstrapCtx.createTimer();
        } (UnavailableException ue) {}
        ...
     }
```
##### Submit Work 
When a resource adapter attempts to submit Work before checkpoint, the work manager will throw a `WorkRejectedException` with message `J2CA8602E` that identifies the resource adapter and the rejected work instance:

> J2CA8602E: The `ExampleWork` work that was submitted by the `StartupExample` resource adapter was rejected during the server checkpoint request.

The server then fails the checkpoint and logs the following error:

> J2CA8601E: The server checkpoint request failed because the `StartupExample` resource adapter submitted work `ExampleWork`.

##### Create a Timer
When a resource adapter attempts to create a Timer before checkpoint, the `createTimer()`method will throw an `UnavailableException` with message `J2CA8512E` that identifies the resource adapter:

> J2CA8512E: A timer could not be created for the `StartupExample` resource adapter during the server checkpoint request..

The server then fails the checkpoint and logs the following error:

> J2CA8511E: The server checkpoint request failed because the `StartupExample` resource adapter created a timer.

You can avoid these failures by using the` beforeAppStart` option.

**Comment by dazavala** [comment]
@dmueller Regarding "Possible mention in section [When to make a checkpoint: beforeAppStart or afterAppStart](https://openliberty.io/docs/latest/instanton.html#beforeAppStart)," I think you and Tom already covered the matter with the point below and no further changes are necessary.  Submitting/scheduling work for a remote resource assumes the resource is accessible.  We'd be repeating ourselves.

- Accessing a remote resource, such as a database. The correct data source is unlikely to be available to connect to during an application container build.

**Comment by dazavala** [comment]
@tjwatson Suggested changes to InstantOn user doc w.r.t. Jakarta Connectors limitations.

**Comment by dmuelle** [comment]
Hi @dazavala - the limitations draft is updated with this info:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton-limitations.html#connectors

If any further edits are needed, just let me know. Thanks!

**Comment by dazavala** [comment]
@dmuelle Definitely like the improvements. I found some revisions:

- [x]  In the draft the phrase **`createTimer() method throws an UnavailableException with the following J2CA8512E`** does not render properly.  Here's how it should look.

  When a resource adapter attempts to create a timer before checkpoint, **the `createTimer()` method throws an `UnavailableException` with the following `J2CA8512E`** message that identifies the resource adapter:

- [x] Remove the extra period from the end of the following error message example.

  > J2CA8512E: A timer could not be created for the `StartupExample` resource adapter during the server checkpoint request..

 - [x] OPTIONAL Looking at other message examples, you can delete the surrounding backquote characters from the error message arguments `ExampleWork` and `StartupExaxmple`.  I suspect the backquotes were transcribed from the PR text.  That said, all instances of the messages arguments are perfect.  If you like the backquotes, keep them.

**Comment by dmuelle** [comment]
Thanks @dazavala - I made those updates

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/instanton-limitations.html#connectors

If any further edits are needed, just let me know. If not, you can sign off by adding the `technical reviewed` label to this issue and the update will publish with the 24.0.0.6 doc release.

**Comment by dazavala** [comment]
Looking good, @dmuelle.  Labeled as directed.  Thanks!

**Comment by dazavala** [comment]
Hello @dmuelle. May I close this issue?  As far as I know the work is complete.

**Comment by dmuelle** [comment]
@dazavala - the work is complete but I keep the issues open until the files are committed to the vNext branch, which should happen tomorrow. I'll configure that PR to close this issue on merge. Thanks!
