### ISSUE TITLE
4413a

### ISSUE THREAD

**Issue by 4413a** [OpenLiberty/docs#7361]
Document: Choose your own monitoring tools with MicroProfile Metrics
http://openliberty.io/github.com.4413a/docs/latest/micrometer-metrics.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

**Comment by dmuelle** [comment]
Hi @4413a - can ypu tell us more about the problem you are having with this page?
