### ISSUE TITLE
the springBoot-3.0 feature page references the jsp-2.3 when it should reference the pages-3.0 feature

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/docs#7362]
[**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**](https://openliberty.io/docs/latest/reference/feature/springBoot-3.0.html)

The table for web and webflux reference `jsp-2.3` but it should instead reference `pages-3.0`

**Comment by dmuelle** [comment]
Hi @tjwatson - this fix is now on draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/springBoot-3.0.html
