### ISSUE TITLE
Make it easy for customers to find ssoRequiresSSL flag 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#7370]
This issue comes from our support team serviceability initiative.  

One of the frequently asked questions from customers is "what flag to set to secure the LTPA cookie in Liberty env?" 

Although the information can be found in the stackovervlow,
https://stackoverflow.com/questions/49119765/securing-ltpa-token-in-websphere-liberty-profile
```
Adding <webAppSecurity ssoRequiresSSL="true"/> to the server.xml file should do it.
```

**Comment by dmuelle** [comment]
We have this documented in OL under [Server configuration security hardening: Best practices](https://openliberty.io/docs/latest/server-configuration-hardening.html) and  [network hardening: LTPA best practices](https://openliberty.io/docs/latest/network-hardening.html#ltpa). I will links to it to [Single sign-on (SSO):LTPA](https://openliberty.io/docs/latest/single-sign-on.html#_ltpa) and the [LTPA examples on the apSecurity feature page](https://openliberty.io/docs/latest/reference/feature/appSecurity-5.0.html#ltpa)

**Comment by dmuelle** [comment]
Hi @una-tapa - I added links to our existing [LTPA best practices info](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/network-hardening.html#ltpa), which includes the `ssoRequiresSSL="true"` setting, to the [LTPA section of the single sign on page](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/single-sign-on.html#_ltpa) and the LTPA examples on the [App Security feature](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/appSecurity-5.0.html#ltpa) page. WL updates are handled in a separate issue. If any further edits are needed for the Open Liberty docs, just let me know. Thanks!
