### ISSUE TITLE
Fix JDBC trace doc for DB2 #7401

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#7402]
issue to track edits for #7401 and deliver to prod in 24.0.0.7

**Comment by dmuelle** [comment]
Hi @KyleAure - these updates are now available for review at

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/jdbc-tracing.html

If the changes look good, would you open a PR from your branch to `staging` and add me as a reviewer? Once that is merged, I'll get the topic queued to publish with 24.007. Thanks!

**Comment by KyleAure** [comment]
Done.
