### ISSUE TITLE
We need to document the property com.ibm.websphere.jpa.hibernate-cdi-compatibility

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/docs#7411]
Hibernate requires us to implement a non-spec interface called ExtendedBeanManager to integrate it into Liberty. Because this interface is not part of the spec it took a very convoluted piece of code to support it. Therefore we required the system property `com.ibm.websphere.jpa.hibernate-cdi-compatibility` to be set before that code is enabled.

We need to document that when using Hibernate with Liberty and CDI that property is required.

**Comment by dmuelle** [comment]
Hi @benjamin-confino - the draft is updated per our slack discussion:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/persistenceContainer-3.1.html#_configure_an_alternative_jpa_implementation

When you have a chance, would you review the update and let me know if any further edits are needed? If not, you can add the `technical reviewed` label to this issue to sign off and the update will publish with the next docs release. Thanks!
