### ISSUE TITLE
Add link to ICR page in GitHub repo

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/docs#7428]
Document: Open Liberty container images
http://openliberty.io/docs/latest/container-images.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

Add the following after the sentence "For example, if 23.0.0.12 is a recent quarterly release, you can pull an image that includes the 23.0.0.12 release with an OpenJ9 distribution of Java 8 by specifying the 23.0.0.12-full-java8-openj9-ubi tag.":

See the [IBM Container Registry (ICR) page on the Open Liberty GitHub repository](https://www.ibm.com/links?url=https%3A%2F%2Fgithub.com%2FOpenLiberty%2Fci.docker%2Fblob%2Fmaster%2Fdocs%2Ficr-images.md) for the full list of supported Open Liberty container images.

**Comment by ramkumar-k-9286** [comment]
Hi Leo @leochr 

The suggested change has been made.

Draft Link: 
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

Please review the same and add the `Developer Reviewed` label if you are satisfied with the change.

Regards,
Ramkumar.

CC @dmuelle

**Comment by leochr** [comment]
@ramkumar-k-9286 Thanks for the update. On second thought, I believe it'll be better to add it after this sentence instead:
"For more information about these tag values, see the [Container image tags naming conventions](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html#tags) section."

**Comment by ramkumar-k-9286** [comment]
Hi Leo @leochr

I have moved the information as per your suggestion.

Draft Link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html

Please review the same and add the `Developer Reviewed` label if you are satisfied with the change.

Regards,
Ramkumar.

CC @dmuelle

**Comment by leochr** [comment]
@ramkumar-k-9286 Looks good. Thank you
