### ISSUE TITLE
FeatureUtility enable proxy exclusion list

### ISSUE THREAD

**Issue by jjiwooLim** [OpenLiberty/docs#7442]
### Feature epic details 

- For the title of this issue, type: Implement proxy exclusion list in featureUtility
- Link to development epic: https://github.com/OpenLiberty/open-liberty/issues/27508
- Target GA release: 24.0.0.12

### Operating systems

Does the documentation apply to all operating systems? 
- [ X] Yes  
- [ ] No; specify operating systems: ______

### Summary
Provide a concise summary of your feature. What is the update, why does it matter, and to whom? What do 80% of target users need to know to be most easily productive using your runtime update?

FeatureUtility can connect to Maven repository using proxy. However, users may not want to use proxy for some Maven repository even when they configured proxy settings. Common use case would be when they want connect to internal repository that doesn't require proxy.

### Configuration
List any new or changed properties, parameters, elements, attributes, etc. Include default values and configuration examples where relevant:

### Updates to existing  topics
To update existing topics, specify a link to the topics that are affected.  Include a copy of the current text and the exact text to which it will change. For example: Change ABC to XYZ

https://openliberty.io/docs/latest/reference/command/featureUtility-commands.html

Add to the end of the table
| Environment variable  |  Corresponding properties |  Description |
----------------| ----------- | -----------
| `no_proxy` | `http.nonProxyHosts` | This is a list of patterns separated by `\|` and `,`. The patterns may start or end with a '*' for wildcards. Any host matching one of these patterns will be reached through a direct connection instead of going through a proxy. |

**Comment by dmuelle** [comment]
Hi @jjiwooLim - when you have a projected GA release for this epic, please add the corresponding version label to this issue so we can prioritize it. Let me know if you have any questions. Thanks!

**Comment by dmuelle** [comment]
Hi @jjiwooLim - this update is ready for review:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-commands.html

One thing I want to confirm is whether the 3 http envars at the end of the table should be all caps like the other ones. I thought environment variables were always specified in all caps but maybe this is an exception?

**Comment by jjiwooLim** [comment]
Hi, yes that's the usual way but we are following the convention used by featureUtility. It used the lowercase for proxy environment variables.

**Comment by jjiwooLim** [comment]
This is a list of patterns separated by `| (bar)` and `, (comma)` -> Period is not part of the separator. Only bar and comma.

**Comment by dmuelle** [comment]
Thanks for reviewing @jjiwooLim - I've updated the draft per your feedback:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/featureUtility-commands.html

If any further changes are needed, just let me know. If not, you can sign off by adding the `technical reviewed` label to this issue. Thanks!
