### ISSUE TITLE
Document the image refresh cycle

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/docs#7496]
Document: Open Liberty container images
http://openliberty.io/docs/latest/container-images.html

**Please describe the problem you are having with the documentation. Is information missing, inaccurate, or unclear? Tell us about the context where you encountered the problem so we can understand how to address it.**

Add the following prior to the sentence "For more information on the full list of supported Open Liberty container images, see ....":

_After the initial release of the Liberty container images, they are refreshed regularly (every 1-2 weeks) to include fixes for the operating system (OS) and Java._

**Comment by ramkumar-k-9286** [comment]
Hi Leo @leochr 

Suggested corrections are done.

Draft link:
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/container-images.html


Please add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar.

CC @dmuelle

**Comment by leochr** [comment]
@ramkumar-k-9286 Looks good. Thank you.
