### ISSUE TITLE
The server package command doc isn't in the OL Docs Server Commands vertical navigation

### ISSUE THREAD

**Issue by helyarp** [OpenLiberty/docs#75]
To recreate, go to the OL Docs **Reference > Server Commands** page at https://www.openliberty.io/docs/ref/command/#server-commands.html. Notice that the list of commands in the navigation tree doesn't include **package**.

The package command info is partly available by going to the Overview at https://www.openliberty.io/docs/ref/command/#server-commands.html and scrolling to the package info:

**Package the server**
Run the **server package** command to package a server, its resources, and applications in a ZIP file that you can store, distribute, or deploy to a different location.
`server package myserver --include=all`

The **server package** link shows some of the package command info but `server-package.adoc` doesn't appear to have been correctly transformed to `server-package.html` (see https://www.openliberty.io/docs/ref/command/#server-package.html) and it's missing from the vertical navigation tree.

**Comment by helyarp** [comment]
Hi, why was this issue closed? The problem still exists at https://www.openliberty.io/docs/ref/command/?

**Comment by ellenwyllie** [comment]
@helyarp Hi, I found a fix for this issue and it has been merged into the development branch. However the changes are not yet visible on openliberty.io so I may have closed the issue a little prematurely
