### ISSUE TITLE
Create build for post-Oct RHR docs

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#754]
Create build config for RHR longer-term which does not require any RHR-specific OL topics; ie all doc content is topics (or guides in certain cases) that are already built for OL docs.

Base the information architecture of the built topics on the table here: https://ibm.box.com/s/xgr9kn0h6edydkqprj1ko2k2mlcbqoru

Put these build files in PurpleLiberty docs repo.

Ensure the built output is coherent and usable.

**Comment by chirp1** [comment]
Until the macro issue is resolved for redirecting links in topics/guides, we can't pull in topics that have the macros.

**Comment by Charlotte-Holt** [comment]
Blocked by https://github.com/OpenLiberty/openliberty.io/issues/1573

**Comment by dmuelle** [comment]
Demo build from 3.13 to test for errors, uses placeholder statement for docs that are not yet complete
[html-single.zip](https://github.com/OpenLiberty/docs/files/4351363/html-single.zip)

**Comment by Charlotte-Holt** [comment]
OpenLiberty/openliberty.io#1573 is closed (which was blocking this). We'll be keeping copies of the files that go in the RHR doc in the PurpleLiberty repo rather than building from the OL docs repo.
