### ISSUE TITLE
Add ft Metrics to the Telemetry Metrics list

### ISSUE THREAD

**Issue by benjamin-confino** [OpenLiberty/docs#7581]
https://github.com/OpenLiberty/docs/blob/vNext/modules/ROOT/pages/mptelemetry-metrics-list.adoc does not include ft.metrics so they need to be added.

**Comment by dmuelle** [comment]
for OL epic: https://github.com/OpenLiberty/open-liberty/issues/27107

**Comment by dmuelle** [comment]
Hi @benjamin-confino - would you mind doing a quick check of https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/mptelemetry-metrics-list.html and if looks ok, add the `technical reviewed` label to this issue?

Thanks!
