### ISSUE TITLE
Liberty FIPS support requires IBM Java or Semeru Java 

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#7599]
Per our team's conversation with both Liberty and Java architects,  it has been confirmed that Liberty's FIPS function requires security providers from either IBM Java or Semeru Java.  
Please help update relevant documentation. Thank you in advance. 

[Internal discussion](https://ibm-cloud.slack.com/archives/C324NP6H5/p1727705371180799?thread_ts=1727431143.349919&cid=C324NP6H5) 

I plan to chat with the doc team soon.

**Comment by dmuelle** [comment]
[STIGDraft_For_DISASubmission.docx](https://github.com/user-attachments/files/17317360/STIGDraft_For_DISASubmission.docx)

**Comment by dmuelle** [comment]
we will update the [Run FIPS-compliant applications](https://openliberty.io/docs/latest/enable-fips.html) page to match what is documented for Semeru in the attached draft

**Comment by dmuelle** [comment]
DISA tracking number RITMU0136962

**Comment by dmuelle** [comment]
Hi @una-tapa - when you have a chance, please review the updated Open Liberty FIPS doc draft:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/enable-fips.html

Thanks!

**Comment by una-tapa** [comment]
Looks great.  Thank you, @dmuelle
