### ISSUE TITLE
Update versionless feature list for 240010

### ISSUE THREAD

**Issue by jhanders34** [OpenLiberty/docs#7600]
Update https://openliberty.io/docs/latest/reference/feature/versionless-features.html#mp with the standalone MP features listed in OpenLiberty/open-liberty#29749

**Comment by dmuelle** [comment]
We do not need to manually update the Feature tables as Harry's commit to automate them went in for 24.0.0.10. But- Im going to repurpose this issue to track some manual edits to those tables that we will incorporate into the generator in the next release.
