### ISSUE TITLE
Update securityUtility encode docs to escape special characters

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#7623]
The [encode](https://openliberty.io/docs/latest/reference/command/securityUtility-encode.html) doc needs to mention that you must escape special characters in passwords that you want to encode. Currently, we only mention that strings with spaces must be enclosed in quotes.

Because special and escape characters differ by OS, we cant exhaustively list all possible characters. Instead, add a section to the end of the doc to show how to check whether the characters are properly escaped.

In the command prompt, type "echo" followed by the password and see where the output started to differ.  That's where we want the user to place the escape character.  The following is the example on Ubuntu.  

```
$ **echo pa$$word**
pa683word  <===== OK until "pa"
$ **echo pa\$$word**    <== Added escape after "pa"
pa$    <=== OK until "pa$" 
$ **echo pa\$\$word**    <== Added escape after "pa$" 
pa$$word  <== Yes, this is the password I want securityUtility to encode
```

**Comment by dmuelle** [comment]
https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/securityUtility-encode.html

**Comment by ramkumar-k-9286** [comment]
Peer Review
---

`pa$$W0rd` ->  `pa$$Word` ( I am not sure if this was a mistake `0` (zero) used instead of `o`).

---
`pa\$\$W0rd` -> `pa\$\$Word`  ( I am not sure if this was a mistake `0` (zero) used instead of `o`).

---

Will inserting a space in the code block be better for visual clarity?

**Comment by dmuelle** [comment]
Thanks @ramkumar-k-9286 - draft is updated:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/command/securityUtility-encode.html
