### ISSUE TITLE
MicroProfile Rest Client 4.0 ID

### ISSUE THREAD

**Issue by jim-krueger** [OpenLiberty/docs#7624]
**REST clients page changes**
The [MicroProfile Rest Client](https://openliberty.io/docs/latest/rest-clients.html#_microprofile_rest_client) section of the [REST clients](https://openliberty.io/docs/latest/rest-clients.html) page requires the following updates for Microprofile Rest Client 4.0 as part of MicroProfile 7.0:

**This is the current last paragraph:**
`If you update your server from an earlier version of the [MicroProfile REST Client](https://openliberty.io/docs/latest/reference/feature/mpRestClient.html) to version 3.0, changes in API behavior might require you to update your application code. For more information, see [Differences between MicroProfile REST Client 3.0 and 2.0](https://openliberty.io/docs/latest/reference/diff/mp-41-50-diff.html#rc).`

**Here is an updated version with recommended changes:**
`If you update your server from a version of the [MicroProfile REST Client](https://openliberty.io/docs/latest/reference/feature/mpRestClient.html) prior to version 3.0 to version 3.0 or higher, changes in API behavior might require you to update your application code. For more information, see [Differences between MicroProfile REST Client 3.0 and 2.0](https://openliberty.io/docs/latest/reference/diff/mp-41-50-diff.html#rc).`

`In addition, If you update your server to version 4.0 of the [MicroProfile REST Client](https://openliberty.io/docs/latest/reference/feature/mpRestClient.html), see [Differences between MicroProfile REST Client 4.0 and 3.0]().`.  _<This will need a URL when https://github.com/OpenLiberty/docs/issues/7610 is completed>_

**MicroProfile Rest Client page changes**

- The URL for this page will need to change from https://openliberty.io/docs/latest/reference/feature/mpRestClient-3.0.html to https://openliberty.io/docs/latest/reference/feature/mpRestClient-4.0.html.
- The title will need to add 4.0 to the front.
- The "Enabling this feature" section need to change to indicate `<feature>mpRestClient-4.0</feature>`
- The "Features that this feature enables" needs to change to list the following features (with appropriate url changes):
```
. jsonp-2.1
. mpConfig-3.1
```

- Add `microProfile-7.0` to the "Platform Versions" and "Features that enable this feature" sections
- Change"Developing a feature that depends on this feature" section to list `io.openliberty.mpRestClient-4.0` instead of 3.0.

**Comment by ramkumar-k-9286** [comment]
Hi @jim-krueger 

Suggested changes made to the page.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/rest-clients.html

One link will currently only work once we add the Differences between MicroProfile 7.0 and 6.1 page ( https://github.com/OpenLiberty/docs/issues/7610 )


Regards,
Ramkumar.


CC @dmuelle

**Comment by ramkumar-k-9286** [comment]
Hi @jim-krueger 

Suggested changes made to the page.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/rest-clients.html

Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.


Regards,
Ramkumar.


CC @dmuelle

**Comment by jim-krueger** [comment]
Hi @ramkumar-k-9286 
So far only the first changes I requested have. been made.  Please see the second part: 

MicroProfile Rest Client page changes

The URL for this page will need to change from https://openliberty.io/docs/latest/reference/feature/mpRestClient-3.0.html to https://openliberty.io/docs/latest/reference/feature/mpRestClient-4.0.html.
The title will need to add 4.0 to the front.
The "Enabling this feature" section need to change to indicate <feature>mpRestClient-4.0</feature>
The "Features that this feature enables" needs to change to list the following features (with appropriate url changes):
. jsonp-2.1
. mpConfig-3.1
Add microProfile-7.0 to the "Platform Versions" and "Features that enable this feature" sections
Change"Developing a feature that depends on this feature" section to list io.openliberty.mpRestClient-4.0 instead of 3.0.

**Comment by ramkumar-k-9286** [comment]
Hi @jim-krueger 

Those feature pages are autogenerated and the MPRC 4.0 page will be available after sometime between GM and GA and will include the details you are asking for without needing any manual edits from the docs team. 

We can share the autogenerated page once it gets generated.

Regards,
Ramkumar

CC @dmuelle

**Comment by jim-krueger** [comment]
@ramkumar-k-9286 Thanks.  I have placed the label you requested.   Thanks!

**Comment by dmuelle** [comment]
LGTM

**Comment by dmuelle** [comment]
Hi @jim-krueger - I notice in the main "Differences between.." topic, we are pointing to examples in the spec for multipart form data. Are there functional changes to multipart form data in MPRC 4.0? Or is it just new examples in the spec?

We have a topic about multipart form data: [Send and receive multipart/form-data parts](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/send-receive-multipart-jaxrs.html)

Does this page need updates for MPRC 4.0? If the new examples in the spec are helpful, we should add them to this page.

**Comment by jim-krueger** [comment]
Hi @dmuelle, Yes, for MPRC 4.0 these are just examples resulting from MPRC moving to the EE10 version of RESTful Web Services.   

Also, yes, we probably should update [Send and receive multipart/form-data parts](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/send-receive-multipart-jaxrs.html), but I'd associate that more closely with RESTful Web Services 4.0, that will be part of EE11.   Currently that document states: 
`In this version and later, this support is provided by the EntityPart API that is defined in the RESTful Web Services specification. For more information, see [section 3.5.2 of the Jakarta Restful Web Services specification].(https://jakarta.ee/specifications/restful-ws/3.1/jakarta-restful-ws-spec-3.1.html#consuming_multipart_formdata).` which covers us until then.

Also, I think adding the examples from the spec here would be a fine thing to do if you want.    The only advantage I can see to using the link instead is if the spec examples get changed in the future (something I don't expect will happen).
