### ISSUE TITLE
security hardening config isn't xml formatted

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#7627]
The document [here ](https://github.com/OpenLiberty/docs/blob/vNext/modules/ROOT/pages/server-configuration-hardening.adoc)mentions 3 bits of server config, but doesn't show it as valid xml. It says:

```
* Add the `webAppSecurity ssoRequiresSSL="true"` statement to the `server.xml` file.
* Add the `webAppSecurity httpOnlyCookies="true"` statement to the `server.xml` file.
* Add the `httpOptions removeServerHeader="true"` statement to the `server.xml` file.
* Add the `webContainer disableXPoweredBy="true"` statement to the `server.xml` file.
```

and I think it would be better if it read:

```
* Add the `<webAppSecurity ssoRequiresSSL="true" />` statement to the `server.xml` file.
* Add the `<webAppSecurity httpOnlyCookies="true" />` statement to the `server.xml` file.
* Add the `<httpOptions removeServerHeader="true" />` statement to the `server.xml` file.
* Add the `<webContainer disableXPoweredBy="true" />` statement to the `server.xml` file.
```

**Comment by dmuelle** [comment]
Is there any reason we shouldn't display these as a block to reduce redundancy? ie

> Add the following declarations to your `server.xml` file:

```xml
<webAppSecurity ssoRequiresSSL="true" httpOnlyCookies="true />
<httpOptions removeServerHeader="true" />
<webContainer disableXPoweredBy="true" />
```

**Comment by ramkumar-k-9286** [comment]
Hi @NottyCode 

Suggested changes have been made.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/server-configuration-hardening.html

Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar

CC @dmuelle

**Comment by NottyCode** [comment]
I would expect the text to stop be a bullet point, but it isn't.

**Comment by ramkumar-k-9286** [comment]
Hi @NottyCode

Corrections were made as per your comment.

Draft link: 

[Server configuration security hardening](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/server-configuration-hardening.html)

Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar

CC @dmuelle

**Comment by NottyCode** [comment]
LGTM
