### ISSUE TITLE
Remove 3.0  from "Servlet 3.0 APIs" in the audit event description  

### ISSUE THREAD

**Issue by una-tapa** [OpenLiberty/docs#7629]
In the following documentation, 
https://openliberty.io/docs/latest/audit-log-events-list-cadf.html#_security_api_authn
https://openliberty.io/docs/latest/json-log-events-list.html#_supported_audit_events_and_their_audit_data

Please remove 3.0 from "Servlet 3.0 APIs" to make it clear that the audit events applies to all servlet releases after 3.0 (4.0+) 

Current Description: 
> You can use the SECURITY_API_AUTHN event to capture the audit information from the login and authentication for servlet 3.0 APIs. The following table provides the fields for the SECURITY_API_AUTHN event and a description of each field.

When this issue is addressed, I would like to see.. 
> You can use the SECURITY_API_AUTHN event to capture the audit information from the login and authentication for servlet APIs. The following table provides the fields for the SECURITY_API_AUTHN event and a description of each field.

I got @volosied and @jhanders34 's assistance  ([private link](https://ibm-cloud.slack.com/archives/C30PFLG8Z/p1728603830848349?thread_ts=1728586932.093139&cid=C30PFLG8Z)) to confirm that _the audit tests cover the EE 6 through 10 features to verify that the audits are correctly processed and E11 will also be added soon._

**Comment by ramkumar-k-9286** [comment]
Hi @una-tapa 

Suggested corrections have been made.

Draft links:

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/audit-log-events-list-cadf.html#_security_api_authn

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/json-log-events-list.html#_supported_audit_events_and_their_audit_data


Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar.


CC @dmuelle

**Comment by una-tapa** [comment]
@ramkumar-k-9286 

Thank you for your help with the update.

I noticed that when searching for "servlet" on the pages, there are still references to the functionality being limited to Servlet 3.0. Since the content applies to versions 4.0, 5.0, 6.0, and beyond, we don't want to restrict it to 3.0. Could you please review the pages and remove all mentions of specific servlet versions?

I apologize for initially requesting changes to just one paragraph. Thanks again for your assistance.

**Comment by ramkumar-k-9286** [comment]
Hi @una-tapa

Suggested corrections have been made.

Draft links:

[Audit log events reference list (CADF format)](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/audit-log-events-list-cadf.html#_security_api_authn)

[JSON log events reference list](https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/json-log-events-list.html#_supported_audit_events_and_their_audit_data)

Please review the same and add the `Developer Reviewed` label if you are satisfied with the changes.

Regards,
Ramkumar.

CC @dmuelle

**Comment by una-tapa** [comment]
Looks great!  Thanks @ramkumar-k-9286
