### ISSUE TITLE
MicroProfile 3.2 ID

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/docs#763]
We need to update a couple of docs to include MicroProfile 3.2.
e.g. the addition of the 3.2 java doc - https://openliberty.io/docs/ref/microprofile/

This is part of OpenLiberty/open-liberty#8622

**Comment by tevans78** [comment]
This is part of https://github.com/OpenLiberty/open-liberty/issues/8622

**Comment by tevans78** [comment]
There may also be some updates required on openliberty.io. e.g. the addition of the 3.2 java doc - https://openliberty.io/docs/ref/microprofile/

**Comment by chirp1** [comment]
From discussions with Tom, it seems that the MP topic in OL doesn't need further updating for MP 3.2.  Just the javadoc would need updating, which the developer would address.

**Comment by lauracowen** [comment]
Adding this to the backlog to check whether anything needs to be done to the existing topic that gives an overview of MicroProfile features (there may not but someone should check):
https://www.openliberty.io/docs/ref/general/#microprofile.html

**Comment by dmuelle** [comment]
@lauracowen I don't see anything that needs to be updated for 3.2 on https://www.openliberty.io/docs/ref/general/#microprofile.html
There is no mention of specific versions on the page and the 3.2 updates to  Health and Metrics are m ore granular than anything that is summarized here. Everything that is in place is still correct and up-to-date. The page already mentions Jaeger for open tracing.

let me know if this issue needs anything further or is clear to close- thanks!

**Comment by lauracowen** [comment]
Sounds good. Happy to close then.
