### ISSUE TITLE
Update removal notice for Java SE 11 support from 26.0.0.10 to 27.0.0.10

### ISSUE THREAD

**Issue by ramkumar-k-9286** [OpenLiberty/docs#7634]
Changes related to WL issue [#4037](https://github.ibm.com/websphere/liberty-docs/issues/4037)

The [Java SE support page on openliberty.io](https://openliberty.io/docs/latest/java-se.html) should have its "Supported Java SE releases" table updated.

**Comment by ramkumar-k-9286** [comment]
Hi @dmuelle 

Updated removal notice for Java SE 11 support from 26.0.0.10 to 27.0.0.10.

Draft link: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/java-se.html

Regards,
Ramkumar.

**Comment by dmuelle** [comment]
LGTM- you can send to staging whenever you're ready
