### ISSUE TITLE
MicroProfile config reference doc should be in reference section

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/docs#7656]
This [page](https://openliberty.io/docs/latest/microprofile-config-properties.html) should be in the reference section and not the development section.

**Comment by dmuelle** [comment]
MicroProfile config properties topic is moved to reference section as of 24.0.0.11 release

https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/microprofile-config-properties.html
