### ISSUE TITLE
Update documentation for mpMetrics-2.0 and mpMetrics-2.2

### ISSUE THREAD

**Issue by Yushan-Lin** [OpenLiberty/docs#768]
Update https://openliberty.io/docs/ref/general/#metrics-catalog.html:
For the reference list, rename the column MPMETRICS-2.0 NAME to MPMETRICS-2.0/2.2 NAME.
Change the above paragraph to:
Some metric names changed between MicroProfile Metrics 1.1 and MicroProfile Metrics 2.0/2.2. The following table lists the mpMetrics-2.0/mpMetrics-2.2 metric names and the corresponding mpMetrics-1.1 metric names. It also lists the metric types, metric units, and descriptions of all metrics that are available for Open Liberty:

Create another page similar to https://openliberty.io/docs/ref/feature/#mpMetrics-2.0.html and https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.liberty.autogen.nd.doc/ae/rwlp_feature_mpMetrics-2.0.html but for 2.2:

MicroProfile Metrics 2.2

This feature provides support for the Eclipse MicroProfile Metrics 2.2 specification for enterprise Java.
Enabling this feature

To enable the MicroProfile Metrics 2.2 feature, add the following element declaration into your server.xml file, inside the featureManager element:
mpMetrics-2.2

Feature configuration elements
Same as 2.0
Stable API packages provided by this feature
Same as 2.0
Features that this feature enables
Same as 2.0
Supported Java versions
Same as 2.0
Features that enable this feature
microProfile-3.2

Developing a feature that depends on this feature
com.ibm.websphere.appserver.mpMetrics-2.2; type="osgi.subsystem.feature"

**Comment by Yushan-Lin** [comment]
WebSphere Liberty: https://github.ibm.com/was-liberty/liberty-docs/issues/1648

**Comment by lauracowen** [comment]
Only the first request is valid in this:

Comment 1) I think "MicroProfile Metrics 2.x" might be better than trying to keep the version numbers updated. Does that seem fair?

Comment 2) The reference topic you link to is automatically generated so that does not require ID to create.

**Comment by Yushan-Lin** [comment]
@lauracowen Comment 1) That sounds good

**Comment by Charlotte-Holt** [comment]
This is live at https://openliberty.io/docs/ref/general/#metrics-catalog.html and https://openliberty.io/docs/ref/general/#metrics1.1-list.html. Closing this issue.
