### ISSUE TITLE
Jakartaee-8.0 Platform for Versionless Features

### ISSUE THREAD

**Issue by rsherget** [OpenLiberty/docs#7691]
For https://github.com/OpenLiberty/open-liberty/issues/30009

Users can now specify Jakartaee-8.0 as a platform with the `<platform>` element in the feature manager. When used, the features will resolve the same as if the user had specified Javaee-8.0 as the platform.

**Comment by hlhoots** [comment]
@dmuelle let me know the content and location to add it, and I will try to get it done this week.

**Comment by dmuelle** [comment]
Hi @hlhoots - I think we'd want to duplicate [this table from the Java EE page](https://github.com/OpenLiberty/docs-generated/blob/vNext/modules/reference/pages/platform/JavaEE.adoc#java-ee-80) to the end of the [Jakarta EE page](https://github.com/OpenLiberty/docs-generated/blob/vNext/modules/reference/pages/platform/JakartaEE.adoc) and add the corresponding heading, platform name, and anchor link (at top of page).

IIRC - Jakarta EE 8 uses the same feature names as Java EE 8? If so, the table itself shouldn't need any edits.

**Comment by hlhoots** [comment]
@dmuelle the changes we discussed have been completed and merged.
