### ISSUE TITLE
Document the MicroProfile version compatibility for MpTelemetry 2.0

### ISSUE THREAD

**Issue by Yas-Franco** [OpenLiberty/docs#7745]
MicroProfile Telemetry 2.0 is compatible with the following MicroProfile and Jakarta versions: 

MicroProfile 6.1 (Jakarta EE10) 
Microprofile 5.0 (Jakarta EE9) 
MicroProfile 4.1 (Jakarta EE8)
MicroProfile 1.4 (Jakarta EE7) 
 
 The compatibility is not documented for the feature

**Comment by dmuelle** [comment]
Hi @yasmin-aumeeruddy, I updated the feature page to clarify this info: https://docs-draft-openlibertyio.mqj6zf7jocq.us-south.codeengine.appdomain.cloud/docs/latest/reference/feature/mpTelemetry-2.0.html

**Comment by Yas-Franco** [comment]
@dmuelle  That looks good. Thank you
