### ISSUE TITLE
Document the webModuleClassPathLoader attribute for class loading

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/docs#7772]
The auto-generated documentation for the [enterpriseApplication](https://openliberty.io/docs/latest/reference/config/enterpriseApplication.html) will contain the following descriptions for the new `webModuleClassPathLoader` attribute:

Name: `webModuleClassPathLoader`
Type: `war` or `ear`
Default: `war`
Description:
> This attribute defines the class loader that is used for JARs that are referenced by web application Class-Path headers.
> **war**
> Use the web application class loader for the JARs that are referenced by a web application Class-Path header.
> **ear**
> Use the parent enterprise application class loader for the JARs that are referenced by a web application Class-Path header.

We should consider adding a new section to the [Class loader configuration](https://openliberty.io/docs/latest/class-loader-library-config.html) page that gives more details like the [beta-blog](https://openliberty.io/blog/2024/10/22/24.0.0.11-beta.html#class) did for the option:

**Comment by dmuelle** [comment]
for epic https://github.com/OpenLiberty/open-liberty/issues/28110

**Comment by dmuelle** [comment]
moved to WL backlog
