### ISSUE TITLE
Options for the server start command are not documented.

### ISSUE THREAD

**Issue by chirp1** [OpenLiberty/docs#788]
Options are documented here for the server stop command: https://openliberty.io/docs/ref/command/#server-stop.html

However, options are not documented for the server start command: https://openliberty.io/docs/ref/command/#server-start.html

Document the options for the server start command.

Additionally, make an update on the --clean option for annotation cache data. The information to document is found in the following issue, which is for APSFOUND-1. APSFOUND-1 is going out in 19.0.0.12: https://github.com/OpenLiberty/docs/issues/787

**Comment by lauracowen** [comment]
@chirp1 Thx.

Can you specify which `server start` options are missing from https://openliberty.io/docs/ref/command/#server-start.html ?

For the `--clean` option on the annotation cache data, do you mean as documented here: https://openliberty.io/docs/ref/command/#server-stop.html ?

**Comment by Charlotte-Holt** [comment]
@NottyCode I moved the `--clean` option to the server start command. Please review the updated commands at:
* https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-start.html
* https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-stop.html

**Comment by Charlotte-Holt** [comment]
This is live at https://openliberty.io/docs/ref/command/#server-stop.html and https://openliberty.io/docs/ref/command/#server-start.html. Closing this issue.
