### ISSUE TITLE
Internal editorial review text in server pause documentation

### ISSUE THREAD

**Issue by kinueng** [OpenLiberty/docs#79]
Is this text suppose to be in the documentation for `server pause` command?

```
NOTE: LC: Can the types be combined in a single command? If so, we should mention it in the descriptions above and give an example in Usage below.
```

See file:
https://github.com/OpenLiberty/docs/blob/master/ref/commands/server/server-pause.adoc

**Comment by lauracowen** [comment]
I've just done a PR to comment it out so it doesn't look bad. There is actually another similar question in the source (but commented out). Before we close this issue, I think the actual problem should be addressed: Have the questions been answered in the topic? If they have, remove the commented out notes from the source. If not, can we update the topics as necessary?

**Comment by bsbyrd1** [comment]
@cbridgha Could you give this topic a review to determine whether this comment is relevant:
Can the types be combined in a single command? If so, we should mention it in the descriptions above and give an example in Usage below.

https://github.com/OpenLiberty/docs/blob/master/ref/commands/server/server-pause.adoc

**Comment by cbridgha** [comment]
What isn't very clear is the usage examples that have been merged into one section at the top, but the example config that helps explain the options (for example pausing specific httpEndpoint elements) are buried in the options doc at the bottom, which isn't obvious why its there at all?

**Comment by Charlotte-Holt** [comment]
@cbridgha I'm currently working on making the updates that we discussed to the server commands. Just to follow up on this original question, though, is it possible to combine the types (message endpoints and HTTP endpoints) into a single command for `server pause`? If so, we could provide an example of this in the Usage section.

**Comment by Charlotte-Holt** [comment]
@cbridgha confirmed that it is possible to combine the types (message endpoints and HTTP endpoints) into a single command for `server pause`. Example at https://developer.ibm.com/wasdev/blog/2018/03/16/endpoints-liberty-mbeans-part2/#controlling-the-state-of-endpoints-at-runtime. @lauracowen maybe we should include an example of this in "Usage examples"?

**Comment by Charlotte-Holt** [comment]
@lauracowen I updated the 'Usage examples' section of `server pause` to include an example that combines the types (message endpoints and HTTP endpoints) into a single command: https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-pause.html. I went ahead and updated the 'Usage examples' section of `server resume` to include an example of this as well: https://draft-openlibertyio.mybluemix.net/docs/ref/command/#server-resume.html. @cbridgha Can you review these two commands for technical accuracy and let me know if any changes are needed? (I gathered my info from https://developer.ibm.com/wasdev/blog/2018/03/16/endpoints-liberty-mbeans-part2/#controlling-the-state-of-endpoints-at-runtime, but I altered the examples to incorporate endpoints from previous examples in both topics.)

**Comment by cbridgha** [comment]
@Charlotte-Holt Sorry for the delay - these examples look good! - much clearer than before.

**Comment by Charlotte-Holt** [comment]
Examples published to: 

- https://openliberty.io/docs/ref/command/#server-pause.html
- https://openliberty.io/docs/ref/command/#server-resume.html

Closing this issue.
