### ISSUE TITLE
Update MicroProfile Intro document to cover the latest

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/docs#80]
We need to update the MP Intro document to include JSON-B i.e. update it to reflect the latest in MP 2.x.  The REST foundation layer should be updated to include JSON-B in the picture.

**Comment by yeekangc** [comment]
@bsbyrd1, please let us know who is best to look at this.

**Comment by lauracowen** [comment]
Also add edits from Dan: https://ibm.box.com/s/eaeuvpt16u9n0suz79zrb0z31kxvk6k0

**Comment by yeekangc** [comment]
This document is on an island of its own at the moment.  We should link to it or expose it somehow.

**Comment by lauracowen** [comment]
There is a link to it from the Guides page but I agree, I think it should be linked from the Docs section at some point.

**Comment by lauracowen** [comment]
Part of the edits I've planned with Dan were because I'm going to produce a shorter version as a blog post (which will link to the longer topic) to promote the guides.

**Comment by lauracowen** [comment]
Also add new version of the graphic (ask Laura).

**Comment by lauracowen** [comment]
Raising priority and assigning to me because some of the blog post work with marketing has a dependency on this being done. I removed milestone so it doesn't come up in the general docs work.

**Comment by lauracowen** [comment]
[eclipse-microprofile-components.pptx](https://github.com/OpenLiberty/docs/files/3039047/eclipse-microprofile-components.pptx)

(attached Dan's updated diagram source file)

**Comment by lauracowen** [comment]
![eclipse-microprofile-components](https://user-images.githubusercontent.com/3322532/55485625-b5c56480-5622-11e9-95c3-d3c67de3a118.png)
[eclipse-microprofile-components.pptx](https://github.com/OpenLiberty/docs/files/3039064/eclipse-microprofile-components.pptx)

(source and exported PNG from Dan's updated diagram of MP features)

**Comment by lauracowen** [comment]
Made some of the updates, inc the new diagram. Not made all the editorial changes proposed in discussion with Dan as I ran out of time. Will create a new issue for those improvements.

**Comment by lauracowen** [comment]
Merged to `master` to publish live here: https://github.com/OpenLiberty/docs/pull/188

(Also moved to a `concept` sub-folder instead of `intros` but left the permalink as-is for now so users won't see any difference in URL for now.)

**Comment by lauracowen** [comment]
https://openliberty.io/docs/intro/microprofile.html
