### ISSUE TITLE
Review comments on Building Resilient microservices

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/docs#807]
Can you add a section on how to use these annotations to solve a real time case such as a time critical situation. In this case, you will use Asynchronous Timeout Fallback etc. Please add some usage on using CompletionStage

Once you have got a CompletionStage, what do you do with it? Obviously you will chain it up and get the result. 

You then explain what happens if the completionstage completed with an error or cancelled etc.

**Comment by dmuelle** [comment]
copying this comment into the parent issue at #336
