### ISSUE TITLE
Write guidance for linking guides to relevant OL doc topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#81]
We need the guides to link to the docs that support them.

We have:

- Docs we're writing, specifically (at the moment) concept docs to support the guides (eg JSON-B/JSON-P concepts to support the https://www.openliberty.io/guides/rest-client-java.html guide.

- Generated docs, eg Javadocs for the annotations (in particular) that are used in the guide sample apps; server config doc (not relevant to most of our guides except the Deploying guide).

In both cases, the developer reading the guide (and/or trying to write their own app based on the guide) needs to be able to find this information. But without being swamped with loads of links (or they won't know which ones to click). The links need to be labelled clearly so that they know what they will find (so they can decide whether it's worth clicking it).

We need some simple guidance about what to include as links, what level should be linked to, where the links should be. For instance, I think the guide design includes links to suggested other guides at the bottom. Should there be a sidebar of related links? Or some other pattern? Or just links within the text as appropriate (and what style should that take?)?

**Comment by bsbyrd1** [comment]
Having a single-source linking strategy would help us long term to manage links between guides and reference doc.

**Comment by Charlotte-Holt** [comment]
General linking guidance at https://ibm.box.com/s/ww5eybttrnioz53wvl9c2mztvzobqmse. This was discussed with the ID team. Closing this issue.

**Comment by Charlotte-Holt** [comment]
Working doc at https://ibm.ent.box.com/notes/598350624712?s=v6mq12hcpcd9h37pgc6qddjgkujjr8i4.

**Comment by dmuelle** [comment]
superseded by #276
