### ISSUE TITLE
server package command page isn't rendering properly

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#82]
https://openliberty.io/docs/ref/command/server-package.html

The stylesheet isn't applied properly. Also, it's not appearing in the ToC:

![image](https://user-images.githubusercontent.com/3322532/49603784-18b03300-f984-11e8-8cc6-e36b8fcbfeb2.png)

(I haven't checked but I guess there might be others the same?)

I'm linking to the `server package` command page from 18004 blog post.

**Comment by steven1046** [comment]
This will be fixed once we merge develop->master

**Comment by steven1046** [comment]
There was a blank line in the server package adoc.

**Comment by steven1046** [comment]
https://openliberty.io/docs/ref/command/#server-package.html

**Comment by kinueng** [comment]
fixed
