### ISSUE TITLE
Finding the supported Javas & APIs for Open Liberty is too hard

### ISSUE THREAD

**Issue by barecode** [OpenLiberty/docs#840]
Finding the versions of Java that Open Liberty supports, and the versions of Java EE, Jakarta EE and MicroProfile that it supports is not obvious. Today, to find the supported Java SE versions,  you need to drill down into this page: https://openliberty.io/docs/ref/general/#java-se.html (thanks @aguibert for showing me where this was, I could _not_ find it).

Similarly, if you want to find the supported Java EE / MicroProfile verisons, you have to look at the API Reference Doc (e.g. https://openliberty.io/docs/ref/javaee/8/) ... and thanks again to @aguibert for pointing me there.

What I think would make sense is some sort of suported technology matrix (or something) that shows what Open Liberty supports. Since OL is a single code stream this table from Tomcat isn't exactly the right model, but what this table does do is tell me, very clearly, what levels of what things are supported:
http://tomcat.apache.org/whichversion.html

**Comment by NottyCode** [comment]
With the new antora documentation the Java SE support doc is much easier to find. No hunting necessary. Can you take a look at the new docs to see if it helps to resolve your concern around hunting through docs.

**Comment by barecode** [comment]
Thanks for getting to this! :) Since its been a while since I raised this, I took a fresh look at the site.

Some of the technologies Liberty ships (MicroProfiel, etc) listed on the home page is good, and the packaging listed under Downloads helps too. The new Java SE technologies page (https://openliberty.io/docs/20.0.0.10/java-se.html) is really nice and obvious to find given the new left-hand nav.

I looked over the rest of the doc too, and the only thing that confused me was when I clicked on "API documentation" under the Development category, I was expecting to see API Reference docs (which I later found in the Reference section). I would suggest that "Documenting your APIs" is a better headline than "API documentation", but its minor so I won't open a new issue for that.

@mbroz2 I think this is good to close. Please note my observation about the "API documentation" title in the nav, and proceed as you see fit :)

**Comment by mbroz2** [comment]
I agree that API Documentation in the docs section can be confusing to someone.  I think "Documenting APIs" would be clearer and I'll raise an issue for the docs team
