### ISSUE TITLE
HTTP Forwarded header support

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#88]
https://github.ibm.com/was-liberty/liberty-docs/issues/916

I think this will probably make it into 19.0.0.1. It's already in development builds and was mentioned in a blog post this week (a shorter version than the doc proposed in the issue above): https://openliberty.io/blog/2018/12/20/http-forwarded-header.html

**Comment by ebreijo** [comment]
Hi @Rwalls1, here are my comments:

1. There is a typo in the following sentence: 
Original
If you’ve written an app that requires login, it’s important to think about how to prevent fradulent access logins. Identify the IP address, and that **peice** of data can help track the clients where invalid logins originate.
Updated
If you’ve written an app that requires login, it’s important to think about how to prevent fradulent access logins. Identify the IP address, and that **piece** of data can help track the clients where invalid logins originate.

2. Add "de facto" to the following sentence:
Original
The Forwarded and X-Forwarded-* header support in Open Liberty is the implementation of the Forwarded header spec RFC 7239 and the standard X-Forwarded-* header.
Updated
The Forwarded and X-Forwarded-* header support in Open Liberty is the implementation of the Forwarded header spec RFC 7239 and the **de facto** standard X-Forwarded-* header.

3. Change "a" to "the" in the following sentence:
Original
These headers can be used by intermediaries and origin servers to reveal a topology of the network that was involved for a specific request.
Updated
These headers can be used by intermediaries and origin servers to reveal **the** topology of the network that was involved for a specific request.

4. Update the following sentence:
Original
The NCSA Access Log records the information of the connected remote TCP connection only.
Updated
**Under this scenario,** the NCSA Access Log records the information of the connected remote TCP connection only.

**Comment by Rwalls1** [comment]
@ebreijo Please review for the latest update: https://github.com/OpenLiberty/docs/blob/develop/ref/rol_xheader.adoc

**Comment by lauracowen** [comment]
Has this been published? Can you paste the link to the topic here, pls?

**Comment by kinueng** [comment]
@lauracowen 
https://openliberty.io/docs/ref/general/#forwarded-header.html
