### ISSUE TITLE
Example config for appSecurity feature

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#894]
From LC: Provide example config for:

1. basic auth from https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_basicreg_full.html or from the **Securing a web application** guide (https://openliberty.io/guides/security-intro.html) if a better example
2. QuickStart security (from Steps 2, 3, and 5 of https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_quickstart.html) - find out whether the deployment descriptor bit (Step 4) is relevant when using Maven - assume the Maven approach, not the server-centric approach (so don't include the information from Step 1)
3. LTPA config https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_sec_ltpa.html (check to be sure that it's for this feature)

**Comment by Rwalls1** [comment]
Link to current draft: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#appSecurity-3.0.html

**Comment by Rwalls1** [comment]
@areddy Please review:  https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#appSecurity-3.0.html

**Comment by lauracowen** [comment]
Looks great.

- Typo: "to authenticate and authorize users with by using a basic user registry." (with/by?)
- can you highlight `server.xml` in backticks/monospace.

Otherwise, this is ready to go, thanks.

**Comment by Rwalls1** [comment]
@lauracowen Please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#appSecurity-3.0.html

**Comment by lauracowen** [comment]
Ok, that looks ready to go, thanks.

**Comment by dmuelle** [comment]
## Peer review
I think this looks good overall. Just a few things to address

- For both the Basic Registry  and Quickstart sections, it's important to note that basic registries are intended for dev/test purposes and are generally not considered to be secure enough for production environments. For example, in the Basic Registry topic, it says
`Although this registry is not secure enough for production environments, it can help simplify authentication and authorization scenarios during development and testing.`
This is info a user should know before setting up the registry. Check [the basic registry topic](https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-user-registries-application-development.html) for more info.
- For the quickstart section, the description makes it sound like this is something you would do _in addition to_ configuring a basic registry. Adding this element automatically configures a basic registry with only one user, who is in the admin role. This is just for testing purposes and it does not enable user groups. It's just a quick way for a dev to set up a registry if they need an admin for testing purposes or to enable another feature (such restConnector) that requires an admin. See the quickStart section of the Basic registry topic for more info.
- Remove passive voice and avoid "perform":
`The basic user registry contains user account details that are used by applications to perform security-related tasks.`
could be
`The basic user registry contains user credentials that applications need for security-related tasks.`

**Comment by Rwalls1** [comment]
@dmuelle Thank you, I've addressed your feedback, I decided to leave out the notice about dev/test purposes since it is already mentioned in the Basic Registry topic that I have linked to in the Basic Registry and Quickstart sections. I wanted to avoid being redundant with that topic and also wanted to maintain a concise focus on the config descriptions.

**Comment by Rwalls1** [comment]
New link to topic: https://draft-openlibertyio.mybluemix.net/docs/20.0.0.9/reference/feature/appSecurity-3.0.html

**Comment by Rwalls1** [comment]
PR: https://github.com/OpenLiberty/docs/pull/1747/files

**Comment by dmuelle** [comment]
published at https://openliberty.io/docs/20.0.0.11/reference/feature/appSecurity-3.0.html

**Comment by chirp1** [comment]
Hi Richard,
You put together a nice set of examples for the topic. I have a few comments:
- For "For more information, see Basic user registries for application development. ", the link is broken for me.  t I think that the link is supposed to be to https://openliberty.io/docs/20.0.0.11/user-registries-application-security.html.. If you add that Quickstart is intended for test purposes (see next bullet), I don't think you need this link as there isn't much difference between your QuickStart section and the QuickStart section at the link.
- For "QuickStart security configuration", indicate that QuickStart is intended for test purposes, which is indicated at https://openliberty.io/docs/20.0.0.11/user-registries-application-security.html.. 
- When you use on first occurrence, "Trust Association Interceptors (TAI) " make it and the sentence that it is in singular.
- For "The following example shows how to disable LTPA cookies ...", explain why one would disable LTPA cookies for TAI. To me, the two sentences preceding this one don't seem to explain why one would disable LTPA cookies for TAI.
- Look over your topic for long noun phrases like the section title "Administrative REST API access role configuration". Rework the title and other noun phrases. For guidance, see "Ambiguous noun phrases" in the IBM quality guide at https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch06.html#ch06lev1sec5 and any other info that you on the subject that is appropriate. 
- Also, add at least two quality guide references as I don't see any in your issue. You can use the "Ambiguous noun phrases" section as one of them. Have at least one on clarity or concreteness.

**Comment by Rwalls1** [comment]
Editing references: https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch06.html
                                 https://learning.oreilly.com/library/view/developing-quality-technical/9780133119046/ch07.html

**Comment by Rwalls1** [comment]
New topic link: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.1/reference/feature/appSecurity-3.0.html

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I have addressed your feedback.

**Comment by chirp1** [comment]
Hi Richard, 
The updates looks good! I have a few more comments:
- For " specifying disableLtpaCookie with", put a noun after "disableLtpaCookie".
- QuickStart and what it is used for: Above I commented "....indicate that QuickStart is intended for test purposes, which is indicated at https://openliberty.io/docs/20.0.0.11/user-registries-application-security.html.". I see that you added "QuickStart security configuration is intended for test purposes.". Now that I'm looking further into the purpose of QuickStart, I found  that Laura said here to give an example of why would one use QuickStart: https://github.com/OpenLiberty/docs/issues/892. So, I'm wondering if we made the purpose of QuickStart too narrow. Maybe saying "intended for" is the main reason for the feature and so the wording is OK, or maybe it has other purposes that we don't know about. I see here that Jesse Van Hill gave info about quikstart: https://github.com/OpenLiberty/docs/issues/1784. So, you could ask him. You could possibly just change the "QuickStart security configuration is intended for test purposes." wording slightly to something like "You can use the QuickStart security configuration for test purposes, for example." and work your wording into the section.
- At this URL https://www.ibm.com/docs/en/was-liberty/base?topic=administering-liberty it seems that defaults are not configured/do not have statements in the server.xml file. So, I found the following wording confusing, possibly saying that the satement is already in the server.xml file: "The following example shows the configuration of the ltpa element in the server.xml file:". Would you reword the text to make the meaning clearer - that if the user wanted to change the default, that they would use syntax similar to the example syntax that you provided? 
- For the "Configure REST API management roles", highlight values like Bob, etc.

**Comment by Rwalls1** [comment]
@chirp1 Thanks, I've addressed your feedback: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.8/reference/feature/appSecurity-3.0.html

**Comment by chirp1** [comment]
Hi Richard,
- For "The following example shows a sample default configuration of the ltpa element in the server.xml file:", how about something like "You can override the default settings for the ltpa element by configuring the ltpa element in the server.xml file. The following examples shows how to configure the ltpa element.".

**Comment by Rwalls1** [comment]
@chirp1 Thanks, please review the latest update: https://draft-openlibertyio.mybluemix.net/docs/21.0.0.8/reference/feature/appSecurity-3.0.html

**Comment by chirp1** [comment]
Looks good. Moving to Ready to Publish.

**Comment by Rwalls1** [comment]
Staging: https://staging-openlibertyio.mybluemix.net/docs/21.0.0.8/reference/feature/appSecurity-3.0.html

**Comment by Rwalls1** [comment]
Updates have been merged to Vnext and will publish with the 21.0.0.8 release.
