### ISSUE TITLE
20.0.0.1 RH updates

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#900]
Update for the 20.0.0.1 release:
- Release notes:
    - Git URLs
    - Release blog post URL
- Update doc version from 2019 -> 2020

**Comment by dmuelle** [comment]
https://github.com/PurpleLiberty/docs/pull/18

update release notes URLs for 20.0.0.1 (except for Features blog post, URL will update upon release)

update `productnumber` and trademarks from 2019 to 2020

**Comment by dmuelle** [comment]
doc is published at https://access.redhat.com/documentation/en-us/open_liberty/2020/
