### ISSUE TITLE
Exit Codes and Server Process includes not all relevant to the server command topics

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#92]
Need a tech review and then probably a selective include of the relevant bits of info in each topic.

cc @NottyCode

**Comment by bsbyrd1** [comment]
@cbridgha Hi Chuck! Can you give the server command topics a quick review? Here's a link to those topics in the repo: https://github.com/OpenLiberty/docs/tree/develop/ref/commands/server

**Comment by bsbyrd1** [comment]
@cbridgha Set up meeting to discuss the best way to tackle this review. Thanks for your help!

**Comment by cbridgha** [comment]
Hi - taking a look this morning - the question regarding the exit code doc....  I agree right now it doesn't add much value being so generic - we could provide exit codes for each command?

The class that defines these is here:  https://github.com/OpenLiberty/open-liberty/blob/integration/dev/com.ibm.ws.kernel.boot.core/src/com/ibm/ws/kernel/boot/ReturnCode.java

Also - the "server process" doc - is really just describing the server environment the process runs in, the default values, and how to override.  This could be better explained.

**Comment by Charlotte-Holt** [comment]
@lauracowen @NottyCode I broke out the exit codes per server command based on Alasdair's feedback and put that information into a Word document (attached here) for review. I figured this would be easier to look over before I start incorporating all these changes into git. Let me know if more changes need to be made to this doc. 

Also, per the comment from @cbridgha above, what changes should be made to the Server process section? It seems like some of the information contained in it references information contained in the Server config overview topic. Would it make more sense to pull the Server process section out of every server command, house it under Server config, and link to it from each server command under See also? 
[Exit Codes Sections.docx](https://github.com/OpenLiberty/docs/files/3178879/Exit.Codes.Sections.docx)

**Comment by lauracowen** [comment]
Good work on piecing together the exit codes! You'll need @cbridgha (or someone he suggests) to review it for accuracy.

Server process section - I agree it's not well explained. I think it should be removed from these topics.

**Comment by Charlotte-Holt** [comment]
@lauracowen @NottyCode @cbridgha I've updated the 'Exit codes' sections for each server command, and I removed the 'Server process' section from all of them. Please review the changes at https://draft-openlibertyio.mybluemix.net/docs/ref/command/, and let me know if further updates are needed. Also, we may want to create a separate issue for handling the 'Server process' section until I rework it and we figure out exactly what we want to do with it. Let me know. Thanks!

**Comment by Charlotte-Holt** [comment]
@NottyCode @lauracowen @cbridgha The 'Server process properties' section has now been updated and is ready for review: https://draft-openlibertyio.mybluemix.net/docs/ref/command/. Let me know what further changes may need to be made. Thanks!

**Comment by NottyCode** [comment]
I don't think you need to document the exit codes for server help. That will only ever be run by a human. I think server list is the same.

**Comment by Charlotte-Holt** [comment]
@NottyCode Okay, I removed the exit codes from `help` and `list`.

**Comment by NottyCode** [comment]
cool, looks much better to me. Thanks

**Comment by Charlotte-Holt** [comment]
Updates made to exit code and server process sections. Published at: 

- https://openliberty.io/docs/ref/command/#server-create.html
- https://openliberty.io/docs/ref/command/#server-debug.html
- https://openliberty.io/docs/ref/command/#server-dump.html
- https://openliberty.io/docs/ref/command/#server-help.html
- https://openliberty.io/docs/ref/command/#server-javadump.html
- https://openliberty.io/docs/ref/command/#server-list.html
- https://openliberty.io/docs/ref/command/#server-package.html
- https://openliberty.io/docs/ref/command/#server-pause.html
- https://openliberty.io/docs/ref/command/#server-resume.html
- https://openliberty.io/docs/ref/command/#server-run.html
- https://openliberty.io/docs/ref/command/#server-start.html
- https://openliberty.io/docs/ref/command/#server-stop.html
- https://openliberty.io/docs/ref/command/#server-version.html

Closing this issue!
