### ISSUE TITLE
SSO configuration with SPNEGO

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#928]
From LC:  Serialises Windows login to use in the browser. Use the KC topics, but give a more thorough introduction:
- Include what SPNEGO provides - don't dive straight in with how it works and initializes requests, etc. (provide a clear definition upfront)
- The step-by-step process and diagrams seem okay - check whether they need updating for a microservices scenario

The SPNEGO topic in KC talks about "Kerberos realms" then puts "(domains)" in parentheses - check to see whether "domains" is the more commonly used term. If so, why aren't we using it? Explain the difference between a "single Kerberos realm" and a "trusted Kerberos realm", if they're both still relevant, so the user can understand which they're dealing with and why you would use one over the other. 

Config examples w/ #954 

**Scenario 1**:  This topic needs to be written for a developer writing cloud-native apps that will be containerized and deployed to the cloud.

**Resources**:
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/cwlp_spnego.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_spnego_config.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_config_kerb_constrained_del.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_using_kerb_principal_name_auth.html

**Comment by Rwalls1** [comment]
#1210

**Comment by Rwalls1** [comment]
@utle Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html

**Comment by utle** [comment]
Comments for 
https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html
This sentence is not quite right. 
`The KDC is stored in the Microsoft Active Directory`

In general, we support all KDCs (MS KDC, RedHat KDC, zOS KDC, MIT KDC, AIX KDC ...etc) but majority of customers are using the MS KDC.
If we are talking about the MS KDC, then it should be something likes 
`The Key Distribution Center (KDC) is implemented as a domain service. It uses the Active Directory as its account database  `

**Comment by Rwalls1** [comment]
@utle I've made the update you requested: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html

**Comment by Rwalls1** [comment]
@lauracowen Please review: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html

**Comment by utle** [comment]
developer approved

**Comment by Rwalls1** [comment]
@NottyCode Please review:  https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html

**Comment by NottyCode** [comment]
I don't think we need to document how SPNEGO works at a protocol level. I don't think anyone using Liberty would care about this and I'm pretty sure there are better places to find that documentation. I think what is important is the following:

1. What use cases is SPNEGO relevant for
2. How do I configure it

neither of which are answered here. In my understanding the main usage scenario for SPNEGO is for single sign on from a windows AD domain to a web application. I.e. user logs into windows desktop, they then navigate to the web app and they don't get prompted to log in.

I think we can simplify this documentation quite a bit.

**Comment by Rwalls1** [comment]
@lauracowen Please review, what are your thoughts on Alasdair's comments: https://draft-openlibertyio.mybluemix.net/docs/ref/general/#sso-config-spnego.html

**Comment by lauracowen** [comment]
Hi Richard,

Alasdair and I took a look at some of the SSO topics last night and we agreed we need to make some changes to how the SSO info is presented. We currently have too much info about the abstract concepts that people could better obtain elsewhere. I'm going to chat with Charlotte about it this afternoon but please can you hold off working on this topic in the meantime?

Thanks,

Laura

**Comment by lauracowen** [comment]
Superceded by #1676 so I'm closing this issue.
