### ISSUE TITLE
Improve process for quality tech reviews

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#93]
ID and engineering need to work together to ensure quality (accuracy and relevance, in particular) of the docs. The current process is not working well enough to catch problems.

For example, see #92 and #91.

**Comment by lauracowen** [comment]
@bsbyrd1 got some feedback from AndyG (our discussion is nested):
* Good having doc source in GitHub because can easily give PR updates.
* Not so good having yet another repo to track and suggested moving doc source into main OL source code repo so that code and docs are together.
** However, not usual practice to keep docs content and code in same repo; not even that usual to have a monolithic code repo.
** Docs are built as part of website and even website infrastructure is held in separate repo for maintenance reasons (similar to Blogs repo).
** Would be difficult to maintain doc issues if in with the main code issues.
** None of these are absolute problems but don't think combining repos would be best solution. However, we recognise the general problem and should look for other ways to make easier (maybe need to understand the specific problems experienced in having multiple repos in the context of doc reviews).

**Comment by bsbyrd1** [comment]
@chirp1 Let's work together on this one to solidify the process that you'd like to propose for the team.

**Comment by lauracowen** [comment]
Explore guides review process as that seems to be working.

**Comment by chirp1** [comment]
ok

**Comment by lauracowen** [comment]
What we're doing seems to be working at the moment. We can return to this in future if we hit specific problems.
