### ISSUE TITLE
Configuring Open Liberty as an SSO provider in a dev/test environment

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#940]
From LC:  OIDC provider docs should be written as they relate to developers - in production (in the cloud) would use external provider like Red Hat SSO (keycloak), so it's not necessary to document (as high priority) how to set up OIDC providers for production systems - in the cloud that's done for you (it's the client/social login side that matters more now). 

**Scenario 1**: This topic needs to be written for a developer writing cloud-native apps that will be containerized and deployed to the cloud.

**Resources**:
- https://developer.ibm.com/wasdev/docs/configuring-an-http-server-to-use-liberty-as-openid-connect-provider/
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_config_oidc_pc_examp_beginner.html 
- https://www.ibm.com/support/knowledgecenter/SSD28V_liberty/com.ibm.websphere.wlp.core.doc/ae/twlp_config_oidc_op.html

**Comment by Charlotte-Holt** [comment]
Peer review feedback: 

- Use the generalized feature name when possible
- I don't think "Request" needs to be capitalized in "HTTP Request header"
- In the sentence "You can configure an Open Liberty server to act as an OpenID Connect Provider by enabling the openidConnectServer-1.0 feature in Liberty.", I think you can remove "in Liberty"
- I don't think you need to show how to configure the features here. The feature overview topic does that. 
- For port 433, I think the port should be monospaced (i.e., `433`)
- Add a colon after 433 to lead into the example
- Add a colon after truststore to lead into the example

**Comment by lauracowen** [comment]
Thanks, Manasi.

I think the info you’ve written in the new topic should be moved into description and examples files for this generated feature topic: https://www.openliberty.io/docs/ref/feature/#openidConnectServer-1.0.html

To do that, in here: https://github.com/OpenLiberty/docs/tree/master/ref/feature:
 - Create a directory called openidConnectServer 
- Then in that directory, create a description.adoc file that contains the two intro paragraphs from your new topic (combined into one).
- Also in that directory, create an examples.adoc file that contains the info from the “Configuring Open Liberty as an SSO provider” section of your new topic.
- The intro to the example needs to be clear about it being for development and that when you go into production the app would be switched to using the cloud-provided provider such as (eg in the Red Hat cloud) Red Hat SSO (based on Keycloak) - I’m not certain about the terminology/naming here.
- The first two paras of the info in the "OpenID Connect" section of your new topic should be incorporated into David's Authentication topic as appropriate. And then to mention that OL can be set up as a provider for development purposes but that the app would use a cloud-hosted SSO provider when deployed.
- I don't think the bulleted list of benefits is relevant to this scenario. We're not arguing that people should be using OL as an OIDC provider in production. We're providing the capability to set it up as a provider for purposes of development environments but the app will be switched to using a cloud-hosted provider when deployed to production. @NottyCode Can you confirm/correct my understanding here, pls?

**Comment by NottyCode** [comment]
@Charlotte-Holt we souldn’t put punctuation marks after monospaced text because the style for the monospaced text adds an space after the text before the punctuation mark and it looks weird when reading. I guess perhaps this might suggest the style should be updated.

**Comment by NottyCode** [comment]
The Open id connect server feature can be used in production, and we do have people using it, but it isn’t a general purpose SSO solution which is typically what people use in production scenarios. As a result it is better suited to development and test scenarios because it reduces moving parts and makes test simpler.

**Comment by ManasiGandhi** [comment]
@lauracowen Worked on your comments.  
- [x]  Create a directory called openidConnectServer
- [x] Then in that directory, create a description.adoc file that contains the two intro paragraphs from your new topic (combined into one).
- [x] Also in that directory, create an examples.adoc file that contains the info from the “Configuring Open Liberty as an SSO provider” section of your new topic.
- [x]  The intro to the example needs to be clear about it being for development and that when you go into production the app would be switched to using the cloud-provided provider such as (eg in the Red Hat cloud) Red Hat SSO (based on Keycloak) - I’m not certain about the terminology/naming here.
- [x] The first two paras of the info in the "OpenID Connect" section of your new topic should be incorporated into David's Authentication topic as appropriate. And then to mention that OL can be set up as a provider for development purposes but that the app would use a cloud-hosted SSO provider when deployed. (**forwarded your message to David**)
- [x] I don't think the bulleted list of benefits is relevant to this scenario. We're not arguing that people should be using OL as an OIDC provider in production. We're providing the capability to set it up as a provider for purposes of development environments but the app will be switched to using a cloud-hosted provider when deployed to production. @NottyCode Can you confirm/correct my understanding here, pls? (**removed the bulleted list**)

**Comment by lauracowen** [comment]
I haven’t read the text yet (I’ll review it properly when it’s built to draft) but can you add some formatting to the examples.adoc file (eg headings and code snippets) similar to https://raw.githubusercontent.com/OpenLiberty/docs/master/ref/feature/socialLogin/examples.adoc

**Comment by lauracowen** [comment]
As the work from this issue has moved into the ODIC server config #676 issue, can you delete the original file that you created for this issue and close this issue, please? We can track the work on the config examples in the config examples issue.
