### ISSUE TITLE
Create topic: Java versions supported in Open Liberty

### ISSUE THREAD

**Issue by bsbyrd1** [OpenLiberty/docs#95]
Create new content about Java 11 support in Open Liberty, based on updates from the following liberty-docs issue: https://github.ibm.com/was-liberty/liberty-docs/issues/829

The updates from the previous issue are made in KC. However, for new content, we can publish that content to openliberty.io and link from KC. For example, we need new content about how to enable the kill switch when starting the JVM. That content can be published in the following draft topic (specifically see the Usage section for that content):
https://github.com/OpenLiberty/docs/blob/develop/ref/rol_Java11.adoc

**Comment by bsbyrd1** [comment]
The current topic will become a topic titled, "Java versions supported in Liberty"

We'll document support for Java SE 8 and Java SE 11. See the following topic for a description of the Java SE 8 runtime environment section: https://www.ibm.com/support/knowledgecenter/en/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/rwlp_restrict.html

**Comment by bsbyrd1** [comment]
Here's a link to the topic that needs to be updated: https://github.com/OpenLiberty/docs/blob/develop/ref/rol_Java11.adoc

**Comment by Rwalls1** [comment]
@bsbyrd1 Here's the link to PR for you to review: https://github.com/OpenLiberty/docs/pull/100

**Comment by Rwalls1** [comment]
@aguibert I have updated the Java versions Open Liberty page with info gathered from your blog and the KC restrictions page: https://github.com/OpenLiberty/docs/blob/develop/ref/rol_Java11.adoc . Please review the update and feel free to go in and make changes to the code yourself.

**Comment by aguibert** [comment]
@Rwalls1 it is important for us to state that not all distributions and versions of Java 11 are supported (yet). In the OpenLiberty blog post, we have this important sentence:

> Currently Open Liberty supports Java 11.0.2 (or newer) on the OpenJ9 VM. Other Java VMs, such as Hotspot, are not supported due to some outstanding VM bugs.

Other than that, looks great!

**Comment by Rwalls1** [comment]
@aguibert The topic has been updated to reflect your latest comment: https://github.com/OpenLiberty/docs/blob/develop/ref/rol_Java11.adoc

**Comment by aguibert** [comment]
looks good, thanks!

**Comment by lauracowen** [comment]
Has this been published? Can you paste the link to the topic here, pls?

**Comment by kinueng** [comment]
@lauracowen 
https://openliberty.io/docs/ref/general/#java-se.html
