### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by Charlotte-Holt** [OpenLiberty/docs#962]
From Laura on LDAP - I think the focus is on enterprises that have LDAP user registries already set up (eg like IBM has Bluepages) that they want to use with their app instead of creating their own user registry or using a social media provider. See what he can do with what’s already in the KC on that basis. Also, worth taking a look at the social login feature’s example config on the draft docs build (the topic Bruce worked on; it’s not published yet so only on draft server) because there’s an example in there of using a social media provider as your user registry (eg users can log in with their Facebook IDs) but limiting which users can log in with the social media provider to only users who also appear in the company’s LDAP registry (I think - something like that). I think the reason for doing that is for usability for the end-user of the app (they just use their social media login details instead of having to remember a whole different set), but the company prevents anyone outside their employees, say, from logging in. This is aimed at developers still, btw - writing an app that uses LDAP.

**Comment by dmuelle** [comment]
@lauracowen draft now available for review at 

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#LDAP-registry.html

**Comment by dmuelle** [comment]
current draft incorporates SME review edits requested by @jvanhill via Slack discussion via #1012 (details in PR comments)

**Comment by lauracowen** [comment]
- Can you move the configuration section from this topic to the LDAP Registry feature config examples instead (replace the simple config example that's there already if this one's better). Then link to the feature topic for how to configure. Avoid putting configuration info into these concept topics and direct them to the feature topic instead.
- Maybe also move the certificate map mode config example out to the LDAP Registry feature as well. Also, is the ampersand correct to display as `&amp;` code in this code snippet? Or should it render as `&`?

Otherwise, looks great, thanks.

**Comment by lauracowen** [comment]
Looks good, thanks.

**Comment by dmuelle** [comment]
Requesting full peer review from @Charlotte-Holt

**Comment by Charlotte-Holt** [comment]
# Peer review feedback
## Intro

- In "Many kinds of LDAP servers exist, such as the IBM Security Directory Server and the Microsoft Active Directory. Open source LDAP servers are also available, such as OpenLDAP and ApacheDS.", there's only a link to the IBM Security Directory Server, and it goes to the KC. It might be okay to link to the KC in this context since it's not the Liberty product, but I think if we link to more info about one of these options, we should link to them all for the sake of product agnosticism. 

## Global

- You have link text that reads "Federated User Registry" and link text that reads "Social Media Login feature". I'd make it consistent whether you include "feature" in the link text or not. 
- I know this is a bigger question that we're still working out, but I'd consider adding bullets to the See also section. I think most of the topics have a bulleted list under **See also** even when information in each bullet is sentence-structured.

**Comment by dmuelle** [comment]
Edits addressed in #1442:

- remove link to IBM directory server
- edit link text to include "feature"
- add bullets to See Also

**Comment by jvanhill** [comment]
The only real issue i see is that when I click on links, several of them fail. If that is expected then it is fine and you can take this comment to reflect my approval.

**Comment by dmuelle** [comment]
@jvanhill yes- we had some file names change recently so I need to update the links. Sorry should've done so before contacting you but I'll fix them now.

**Comment by dmuelle** [comment]
links fixed in #1466

**Comment by jvanhill** [comment]
Developer approved.

**Comment by chirp1** [comment]
Hi David, I read the short description and saw some issues with it. Would you and Charlotte read and study the short description literature and rework the short description? Also, check over the rest of your topic as needed. I'll review the topic after you make further updates.

**Comment by dmuelle** [comment]
Short description revised per guidance in #1485

**Comment by dmuelle** [comment]
This content was moved into a single topic for User registries, tracked in https://github.com/OpenLiberty/docs/issues/1784
Removed this draft from draft site
Closing this issue
