### ISSUE TITLE
Make file names consistently use hyphens instead of underscores or spaces

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#976]
We currently have a mixture of file naming practices (sometimes underscores (`_`), sometimes spaces. We need to fix this to make it consistently hyphens (`-`) between words in a file name (and fix any references in other topics to affected files). Hyphens are used on the rest of the OL.io website. Also, make sure they're all lower-case (not capital letters in file names).

Should be done sooner rather than later so that there are fewer references to the old filename for topics that get changed.

**Comment by Charlotte-Holt** [comment]
This fix will be covered by the fixes outlined in #1743
