### ISSUE TITLE
Review feedback for JSON-B/JSON-P topic

### ISSUE THREAD

**Issue by lauracowen** [OpenLiberty/docs#99]
#35 

From Alasdair:

I know the "Why JSON-B is better than JSON-P" section is yet to be SME-reviewed but @NottyCode  gave some feedback I forgot to pass on to you last week that might be relevant when discussing with the SME.

It would be better if the section identified when to use JSON-B and when to use JSON-P, rather than saying one is always better than the other. Both APIs are provided and both have strengths with particular use cases.

**Comment by lauracowen** [comment]
Additional feedback in discussion with Alasdair:

This topic should actually be split into two and describe JSON-B in one and JSON-P in the other. In the relevant topics, the benefits (and not benefits) of each should be described so that developers can decide which is the most relevant to them. Feel free to ping me (Wed to Fri) or Alasdair if you need more input. Thx

**Comment by dmuelle** [comment]
picking up this work in #35
