### ISSUE TITLE
Federating User registries

### ISSUE THREAD

**Issue by dmuelle** [OpenLiberty/docs#996]
per discussion w/ Ajay- move this info out of LDAP topic into separate topic

https://www.ibm.com/support/knowledgecenter/SSEQTP_liberty/com.ibm.websphere.wlp.doc/ae/cwlp_repository_federation.html

**Comment by dmuelle** [comment]
@lauracowen draft available for review at:

https://draft-openlibertyio.mybluemix.net/docs/ref/general/#federated-registries.html

**Comment by dmuelle** [comment]
current draft incorporates SME review edits requested by @jvanhill via Slack discussion via #1014 (details in PR comments)

**Comment by lauracowen** [comment]
Most of this is about configuration. Can you instead add the pertinent parts of thes config examples to the relevant features? (I'm guessing the ldapRegistry feature and the federatedRegistry feature?).

I don't have a problem with having a concept topic on federated registries but it doesn't seem like there's much/enough info to warrant it. Maybe instead each of the relevant other registry topics should mention that they can be federated and then point to the relevant autogen feature for examples of how to do it?

**Comment by lauracowen** [comment]
In the paragraph that starts "Although federation of LDAP registries occurs by default...", it implies that to use the `federatedRepository` element, you have to enable the federatedRegistry feature, which isn't explicitly enabled in the first code snippet. Does the ldapRegistry feature auto enable the federatedRegistry feature?

**Comment by jvanhill** [comment]
> Does the ldapRegistry feature auto enable the federatedRegistry feature?

Yes, the ldapRegistry-3.0 feature auto enables federatedRepository-1.0 feature.

**Comment by dmuelle** [comment]
@lauracowen 
Moving this  info out to LDAP and user registry topics, examples to LDAP and Federated registry features. Agree that there is not enough here to warrant a separate topic without config examples. Ok to dissolve this doc and close the issue?
 
- [https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#ldapRegistry-3.0.html](LDAP User Registry 3.0)
- [https://draft-openlibertyio.mybluemix.net/docs/ref/feature/#federatedRegistry-1.0.html](Federated User Registry 1.0)
- [https://draft-openlibertyio.mybluemix.net/docs/ref/general/#csec-LDAP-registry.html](LDAP user registries)
- [https://draft-openlibertyio.mybluemix.net/docs/ref/general/#basic-registry.html](Basic user registries for application development)

**Comment by lauracowen** [comment]
Yes. Thanks
